updated organization user role save method
openedx/course-discovery pull request #1005
Opened 2017-06-21 11:14 UTC by asadazam93

Educator-665

When a new user is assigned to a role in organization_user_roles via the publisher admin the courses_user_roles for that organization are also updated accordingly. i.e the new user role is assigned in all the courses for that organization.

2017-06-22 10:41 UTC, awais786 commented on course_discovery/apps/publisher/admin.py
> +        CourseUserRole.objects.filter(course__in=courses_with_role).update(user=obj.user)
Add role condition.

2017-07-04 10:31 UTC, waheedahmed requested changes

2017-07-04 10:31 UTC, waheedahmed commented on course_discovery/apps/publisher/admin.py
> +        for course_user_role in course_user_roles:
You can achieve this with single line instead of looping on queryset and saving every object individually and also no need for extra query at L58:
```
CourseUserRole.objects.filter(course__organizations__in=[obj.organization], role=obj.role).update(user=obj.user)
```

2017-07-04 11:02 UTC, waheedahmed approved these changes

2017-07-04 12:41 UTC, merged