Update django-contrib-comments
openedx/course-discovery pull request #1024
Opened 2017-06-26 11:00 UTC by vkaracic

Version 1.8.0 of django-contrib-comments moved away from
using the SITE_ID settings attribute in favor of supporting
multi-tenancy.

LEARNER-1583 + EDUCATOR-733

@edx/helio and @awais786 please review.

2017-06-26 12:27 UTC, clintonb requested changes
Test? The last time we merged this, it broke. How do we know the breakage has been addressed?

2017-06-27 11:38 UTC, vkaracic commented
@clintonb test added!

2017-06-27 12:44 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_forms.py
> +    """Tests for the CommentsForm form."""
I've always found these class-level comments worthless. Feel free to remove this.

2017-06-27 12:44 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_forms.py
> +        """Retrieves the Comments model."""
What retrieves the model? This doc string doesn't really help me understand what you're testing or why.

2017-06-27 12:44 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_forms.py
> +        """Sets the right site_id value."""
Same as above. Help me understand why this test is useful.

2017-06-27 19:22 UTC, vkaracic commented
@clintonb I have somewhat addressed your comments. I've created a test on a more suitable place. The error that happens when upgrading this package happens when data is posted the comment post endpoint hence this test. And I have confirmed that when I remove the `site_id` parameter this new test fails.

2017-06-27 19:33 UTC, clintonb approved these changes

2017-06-28 08:46 UTC, merged