optimize queries
openedx/course-discovery pull request #1037
Opened 2017-07-06 12:12 UTC by muhammad-ammar

2017-07-07 09:27 UTC, muzaffaryousaf requested changes
@muhammad-ammar Done with first pass, let me know when you're done.

2017-07-07 09:27 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/models.py
> +        return ''
Can we have single `return` here.
```
course_user_name = ''
if condition:
   course_user_name = 'blah'
return course_user_name
```

2017-07-07 09:27 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/models.py
> +              to reduce the number of queries executed.
Is it specific to that view only, if yes then i think we don't put this as property here.

2017-07-07 09:27 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/models.py
> +            return ''
Same, let's try to have single return.

2017-07-07 09:27 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/models.py
> +        Return course project coordinator user name.
NIT: Return --> Returns

2017-07-07 09:27 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/models.py
> +            return self.course_user_roles.only('user').get(role=PublisherUserRole.ProjectCoordinator).user
Does this make any difference in query time ? Have you tried personally ?

2017-07-07 09:27 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +        )
Can we add test coverage for query counts ?

2017-07-07 09:27 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +        )
I'm assuming that existing tests are already covering this logic in terms of data set. Can you confirm if that's the case.

2017-07-07 09:27 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +        courses = Course.objects.select_related().prefetch_related(
Nice Shot for using `prefetch_related` 💯

2017-07-07 09:27 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +            course_user_name=F('course_user_roles__user__full_name')
Why do we need these annotates and how much they're adding to the performance improvement.

2017-07-07 09:31 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +        courses = Course.objects.select_related().prefetch_related(
`There may be some situations where you wish to call select_related() with a lot of related objects, or where you don’t know all of the relations. In these cases it is possible to call select_related() with no arguments. This will follow all non-null foreign keys it can find - nullable foreign keys must be specified. This is not recommended in most cases as it is likely to make the underlying query more complex, and return more data, than is actually needed.`

@muhammad-ammar Hope you've seen this from Django docs.

2017-07-07 10:21 UTC, muhammad-ammar commented on course_discovery/apps/publisher/models.py
> +            return self.course_user_roles.only('user').get(role=PublisherUserRole.ProjectCoordinator).user
yes, I have verified this. we are only selecting a single field instead of all table columns.

2017-07-07 10:48 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +        courses = Course.objects.select_related().prefetch_related(
I have removed this.

2017-07-07 10:51 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +            course_user_name=F('course_user_roles__user__full_name')
This will have a huge impact. Currently for each course separate database hits are made to calculate the name of project coordinator. So after annotation no database query will be made in the loop.

2017-07-07 13:04 UTC, muhammad-ammar commented
@awais786 @waheedahmed Can anyone of you review the changes?

2017-07-07 13:40 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +        if self.user_role == PublisherUserRole.ProjectCoordinator:
Make sure course has the role otherwise it will throw the exception.
Also there is existing property for [PC](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/publisher/models.py#L129)

2017-07-12 08:14 UTC, muhammad-ammar commented
@awais786 Can you have a quick look? It would be great if we can merge this today.

2017-07-12 08:24 UTC, muhammad-ammar commented
@muzaffaryousaf Can you have a final look?

2017-07-12 16:32 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.courses = [factories.CourseFactory() for _ in range(10)]
Ideally, we should import the `CourseFactory` in first place instead of using `factories`.

2017-07-13 09:54 UTC, muzaffaryousaf approved these changes
LGTM 👍  except couple of NITs. 💯

2017-07-13 09:54 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertContains(response, 'Edit')
Earlier we were not expecting 'Edit' in response but now we do. Reason ?

2017-07-13 09:54 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertContains(response, 'Edit')
Is it not too much broad assertion ?

2017-07-13 09:54 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertContains(response, 'Edit')
I see you're check the assertion later.

2017-07-13 09:54 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +        )
can we add `objects.all()`

2017-07-13 11:31 UTC, awais786 commented
👍 Good Job @muhammad-ammar.

2017-07-13 11:36 UTC, muhammad-ammar commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.courses = [factories.CourseFactory() for _ in range(10)]
yes, but this what is happening now but we can refactor it later in a separate PR

2017-07-13 11:38 UTC, muhammad-ammar commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertContains(response, 'Edit')
It is but i will prefer to update the test in a separate PR.

2017-07-14 12:40 UTC, merged

2017-07-14 15:48 UTC, MichaelRoytman commented
Hello,

I saw that this commit went to stage this morning. I got a bunch of pages this morning for stage discovery.

You can see the NewRelic alerts below.

https://rpm.newrelic.com/accounts/88178/incidents/30400026

https://rpm.newrelic.com/accounts/88178/applications/15120497/traced_errors/8a5f2e9e-68a4-11e7-8968-0242ac11000f_16360_21050/similar_errors?original_error_id=8a5f2e9e-68a4-11e7-8968-0242ac11000f_16360_21050

Could you take a look at this before it goes to production? Please coordinate with the Learner - Spartan team, if need be.

Best,
Michael

2017-07-14 17:07 UTC, muzaffaryousaf commented
@MichaelRoytman I've verified from New Relic https://rpm.newrelic.com/accounts/88178/applications/15120497/traced_errors/8a5f2e9e-68a4-11e7-8968-0242ac11000f_16360_21050?original_error_id=8a5f2e9e-68a4-11e7-8968-0242ac11000f_16360_21050
This PR did't changed anything related to this error, something else must be. Looks like something is wrong with Publisher's data.

2017-07-18 09:07 UTC, muzaffaryousaf commented
@sstack22 This is live on prod, you can check the improvements in PR header.