If the family name was not entered (is None), it's not appended to th…
openedx/course-discovery pull request #1038
Opened 2017-07-06 13:36 UTC by afzaledx

…e given name to make the full name.

LEARNER-1701

2017-07-06 13:54 UTC, afzaledx commented
@edx/helio

2017-07-06 13:59 UTC, mjfrey approved these changes

2017-07-06 14:01 UTC, clintonb requested changes

2017-07-06 14:01 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        return ' '.join((self.given_name, self.family_name,)) if self.family_name else self.given_name
Don't do this. Set the default value of `family_name` to an empty string and make the field non-nullable.

2017-07-06 14:03 UTC, clintonb commented
See the note on commit messages at https://openedx.atlassian.net/wiki/display/ECOM/Developer+Onboarding. Shorten your commit summaries.

2017-07-06 14:44 UTC, afzaledx commented
@clintonb , can you please review again?

2017-07-06 15:06 UTC, clintonb commented
Let's discuss this on the ticket. Fixing this correctly will involve a bit more work, and I'm not convinced this is a real issue we have with our current data.

2017-07-07 12:55 UTC, clintonb commented
This is not a priority. We'll get to it...eventually.

2017-07-07 12:55 UTC, closed without merging