EDUCATOR-831 Correct course title format in publisher course update.
openedx/course-discovery pull request #1044
Opened 2017-07-11 10:59 UTC by attiyaIshaque

2017-07-11 11:38 UTC, asadazam93 approved these changes
Looks good

2017-07-11 11:38 UTC, awaisdar001 requested changes

2017-07-11 11:38 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_forms.py
> +        course_form = CustomCourseForm()
@attiyaIshaque I would suggest populating data in the `CustomCourseForm` instance and then call `course_form.is_valid()`. This would automatically populate `course_form.cleaned_data`. This way you do not have to call `course_form.clean_title` explicitly.

2017-07-11 11:38 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_forms.py
> +        self.assertEqual(course_form.clean_title(), "áçã")
I would also suggest checking saving of the `course_form` object. After manipulating the title key in the `clean` method, we should also check that is safe to be stored in the database (i.e. no Charset issues).

2017-07-12 09:53 UTC, attiyaIshaque commented
@awaisdar001 I have addressed the comments and thanks for helping me out in Unit test. :)

2017-07-12 13:14 UTC, awaisdar001 approved these changes

2017-07-12 13:14 UTC, awaisdar001 commented
Once the tests passes 👍

2017-07-12 13:26 UTC, merged