[WIP] paginate courses list page on backend
openedx/course-discovery pull request #1066
Opened 2017-07-19 13:54 UTC by muhammad-ammar

[EDUCATOR-882](https://openedx.atlassian.net/browse/EDUCATOR-882)

2017-07-21 10:33 UTC, muhammad-ammar commented
@muzaffaryousaf @awais786 This is ready for review. Currently build is failing for some reason. Looking into it.

2017-07-21 10:36 UTC, awais786 commented on course_discovery/templates/publisher/courses.html
> +            var $coursesTable = $('#dataTableCourse').DataTable({
Move this code in a separate file and call in a compress block.

2017-07-21 10:37 UTC, muhammad-ammar commented on course_discovery/templates/publisher/courses.html
> +            var $coursesTable = $('#dataTableCourse').DataTable({
ah..ok..thanks for pointing this.

2017-07-21 10:38 UTC, muzaffaryousaf commented
@muhammad-ammar  Are you building up sandbox ?

2017-07-21 10:56 UTC, muhammad-ammar commented
@muzaffaryousaf I am trying to [build](https://docs.google.com/document/d/1pYMorQrXwBH_6B2dNn1ZmY84XDtX0QQ36GTJ_YgJoVg/edit?ts=596f673a#) a sandbox. Currently its not working.

2017-07-21 11:19 UTC, muhammad-ammar commented on course_discovery/templates/publisher/courses.html
> +            var $coursesTable = $('#dataTableCourse').DataTable({
I have created a separate js file but now how can i acces the server variables like `publisher_total_courses_count`, `courses`, `publisher_courses_url` etc in the js file? Can you please point me to any docs about why we need this compress change.

2017-07-21 13:02 UTC, muzaffaryousaf requested changes
I've looked at code for now and left some feedback, I'm reviewing tests now.

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/templates/publisher/courses.html
> +                                return '<a href="'+data.url+ '" class="btn btn-brand btn-small btn-course-edit">' + data.title + '</a>'
can we use format instead of + ??

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +            page_size = int(self.request.GET.get('length', COURSES_DEFAULT_PAGE_SIZE))
`length` can we rename this to page_size ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +    def get_paginate_by(self, queryset):
`queryset` is not being used.

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +            5: 'course_state__owner_role_modified',
Is't 4 & 5 are same ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/serializers.py
> +            return ''
`return course.project_coordinator.full_name if course.project_coordinator else ''`

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/serializers.py
> +            'date': course.course_state.course_team_status['date'].strftime('%m/%d/%y')
Any possibility for DoesNotExist exception OR index error ? Also, can we use get instead of these `['status_text']` and `course_team_status['date']`  ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/serializers.py
> +            'date': course.course_state.course_team_status['date'].strftime('%m/%d/%y')
can we extract `course.course_state.course_team_status` in a variable ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +        ordering_direction = self.request.GET.get('sortDirection', 'asc')
`sort_direction`

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +        ordering_field = ordering_fields.get(ordering_field_index)
Maybe `sort_field` ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/serializers.py
> +        return course.publisher_course_runs.count()
Will `publisher_course_runs` be present every time event if ordering field is not course_runs_count?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +            queryset = queryset.order_by(Lower(ordering_field).desc())
Why we're using Lower  in order_by ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +        keywords, dates = self.extract_keywords_and_dates(filter_text)
We need healthy / heavy coverage for this method.

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +            keywords_filter = (keyword_filter & keywords_filter) if bool(keywords_filter) else keyword_filter
(keyword_filter & keywords_filter) for AND purpose on query set ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +                Q(reduce(lambda x, y: x | y, [Q(course_state__owner_role_modified__date=date) for date in dates]))
comment would be helpful for lambda and reduce here. Are we looking for exact date match ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +            totalRecords = self.object_list.count()
totalRecords --> count ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/static/js/publisher/views/courses.js
> +                        return '<a href="'+data.url+'">' + data.title + '</a>';
.format ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +                'draw': int(self.request.GET['draw']),
What is this use for ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +            queryset = queryset.annotate(course_runs_count=Count('publisher_course_runs'))
Will this count related `publisher_course_runs` only?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/tests/test_views.py
> +        with mock.patch.object(Course, "save") as mock_method:
Were you seeing any failure for not using mock. or it's just refactor ?

2017-07-21 13:02 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/tests/test_views.py
> +        with mock.patch.object(Course, "save") as mock_method:
NVM, I've seen that you're using patch decorator.

2017-07-21 13:11 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +        ordering_direction = self.request.GET.get('sortDirection', 'asc')
This variable is passed from JS so JS convention is followed.

2017-07-21 13:12 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +        ordering_field = ordering_fields.get(ordering_field_index)
django uses the ordering convention so i followed that.

2017-07-21 13:12 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +            queryset = queryset.annotate(course_runs_count=Count('publisher_course_runs'))
yes

2017-07-21 13:12 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +            queryset = queryset.order_by(Lower(ordering_field).desc())
for case insensitive ordering

2017-07-21 13:13 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +            keywords_filter = (keyword_filter & keywords_filter) if bool(keywords_filter) else keyword_filter
yes

2017-07-21 13:13 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +                Q(reduce(lambda x, y: x | y, [Q(course_state__owner_role_modified__date=date) for date in dates]))
yes...this will do an exact date match

2017-07-21 13:14 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +                'draw': int(self.request.GET['draw']),
this is required by DataTables. https://datatables.net/manual/server-side

2017-07-21 13:15 UTC, muhammad-ammar commented on course_discovery/apps/publisher/serializers.py
> +        return course.publisher_course_runs.count()
`publisher_course_runs` is a related field to course and will always be present.

2017-07-21 13:16 UTC, muhammad-ammar commented on course_discovery/static/js/publisher/views/courses.js
> +                        return '<a href="'+data.url+'">' + data.title + '</a>';
I am not sure if we can use `format` in jS?

2017-07-21 13:16 UTC, muhammad-ammar commented on course_discovery/apps/publisher/tests/test_views.py
> +        with mock.patch.object(Course, "save") as mock_method:
I changed this due a quality error.

2017-07-21 13:18 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +            5: 'course_state__owner_role_modified',
yes...both columns on frontend uses the same model field.

2017-07-21 13:18 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +            page_size = int(self.request.GET.get('length', COURSES_DEFAULT_PAGE_SIZE))
I will check if this is possible.

2017-07-21 13:22 UTC, muhammad-ammar commented
@muzaffaryousaf @awais786 Here is the [sandbox](https://discovery-pagination.sandbox.edx.org/publisher/courses/). Currently styling is messed up for some reason. Looking into it.

2017-07-21 13:27 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +        ordering_field = ordering_fields.get(ordering_field_index)
ordering_field ??

2017-07-21 13:41 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/serializers.py
> +        return course.publisher_course_runs.count()
Any chance for does not exist?

2017-07-21 13:41 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +            5: 'course_state__owner_role_modified',
And same data?

2017-07-21 13:42 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +        ordering_direction = self.request.GET.get('sortDirection', 'asc')
I mean ordering_direction --> sort_direction

2017-07-21 13:43 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +        ordering_direction = self.request.GET.get('sortDirection', 'asc')
If Django uses ordering then its okay

2017-07-21 13:45 UTC, muzaffaryousaf commented
@muhammad-ammar Sandbox is redirecting me to this url --> 
`http://127.0.0.1:8000/oauth2/authorize/?client_id=discovery-key&state=vp2K5UxMbANv5XFnm6WOb6qe4DvtHrrE&response_type=code&scope=openid+profile+email+permissions&redirect_uri=https://discovery-pagination.sandbox.edx.org/complete/edx-oidc/`

2017-07-25 13:23 UTC, muhammad-ammar commented
@muzaffaryousaf @awais786 Please continue the review. I have addressed the feedback and [sandbox](https://discovery-pagination.sandbox.edx.org/publisher/courses/) is working now. For oauth2 authentication, you can use the below credentials when asked

email: staff@example.com
password: edx

2017-07-25 15:36 UTC, muhammad-ammar commented
@sstack22 Can you take a look at pagination on [courses](https://discovery-pagination.sandbox.edx.org/publisher/courses/) list. Currently ordering is happening on 1st and last 3 columns and filtering is applying on first 2 and last 2 columns.

2017-07-26 20:09 UTC, awais786 commented on course_discovery/apps/publisher/serializers.py
> +        publisher_hide_features_for_pilot = self.context['publisher_hide_features_for_pilot']
You can remove these kind of flags. They were added for pilot.

2017-07-26 20:20 UTC, awais786 commented
@muhammad-ammar I have checked the PR and sandbox also. Code look good and also working fine on sandbox. Nice work 👍

2017-07-27 14:18 UTC, sstack22 commented
@muhammad-ammar  - from looking at the sandbox, I can't tell if sorting/filtering is working as expected, as everything seems to have the same date (though the course names are changing order). Is there a bug here?

2017-07-27 14:28 UTC, muhammad-ammar commented
@sstack22 The date is same because all the courses data is imported from stage on same day. That's why same date is set for all the courses. I will manually modify the dates so that you can check the ordering. Will notify you once dates are updated.

2017-07-28 05:06 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +    def get_paginate_by(self, queryset):
Do we need to address this ?

2017-07-28 05:09 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +    def get_paginate_by(self, queryset):
actually quality is good for this so that's why i didn't changed it.

2017-07-28 05:09 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +            5: 'course_state__owner_role_modified',
yes

2017-07-28 05:09 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +                Q(reduce(lambda x, y: x | y, [
Not a big fan of use x and y as names. It'd be nice if we can change them.

2017-07-28 05:10 UTC, muzaffaryousaf commented on course_discovery/apps/publisher/views.py
> +            tuple: tuple of two lists, first list contains date strings and second contains keywords without dates
without dates ???

2017-07-28 05:12 UTC, muzaffaryousaf commented on course_discovery/static/js/publisher/views/courses.js
> +        'lengthMenu': [25, 50, 100],
can we manage this from backend ?

2017-07-28 05:13 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +            tuple: tuple of two lists, first list contains date strings and second contains keywords without dates
oops...looks like docstring need a cleanup

2017-07-28 05:13 UTC, muzaffaryousaf commented on course_discovery/static/js/publisher/views/courses.js
> +                        return '<a href="'+data.url+'">' + data.title + '</a>';
NVM

2017-07-28 05:14 UTC, muzaffaryousaf approved these changes
LGTM 👍  I've left some inline comments.

2017-07-28 05:37 UTC, muhammad-ammar commented
@sstack22 Dates are changed now. You can check the ordering.

2017-07-28 05:43 UTC, muhammad-ammar commented on course_discovery/apps/publisher/views.py
> +                Q(reduce(lambda x, y: x | y, [
how about `Q(reduce(lambda date1, date2: date1 | date2, [...`

2017-07-28 07:18 UTC, muhammad-ammar commented
@muzaffaryousaf Addressed your feedback. Also sandbox is updated.

2017-07-28 13:15 UTC, sstack22 commented
👍  - this looks good!

2017-07-31 07:31 UTC, merged