LEARNER-1816 Updated name for program banner image
openedx/course-discovery pull request #1072
Opened 2017-07-24 09:04 UTC by Ayub-Khan

**[LEARNER-1816](https://openedx.atlassian.net/browse/LEARNER-1816)** XSeries banner and card images displaying incorrectly	

**Description**
Updated the Name with the date. So that Cached image of cloud front is replaced with the new image we upload.

2017-07-25 17:12 UTC, schenedx requested changes
@Ayub-Khan I have questions about this approach.

2017-07-25 17:12 UTC, schenedx commented on course_discovery/apps/course_metadata/utils.py
> +            'name': str(field_value) + "{:-%d-%m-%Y}".format(datetime.datetime.now())
I don't really like using the current date for this purpose. Is there another choice we can use to make this unique?
Plus, with this implementation, if two files are uploaded in the same date, they would still have the same name.
Why can't we use a random set of string if we just want cache busting? For random string, we can use regex to unit test and validate, right?

2017-07-25 17:21 UTC, clintonb requested changes
This seems to be treating a symptom, not the actual issue. The images stored in the Discovery Service are correct. The issue is that the downstream client—the marketing site—is improperly caching the images. Fix the client, not the server.

2017-07-25 17:25 UTC, clintonb commented
Correction: It looks like this service is in fact caching an invalid image: https://prod-edx-discovery.edx.org/api/v1/programs/ef7f3b09-5660-466c-8283-0810077f353a/. How can we invalidate the cache when an image is changed without necessarily changing the image's name?

2017-07-25 17:26 UTC, clintonb commented
Perhaps the solution is to not worry about invalidation, but inform users to upload real images rather than placeholders.

2017-07-25 17:29 UTC, clintonb commented on course_discovery/apps/course_metadata/utils.py
> +            'name': str(field_value) + "{:-%d-%m-%Y}".format(datetime.datetime.now())
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ReplacingObjectsSameName.html

I agree with @schenedx. Use a portion of a GUID. The resulting file name should be:

`{program_uuid}.{size}.{cache_guid}.jpg`
`ef7f3b09-5660-466c-8283-0810077f353a.small.abc123.jpg`

2017-07-25 17:30 UTC, schenedx commented
@clintonb The root cause is that, cloudfront would cache the image stored on S3. Every time we upload a new image, the image reference to S3 remains the same. 
See https://dphy0qlkz2ftb.cloudfront.net/media/programs/banner_images/a87e5eac-3c93-45a1-a8e1-4c79ca8401c8.large.jpg VS https://dphy0qlkz2ftb.cloudfront.net/media/programs/banner_images/a87e5eac-3c93-45a1-a8e1-4c79ca8401c8.large.jpg?gdaf=4345

The idea is that, we should use a different name to reference this S3 image every time a new file has been uploaded to get around the image cache.

2017-07-25 17:35 UTC, clintonb commented
@schenedx @Ayub-Khan what's the plan for cleaning up old images?

2017-07-25 17:38 UTC, schenedx commented
@clintonb Now I remember why we didn't create a unique name for each banner image in the first place. I don't know a good plan to clean old images... Aaarrrgg

2017-07-25 17:55 UTC, clintonb commented
You could write a management command that cleans up older files after a certain period of time. We would need to establish an SLA with API clients (especially affiliates) so that they understand that image links are only good for 30 days, for example. Ultimately, we could do something similar for other static assets—CSS and JS—on the frontend.

2017-07-25 18:08 UTC, schenedx commented
@Ayub-Khan @clintonb 
I think it's not worth the trouble to implement this management command which clean up old banner images. We only add very few old banner images for a long periods of time (years). It's not a problem we need to worry about at the moment I say.

2017-07-27 19:54 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +        regex = re.compile(path + str(getattr(self.program, field)) + '-............' + ext)
Drop the dots. Use `-[a-f0-9]{12}`.

2017-07-27 20:58 UTC, clintonb approved these changes

2017-07-28 13:38 UTC, schenedx approved these changes
Minor comment, rest LGTM 👍

2017-07-28 13:38 UTC, schenedx commented on course_discovery/apps/course_metadata/utils.py
> +            'name': str(field_value) + str(uuid.uuid4())[23:]
So, we use the first 12 characters? Can you please add a comment?

2017-07-28 15:32 UTC, Ayub-Khan commented on course_discovery/apps/course_metadata/utils.py
> +            'name': str(field_value) + str(uuid.uuid4())[23:]
last 12 characters

2017-07-28 17:02 UTC, merged