EDUCATOR-756 Instructor form data cleared on cancel.
openedx/course-discovery pull request #1076
Opened 2017-07-26 09:25 UTC by attiyaIshaque

2017-07-26 12:48 UTC, Rabia23 requested changes

2017-07-26 12:48 UTC, Rabia23 commented on course_discovery/static/js/publisher/modal-screen.js
> +    clearData('#given-name');
We can make a list of selectors and loop over the list like this:
 
```
selectors = ['#given-name', '#family-name',  '#title', '#email', '#bio', '#facebook', '#twitter', '#blog', '#majorWorks']
for (i in selectors) {
   clearData(selectors[i]);
}
```

2017-07-27 06:05 UTC, attiyaIshaque commented on course_discovery/static/js/publisher/modal-screen.js
> +    clearData('#given-name');
Oh great. I will do that. Thanks

2017-07-27 08:39 UTC, asadazam93 approved these changes
Looks good

2017-07-27 09:10 UTC, Rabia23 approved these changes

2017-07-27 09:12 UTC, merged