ownership and course state does not change on pc edit
openedx/course-discovery pull request #1081
Opened 2017-08-01 11:57 UTC by asadazam93

## [EDUCATOR-1008](https://openedx.atlassian.net/browse/EDUCATOR-1008)

### Description
There are fields in the course that only PCs have the ability to fill in namely (About Video Link), but since the project coordinator has no role in the actual workflow of the course so when the project coordinator makes an edit to the course the ownership is changed to PC along with the course state changed to Draft and that disturbs the actual workflow between the course team and the marketing team.
Solution 
So now when a project coordinator edits a course the course state will not be changed and neither the ownership (however a history object for that edit would be created) hence the workflow of the course that involves the course team and marketing team would not be disturbed. A project coordinator is only making edits on behalf of the course team, he is not a part of the workflow of sending the course for review neither marking the course as reviewed so it does not make sense to transfer ownership to the PC.

### How to Test?

- Login as project coordinator of a course.
- Edit the course
- Confirm that the ownership and state of the course did not change but a history object for that edit was created

**Sandbox**
- Will be provided on request

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review: @attiyaIshaque 
- [ ] Code review: @awaisdar001  

FYI: @sstack22 

### Post-review
- [ ] Rebase and squash commits

2017-08-01 13:01 UTC, attiyaIshaque commented on course_discovery/apps/publisher/tests/test_views.py
> +        project_coordinator.groups.add(Group.objects.get(name=INTERNAL_USER_GROUP_NAME))
You can also use this:
```project_coordinator.groups.add(Group.objects.get(name= for name in [INTERNAL_USER_GROUP_NAME, PROJECT_COORDINATOR_GROUP_NAME]))```

2017-08-04 10:47 UTC, asadazam93 commented on course_discovery/apps/publisher/tests/test_views.py
> +        project_coordinator.groups.add(Group.objects.get(name=INTERNAL_USER_GROUP_NAME))
I tried but get cannot return multiple groups.

2017-08-04 12:12 UTC, attiyaIshaque commented on course_discovery/apps/publisher/tests/test_views.py
> +        project_coordinator.groups.add(Group.objects.get(name=INTERNAL_USER_GROUP_NAME))
Okay. :)

2017-08-04 12:14 UTC, attiyaIshaque approved these changes
@asadazam93 code good looks to me, aslo i have tested on sandbox. 👍

2017-08-07 08:06 UTC, awaisdar001 requested changes

2017-08-07 08:06 UTC, awaisdar001 commented on course_discovery/apps/publisher/views.py
> -                if self.object.course_state.name != CourseStateChoices.Draft:
What is `self.object`? This seems a very genric name to me. Please update it to whatever type of object that is. I.e. `course` or `course_run`

2017-08-07 08:06 UTC, awaisdar001 commented on course_discovery/apps/publisher/views.py
> +                if (self.object.course_state.owner_role != user_role.role and
If you are checking that `self.object.course_state.owner_role` should not be equal to 2 or more variables do this.
`self.object.course_state.owner_role not in  (user_role.role, PublisherUserRole.ProjectCoordinator)`

2017-08-07 08:06 UTC, awaisdar001 commented on course_discovery/apps/publisher/views.py
> +                if (self.object.course_state.name != CourseStateChoices.Draft and
is `self.object` is a keyword here which is required for backend oprations? Or it is just a normal veriable name? If it is just a veriable, can we change this somthing meaningful ? maybe `course` or `course_run`? then the following statement can become more readable. 

`self.object.course_state.name != CourseStateChoices.Draft` => `course.course_state_name != CourseStateChoices.Draft` 

Note the `course_state_name` property method.

2017-08-08 11:23 UTC, asadazam93 commented on course_discovery/apps/publisher/views.py
> +                if (self.object.course_state.name != CourseStateChoices.Draft and
self.object is an object instance the view is operating on, i.e it is an instance of a django model in this case (it is inherited from the mixin we are using). So that is why we cannot change it's name.

2017-08-08 11:28 UTC, asadazam93 commented on course_discovery/apps/publisher/views.py
> +                if (self.object.course_state.owner_role != user_role.role and
These are two different conditions. First check is that the the owner role is not equal to the logged in user role and the second condition is that the logged in user is not a project coordinator.

2017-08-11 11:18 UTC, merged