Add start date, end date, and CEUs to Programs
openedx/course-discovery pull request #1083
Opened 2017-08-02 20:29 UTC by tuchfarber

In order to make WL certificates dynamic, we need this program information to be available to the template.

[WL-1119]
[WL-1120]

2017-08-02 21:03 UTC, tuchfarber commented
@clintonb I don't see start and end date being an issue, but we haven't broached where CEU/CMEs should be stored. Wanted a Learner perspective on it. The other option I can think of is to store them at the course level and bubble them up in the ProgramSerializer somewhere. Thoughts?

2017-08-02 21:19 UTC, clintonb requested changes
Tests? Squash your commits.

2017-08-02 21:19 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    start_date = models.DateField(null=True, blank=True, db_index=True)
None of these new fields need to be indexed unless you intend on actually querying the DB with them.

2017-08-02 21:19 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    continuing_education_units = models.DecimalField(
Why is this a decimal field?

2017-08-02 21:19 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0060_auto_20170802_2006.py
> +# -*- coding: utf-8 -*-
You should only have one migration.

2017-08-02 21:19 UTC, clintonb commented on course_discovery/apps/course_metadata/admin.py
> +        'marketing_slug', 'overview', 'credit_redemption_overview', 'video', 'weeks_to_complete', 'start_date',
Chat with UX and Tatiana in Marketing about grouping these fields in some logical manner. See https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets.

2017-08-02 21:19 UTC, clintonb commented
FYI @edx/learner

2017-08-02 21:25 UTC, tuchfarber commented on course_discovery/apps/course_metadata/models.py
> +    start_date = models.DateField(null=True, blank=True, db_index=True)
Noted. Will update.

2017-08-02 21:26 UTC, tuchfarber commented on course_discovery/apps/course_metadata/models.py
> +    continuing_education_units = models.DecimalField(
Needed to store half credits. The current Sys Eng program we're running is 8.5 CEUs.

2017-08-02 21:28 UTC, clintonb commented
Should CEUs be a property of course runs, courses, or programs?

2017-08-03 17:38 UTC, douglashall commented on course_discovery/apps/course_metadata/models.py
> +    continuing_education_units = models.DecimalField(
I would store the `continuing_education_unit` value at the most atomic level possible. I could see the next request coming in from folks being the display of CEUs on the course about page. If you add the `continuing_education_unit` field to the Course model you could calculate Program CEUs.

The problem with that approach though is that there would not be a good way for course staff to author the CEU data at the present time. Course staff do not have access to Django admin in the discovery service, so someone here at edX (project coordinator) would have to take on this step when setting up new courses.

2017-08-03 19:02 UTC, clintonb commented
@tuchfarber it will be best to split this into two PRs—one for dates, another for CEUs. The dates change is fine, as long as you communicate it to PCs. The CEUs change will require more discussion.

2017-08-04 17:18 UTC, closed without merging

2017-08-04 17:19 UTC, tuchfarber commented
It's been decided that CEU metadata should fall under Courses, not programs.

2017-08-04 18:05 UTC, clintonb commented
@tuchfarber delete your branches after closing PRs