EDUCATOR-1086  Allow range of hours/units or one, non-range value in 'Estimated Effort' field
openedx/course-discovery pull request #1087
Opened 2017-08-10 14:01 UTC by Rabia23

2017-08-11 12:44 UTC, asadazam93 approved these changes
Looks good

2017-08-15 06:29 UTC, awaisdar001 requested changes

2017-08-15 06:29 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_forms.py
> +            run_form.clean()
there are many `ValidationError` in the form `clean` method, We should also test if the expected `ValidationError` has occurred.

2017-08-15 06:29 UTC, awaisdar001 commented on course_discovery/apps/publisher/models.py
> -            course_run.max_effort, course_run.video_language, course_run.length
We are updating `can_send_for_review` method in the `CourseRunState` model, the relevant test is missing.

2017-08-15 09:57 UTC, Rabia23 commented on course_discovery/apps/publisher/models.py
> -            course_run.max_effort, course_run.video_language, course_run.length
@awaisdar001 relevant test exists. It has been updated already. 
Here is a link:
https://github.com/edx/course-discovery/pull/1087/files#diff-7541c140671314e6639d6a0fe3f4c4df

2017-08-15 10:02 UTC, Rabia23 commented on course_discovery/apps/publisher/tests/test_forms.py
> +            run_form.clean()
Tests already exist for the other `ValidationError` in the form `clean` method.

2017-08-15 13:11 UTC, merged