EDUCATOR-807 Fix Course Start date storing in Preview dashboard.
openedx/course-discovery pull request #1098
Opened 2017-08-24 10:13 UTC by attiyaIshaque

2017-08-24 10:52 UTC, awaisdar001 requested changes

2017-08-24 10:52 UTC, awaisdar001 commented on course_discovery/templates/publisher/dashboard/_in_preview.html
> +                        <td data-order="{{ course_run.start|date:"Y-m-d" }}">
@attiyaIshaque whats the documentation link?

2017-08-24 10:54 UTC, attiyaIshaque commented on course_discovery/templates/publisher/dashboard/_in_preview.html
> +                        <td data-order="{{ course_run.start|date:"Y-m-d" }}">
@awaisdar001 https://datatables.net/examples/advanced_init/html5-data-attributes.html

2017-08-25 07:07 UTC, Rabia23 commented
Looks good 👍

2017-08-25 07:07 UTC, Rabia23 approved these changes

2017-08-25 10:14 UTC, asadazam93 approved these changes
Looks Good

2017-08-25 10:16 UTC, awaisdar001 approved these changes

2017-08-25 10:17 UTC, merged