ignore for now
openedx/course-discovery pull request #1108
Opened 2017-09-06 21:38 UTC by MatthewPiatetsky

LEARNER-2409 Add currency view

2017-09-07 18:54 UTC, mikedikan reviewed
Small comments - looks good so far 👍

2017-09-07 18:54 UTC, mikedikan commented on course_discovery/apps/api/v1/views/currency.py
> +    EUROZONE_COUNTRIES = [
Should this be in this file and not in settings?

2017-09-07 18:54 UTC, mikedikan commented on course_discovery/apps/api/v1/tests/test_views/test_currency.py
> +    def test_list(self):
Is there a way to have this in an external file?

2017-09-07 20:43 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_currency.py
> +    def test_list(self):
i just shortened the test data instead and refactored the files a bit to allow easily mocking all three files

2017-09-07 20:44 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +    EUROZONE_COUNTRIES = [
imo this and the other variable in this file are pretty specific implementation things rather than settings that may be changed/reused. (i could also see this code being replaced by a package in the future)
i think if we end up wanting to reuse this anywhere else though then it should be a setting

2017-09-08 14:41 UTC, mikedikan approved these changes
:shipit:

2017-09-11 19:22 UTC, jdmulloy requested changes

2017-09-11 19:22 UTC, jdmulloy commented on course_discovery/apps/api/v1/views/currency.py
> +            response = requests.get(url + api_key)
What happens when this service is down or slow to respond. What is the timeout?

2017-09-11 19:22 UTC, jdmulloy commented on course_discovery/apps/api/v1/views/currency.py
> +            api_key = settings.OPENEXCHANGERATES_API_KEY
What happens if the key has not been set, such as in a sandbox or devstack?

2017-09-11 19:22 UTC, jdmulloy commented on course_discovery/apps/api/v1/views/currency.py
> +            logging.error('Could not retrieve rates from openexchangerates')
For debugging and troubleshooting purposes when failures occur logging the exception type and message here would be very useful.

2017-09-11 19:22 UTC, jdmulloy commented on course_discovery/apps/api/v1/views/currency.py
> +            url = 'https://openexchangerates.org/api/latest.json?app_id='
It might also be nice to have the URL in a config variable in case it needs to change in the future, or if we make this more modular to allow other users of our code to use other providers.

Nit: It would be cleaner and less fragile to pass the app_id parameter as an argument to the requests.get method instead of constructing a string. See http://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls for details.

Perhaps something like the following.
```
url = 'https://openexchangerates.org/api/latest.json'
response = requests.get(url, params={'api_key':  api_key})
```

2017-09-11 19:22 UTC, jdmulloy commented on course_discovery/apps/api/v1/views/currency.py
> +        rates = self.get_rates()
What happens when get_rates() returns None, such as when an exception is caught? In the method get() below "rates" is assumed to be a dictionary. If it's None then we will get stack traces saying something like```'NoneType' object has no attribute 'get'```

2017-09-11 21:35 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +            api_key = settings.OPENEXCHANGERATES_API_KEY
added an if statement

2017-09-11 21:35 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +            url = 'https://openexchangerates.org/api/latest.json?app_id='
the code wouldn't work as it stands with another provider. imo i would keep it like this and move it to config if a second use case comes up. added the params dict though

2017-09-11 21:36 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +            response = requests.get(url + api_key)
added a 2 second timeout.
i figured we don't want to wait too long, but at the same time this should only run once a day, which is why i said 2 seconds over 1.

2017-09-11 21:36 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +            logging.error('Could not retrieve rates from openexchangerates')
added message/status code/xception type to the log

2017-09-11 21:37 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +        rates = self.get_rates()
changed get_rates to return dict

2017-09-11 21:37 UTC, MatthewPiatetsky commented
@jdmulloy still need to update tests and make sure all my new code works, but otherwise did I address your comments?

2017-09-12 19:27 UTC, AlasdairSwan commented
@MatthewPiatetsky I have a question about the format of the returned data. So the response would be in the following format;
```
"MEX": [
    "MXN",
    "$",
    17.795193
]
```
How about making it something like;
```
"MEX": {
    country: "MXN",
    unit: "$",
    rate: 17.795193
}
```
So it's easier to read the code that would use it. For example;
```
var displayPrice = MEX[1] + ' ' + MEX[0] + ' ' + (price * MEX[2]);
```
isn't as easy to read as
```
var displayPrice = MEX.unit + ' ' + MEX.country + ' ' + (price * MEX.rate);
```

2017-09-12 19:33 UTC, MatthewPiatetsky commented
@AlasdairSwan i was just keeping down the size of the response, but that's fine, I can change it to that

2017-09-12 20:04 UTC, AlasdairSwan commented
Thanks @MatthewPiatetsky, I just think it would make it easier to work with. These may be clearer names;
```
"MEX": {
    code: "MXN",
    symbol: "$",
    rate: 17.795193
}
```

2017-09-12 21:03 UTC, feanil requested changes

2017-09-12 21:03 UTC, feanil commented on course_discovery/apps/api/v1/views/currency.py
> +                logging.error('No app id available for openexchangerates')
Is this an error?  Won't this be true for all non edx deployments to start with?

2017-09-12 21:03 UTC, feanil commented on course_discovery/apps/api/v1/views/currency.py
> +                response_json = response.json()
This call can fail if the response is not JSON.  If you try to use `response_json.get('message')` in the except section, that will probably just return `None`.  You should handle this case.  You should do something different if requests fails to parse JSON from the response.

2017-09-12 21:12 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +                logging.error('No app id available for openexchangerates')
running this code without an app id would mean you'd get a 403 response back.
so shouldn't this be an error if this code will not work without an app id?

2017-09-12 21:15 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +                response_json = response.json()
what additional granularity would this provide, since we would see a json decode error in the exception type even if message was none.
IMO catching specific exceptions would be useful if I was following some API docs, but they don't have an official python API client, so if there was an error, we don't know exactly what it would mean regardless.

2017-09-12 22:44 UTC, jdmulloy requested changes

2017-09-12 22:44 UTC, jdmulloy commented on course_discovery/apps/api/v1/views/currency.py
> +                logging.error('No app id available for openexchangerates')
Is using this feature going to become a requirement for non edx deployments? If this feature is optional then there should be a flag to enable/disable it. Either way I would argue that this should be a warning and the code should still operate, just without the exchange rate information.

2017-09-12 22:44 UTC, jdmulloy commented on course_discovery/apps/api/v1/views/currency.py
> +                response.status_code, response_json.get('message'), type(e).__name__
Depending on where the failure occurs in the try block ```response.status_code``` or ```response_json.get()``` may not exist, which will cause this line to throw an exception. Logging just the exception type name and message is probably sufficient here. If you want to log the HTTP status code and/or the response body, you'll need to check that they exist before trying to use them.

2017-09-13 14:55 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +                logging.error('No app id available for openexchangerates')
this is a standalone endpoint at the moment not called by anything.
The feature we're building would not need to be used by non edx deployments. However, we may end up building the code to call this as an npm package only installed for edx, or some javascript included in the edx templates, so it won't necessarily need a feature flag to be edx only.
If we log an error the code will still operate. This is not like raising an exception, correct?
However, we'd want to know that something broke so we could look into it

2017-09-13 15:13 UTC, feanil commented on course_discovery/apps/api/v1/views/currency.py
> +                response_json = response.json()
@MatthewPiatetsky if you don't catch the json decode exception differently, you will end up throwing another exception in your except clause because it assumes that the `response_json` variable is defined and is a python dict.  When you do `response_json.get()` it probably throw a name error.

2017-09-13 15:15 UTC, feanil commented on course_discovery/apps/api/v1/views/currency.py
> +                logging.error('No app id available for openexchangerates')
@MatthewPiatetsky I think it makes sense to log this but I thin you should log at the info or warning level rather than error.

2017-09-13 15:22 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +                response_json = response.json()
@jdmulloy suggested above to only use the exception message and type, so I am no longer logging those

2017-09-13 15:24 UTC, feanil commented on course_discovery/apps/api/v1/views/currency.py
> +                response_json = response.json()
You may want to log `respons.text` as this might have more information on why the call failed. eg. The server keeps sending you their 500 page content.

2017-09-13 15:27 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +                response.status_code, response_json.get('message'), type(e).__name__
changed to log exception type name and message

2017-09-13 15:35 UTC, feanil commented on course_discovery/apps/api/v1/views/currency.py
> +                response.status_code, response_json.get('message'), type(e).__name__
You want `response.text` which will work even if the content is not json.   looking into the json won't if the content is not json.

2017-09-13 15:42 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/currency.py
> +                response.status_code, response_json.get('message'), type(e).__name__
that is what i'm currently using

2017-09-13 15:44 UTC, feanil approved these changes

2017-09-13 15:50 UTC, jdmulloy approved these changes
This looks good.

2017-09-21 18:59 UTC, merged