WIP: Add translations to the Subjects model
openedx/course-discovery pull request #1129
Opened 2017-09-20 17:30 UTC by BenjiLee

@edx/learner-heart 

Phase 1 (https://openedx.atlassian.net/browse/LEARNER-2615) of https://openedx.atlassian.net/browse/LEARNER-2314

* Add django-parler to requirements
* Install Django-parler (this step may be different since we configure prod in a different repo)
* Create migration to add translations table for subjects
* Copy data to new table.
* Modify api to look up and return new fields without changing the response structure
* Update admin interface to make the unused fields to be uneditable.

2017-09-21 20:31 UTC, amangano-edx commented on course_discovery/apps/api/v1/views/subjects.py
> +        return serializers.SubjectSerializer.prefetch_queryset(self.request.query_params.get('language', 'en'))
We should use the default from `django.settings`, rather than hardcoding this to `en`, as open source users may default to something other than en.

2017-09-21 20:32 UTC, amangano-edx commented on course_discovery/apps/course_metadata/admin.py
> +    exclude = ('name', 'subtitle', 'description')
Could you add a comment explaining why we need to exclude these?

2017-09-21 20:33 UTC, amangano-edx commented on course_discovery/apps/course_metadata/admin.py
>      list_display = ('uuid', 'name', 'slug',)
name should probably be excluded as well.

2017-09-21 20:35 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0058_auto_20170919_1927.py
> +        ),
Should we also build an index on language code since we'll be querying by it a lot?

2017-09-21 20:36 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0059_make_translations_table.py
> +    for object in Subject.objects.all():
Is object a special word in python?

2017-09-21 20:37 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0059_make_translations_table.py
> +        object.save()   # Note this only calls Model.save()
The forward_func didn't make any modifications to the master object, so I don't see why the backwards_func would need to. The backwards_func should probably just clear the translations for each master object from the translations table.

2017-09-21 20:43 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0059_make_translations_table.py
> +            return translations.get(language_code=settings.PARLER_DEFAULT_LANGUAGE_CODE)
What is `PARLER_DEFAULT_LANGUAGE_CODE` and how is it different from our default language code?

2017-09-21 20:43 UTC, amangano-edx commented on course_discovery/apps/course_metadata/models.py
> +class Subject(TranslatableModel, TimeStampedModel):
Does mixin order matter here?

2017-09-21 20:47 UTC, amangano-edx commented on course_discovery/apps/course_metadata/models.py
> +        verbose_name = _("Subject model translations")
nit: inconsistent quote usage.

2017-09-21 20:49 UTC, amangano-edx commented on course_discovery/settings/base.py
> -LANGUAGE_CODE = 'en-us'
We should be careful about making this change, as it might affect how strings are extracted into .po files and made available to transifex.

2017-09-21 20:54 UTC, BenjiLee commented on course_discovery/settings/base.py
> +PARLER_LANGUAGES = {
This should be moved to edx configuration repo

2017-09-21 20:55 UTC, BenjiLee commented on course_discovery/settings/devstack.py
> +LANGUAGE_CODE = 'en'
This will be removed.

2017-09-22 13:44 UTC, BenjiLee commented
@amangano-edx I tried to name the fields in the new table to the same ones in the original table. SQL allows this, but Django parler throws an error because it's sharing the same field name.

2017-09-22 13:47 UTC, BenjiLee commented on course_discovery/apps/course_metadata/models.py
> +class Subject(TranslatableModel, TimeStampedModel):
I don't believe it should. Both models have super's on their init method and do not share method namespace.

2017-09-22 13:54 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0059_make_translations_table.py
> +    for object in Subject.objects.all():
Addressed

2017-09-22 13:56 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0059_make_translations_table.py
> +            return translations.get(language_code=settings.PARLER_DEFAULT_LANGUAGE_CODE)
It's the default language code that parler uses. By default it is the same as the LANGAUGE CODE but I think it's better to be explicit about it since we are using it for parler.

2017-09-22 18:43 UTC, amangano-edx commented
@BenjiLee do you have any insight as to why parlor doesn't allow the field names to be the same?

2017-09-25 12:15 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0058_auto_20170919_1927.py
> +        ),
I don't believe there will be any queries for the language code specifically on the Subject Translations table. The query accesses the Subjects model, when then references the Subjects Translations model by ID.

2017-09-25 12:17 UTC, BenjiLee commented
@amangano-edx It's probably because of the usability we gain from Parler. It allows us to reference the SubjectTranslations model directly from the Subjects model. 

Example:
>>> subject = Subject.objects.all()[0]
>>> subject.get_current_language() 
'en'
>>> subject.name
'english name in subjects table'
>>> subject.name_t
'english name in subjects translations table'

2017-09-25 17:34 UTC, bderusha requested changes

2017-09-25 17:34 UTC, bderusha commented on course_discovery/apps/course_metadata/migrations/0058_auto_20170919_1927.py
> +                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='course_metadata.Subject')),
I'm assuming`master` is a parler default field name?

2017-09-25 17:34 UTC, bderusha commented on course_discovery/apps/course_metadata/migrations/0058_auto_20170919_1927.py
> +            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False,
Will this do the right thing?  Since the `name_t` field lives in another table and now has multiple values per "master" record?

2017-09-25 17:34 UTC, bderusha commented on course_discovery/apps/course_metadata/migrations/0059_make_translations_table.py
> +            language_code=settings.LANGUAGE_CODE,
NIT: should this be the `PARLER_DEFAULT_LANGUAGE_CODE`

2017-09-25 17:34 UTC, bderusha commented on course_discovery/apps/course_metadata/migrations/0059_make_translations_table.py
> +            return translations.get()
If no translations exist for some reason this migration will not be able to run.  Should probably put in another `try...except` block and log an error if this happens but let the migration continue

2017-09-25 17:34 UTC, bderusha commented on course_discovery/apps/course_metadata/models.py
> +            raise ValidationError({'name_t': ['Subject with this Name and Parger already exists', ]})
SpellCheck:  `Parger` VS `Partner` :)

2017-09-25 17:34 UTC, bderusha commented on course_discovery/settings/base.py
> +        {'code': 'es', },
Makes sense to have the default be English in this repo...but probably not Spanish

2017-09-25 17:34 UTC, bderusha commented on course_discovery/settings/base.py
> +         'fallbacks': ['en'],  # defaults to PARLER_DEFAULT_LANGUAGE_CODE
do we just want to use the default here then?

2017-09-25 17:34 UTC, BenjiLee commented on course_discovery/apps/course_metadata/models.py
> +            raise ValidationError({'name_t': ['Subject with this Name and Parger already exists', ]})
Definitely Parger

2017-09-25 17:38 UTC, BenjiLee commented on course_discovery/settings/base.py
> +PARLER_LANGUAGES = {
https://github.com/edx/configuration/pull/4108

2017-09-25 17:38 UTC, BenjiLee commented on course_discovery/settings/base.py
> -LANGUAGE_CODE = 'en-us'
Verified that transifex is using 'en'

2017-09-25 17:39 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0058_auto_20170919_1927.py
> +            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False,
It will use the default language.

2017-09-25 17:40 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0059_make_translations_table.py
> +            return translations.get()
I don't think there is a way to create a subject without the default language. Let me test this

2017-09-25 17:46 UTC, bderusha commented on course_discovery/apps/course_metadata/models.py
> +    master = models.ForeignKey(Subject, related_name='translations', null=True)
Prefer `subject` to `master` as best practice

2017-09-25 17:57 UTC, BenjiLee commented on course_discovery/apps/course_metadata/models.py
> +    master = models.ForeignKey(Subject, related_name='translations', null=True)
Django-parler requires that we use the keyword `master`

2017-09-25 18:02 UTC, bderusha commented on course_discovery/apps/course_metadata/models.py
> +    master = models.ForeignKey(Subject, related_name='translations', null=True)
gross 👍 :shipit:

2017-09-25 18:04 UTC, BenjiLee commented on course_discovery/settings/base.py
> +        {'code': 'es', },
removed here. added in the configuration repo

2017-09-25 18:04 UTC, BenjiLee commented on course_discovery/settings/base.py
> +         'fallbacks': ['en'],  # defaults to PARLER_DEFAULT_LANGUAGE_CODE
fixed

2017-09-25 18:04 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0059_make_translations_table.py
> +            language_code=settings.LANGUAGE_CODE,
updated

2017-09-25 20:16 UTC, bderusha approved these changes
:shipit:

2017-10-03 14:18 UTC, amangano-edx commented on course_discovery/apps/api/tests/test_serializers.py
>              'subtitle': subject.subtitle,
Should this be set to `subject.subtitle_t`?

2017-10-03 14:18 UTC, amangano-edx commented on course_discovery/apps/course_metadata/admin.py
> +    exclude = ('name', 'subtitle', 'description')
Are we able to set `name_t`, `subtitle_t`, and `description_t`?

2017-10-03 14:21 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0061_make_translations_table.py
> +# -*- coding: utf-8 -*-
Nit: The names of these two migration files are confusing. This one is called `_make_translations_table`, but it's actually just filling in the existing table with data. The other migration is called '_update_subject_models', but it's actually creating a completely new model/index.

2017-10-03 14:23 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0061_make_translations_table.py
> +        subject.save()  # Note this only calls Model.save()
I don't see why we're doing anything to the original subjects table in the backwards function. The original subjects table wasn't touched in the forwards function at all, only the translations table was. We should be reversing whatever was done to the translations table in the forwards_func here.

2017-10-03 14:25 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
Just curious, but why did you decide to add an index here? I thought we came to the conclusion that an index wouldn't make sense for this field since there is not much data here.

2017-10-03 14:26 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                ('subtitle_t', models.CharField(blank=True, max_length=255, null=True)),
Any chance of subtitle being > 255 characters?

2017-10-03 14:27 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                ('name_t', models.CharField(max_length=255)),
Why can't name_t be blank/null?

2017-10-03 14:28 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations',
Should we disallow nulls here? It would be weird to have a translation with no master subject.

2017-10-03 14:31 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                                                            populate_from='name_t'),
Shouldn't the slug be based on the canonical name instead of the translated name?

2017-10-03 14:32 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +            unique_together=set([('partner', 'slug'), ('partner', 'uuid')]),
Why do we need to change the constraints on the original table?

2017-10-03 14:36 UTC, amangano-edx commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    Subject)
Nit: line 23 seems really short compared to line 22, so I think we can probably just leave subject on line 23.

2017-10-03 14:38 UTC, BenjiLee commented on course_discovery/apps/api/tests/test_serializers.py
>              'subtitle': subject.subtitle,
Will fix

2017-10-03 14:38 UTC, BenjiLee commented on course_discovery/apps/course_metadata/admin.py
> +    exclude = ('name', 'subtitle', 'description')
We are

2017-10-03 14:39 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
This was automatically created, but I will take a look.

2017-10-03 14:40 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                ('subtitle_t', models.CharField(blank=True, max_length=255, null=True)),
These values were copied from the original subject's subtitle field. While I agree that a subtitle would be short, what are the advantages to shortening this now?

2017-10-03 14:40 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                ('name_t', models.CharField(max_length=255)),
You need to have a name_t in order to create the subject.

2017-10-03 14:42 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations',
This was automatically created. I'll look into this.

2017-10-03 14:44 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                                                            populate_from='name_t'),
The translated name will eventually be the canonical name. If we used the subject.name instead of subject.name_t, when a subject is created, the slug will be 'null'. In the clean up phase, it will be changed back to name from name_t.

2017-10-03 14:45 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +            unique_together=set([('partner', 'slug'), ('partner', 'uuid')]),
These constraints are the ones that are being kept. The one we are dropping is partner<->name_t which now exists on different tables. The dropped constraints are validated via a overriden `validate_unique` method.

2017-10-03 14:46 UTC, BenjiLee commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    Subject)
will do. Auto imported wanted it this way. If it fails isort, i will set it to as is.

2017-10-03 15:17 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                ('subtitle_t', models.CharField(blank=True, max_length=255, null=True)),
Ok, just making sure we've thought about that, as the DB would limit this field to 255 characters based on the current settings.

2017-10-03 15:18 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                                                            populate_from='name_t'),
Hmm, does this complicate things from a subject-creation standpoint? Doesn't it mean that the subject-translation will need to be created and saved before the master, as otherwise name_t wouldn't be populated yet?

2017-10-03 15:22 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                                                            populate_from='name_t'),
That's the magic of parler. In the admin, when creating a subject, the fields shown to you are combined from the Subjects and Subjects translations model. It looks like the original  subjects form.

2017-10-04 18:01 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0061_make_translations_table.py
> +# -*- coding: utf-8 -*-
updated.

2017-10-04 18:05 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0061_make_translations_table.py
> +        subject.save()  # Note this only calls Model.save()
After this PR is merged, when a user creates a subject, the data goes in the subject translations model and no longer the original Subjects model. When migrating backwards, it will take the default language and set the original subject models now deprecated fields.

Example:

Before PR:
subject.name -> The name of the subject

After PR:
subject.name -> No longer used
subject.name_t -> The new required field.

When creating a new topic, subject.name does not get populated. When migrating backwards, subject.name_t will be migrated in the backwards_func() to subject.name.

2017-10-04 18:08 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
Looks like it's explicitly set in the django-parler package. Leaving this as is for now.

2017-10-04 18:21 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0060_update_subject_models.py
> +                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations',
I agree with you and I'm not sure why it's in the documentation so I asked a question https://github.com/django-parler/django-parler/issues/196

2017-10-05 20:21 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0061_migrate_subjects_data.py
> +            translation = SubjectTranslation.objects.filter(master_id=subject.pk)
Should we scope this to just the `PARLER_DEFAULT_LANGUAGE_CODE`? What if a subject has more than one translation?

2017-10-05 20:22 UTC, amangano-edx commented on course_discovery/apps/course_metadata/migrations/0061_migrate_subjects_data.py
> +            logger.exception('Migrating data from SubjectTranslation for master_id={} DoesNotExist')
I think you forgot to call `format` on this string.

2017-10-05 20:24 UTC, amangano-edx commented on course_discovery/apps/course_metadata/models.py
> +    def validate_unique(self, *args, **kwargs):
Note that this might not run in some cases, such as when loading data directly into the database via mySql

2017-10-05 20:26 UTC, amangano-edx commented on course_discovery/apps/course_metadata/tests/test_signals.py
> +            if model in [DataLoaderConfig, SubjectTranslation] or 'abstract' in model.__name__.lower():
Why is this necessary?

2017-10-05 20:26 UTC, amangano-edx commented on course_discovery/settings/base.py
> +PARLER_LANGUAGES = {
Is this just default config now?

2017-10-05 20:27 UTC, amangano-edx commented on course_discovery/settings/base.py
> +        {'code': 'en', },
Can we reference a constant for this?

2017-10-05 20:27 UTC, amangano-edx approved these changes
A few more questions and minor stuff. Otherwise LGTM

2017-10-06 13:25 UTC, BenjiLee commented on course_discovery/settings/base.py
> +PARLER_LANGUAGES = {
Correct

2017-10-06 13:26 UTC, BenjiLee commented on course_discovery/settings/base.py
> +        {'code': 'en', },
Maybe `LANGUAGE_CODE`?

2017-10-06 13:26 UTC, BenjiLee commented on course_discovery/apps/course_metadata/tests/test_signals.py
> +            if model in [DataLoaderConfig, SubjectTranslation] or 'abstract' in model.__name__.lower():
SubjectTranslation does not need a factory for testing.

2017-10-06 13:53 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0061_migrate_subjects_data.py
> +            logger.exception('Migrating data from SubjectTranslation for master_id={} DoesNotExist')
shh...

2017-10-06 13:55 UTC, BenjiLee commented on course_discovery/apps/course_metadata/models.py
> +    def validate_unique(self, *args, **kwargs):
Yep. Well aware of this. There is no database level validation across foreign keys :(

2017-10-06 13:55 UTC, BenjiLee commented on course_discovery/apps/course_metadata/migrations/0061_migrate_subjects_data.py
> +            translation = SubjectTranslation.objects.filter(master_id=subject.pk)
Fetching a subject returns you the default by default.

2017-10-06 18:00 UTC, merged

2017-10-06 18:33 UTC, bderusha commented
🔥 🎸 🎆