Course team would be able to edit existing instructor of same org.
openedx/course-discovery pull request #1134
Opened 2017-09-25 14:00 UTC by attiyaIshaque

2017-09-27 09:12 UTC, attiyaIshaque commented
@asadazam93 and @tasawernawaz please review it. Thanks

2017-09-27 11:21 UTC, tasawernawaz requested changes

2017-09-27 11:21 UTC, tasawernawaz commented on course_discovery/apps/course_metadata/lookups.py
> +            organization_id = False
why `organization_id` default is `False` rather than `None` ?

2017-09-27 11:21 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +            'uuid': obj.uuid if obj.uuid else None,
is there any chance that `uuid` is `None` ?

2017-09-27 11:21 UTC, tasawernawaz commented on course_discovery/apps/publisher/templates/publisher/_personLookup.html
> +        <span style="display:none">{{ organization_id }}</span>
use css class `hidden` to hide this.

2017-09-27 11:21 UTC, tasawernawaz commented on course_discovery/apps/publisher/templates/publisher/course_run/edit_run_form.html
> +                    <div id="course_user_role" style="display:none">{{ course_user_role }}</div>
same here, use css class to hide on both these lines.

2017-09-27 11:21 UTC, tasawernawaz commented on course_discovery/static/js/publisher/instructors.js
> +function renderSelectedInstructor(id, name, image, uuid, organization_id) {
what if `organization_id` is not available ?

2017-09-27 11:21 UTC, tasawernawaz commented on course_discovery/static/js/publisher/instructors.js
> +    if (course_user_role == "course_team") {
It will be good if we can remove hard coded user role from here ? and use it as data attribute.

2017-09-27 11:25 UTC, tasawernawaz commented
When we add instructor we use to add instructor on Drupal as well. I am not sure that we need to do same here while editing instructor or not. May be after running `refresh_course_metadata` will override changes made by course team. Please confirm this before merging.

2017-09-27 12:06 UTC, attiyaIshaque commented on course_discovery/apps/course_metadata/lookups.py
> +            organization_id = False
@tasawernawaz I will change it to `None`.

2017-09-27 12:06 UTC, attiyaIshaque commented on course_discovery/apps/publisher/forms.py
> +            'uuid': obj.uuid if obj.uuid else None,
Added for the safety check.

2017-09-27 12:06 UTC, attiyaIshaque commented on course_discovery/apps/publisher/templates/publisher/_personLookup.html
> +        <span style="display:none">{{ organization_id }}</span>
Sure.

2017-09-27 12:07 UTC, attiyaIshaque commented on course_discovery/apps/publisher/templates/publisher/course_run/edit_run_form.html
> +                    <div id="course_user_role" style="display:none">{{ course_user_role }}</div>
Sure.

2017-09-27 12:07 UTC, attiyaIshaque commented on course_discovery/static/js/publisher/instructors.js
> +function renderSelectedInstructor(id, name, image, uuid, organization_id) {
It wouldn't check further.

2017-09-27 12:10 UTC, attiyaIshaque commented on course_discovery/static/js/publisher/instructors.js
> +    if (course_user_role == "course_team") {
I have checked it dynamically here `course_user_role = $('#course_user_role').text(),`

2017-09-27 12:14 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +            'uuid': obj.uuid if obj.uuid else None,
I mean uuid can't be `None`, if it can't then no need to add this check

2017-09-27 12:14 UTC, asadazam93 commented
@tasawernawaz we are using the people [api](https://github.com/edx/course-discovery/blob/fa251757dae29dbff2380728790116be9a498fe2/course_discovery/apps/api/v1/views/people.py). I think this api will update the marketing site as well.

2017-09-27 12:17 UTC, attiyaIshaque commented on course_discovery/apps/publisher/forms.py
> +            'uuid': obj.uuid if obj.uuid else None,
okay. i will remove this check.

2017-09-27 12:44 UTC, attiyaIshaque commented
@tasawernawaz I have addressed your comments.

2017-09-27 13:09 UTC, tasawernawaz approved these changes

2017-09-28 10:46 UTC, asadazam93 approved these changes

2017-09-28 11:38 UTC, merged