updated people api create to use group authentication
openedx/course-discovery pull request #1140
Opened 2017-09-27 11:25 UTC by asadazam93

## [EDUCATOR-1383](https://openedx.atlassian.net/browse/EDUCATOR-1383)

### Description
https://github.com/edx/course-discovery/blob/fa251757dae29dbff2380728790116be9a498fe2/course_discovery/apps/api/v1/views/people.py#L26
previously this endpoint allowed any authenticated user to create a new person entity.
I have added one more method of authentication to create a new person. i.e group. The authenticated user has to be part of any group to be able to create a new person. As course team users of the publisher are the people who mostly use this endpoint and they are neither staff nor superusers so using both these permissions was not going be sufficient. The course team users are part of a group so I have used groups as a method of authentication (any non verified or non staff member is not a part of any group)

**Sandbox**
- N/A

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] @awaisdar001  
- [ ] @attiyaIshaque  

### Post-review
- [ ] Rebase and squash commits

2017-09-28 07:50 UTC, attiyaIshaque requested changes

2017-09-28 07:50 UTC, attiyaIshaque commented on course_discovery/apps/api/decorators.py
> +def checkgroup(create_func):
Please try finding a more appropriate name for this method. Maybe like `checkusergroup`.

2017-09-28 07:50 UTC, attiyaIshaque commented on course_discovery/apps/api/decorators.py
> +        logger.exception('Permission denied. User has no groups')
Please add username in the logger.exception.

2017-09-28 07:50 UTC, attiyaIshaque commented on course_discovery/apps/api/v1/tests/test_views/test_people.py
> +        self.user.groups.add(Group.objects.get(name=INTERNAL_USER_GROUP_NAME))
you can do it in this way
```
group = Group.objects.get(name=INTERNAL_USER_GROUP_NAME)
```
and also use it here `self.user.groups.remove(Group.objects.get(name=INTERNAL_USER_GROUP_NAME))`

2017-09-30 14:51 UTC, clintonb requested changes
These permissions are too permissive. Users should be part of a specific group/groups, not just any group. Be explicit about who is allowed to access the endpoint. Also, use a proper [permissions class](http://www.django-rest-framework.org/api-guide/permissions/), not a custom decorator.

2017-10-02 08:09 UTC, asadazam93 commented
@clintonb the course team users can be a part of any group (150+ groups exist and more groups are being added with time) so I am not sure how can we use specific groups. Please share your thoughts. And I will replace the decorator with a custom permission class as soon as this groups issue is resolved.

2017-10-02 12:52 UTC, clintonb commented
Find some commonality in the groups. Associate them with an organization, set a common prefix (not a great idea). Do something that is more secure and properly uses Django permissions.

2017-10-02 13:16 UTC, asadazam93 commented
@clintonb one possible solution that I have in mind is that we create a new group (say `course_team`) and assign all course team users to this group. This way we will be able to identify course team users and set a custom permission class for that group. 

Currently there is no simpler way to identify a course team member but the fact that they are assigned to some group (the group list is a long mutable list with no commonality so we can not be sure of exactly which group)

2017-10-02 13:38 UTC, clintonb commented
The new group should be called "Course Creators". How do you intend to keep this group updated?

2017-10-04 10:55 UTC, asadazam93 commented
@clintonb we will firstly need to write a management to add the current course team users to this new group and then all new course team users will also need to be added to this group.It would be more secure but at the same time it would complicate the solution. I was going for a more simpler solution by checking if the user is part of any group because a user which is a part of a group is in almost all cases a staff member or some internal user. And since only staff members or superusers can add or change group it seems to be secure enough. What are your thoughts about this?

2017-10-04 13:30 UTC, clintonb commented
My thoughts are that we should go for the correct solution when it comes to security. There is no telling what will change in the future regarding groups and who is in the groups. Permissions should be explicit, not implicit.

2017-10-30 13:49 UTC, schenedx commented
@clintonb Asking the escalation team to solve the mess we have with Publisher Permissions is too huge of an undertaking in this context, in my opinion. 
We had a conversation about this in our Educator Triage meeting. We will create a ticket to track the need of your proposal. Shelby will schedule that. We will just take the easiest route here to fix the permission problem. If you have concerns on this plan, please come and talk with Scott and me.

2017-10-31 11:54 UTC, awaisdar001 requested changes

2017-10-31 11:54 UTC, awaisdar001 commented on course_discovery/apps/publisher/permissions.py
> +        logger.exception('Permission denied. User [%s] has no groups', request.user.username)
maybe logger.info or error?

2017-10-31 11:54 UTC, awaisdar001 commented on course_discovery/apps/api/v1/tests/test_views/test_people.py
> +        Person.objects.all().delete()
Why you are deleting the objects?

2017-10-31 14:22 UTC, awaisdar001 approved these changes

2017-10-31 14:22 UTC, awaisdar001 commented on course_discovery/apps/api/v1/tests/test_views/test_people.py
> +        """ Verify group is required when creating a person. """
Only one nit in the docstring. looks good to me.  https://openedx.atlassian.net/wiki/spaces/EDUCATOR/pages/251528559/Coding+Practices

2017-11-01 10:24 UTC, attiyaIshaque approved these changes
Looks good to me. 👍

2017-11-01 10:31 UTC, merged

2017-11-06 20:26 UTC, schenedx commented
The changes here blocked marketing site from accessing instructors API.
Updated the implementation of this on https://github.com/edx/course-discovery/pull/1207