[WIP] -- ENT-657: Change UTM Source value in API results returned by discovery API
openedx/course-discovery pull request #1145
Opened 2017-09-29 11:01 UTC by saleem-latif

Hi,

This PR contains changes for [ENT-657](https://openedx.atlassian.net/browse/ENT-657).

**Note:**
Currently I am working on the tests for the changes, I will update the PR once tests are ready.

**Jira Ticket:**   [ENT-652](https://openedx.atlassian.net/browse/ENT-652) and [ENT-657](https://openedx.atlassian.net/browse/ENT-657)

**Description:**
The `MinimalCourseRunSerialize`r includes the `marketing_url` and appends the UTM parameters. We will need to modify the `get_marketing_url_for_user` function which appends the UTM parameters to the `marketing_url`.
The information that the partner enters on the API access request form is stored in the LMS database using the `ApiAccessRequest` model. We will need to add an API view in the `api_admin` Django app which will return the `ApiAccessRequest` records for the current user. The `api_admin` data model allows for a single user to have many `ApiAccessRequest` records. The discovery service will need to make call the `api_admin` API endpoint, pick the first `ApiAccessRequest` record returned, and use the `company_name` to populate the `utm_source` value on the marketing URL.

2017-09-29 17:45 UTC, brittneyexline reviewed
looks like it's on the right track!

2017-09-29 17:45 UTC, brittneyexline commented on course_discovery/apps/api/serializers.py
> +        utm_source = get_utm_source_for_user(partner, user, default=user.username)
based on this function name, maybe it would make sense to read the waffle switch from within this function to toggle between user.username and the api call, then it would all be nicely contained in that function.

2017-09-29 17:45 UTC, brittneyexline commented on course_discovery/apps/api/serializers.py
> +        utm_source = get_utm_source_for_user(partner, user, default=user.username)
it would also make it easier to handle errors from calling the lms and falling back to the username.

2017-10-03 20:10 UTC, douglashall requested changes
Some inline comments to address. Also, can you create a data migration for the waffle switch?

2017-10-03 20:10 UTC, douglashall commented on course_discovery/apps/api/serializers.py
> +    return default
Remove default parameter from method signature and simplify to:
```
default = user.username
if waffle.switch_is_active('user_company_name_as_utm_source_value') and partner.lms_url:
    api_access_request = LMSAPIClient(partner.lms_url).get_api_access_request(user)
    if api_access_request:
        return api_access_request['company_name']
return default
``

2017-10-03 20:10 UTC, douglashall commented on course_discovery/apps/core/api_client/lms.py
> +        cache_key = get_cache_key(username=user.username, resourse=resource)
typo: `resourse`

2017-10-03 20:10 UTC, douglashall commented on course_discovery/apps/core/api_client/lms.py
> +        client = EdxRestApiClient(self._url, oauth_access_token=user.access_token)
Initialize `EdxRestApiClient` in `__init__`.

2017-10-03 20:10 UTC, douglashall commented on course_discovery/apps/core/api_client/lms.py
> +            return response['results'][0]
Let's log a warning here if the user had more than one API Access Request models associated with their account.

2017-10-04 10:27 UTC, saleem-latif commented on course_discovery/apps/core/api_client/lms.py
> +        client = EdxRestApiClient(self._url, oauth_access_token=user.access_token)
@douglashall I initialized it here as I am using `User's access_token` instead of global `JWT/Access Token` associated with the service user. I think since we are fetching user specific data in this method, it makes sense to initialize APIClient inside the method.

2017-10-04 12:23 UTC, douglashall commented on course_discovery/apps/core/api_client/lms.py
> +        client = EdxRestApiClient(self._url, oauth_access_token=user.access_token)
The `__init__` function of `LMSAPIClient` should take a Site and User as parameters and construct the `EdxRestApiClient` using them.

2017-10-04 13:35 UTC, saleem-latif commented
@douglashall , @brittneyexline  I have made the changes you suggested, please take another look.

2017-10-04 14:33 UTC, douglashall commented on course_discovery/apps/core/api_client/lms.py
> +            return None
Let's rework this a bit more:
```
api_access_request = cache.get(cache_key)
if not api_access_request:
    try:
        results = getattr(self.client, resource).get(**query_parameters)['results']
        if len(results) > 1:
            logger.warning('Multiple APIAccessRequest models returned from LMS API for user [%s].', user.username)
        api_access_request = results[0]
        cache.set(cache_key, api_access_request, 60 * 60)
    except (SlumberBaseException, ConnectionError, Timeout):
        logger.exception('Failed to fetch API Access Request from LMS for user "%s"', user.username)
    except (IndexError, KeyError):
        logger.exception('APIAccessRequest model not found for user [%s]', user.username)

return api_access_request

2017-10-05 18:10 UTC, douglashall approved these changes

2017-10-05 18:27 UTC, douglashall commented on course_discovery/apps/api/serializers.py
> +    return default
As @clintonb pointed out, the ApiAccessRequest.company_name field is not unique. Let's do this instead:
```
utm_source = user.username
if waffle.switch_is_active('use_company_name_as_utm_source_value') and partner.lms_url:
    lms = LMSAPIClient(partner.site, user)
    api_access_request = lms.get_api_access_request(user)

    if api_access_request:
        utm_source = '{}:{}'. format(utm_source, api_access_request['company_name']

return utm_source
```

2017-10-05 18:31 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    return default
Please see http://www.bytefive.com/blogs/understanding-utm_source-utm_medium-and-utm_campaign.

2017-10-05 18:43 UTC, douglashall commented on course_discovery/apps/api/serializers.py
> +    return default
Thanks @clintonb. One more edit:
```
utm_source = user.username
if waffle.switch_is_active('use_company_name_as_utm_source_value') and partner.lms_url:
    lms = LMSAPIClient(partner.site, user)
    api_access_request = lms.get_api_access_request(user)

    if api_access_request:
        utm_source = '{} {}'.format(utm_source, api_access_request['company_name'])

return utm_source_encode(utm_source)

def utm_source_encode(utm_source):
    """ Return encoded version of utm_source value. """
    # Remove all non-word characters (everything except numbers and letters)
    utm_source = re.sub(r"[^\w\s]", '', s)

    # Replace all runs of whitespace with a single dash
    utm_source = re.sub(r"\s+", '-', s)

    return utm_source
```

2017-10-05 18:45 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    return default
Keep it simple: [`slugify`](https://docs.djangoproject.com/en/1.11/ref/utils/#django.utils.text.slugify)

2017-10-06 11:01 UTC, saleem-latif commented
@douglashall I have updated the code according to the suggestion.

2017-10-06 11:14 UTC, douglashall commented
This is looking good to me. @clintonb Do you think we need to cache in memory or will memcached be good enough?

2017-10-11 13:50 UTC, douglashall commented
@saleem-latif Can you rebase this when you get a chance?

2017-10-11 13:50 UTC, douglashall commented
@clintonb We are going to move forward with this approach. If it becomes a problem, we can revert.

2017-10-12 07:40 UTC, saleem-latif commented
@douglashall rebased and the build is green.

2017-10-12 09:17 UTC, merged

2017-10-12 15:52 UTC, clintonb commented
This is throwing errors on stage:

```
Oct 12 15:46:03 ip-10-3-120-228 [service_variant=discovery][course_discovery.apps.core.api_client.lms] ERROR [ip-10-3-120-228  2522] [/edx/app/discovery/discovery/course_discovery/apps/core/api_client/lms.py:79] - Failed to fetch API Access Request from LMS for user "learner-test".
Traceback (most recent call last):
  File "/edx/app/discovery/discovery/course_discovery/apps/core/api_client/lms.py", line 68, in get_api_access_request
    results = getattr(self.client, resource).get(**query_parameters)['results']
  File "/edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/slumber/__init__.py", line 155, in get
    resp = self._request("GET", params=kwargs)
  File "/edx/app/discovery/venvs/discovery/lib/python3.5/site-packages/slumber/__init__.py", line 101, in _request
    raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
slumber.exceptions.HttpClientError: Client Error 401: https://courses.stage.edx.org/api-admin/api/v1/api_access_request/
```

2017-10-12 15:55 UTC, clintonb commented
You should discontinue using the user's access token because (1) we want to get away from bearer tokens and (2) you don't have to worry about permissions. See https://github.com/edx/course-discovery/blob/295fa22d02bedc86d6908bfec75b199c1a20434f/course_discovery/apps/core/models.py#L124-L127.