Fix the Course run filters in *In Development* tab.
openedx/course-discovery pull request #1164
Opened 2017-10-05 15:34 UTC by attiyaIshaque

2017-10-10 09:29 UTC, waheedahmed requested changes

2017-10-10 09:29 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +    def get_filters_status(self, course_runs, filter_func):
I don't think it's worth doing all this stuff to just get already defined statuses, how much time it will take if there are 2K+ course runs loading on dashboard?

Instead you can simply store these statuses in some variables and use them on both places. https://github.com/edx/course-discovery/blob/549a00b4ba7dccce376da88e11b8c9914825bebb/course_discovery/apps/publisher/wrappers.py#L226

2017-10-10 09:48 UTC, attiyaIshaque commented on course_discovery/apps/publisher/views.py
> +    def get_filters_status(self, course_runs, filter_func):
@waheedahmed Sure I will change it in some variables. Thanks for explaining it.

2017-10-10 10:59 UTC, attiyaIshaque commented
@waheedahmed I have addressed your requested changes.

2017-10-10 12:40 UTC, waheedahmed requested changes

2017-10-10 12:40 UTC, waheedahmed commented on course_discovery/apps/publisher/wrappers.py
> +    def get_courses_run_wrapper(cls, course_runs):
I think more appropriate name for this is `get_course_run_wrappers`.

2017-10-10 12:40 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        context['course_team_status'] = '%s|%s' % (CourseRunWrapper.Draft, CourseRunWrapper.AwaitingCourseTeamReview)
Use format.

2017-10-10 12:40 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        internal_user_course_runs = in_progress_course_runs.exclude(
I think you can reduce one query by combining count query here, same with course_team_course_runs.

2017-10-10 13:58 UTC, waheedahmed approved these changes
:+1:
Please remember to squash your commits

2017-10-11 14:02 UTC, noraiz-anwar approved these changes
👍

2017-10-11 14:03 UTC, merged