Fix instructor bio editing capability for all internal users.
openedx/course-discovery pull request #1173
Opened 2017-10-11 09:34 UTC by attiyaIshaque

2017-10-12 11:18 UTC, asadazam93 approved these changes

2017-10-13 06:03 UTC, tasawernawaz requested changes

2017-10-13 06:03 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
>              'uuid': obj.uuid,
you have already `uuid` here, why we need to save it again in `can_edit_instructor`.

2017-10-13 06:03 UTC, tasawernawaz commented on course_discovery/apps/publisher/templates/publisher/_personFieldLabel.html
> +<img src="{{ profile_image }}"/><span{% if can_edit_instructor %}  data-can-edit="{{ can_edit_instructor }}" {% endif %} data-uuid="{{ uuid }}" >{{ full_name }}</span>{% if organization_id %}<span>{{
possibly both 'data-can-edit' and 'data-uuid' will have same value. Can you use `True/Flase` for possible values of `can_edit_instructor` ?

2017-10-13 06:03 UTC, tasawernawaz commented on course_discovery/apps/publisher/templates/publisher/_personLookup.html
> +<table class="instructor-option" id="{{ uuid }}" {% if can_edit_instructor %}  data-can-edit="{{ can_edit_instructor }}" {% endif %}>
same here

2017-10-13 06:03 UTC, tasawernawaz commented
@attiyaIshaque If sandbox is ready please update the description with sandbox link.

2017-10-13 06:31 UTC, attiyaIshaque commented on course_discovery/apps/publisher/templates/publisher/_personFieldLabel.html
> +<img src="{{ profile_image }}"/><span{% if can_edit_instructor %}  data-can-edit="{{ can_edit_instructor }}" {% endif %} data-uuid="{{ uuid }}" >{{ full_name }}</span>{% if organization_id %}<span>{{
I got your point. Thanks, I will change it. :)

2017-10-13 07:13 UTC, attiyaIshaque commented
@tasawernawaz I have added the sandbox link.

2017-10-13 09:26 UTC, tasawernawaz approved these changes
Just a minor change requested.

2017-10-13 09:26 UTC, tasawernawaz commented on course_discovery/apps/course_metadata/lookups.py
> +                'can_edit_instructor': True if not result.profile_image_url else False,
you can replace `True if not result.profile_image_url else False` with `not result.profile_image_url`

2017-10-13 10:39 UTC, attiyaIshaque commented
@tasawernawaz I have addressed your requested change. Now I am merging it. Thanks

2017-10-13 10:39 UTC, merged