Refactor LMSAPIClient to use discovery service user instead of request user.
openedx/course-discovery pull request #1176
Opened 2017-10-12 16:16 UTC by douglashall

ENT-657

2017-10-12 17:12 UTC, clintonb requested changes

2017-10-12 17:12 UTC, clintonb commented on course_discovery/apps/core/api_client/lms.py
> +        self.client = EdxRestApiClient(site.partner.lms_url, oauth_access_token=site.partner.access_token)
Partner's use JWT access tokens, not bearer tokens (expected by `oauth_access_token`).

2017-10-12 17:15 UTC, douglashall commented on course_discovery/apps/core/api_client/lms.py
> +        self.client = EdxRestApiClient(site.partner.lms_url, oauth_access_token=site.partner.access_token)
Thanks. Pushing fix now.

2017-10-12 18:33 UTC, clintonb commented on course_discovery/apps/core/api_client/lms.py
>          cache_key = get_cache_key(username=user.username, resource=resource)
Since you're here, please remove the comment on line 74 as it is wrong. We don't require an access request for all clients. For example, none of the service users have requests. I, personally, don't have an access request. That comment will be confusing in the future.

2017-10-12 18:39 UTC, douglashall commented on course_discovery/apps/core/api_client/lms.py
>          cache_key = get_cache_key(username=user.username, resource=resource)
Done.

2017-10-12 19:10 UTC, clintonb approved these changes

2017-10-12 19:10 UTC, clintonb commented on course_discovery/apps/core/api_client/lms.py
> +                logger.warning('APIAccessRequest model not found for user [%s].', user.username)
This should be at the info level.

2017-10-13 08:04 UTC, saleem-latif approved these changes
LGTM

2017-10-13 10:09 UTC, clintonb requested changes
Your test class should be a py.test style class, if a class at all. See https://docs.pytest.org/en/latest/contents.html.

2017-10-13 10:09 UTC, clintonb commented on course_discovery/apps/core/tests/mixins.py
> +            "scope": "API Permissions"
That’s not a proper scope.

2017-10-13 10:09 UTC, clintonb commented on course_discovery/apps/core/tests/mixins.py
> +    def mock_access_token(self, partner, jwt_token="Test JWT"):
This is overkill. See https://github.com/edx/course-discovery/blob/5e45a193854a9ba15a782b27ed7d862d635fdc78/course_discovery/apps/publisher/api/v1/tests/test_views.py#L94-L95.

2017-10-13 12:40 UTC, saleem-latif commented on course_discovery/apps/core/tests/mixins.py
> +    def mock_access_token(self, partner, jwt_token="Test JWT"):
yes, I tried to use that at first but I had to use that decorator for almost all the new test cases, that resulted in a lot of repetition. I think using it with mixin gives us nice contained mocking and adding new test cases to this class also becomes easier.

2017-10-13 13:00 UTC, saleem-latif commented
@clintonb I have incorporated your feedback, please take another look

2017-10-13 14:04 UTC, clintonb commented on course_discovery/apps/core/tests/mixins.py
> +    def mock_access_token(self, partner, jwt_token="Test JWT"):
You only have four test cases. The mock will be cleaner, and slightly faster, than using `responses`.

2017-10-13 14:04 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +class TestGetUTMSourceForUser(LMSAPIClientMixin, unittest.TestCase):
The point of using `pytest` is to _not_ use `unittest`. See some example tests in https://github.com/edx/course-discovery/pull/1172.

2017-10-15 10:57 UTC, merged