Filters/SearchQuery returns correct results in Course Tab.
openedx/course-discovery pull request #1180
Opened 2017-10-18 13:27 UTC by attiyaIshaque

2017-10-19 11:33 UTC, awaisdar001 requested changes

2017-10-19 11:33 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_views.py
> +        {'search_text': 'N/A', 'expected': 0},
You should have some courses with `N/A` status so we are sure that they have been correctly returned.

2017-10-23 10:26 UTC, attiyaIshaque commented
@awaisdar001 I have addressed your requested change.

2017-10-23 10:52 UTC, awaisdar001 requested changes

2017-10-23 10:52 UTC, awaisdar001 commented on course_discovery/apps/publisher/views.py
> +            if keyword.lower() in str(CourseState.ApprovedByMarketing).lower():
Do we need to do `keyword.lower()` in every `elseif`? Can we avoid this and have `keyword_lower` variable?

2017-10-23 12:47 UTC, attiyaIshaque commented
@awaisdar001 Please review it again.

2017-10-24 05:22 UTC, awaisdar001 commented
@attiyaIshaque you having a failing `travis-ci`

2017-10-24 07:21 UTC, attiyaIshaque commented
@awaisdar001 I have rebased my branch. Build is green now.

2017-10-24 10:17 UTC, asadazam93 approved these changes
Looks good

2017-10-24 10:20 UTC, awaisdar001 approved these changes

2017-10-24 10:35 UTC, merged