EDUCATOR-1523 Fix Instructor photos size and dimensions.
openedx/course-discovery pull request #1198
Opened 2017-10-31 16:12 UTC by attiyaIshaque

2017-11-02 07:15 UTC, asadazam93 approved these changes

2017-11-02 07:53 UTC, Rabia23 requested changes

2017-11-02 07:53 UTC, Rabia23 commented on course_discovery/static/js/publisher/instructors.js
> +    if (input.files && imageFile) {
Why there is need of `input.files` in `if` condition? I think only `imageFile` is sufficient to check whether file exists or not.

2017-11-02 07:53 UTC, Rabia23 commented on course_discovery/static/js/publisher/instructors.js
> +        imageFile = input.files[0],
What if `input.files` is empty? It will throw an error because you are accessing an element from an empty array.

2017-11-02 10:37 UTC, attiyaIshaque commented on course_discovery/static/js/publisher/instructors.js
> +    if (input.files && imageFile) {
oh, my bad. I will remove the input.files condition

2017-11-02 10:37 UTC, attiyaIshaque commented on course_discovery/static/js/publisher/instructors.js
> +        imageFile = input.files[0],
Actually, function is calling on, onChange event. so it will never throw the exception

2017-11-02 10:48 UTC, attiyaIshaque commented
@Rabia23 I have addressed your requested change.

2017-11-02 10:53 UTC, Rabia23 commented on course_discovery/static/js/publisher/instructors.js
> +        imageFile = input.files[0],
alright.

2017-11-02 10:53 UTC, Rabia23 approved these changes

2017-11-02 11:00 UTC, Rabia23 commented
👍

2017-11-02 11:14 UTC, merged

2017-11-02 20:27 UTC, schenedx commented
@attiyaIshaque The instructions says, the image must be less than 110X110px. That's in contrast of the message you put on the PR description where the image must only be 110X110 pixel. I think we should have a PR to update the message properly.

2017-11-03 05:55 UTC, attiyaIshaque commented
@schenedx oh I got your point. I will update it in my other PR. :)