[ENT-676] Add course run tags to course run serializer.
openedx/course-discovery pull request #1208
Opened 2017-11-04 14:03 UTC by UmanShahzad

We were not previously getting the `tags` detail for course runs when querying for course runs or courses. We want to integrate with Degreed and they optionally ask for course tags to be sent along in the payload. We get our course data from course discovery, so we want this information.

**JIRA tickets**: [ENT-676](https://openedx.atlassian.net/browse/ENT-676)

**Merge deadline**: ASAP

**Testing instructions**:

1. Make sure to have a course run in course-discovery with the `tags` field in the admin filled out with some fake tags.
1. Go to `/api/v1/courses`, and see no `tags` field in the serialized data.
1. Go to `/api/v1/courses/{course_key}` and see no `tags` field in the serialized data.
1. Go to `/api/v1/course_runs`, and see no `tags` field in the serialized data.
1. Go to `/api/v1/course_runs/{course_run_key}` and see no `tags` field in the serialized data.
1. Checkout this branch for course-discovery and restart the service.
1. Go to `/api/v1/courses/`, and see that `tags` is now serialized.
1. Go to `/api/v1/courses/{course_key}`, and see that `tags` is now serialized.
1. Go to `/api/v1/course_runs/`, and see that `tags` is now serialized.
1. Go to `/api/v1/course_runs/{course_run_key}`, and see that `tags` is now serialized.

**Reviewers**
- [x] @itsjeyd  
- [x] @douglashall

2017-11-04 14:03 UTC, edx-webhook commented
Thanks for the pull request, @UmanShahzad! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=1208&repo=edx%2Fcourse-discovery"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

2017-11-04 20:03 UTC, UmanShahzad commented on course_discovery/apps/api/v1/tests/test_views/test_catalogs.py
> +            with self.assertNumQueries(21):
These are happening because of the extra query to the taggit tables:

```sql
SELECT DISTINCT `taggit_tag`.`id`, `taggit_tag`.`name`, `taggit_tag`.`slug` FROM `taggit_tag` INNER JOIN `taggit_taggeditem` ON (`taggit_tag`.`id` = `taggit_taggeditem`.`tag_id`) WHERE (`taggit_taggeditem`.`content_type_id` = 43 AND `taggit_taggeditem`.`object_id` = 834)
```

2017-11-06 16:30 UTC, douglashall commented
@clintonb @mjfrey @bderusha Any concerns about adding the `tags` field to the `CourseRunSerializer`?

2017-11-06 16:36 UTC, clintonb requested changes

2017-11-06 16:36 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +            'tags': [],
Add some tags, and actually test serialization.

2017-11-06 16:36 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_catalogs.py
> +            with self.assertNumQueries(21):
Prefetch the tags. See https://github.com/edx/course-discovery/blob/c2cbe4a66438bed57dafde7f5c32194c88867d6f/course_discovery/apps/api/serializers.py#L494-L502 for an example.

2017-11-06 16:39 UTC, clintonb commented
1. Update the commit message to follow our guidelines at https://openedx.atlassian.net/wiki/spaces/OpenDev/pages/161880915/Git+Best+Practices#GitBestPractices-CommitMessages.
2. Why do you need tags?
3. Who will be responsible for administering the tags?
4. What tool(s) will be used to administer them?

2017-11-06 16:48 UTC, UmanShahzad commented
Thanks for the fast review!

1. Can you be more specific? Do you mean just to add the ticket identifier?
1. Please read the PR description.
3 & 4. This is not a new field, so I think these questions were more relevant for when they were introduced -- @douglashall do you know an answer nevertheless?

2017-11-06 16:55 UTC, clintonb commented
1. Ticket number, yes. An explanation of why these fields are being exposed would aid future debugging.
2. I did read the description, and the ticket's description. Neither explains why you _need_ tags. Your description explains the change being made, but not why. I'm not digging through ticket comments for info that should, frankly, be in the description.
3. The field is not new. It was added by ECOM-6392 for a very narrow internal use case.

2017-11-06 17:12 UTC, douglashall commented
@UmanShahzad Given the purpose of the tags field as described in ECOM-6392, it seems like the tags field will not be useful for population of course metadata on the Degreed side. Let's close this PR out and remove the piece that sends the tag metatdata to Degreed.

2017-11-06 18:17 UTC, UmanShahzad commented
@douglashall Sure.

2017-11-06 18:17 UTC, closed without merging