Add instructor outside organization using org_override
openedx/course-discovery pull request #1218
Opened 2017-11-13 12:56 UTC by asadazam93

## [EDUCATOR-879](https://openedx.atlassian.net/browse/EDUCATOR-879)

### Description
Allow instructors to be added outside of organization using the oranization_override field.

**Sandbox**
- In progress

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] @schenedx    
- [ ] @attiyaIshaque  

### Post-review
- [ ] Rebase and squash commits

2017-11-13 14:55 UTC, schenedx requested changes
Please see my inline review comments

2017-11-13 14:55 UTC, schenedx commented on course_discovery/apps/publisher/templates/publisher/_add_instructor_popup.html
> +                    <span id="override_toggle"> <a>Override </a></span>
I don't think the link should be named `Override`. How about `Manual Input` Or `Text Input`?
The link text here needs to be translated. Please use `{% trans "Manual Input" %}`

2017-11-13 14:55 UTC, schenedx commented on course_discovery/apps/publisher/templates/publisher/_add_instructor_popup.html
> +                <div id="org_container" style="display: block;">
Please use class names instead of inline style like `display: block;`

2017-11-13 14:55 UTC, schenedx commented on course_discovery/apps/publisher/templates/publisher/_add_instructor_popup.html
> +                    <label class="field-label">{% trans "Organization Override" %}
Instead of calling this text field `Organization Override`. It sounds better to just be `Organization`

2017-11-13 14:55 UTC, schenedx commented on course_discovery/apps/publisher/templates/publisher/_add_instructor_popup.html
> +                <div id="org_override_container" style="display: none;">
I think it's better to initiate the `display:none;` state of this element in javascript, rather than using inline style here

2017-11-13 14:55 UTC, schenedx commented on course_discovery/apps/publisher/templates/publisher/_personFieldLabel.html
> +        {% elif staff.position.organization_id is None %}
Are you sure this is the right place for this `elif` statement? Shouldn't this `elif` be after line 9?

2017-11-13 14:55 UTC, schenedx commented on course_discovery/apps/publisher/templates/publisher/_personFieldLabel.html
> +        {% elif staff.position.organization_id is None %}
Or is this even needed?

2017-11-13 14:55 UTC, schenedx commented on course_discovery/static/js/publisher/instructors.js
> +    else if (organization_id == "None") {
This statement repeats the condition above

2017-11-13 14:55 UTC, schenedx commented on course_discovery/static/js/publisher/instructors.js
> +        if ($('#organization_override').val()) {
Please move this into a new function. Like `get_form_instructor_organization`

2017-11-14 10:42 UTC, asadazam93 commented on course_discovery/apps/publisher/templates/publisher/_personFieldLabel.html
> +        {% elif staff.position.organization_id is None %}
This elif is for the case when the logged in user is not course team so it needs to be there for all internal users to be able to edit the instructor

2017-11-14 10:43 UTC, asadazam93 commented on course_discovery/static/js/publisher/instructors.js
> +    else if (organization_id == "None") {
The above condition is for course team user. This condition is for when someone other than the course team is logged in.

2017-11-14 13:39 UTC, schenedx requested changes
Reviewed.
Maybe we can talk about the if else condition face to face?

2017-11-14 13:39 UTC, schenedx commented on course_discovery/apps/api/serializers.py
> +        instance.position.organization = organization if organization else None
I don't think you need those temporary variables.
You can do `instance.position.organization = position_data.get('organization')`directly, and that achieve the same.

2017-11-14 13:39 UTC, schenedx commented on course_discovery/apps/api/serializers.py
> +        instance.position.organization_override = organization_override if organization_override else None
This is the same thing. You just need one line to achieve the same result:
`instance.position.organization_override = position_data.get('organization_override')`

2017-11-14 13:39 UTC, schenedx commented on course_discovery/apps/publisher/templates/publisher/_personFieldLabel.html
> +        {% elif staff.position.organization_id is None %}
@sstack22 Question:
Should we allow ANY internal user to edit instructors on Publisher?
Currently, we only allow course team members to do so. Should we open the access to edit up to others?

2017-11-14 13:39 UTC, schenedx commented on course_discovery/static/js/publisher/instructors.js
> +        var position = getFormInstructorPosition($('#organization_override').val())
Instead of passing in the value like this, just call the function without parameters, and call statement `$('#organization_override').val()` inside this method. You already do similar things in this method anyways. Let's make it consistent.

2017-11-14 13:39 UTC, schenedx commented on course_discovery/static/js/publisher/instructors.js
> +    else if (organization_id == "None") {
I am really having trouble with this if else block.
To me, those conditions can be written as a separate function, and then we just have to write ` controlOptions += '<a class="edit" id="' + uuid + '"href="#"><i class="fa fa-pencil-square-o fa-fw"></i></a>';` once.
Also, why do we go through so many logic to render this edit icon anyways?

2017-11-15 10:23 UTC, asadazam93 commented
@schenedx I have addressed your comments. About the if condition maybe we can talk about it in the meeting today?

2017-11-15 13:04 UTC, sstack22 commented
@asadazam93  - it seems there is a bug in the sandbox. I don't see a way to choose an existing organization - it looks like manual input is the only option. CC: @srpearce as an FYI and also for thoughts on text.

![screen shot 2017-11-15 at 8 02 45 am](https://user-images.githubusercontent.com/11049466/32837462-a691417a-c9db-11e7-9a84-11f16d14c64f.png)

2017-11-15 15:15 UTC, asadazam93 commented
@sstack22 maybe because the user you are logging in with is not related to any organization. One can only create instructors for organizations you are related with.

2017-11-15 15:18 UTC, schenedx commented on course_discovery/static/js/publisher/instructors.js
> +    if ($('#organization_override').val()) {
#nitpick This value is being used twice. Once here and once on line 109. Can you get this value into a temporary variable and use the variable instead on line 109?

2017-11-15 22:18 UTC, srpearce commented
@asadazam93 You mentioned that the username/password are asadazam/asadazam. Where do we enter this? When I sign in to the edX platform, I have to use an e-mail address (so I just used the standard staff@example.com with edx as the password).

2017-11-15 23:08 UTC, srpearce commented
I have a few suggestions for this UI. 

Here is what the UI label looks like currently before the user clicks **Manual Input**. There's no field or drop-down under **Organization**:
![screenshot 47](https://user-images.githubusercontent.com/3493253/32864425-12f0295c-ca2d-11e7-9c27-27c9164a46c0.png)
**Note: This may be different if the user is signed in as someone who is a member of an organization. But the only way I know how to sign in is with the staff@example.com / edx credentials; I'm not aware of a place to enter just a username that isn't an email address.**

And here's what it looks like after you click **Manual Input**. There are two **Organization** labels but just one field:
![screenshot 46](https://user-images.githubusercontent.com/3493253/32864388-f4db79b2-ca2c-11e7-8450-b24acffa17ee.png)

Again, I'm guessing that being able to sign in as asadazam will fix some of these problems.

However, for now I'll just say that I think the option should look like this before the user clicks **Enter a different organization**:
(Note that I cobbled these together with SnagIt, so they're not 100% what this should look like.)

![screenshot 46a](https://user-images.githubusercontent.com/3493253/32864326-c19ca418-ca2c-11e7-931c-029d1ebbc65a.png)

Notes:
* **Manual Input** has changed to **Enter a different organization** and has moved under the drop-down list.
* **Required** has parentheses instead of an asterisk, and is in normal text instead of bold. (I'd recommend this change for all instances of "* required" on the page—it would look more professional.)

And I think it should look like this after the user clicks **Enter a different organization** (I've entered some sample text here):
![screenshot 46b](https://user-images.githubusercontent.com/3493253/32864855-b59eaa60-ca2e-11e7-9f1d-41c8a8369e5e.png)

Notes:
* The arrow that indicates the field is a drop-down list is gone because this is now a text field, and the cursor automatically appears inside the text field.
* The **Enter a different organization** option is no longer visible. (If we want the user to be able to enter another organization, we should keep this option visible.)

These are just suggestions; if you have any questions, please let me know.

2017-11-16 11:28 UTC, asadazam93 commented
@srpearce You have to login via the admin. https://discovery-escalation-discovery.sandbox.edx.org/admin
I have Implemented your suggestions. Thank you for your input.

2017-11-16 11:34 UTC, asadazam93 commented
@schenedx while testing that single if statement I discovered that we needed that None check for organization after all, because without that check the course team will not be able to edit instructors that are not related to any organization.

2017-11-16 16:22 UTC, schenedx requested changes
See my comments
It makes sense we need the `org is null` check

2017-11-16 16:22 UTC, schenedx commented on course_discovery/static/js/publisher/instructors.js
> +            organization_override: $('#organization_override').val()
We should also return the dictionary with organization set to null
we should return 
```
{
    title: $('#title').val(),
    organization_override: $('#organiztion_override').val(),
    organization: null
}
```
If don't do this, when course teams are editing an existing instructor who had organization specified before, to update it to have org override, we will have the instructor's organization and org override both specified, which will lead to confusion.

2017-11-16 16:22 UTC, schenedx commented on course_discovery/static/js/publisher/instructors.js
> +        organization: parseInt($('#id_organization').val())
You should make sure you explicitly set the organization override value to be `null` in this dictionary return

2017-11-16 16:22 UTC, schenedx commented on course_discovery/static/js/publisher/instructors.js
> +    if((user_is_course_team && user_is_in_similar_org_as_instructor && uuid || org_is_none) || is_internal_user || edit_instructor){
I think the bracket should be:
`if(user_is_course_team && ((user_is_in_similar_org_as_instructor && uuid) || org_is_none) || is_internal_user...)`

2017-11-16 16:22 UTC, schenedx commented on course_discovery/apps/publisher/templates/publisher/_personFieldLabel.html
> +         staff.position.organization_id in organizations_ids or staff.position.organization_id is None) or is_internal_user  %}
Again, can you please make sure the condition `staff.position.organization_id` is combined at the right place?
like 
```
if (course_user_role == 'course_team' and ((staff.position and staff.uuid and
         staff.position.organization_id in organizations_ids) or staff.position.organization_id is None))...
```

2017-11-17 09:52 UTC, asadazam93 commented on course_discovery/static/js/publisher/instructors.js
> +            organization_override: $('#organization_override').val()
Yeah you are right

2017-11-17 09:52 UTC, asadazam93 commented
@schenedx I have addressed your comments.

2017-11-17 14:49 UTC, schenedx approved these changes
I still have a nitpick in the PR not addressed. But this is good to merge in my opinion. Good work!

2017-11-20 11:24 UTC, noraiz-anwar approved these changes
👍

2017-11-20 11:38 UTC, merged

2017-11-21 19:57 UTC, schenedx commented on course_discovery/static/js/publisher/instructors.js
> +    var user_is_in_similar_org_as_instructor = $.inArray(parseInt(organization_id), JSON.parse(user_organizations_ids)) > -1;
So, I was trying to validate this change on stage and found:
1. `user_organizations_ids` variable may contain a empty string. This means the statement `JSON.parse(user_organizations_ids)` can be throwing an exception
2. organization_id can be empty string as well. That means you don't even need to do `parseInt(organization_id)` if organization_id is empty

2017-11-27 21:26 UTC, srpearce commented
Nit: I'm not sure if this is related to @schenedx 's comments above, but I see this behavior when I start to enter a different organization but then change my mind:

1. I create a new instructor.
2. I see this:  
![screenshot 53](https://user-images.githubusercontent.com/3493253/33289831-c766fde2-d38e-11e7-8410-fa560b18dcf5.png)
3. I click **Enter a different organization**. (Note: The pointer changes to a beam on hover, where I would expect it to change to a hand. The text becomes underlined on hover, though, so that's helpful.)
4. I see this:
![screenshot 54](https://user-images.githubusercontent.com/3493253/33289872-ebb7a818-d38e-11e7-85fa-954ab8b9d821.png)
5. I decide I don't want to enter a new organization after all. I'm not sure how to get rid of the blank space so that I can see "Massachusetts Institute of Technology" again.

I played around with it and discovered that I can click **Enter a different organization** again. I can also click _near_ the **Enter a different organization** text to return to the original. I would expect to be able to click anywhere outside the **Organization** field, or to have a **Cancel** option.