Fix the edX status column sorting on the courses page.
openedx/course-discovery pull request #1219
Opened 2017-11-13 16:00 UTC by attiyaIshaque

2017-11-13 17:01 UTC, schenedx requested changes
Could you please create new unit tests in the CourseListViewTests tests in https://github.com/edx/course-discovery/blob/master/course_discovery/apps/publisher/tests/test_views.py#L1637?

2017-11-13 17:01 UTC, schenedx commented on course_discovery/apps/publisher/views.py
> +            if ordering_field_index not in ordering_fields.keys() and ordering_field_index != 6:
why index != 6? What does the value 6 mean? Can you use a constant to specify what `6` means?

2017-11-13 17:31 UTC, attiyaIshaque commented on course_discovery/apps/publisher/views.py
> +            if ordering_field_index not in ordering_fields.keys() and ordering_field_index != 6:
Sure @schenedx i will change it.

2017-11-13 17:34 UTC, attiyaIshaque commented
@schenedx I have added the unit test in this PR https://github.com/edx/course-discovery/pull/1210/files#diff-7541c140671314e6639d6a0fe3f4c4dfR1917

I have just change the small implementation.

2017-11-13 17:59 UTC, schenedx reviewed
Added more coments.

2017-11-13 17:59 UTC, schenedx commented on course_discovery/apps/publisher/views.py
> +INTERNAL_USER_STATUS = 6
This variable should be named as `EDX_STATUS_COLUMN_INDEX` correct? Why is it `INTERNAL_USER_STATUS`?

2017-11-13 17:59 UTC, schenedx commented on course_discovery/apps/publisher/views.py
> +            if ordering_field == 'course_runs_count':
Why not use the index here as well? Why use the field name which is more likely change?

2017-11-13 18:05 UTC, attiyaIshaque commented on course_discovery/apps/publisher/views.py
> +            if ordering_field == 'course_runs_count':
Oh, I don't know. But I will also change it into some constant. :)

2017-11-13 18:05 UTC, attiyaIshaque commented on course_discovery/apps/publisher/views.py
> +INTERNAL_USER_STATUS = 6
Because it's calculated on the property `INTERNAL_USER_STATUS`. I will change it.

2017-11-14 12:15 UTC, attiyaIshaque commented
@schenedx I have addressed your comments.
@asadazam93 Can you please review it?

2017-11-14 15:10 UTC, schenedx approved these changes
Just minor comments. 
👍

2017-11-14 15:10 UTC, schenedx commented on course_discovery/apps/publisher/views.py
> +        if ordering_field_index == EDX_STATUS_COLUMN_INDEX:
Please add comment to let others know why we implemented special logic for EDX_STATUS column

2017-11-14 15:10 UTC, schenedx commented on course_discovery/apps/publisher/views.py
> +            if ordering_field_index == COURSE_RUNS_COUNT_INDEX:
This if block can be moved to above line 885. Then it would make the logic easier to read

2017-11-14 15:21 UTC, attiyaIshaque commented on course_discovery/apps/publisher/views.py
> +            if ordering_field_index == COURSE_RUNS_COUNT_INDEX:
If we move this line to above line 885
```
if ordering_field_index == COURSE_RUNS_COUNT_INDEX:
```
then this part not executed 
```
 if ordering_direction == 'asc':
                 queryset = queryset.order_by(Lower(ordering_field).asc())
else:
                queryset = queryset.order_by(Lower(ordering_field).desc())
```
so in my opinion it should remain in this part.

2017-11-14 15:21 UTC, attiyaIshaque commented on course_discovery/apps/publisher/views.py
> +        if ordering_field_index == EDX_STATUS_COLUMN_INDEX:
Okay sure i will add it.

2017-11-14 15:29 UTC, schenedx commented on course_discovery/apps/publisher/views.py
> +            if ordering_field_index == COURSE_RUNS_COUNT_INDEX:
I think you didn't fully understand me. 
If you move the `if ordering_field_index == COURSE_RUNS_COUNT_INDEX:` statement above line 885. 
Then let line 885 to be a single if statement again. Then the `else` where you are doing ordering directions, will be executed

2017-11-14 15:36 UTC, attiyaIshaque commented on course_discovery/apps/publisher/views.py
> +            if ordering_field_index == COURSE_RUNS_COUNT_INDEX:
oh. Got it. Thanks i will do it.

2017-11-15 07:53 UTC, asadazam93 approved these changes

2017-11-15 09:35 UTC, merged