Display verified seat if it exists over audit
openedx/course-discovery pull request #1229
Opened 2017-11-20 11:33 UTC by asadazam93

## [EDUCATOR-1602](https://openedx.atlassian.net/browse/EDUCATOR-1602)

### Description
If a course run has more than one seat and if one of those is a paid seat, the paid seat should be displayed over the audit the seat in publisher.

**Sandbox**
N/A

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] @schenedx    
- [ ] @noraiz-anwar

### Post-review
- [ ] Rebase and squash commits

2017-11-20 14:45 UTC, schenedx requested changes
Please consider a unit test case for this scenario?

2017-11-20 14:45 UTC, schenedx commented on course_discovery/apps/publisher/views.py
> +        course_run_paid_seat = course_run.seats.filter(type__in=['verified', 'professional']).first()
Can you move the list `['verified', 'professional']` into the Publisher Models.py at https://github.com/edx/course-discovery/blob/master/course_discovery/apps/publisher/models.py#L34 with a constant name? This way, this list can be re-used.

2017-11-22 11:13 UTC, asadazam93 commented
@schenedx I have addressed your comment related to the code. Working on test case

2017-11-22 13:45 UTC, schenedx reviewed
Please add unit tests

2017-11-27 14:54 UTC, schenedx reviewed
Almost there. I think we need one more test?

2017-11-27 14:54 UTC, schenedx commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertNotContains(response, '<div id="SeatPriceBlock" class="col col-6 hidden" style="display: block;">')
Shouldn't you check the seat has the name `Audit`?

2017-11-27 14:54 UTC, schenedx commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertNotContains(response, '<div id="SeatPriceBlock" class="col col-6 hidden" style="display: block;">')
And can you point me to the test case where we have the verified seat and the publisher does show `Verified`?

2017-11-28 08:09 UTC, asadazam93 commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertNotContains(response, '<div id="SeatPriceBlock" class="col col-6 hidden" style="display: block;">')
@schenedx this is that case. We have both verified and audit seats but the response renders verified seat. And here I am checking if the price is not hidden which would indicate that it is a verified seat thus has a price. We pass seat_form from the context so I was not able to check seat type that is why I used this to check for verified seat.

2017-11-28 13:39 UTC, schenedx approved these changes
👍

2017-11-28 14:25 UTC, merged