EDUCATOR-1787 Allow hyphen character in course number
openedx/course-discovery pull request #1231
Opened 2017-11-21 19:52 UTC by Rabia23

## [EDUCATOR-1787](https://openedx.atlassian.net/browse/EDUCATOR-1787)

### Description
In the past, publisher only allows [ _ ] and [ . ] (In addition to alphanumeric characters) in course number but now it allows [-] character as well to keep it consistent with Studio which allows  [ _ ], [ - ], [ . ]. It also allows [.] in organization key (In addition to alphanumeric characters, underscore and hyphen) for consistency with studio as we had missed this case in https://github.com/edx/course-discovery/pull/1203.

### How to Test?
**Sandbox**
https://discovery-escalation-discovery.sandbox.edx.org/publisher/courses/29/edit/
Edit any field and click on `Update Course`. It allows [-] character in course number.

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [x]  @awaisdar001 
- [x]  @asadazam93 

FYI: 

### Post-review
- [x] Rebase and squash commits

2017-11-22 11:04 UTC, awaisdar001 requested changes

2017-11-22 11:04 UTC, awaisdar001 commented on course_discovery/apps/publisher/templates/publisher/course_edit_form.html
> +                                                <li>{% trans "Maximum 50 characters. Characters can be letters, numbers, periods, underscores or hyphens." %}</li>
is it just the cosmetic change? changing 10 to 50?

2017-11-22 11:04 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_forms.py
> +        "abc(123)"
also check for `!#$%^&*+=` chars in the dd.data.

2017-11-22 11:04 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_forms.py
> +        "abc(123)"
one thing you can do is to pass the invalid chars as a list in dd.data and on line 239 you can combine the chars in iteration with and test the validation error.

2017-11-22 11:05 UTC, Rabia23 commented on course_discovery/apps/publisher/templates/publisher/course_edit_form.html
> +                                                <li>{% trans "Maximum 50 characters. Characters can be letters, numbers, periods, underscores or hyphens." %}</li>
yes

2017-11-22 11:06 UTC, Rabia23 commented on course_discovery/apps/publisher/tests/test_forms.py
> +        "abc(123)"
sure

2017-11-22 11:31 UTC, Rabia23 commented
@awaisdar001 I have addressed your changes. Can you please take a look again?

2017-11-22 12:58 UTC, awaisdar001 requested changes

2017-11-22 12:58 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_forms.py
> +    def test_invalid_course_number(self, number_list):
`invalid_char_list`

2017-11-22 12:58 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_forms.py
> +    def test_valid_course_number(self, number):
`number` => `valid_number`

2017-11-22 12:58 UTC, awaisdar001 commented on course_discovery/apps/publisher/templates/publisher/course_edit_form.html
> +                                        {% if form.number.errors %}
Why are we using `escape`?

2017-11-22 12:58 UTC, awaisdar001 commented on course_discovery/apps/publisher/forms.py
> +        if not re.match("^[a-zA-Z0-9._-]*$", number):
Can publisher and course metadata both use the same regex?

2017-11-27 07:28 UTC, awaisdar001 requested changes

2017-11-27 07:28 UTC, awaisdar001 commented on course_discovery/apps/course_metadata/models.py
> +    key = models.CharField(max_length=255, help_text=_('Only ascii characters allowed (a-zA-Z0-9._-)'))
@Rabia23  Can we have the `help_text` more like the validation error to be more explicit about what characters we are allowing to course teams?

2017-11-27 07:28 UTC, awaisdar001 commented on course_discovery/apps/publisher/utils.py
> +ALLOWED_CHARS_PATTERN = re.compile(r"^[a-zA-Z0-9._-]*$")
Which chars? The variable is not self-explanatory.

2017-11-27 07:28 UTC, awaisdar001 commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        [" ", "@", "(", "!", "#", "$", "%", "^", "&", "*", "+", "=", "{", "[", "ó"]
Do we need to test `,` also?

2017-11-27 07:28 UTC, awaisdar001 commented on course_discovery/apps/course_metadata/tests/test_models.py
>      def test_clean_success(self, key):
what is `key` here? we are not unpacking ddt.data here. is the variable `key` is a list/tuple?

2017-11-27 07:28 UTC, awaisdar001 commented on course_discovery/apps/publisher/templates/publisher/course_edit_form.html
> +                                        {% if form.number.errors %}
@Rabia23 ^^

2017-11-27 07:28 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_forms.py
> +    def test_valid_course_number(self, valid_number):
See my comment above.
`valid_number` same as `key`

2017-11-27 07:28 UTC, awaisdar001 commented on course_discovery/apps/publisher/forms.py
> +            raise ValidationError(_('Please do not use any spaces or special characters other than period, '
@Rabia23 Please find a perfered way to use string in edX. Here you are using `''` to define a string and on the L#186 it `self.cleaned_data.get("number")` please find a perfered way and stick with it.

2017-11-27 08:45 UTC, Rabia23 commented on course_discovery/apps/course_metadata/tests/test_models.py
>      def test_clean_success(self, key):
`key` is a variable name. Each value will be assigned to variable `key`.

2017-11-27 08:48 UTC, awaisdar001 commented on course_discovery/apps/course_metadata/tests/test_models.py
>      def test_clean_success(self, key):
see no `@ddt.unpack`?

2017-11-27 08:49 UTC, Rabia23 commented on course_discovery/apps/course_metadata/tests/test_models.py
>      def test_clean_success(self, key):
because there is no need of it.

2017-11-27 08:50 UTC, Rabia23 commented on course_discovery/apps/course_metadata/tests/test_models.py
>      def test_clean_success(self, key):
`@ddt.data(
        "keywithoutspace",
        "correct-key",
        "correct_key",
        "correct.key"
    )`

2017-11-27 08:54 UTC, awaisdar001 requested changes

2017-11-27 08:54 UTC, awaisdar001 commented on course_discovery/apps/course_metadata/tests/test_models.py
>      def test_clean_success(self, key):
you are assigning the list to `self.organization.key = key` in `test_clean_success` body and then calling a clean, are you missing something?

2017-11-27 09:00 UTC, Rabia23 commented on course_discovery/apps/course_metadata/tests/test_models.py
>      def test_clean_success(self, key):
I am not assigning list to `self.organization.key`. Individual value is assigned to `self.organization.key`.

2017-11-27 09:02 UTC, awaisdar001 commented on course_discovery/apps/course_metadata/tests/test_models.py
>      def test_clean_success(self, key):
Talked with rabia. we are on the same page with this one. Got rid of my confusion on this.

2017-11-27 10:02 UTC, Rabia23 commented on course_discovery/apps/publisher/tests/test_forms.py
> +    def test_valid_course_number(self, valid_number):
we are on the same page for `valid_number` as we discussed above for `key` variable.

2017-11-28 10:00 UTC, awaisdar001 commented
@Rabia23 please read out https://openedx.atlassian.net/wiki/spaces/OpenDev/pages/161880915/Git+Best+Practices and do not squash commits once a review has started, to aid reviewers.

2017-11-28 10:06 UTC, awaisdar001 approved these changes
small nits, rest looks good to me.

2017-11-28 10:06 UTC, awaisdar001 commented on course_discovery/apps/course_metadata/models.py
> +                                                       'in the course\'s course key.'))
👍

2017-11-28 10:06 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_forms.py
> +            course_form.cleaned_data = {'number': 'course_num{}'.format(char)}
`char` => `invalid_char`

2017-11-28 11:26 UTC, asadazam93 approved these changes

2017-11-28 11:35 UTC, merged