consider course entitlement products in program price ranges
openedx/course-discovery pull request #1236
Opened 2017-11-27 15:13 UTC by McKenzieW

Update price_ranges calculation to look at entitlement products in addition to seats

[LEARNER-3297](https://openedx.atlassian.net/browse/LEARNER-3297)

2017-11-29 19:49 UTC, staubina requested changes
Some minor code changes. I defer on some of them to others though.

Please stop by and lets discuss if any of my comments are confusing.

2017-11-29 19:49 UTC, staubina commented on course_discovery/apps/course_metadata/models.py
> +        """
Is there another way to handle this other than the Warning here? 

I am not familiar enough with this code base to provide a solution.
@mjfrey @clintonb @bderusha

2017-11-29 19:49 UTC, staubina commented on course_discovery/apps/course_metadata/models.py
> +                        # replace it with the entitlement product
@McKenzieW is this comment accurate?  I do not see a replacement happening, just a removal.

2017-11-29 19:49 UTC, staubina commented on course_discovery/apps/course_metadata/models.py
> +        for course_products in course_map.values():
This section is for course_runs only correct?

If it is then a simple nit, can we call it course_run_products?

2017-11-29 19:49 UTC, staubina commented on course_discovery/apps/course_metadata/models.py
> +        for course_products in course_map.values():
Or stick with the course_seat name that is common?

2017-11-29 19:57 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        """
This can be made more efficient—2 queries. Approach this as if you were writing it in SQL. In this case, you want `CourseEntitlement` objects, so the main filter should be on that table/class. From there, filter further.

```python
CourseEntitlement.objects.filter(mode__name__in=applicable_seat_types, course__in=self.courses.all())
```

2017-11-30 15:28 UTC, Mjloturco commented on course_discovery/apps/course_metadata/models.py
> +                        # replace it with the entitlement product
The removal happens and then online 1180 the corresponding entitlement as added instead.

2017-11-30 15:30 UTC, Mjloturco commented on course_discovery/apps/course_metadata/models.py
> +        for course_products in course_map.values():
This is for all products in the course_map, both seat or entitlements, this computes the sum for all selected products for the program (with selected products being one product percourse, entitlement if available, falling back to seat if no entitlement available)

2017-11-30 15:47 UTC, Mjloturco commented on course_discovery/apps/course_metadata/models.py
> +        """
👍

2017-11-30 16:40 UTC, staubina commented on course_discovery/apps/course_metadata/models.py
> +                        # replace it with the entitlement product
Update the comment to reflect the logic please.

2017-11-30 16:41 UTC, staubina approved these changes
Please update the comment and wait on one more review, maybe @clintonb.  Then Squash and :shipit:

2017-11-30 16:43 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_models.py
> +            factories.CourseEntitlementFactory(course=course, currency=currency, price=100, mode=mode)
Given that you aren't using the price in your tests, you should let the factory do it's thing. Setting values that are irrelevant to the test is distracting/misleading when others read the tests.

2017-11-30 16:44 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        self.assertEqual(set(course.entitlements.filter(mode__in=applicable_seat_types)), set(program.entitlements))
Use pytest assertions.

`assert a == b`

2017-11-30 18:55 UTC, Mjloturco commented
travis run all

2017-11-30 18:55 UTC, Mjloturco commented
jenkins run all

2017-11-30 20:50 UTC, mjfrey approved these changes

2017-12-01 14:09 UTC, merged