if preview declined the url should not dissapear
openedx/course-discovery pull request #1242
Opened 2017-11-29 10:49 UTC by asadazam93

## [EDUCATOR-1107](https://openedx.atlassian.net/browse/EDUCATOR-1107)

### Description
On the course run detail page if the course team declines the preview, the URL does not disappear, but that field is able to be edited by publisher

**Sandbox**
In progress

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [x] @schenedx    
- [x] @awaisdar001

### Post-review
- [ ] Rebase and squash commits

2017-11-29 10:51 UTC, awaisdar001 requested changes

2017-11-29 10:51 UTC, awaisdar001 commented on course_discovery/apps/publisher/templates/publisher/_approval_widget.html
> +                        {% if object.preview_url and object.course.course_team_admin == request.user and object.course_run_state.is_approved and not object.course_run_state.is_preview_accepted and ob
we are checking `object.preview_url` on line#22 do we need to check it again here?

2017-11-29 10:51 UTC, awaisdar001 commented on course_discovery/apps/publisher/templates/publisher/_approval_widget.html
> +                        {% if object.preview_url and object.course.course_team_admin == request.user and object.course_run_state.is_approved and not object.course_run_state.is_preview_accepted and ob
what is `object` here?

2017-11-29 16:08 UTC, schenedx requested changes
I think the change can be designed better

2017-11-29 16:08 UTC, schenedx commented on course_discovery/apps/publisher_comments/models.py
> -    course_run.preview_url = None
After the removal of these lines, we make this function useless. Why have this function?

2017-11-30 08:18 UTC, asadazam93 commented on course_discovery/apps/publisher_comments/models.py
> -    course_run.preview_url = None
We still have to change owner_role and send email in this function.

2017-11-30 08:43 UTC, awaisdar001 commented on course_discovery/apps/publisher/wrappers.py
> +    def is_in_preview_review(self):
@asadazam93 
http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#breaking-long-lines
pls follow for breaking long lines.

2017-11-30 08:43 UTC, awaisdar001 commented
Just a nit, else looks good to me, Do you have an updated sandbox link?

2017-11-30 09:27 UTC, asadazam93 commented
@awaisdar001 Sandbox updated

2017-11-30 10:36 UTC, awaisdar001 approved these changes

2017-11-30 16:01 UTC, schenedx approved these changes
Just 1 more comment. Rest LGTM

2017-11-30 16:01 UTC, schenedx commented on course_discovery/apps/publisher_comments/models.py
> -    course_run.preview_url = None
@asadazam93 Got it. Then we don't need to save the course_run on line 50

2017-12-06 09:26 UTC, merged