load entitlement modes by slug not name
openedx/course-discovery pull request #1253
Opened 2017-12-07 18:17 UTC by McKenzieW

Entitlement products are getting deleted from discovery in stage; this might be because their `certificate_type`s are not matching with the `name` field of any `SeatType` objects, because `certificate_type`s are not capitalized, but the `SeatType` `name` field is.

2017-12-07 20:40 UTC, mjfrey requested changes

2017-12-07 20:40 UTC, mjfrey commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        CourseEntitlement.objects.filter(partner=self.partner).exclude(sku__in=skus).delete()
Can we logs which skus we are deleting?  This will prove helpful in the future.

2017-12-07 20:40 UTC, mjfrey commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        msg = 'Creating {entitlement} with sku {sku}'.format(entitlement=body['title'], sku=sku)
I would add the partner here as well.

2017-12-07 20:54 UTC, McKenzieW commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        CourseEntitlement.objects.filter(partner=self.partner).exclude(sku__in=skus).delete()
I think we'd have to perform the query a second time to log the skus of the entitlements that are being deleted.

2017-12-07 20:59 UTC, McKenzieW commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        CourseEntitlement.objects.filter(partner=self.partner).exclude(sku__in=skus).delete()
I'm trying something out that could avoid an extra query, but I'm not positive that it will work

2017-12-07 20:59 UTC, mjfrey commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        CourseEntitlement.objects.filter(partner=self.partner).exclude(sku__in=skus).delete()
I just think it would be nice to log the entitlements we are deleting.

2017-12-07 21:04 UTC, McKenzieW commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        CourseEntitlement.objects.filter(partner=self.partner).exclude(sku__in=skus).delete()
Yeah, we can do that. I'm about to push the change up

2017-12-07 21:08 UTC, McKenzieW commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        CourseEntitlement.objects.filter(partner=self.partner).exclude(sku__in=skus).delete()
well I'm going to push the change up once the quality checks are done running locally

2017-12-07 21:17 UTC, mjfrey approved these changes

2017-12-08 12:52 UTC, staubina reviewed
One nit otherwise looks good to me.

2017-12-08 12:52 UTC, staubina commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        for entitlement in entitlements_to_delete:
Nit: Is it possible for this list to be large?  Should we just log them all at once rather than looping through the list?

2017-12-08 12:55 UTC, McKenzieW commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        for entitlement in entitlements_to_delete:
I don't imagine that it would be large, because entitlements would only likely need to be deleted if they were incorrectly created in ecommerce, then loaded into discovery before they were fixed in ecommerce, which I assume wouldn't happen in large batches or even very often.

2017-12-08 15:25 UTC, Mjloturco reviewed
Mostly nits. A thing or two we might want to briefly consider.

2017-12-08 15:25 UTC, Mjloturco commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        for entitlement in entitlements_to_delete:
If we are assuming it wont happen in large batches or very often, would it be helpful to somehow log how many course entitlements were being deleted? It may be overkill but could help us track bugs like what we saw down. Something like 'deleted 20 entitlements for partner ____ '. thoughts?

2017-12-08 15:25 UTC, Mjloturco commented on course_discovery/apps/course_metadata/data_loaders/tests/test_api.py
> +        msg += ' while loading Verified Entitlement to Fake Course with sku sku132'
Nit: Course Entitlement products are named 'Course {course name}' instead of 'Verified Entitlement to {course name}'.

2017-12-08 15:25 UTC, Mjloturco commented on course_discovery/apps/course_metadata/migrations/0072_courseentitlement_partner.py
> +            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Partner'),
Are we sure we want to delete any course_entitlements if the corresponding partner is deleted? I'm not sure myself, but we might want to consider.

2017-12-08 16:18 UTC, McKenzieW commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        for entitlement in entitlements_to_delete:
I'm not quite clear on why the expectation against large batches and frequency indicates a potential usefulness of logging a count of the deleted course entitlements.

2017-12-08 17:53 UTC, closed without merging