Changed instructor field on program to be more accurate
openedx/course-discovery pull request #1261
Opened 2017-12-11 19:55 UTC by tuchfarber

Changes the `instructors` field on the program model to a more accurate `instructor_ordering`. 

Not yet ready to merge. Opening PR because I'm experiencing test issues locally and want to see if they happen in travis as well.

2017-12-12 19:18 UTC, mikedikan reviewed
This looks good - can you also leave a brief comment explaining the field - the rename is good step, but I think clarifying in more detail would help.

2017-12-12 19:18 UTC, mikedikan commented
ping @clintonb & @schenedx

2017-12-12 19:24 UTC, schenedx reviewed
I am worrying about the rename migration. The generate idea here make sense to me

2017-12-12 19:24 UTC, schenedx commented on course_discovery/apps/course_metadata/migrations/0074_auto_20171211_1922.py
> +        migrations.RenameField(
I think doing rename field with a migration will break production system. 
The migration runs first. The old code will be running against the new db column name.
You might want to update the code to add the new `instructor_ordering` model attribute first, and mark the old attribute obsolete, then create another PR to retire the obsolete attribute.

2017-12-12 19:49 UTC, tuchfarber commented on course_discovery/apps/course_metadata/migrations/0074_auto_20171211_1922.py
> +        migrations.RenameField(
Will this be an issue if no code is using this field yet? I have yet to merge the PR that references this.

2017-12-12 19:50 UTC, schenedx commented on course_discovery/apps/course_metadata/migrations/0074_auto_20171211_1922.py
> +        migrations.RenameField(
I guess, in this case, it should be OK then. Thanks for that information

2017-12-12 19:54 UTC, tuchfarber commented on course_discovery/apps/course_metadata/migrations/0074_auto_20171211_1922.py
> +        migrations.RenameField(
No problem, thanks for the confirmation.

2017-12-12 20:10 UTC, clintonb requested changes

2017-12-12 20:10 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    instructor_ordering = PersonSerializer(many=True)
Does this need to be a complete person, or can it simply be the UUIDs?

2017-12-12 20:10 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
>          help_text='Used to organize the instructors on the program about page.'
Ditch the comment above, and update the help text to better explain what the field is used for. Also, mark it for translation.

```python
help_text=_('This field can be used by API clients to determine the order in which instructors will be displayed on program pages. Instructors in this list should appear before all others associated with this programs courses runs.')
```

2017-12-12 20:10 UTC, clintonb commented
Remember to squash your commits, and update your commit message to follow our guidelines at https://openedx.atlassian.net/wiki/spaces/OpenDev/pages/161880915/Git+Best+Practices#GitBestPractices-CommitMessages.

2017-12-12 20:22 UTC, tuchfarber commented on course_discovery/apps/api/serializers.py
> +    instructor_ordering = PersonSerializer(many=True)
This needs to be a person because we are using the name fields to sort users. The instructors are coming from studio, not discovery.

2017-12-12 20:31 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    instructor_ordering = PersonSerializer(many=True)
I am referring to the data that is serialized. If you only need select fields, only serialize those fields. Adding data in the future is easy. Removing unnecessary data later requires a new version of the API to be released.

Also, please investigate a method of using the UUID to match. Matching on the name is not ideal.

2017-12-12 21:26 UTC, tuchfarber commented on course_discovery/apps/api/serializers.py
> +    instructor_ordering = PersonSerializer(many=True)
I assumed that reusing an existing serializer would be preferred to polluting with a name-only serializer. I can see both sides of the argument though.

I agrees that UUIDs would be preferable, but instructors are currently being pulled out of studio/modulestore where they are unique for each course. If we were pulling from discovery, we could use UUIDs. A quick glance shows none of our instructors are in discovery though, only studio/modulestore.

2017-12-12 21:27 UTC, tuchfarber commented on course_discovery/apps/api/serializers.py
> +    instructor_ordering = PersonSerializer(many=True)
If that's something we want to fix, I think we can save that for a future iteration. I would prefer to use discovery whenever possible, but for now, I this this would be acceptable.

2017-12-12 21:29 UTC, tuchfarber commented
Also, I'm not sure how to fix the translations error? I haven't worked with this much before.

2017-12-12 22:58 UTC, mikedikan approved these changes
Thanks for the updates @tuchfarber

2017-12-12 22:58 UTC, mikedikan commented on course_discovery/apps/course_metadata/models.py
> +        help_text=_('This field can be used by API clients to determine the order in which instructors will be '
This is great - thanks!

2017-12-13 01:23 UTC, clintonb approved these changes
Generate, and commit, the source translation files to resolve the build error.

2017-12-13 17:57 UTC, merged