Courses having 'null' in course-end date shows incorrect course card
openedx/course-discovery pull request #1263
Opened 2017-12-12 15:59 UTC by uzairr

## [LEARNER-3218](https://openedx.atlassian.net/browse/LEARNER-3218)

### Description
Course-discovery is returning incorrect availability status of the courses that have 'null' value in their course_end date.To avoid it,a conditional statement is modified so that it will behave as expected.

2017-12-13 13:18 UTC, ahsan-ul-haq requested changes

2017-12-13 13:18 UTC, ahsan-ul-haq commented on course_discovery/apps/course_metadata/models.py
> +        elif self.start and (self.start <= now):
What status will appear for courses with null end date after this change?

2017-12-13 13:20 UTC, tasawernawaz approved these changes
@ahsan-ul-haq I think the status will be `current`. @uzairr can confirm.

2017-12-13 13:25 UTC, uzairr commented on course_discovery/apps/course_metadata/models.py
> +        elif self.start and (self.start <= now):
@ahsan-ul-haq if a course is started but have 'null' in its course-end date then it should return 'Current' status.

2017-12-14 10:39 UTC, ahsan-ul-haq approved these changes

2017-12-15 07:38 UTC, merged