Allow mulitple image resolutions to be uploaded into Publisher
openedx/course-discovery pull request #1264
Opened 2017-12-12 20:15 UTC by schenedx

Add a new image validator that can allow multiple image resolutions.
EDUCATOR-1954
@tasawernawaz @asadazam93 Please review

2017-12-13 07:26 UTC, tasawernawaz requested changes

2017-12-13 07:26 UTC, tasawernawaz commented on course_discovery/apps/publisher/validators.py
> +class ImageMultiSizeValidator(ImageSizeValidator):
Do we still need this `ImageSizeValidator` ? If not, can we inherit this validator directly from `BaseSizeValidator`

2017-12-13 07:26 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
> +        data = {'title': 'Test valid', 'number': 'testX453', 'image': image}
sugestion: docsting will be helpful here.

2017-12-13 07:26 UTC, tasawernawaz commented on course_discovery/apps/publisher/templates/publisher/course_edit_form.html
> +                                            <li>{% trans "The image size must be of size 1134 X 675 pixels." %}</li>
should not this message look similar to what we have while creating course ? e.g  containing available sizes `(2120 X 1192), (1134 X 675), (378 X 225)`

2017-12-13 13:26 UTC, schenedx commented on course_discovery/apps/publisher/templates/publisher/course_edit_form.html
> +                                            <li>{% trans "The image size must be of size 1134 X 675 pixels." %}</li>
@tasawernawaz Fair assumption. I had a discussion with @sstack22 about it and she mentioned we should message to user to hightlight the preferred resolution. But we should accept all three resolutions, therefore the difference between the instruction and the error message.

2017-12-13 13:26 UTC, schenedx commented on course_discovery/apps/publisher/tests/test_views.py
> +        data = {'title': 'Test valid', 'number': 'testX453', 'image': image}
Sure, I can add those

2017-12-13 13:27 UTC, schenedx commented on course_discovery/apps/publisher/validators.py
> +class ImageMultiSizeValidator(ImageSizeValidator):
It's not used. I guess clean it up is a good idea. I'll do that

2017-12-13 13:31 UTC, tasawernawaz commented on course_discovery/apps/publisher/templates/publisher/course_edit_form.html
> +                                            <li>{% trans "The image size must be of size 1134 X 675 pixels." %}</li>
@schenedx If this is as per requirement then may be it is OK, but to me this may cause confusion while user will see error message.

2017-12-13 14:08 UTC, schenedx commented on course_discovery/apps/publisher/validators.py
> +class ImageMultiSizeValidator(ImageSizeValidator):
It turns out, I cannot clean up the `ImageSizeValidator`. This old class was referenced in model migrations. And if I remove, the unit test won't work because the migration file references to this old class would no longer be valid.
I can add a comment in code to explain this

2017-12-13 15:06 UTC, tasawernawaz approved these changes

2017-12-13 15:36 UTC, merged

2017-12-13 16:08 UTC, schenedx commented
@srpearce Please note the instructor change and error message change here. Could you please help me update the documentation associated with this change? We want course teams to upload 1134X675 instead of the huge 2120X1192 course image now

2017-12-13 16:23 UTC, srpearce commented
@schenedx I can update the docs. I'd also like to revise the UI text; for example, "The image **size** must be of **size** 1134 X 675 pixels" contains a redundancy, we don't use the word "please" in UI text because of translation issues, and there are stray parentheses in the error message. What is the best way to make these changes? I can update the HTML files and create a PR, but I don't know how to update tests.

For future reference, **any** user-facing UI strings should go through a doc review before they're merged.

2017-12-13 16:25 UTC, srpearce commented on course_discovery/apps/course_metadata/migrations/0074_auto_20171212_2016.py
> +            field=stdimage.models.StdImageField(blank=True, help_text='Please provide a course preview image', null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('
Is this the same as a course image, or is it something different?

2017-12-13 16:25 UTC, schenedx commented
@srpearce Got it. Thanks for the feedback. Can you add your text updates to the ticket EDUCATOR-1954 and I will create a second PR for the wording changes?

2017-12-13 16:25 UTC, schenedx commented on course_discovery/apps/course_metadata/migrations/0074_auto_20171212_2016.py
> +            field=stdimage.models.StdImageField(blank=True, help_text='Please provide a course preview image', null=True, upload_to=course_discovery.apps.course_metadata.utils.UploadToFieldNamePath('
This is the same as a course image. It's the image shows on both the dashboard and the course about page on marketing site

2017-12-13 16:33 UTC, srpearce commented
@schenedx Will do. Thanks!

2017-12-19 19:02 UTC, schenedx commented
The copy update PR is at https://github.com/edx/course-discovery/pull/1271