WIP - LEARNER-3879: Adds in publisher entitlement model and version to course
openedx/course-discovery pull request #1286
Opened 2018-01-23 21:04 UTC by jlajoie

2018-01-24 14:39 UTC, amangano-edx commented on course_discovery/apps/publisher/models.py
> +    }
I'm not sure how we do it elsewhere, but aren't there issues with storing price as a decimal (due to the somewhat unreliable behavior of floats)?

2018-01-24 15:16 UTC, amangano-edx commented on course_discovery/apps/publisher/models.py
> +    mode = models.ForeignKey(SeatType, related_name='publisher_entitlements')
Do we want a foreign key relationship here? The seat model uses a CharField for type.

2018-01-24 15:35 UTC, amangano-edx commented on course_discovery/apps/publisher/models.py
> +    )
This isn't currently used (on the Seat model, it's used for the choices argument on the 'type' field).

Also, if we need this, could we call it something like `COURSE_MODE_CHOICES` to distinguish it from `Seat`s?

2018-01-24 15:37 UTC, amangano-edx commented on course_discovery/apps/publisher/constants.py
> +COURSE_ENTITLEMENT_VERSION = 1
I think it might be better for these to live directly on the `Course` model, since they're specific to the model, not the application.

2018-01-24 15:37 UTC, jlajoie commented on course_discovery/apps/publisher/models.py
> +    }
This was taken directly from the Seat model, so any problems here would also occur there.

2018-01-24 15:38 UTC, jlajoie commented on course_discovery/apps/publisher/models.py
> +    mode = models.ForeignKey(SeatType, related_name='publisher_entitlements')
We don't, but it seemed better to not use modes as strings if that was possible. Happy to change it though since it'd match the Publisher__Seat model. Opinions?

2018-01-24 15:38 UTC, amangano-edx commented on course_discovery/apps/publisher/migrations/0065_set_course_verison.py
> +        course.save()
Do we need to fill in the historical table (https://github.com/edx/course-discovery/pull/1286/files#diff-a604c93caaa88baf79e663d0bdb94ed9R20) as well?

2018-01-24 15:41 UTC, amangano-edx commented on course_discovery/apps/publisher/migrations/0065_set_course_verison.py
> +# Generated by Django 1.9.13 on 2017-05-05 02:32
Curious how this was generated using Django 1.9, but other migrations in this PR (https://github.com/edx/course-discovery/pull/1286/files#diff-a604c93caaa88baf79e663d0bdb94ed9R2) were generated using Django 1.11.

2018-01-24 15:46 UTC, amangano-edx commented on course_discovery/apps/publisher/models.py
> +    mode = models.ForeignKey(SeatType, related_name='publisher_entitlements')
Just my opinion, but I'd prefer to use strings because:
1.) It's more consistent with how the other models work
2.) We avoid creating direct relationships between publisher models and course metadata models
3.) It's unclear what the SeatType model is meant to represent. Is it a CourseMode, or something meant to be more coupled to Seats?

2018-01-24 15:46 UTC, mikix commented on course_discovery/apps/publisher/models.py
> +    )
Oh yeah even my branch doesn't use this -- the type choices are just in the CourseForm (not even the model) and then we branch off that (at least in my branch).

I'm fine with this being dropped.

2018-01-24 19:00 UTC, mikix commented on course_discovery/apps/publisher/models.py
> +    mode = models.ForeignKey(SeatType, related_name='publisher_entitlements')
Though the course_metadata.models.Seat class has this note about their type field: "TODO Replace with FK to SeatType model"

2018-01-24 19:47 UTC, jlajoie commented on course_discovery/apps/publisher/models.py
> +    mode = models.ForeignKey(SeatType, related_name='publisher_entitlements')
Updating this to just use the Char. I think I prefer the consistency inside of the Publisher tables rather so that they can be updated in parallel later. I'm going to just update my base migration so you guys that are based off of this it'll break your migrations down the road.

You'll have to drop your tables manually and then remove the entries from the django_migrations table. Reason for this is to keep it at only single migration to add the field, single migration to populate the base version, and single migration for the entitlements table, rather than having multiple per table in a single PR.

2018-01-24 19:47 UTC, jlajoie commented on course_discovery/apps/publisher/models.py
> +    )
Using this now that I'm going to use the CharField.

2018-01-24 19:48 UTC, jlajoie commented on course_discovery/apps/publisher/migrations/0065_set_course_verison.py
> +# Generated by Django 1.9.13 on 2017-05-05 02:32
Because copy + paste failure 😄 , just wrote this from hand based off of another, I'll update this properly.

2018-01-24 19:50 UTC, amangano-edx commented on course_discovery/apps/publisher/migrations/0065_set_course_verison.py
> +# Generated by Django 1.9.13 on 2017-05-05 02:32
Ha, if I had read past the Django 1.19.13 bit I would have seen that it was also 'generated' last May.

2018-01-25 14:21 UTC, mikix requested changes
Nice!  I left some comments, but the only obvious fix is list_display in admin.py.

2018-01-25 14:21 UTC, mikix commented on course_discovery/apps/publisher/admin.py
> +    list_display = ['mode']
You probably want course_id here too

2018-01-25 14:21 UTC, mikix commented on course_discovery/apps/publisher/models.py
> +    COURSE_ENTITLEMENT_VERSION = 1
Tiny ignorable nit: COURSE_ seems redundant.

2018-01-25 14:21 UTC, mikix commented on course_discovery/apps/publisher/models.py
> +    mode = models.CharField(max_length=63, choices=COURSE_MODE_CHOICES, verbose_name='Course mode')
I'm a fan of mode instead of type, even though it does differ from Seat. Makes it easier to use variables called 'mode' rather than the reserved 'type' around in the code. :+1: 

Is it worth considering ChoiceField here?  I assume that adds a DB constraint?  Or at least a constraint in Django... I know Seat uses a CharField and we want to be compatible with that.  But maybe ChoiceField is still compatible (just strings) but with bonus features?

I dunno, I don't care enough or know enough to say it should change.  Just a thought.

2018-01-25 14:33 UTC, amangano-edx commented on course_discovery/apps/publisher/models.py
> +    COURSE_ENTITLEMENT_VERSION = 1
Nit: It might be helpful to add a couple comments above these summarizing the different states.

2018-01-25 14:37 UTC, amangano-edx commented on course_discovery/apps/publisher/models.py
> +    version = models.IntegerField(null=True, blank=True, verbose_name=_('Workflow Version'))
Do we need to update any logic anywhere to make sure that this is always set on save/create?

2018-01-25 14:38 UTC, amangano-edx commented on course_discovery/apps/publisher/models.py
> +    version = models.IntegerField(null=True, blank=True, verbose_name=_('Workflow Version'))
Otherwise, we risk allowing null values to be inserted during the time between when your migration runs and the rest of the publisher work is done.

2018-01-25 14:43 UTC, amangano-edx commented on course_discovery/apps/publisher/migrations/0065_set_course_verison.py
> +    for course in Course.objects.filter(Q(version__isnull=True)):
Nit: is the Q object necessary here, or could you get by with just
`Course.objects.filter(version__isnull=True)`

2018-01-25 18:25 UTC, jlajoie commented on course_discovery/apps/publisher/admin.py
> +    list_display = ['mode']
Actually didn't need it, was able to add a way to search for courses, the mode as a dropdown I think is fine.

2018-01-25 18:28 UTC, jlajoie commented on course_discovery/apps/publisher/migrations/0065_set_course_verison.py
> +    for course in Course.objects.filter(Q(version__isnull=True)):
Was able to do away with this file entirely by adding the default to the migration 👍

2018-01-25 18:32 UTC, jlajoie commented on course_discovery/apps/publisher/migrations/0065_set_course_verison.py
> +    for course in Course.objects.filter(Q(version__isnull=True)):
Also 12113 rows in the publisher_historicalcourse table, and 3151 in the publisher_course table, so this shouldn't have any real impact.

2018-01-25 18:47 UTC, jlajoie commented on course_discovery/apps/publisher/admin.py
> +    list_display = ['mode']
<img width="768" alt="screen shot 2018-01-25 at 1 40 16 pm" src="https://user-images.githubusercontent.com/1559107/35406197-3f7ec236-01d6-11e8-871c-3e7cb7e3f925.png">
What these options look like (won't load all courses in a dropdown anymore)

2018-01-25 20:45 UTC, mikix approved these changes
Looks good to me

2018-01-29 14:14 UTC, merged