Be entitlement-aware for new courses
openedx/course-discovery pull request #1299
Opened 2018-01-30 20:21 UTC by mikix

**WIP**

When creating a new course in publisher, require type and price up front rather than waiting until creating a course run. (only for verified and professional courses)

And hide this feature behind a waffle flag.

https://openedx.atlassian.net/browse/LEARNER-3767

2018-01-30 21:21 UTC, mikix commented
I'm going to make a couple changes based on a talk with Deen -- make the mode field default to 'verified'

2018-02-02 14:36 UTC, amangano-edx commented on course_discovery/apps/publisher/forms.py
> +        (CourseEntitlement.PROFESSIONAL, _('Professional education')),
Nit: Does 'education' need to be capitalized?

2018-02-02 14:44 UTC, mikix commented on course_discovery/apps/publisher/forms.py
> +        (CourseEntitlement.PROFESSIONAL, _('Professional education')),
I don't think so. I copied the string from SeatForm, which uses that same form. But I suppose if I'm using that form, I should de-capitalize "Audit-only or Credit"...  Will fix.

2018-02-02 16:18 UTC, amangano-edx commented on course_discovery/apps/publisher/forms.py
> +            raise ValidationError({'price': ''})  # mimics required field behavior (red border only, no error string)
Note: if you want to attach this error directly to the price field, you can use `add_error`, as specified here: https://docs.djangoproject.com/en/1.11/ref/forms/validation

2018-02-02 16:25 UTC, amangano-edx commented on course_discovery/apps/publisher/templates/publisher/add_course_form.html
> +                <div class="field-title" {% if not publisher_entitlements %}hidden{% endif %}>{% trans "CERTIFICATE TYPE AND PRICE" %}</span></div>
Is there any reason to include this in the DOM at all if publisher_entitlements is false? If not, could we move the `if publisher_entitlements` call outside of this div?

2018-02-02 16:35 UTC, amangano-edx commented on course_discovery/apps/publisher/templates/publisher/add_course_form.html
> +                </div>
We should pass the translated text through an escape filter.

2018-02-02 16:37 UTC, amangano-edx commented on course_discovery/apps/publisher/templates/publisher/add_course_form.html
> +                <div {% if not publisher_entitlements %}class="hidden"{% else %}class="row"{% endif %}>
If you move the `if not publisher_entitlements` check to line 131, as suggested in the above comment, you would be able to remove it here.

2018-02-02 16:39 UTC, amangano-edx commented on course_discovery/apps/publisher/templates/publisher/course_run/edit_run_form.html
> +                            <div id="seatPriceBlock" class="col col-6 {% if seat_form.type.value == 'audit' or not seat_form.price.value %}hidden{% endif %}">
If we're going to change this everywhere, and if it's only being used for JS logic, it would be better to add a class like `.js-seat-block`. This is a convention we've used in several IDAs when we've need to hook into html elements using JavaScript.

2018-02-02 16:43 UTC, amangano-edx commented on course_discovery/apps/publisher/tests/test_forms.py
> +        (None, 50),
This case should probably be invalid.

2018-02-02 16:52 UTC, amangano-edx commented on course_discovery/apps/publisher/tests/test_views.py
> +    def _make_course(self, data=None):
Nit: This name could be more descriptive. At first glance, it may seem like a simple factory function when in reality it's posting to an endpoint and validating a response.

2018-02-02 16:53 UTC, amangano-edx commented on course_discovery/apps/publisher/tests/test_views.py
> +        toggle_switch(PUBLISHER_ENTITLEMENTS_WAFFLE_SWITCH, True)
Sanity check: does this affect global state? I think it should probably be ok since the switches are stored in a DB table, which is theoretically rolled back between tests.

2018-02-02 16:58 UTC, amangano-edx commented on course_discovery/apps/publisher/tests/test_views.py
> +        """
It might be good to explicitly toggle the switch off, in case the default ever changes.

2018-02-02 17:00 UTC, amangano-edx commented on course_discovery/apps/publisher/tests/test_views.py
> +        Verify that when we check price validity when making an entitlement
I think the word "when" can be removed after "that"

2018-02-02 17:00 UTC, amangano-edx commented on course_discovery/apps/publisher/tests/test_views.py
> +        Verify that when we create a normal seat, we set version
It might be good to specify what a 'normal seat' is, as it's not clear from reading the test.

2018-02-02 17:02 UTC, amangano-edx commented on course_discovery/apps/publisher/views.py
> +            'publisher_entitlements': waffle.switch_is_active(PUBLISHER_ENTITLEMENTS_WAFFLE_SWITCH),
Alternatively, you could change the template to only render the entitlement_form if present (`{% if entitlement_form %}`), and only add it to the context when the waffle switch is present.

2018-02-02 17:04 UTC, amangano-edx commented on course_discovery/apps/publisher/views.py
> +            'publisher_entitlements': waffle.switch_is_active(PUBLISHER_ENTITLEMENTS_WAFFLE_SWITCH),
Note: This is just a suggestion, feel free to ignore.

2018-02-02 17:05 UTC, amangano-edx commented on course_discovery/apps/publisher/views.py
> +                        entitlement.course = course
The SeatForm overrides `save` and takes course as an argument. It might be good to do something similar here.

2018-02-02 17:08 UTC, mikix commented on course_discovery/apps/publisher/templates/publisher/add_course_form.html
> +                <div class="field-title" {% if not publisher_entitlements %}hidden{% endif %}>{% trans "CERTIFICATE TYPE AND PRICE" %}</span></div>
Yeah probably. I was cargo culting here, didn't consider that solution. That's better, as long as the EntitlementForm doens't need the html side to exist, which I'm guessing not.

2018-02-02 17:12 UTC, mikix commented on course_discovery/apps/publisher/forms.py
> +            raise ValidationError({'price': ''})  # mimics required field behavior (red border only, no error string)
True, but other of the forms do use this ValidationError strategy, seemingly because it's easier to work with / detect in the tests. (Clearing error state on a form wipes out the fake data we inject into it in the tests.)

2018-02-02 17:12 UTC, amangano-edx commented on course_discovery/apps/publisher/views.py
> +        if course_form.is_valid() and entitlement_form.is_valid():
Is `entitlement_form` valid even if it's empty? It might be better to do this check somewhere between lines 291 and 294 and raise an `IntegrityError` if `False`, which I believe would rollback the database.

2018-02-02 17:18 UTC, amangano-edx commented on course_discovery/apps/publisher/views.py
> +        if course_form.is_valid() and entitlement_form.is_valid():
Alternatively, you could include the waffle check in the logic here.

```
does_not_support_entitlements = not waffle.switch_is_active(PUBLISHER_ENTITLEMENTS_WAFFLE_SWITCH)
if course_form.is_valid() and (does_not_support_entitlements or entitlement_form.is_valid()

`

2018-02-02 17:20 UTC, mikix commented on course_discovery/apps/publisher/templates/publisher/course_run/edit_run_form.html
> +                            <div id="seatPriceBlock" class="col col-6 {% if seat_form.type.value == 'audit' or not seat_form.price.value %}hidden{% endif %}">
True. But we're starting to shave yaks now. I originally left these ids unchanged to be minimally-disruptive, before a nit in a previous review suggested the capitalization change. If you prefer a full fix to the SeatPriceBlock mess (which is a totally valid POV), I think I'll undo the changes in this PR and make a separate PR for that cleanup to keep work separated. But if this is a small nit comment, I'll leave it as-is for now to reduce PR scope creep.

2018-02-02 17:33 UTC, mikix commented on course_discovery/apps/publisher/templates/publisher/add_course_form.html
> +                </div>
This is a django template, which is autoescaped, right?

2018-02-02 17:41 UTC, mikix commented on course_discovery/apps/publisher/tests/test_views.py
> +        toggle_switch(PUBLISHER_ENTITLEMENTS_WAFFLE_SWITCH, True)
It just creates a Switch object in the database, which gets reset because we are using Django's TestCase class which clears the database between tests. So I believe we're safe.

2018-02-02 18:22 UTC, amangano-edx commented on course_discovery/apps/publisher/templates/publisher/course_run/edit_run_form.html
> +                            <div id="seatPriceBlock" class="col col-6 {% if seat_form.type.value == 'audit' or not seat_form.price.value %}hidden{% endif %}">
I think it's fine to leave it as is.

2018-02-02 21:05 UTC, mikix commented on course_discovery/apps/publisher/views.py
> +        if course_form.is_valid() and entitlement_form.is_valid():
entitlement_form is valid when it's empty (this is tested by test_valid_price with arguments of None, None).

If you don't feel strongly about moving it, I'd prefer to keep it where it is, for symmetry and because it falls down to a raised exception below automatically (rather than moving it and explicitly raising a new exception if it's false).

2018-02-02 21:07 UTC, mikix commented on course_discovery/apps/publisher/templates/publisher/add_course_form.html
> +                </div>
As we discussed in person, the translated text is *not* autoescaped. But we filed a separate ticket for discovery as a whole.

2018-02-02 21:07 UTC, mikix commented
OK, I've updated this PR to address your comments, @amangano-edx. Should be good for another look.

2018-02-05 14:30 UTC, jlajoie commented on course_discovery/apps/publisher/templates/publisher/add_course_form.html
> +                <div class="field-title">{% trans "CERTIFICATE TYPE AND PRICE" %}</span></div>
Does it make sense to have the translation be from all caps, wouldn't it make more sense to have that stylization be handled through the django `upper` filter?

2018-02-05 14:30 UTC, jlajoie commented on course_discovery/apps/publisher/templates/publisher/add_course_form.html
> +                <div class="field-title">{% trans "CERTIFICATE TYPE AND PRICE" %}</span></div>
Nevermind, just saw that the rest of the file is done this way and this will be consistent.

2018-02-05 14:39 UTC, mikix commented on course_discovery/apps/publisher/templates/publisher/add_course_form.html
> +                <div class="field-title">{% trans "CERTIFICATE TYPE AND PRICE" %}</span></div>
Great question -- you are probably right. However, this string exists already on the course run page. So doing this one the right way would introduce a new translation string.

2018-02-05 14:41 UTC, mikix commented on course_discovery/apps/publisher/templates/publisher/add_course_form.html
> +                <div class="field-title">{% trans "CERTIFICATE TYPE AND PRICE" %}</span></div>
Heh whoops, sorry. Github didn't show me your second comment.

2018-02-05 14:58 UTC, jlajoie approved these changes

2018-02-05 15:30 UTC, amangano-edx commented on course_discovery/apps/publisher/forms.py
> +    def save(self, commit=True, course=None):  # pylint: disable=arguments-differ
The SeatForm takes a `changed_by` keyword argument. Is that something we'll need for the `CourseEntitlement` model?

2018-02-05 15:32 UTC, amangano-edx commented on course_discovery/apps/publisher/forms.py
> +        has_price = price is not None and price > 0
Nit: You could simplify this as: `has_price = price and price > 0`

2018-02-05 15:33 UTC, amangano-edx commented on course_discovery/apps/publisher/forms.py
> +        if has_mode != has_price:
Nit: This is a little hard to parse. I think something like `if has_mode and not has_price:` is clearer.

2018-02-05 15:35 UTC, amangano-edx commented on course_discovery/apps/publisher/forms.py
> +        if has_mode != has_price:
Though, I guess you would lose out on the validation that ensures price must be null when mode is null, so maybe it's better to keep it like you have it.

2018-02-05 15:37 UTC, amangano-edx commented on course_discovery/apps/publisher/templates/publisher/add_course_form.html
> +                <div class="field-title">{% trans "CERTIFICATE TYPE AND PRICE" %}</span></div>
Nit: It's easier to see the beginning/end of the if block when the enclosed code is indented.

2018-02-05 15:40 UTC, amangano-edx commented on course_discovery/static/js/publisher/seat-type-change.js
> +$(document).on('change', '#id_type, #id_mode', function (e) {
Sanity Check: It won't cause any issues if `#id_mode` is not in the DOM right (it won't be on the add_courserun_form)?

2018-02-05 15:46 UTC, amangano-edx commented on course_discovery/apps/publisher/views.py
> +                'entitlement_form': entitlement_form,
I think this needs to be added conditionally, otherwise we may show the entitlement form even when the waffle flag is off after an initial POST request fails with an error.

2018-02-05 15:56 UTC, amangano-edx requested changes
Looks good overall, but I think we need to change `post` to ensure that the entitlement form isn't mistakenly rendered on error.

2018-02-05 16:01 UTC, mikix commented on course_discovery/static/js/publisher/seat-type-change.js
> +$(document).on('change', '#id_type, #id_mode', function (e) {
No issue that I can see. For example, in the course creation page, #id_type doesn't exist either. jquery seems to handle it gracefully.

2018-02-05 16:07 UTC, mikix commented on course_discovery/apps/publisher/views.py
> +                'entitlement_form': entitlement_form,
Right you are -- I missed that when changing how the form worked, thanks. Done now (plus a nit above).

2018-02-05 16:57 UTC, mikix commented on course_discovery/apps/publisher/forms.py
> +        has_price = price is not None and price > 0
Actually, that can change has_price into None instead of False. I want them both to be bools for comparison's sake.

2018-02-05 16:58 UTC, mikix commented
OK, should be good for another look. Fixed the context setting. Squashed and updated translations too.

2018-02-05 18:32 UTC, amangano-edx commented on course_discovery/apps/publisher/views.py
> +                    support_entitlements = waffle.switch_is_active(PUBLISHER_ENTITLEMENTS_WAFFLE_SWITCH)
If you move this to the top of the method, you can re-use it on line 347.

2018-02-05 18:38 UTC, mikix commented on course_discovery/apps/publisher/views.py
> +                    support_entitlements = waffle.switch_is_active(PUBLISHER_ENTITLEMENTS_WAFFLE_SWITCH)
Gah yes. Fixed. That's what I get for quick fixin'.

2018-02-05 19:09 UTC, amangano-edx approved these changes

2018-02-05 20:15 UTC, merged