EDUCATOR-2231 remove course run enrollment dates references
openedx/course-discovery pull request #1336
Opened 2018-02-27 17:04 UTC by Rabia23

2018-03-02 09:53 UTC, awaisdar001 requested changes

2018-03-02 09:53 UTC, awaisdar001 commented on course_discovery/apps/publisher/api/v1/tests/test_views.py
> -        assert discovery_course_run.enrollment_start == publisher_course_run.enrollment_start
Test to see if `discovery_course_run.enrollment_start == None`

2018-03-05 07:49 UTC, awaisdar001 reviewed
👍

2018-03-05 07:49 UTC, awaisdar001 commented on course_discovery/apps/publisher/api/v1/tests/test_views.py
>          assert discovery_course_run.max_effort == publisher_course_run.max_effort
Just curious to know, can we use `self.assertEqual` here?

2018-03-06 09:41 UTC, Rabia23 commented
@schenedx Can you please have a look at this one too?

2018-03-06 14:40 UTC, schenedx reviewed
I believe you can also remove the reference of enrollment_start and end from the model.py, just don't check in the migration file generated.
Additionally, why update all the assert styles in tests? What is the value of making those changes?

2018-03-07 12:25 UTC, Rabia23 commented
@schenedx just curious to know, what is the hesitation of not generating migration file after removing the reference of enrollment_start and end from the model.py file.

2018-03-07 12:33 UTC, Rabia23 commented
`assert` is pure python related thing and `self. assertEqual()` comes from `unittest.TestCase.assertEqual()` so i think it's good idea to use `assertEqual` instead of `assert` in unit tests.

2018-03-07 15:33 UTC, schenedx commented
@Rabia23 
Do you know how the code deploys to production? Do you know that data base table change will be first introduced into the production system, then after a few minutes, the actual server code will change? If we introduce migration within the same PR, the database will have breaking change deployed before the servers code will be updated. Within that few minutes a lot of things will break. If you still have questions, I strongly recommend you talk to someone like @waheedahmed to understand more.
As for the assert changes, there are school of thought that python asserts are better choice than the unit test implementation of the asserts. If the changes from one thing to the other do not have any value, why make them? I would be against changing code because you thought one way is better than the other way while both ways works.

2018-03-08 09:40 UTC, closed without merging

2018-03-08 10:47 UTC, Rabia23 commented
@schenedx Thank you for taking deployment process into my account . I didn't know this before. I messed up this PR so i have opened new PR https://github.com/edx/course-discovery/pull/1350 in which I have removed the reference of `enrollment_start` and `enrollment_end` from the model.py file and also revert back `assert` changes. 
Please have a look at that PR.
Thanks.