Catalog_query contains endpoint
openedx/course-discovery pull request #1344
Opened 2018-03-05 17:28 UTC by McKenzieW

Add an endpoint in discovery that can determine whether a given set of courses and/or course runs exist in the subset of the course catalog described by a given query.

[LEARNER-4166](https://openedx.atlassian.net/browse/LEARNER-4166) Discovery subtask

2018-03-05 17:44 UTC, McKenzieW commented
@edx/helio take a look

2018-03-05 18:03 UTC, Mjloturco requested changes
Mostly looks good! I'd recommend we get someone with a good eye for performance to take a look at this, since this will get hit for most ecommerce basketCalculateView calls and for a bunch of BasketAdd calls I believe as well.

2018-03-05 18:03 UTC, Mjloturco commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +        if query and course_run_ids or course_uuids:
Python [order of precedence](http://www.mathcs.emory.edu/~valerie/courses/fall10/155/resources/op_precedence.html) with do this as 
``` python
if (query and course_run_ids) or course_uuids:
```
not sure thats what you want here.

2018-03-05 18:03 UTC, Mjloturco commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +                ids_in_queryset = list(CourseRun.search(query).filter(partner=partner.short_code).
could the chained filters be condensed? 

``` python 
list(CourseRun.search(query).filter(partner=partner.short_code, key__in=course_run_ids).values_list('key', flat=True))
```

2018-03-05 18:03 UTC, Mjloturco commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +                ids_in_queryset += list(Course.search(query).filter(partner=partner).filter(uuid__in=course_uuids).
ditto on filter merge.

2018-03-05 18:03 UTC, Mjloturco commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +        query = request.GET.get('query')
Seems like we may want to do some optimization around this query, could we somehow detect if the query is 'All' and just return an all valid response? Would cut down on a lot of DB call if we have coupons that are valid for all runs/courses.

2018-03-05 18:03 UTC, Mjloturco commented on course_discovery/apps/course_metadata/search_indexes.py
> +    uuid = indexes.CharField(model_attr='uuid')
Does adding things to the index have any weird impacts on Search? Like does this expose the uuid in places it shouldn't be? (I suspect no but might be worth checking)

2018-03-05 18:23 UTC, McKenzieW commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +        query = request.GET.get('query')
From the discussion I had with Michael he didn't seem particularly interested in adding query-aware functionality to this code, largely because it could get really mucky (unfortunately there are a lot of different variations that could essentially "all" either of courses or course runs or both) one thing I do know though is that when elasticsearch gets the `*:*` query it does just return all without performing any sort of search functionality.

2018-03-05 18:23 UTC, McKenzieW commented on course_discovery/apps/course_metadata/search_indexes.py
> +    uuid = indexes.CharField(model_attr='uuid')
I'm not sure, I will see what I can find about that.

2018-03-05 20:32 UTC, Mjloturco approved these changes

2018-03-06 13:02 UTC, staubina requested changes
Please let me know if you have any questions about my comments.

2018-03-06 13:02 UTC, staubina commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +        Returns a dict mapping the course and run indentifiers included in the request to boolean values
Small code style things this should match the Docstrings code style defined here:

http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#docstrings

```
Returns
    dict:  mapping the course and run indentifiers included in the request to boolean values
        indicating whether or not the associated course or run is contained in the queryset
        described by the query found in the request.
```

2018-03-06 13:02 UTC, staubina commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +        serializer: serializers.ContainedCoursesAndRunsSerializer
Is this another Returned object?

2018-03-06 13:02 UTC, staubina commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +        return Response(status=status.HTTP_400_BAD_REQUEST)
It might be of value to say why this was a bad request or log the reason.

2018-03-06 13:02 UTC, staubina commented on course_discovery/apps/api/v1/tests/test_views/test_catalog_queries.py
> +        self.assertEqual(
We should stick to one form of assertion in our tests.  self.assertEqual is from the unittest package while assert is the pytest method.  I believe we are moving toward using pytest more now.  I would recommend using one or the other. I am currently using assert myself.

2018-03-06 13:02 UTC, staubina commented on course_discovery/apps/api/v1/tests/test_views/test_catalog_queries.py
> +        self.assertEqual(
I am verifying this with TestEng.

2018-03-06 13:08 UTC, McKenzieW commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +        serializer: serializers.ContainedCoursesAndRunsSerializer
No it at one point was a serializer I was going to use on the dataset to construct the return object but I switched approaches and just forgot to remove it from the docstring.

2018-03-06 14:05 UTC, staubina approved these changes
Overall looks good to me.  I would take some time to take what Nimisha mentioned into consideration.

2018-03-06 14:21 UTC, nasthagiri commented on course_discovery/apps/api/v1/urls.py
> +    url(r'^catalog_query/contains/?', CatalogQueryContainsViewSet.as_view(), name='catalog_query-contains')
When designing APIs, a top-most consideration is consistency with other endpoints - from the perspective of the API consumer.

For example, compare the difference in usage and behavior between
`/course_runs/contains` and `/catalogs/contains`
where the former takes a query string while the latter doesn't. 

And compare the difference in naming between
`/course_runs/contains` and the proposed `/catalog_query/contains`
where their usage and behavior are consistent, but the naming isn't.

I believe to be clear to the consumer, you probably want all 4 of the permutations:

- /course_runs/contains/
- /catalogs/contains/
- /course_runs/query_contains/
- /catalgos/query_contains/

Also, as mentioned in our discussion, these "contains" endpoints are currently not RESTful.  But that opens up a larger conversation.

2018-03-06 15:43 UTC, McKenzieW commented on course_discovery/apps/course_metadata/search_indexes.py
> +    uuid = indexes.CharField(model_attr='uuid')
I spoke to Doug Hall and he confirmed that this change would not likely have any performance implications.

2018-03-07 16:19 UTC, jaebradley commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +            ids_in_question = []
Nit: `ids_in_queryset` and `ids_in_question` make sense - but they seem implementation-focussed?

`ids_in_queryset` seems to represent all the specified course identifiers and `ids_in_question` seems to represent all the identifiable course identifiers (lol say that five times fast)?

So maybe `specified_course_ids` and `identified_course_ids` might provide more context?

2018-03-07 16:19 UTC, jaebradley commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +                course_run_ids = course_run_ids.split(',')
I think it's fine here, but in general, variable reassignment can sometimes lead to unexpected complications.

2018-03-07 16:19 UTC, jaebradley commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +                ids_in_queryset += list(Course.search(query).filter(partner=partner, uuid__in=course_uuids).
It's `partner=partner` here and `partner=partner.short_code` above - does it matter?

2018-03-07 16:19 UTC, jaebradley commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +            contains = {str(indentifier): indentifier in ids_in_queryset for indentifier in ids_in_question}
Nit: typo - `indentifier` vs. `identifier`?

2018-03-07 16:19 UTC, jaebradley commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +            contains = {str(indentifier): indentifier in ids_in_queryset for indentifier in ids_in_question}
Probably doesn't make that big of a performance difference overall but [`set`s are probably a lot faster than `list`s for existence checking](https://stackoverflow.com/questions/2831212/python-sets-vs-lists).

Maybe consider making `ids_in_queryset` a `set`?

2018-03-07 16:20 UTC, Mjloturco commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +                ids_in_queryset += list(Course.search(query).filter(partner=partner, uuid__in=course_uuids).
Courses vs CourseRuns probably store the partner relationship differently.

2018-03-07 19:07 UTC, jaebradley commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +            'CatalogQueryContains endpoint requires query and indentifiers list(s)', status=status.HTTP_400_BAD_REQUEST
Nit: `indentifiers` vs. `identifiers`

2018-03-07 19:07 UTC, jaebradley commented on course_discovery/apps/api/v1/tests/test_views/test_catalog_queries.py
> +        url = '{}/?{}'.format(reverse('api:v1:catalog-query_contains'), qs)
if you're worried about repeating yourself you could just move this to a test variable?

2018-03-07 19:07 UTC, jaebradley commented on course_discovery/apps/api/v1/tests/test_views/test_catalog_queries.py
> +        self.assertEqual(response.data, 'CatalogQueryContains endpoint requires query and indentifiers list(s)')
This `str` message seems duplicated - you could consider moving this to a test variable?

2018-03-07 21:44 UTC, jaebradley commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +                identified_course_ids = set(CourseRun.search(query).filter(
Does `values_list` return an `iterable`?

You can append an `iterable` to a `set` by calling `update`.

![image](https://user-images.githubusercontent.com/8136030/37119788-8ce31a8e-2226-11e8-99fe-f36133812a97.png)

2018-03-07 21:45 UTC, McKenzieW commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +                identified_course_ids = set(CourseRun.search(query).filter(
oh yay! it does return an iterable. Thank you!

2018-03-08 14:11 UTC, Mjloturco approved these changes
Just clean up that extra logger and then this looks good to go.

2018-03-08 14:11 UTC, Mjloturco commented on course_discovery/apps/api/v1/views/catalog_queries.py
> +logger = logging.getLogger(__name__)
Nit: logging looks unused

2018-03-08 15:53 UTC, staubina approved these changes
:shipit:

2018-03-08 16:10 UTC, merged