Updated travis validate translations
openedx/course-discovery pull request #1347
Opened 2018-03-06 11:26 UTC by Ayub-Khan

Create a validate_translation script and started
using the script for validation to update travis
check.

2018-03-06 14:13 UTC, amangano-edx requested changes
I don't think you need a custom validate script. As of https://github.com/edx/i18n-tools/tree/0.4.0, the i18n_tool validate command will return a non-zero exit code if any translations fail validation, which will break the jenkins/travis builds. Therefore, you should be able to just use i18n_tool validate directly,.

2018-03-07 17:00 UTC, amangano-edx commented on .travis.yml
> +    - docker exec -t discovery bash -c 'source /edx/app/discovery/discovery_env && cd /edx/app/discovery/discovery/course_discovery && i18n_tool validate'
Alternatively, you could add a make target that changes the directory to `course_disovery` before running the `i18n_tool validate`, much like the `make fake_translations` command does. This would make it easier to run the validator locally.

2018-03-07 17:00 UTC, amangano-edx commented
Please validate that this works by creating a test branch, committing a bad translation to it, and confirming that the build fails.

2018-03-07 17:00 UTC, amangano-edx commented
Also, please confirm that the correct version of edx-i18n-tools is installed (>= 0.4.0) in the travis environment.

2018-04-18 16:29 UTC, hamzamunir7300 reviewed
:+1

2018-04-18 16:29 UTC, hamzamunir7300 approved these changes
:+1

2018-04-18 16:30 UTC, merged