ENT-960 Fix catalogs creation bug due to request data format
openedx/course-discovery pull request #1401
Opened 2018-04-19 11:22 UTC by zubair-arbi

@asadiqbal08 @saleem-latif 
Catalogs creation endpoint in discovery was expecting list value for viewers `'viewers': ['user_1', 'user_2']` but catalogs creation page in LMS api-admin was sending serialized value for viewers field `viewers': "['user_1, 'user_2']"`.

* Updated Catalogs creation view to expect request data in json format
* Update tests to reflect the change

**Testing Instructions:**
* Setup edx-platform with discovery service point to the branch `zub/ENT-960-fix-catalogs-creation-bug`.
* Open catalogs creation page in edx-platform `http://localhost:8000/api-admin/catalogs/`
<img width="604" alt="screen shot 2018-04-19 at 4 13 28 pm" src="https://user-images.githubusercontent.com/5072991/38988506-d4b83492-43ec-11e8-9b40-acdb6fe4c67b.png">
* Search catalogs with an existing username.
* View the catalogs list page along with catalog creation form. Provide details on the catalog creation form.
<img width="311" alt="screen shot 2018-04-19 at 4 14 00 pm" src="https://user-images.githubusercontent.com/5072991/38988530-f034b0ba-43ec-11e8-9edd-0874e59be9e6.png">
* Verify that on clicking button "Catalog Creation" the user is redirected to catalog detail page.
<img width="333" alt="screen shot 2018-04-19 at 4 14 22 pm" src="https://user-images.githubusercontent.com/5072991/38988752-d371852e-43ed-11e8-832b-4b09ddd47d10.png">

2018-04-19 11:57 UTC, saleem-latif approved these changes

2018-04-19 12:54 UTC, zubair-arbi commented
@georgebabey please have a look on this fix.

2018-04-19 15:31 UTC, georgebabey requested changes
We should avoid changing the API and instead change the caller (LMS api-admin).  Changing the caller would also avoid having to evaluate the usernames which seems like a stronger API

2018-04-20 12:08 UTC, zubair-arbi commented
@georgebabey @saleem-latif I have updated edx-platform code to provide proper list so I am closing this PR in favor of https://github.com/edx/edx-platform/pull/18003

2018-04-20 12:08 UTC, closed without merging