Update corresponding drupal node on instructor update via publisher
openedx/course-discovery pull request #1404
Opened 2018-04-23 11:08 UTC by asadazam93

## [EDUCATOR-2518](https://openedx.atlassian.net/browse/EDUCATOR-2518)

### Description
When an instructor is updated via the publisher front end it will update the corresponding person node on the drupal site. Since we do not have the node id in discovery (which is required to update a node in drupal) a get request is first sent to drupal with the uuid to get the corresponding node id and then the node is updated via the node id.
If no node exists for a uuid in that case only discovery will be updated and the drupal update will be skipped. (This is an extreme edge case as for all person created via publisher we always fill the uuid but since there are some instructors that have uuid empty in the existing database I have covered this edge case)

**Sandbox**
N/A

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] @schenedx 
- [ ] @awaisdar001 

### Post-review
- [ ] Rebase and squash commits

2018-04-23 11:11 UTC, asadazam93 commented
Adding test case for update

2018-04-23 11:14 UTC, awaisdar001 commented on course_discovery/apps/api/v1/views/people.py
> +                self.perform_update(serializer)
Where this update is performed after the call to `marketing_person.update_person`?

2018-04-23 11:16 UTC, awaisdar001 commented on course_discovery/apps/api/v1/views/people.py
> +        if waffle.switch_is_active('publish_person_to_marketing_site'):
We can simplify the indentation by
```
if not waffle.switch_is_active('publish_person_to_marketing_site'):
    return

```

Even better 
```
if not publish_person_to_marketing():
    return
```

2018-04-23 11:19 UTC, awaisdar001 commented on course_discovery/apps/api/v1/views/people.py
> +        Update a person
Please be more descriptive where it updates the person ?

2018-04-23 11:22 UTC, asadazam93 commented on course_discovery/apps/api/v1/views/people.py
> +                self.perform_update(serializer)
This updates the Person instance in course metadata

2018-04-23 11:41 UTC, awaisdar001 commented on course_discovery/apps/api/v1/views/people.py
> +                self.perform_update(serializer)
Can we the method name readable?

2018-04-23 11:52 UTC, asadazam93 commented on course_discovery/apps/api/v1/views/people.py
> +                self.perform_update(serializer)
This method is inherited from django ModelViewSet

2018-04-23 13:58 UTC, schenedx requested changes
Please add unit tests

2018-04-23 13:58 UTC, schenedx commented on course_discovery/apps/api/v1/views/people.py
> +                        'uuid': person_data['uuid']
Why do we want to update `UUID`? This value originally comes from the marketings site anyways. Let's not update it.

2018-04-23 13:58 UTC, schenedx commented on course_discovery/apps/api/v1/views/people.py
> +                        'given_name': serializer.validated_data['given_name'],
I believe this is the same list of fields as the `create` method above. Can we refactor this list of fields to create/update into a single function so we can change this later with needs?

2018-04-23 13:58 UTC, schenedx commented on course_discovery/apps/api/v1/views/people.py
> +                self.perform_update(serializer)
This method should be performed whether or not the waffle flag `publish_person_to_marketing_site` is true. I think you put this inside the if statement?

2018-04-23 13:58 UTC, schenedx commented on course_discovery/apps/api/v1/views/people.py
> +                self.perform_update(serializer)
Or the waffle flag really is `enable_update_person`?

2018-04-24 13:54 UTC, asadazam93 commented on course_discovery/apps/api/v1/views/people.py
> +                        'uuid': person_data['uuid']
I am just passing the uuid to the update_person method as it uses the uuid to request for the node id. This is not the data to be updated. The data to be updated is returned by _get_node_data method

2018-04-24 13:55 UTC, asadazam93 commented on course_discovery/apps/api/v1/views/people.py
> +                        'given_name': serializer.validated_data['given_name'],
The list is slightly different as I pass uuid to the update_person method which is not passed to create method.

2018-04-24 13:59 UTC, asadazam93 commented on course_discovery/apps/api/v1/views/people.py
> +                self.perform_update(serializer)
This is how it has been implemented in the create method as well. This is just to make the data consistent. If one is updated and the other isn't that would make the data inconsistent. And the way it currently works the data would be reverted as drupal would override discovery when refresh metadata runs. I think updating the flag is what we need to do here

2018-04-24 14:05 UTC, asadazam93 commented
Adding unit tests

2018-04-24 14:51 UTC, schenedx reviewed
See my comments on UUID

2018-04-24 14:51 UTC, schenedx commented on course_discovery/apps/api/v1/views/people.py
> +                        'given_name': serializer.validated_data['given_name'],
If you are passing in node_uuid explicitly, you will have these two objects the same.

2018-04-24 14:51 UTC, schenedx commented on course_discovery/apps/api/v1/views/people.py
> +                        'uuid': person_data['uuid']
If you are passing the UUID into the update_person method because it needs it, please make the parameter of the method be explicit! Your `update_person` method should have this signature:
```
def update_person(self, partner, node_uuid, person):
```

2018-04-25 12:32 UTC, awaisdar001 commented on course_discovery/apps/api/v1/views/people.py
> +                'An error occurred while adding the person [%s]-[%s]-[%s].',
Can this error be explicit that where the error occurred? i.e. adding in discovery.

2018-04-25 12:32 UTC, awaisdar001 commented on course_discovery/apps/api/v1/views/people.py
> +        Update a person
Doc string

2018-04-25 12:35 UTC, awaisdar001 commented on course_discovery/apps/course_metadata/people.py
> +            logger.info('Person with UUID [%s] does not exist on the marketing site', person_uuid)
is it intentional to use `info` here?

2018-04-25 20:03 UTC, schenedx commented
@asadazam93 We should have some unit tests on the view as well.

2018-04-26 08:09 UTC, asadazam93 commented on course_discovery/apps/course_metadata/people.py
> +            logger.info('Person with UUID [%s] does not exist on the marketing site', person_uuid)
yes it is intentional. If drupal node is not found it should update the course discovery instance. Just added a log here so that if any data revert issue comes up we can check if the node was found or not.

2018-04-26 08:37 UTC, asadazam93 commented
@schenedx the view tests already exist. I have updated the test

2018-04-26 08:51 UTC, awaisdar001 approved these changes

2018-04-26 14:36 UTC, schenedx approved these changes
:+1:

2018-04-26 14:36 UTC, schenedx commented on course_discovery/apps/api/v1/views/people.py
> +    def _get_person_data(self, serializer):
Nice!

2018-04-26 14:36 UTC, schenedx commented on course_discovery/apps/course_metadata/people.py
> +            'title': person['given_name'] + ' ' + person['family_name'],
This is the title of the actual drupal node? It's not learner visible, correct?

2018-04-27 11:40 UTC, asadazam93 commented on course_discovery/apps/course_metadata/people.py
> +            'title': person['given_name'] + ' ' + person['family_name'],
yes correct

2018-04-27 11:40 UTC, merged