Add Journal functionality
openedx/course-discovery pull request #1428
Opened 2018-06-04 14:52 UTC by tuchfarber

This PR contains all changes needed to add Journal functionality to the discovery service.

2018-06-05 19:53 UTC, tuchfarber commented
@mikedikan @schenedx We previously discussed that all major discovery changes should be signed off by all three teams. Since this would probably fall into the category of a major change, I requested review from the both of you. If you don't feel like your the right person for the review, feel free to swap with someone. Cheers!

2018-06-05 20:21 UTC, mikedikan commented
@tuchfarber - I think @bderusha and I would love to take a look, can it be after the hackathon?

2018-06-05 20:29 UTC, tuchfarber commented
@mikedikan For sure! No rush.

2018-06-11 20:15 UTC, tuchfarber commented
@mikedikan @bderusha Just a ping now that the hackathon is over. We'd like to get this merged before end of week if possible. Thanks again!

2018-06-12 19:21 UTC, bderusha requested changes

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/api/serializers.py
> +            'slug'
NIT: add trailing comma

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/api/serializers.py
> +            'applicable_seat_types'
NIT: trailing comma

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/api/serializers.py
> +class JournalSerializer(serializers.ModelSerializer):
Can we add the `prefetch_queryset` pattern used elsewhere in our serializers to prevent N+1 queries and other DB performance issues.

https://github.com/edx/course-discovery/search?q=prefetch_queryset&unscoped_q=prefetch_queryset

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/README.rst
> +The journal bundle is a collection of journals and courses. It works similar to a program in the bundling aspect, the difference lies in the fact that it doesn't necessarily constitute a progression
Are there any other use cases product envisions for journal bundles?

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/api/v1/views.py
> +    queryset = Journal.objects.all().order_by('-created')
Is there a business reason for `order_by('-created')`?

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/constants.py
> +UUID_PATTERN = '[0-9a-f-]+'
Should this pattern live in (or be imported from `core`)?

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/migrations/0011_journal_slug.py
> +# -*- coding: utf-8 -*-
There are a lot of migrations here for a feature that hasn't landed yet :)  which makes sense based on how we develop but it would be great to consolidate these 

https://docs.djangoproject.com/en/1.9/ref/django-admin/#django-admin-squashmigrations

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/models.py
> +        help_text=_('Used to determine whether journal is marketed or not.'),
Would we ever need to market a journal before it is active?

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/models.py
> +    status = models.CharField(
Will we ever need to allow access to a journal after it has been made inactive?

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/models.py
> +    access_length = models.IntegerField(null=True, help_text='number of days valid after purchase', default=365)
NIT:  prefer to add the units to the field name `access_length_days`

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/models.py
> +            ('partner', 'uuid'),
`uuid` should already be unique... not sure what this is accomplishing.

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/models.py
> +        help_text=_('Used to determine whether journal is marketed or not.'),
Also, please do not translate this text.

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/models.py
> +        help_text=_('The user-facing display title for this Journal Bundle'),
don't translate help text

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/views.py
> +# Create your views here.
Remove if not required

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/models.py
> +    # ecommerce related
How do we populate this?

2018-06-12 19:21 UTC, bderusha commented on course_discovery/apps/journal/models.py
> +    # marketing related fields
How do we populate this?

2018-06-12 19:25 UTC, mikedikan reviewed
First pass

2018-06-12 19:25 UTC, mikedikan commented on course_discovery/apps/journal/README.rst
> +The Journal app in discovery is meant to the source of truth for most journal related information. It includes two models: Journal and JournalBundle.
to be the

2018-06-12 19:25 UTC, mikedikan commented on course_discovery/apps/journal/README.rst
> +The journal product is similar to a course run in the fact that it has content is linked to an organization and you can purchase/receive access to it. One notable difference is that a Journal will ha
has content, is linked... organization, and

(commas)

2018-06-12 19:25 UTC, mikedikan commented on course_discovery/apps/journal/README.rst
> +The journal product is similar to a course run in the fact that it has content is linked to an organization and you can purchase/receive access to it. One notable difference is that a Journal will ha
Will journals be re-run?

2018-06-12 19:25 UTC, mikedikan commented on course_discovery/apps/journal/models.py
> +    price = models.DecimalField(**PRICE_FIELD_CONFIG)
How does price get populated?  Are journals defined in ecommerce service?  Is there a process that keeps those prices in sync?

2018-06-12 19:25 UTC, bderusha commented
@tuchfarber I think there are a couple of business logic questions that I have around the use cases and the journal lifecycle that may warrant a quick meeting.  Feel free to schedule one if you'd prefer to not type out answers to my questions to those effects.

2018-06-25 19:08 UTC, tuchfarber reviewed
@mikedikan @bderusha Everything requested has been taken care of. Ready for any followup. (Sorry about the delay, had to get everything reviewed into the feat branch first.)

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/README.rst
> +The Journal app in discovery is meant to the source of truth for most journal related information. It includes two models: Journal and JournalBundle.
Fixed

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/README.rst
> +The journal product is similar to a course run in the fact that it has content is linked to an organization and you can purchase/receive access to it. One notable difference is that a Journal will ha
Clarified

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/README.rst
> +The journal bundle is a collection of journals and courses. It works similar to a program in the bundling aspect, the difference lies in the fact that it doesn't necessarily constitute a progression
Clarified.

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/api/v1/views.py
> +    queryset = Journal.objects.all().order_by('-created')
I think we may have used it previously, but it is no longer needed.

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/constants.py
> +UUID_PATTERN = '[0-9a-f-]+'
Every view has it individually defined. To keep this Journals-only focused, I can follow this up with a change to all of them (this included) 
![image](https://user-images.githubusercontent.com/6179874/41489922-ac781542-70bf-11e8-8eb1-5a7be95d5f41.png)

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/models.py
> +    # ecommerce related
As described per meeting, Journals IDA publishes data out to discovery and ecommerce and is in charge of all creation/modifiying of data.

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/models.py
> +    price = models.DecimalField(**PRICE_FIELD_CONFIG)
Journals IDA publishes data out to discovery and ecommerce and is in charge of all creation/modifiying of data.

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/models.py
> +    # marketing related fields
See above

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/models.py
> +    status = models.CharField(
Added 'retired' field. Cases are now:
- Active: Viewable and purchasable
- Retired: Viewable and not purchasable
- Inactive: Not viewable and not purchasable

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/models.py
> +            ('partner', 'uuid'),
You're right, removed.

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/models.py
> +        help_text=_('The user-facing display title for this Journal Bundle'),
Fixed

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/views.py
> +# Create your views here.
Gone

2018-06-25 19:08 UTC, tuchfarber commented on course_discovery/apps/journal/api/serializers.py
> +class JournalSerializer(serializers.ModelSerializer):
Added

2018-07-02 14:16 UTC, tuchfarber commented
@mikedikan @bderusha Friendly Monday morning ping for a second pass / approval :)

CC: @bill-filler

2018-07-06 15:44 UTC, bderusha approved these changes
Nice work @tuchfarber 👍 Looks good.

I had a few minor comments, but this is mergeable to me.  Your call if you want to do anything with them.  I'm fine either way.

2018-07-06 15:44 UTC, bderusha commented on course_discovery/apps/journal/models.py
> +        default=JournalStatus.Active
Just want to confirm that `Active` is the correct default.  I assumed we would want to make activating a journal an explicit action once it is ready.

2018-07-06 15:44 UTC, bderusha commented on course_discovery/apps/journal/migrations/0001_squashed_0012_auto_20180618_1646.py
> +# -*- coding: utf-8 -*-
NIT:

This file could be cleaned up by dropping these tables from your DB and rerunning `makemigrations`.  I didn't realize that the squash migrations command didn't resolve those things for you.  It'd be great if this file just cleanly created two new tables.

2018-07-10 17:58 UTC, merged