Create new instructor position if blank
openedx/course-discovery pull request #1431
Opened 2018-06-06 11:35 UTC by asadazam93

## [EDUCATOR-3007](https://openedx.atlassian.net/browse/EDUCATOR-3007)

### Description
Blank position check in javascript while loading instructors on the course run edit page. Also if a person has no position and that person is updated with new position data it should create a new position for that person.

**Sandbox**
N/A

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] @attiyaIshaque
- [ ] @awaisdar001

### Post-review
- [ ] Rebase and squash commits

2018-06-07 10:28 UTC, attiyaIshaque approved these changes
Thanks for fixing this. 👍

2018-06-07 17:44 UTC, awaisdar001 requested changes

2018-06-07 17:44 UTC, awaisdar001 commented on course_discovery/apps/api/serializers.py
> +            Position.objects.create(person=instance, **position_data)
Can we use `create_or_update`?

2018-06-08 08:08 UTC, asadazam93 commented on course_discovery/apps/api/serializers.py
> +            Position.objects.create(person=instance, **position_data)
@awaisdar001 there is no unique attribute to use create_or_update. This is just for the instructors that have no position because their position was deleted. Position can no longer be deleted via the admin site. So once all the existing instructors have positions we can even remove this part of the code.

2018-06-11 17:28 UTC, awaisdar001 approved these changes

2018-06-11 17:29 UTC, merged