Add staff permission on discovery people API.
openedx/course-discovery pull request #1447
Opened 2018-06-27 07:44 UTC by attiyaIshaque

2018-06-27 11:37 UTC, asadazam93 commented on course_discovery/apps/api/v1/views/people.py
> +class IsStaff(permissions.BasePermission):
Can we move this to a permissions file?

2018-06-27 11:45 UTC, attiyaIshaque commented on course_discovery/apps/api/v1/views/people.py
> +class IsStaff(permissions.BasePermission):
Sure @asadazam93. There is no permission file. I will create a new one and add it to the permissions file.

2018-06-27 13:36 UTC, schenedx approved these changes
Just a minor question. Rest LGTM

2018-06-27 13:36 UTC, schenedx commented on course_discovery/apps/api/permissions.py
> +        if request.method == 'GET':
Why only check on GET requests? Why not all request methods?

2018-06-27 13:56 UTC, attiyaIshaque commented on course_discovery/apps/api/permissions.py
> +        if request.method == 'GET':
If we add permissions on other requsets method then the course teams can't add or update the instructors because all course team are not having the staff rights.

2018-06-27 14:02 UTC, schenedx requested changes

2018-06-27 14:02 UTC, schenedx commented on course_discovery/apps/api/permissions.py
> +        if request.method == 'GET':
Interesting. Do you know if this change affects publisher viewing instructors? Could you please test that case?
If you are limiting the permission only to "GET" method, could you please update the name of the permission class to be "ReadByStaffOnly"?

2018-06-27 14:25 UTC, attiyaIshaque commented on course_discovery/apps/api/permissions.py
> +        if request.method == 'GET':
@schenedx yeah i have test that it does not affects the publisher viewing instructors. Course runs does not use this GET method.  CC:@asadazam93

And i will change the name of permission class.

2018-06-28 07:56 UTC, attiyaIshaque commented
@schenedx I have changed the name of permission class.

2018-06-28 13:50 UTC, schenedx approved these changes
👍

2018-06-29 07:00 UTC, asadazam93 approved these changes

2018-06-29 09:17 UTC, merged