Added preview accepted status
openedx/course-discovery pull request #1448
Opened 2018-06-29 10:43 UTC by asadazam93

## [EDUCATOR-3040](https://openedx.atlassian.net/browse/EDUCATOR-3040)

### Description
The course run detail page widget sidebar was missing preview accepted status for publisher. I have added a condition to fix it. However, this is not the proper solution as it makes the code unclean and unnecessarily complicated. I have added complete details of the proper solution but since that is a complicated task that is to be done later. 

**Sandbox**
N/A

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] @attiyaIshaque 
- [ ] @Rabia23 

### Post-review
- [ ] Rebase and squash commits

2018-07-02 10:26 UTC, awaisdar001 requested changes

2018-07-02 10:26 UTC, awaisdar001 commented on course_discovery/apps/publisher/templates/publisher/_approval_widget.html
> +                            {% elif course_run.course_run_state.owner_role == 'publisher' and course_run.course_run_state.preview_accepted %}
Can we have `course_run.course_run_state.owner_role` in a varible and use it?

2018-07-02 10:26 UTC, awaisdar001 commented on course_discovery/apps/publisher/templates/publisher/_approval_widget.html
>                          {% elif course_run.course.publisher == request.user %}
also `course_run.course.publisher == request.user` in a variable?

2018-07-02 10:26 UTC, awaisdar001 commented on course_discovery/apps/publisher/templates/publisher/_approval_widget.html
> +                            {% elif course_run.course_run_state.owner_role == 'publisher' and course_run.course_run_state.preview_accepted %}
What about this? and moving all the logic in `course_run` model's class method `preview_status`? 
`<span class="preview-status">{{course_run.preview_status}}</span>`

It looks cleaner.

2018-07-04 10:56 UTC, awaisdar001 approved these changes

2018-07-04 10:58 UTC, awaisdar001 commented
Please add tests as well.

2018-07-05 11:10 UTC, attiyaIshaque approved these changes
Please squash your commits and update your branch with the latest code. 
Once the tests passed. 👍

2018-07-05 12:54 UTC, merged