New Course Run must not be added to associated retired programs.
openedx/course-discovery pull request #1460
Opened 2018-07-11 07:13 UTC by uzairr

## [LEARNER-1176](https://openedx.atlassian.net/browse/LEARNER-1176)

### Description
Project Coordinators need to be able to exclude all future runs of courses in a program, so that they can convert an XSeries program into a Professional Certificate (or into a MicroMasters), without all future course runs applying to both the XSeries program and the Professional Certificate.

- [x] Unit Tests

2018-07-12 00:25 UTC, waheedahmed requested changes

2018-07-12 00:25 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +        retired_programs = self.course.programs.filter(status=ProgramStatus.Retired)
You should make sure that this code only executes on new course run creation, otherwise it will exclude old course runs as well upon updating.

2018-07-12 18:43 UTC, staubina commented on course_discovery/apps/course_metadata/models.py
> +        retired_programs = self.course.programs.filter(status=ProgramStatus.Retired)
With the method being named save I think this is a valid concern here.

2018-07-16 10:39 UTC, uzairr commented on course_discovery/apps/course_metadata/models.py
> +        retired_programs = self.course.programs.filter(status=ProgramStatus.Retired)
good catch @waheedahmed .Now, I have added a check for pk which will ensure that newly added code will be executed only for newly created courseruns

2018-07-18 09:28 UTC, waheedahmed approved these changes
Some minor changes otherwise :+1:

2018-07-18 09:28 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +        is_new_course_run = not self.pk
Move this to top of the function.

2018-07-18 09:28 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +            retired_programs = self.course.programs.filter(status=ProgramStatus.Retired)
CourseRun model have a property `programs`, use that `self.programs.filter(status=ProgramStatus.Retired)`.

2018-07-18 15:08 UTC, staubina approved these changes
Please make @waheedahmed's recommended changes then it should be ready to merge.

2018-07-19 10:03 UTC, waheedahmed approved these changes

2018-07-19 11:33 UTC, merged