Yro add degree submodels
openedx/course-discovery pull request #1461
Opened 2018-07-12 15:49 UTC by yro

# [WIP]

2018-07-12 20:57 UTC, yro commented on course_discovery/apps/course_metadata/models.py
> +        except DegreeMarketing.DoesNotExist:
This is meant as kind of a validation -- ultimately either this will be its own endpoint or call the various and sundry `DegreeMarketing` fields as an addition to the `Program` model for rendering by the future react template.

2018-07-13 13:52 UTC, schenedx requested changes
Most of the work is there done.
I do feel this can be further improved.

2018-07-13 13:52 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +    title = models.CharField(
Both `title` and `subtitle` are common fields between `Program` and `DegreeMarketing`. Are you thinking Degree fields like these should serve as overrides? Or should they be limited to unique fields only related to Degree?
If it's the latter, maybe find a unique field like `application_deadline` or `apply_url` to be the initial field?

2018-07-13 13:52 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +            return degree_marketing.uuid
Instead just returning the `uuid` field here, can you create a new serializer for `DegreeMarketing` model and use that serializer in the MinimalProgramsSerializer?
This is the pattern DRF promotes. Keep the selection of fields to be visible to API in serializer.

2018-07-13 14:44 UTC, yro commented on course_discovery/apps/course_metadata/models.py
> +    title = models.CharField(
@schenedx I don't disagree, but it's still unclear whether or not this is an override. I'll change these fields so that there's not any confusion.

2018-07-13 15:01 UTC, yro commented on course_discovery/apps/course_metadata/models.py
> +            return degree_marketing.uuid
@schenedx agree. Will do.

2018-07-13 16:18 UTC, schenedx approved these changes
This is much better.
I think we can work to merge it asap.

2018-07-13 16:18 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +    uuid = models.UUIDField(blank=True, default=uuid4, editable=False, unique=True, verbose_name=_('UUID'))
I don't yet see how we can use this field anywhere.
Let's take this out, and will add it back in when there is a use?

2018-07-13 16:31 UTC, schenedx commented
@mikedikan @bderusha FYI
Here is our prototype for the degree model to host Master data in discovery.
If you have strong opinions on this PR, please come and talk to us. We are faced with tight deadline and would like to iterate as quickly and frequently as possible.

2018-07-13 17:58 UTC, yro commented on course_discovery/apps/course_metadata/models.py
> +    uuid = models.UUIDField(blank=True, default=uuid4, editable=False, unique=True, verbose_name=_('UUID'))
👍

2018-07-14 17:59 UTC, merged

2018-07-18 14:48 UTC, iloveagent57 commented on course_discovery/apps/course_metadata/models.py
> +    program = models.OneToOneField(
I realize this is already merged, and we can get to it later: this should really be a many-to-many relationship: https://docs.djangoproject.com/en/2.0/topics/db/examples/many_to_many/ with an intermediate table between Degree and Program like `ProgramDegreeMembership`.  This is what enables a Degree to consist of many programs, and for a program to be a part of many different Degrees.

2018-07-18 14:54 UTC, yro commented on course_discovery/apps/course_metadata/models.py
> +    program = models.OneToOneField(
@iloveagent57 Caught up IRL, but absolutely. This model is just a placeholder, and is wide open; I agree -- do your thing.