EDUCATOR-3227: Discovery feeds "Details" to Master's Product Page
openedx/course-discovery pull request #1478
Opened 2018-07-27 17:52 UTC by sandroroux

2018-08-02 13:53 UTC, schenedx requested changes
You need migration file in this PR.

2018-08-02 13:53 UTC, schenedx commented on course_discovery/apps/api/serializers.py
> +    tuition_costs = DegreeCostSerializer(many=True)
#NIT maybe the property name should just be called "costs"? That's simple and easy to understand.

2018-08-03 14:42 UTC, schenedx requested changes
You need the changes to the `DegreeFactory` in factories.py. Those new fields needs to be there and generated for tests to work.
The model in general looks good. Can you put screenshots of how Django Admin interface look on this PR?

2018-08-03 20:42 UTC, iloveagent57 submitted a review, later dismissed
I think using a M2M relationship is not the right thing for these models.  Also, I'm a little wary of us over-using it in general (e.g. for Rankings, which are less likely to run into the issue I've described here, but are still susceptible to it).

2018-08-03 20:42 UTC, iloveagent57 commented on course_discovery/apps/course_metadata/models.py
> +    deadlines = SortedManyToManyField(DegreeDeadline, blank=True)
I'm not sure these should be many-to-many relationships.  It could lead to cases where an existing deadline, used by two different degrees, is modified for the sake of one degree, which means the other degree will now show that updated deadline, too.  This isn't that far-fetched a scenario, since many schools use very similar or identical deadlines for their programs (e.g. January 1st).  It might be better to have `degree` be a FK field of the DegreeDeadline model.

2018-08-03 20:42 UTC, iloveagent57 commented on course_discovery/apps/course_metadata/models.py
> +    costs = SortedManyToManyField(DegreeCost, blank=True)
I think the same argument as for `DegreeDeadline` above holds here.

2018-08-07 14:05 UTC, schenedx requested changes
Please squash all 3 of your migrations into 1

2018-08-07 14:05 UTC, schenedx commented on course_discovery/apps/api/serializers.py
> +    prerequisite_coursework = serializers.CharField()
Why do we want to serialize this to `CharField`? Why not use the default `TextField`, the same as with the model?

2018-08-07 14:05 UTC, schenedx commented on course_discovery/apps/api/tests/test_serializers.py
> +        self.maxDiff = None
You would want these two lines to be removed

2018-08-08 19:54 UTC, schenedx approved these changes
👍

2018-08-09 19:40 UTC, merged

2018-08-10 01:46 UTC, schenedx commented on course_discovery/apps/course_metadata/migrations/0098_degree_lead_capture_image.py
> -        ('course_metadata', '0096_degree_lead_capture_list_name'),
This is a super bad change!
Because of this update, our deployment to stage for this commit fails. The django admin for Degrees model is now throwing 500 errors. I need to think of a way to revert this change cleanly