Yro/EDUCATOR-3226
openedx/course-discovery pull request #1489
Opened 2018-08-03 17:56 UTC by yro

## [EDUCATOR-3226](https://openedx.atlassian.net/browse/EDUCATOR-3226)

### Description
Implement 'Quick Facts' model for marketing site

### Testing
- [ ] Unit tests

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review: @iloveagent57 

FYI: @edx/educator-neem

### Post-review
- [ ] Rebase and squash commits

2018-08-03 20:46 UTC, iloveagent57 requested changes

2018-08-03 20:46 UTC, iloveagent57 commented on course_discovery/apps/course_metadata/models.py
> +    quick_facts = SortedManyToManyField(IconTextPairing, blank=True)
Having a M2M relationship here means the following can happen: degree A and degree B both use IconTextPairing 1.  Someone updates the pairing with a new icon at the request of degree B's institution.  Now that icon is used for both degree A and degree B.  It's probably better to have `degree` by a FK field on the `IconTextPairing` model.
(I just left a comment to this effect on Alessandro's PR, too)

2018-08-03 20:50 UTC, yro commented
Closing PR.

2018-08-03 20:50 UTC, closed without merging

2018-08-03 20:54 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +    icon = models.CharField(max_length=100, verbose_name=_('Icon URL or fa class'))
Having `CharField` here means the data entry person from Marketing needs to know what to enter as the Icon URL. That may not be information they have.
I think a way to provide convenience for marketing user is to create a new table that contains all the FA class options. Then we in engineering fill out the urls for each FA icon or class in the new table. 
This means, on the `IconTextPairing`, it will be just a drop down for Marketing user to select.

2018-08-03 20:54 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +    icon = models.CharField(max_length=100, verbose_name=_('Icon URL or fa class'))
That said, if you think we should consider my suggestion as an enhancement to this, please create a ticket for our project, and we can work on this later.

2018-08-06 13:26 UTC, yro commented
@schenedx @iloveagent57 Thank you for your suggestions, since there are so many requests with downstream effects, I'm going to start a fresh branch.