Fix the character count both in publisher and discovery.
openedx/course-discovery pull request #1554
Opened 2018-09-11 11:32 UTC by attiyaIshaque

2018-09-11 17:25 UTC, awaisdar001 requested changes
I have made few comments also @schenedx to review the migration of the PR as migrations in discovery are often very tricky.

2018-09-11 17:25 UTC, awaisdar001 commented on course_discovery/apps/publisher/forms.py
> +    title = forms.CharField(label=_('Course Title'), required=True)
I think the title doesn't have tinymce widget and hence styling is not available, I would suggest keeping the validator for `title` makes sense.

2018-09-11 17:25 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_views.py
> -        self.AssertEditCourseSuccess(post_data=self._post_data(organization_extension))
I would suggest keeping these methods `AssertEditCourseSuccess` in as they reduce significant LOCs

2018-09-11 17:25 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_views.py
> -    def test_update_course_with_empty_title(self):
`test_update_course_with_empty_title` name makese sense. do not change it.

2018-09-11 17:25 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_views.py
> -    def test_max_length_exceed_error(self, field, max_length):
Add `ddt.data` to test it for all fields like it was testing before.

2018-09-11 17:25 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_views.py
> +    def test_text_area_post_with_html(self, field):
Similarly for this one.

2018-09-11 17:25 UTC, awaisdar001 commented on course_discovery/apps/publisher/tests/test_views.py
> -    def AssertEditFailedWithError(self, post_data, error):
These are good helper methods which we should not be removing.

2018-09-11 18:01 UTC, schenedx commented
@attiyaIshaque Do we have a jira ticket documenting the requirement associated with this work?
also, I don't like how you packaged two different sets of efforts into a single PR. This makes this PR really difficult to review. Can you please separate out your work on converting the short description field from charfield to textfield a separate PR from the revert?

2018-09-12 07:08 UTC, attiyaIshaque commented
Okay, @schenedx I will work in two separate PR's.

2018-09-12 07:08 UTC, closed without merging