Updates to the Ecommerce Data loader to detect network errors
openedx/course-discovery pull request #1557
Opened 2018-09-12 17:09 UTC by staubina

[LEARNER-6317]

Network request error detection added along with a basic retry
to remove the liklihood of intetvention being required.

2018-09-12 17:15 UTC, staubina commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        while (attempt_count == 0 or
Note: When adding in a retry loop the code was shifted in so it looks like more was changed.

2018-09-13 19:43 UTC, bderusha requested changes
The gist of this code looks great.  Left a few comments of things we might want to restructure

2018-09-13 19:43 UTC, bderusha commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        while (attempt_count == 0 or
For readability can we put the code that does the thing in its own method so the ingest method looks more like

```
succeeded = do_the_thing()
attempt_count=1
while(not succeeded and attempt_count < MAX):
    succeeded = do_the_thing()
    attempt_count += 1

if not succeeded:
    error
```

This will also make reviewing this code easier because the indentation will be clear as to what you actually changed.

2018-09-13 19:43 UTC, bderusha commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                    for page in pageranges['course_runs']:
Rather than wrapping the body of these methods with the `try` block can we just wrap this whole section?

2018-09-18 16:33 UTC, staubina commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                    for page in pageranges['course_runs']:
No because the exception will not bubble up out of the thread.  That is why we are not seeing the exceptions at process level.

2018-09-19 15:32 UTC, bderusha approved these changes
One sanity check question, more for me than anything else.  Otherwise :shipit: 


Also squash before merging

2018-09-19 15:32 UTC, bderusha commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                    self.processing_failure_occurred = True
I don't doubt that this works... but I don't understand how.  How does this not get recorded as a failure every time?

2018-09-19 15:57 UTC, staubina commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                    self.processing_failure_occurred = True
Looking at this again I think I need to flip the logic or add a continue.

Good catch.

2018-09-19 16:02 UTC, staubina commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                    self.processing_failure_occurred = True
@bderusha Updated with a new commit.

2018-09-19 16:31 UTC, jlajoie commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        self.course_run_count = 0
I feel for best practice you'll want the locks acquired/released here on course_run_count since this method will be callable from within the threads. Better to just future proof this.

2018-09-19 16:34 UTC, staubina commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        self.course_run_count = 0
👍 on this catch.

2018-09-19 16:36 UTC, staubina commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        self.course_run_count = 0
Actually looking at this again I am not sure it is needed because the threads are not currently active at this point in the code.

The threading starts just below this initialization after the with call.

2018-09-19 16:42 UTC, jlajoie approved these changes

2018-09-21 12:14 UTC, merged