Updating social link UI and making discovery the source of truth for social links
openedx/course-discovery pull request #1635
Opened 2018-12-04 15:25 UTC by Dillon-Dumesnil

DISCO-304

2018-12-05 15:23 UTC, mikix reviewed
Haven't yet reviewed the UI yet - will do that today. But some quick code comments below:

2018-12-05 15:23 UTC, mikix commented on course_discovery/apps/api/serializers.py
> +                PersonSocialNetwork.objects.filter(id=network.id).delete()
I think you can just do "network.delete()" to save on a query here.

2018-12-05 15:23 UTC, mikix commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> -        self.set_social_network(person, data)
:fireworks:

2018-12-05 15:23 UTC, mikix commented on course_discovery/static/js/publisher/instructors.js
> +    addNewSocialLink('banana' + Math.floor(Math.random()*1000000));
You might want the prefix "new" or something? The topical "banana" reference is going to just be a confusing bit of code a year from now.

Also, we have a one in a million chance of a hitting a duplicate id here. You could do something like:

```
function generateNewSocialLinkName() {
    if (typeof generateNewSocialLinkName.counter == 'undefined' ) {
        generateNewSocialLinkName.counter = 0;
    }
    return 'new' + generateNewSocialLinkName.counter++;
}
```

As a way to get a static variable in javascript (so says the internet).

2018-12-05 15:23 UTC, mikix commented on course_discovery/static/js/publisher/instructors.js
> +                                <option value="others">Other</option>\
Blog and other should be gettext-translated. And probably also Facebook and Twitter? I dunno if they have any localized versions, but they might. Maybe so in languages with totally different scripts, like Arabic, they have some translated version.

2018-12-05 15:23 UTC, mikix commented on course_discovery/static/js/publisher/instructors.js
> +                        <button class="remove-social-link-btn" type="button"> X </button>\
I hate to be this guy, but you might consider using ✕ or ✖ (multiplication and heavy multipication) here as more symetrical close glyphs. And more resistant to odd font faces on the client side.

2018-12-05 15:29 UTC, mikix commented on course_discovery/static/js/publisher/instructors.js
> +                        <button class="remove-social-link-btn" type="button"> X </button>\
Or the fontawesome [close icon](https://fontawesomeicons.com/close), if we use font awesome in discovery? (which looks identical to heavy multiplication to me)

2018-12-05 15:46 UTC, mikix commented
In terms of how it looks - it'd be nice if the type and close buttons were as tall as the text boxes. And if we can make the "optional" tag for the title look as grey as the optional tag elsewhere in the form.

But looks great!

2018-12-05 23:03 UTC, Dillon-Dumesnil commented on course_discovery/static/js/publisher/instructors.js
> +var newLinkCount = 1;
Probably a dirty-ish way to do it, but the count will never get particularly high, guarantees we won't see duplicates, and will reset whenever the page is loaded.

2018-12-06 14:05 UTC, mikix approved these changes
All my concerns have been addressed! Thanks and nice work.

2018-12-06 14:14 UTC, AlasdairSwan requested changes
Nice work in an ```interesting``` code base, just a few suggestions.

2018-12-06 14:14 UTC, AlasdairSwan commented on course_discovery/apps/publisher/templates/publisher/_add_instructor_popup.html
> +                    <label class="field-label">{% trans "Social Links" %}
What form element is this label for?

2018-12-06 14:14 UTC, AlasdairSwan commented on course_discovery/apps/publisher/templates/publisher/_add_instructor_popup.html
> +                <button class="btn-base" type="button" id="add-social-link-btn" style="margin-bottom: 20px;">
CSS should be used instead of inline styles. You shouldn't need to add ```type="button"``` when using the ```button``` element. Is the ```id``` being  used somewhere (i.e. I'm not sure you need an id here) ?

2018-12-06 14:14 UTC, AlasdairSwan commented on course_discovery/static/js/publisher/instructors.js
> +                                <option value="others">' + gettext('Other') + '</option>\
Nitpick: ```value="others"``` or ```value="other```.

2018-12-06 14:14 UTC, AlasdairSwan commented on course_discovery/static/js/publisher/instructors.js
> +                        <button class="remove-social-link-btn fa fa-close" type="button"></button>\
No need to set ```type="button"```.

2018-12-06 14:14 UTC, AlasdairSwan commented on course_discovery/static/js/publisher/instructors.js
> +    return [socialLinksArray, error];
Why not just return an object;
```
return {
  socialLinks: [],
  error: ''
};
```

2018-12-06 14:14 UTC, AlasdairSwan commented on course_discovery/static/js/publisher/instructors.js
> +                    data['urls_detailed'][i]['url'],
Nitpick: dot notation is more standard when possible (e.g. ```data.urls_detailed.[i].url```).

2018-12-06 14:14 UTC, AlasdairSwan commented on course_discovery/static/sass/publisher/course_form.scss
> +          @include margin-right(5px);
Nitpick: ```@include```s should be declared at the top of the selector.

2018-12-06 14:14 UTC, AlasdairSwan commented on course_discovery/static/js/publisher/instructors.js
> +        socialLinkError = socialLinks[1];
It's weird that you need to know the position in an array to get various types of data. I would be easier to read/understand if ```getSocialLinks``` returned an object.

2018-12-06 15:06 UTC, Dillon-Dumesnil commented on course_discovery/apps/publisher/templates/publisher/_add_instructor_popup.html
> +                    <label class="field-label">{% trans "Social Links" %}
Talked about in person. Despite this label not corresponding to a form element, it was decided it was not worth switching the element and then fixing the styling.

2018-12-06 15:07 UTC, Dillon-Dumesnil commented on course_discovery/static/js/publisher/instructors.js
> +                                <option value="others">' + gettext('Other') + '</option>\
Talked about in person. It is value 'others' because that is what the database expects.

2018-12-06 16:19 UTC, Dillon-Dumesnil commented
![image](https://user-images.githubusercontent.com/12799718/49596661-da495280-f948-11e8-9b8d-e6b607ab9086.png)

2018-12-06 18:17 UTC, AlasdairSwan approved these changes
Why not :shipit:

2018-12-06 18:36 UTC, merged