Support create and patch in course run API
openedx/course-discovery pull request #1806
Opened 2019-03-04 20:04 UTC by mikix

Allow POST, PATCH, and PUT on the main course run API. And push to studio when changes are made too.

https://openedx.atlassian.net/browse/DISCO-622

2019-03-08 13:28 UTC, staubina requested changes
First run through with comments.  I will try to look again after standup.

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/api/permissions.py
> +            org = course and course.split('+')[0].split('/')[0]  # handle old and new style keys
Are the Opaque keys available in Discovery?  If they are we should use CourseKey here.

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/api/permissions.py
> +            org = course and course.split('+')[0].split('/')[0]  # handle old and new style keys
Example here: https://github.com/edx/course-discovery/blob/dd8f65abc75dc9a424fe5423f1905399f8a990c9/course_discovery/apps/course_metadata/data_loaders/marketing_site.py

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/api/permissions.py
> +class IsCourseRunEditorOrDjangoOrReadOnly(BasePermission):
Can we combine this with the Course permissions method that we created?

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/api/serializers.py
> +        key_sep = '+' if '+' in course.key else '/'
We should use CourseKey here. It will save us a lot of work and understands CourseKey formatting

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/api/utils.py
> +from opaque_keys.edx.keys import CourseKey
Just wanted to point to the use of CourseKey here as a possible example.

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/api/utils.py
> +    """ A convenience class for talking to the Studio API - designed to allow subclassing for publisher models. """
Is there any need to update this comment?

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/api/utils.py
> +    """ A convenience class for talking to the Studio API - designed to allow subclassing for publisher models. """
Also is this all new code or a move from the old Publisher code?

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/api/v1/views/course_runs.py
> +        except Exception as e:  # pylint: disable=broad-except
Do we need a broad exception here?  Is there something that we are trying to catch?

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/api/v1/views/course_runs.py
> +        if course_run.course.partner.studio_url:
What do we do id the URL is not available or set?  Should we log or anything?

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/api/v1/views/course_runs.py
> +        self.push_to_studio(request, course_run, create=True, old_course_run=old_course_run)
Do we care if this fails or succeeds?

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/publisher/signals.py
> -                raise
Just looking at these changes at a high level, will they impact old publisher in any way?

2019-03-08 13:28 UTC, staubina commented on course_discovery/apps/publisher/signals.py
> +        except Exception:  # pylint: disable=broad-except
I think we should be cautious with broad exception catches, are there specific exceptions we are looking for here?

2019-03-08 15:22 UTC, mikix commented on course_discovery/apps/api/permissions.py
> +            org = course and course.split('+')[0].split('/')[0]  # handle old and new style keys
As discussed in IRC, OpaqueKeys is not sufficient here because the parsing you are commenting on is parsing of course key fragments, not full course keys.

I'm adding a utility function to make this clear and collect the two instances of me parsing the course key in one place.

Good call out.

2019-03-08 15:27 UTC, mikix commented on course_discovery/apps/api/permissions.py
> +class IsCourseRunEditorOrDjangoOrReadOnly(BasePermission):
I think two classes fits more naturally for this case:

(1) The course run endpoint also looks at django permissions. And combining "or" permissions kind of has to be done all together in one permission class. But the course endpoint doesn't need that django permission check.

(2) Looking up the course changes a lot based on whether we are at a course or course run endpoint. In one former, the course / org is provided in the incoming data. In the latter, we are looking up a course run / course from the incoming data. So while they call the same permission checking functions, the request parsing is all different.

2019-03-08 15:28 UTC, mikix commented on course_discovery/apps/api/utils.py
> +    """ A convenience class for talking to the Studio API - designed to allow subclassing for publisher models. """
This is a move from old publisher with additional support added for subclassing and overriding all the utility bits like "how do I get the course run key from a course run" - that changes between CourseMetadata and Publisher tables.

The comment is a new comment - doesn't need to be updated. Although maybe it needs to be updated to be better, if you're asking the question? :)

2019-03-08 15:29 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +        if course_run.course.partner.studio_url:
If the partner doesn't have a studio url set (which is an optional field), I figured we don't want to fill their logs with warnings about it.

2019-03-08 15:31 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +        self.push_to_studio(request, course_run, create=True, old_course_run=old_course_run)
If it fails, it will raise an exception that is caught by writable_request_wrapper and returns a 400 to the caller.

2019-03-08 15:34 UTC, mikix commented on course_discovery/apps/publisher/signals.py
> -                raise
The hope is not. Old publisher (in this code block) was always doing "1) check if re-run, then create re-run or run, 2) update icon" -- the new endpoint wanted to do the same thing. So I moved the logic into the shared StudioAPI class. So this is hopefully just a cleanup, not a change in behavior.

2019-03-08 15:38 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +        except Exception as e:  # pylint: disable=broad-except
This is a "did anything go wrong handling this API call" exception catch. Whether that should be broad or not is possibly a philisophical issue. I lean towards broad catches being acceptable for cases like this, because we are on a "boundary" where regardless of what goes wrong, we want to present a uniform answer to the world outside the boundary.

2019-03-08 15:41 UTC, mikix commented on course_discovery/apps/publisher/signals.py
> +        except Exception:  # pylint: disable=broad-except
This specific instance is actually a tightening of a bare-except in the old code that I was refactoring. I'm not sure what all the exceptions it expects or cares about are. Probably just SlumberBaseException in practice.

I *suspect* the original bare except was added simply so they can log a message that tests can pick up. They have one test that adds a side effect exception and checks that it was caught. :man_shrugging: I'd be fine with dropping this except (which simply logs and raises anyway) and reworking that test.

2019-03-08 15:48 UTC, mikix commented on course_discovery/apps/api/utils.py
> +    """ A convenience class for talking to the Studio API - designed to allow subclassing for publisher models. """
Expanded the comment slightly.

2019-03-11 14:14 UTC, staubina commented on course_discovery/apps/api/v1/views/course_runs.py
> +        if course_run.course.partner.studio_url:
When would we care to know about this though?

2019-03-11 14:15 UTC, staubina commented on course_discovery/apps/publisher/signals.py
> -                raise
Have you been able to do any manual testing with old publisher to verify we did not break it?

2019-03-11 14:17 UTC, staubina approved these changes
Overall the changes look good to me.  Should we plan some manual testing if we think it is necessary for old publisher though?  As a result of moving some of the code to shared functionality.

2019-03-11 14:20 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +        if course_run.course.partner.studio_url:
Devstack didn't have it set, but I think that would be an expected situation. If it weren't set in prod, I imagine various little integration points with studio wouldn't work.

I don't know when we would care to know. I'm happy to throw an info log in there - I imagine most prod instances have that field set and wouldn't be spammed so much?

2019-03-11 14:56 UTC, mikix commented on course_discovery/apps/publisher/signals.py
> -                raise
Yes, I can manually create and update the studio course info and image from old publisher.

2019-03-11 15:13 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +        if course_run.course.partner.studio_url:
Added an info output here and a test to confirm it.

2019-03-11 17:59 UTC, merged