Support creating and editing course drafts
openedx/course-discovery pull request #1843
Opened 2019-04-04 20:53 UTC by mikix

Now every time we hit the course API endpoint, we'll create any drafts that are necessary and then edit those drafts.

2019-04-04 20:55 UTC, mikix commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.assertEqual(self.client.patch(url).status_code, 404)
These 404/403 changes are because now that we filter based on editable, the object just isn't found at all and does a 404. I don't super care about the distinction, so I didn't add code to explicitly check for this case. But am willing to discuss if this 403 feels more correct to folks.

2019-04-05 14:13 UTC, staubina requested changes
Some questions and small comments.

2019-04-05 14:13 UTC, staubina commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.assertEqual(self.client.patch(url).status_code, 404)
Do we have any concern that users of the endpoint might have issues with the new status code?

2019-04-05 14:13 UTC, staubina commented on course_discovery/apps/api/v1/views/courses.py
> +            raise  # just pass some exceptions along
Do we care to log out here that we denied permission on a request?

2019-04-05 14:13 UTC, staubina commented on course_discovery/apps/api/v1/views/courses.py
> +        if get_query_param(self.request, 'editable') or self.request.method not in SAFE_METHODS:
`self.request.method not in SAFE_METHODS`

I am interested in this addition here.  Why would we want to set the editable courses on methods that are not "SAFE"?

2019-04-05 14:13 UTC, staubina commented on course_discovery/apps/api/v1/views/utils.py
> +    for f in model._meta.get_fields():
nit: can we use a more descriptive name for `f`?

2019-04-05 14:53 UTC, mikix commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.assertEqual(self.client.patch(url).status_code, 404)
Naw - the only user of this flow is PFE.

2019-04-05 14:53 UTC, mikix commented on course_discovery/apps/api/v1/views/courses.py
> +        if get_query_param(self.request, 'editable') or self.request.method not in SAFE_METHODS:
SAFE methods are get, options, head, etc. Non-SAFE methods are post, put, and patch.

So basically, this is "if the user asked for draft mode or they are trying to write, give 'em drafts"

2019-04-05 14:53 UTC, mikix commented on course_discovery/apps/api/v1/views/courses.py
> +            raise  # just pass some exceptions along
Sure... Makes some sense

2019-04-05 15:34 UTC, mikix commented on course_discovery/apps/api/v1/views/utils.py
> +    for f in model._meta.get_fields():
Done.

2019-04-05 15:34 UTC, mikix commented on course_discovery/apps/api/v1/views/courses.py
> +            raise  # just pass some exceptions along
Upon testing, we do log the status codes like 403 and 404 naturally. That's probably enough?

2019-04-05 15:35 UTC, mikix commented
@staubina I added the course_runs-being-empty fix to this PR. I've tested manually with my created-runs, but if you also want to merge-and-test, that would be welcome. Else we'll see.

2019-04-05 15:59 UTC, staubina commented on course_discovery/apps/api/v1/views/courses.py
> +        if get_query_param(self.request, 'editable') or self.request.method not in SAFE_METHODS:
I recommend a comment here then to make that a little more clear.

Also team note, should we write an ADR about the API changes we have made to go with the Draft ADR?

2019-04-05 15:59 UTC, staubina commented
I will pull down the changes and test locally

2019-04-05 16:00 UTC, staubina approved these changes
Looks good to me.

2019-04-05 16:05 UTC, mikix commented on course_discovery/apps/api/v1/views/courses.py
> +        if get_query_param(self.request, 'editable') or self.request.method not in SAFE_METHODS:
I believe our draft ADR covered the fact that when writing / reading, we'll deal with drafts:

```
Add a query parameter to list endpoints that will return draft versions of
rows if available, and if not available, will return the official versions.
We can just re-use the editable=1 flag for that.

All form and API updates will be applied to the draft row. And only after a
successful review, the data of the draft row will be written to the official
row. (Although that "review" might be a no-op depending on business logic -
it may be skipped if the course run is already live for example.)
```

These API changes are additions, not contract breakages - they used to just not allow writes at all.

2019-04-05 16:41 UTC, merged