WL-1936 | Added estimated hours for course run in catalog list endpoint.
openedx/course-discovery pull request #1907
Opened 2019-05-16 07:29 UTC by hasnain-naveed

2019-05-16 08:34 UTC, ziafazal requested changes

2019-05-16 08:34 UTC, ziafazal commented on course_discovery/apps/api/tests/test_serializers.py
> +                'estimated_hours': ((course_run.min_effort + course_run.max_effort) / 2) * course_run.weeks_to_complete,
we should use the `get_course_run_estimated_hours` method here too

2019-05-16 09:26 UTC, ziafazal approved these changes
👍

2019-05-16 12:47 UTC, georgebabey commented on course_discovery/apps/course_metadata/utils.py
> +def get_course_run_estimated_hours(course_run):
I assume this logic is pulled from some place else - is there any chance we can consolidate it or, if not, at least link to it. Just thinking if we ever want to update the algorithm we'd want to make sure we do so once (or at least in all of the places)

2019-05-17 07:58 UTC, hasnain-naveed commented on course_discovery/apps/course_metadata/utils.py
> +def get_course_run_estimated_hours(course_run):
This logic is in [story](https://openedx.atlassian.net/browse/WL-1936) description. I have asked a question on [ENT-1598](https://openedx.atlassian.net/browse/ENT-1598) about this whether we need estimated hours or all three fields (min_effort, max_effort, and weeks_to_complete).
@georgebabey

2019-05-23 12:40 UTC, georgebabey approved these changes

2019-05-24 09:45 UTC, merged