Move course_discovery defaults from configration repo
openedx/course-discovery pull request #1924
Opened 2019-05-29 12:20 UTC by syedimranhassan

2019-05-29 18:18 UTC, coryleeio requested changes

2019-05-29 18:18 UTC, coryleeio commented on course_discovery/settings/base.py
> +discovery_service_config_overrides = {
The values under discovery_service_config_overrides are the only ones that get injected to the application environment. aka discovery.yml

the intent of this ticket is that the 
values that are in discovery.yml have their default values set in the application, not in ansible.

I think you would want to only keep the contents of the 
discovery_service_config_overrides

section as top level keys

For example say that DISCOVERY_EMAIL_USE_TLS is set to true.

instead of 
discovery_service_config_overrides = {
   EMAIL_USE_TLS: DISCOVERY_EMAIL_USE_TLS
...
}

you would just put:
EMAIL_USE_TLS: true

We are trying to kill the 'config prefixing'

so there shouldn't be any DISCOVERY_MY_VAR type variables, only MY_VAR

(The values that get read in from the yml AFTER the discovery.yml gets rendered)

2019-05-29 18:22 UTC, coryleeio commented on course_discovery/settings/base.py
> +discovery_service_config_overrides = {
You will also want to de-dupe those top level variables

2019-05-30 12:42 UTC, syedimranhassan commented on course_discovery/settings/base.py
> +discovery_service_config_overrides = {
Hi,
Thanks @corylee. I have set default values of variables in base.py that are in discovery.yml using default.yml. But there are some variable in discovery.yml that are not in default.yml or base.py. I think they are coming from internal or secure. So, should they also be moved to base.py?

2019-05-30 14:00 UTC, coryleeio commented on course_discovery/settings/base.py
> +discovery_service_config_overrides = {
No, just the defaults - the idea is that we are going to remove the defaults from configuration soon, so we want to copy them into the application repo so that developers can own the defaults for their application.

Ideally this PR does not change the behavior of the application, even for upstream users, so we don't want to set any defaults that are not already set.

2019-05-30 20:05 UTC, coryleeio commented on course_discovery/settings/base.py
> +DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
This value was under 
DISCOVERY_MEDIA_STORAGE_BACKEND

which eventually (if you trace it through edx_django_service and the like resolves to:
MEDIA_STORAGE_BACKEND

which already has a default of {}, so I think this can be deleted


I dont see it being used anywhere

2019-05-30 20:09 UTC, coryleeio requested changes

2019-05-30 20:09 UTC, coryleeio commented on course_discovery/settings/base.py
> +SOCIAL_AUTH_REDIRECT_IS_HTTPS = False
I think what you did here is correct, we need to get all the values from under 

edx_django_service_config_default
LANGUAGE_CODE
SECRET_KEY
TIME_ZONE
STATIC_ROOT
etc


and default them to whatever they are currently defaulted too for discovery

2019-06-06 18:16 UTC, coryleeio commented on course_discovery/settings/base.py
> +SOCIAL_AUTH_REDIRECT_IS_HTTPS = False
You need to include all these values as well:
https://github.com/edx/configuration/blob/master/playbooks/roles/edx_django_service/defaults/main.yml#L182-L222

as they get merged into the edx_django_service_config here:
https://github.com/edx/configuration/blob/master/playbooks/roles/edx_django_service/defaults/main.yml#L226

2019-06-10 17:08 UTC, coryleeio requested changes

2019-06-10 17:08 UTC, coryleeio commented on course_discovery/settings/base.py
> +STATIC_ROOT = "/edx/app/NOT-SET/staticfiles"
Two more little things:

Why was the STATIC_ROOT changed?
Can you move MEDIA_STORAGE_BACKEND into here and remove the comment above it so that all the defaults live here that used to live in configuration.

2019-06-11 12:32 UTC, syedimranhassan commented on course_discovery/settings/base.py
> +SOCIAL_AUTH_REDIRECT_IS_HTTPS = False
I have added all these varaiables and also I have moved databases to local.py and copy caches from local.py to base.py

2019-06-11 17:17 UTC, coryleeio requested changes
2 more changes - then I think this is ready to go.

2019-06-11 17:17 UTC, coryleeio commented on course_discovery/settings/base.py
> -# Set this value in the environment-specific files (e.g. local.py, production.py, test.py)
I want to have both the DATABASES entry and the CACHES to both bein base.py or both not be, i'd say put DATABASES back and add CACHES.

2019-06-11 17:17 UTC, coryleeio commented on course_discovery/settings/local.py
> +        'ENGINE': 'django.db.backends.',
I would revert this part, we dont want to change their local dev settings.

2019-06-12 18:53 UTC, coryleeio approved these changes
This looks good to me

2019-06-12 18:54 UTC, coryleeio commented
:shipit:

2019-06-13 11:22 UTC, merged