DISCO-983: Adding Seats to Discovery on Course Run creation and updat…
openedx/course-discovery pull request #1927
Opened 2019-05-30 19:54 UTC by Dillon-Dumesnil

…ing Seats on saves and publishes

2019-05-30 20:05 UTC, bbaker6225 commented on course_discovery/apps/api/v1/views/course_runs.py
> +import datetime
Do we need to use this library?

2019-06-03 15:53 UTC, jlajoie commented on .coveragerc
> +    *
This one seems aggressive?

2019-06-03 15:54 UTC, Dillon-Dumesnil commented on .coveragerc
> +    *
Oops. I add that in during testing so I don't have the coverage report taking up my whole console. Removed

2019-06-04 14:49 UTC, mikix commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.assertEqual(Seat.everything.filter(course_run=new_course_run).count(), 1)
This is redundant with a `get()` call, but is also harmless to have.

2019-06-04 14:49 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +            raise ValidationError(_('Seat mode [{}] is not valid.').format(mode))
nit: I generally prefer to have early exits like this on their own. So that you don't have to indent the main path. Like so:

```
         if mode not in Seat.SEAT_TYPES:
            raise ValidationError(_('Seat mode [{}] is not valid.').format(mode))

         <NORMIE CODE>
```

Also, might be worth moving this into a `create_seats` helper method, like you did for `update_seats`? Although actually, `update_seats` does an update_or_create... could you just reuse it somehow?

2019-06-04 14:49 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +            raise ValidationError(_('Seat mode [{}] is not valid.').format(mode))
Same error path / happy path comment.

2019-06-04 14:49 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +            self.update_seats(mode, price, course_run)
Do we want to do anything if the price & mode don't match current values, but we're already published? Current code looks like it will silently ignore that request, which might be misleading. Maybe it doesn't super matter, if the UI doesn't let us get in that situation.

2019-06-04 14:49 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +    currency = models.ForeignKey(Currency, default='USD')
Whoa, you can specify a default primary key lookup like that? Makes sense, but neat. I guess we don't usually have non-ID primary keys.

2019-06-04 14:49 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +            set_official_state(seat, Seat, {'course_run': official_version})
It feels like you're taking advantage of a side effect here. The previous promise of this `ensure_official_version` is that it's a no-op if a draft exists. That's no longer true. You're using a `please make sure the DB is sane by migrating old data` check to become a `also move data over from draft`

HOWEVER - is our code broken right now? Do we only copy data over the first time we become reviewed? It likes we only ever call `ensure_official_version` to do the copy... Hmph. I think someone looked at the `ensure_draft_version` which *was* a `make the DB sane for migration purposes` check and assumed that `ensure_official_version` would be same vibe. But it's not, it's should just have a `always copy draft to official` vibe.

We should... fix that, yeah? Don't know if it makes sense in your PR or not. But looks like we want to take your blurred line and just destroy the line...

2019-06-05 13:30 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/course_runs.py
> +            self.update_seats(mode, price, course_run)
I was thinking no because right now, we send a patch request for every course run on every save and we don't want to update the Seat prices because of a change in the entitlement (which is where we are currently getting our mode/price from).

I wrote this code thinking that once a course run is published, we shouldn't really be changing the Seat prices for it, but we can still leave the ability to change the entitlement cost and have that apply to future runs without changing the older ones.

2019-06-05 15:12 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/course_runs.py
> +            self.update_seats(mode, price, course_run)
@transaction.atomic
    def _update_seats_from_entitlement(self, course, entitlement, changed_by):
        for run in self._get_active_course_runs(course):
            run.seats.all().delete()
            seat = Seat(
                type=CourseEntitlement.MODE_TO_SEAT_TYPE_MAPPING[entitlement.mode],
                price=entitlement.price,
                currency=entitlement.currency
            )

            # Use the SeatForm here to not duplicate logic for creating seats
            seat_form = SeatForm(instance=seat)
            seat_form.save(commit=True, course_run=run, changed_by=changed_by)

2019-06-05 15:13 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/course_runs.py
> +            self.update_seats(mode, price, course_run)
Based on this function in current publisher, we should continue to update seats even after publishing. I will update.

2019-06-05 15:14 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/models.py
> +    currency = models.ForeignKey(Currency, default='USD')
Pretty cool stuff :sunglasses:

2019-06-07 14:30 UTC, mikix reviewed
Looks good overall! Thanks for taking on the expanded update_official work!

2019-06-07 14:30 UTC, mikix commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        new_key = 'course-v1:{}+1T2000'.format(course.key.replace('/', '+'))
Ugh, I hate this stuff. I kinda wish we just fixed our factories to generate new style formats and added a test somewhere that we still handle old. But that's never something I want to take on when I'm doing something else. And this is not me asking you to, I'm just griping.

2019-06-07 14:30 UTC, mikix commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.assertEqual(Seat.everything.filter(course_run=new_course_run).count(), 2)
Super-nit: You could probably drop the course_run= bit, since these are only seats in database (here and in other tests).

2019-06-07 14:30 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +            raise ValidationError(_('Seat mode [{}] is not valid.').format(mode))
Do we have validation somewhere around a negative price? I feel like we did for entitlements, but maybe not seats. Not a high priority, but this made me think of that.

2019-06-07 14:30 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +            Seat.everything.filter(draft=True, course_run=course_run, type='professional').delete()
This might be more futureproof as `.exclude(mode).exclude(audit)` - should also probably be:

```
if mode in Seat.REQUIRES_AUDIT_SEAT:
 ...
else:
 ...
```

Rather than so explicit about naming the types and leaving a hanging elif without an else.

2019-06-07 14:30 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +            Seat.everything.filter(draft=True, course_run=course_run).exclude(type=mode).delete()
Note to self - do we handle the draft->official well for mode changes?

2019-06-07 14:30 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +            deadline = deadline.replace(hour=23, minute=59, second=59, microsecond=99999)
Can we just compare < rather than <= and avoid this trick? Or is that comparison buried in ecommerce logic?

2019-06-07 14:30 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +        if mode or price:
This is a little tricky. Price can be validly falsy at 0.00. Plus, the `or` isn't quite right with the pops above. Like, if I PATCH mode='verified' but don't pass in price, you'll reset my price on me, even though I didn't ask for that to be patched.

Is this better?
```
        update_seats = 'mode' in request.data or 'price' in request.data
        mode = request.data.pop('mode', course_run.mode)
        price = request.data.pop('price', course_run.price)
        if update_seats:
```

2019-06-07 14:30 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +            return official_version
You already commented on and had a plan for the duplication of code in this function. Just mentioning it here for recordkeeping.

2019-06-07 14:30 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +                    set_official_state(entitlement, CourseEntitlement, {'course': official_version})
What about existing official entitlements with a different mode? I guess we should modify/delete those? Same Q for seats.

2019-06-07 15:19 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/course_runs.py
> +            raise ValidationError(_('Seat mode [{}] is not valid.').format(mode))
Will write a ticket so this PR doesn't go crazy

2019-06-07 18:13 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/course_runs.py
> +            deadline = deadline.replace(hour=23, minute=59, second=59, microsecond=99999)
This was copied over from the Publisher Seat model and I'm not sure where the comparison is actually happening. I agree about the code smell, but without having the time to invest in looking where it's used, I'm just going to leave it for now.

2019-06-07 20:52 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/course_runs.py
> +            Seat.everything.filter(draft=True, course_run=course_run).exclude(type=mode).delete()
I have added in code for raising a ValidationError on non allowed mode changes to both Seats and Entitlements. Essentially this covers changing from anything but audit -> verified after creation of products.

2019-06-10 20:00 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +            creating = True
`creating  = not draft_version.official_version`

2019-06-10 20:01 UTC, bbaker6225 commented on course_discovery/apps/course_metadata/models.py
> +            creating = True
🔥

2019-06-10 20:07 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +            )
We talked about this in person, but for reference: we should un-indent this block or move it out or something.

2019-06-10 20:08 UTC, mikix commented on course_discovery/apps/api/v1/views/courses.py
> +                                    'out to your coordinator for additional help if necessary.'))
"project coordinator"

2019-06-10 20:28 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +            creating = True
`creating = not draft_version.official_version` again

2019-06-11 13:16 UTC, mikix approved these changes
I think all my comments have been addressed. Thanks so much for working through the twists and turns of this PR!

2019-06-12 13:25 UTC, staubina requested changes
The first pass is done.  I need to a deeper look at the logic to review any further, let me know if you think that is necessary with all the reviews you are getting.

2019-06-12 13:25 UTC, staubina commented on course_discovery/apps/api/v1/views/course_runs.py
> +            Seat.everything.filter(draft=True, course_run=course_run)\
nit: Please avoid using the \ for new lines.

PEP8 https://www.python.org/dev/peps/pep-0008/#maximum-line-length recommends using the \ only when there is no other option.

2019-06-12 13:25 UTC, staubina commented on course_discovery/apps/api/v1/views/course_runs.py
> +            Seat.everything.filter(draft=True, course_run=course_run).exclude(type=mode).delete()
What is the goal of the deletes?

It looks like it is clean up for when the mode changes, am I interpreting it correctly?

2019-06-12 13:25 UTC, staubina commented on course_discovery/apps/api/v1/views/courses.py
> +        if course.official_version and entitlement.mode != mode and \
Same as above, use a parenthesis here not a slash please. (PEP-8)

2019-06-12 13:25 UTC, staubina commented on course_discovery/apps/api/v1/views/courses.py
> +        mode_switch_whitelist = {'audit': 'verified'}
I recommend using the constants here for AUDIT and VERIFIED

2019-06-12 13:25 UTC, staubina commented on course_discovery/apps/api/v1/views/courses.py
> +                CourseRunViewSet().update_or_create_seats(course_run)
I feel like the right home for` update_or_create_seats()` might be in the model or in a utility file, not as part of the View code.  I am going to look closer at the method though.

2019-06-12 13:25 UTC, staubina commented on course_discovery/apps/api/v1/views/course_runs.py
> +    def update_or_create_seats(self, course_run):
I think a Docstring might be useful for this method as you seem to be adding comments where you use it a lot.  You could condense those comments into a clear, concise method docstring.

2019-06-12 13:25 UTC, staubina commented on course_discovery/apps/api/v1/views/course_runs.py
> +    def update_or_create_seats(self, course_run):
Also, I believe this method might be better housed in the model.  All of the action in this method seemed to be Database related.  Is there another reason to housed it in the ViewSet code?

2019-06-12 14:34 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/course_runs.py
> +            Seat.everything.filter(draft=True, course_run=course_run).exclude(type=mode).delete()
Yeah, basically. Just want to make sure we are only keeping track of the Seats that should exist. Like Professional and Audit should both exist alone and Verified has both so if you're switching from Professional to Audit or Verified, we just need to delete the professional seat for you.

2019-06-12 15:52 UTC, staubina approved these changes

2019-06-12 18:00 UTC, merged