Add a command to publish runs once live date hits
openedx/course-discovery pull request #1959
Opened 2019-06-17 17:55 UTC by mikix

A new management command publish_live_course_runs has now been added.
Any course runs which are reviewed and whose dates have passed are
now able to be published by running this command.

DISCO-815

2019-06-20 18:54 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +    def save(self, suppress_publication=False, **kwargs):
I refactored `save()` a bit here, but it wasn't really necessary for my work. Just saw an opportunity. I moved the marketing site stuff to its own method. I think it's a bit more readable now.

2019-06-20 18:54 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +        is_published = self.status == CourseRunStatus.Published
A test in travis started failing on ChoiceItem not having a lower method?...  Not sure why I triggered that. But this code wasn't great anyway. That caution around case is not done anywhere else (and our DB has only lowercase...). So I just figured I'd clean it up.

2019-06-21 12:45 UTC, staubina requested changes
I am curious why we did not just filter rather than going through all course runs. 

Also, are we applying the redirects here too?  I might just be missing the method that we apply the redirects in.

2019-06-21 12:45 UTC, staubina commented on course_discovery/apps/course_metadata/management/commands/publish_live_course_runs.py
> +        for course_run in CourseRun.objects.all():
Why don't we filter the Course run by datetime rather than looking at every course run?

2019-06-21 12:45 UTC, staubina commented on course_discovery/apps/course_metadata/management/commands/publish_live_course_runs.py
> +        for course_run in CourseRun.objects.all():
We should be able to use the ORMs filter query to greatly reduce the set of course runs which should by default be faster than looping through all course runs.

2019-06-21 12:45 UTC, staubina commented on course_discovery/apps/course_metadata/management/commands/publish_live_course_runs.py
> +            except Exception:  # pylint: disable=broad-except
nit: I am still not a fan of Bare exceptions. Any chance we can be more specific here?

2019-06-21 12:46 UTC, staubina commented on course_discovery/apps/course_metadata/management/commands/publish_live_course_runs.py
> +        for course_run in CourseRun.objects.all():
These two checks seem like the ones that could easily be made into a filter 
```
            reviewed = course_run.status == CourseRunStatus.Reviewed
            past_due = course_run.go_live_date and course_run.go_live_date <= now
```

2019-06-21 12:48 UTC, mikix commented on course_discovery/apps/course_metadata/management/commands/publish_live_course_runs.py
> +        for course_run in CourseRun.objects.all():
Yeah, you're right. I just brain farted on that.

2019-06-21 12:51 UTC, mikix commented
> Also, are we applying the redirects here too?

No. That was taken out of this ticket and moved to https://openedx.atlassian.net/browse/DISCO-898 (which asks for a redirect cron and to update this management command to include redirects).

2019-06-21 12:56 UTC, mikix commented on course_discovery/apps/course_metadata/management/commands/publish_live_course_runs.py
> +            except Exception:  # pylint: disable=broad-except
Minor nitpick - "bare" exceptions and "broad" exceptions are different. "Bare" is without the word "Exception" in there, and I agree. Those are 99% of the time a bad idea.

But I'd push back on broad exceptions being always bad. I believe they are useful in situations like this where you are treating a code block like a black box and don't care why something fails. You just want to ensure that any failure doesn't stop the loop.

Like... even if we had a list of all possible errors that could be raised, what would be the deciding factor between continuing the loop and stopping it? I guess an error that would suggest the rest of the publish attempts would fail anyway, so why bother. But I'm not sure what those are.

2019-06-21 13:04 UTC, mikix commented on course_discovery/apps/course_metadata/management/commands/publish_live_course_runs.py
> +            except Exception:  # pylint: disable=broad-except
I guess a common complaint of broad exceptions is also that it makes it hard to debug, because they hide errors. Which is fair if the code is trying to "handle" an error silently. But for cases where you catch-and-log, it seems a little less bad to me.

2019-06-21 13:05 UTC, mikix commented on course_discovery/apps/course_metadata/management/commands/publish_live_course_runs.py
> +        for course_run in CourseRun.objects.all():
Fixed. Thank you!

2019-06-21 13:30 UTC, staubina commented on course_discovery/apps/course_metadata/management/commands/publish_live_course_runs.py
> +        course_runs = CourseRun.objects.filter(status=CourseRunStatus.Reviewed, go_live_date__lte=now)
👍

2019-06-21 13:57 UTC, staubina commented on course_discovery/apps/course_metadata/management/commands/publish_live_course_runs.py
> +            except Exception:  # pylint: disable=broad-except
I think my distaste comes from what you mentioned.  Catch and log seems reasonable.

2019-06-21 14:02 UTC, staubina approved these changes

2019-06-21 14:03 UTC, merged