Update upgrade deadline in publisher seats
openedx/course-discovery pull request #1993
Opened 2019-07-03 10:59 UTC by uzairr

Currently, update in deadline date in course metadata seats has no
effect on the seats in publisher.To make the publisher seats coherent
with the course metadata save method is overriden which will update
the deadline date in publisher seats.

PROD-423

2019-07-08 08:18 UTC, waheedahmed requested changes
Also add some tests.

2019-07-08 08:18 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +                seat.upgrade_deadline = self.upgrade_deadline
What if `self.upgrade_deadline` is `None` or someone is changing something else is seat object, we shouldn't make these DB calls if not needed.

Add a check after super call if upgrade_deadline is changed then do the rest.

2019-07-08 08:19 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +                seat.upgrade_deadline = self.upgrade_deadline
Also, is this required on other seat types as well e.g. credit, no-id-professional etc?

2019-07-08 11:26 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +        if self.upgrade_deadline:
Is there any way to somehow check here if the value is changed for `upgrade_deadline`, because this check will always gets `True` if `upgrade_deadline` is not `NULL`.

2019-07-10 14:12 UTC, waheedahmed requested changes

2019-07-10 14:12 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +            old_seat = Seat.objects.get(id=self.id)
I believe you can do following to identify if the value is changed or not instead of querying again:
```
def __init__(self, *args, **kwargs):
    super(Seat, self).__init__(*args, **kwargs)
    self.__original_upgrade_deadline = self. upgrade_deadline
```

2019-07-10 14:12 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +        if self.upgrade_deadline and self.upgrade_deadline != old_seat.upgrade_deadline:
And do this here:
```
if self.upgrade_deadline and self.upgrade_deadline != self.__original_upgrade_deadline:

2019-07-10 14:12 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +                seat = run.seats.get(type=self.type)
What if somehow there is no seat object for this in publisher? Do we need try except here?

2019-07-12 09:55 UTC, waheedahmed approved these changes
Couple of questions, 👍 once addressed.

Also get it reviewed by someone from discovery-squad as well.

2019-07-12 09:55 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +                return
Shouldn't we log some kind of warning message here for debuging?

2019-07-12 09:55 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +                return
Also why we need return statement here?

2019-07-15 08:46 UTC, uzairr commented on course_discovery/apps/course_metadata/models.py
> +                return
Thanks for pointing out! I added a warning log message instead of returning.

2019-07-16 17:33 UTC, mikix reviewed
This is not usually the direction in which we sync data. We're trying to build up publisher wherever we find instances like this of people needing to manually tweak data in django admin or whatever. We're trying to make the line be "make any course edits in publisher directly".

My preference would be to add an upgrade_deadline UI field if we need it, to publisher. But I understand if we don't want to invest in that.

Is the problem because someone's runbook for updating upgrade deadlines is to manually tweak the course in django admin? We probably need to update it to also mention the draft rows that new publisher creates in the Course Metadata tables too...

2019-07-16 17:33 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +        super(Seat, self).__init__(*args, **kwargs)
extremely minor nit, but Disco is py3 only, so you can just do `super().__init__(*args, **kwargs)` (no need for `Seat, self`). Same comment below in `save`.

2019-07-16 17:33 UTC, mikix commented on course_discovery/apps/course_metadata/tests/test_models.py
> +            Seat as PublisherSeat, Course as PublisherCourse
Circular import? The publisher model code ends up calling into test_models?

2019-07-16 17:33 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +    def save(self, *args, **kwargs):  # pylint: disable=arguments-differ
You can drop `*args` and then the `arguments-differ` exception. `save` takes no arguments.

2019-07-16 17:33 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +
You probably want to do `self.__original_upgrade_deadline = self.upgrade_deadline at the bottom of this `if`. And maybe just call it `_old_upgrade_deadline` since you just care about the most recent value, not the original one. (And one underscore instead of two - one is for private stuff, two is for python stuff).

2019-07-16 17:33 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +                logger.warning(
`logger.exception` would cause the stacktrace to be printed, which is usually helpful for figuring out where in the code a message is coming from / why it's happening.

But more importantly, why is it an error if the publisher model doesn't exist? The seat could be from before publisher existed. The seat could be from the new publisher frontend, which doesn't keep its data in the old publisher models. I think you should just silently ignore it if no publisher model exists for this seat/run.

2019-07-16 17:33 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +                    'An Error occurred while updating upgrade deadline in publisher\'s seat: {}'.format(str(exc))
I myself prefer to also translate error messages, although I know our code base is inconsistent in that regard.

2019-07-16 17:39 UTC, mikix commented
Oh I see from the ticket - not really a runbook issue per se, but an RCM import issue. We'll still need to do something there for new-publisher. Like update draft row too if the seat changes. This code might make more sense outside of the `save` method and more in the ecom RCM code as a special case for that flow especially. Easier to reason about and safer to avoid updating both publishers when we shouldn't.

2019-07-16 17:40 UTC, mikix commented
Though I still stand by "we should just add this to publisher"

2019-07-22 20:42 UTC, jmyatt commented
+1 for moving this from `save` to the ecom RCM code

2019-07-31 16:21 UTC, jmyatt commented
let's hold off on this PR for now until we hear back on the latest questions in [the ticket](https://openedx.atlassian.net/browse/PROD-423)

2019-08-07 07:40 UTC, closed without merging