Add presave hooks to enforce external_key uniqueness
openedx/course-discovery pull request #2053
Opened 2019-07-26 16:11 UTC by jansenk

Add pre_save hooks to CourseRun, CurriculumCourseMembership, and Curriculum
to make sure that no two CourseRuns that have been 'linked' together within
a Course, Curriculum, or Program have the same external course key

2019-07-26 16:13 UTC, jansenk commented on course_discovery/apps/course_metadata/signals.py
> +def check_curriculum(curriculum, course_run_map, checked_courses):
probably rename this

2019-07-26 16:14 UTC, jansenk commented on course_discovery/apps/course_metadata/signals.py
> +def check_curriculum_for_duplicate_external_key(curriculum, course_run_map, checked_courses):
add comment

2019-07-26 18:27 UTC, kdmccormick reviewed
Looks pretty comprehensive -- good stuff.

Still figuring out exactly how, but I think there are some places that you could remove code and save database time, while keeping the output of your algorithm the same.

2019-07-26 18:27 UTC, kdmccormick commented on course_discovery/apps/course_metadata/signals.py
> +        - external_key_map: dict mapping external course keys to their course runs.
Update docstring params

2019-07-26 18:27 UTC, kdmccormick commented on course_discovery/apps/course_metadata/signals.py
> +        - external_key_map: dict mapping external course keys to their course runs.
Docstring params

2019-07-26 18:31 UTC, jansenk commented
> Looks pretty comprehensive -- good stuff.
> 
> Still figuring out exactly how, but I think there are some places that you could remove code and save database time, while keeping the output of your algorithm the same.

I agree. I'm still poking at it but i'm sure there's a way to optimize further

2019-07-26 19:26 UTC, kdmccormick requested changes

2019-07-26 19:26 UTC, kdmccormick commented on course_discovery/apps/course_metadata/signals.py
> +        for curriculum in curricula.all():
Imagine the course run is in both curricula X and Y, which are both part of program P.
This will:
* check_curricula(X):
    * check_program_for_dupes(P)
        * check_curriculum_for_dupes(X)
        * check_curriculum_for_dupes(Y)
* check_curricula(Y):
    * check_program_for_dupes(P)
        * check_curriculum_for_dupes(X)
        * check_curriculum_for_dupes(Y)

2019-07-26 19:26 UTC, kdmccormick commented on course_discovery/apps/course_metadata/tests/test_signals.py
> +        """
Love the ascii visuals

2019-07-26 19:26 UTC, kdmccormick commented on course_discovery/apps/course_metadata/tests/test_signals.py
> +    """
If these all test a specific thing and don't share data with the other tests, I recommend splitting them out in to their own test class.

2019-07-26 19:26 UTC, kdmccormick commented on course_discovery/apps/course_metadata/tests/test_signals.py
> +    @classmethod
The helpers that don't use `cls`/`self` could be `@staticmethod`s

2019-07-26 19:26 UTC, kdmccormick commented on course_discovery/apps/course_metadata/tests/test_signals.py
> +class ExternalCourseKeyTests(TestCase):
Great exhaustive testing :100:

2019-07-26 19:26 UTC, kdmccormick commented on course_discovery/apps/course_metadata/signals.py
> +    course_run_map = {
The "make a map from ext keys to course runs" logic is duplicated across the three signal handlers; could you just pass in a list of course runs and have `check_curriculum` build the map?

2019-07-26 19:28 UTC, Zacharis278 commented on course_discovery/apps/course_metadata/signals.py
> +    for course_run in course.course_runs.all():
if you're looking for optimizations might I suggest querying course runs filtered by external keys in the map to start instead of calling .all() and looping in python.

I think you could actually expand this approach all the way up the stack via a giant join so you're only ever checking curricula, courses, course_runs that are a potential conflict.

2019-07-26 19:47 UTC, Zacharis278 commented
What does the querycount look like on this as you add more curricula/courses.  I'm thinking this is going to run into n+1 problems at first glance

2019-07-26 19:54 UTC, kdmccormick commented
@Zacharis278 I agree with the n+1 concern, but I think starting with the course run with matching external keys and then "looking up" the tree would also be difficult, specifically when you have many course runs in question.

I think you can leverage the Django ORM like Dave was showing in all-hands this morning to do it efficiently top-down, something like:

```python

def check_program(program):

    # Grab all run/key pairs at once with three big queries
    curriculum_ids = program.curricula.values_list('id')
    course_ids = CurriculumCourseMembership.objects.filter(curriculum_id__in=curriculum_ids).values_list('course_id')
    run_pairs = CourseRun.objects.filter(course_id__in=course_ids).values_list('external_key', 'id')
    run_ids_by_ext_key = {}

    # Check for conflicts
    for ext_key, run_id in run_pairs:
        if not ext_key:
            continue
        existing_run_id = run_ids_by_ext_key.get(ext_key)
        if not existing_run_id:
            print('{} refers to {}'.format(ext_key, run_id))
            run_ids_by_ext_key[ext_key] = run_id
        elif existing_run_id != run_id:
            print('error: {} refers to both {} and {}'.format(ext_key, existing_run_id, run_id))
```

2019-07-29 15:59 UTC, schenedx reviewed
Besides the two naming suggestion, I don't have any more feedback in addition to what you already got. Don't be afraid to name functions with a lot of words.

2019-07-29 15:59 UTC, schenedx commented on course_discovery/apps/course_metadata/signals.py
> +def save_course_run(sender, instance, **kwargs):  # pylint: disable=unused-argument
Rather than name the function this way, I prefer name the function as summary of what it does. Maybe `ensure_external_key_uniqueness`?

2019-07-29 15:59 UTC, schenedx commented on course_discovery/apps/course_metadata/signals.py
> +def save_curriculum(sender, instance, **kwargs):  # pylint: disable=unused-argument
Again, it's best to rename it to tell next developer what this function does. I suggest `ensure_external_key_uniqueness_across_curriculum`

2019-08-01 17:40 UTC, kdmccormick approved these changes
Looks great! One small nit.

2019-08-01 17:40 UTC, kdmccormick commented on course_discovery/apps/course_metadata/signals.py
> +    course_run = CourseRun.objects.filter(
Nice :ok_hand:

2019-08-01 17:40 UTC, kdmccormick commented on course_discovery/apps/course_metadata/signals.py
> +        raise ValidationError(message)
Consider putting *all* the offending course runs in the message. Might make it easier to fix an issue like someone accidentally linking the wrong curriculum and creating dozens of conflicts.

2019-08-08 14:15 UTC, mikix approved these changes
I don't have enough context on curricula and external_key to be super useful here. One small code comment below and one approach comment here:

This is adding a lot of complexity and at minimum, one extra lookup on every CourseRun save, which is a frequent thing. Could we not just ignore uniqueness on `save` but check it on access? Like, if a partner is hitting our API with their own external key, do a `get(external_key=incoming_key)`, catch the MoreThanOne exception, and present a very clear error like "You set the same external key for these runs, go fix it"?

If that was discussed and discarded, I trust ya. But just sanity checking.

2019-08-08 14:15 UTC, mikix commented on course_discovery/apps/course_metadata/signals.py
> +        old_course_run = CourseRun.everything.get(pk=instance.id)
Minor nit, but these lines should be consistent - either check for and pass in `instance.pk` or assume `id` is the primary key and get `id=instance.id`. Otherwise, you're using the `pk` abstraction to no purpose. (using `pk` in both places is my vote)

The pk/id mixing is done elsewhere in this file.

2019-08-19 17:12 UTC, merged