Ndalfonso/disco 1188 internal workflow
openedx/course-discovery pull request #2065
Opened 2019-08-05 13:48 UTC by xnick421

2019-08-05 16:19 UTC, jlajoie requested changes

2019-08-05 16:19 UTC, jlajoie commented on course_discovery/apps/api/v1/views/course_runs.py
> +    INTERNAL_REVIEW_FIELDS = (
nit: Might be worth defining these fields as a constant on the model? Just worth thinking about, doesn't really matter

2019-08-05 16:19 UTC, jlajoie commented on course_discovery/apps/api/v1/views/course_runs.py
> +                    status=status.HTTP_403_FORBIDDEN
nit: I'd argue this is more of a 400 than a 403. It's just a bad request trying to do things the endpoint doesn't allow, not that your authorized user specifically is disallowed.

2019-08-05 16:19 UTC, jlajoie commented on course_discovery/apps/course_metadata/models.py
> +        ('', '--'),
This is for "not reviewed yet" right?

2019-08-05 16:19 UTC, jlajoie commented on course_discovery/apps/api/v1/views/course_runs.py
> +    @action(detail=True, methods=['patch'], permission_classes=[InternalUserPermission])
This feels pretty hard amounts of "not REST" to me, is there a reason we're not just using the default PATCH endpoint and overriding parts of it for these users?

2019-08-05 16:32 UTC, xnick421 commented on course_discovery/apps/api/v1/views/course_runs.py
> +                    status=status.HTTP_403_FORBIDDEN
could even be a 422, ill change to 400

2019-08-05 16:32 UTC, xnick421 commented on course_discovery/apps/course_metadata/models.py
> +        ('', '--'),
yep

2019-08-05 16:35 UTC, xnick421 commented on course_discovery/apps/api/v1/views/course_runs.py
> +    INTERNAL_REVIEW_FIELDS = (
ill move 'em over

2019-08-05 16:37 UTC, xnick421 commented on course_discovery/apps/api/v1/views/course_runs.py
> +    @action(detail=True, methods=['patch'], permission_classes=[InternalUserPermission])
i suggested it and agreed on it with dillon and jason.  just seemed like a well defined way of separating this type of update since its a little different than other updates.

2019-08-06 18:43 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +    ofac_comment = models.TextField(blank=True, help_text='Comment related to OFAC restriction')
This feels like such a process-oriented field on what is otherwise a definition-oriented model. The other fields are evergreen, while this one's content is tied to a moment in time. Plus, this comment field might be "temporary" until we move the country restriction list into Discovery and can just make that change directly from frontend.

Another option might be a separate model that is OneToOne with a CourseRun, to keep things cleaner? Lets you encode more metadata along with it too, and have room for expansion. Or just delete it wholesale once we no longer need `ofac_comment`.

Something like:
```
class LegalReview(TimestampedModel):
    course_run = OneToOneField...
    changed_by = Field...
    ofac_comment = Field...
```

But that is a big and subjective requested change. And is more about the design than just getting things done. If neither @jlajoie or @Dillon-Dumesnil agree, then forget it.

2019-08-06 18:43 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +        'reviewed',
These should use CourseRunStatus.Reviewed etc naming, rather than hardcoded strings.

2019-08-06 18:43 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +            request.data.pop('status', None)  # Status management is handled in the model
We popped these two above the serializater creation precisely because we didn't want them to be encoded in the serializer. Can we move them back up cleanly?

2019-08-06 18:43 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +        else:
Eh, why bother having an `else` here? You unconditionally returned above.

2019-08-06 18:43 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +            return Response(serializer.data)
You sounded like you felt this method was getting too complicated. Maybe instead of a big `if` in the middle of this method, you could do something like:

```
def handle_internal_review_change(...):
         if (request.user.is_staff and course_run.in_review and 'status' in request.data and
                request.data['status'] in CourseRun.INTERNAL_STATUS_TRANISTIONS):
            # Disallow updates on non internal review fields while course is in review
            for key in request.data.keys():
                if key not in CourseRun.INTERNAL_REVIEW_FIELDS:
                    return Response(
                        _('Can only update status, ofac restrictions, and ofac comment'),
                        status=status.HTTP_400_BAD_REQUEST
                    )

            serializer.save()
            return Response(serializer.data)

        # Disallow internal review fields when course run is not in review
        for key in request.data.keys():
            if key in CourseRun.INTERNAL_REVIEW_FIELDS:
                return Response(
                    _('Invalid param'),
                    status=status.HTTP_400_BAD_REQUEST
                )

     return None
```

Then in the main method:
```
    response = self.handle_internal_review_change(...)
    if response:
        return response
```

Or something? Or whatever you like, just an option to keep this tighter. I agree its branching logic is getting a bit much.

2019-08-06 18:43 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +    INTERNAL_STATUS_TRANISTIONS = (
Typo in transitions.

2019-08-06 19:04 UTC, xnick421 commented on course_discovery/apps/api/v1/views/course_runs.py
> +            return Response(serializer.data)
ill break it up

2019-08-06 19:12 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/course_runs.py
> +            return Response(serializer.data)
Also could have 
```
if (condition):
    return handle_internal_status(params)
```

2019-08-06 19:16 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/models.py
> +    INTERNAL_STATUS_TRANISTIONS = (
Also might make sense to move these status transitions into the CourseRunStatus model since that is what keeps track of all the statuses.

2019-08-06 19:17 UTC, mikix commented on course_discovery/apps/api/v1/views/course_runs.py
> +            return Response(serializer.data)
But ideally he could also stuff the check for `!condition -> don't allow certain fields too` in there to keep all the logic in one place.

2019-08-06 19:19 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/course_runs.py
> +            return Response(serializer.data)
Yeah, I don't care either way. Just giving another potential instead of asking for a response that may or may not be there.

2019-08-06 19:33 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/models.py
> +    ofac_comment = models.TextField(blank=True, help_text='Comment related to OFAC restriction')
From my understanding, I don't have strong feelings about this.

2019-08-06 21:16 UTC, merged