make url_slug unique
openedx/course-discovery pull request #2118
Opened 2019-08-26 22:09 UTC by rgraber

1. Make the url_slug unique (with draft status) in course metadata
2. Make url_slug unique in publisher
3. Add migrations to course metadata and publisher to backfill unique URL slugs for all existing courses, keeping course metadata and publisher in sync
4. Update error text for when slug is not unique

2019-08-29 18:13 UTC, mikix commented on course_discovery/apps/publisher/migrations/0080_populate_url_slug.py
> +    pass
I believe you can just neglect to pass a backward argument if you don't have anything to do.

2019-08-29 18:13 UTC, mikix commented on course_discovery/apps/publisher/migrations/0080_populate_url_slug.py
> +from course_discovery.apps.publisher.models import Course
This should be something like `Course = apps.get_model('publisher', 'course')` inside the forward method. See other migration files. This is done to avoid imports breaking as models go away over time but migration files stay the same.

2019-08-29 18:13 UTC, mikix commented on course_discovery/apps/publisher/migrations/0080_populate_url_slug.py
> +        course_metadata_course = instance.discovery_counterpart
This is an extra lookup per loop... Maybe that's fine, tables aren't huge.

I think it will also break once you do the suggestion above (`apps.get_model`) because the model class returned from that call is not the real model. It's some weird shim that Django provides. So it might not have `@property` methods like `discovery_counterpart`. I'm not sure if this whole paragraph is true or not.

2019-08-29 18:13 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +                             help_text=_('Leave this field blank to have the value generated automatically.'),)
Seems like a leftover edit?

2019-08-29 18:13 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +            ('url_slug', 'draft'),
Have you confirmed prod/stage don't have any dups?

2019-08-29 18:13 UTC, mikix commented on course_discovery/apps/course_metadata/migrations/0195_save_all_url_slugs.py
> +from course_discovery.apps.course_metadata.models import Course
Same import comment as other migration file.

2019-08-29 18:13 UTC, mikix commented on course_discovery/apps/course_metadata/migrations/0195_save_all_url_slugs.py
> +        instance.save()
Maybe a comment that you're doing this to set the slug.

2019-08-29 18:13 UTC, mikix commented on course_discovery/apps/api/v1/views/courses.py
> +                              'key \'course_metadata_course_url_slug_draft_4ddec6b0_uniq\''
That seems very brittle. Where is that hex coming from? What about Open edX users that might have different database backends? What about us in the future if we change backends?

You could maybe test if the slug already exists as a way of checking if that is why the IntegrityError happened? I dunno.

2019-08-29 18:27 UTC, rgraber commented on course_discovery/apps/course_metadata/models.py
> +            ('url_slug', 'draft'),
The full migration includes wiping out all existing url_slugs before doing the update since otherwise there's not really a great way to determine which ones get which version, and we weren't using them yet anyway.

2019-08-29 20:01 UTC, rgraber commented on course_discovery/apps/course_metadata/models.py
> +            ('url_slug', 'draft'),
But there isn't a wipeout migration on publisher I just realized, so I'll add that.

2019-09-04 13:55 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +            # need to handle this here because we can't make these queries inside an atomic block
Out of curiosity, why can't these checks be inside an atomic block?

Something like before saving, calling: 
```
if Course.everything.filter(url_slug=form_data['url_slug']).exists():
    raise ValidationError('The course URL slug [{slug}] is already in use. Please update this field and try again.'.format(slug=form_data['url_slug'])
```

2019-09-04 14:40 UTC, rgraber commented on course_discovery/apps/api/v1/views/courses.py
> +            # need to handle this here because we can't make these queries inside an atomic block
I kept getting "  "An error occurred in the current transaction. You can't "
TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block." Further research suggests there's a way around it but I don't know if this is enough of a potential problem to justify the time sink.

2019-09-04 15:31 UTC, rgraber commented on course_discovery/apps/api/v1/views/courses.py
> +            # need to handle this here because we can't make these queries inside an atomic block
Ah, I think the problem was I was originally trying to call it within an exception handler within the atomic transaction, which was not legal

2019-09-04 15:59 UTC, Dillon-Dumesnil requested changes
It's a good start, just a couple things to fix up and I had a few questions throughout.

Also don't forget to add tests for uniqueness within the view and course metadata. There is only the test right now for the publisher app

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +            # 1062 is the code for a uniqueness violation
I don't think this line is still needed after the changes you made from Mike Terry's comment earlier.

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/migrations/0193_remove_course_url_slug.py
> +class Migration(migrations.Migration):
In general with all of these migrations in this PR, they can all be put into a single migration and you can dictate the order by the order they show up in for the operations. I.e.
```
    operations = [
        migrations.RemoveField(
            model_name='course',
            name='url_slug',
        ),
        migrations.AddField(
            model_name='course',
            name='url_slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='Leave this field blank to have the value generated automatically.', populate_from='title'),
        ),
    ]

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/migrations/0193_remove_course_url_slug.py
> +        migrations.RemoveField(
Why are you removing this field just to re-add it again below? That adds a red flag in my mind.

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/migrations/0196_save_all_url_slugs.py
> +    for instance in Course.objects.all():
So I'm personally not a huge fan of needing to add in the `MigratableCourseDraftManager`. It has to do with `Course.objects` being a `DraftManager` and for whatever reason, that doesn't show up. I don't know, it's weird.

Anyway, I think there are two cleaner ways to handle this situation:
1) Just use the `everything` Manager since we know that works. So this line can just change to `for instance in Course.everything.filter(draft=False):`
2) Add `use_in_migrations` to the `DraftManager` class so that way `objects` works in Migrations for all of our models (it currently does for other models and is the reason `everything` already works)

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/models.py
> +            ('url_slug', 'draft'),
This should still have `'partner'`. The partner is like our different sites and we want to continue to enforce uniqueness between them

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/models.py
> +    objects = MigratableCourseDraftManager()
See above about MigratableCourseDraftManager

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/publisher/api/v1/tests/test_views.py
> +        publisher_course_run.save()
Is it necessary to save the course run here? Just curious if we can avoid another database write.

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/publisher/api/v1/tests/test_views.py
> +        discovery_matching_course = CourseFactory()
You can just switch this to `CourseFactory(draft=False, url_slug='duplicate')`

If url_slug is not in the CourseFactory, I'd probably just recommend adding it as a FuzzyText

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/publisher/migrations/0080_remove_course_url_slug.py
> +class Migration(migrations.Migration):
Same as above. You shouldn't need multiple migration files. Also want to know about the remove and add.

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/publisher/migrations/0082_populate_url_slug.py
> +        except:
Blanket `except` here is a kind of scary thing. Do we not care what might go wrong and we should continue the migration? Are there expected issues that we can specifically catch? Are there _any_ scenarios that this migration should fail?

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/managers.py
> +class MigratableCourseDraftManager(DraftManager.from_queryset(CourseQuerySet)):
See comment below (in one of the migration files) regarding this class.

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/publisher/migrations/0082_populate_url_slug.py
> +            discovery_course = DiscoveryCourse.objects.get(partner=partner, key=key)
Did `discovery_counterpart` not work? I feel like that would be the cleaner way if possible.

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/publisher/api/v1/tests/test_views.py
> +        publisher_course_run.save()
Same here about is this necessary

2019-09-04 15:59 UTC, Dillon-Dumesnil commented on course_discovery/apps/publisher/api/v1/tests/test_views.py
> +        publisher_course_run.course.url_slug = 'fixed'
I think this should be broken off into a second test. With the test name `test_publish_with_duplicate_url_slug`, this part feels misleading. Then you have one test for the success case and one for the fail case with the uniqueness being broken.

2019-09-04 16:21 UTC, rgraber commented on course_discovery/apps/course_metadata/migrations/0193_remove_course_url_slug.py
> +        migrations.RemoveField(
I needed to wipe all existing url_slugs because there was a chance they wouldn't be unique since it was originally added without that constraint

2019-09-04 16:30 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/migrations/0193_remove_course_url_slug.py
> +        migrations.RemoveField(
I would argue to wipe it as part of the function in the other migration then. Just null it to start and then do the save so it is automatically created. Removing and re-adding the same field feels hacky to get this result.

2019-09-04 17:03 UTC, rgraber commented on course_discovery/apps/publisher/migrations/0082_populate_url_slug.py
> +            discovery_course = DiscoveryCourse.objects.get(partner=partner, key=key)
No, discovery counterpart doesn't work because of the way models are created in migrations. It needs to be recreated by hand.

2019-09-04 18:11 UTC, rgraber commented on course_discovery/apps/course_metadata/migrations/0196_save_all_url_slugs.py
> +    for instance in Course.objects.all():
I'm ok with using the .everything, but FYI adding in use_in_migrations to the DraftManager class does not actually work (related to https://stackoverflow.com/questions/37764070/django-migrations-valueerror-could-not-find-manager-in-django-db-models-manager ).

2019-09-04 18:27 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/migrations/0196_save_all_url_slugs.py
> +    for instance in Course.objects.all():
Oh weird, I totally thought that would work. Weird. Oh well, I think the everything fix will be good for now.

2019-09-04 20:53 UTC, rgraber commented on course_discovery/apps/publisher/api/v1/tests/test_views.py
> +        discovery_matching_course = CourseFactory()
url_slug should be auto-generated on save from the title, so I don't think they need to be in the CourseFactory

2019-09-04 20:54 UTC, rgraber commented on course_discovery/apps/publisher/api/v1/tests/test_views.py
> +        publisher_course_run.course.url_slug = 'fixed'
Since there already is a test for a successful publish I just added checking the url_slug into that

2019-09-04 21:57 UTC, rgraber commented
> It's a good start, just a couple things to fix up and I had a few questions throughout.
> 
> Also don't forget to add tests for uniqueness within the view and course metadata. There is only the test right now for the publisher app

I'm not sure it's necessary to test the course_metadata uniqueness since that's entirely enforced via a django constraint, and it doesn't seem right to unit test specific error messaging

2019-09-05 17:53 UTC, Dillon-Dumesnil requested changes
It's looking good. One key thing to fix in the course_metadata migration, but otherwise pretty much there. Nice job

2019-09-05 17:53 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +        if Course.everything.filter(url_slug=course_creation_fields['url_slug'],
I think I would update this to
```
if course_creation_fields['url_slug'] and Course.everything.filter(
    url_slug=course_creation_fields['url_slug'], 
    partner_id=course_creation_fields['partner']
).exists():
```
This way you can early exit if `url_slug` was never defined and don't have to hit the database unless necessary

2019-09-05 17:53 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +                _('Course edit was unsuccessful. '
Since this is its own message, I think we should be more explicit here that `Course creation was unsuccessful.` rather than just saying edit.

Nit: Write each line as far as it will go rather than break on sentences. Might be able to reduce overall line count.

2019-09-05 17:53 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +                                        partner=course.partner).exclude(key=course.key):
Nit: I would recommend switching this to exclude based on `UUID` rather than `key`

2019-09-05 17:53 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +        if serializer.validated_data.get('url_slug'):
Combine these two ifs into an `if` with an `and`.
```
if serializer.validated_data.get('url_slug') and Course.everything.filter(
    url_slug=serializer.validated_data['url_slug'], partner=course.partner
).exclude(key=course.key):
```

2019-09-05 17:53 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +                    'The course URL slug ‘{}’ is already in use. '
Please line up any successive lines with the line above it. Like, having the beginning quote at the same indentation level.
```
    _('Course edit was unsuccessful. '
      'The course URL...
```

2019-09-05 17:53 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +                        'The course URL slug ‘{}’ is already in use. '
Same comment about indentation level

2019-09-05 17:53 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +                        'The course URL slug ‘{}’ is already in use. '
Same comment about wrapping with brackets and using format variable.

2019-09-05 17:53 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +                    'The course URL slug ‘{}’ is already in use. '
I think it is our convention to wrap user input in brackets to help indicate to transifex users that it doesn't need to be translated. So `{}` -> [{}]. I would also recommend adding in a format variable just for additional clarity. So having The course URL slug [{slug}]...).format(slug=serializer.validated_data['url_slug']) instead of just [{}]

2019-09-05 17:53 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/migrations/0194_initialize_course_url_slug.py
> +                # update corresponding draft instance
The remainder of this function needs to be wrapped in an `if instance.draft_version:` since not all official rows necessarily have draft versions.

2019-09-05 17:53 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/migrations/0194_initialize_course_url_slug.py
> +        updated_pks = []
Nit: Change this variable name to `updated_draft_pks` for clarity since only those pks are added to this list and not all pks that are updated.

2019-09-05 17:53 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/models.py
> +            ('partner', 'url_slug', 'draft'),
👍

2019-09-05 19:36 UTC, rgraber commented on course_discovery/apps/api/v1/views/courses.py
> +                    'The course URL slug ‘{}’ is already in use. '
I believe pycodestyle complains about that and calls it under-indented but I'll double check.

2019-09-05 19:50 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +                    'The course URL slug ‘{}’ is already in use. '
Oh weird. I could have sworn I've been yelled at in the past by pycode about that, but maybe things changed when we switched from pylint to pycode. I guess do whichever the linter is okay with and maybe it just accepts both. Sounds good. Thanks for checking!

2019-09-06 01:47 UTC, rgraber commented on course_discovery/apps/api/v1/views/courses.py
> +                    'The course URL slug ‘{}’ is already in use. '
Turns out I was accidentally lining the text up with the underscore instead of the other text which was why it was complaining.

2019-09-06 14:18 UTC, Dillon-Dumesnil approved these changes
Looks good! I had a small nit, but feel free to ignore

2019-09-06 14:18 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +                _('Course creation was unsuccessful. The course URL slug ‘[{url_slug}]’ is already in use. Please '
Nit: Remove the ticks and just use the brackets.

2019-09-06 14:18 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/views/courses.py
> +                _('Course edit was unsuccessful. The course URL slug ‘[{url_slug}]’ is already in use. '
Same nit here

2019-09-06 14:44 UTC, dianakhuang approved these changes
:shipit:

2019-09-06 14:46 UTC, merged