Ndalfonso/disco 1331 delete publisher enable read only fields
openedx/course-discovery pull request #2119
Opened 2019-08-27 11:24 UTC by xnick421

2019-08-27 13:24 UTC, mikix requested changes

2019-08-27 13:24 UTC, mikix commented on course_discovery/apps/course_metadata/data_loaders/api.py
>          pacing_type = self.get_pacing_type(body)
Since you're removing the second place these two variables are used, you could probably move them inline to their single use below now.

2019-08-27 13:24 UTC, mikix commented on course_discovery/apps/publisher/api/v1/tests/test_views.py
> -    def test_publish(self):  # pylint: disable=too-many-statements
You still want this test. This tests publishing to ecom, discovery, and studio. It's not just about that waffle flag. I think you just need to remove the switch override and fix whatever behavior breaks in the test because it's off.

2019-08-27 13:24 UTC, mikix commented on course_discovery/apps/publisher/models.py
>              https://openedx.atlassian.net/browse/EDUCATOR-3488.
Might want to fix up this docstring too - mention that this is old unused method. 

Or better yet, remove this method, now that we don't need it and fix up users of it. Same for other `_temporary` methods. But that all might be too much. Maybe better to just leave them as simple fall backs for now (with the comment on why) and we'll clean it up when decommissioning publisher.

2019-08-27 13:24 UTC, mikix commented on course_discovery/apps/publisher/models.py
> -            # Treat empty strings as NULL
You deleted this comment

2019-08-27 13:24 UTC, mikix commented on course_discovery/apps/publisher/tests/test_admin.py
> -    def test_update_course_form(self):
This test seems unrelated to the waffle feature? I think we still want it, just without the override.

2019-08-27 13:24 UTC, mikix commented on course_discovery/apps/publisher/tests/test_models.py
>      def test_pacing_type_temporary_without_switch(self):
Might rename to just `test_pacing_type_temporary` - same comment throughout this file.

2019-08-27 13:24 UTC, mikix commented on course_discovery/apps/publisher/tests/test_studio_api_utils.py
> -def test_generate_data_for_studio_api():
These two tests seem unrelated to the switch - I'd imagine we still want them, right?

2019-08-27 13:24 UTC, mikix commented on course_discovery/apps/publisher/tests/test_views.py
> -    def test_page_without_data(self):
I think we still want this.

2019-08-27 13:24 UTC, mikix commented on course_discovery/apps/publisher/tests/test_views.py
> -    def test_course_run_detail_page_staff(self):
We want this.

2019-08-27 13:24 UTC, mikix commented on course_discovery/apps/publisher/tests/test_views.py
> -    def test_detail_page_with_comments(self):
We want this.

2019-08-27 13:24 UTC, mikix commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> -    def test_course_run_without_start_date(self):
We want this - this test had the flag disabled - nothing should change for this test. Though you might want to clean up the docstring.

2019-08-27 13:28 UTC, xnick421 commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> -    def test_course_run_without_start_date(self):
there is a note in this test should be deleted

2019-08-27 14:00 UTC, mikix commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> -    def test_course_run_without_start_date(self):
Yeah, but remember that we are disabling this waffle flag in the `False` path. We no longer want the feature this waffle was designed to provide. And that note in the test was saying "once we remove this waffle flag as `True`, we don't need this test" - but we're removing it as `False` so test is still relevant.

2019-08-28 18:06 UTC, mikix commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +        be deleted, as there will be no way to have a course run without a start date in Publisher.
You don't need this comment anymore.

2019-08-28 18:07 UTC, mikix approved these changes

2019-08-28 20:55 UTC, merged