DISCO-1316 saleforce record updates
openedx/course-discovery pull request #2138
Opened 2019-09-04 18:12 UTC by xnick421

update course, course run, and organization in salesforce when they are update in the db, also push them to saleforce on creation

2019-09-04 19:31 UTC, jlajoie commented on course_discovery/apps/course_metadata/salesforce.py
> +
Just calling this out that once rebasing with prod some of this data may have changed, you'll just need to update to what's out there now

2019-09-04 20:15 UTC, jlajoie reviewed
Looks like a great start, good stuff pulling the object payloads into external methods. Just the one comment about keeping track of some of those changes that may have occurred in master, and also don't forget about this AC ```Changes should be applied only for Official rows as that is what our Go Live date will be based on, not proposed changes```. You'll just want to check that on the updates if there exists a draft field (course/course run) and it isn't a draft, that's the time you'll want to write those changes out to salesforce since we'll only want real "live" data to exist in SF.

2019-09-04 20:15 UTC, jlajoie commented on course_discovery/apps/course_metadata/signals.py
> +        return False
nit: Make this return None, you're evaluating for truthiness but in terms of type comparisons a null value makes more sense than either it's a boolean or it's a whole salesforce object

2019-09-10 17:35 UTC, Dillon-Dumesnil reviewed
We're getting there! Couple comments. Let me know if you have any questions.

2019-09-10 17:35 UTC, Dillon-Dumesnil commented on course_discovery/apps/api/v1/tests/test_views/test_comments.py
> +from django.db.models.signals import post_save
Nit: Add an empty line here to keep the separation in imports.

2019-09-10 17:35 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/salesforce.py
> +            organization = course.authoring_organizations.first()
I wonder if this should just be written into an `@property` on the Course model. Curious how many times it is used to determine the authoring org. Or maybe one day even turned into a many to one instead of m2m. Not something you need to change, I was just reflecting.

2019-09-10 17:35 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/signals.py
> +            util.create_publisher_organization(instance)
Probably not worth it, but I wonder if we could just change this all to an `update_or_create` and get rid of this whole if statement.

2019-09-10 17:35 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/signals.py
> +    partner = instance.course.partner
Not sure it's really necessary, but a helper function to handle this stuff could be useful and potentially cleaner. It just raises a bit of a flag in my mind seeing how similar these three functions are and I'm curious how you could abstract it. Potentially only the first three lines, but might be an improvement.
```
    partner = instance.partner
    util = _get_salesforce_util(partner)
    if util:
```
I'm not diehard on it. Just might be nice

2019-09-10 17:35 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/signals.py
> +def update_salesforce_organization(instance, created, **kwargs):  # pylint: disable=unused-argument
Not sure if the naming of these functions has to be specific, but I would prefer all three of these to be `update_or_create_salesforce_xxxxx` since it is technically doing either.

2019-09-10 17:35 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/signals.py
> +    Function to determine whether or not the post_save hook for Organization, Course,
I think this docstring should be rewritten and potentially not even exist here. This function is trying to return to you a SalesforceUtil. You're writing the docstring about what the return value is going to be used for _by you_ and not what the function is actually doing. On that point, that's why I think this might not even best live here and potentially live as a helper function next to the Util itself and this file would just import the helper. Something to think about.

2019-09-10 17:35 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/utils.py
> +    # If a course or course run is being saved, we refresh the instance from the db and set
I think this comment can be improved. Don't use the comment to explain what is happening in the code, that's obvious. Explain _why_ we need to do this. Mention the local object doesn't have salesforce_id so we have to refresh the db since it was saved there in a post_save hook. Give the why, not the what.

2019-09-10 17:35 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/tests/test_salesforce.py
> +        self.salesforce_path = 'course_discovery.apps.course_metadata.salesforce.Salesforce'
Nice job, I like these improvements.

2019-09-10 17:35 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/tests/test_salesforce.py
> +    def test_update_publisher_organization(self, salesforce_id):
Is it possible to check any data changing with these three functions instead of just that the function is called? Probably not, just thought I'd ask

2019-09-10 17:35 UTC, Dillon-Dumesnil commented on course_discovery/apps/course_metadata/tests/test_signals.py
> +
Maybe just also do a save here while the Course is still draft to illustrate that drafts do not call the update method.

2019-09-10 17:57 UTC, xnick421 commented on course_discovery/apps/course_metadata/tests/test_salesforce.py
> +    def test_update_publisher_organization(self, salesforce_id):
we would have to define the mock methods to return values

2019-09-11 15:19 UTC, jlajoie requested changes
Couple of nits, looks like a solid update and it looks like most of the headache was around what objects had the salesforce_id in memory that we operated on, vs where we had fetched and loaded course/course_runs into memory that were not operated upon in that salesforce object lifecycle. Makes sense!

2019-09-11 15:19 UTC, jlajoie commented on course_discovery/apps/course_metadata/salesforce.py
> +            if course.official_version and not course.official_version.salesforce_case_id:
This only ever runs against draft versions, correct?

2019-09-11 15:19 UTC, jlajoie commented on course_discovery/apps/course_metadata/salesforce.py
>              course.salesforce_id = sf_course.get('id')
Should we be trying to set the official version salesforce_id here as well?

2019-09-11 15:19 UTC, jlajoie commented on course_discovery/apps/course_metadata/salesforce.py
>              course_run.salesforce_id = sf_course_run.get('id')
Should we be trying to set the official version salesforce_id here as well? (for runs this time)

2019-09-11 15:19 UTC, jlajoie commented on course_discovery/apps/course_metadata/signals.py
> +    partner = instance.course.partner
They're definitely all similar, but the way we grab the partner from each model varies and the subsequent method calls seemed distinct enough that it feels cleaner to me to just keep them separate. It's like, 3 lines of boiler plate and they all live together so it shouldn't be missed.

2019-09-11 15:19 UTC, jlajoie commented on course_discovery/apps/course_metadata/utils.py
> +    # We refresh the objects instance before we set it's salesforce_id because the instance in memory is
tiniest nit: objects -> object's

2019-09-11 15:19 UTC, jlajoie commented on course_discovery/apps/course_metadata/utils.py
> +    # We refresh the objects instance before we set it's salesforce_id because the instance in memory is
double tiny nit: its is possessive, it's is a contraction of it is, "we set it is salesforce_id"

2019-09-11 15:19 UTC, jlajoie commented on course_discovery/apps/course_metadata/utils.py
> +        return None
👍

2019-09-11 15:19 UTC, jlajoie commented on course_discovery/apps/course_metadata/utils.py
> +        return None
nit: this method might be worth migrating to the get_util_or_404 method we have setup in the comments API? Just use this and instead of catching the exception in there just return the 404 if it's null? Don't care but seems like it could be worthwhile cleanup

2019-09-11 15:38 UTC, xnick421 commented on course_discovery/apps/course_metadata/salesforce.py
> +            if course.official_version and not course.official_version.salesforce_case_id:
yea, but it may not have an official version yet, which is why we check.  so this logic is for the case where an official version is made without any previous comments, which means both draft and official have no case_id.  then the next time a comment comes in, it creates the case, the draft gets the id, and we copy over the id in this if block

2019-09-11 15:39 UTC, xnick421 commented on course_discovery/apps/course_metadata/salesforce.py
>              course.salesforce_id = sf_course.get('id')
we do it in the set_draft_state util method.  we refresh the in memory instance there to reflect whats in the db.  we can talk more about this

2019-09-12 19:43 UTC, jlajoie requested changes
Just the one change, we'll need to handle the case of "hey things are okay this has the proper IDs set"

2019-09-12 19:43 UTC, jlajoie commented on course_discovery/apps/course_metadata/signals.py
> +            if not instance.salesforce_id:
I think you'll need the else i there is a salesforce_id to just do the update like normal

2019-09-12 19:43 UTC, jlajoie commented on course_discovery/apps/course_metadata/signals.py
> +            if not instance.salesforce_id:
Same here, if there is a salesforce_id just do the update

2019-09-13 13:30 UTC, jlajoie commented on course_discovery/apps/course_metadata/salesforce.py
> +        if instance.__class__.__name__ == 'Course':
Might be best to change this to an isinstance check so in case we refactor class names (probably won't ever happen) this code won't break?

2019-09-13 13:32 UTC, jlajoie commented on course_discovery/apps/course_metadata/salesforce.py
> +    instance.salesforce_id = instance.draft_version.salesforce_id
Might be worth even having an extra check that makes sure there is a draft_version.salesforce_id set? As it is now there are branches where you can start with no salesforce_id and can end up with no code being run other than ```instance.salesforce_id = instance.draft_version.salesforce_id```

2019-09-16 18:39 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +            self._cache.pop('_cache')
This wouldn't stop it from getting in. You're popping it from the cache var before you overwrite it. Maybe move this block down after setting _cache?

You probably want this logic in `save` too?

2019-09-17 13:10 UTC, jlajoie approved these changes
Just minor comments but looks good to go, tested locally as well

2019-09-17 13:10 UTC, jlajoie commented on course_discovery/apps/course_metadata/models.py
> +class CachedMixin:
Not even at the level of a nit, but I can't decide if Cached vs Cache is better,

2019-09-17 13:10 UTC, jlajoie commented on course_discovery/apps/course_metadata/salesforce.py
> +    name = instance.__class__.__name__
I think we talked about maybe swapping this to an instanceof check with a localized import, did that not work out? If it didn't that's cool just want to double check

2019-09-17 13:10 UTC, jlajoie commented on course_discovery/apps/course_metadata/salesforce.py
> +    name = instance.__class__.__name__
Same as above with instanceof check

2019-09-17 14:00 UTC, jlajoie commented on course_discovery/apps/course_metadata/salesforce.py
> +    'partner': ('publisher_url', 'domain'),
I think we can drop partner and organization here

2019-09-17 15:54 UTC, merged