Exclude ended/expired course runs from endpoint
openedx/course-discovery pull request #2211
Opened 2019-10-08 09:25 UTC by zamanafzal

This Pr code aimed to remove the Ended/Expired Course Runs from the Endpoint
`/api/v1/search/all/`

You can test this scenario by
1- Creating an Enterprise Customer
2- Creating an Enterprise Customer Catalog
3- Creating a course with Ended Course Runs and some Active course Runs.
4- Associate this Course with enterprise on Via E-COMMERCE COURSE ADMINISTRATION Panel.
5- Then run these two commands on discover shell
python manage.py refresh_course_metadata
python manage.py update_index --disable-change-limit
6- Please check on the endpoint mentioned above.
**PRE-PR Results:**
All course runs will be visible in results.
**POST-PR Results**:
Course runs which are expired will not be visible in results.

2019-10-08 10:00 UTC, muhammad-ammar requested changes
Looks great. Can we add another test with multiple courseruns, make some the courseruns expiry and then verify that expired courseruns are exlcluded but non-expired are returned.

2019-10-08 23:32 UTC, jmyatt commented
is this or #2203 the correct PR for this?

2019-10-09 07:42 UTC, muhammad-ammar approved these changes

2019-10-09 09:33 UTC, waheedahmed requested changes

2019-10-09 09:33 UTC, waheedahmed commented on course_discovery/apps/api/serializers.py
> +            for course_run in result.object.course_runs.exclude(end__lte=datetime.datetime.now(pytz.UTC))
I believe there are other consumers as well of this endpoint (e.g. marketing search) where we need archived runs. Maybe there is already a filter available which you can use to filter out the archived runs otherwise create one.

2019-10-10 13:52 UTC, zamanafzal commented on course_discovery/apps/api/serializers.py
> +            for course_run in result.object.course_runs.exclude(end__lte=datetime.datetime.now(pytz.UTC))
@waheedahmed I have updated the PR and steps (in PR description) to verify the change. Now course runs will be excluded on the basis of query param. Please take a look.

2019-10-10 14:11 UTC, waheedahmed commented on course_discovery/apps/api/serializers.py
> +        request = self.context['request']
Can following query serve the purpose instead of implementing new one?
https://discovery.edx.org/api/v1/search/all/?content_type=course&availability=Current&availability=Starting+Soon&availability=Upcoming

2019-10-18 05:11 UTC, muhammad-ammar requested changes

2019-10-18 05:11 UTC, muhammad-ammar commented on course_discovery/apps/api/serializers.py
> +            course_runs = [course_run for course_run in result.object.course_runs.all()]
I think we don't need to iterate queryset here. Below code should serve the purpose.

```python
course_runs = result.object.course_runs.all() 
if request.GET.get("exclude_expired_course_run"):
    course_runs = course_runs.exclude(end__lte=datetime.datetime.now(pytz.UTC))
```

2019-10-18 05:11 UTC, muhammad-ammar commented on course_discovery/apps/api/serializers.py
> +        exclude_expire_course_run = query_params.get("exclude_expire_course_run", None)
no need to create an extra variable,  we can do

```python
if request.GET.get("exclude_expired_course_run"):
```

also `dict.get` returns `None` as the default value so we don't need to.

2019-10-18 05:11 UTC, muhammad-ammar commented on course_discovery/apps/api/tests/test_serializers.py
> +    request = APIRequestFactory().get('/', query_param)
we should not add `query_param` in request if `query_param` is `None`.

2019-10-18 05:11 UTC, muhammad-ammar commented on course_discovery/apps/api/serializers.py
> +        exclude_expire_course_run = query_params.get("exclude_expire_course_run", None)
`exclude_expire_course_run` -> `exclude_expired_course_run`

2019-10-18 09:33 UTC, zamanafzal commented on course_discovery/apps/api/serializers.py
> +            course_runs = [course_run for course_run in result.object.course_runs.all()]
Yeah, there is no need to iterate it. I will remove it. After removal this shouldn't be like
`if request.GET.get("exclude_expired_course_run"):
    course_runs = result.object.course_runs.exclude(end__lte=datetime.datetime.now(pytz.UTC))
else:
course_runs = result.object.course_runs.all() 
`
in this case we will get the desired data only and no need to filter it again if we need to Exclude Expired Course Runs

2019-10-18 11:37 UTC, muhammad-ammar approved these changes
LGTM

2019-10-18 12:52 UTC, merged