BOM-1231
openedx/course-discovery pull request #2427
Opened 2020-02-13 15:29 UTC by UsamaSadiq

Updated social auth app django for Django2.0 support

2020-02-14 10:44 UTC, Ayub-Khan requested changes

2020-02-14 10:44 UTC, Ayub-Khan commented on requirements/github.in
> +-e git+https://github.com/python-social-auth/social-app-django.git@c00d23c2b45c3317bd35b15ad1b959338689cef8#egg=social-auth-app-django
Remove '-e'. No need.

2020-02-14 11:35 UTC, UsamaSadiq commented on requirements/github.in
> +-e git+https://github.com/python-social-auth/social-app-django.git@c00d23c2b45c3317bd35b15ad1b959338689cef8#egg=social-auth-app-django
Updated as per suggestion.

2020-02-14 13:30 UTC, mraarif approved these changes

2020-02-14 13:35 UTC, mraarif approved these changes

2020-02-14 13:58 UTC, jmbowman approved these changes

2020-02-14 14:15 UTC, Dillon-Dumesnil approved these changes
Do you think it would be helpful to create a ticket that we can check in on in sixth months or so to see if a release has happened? My only concern here is that we forget about this line of code and it just stays this way. Creating a ticket is not necessary and only intended as a potential help, but if we don't think it would be helpful, we do not need to pursue it.

2020-02-14 14:16 UTC, Dillon-Dumesnil commented
Also it looks like Ayub-Khan will either need to give an approval on this PR or that review needs to be dismissed before this can merge as it is currently blocking merging.

2020-02-17 10:04 UTC, Ayub-Khan approved these changes

2020-02-17 11:05 UTC, merged