Enterprise API: Include additional detail-level fields in Enterprise Catalog Courses List
openedx/course-discovery pull request #2571
Opened 2020-04-29 14:30 UTC by zamanafzal

Enterprise API: Include additional detail-level fields in Enterprise Catalog "Courses" list endpoint
The fields are: 
course detail -> outcome
course detail -> modifed
course detail -> level_type
course run detail -> staff
course run detail -> content_language

2020-04-29 14:59 UTC, jmyatt requested changes

2020-04-29 14:59 UTC, jmyatt commented on course_discovery/apps/api/serializers.py
> +            'content_language': course_run.language.code if course_run.language else None,
I don't think you want to add this here, since it's one of the new fields you're adding conditionally based on the presence of `detail_fields`

2020-04-29 14:59 UTC, jmyatt commented on course_discovery/apps/course_metadata/search_indexes.py
> +        return obj.outcome if obj.outcome else None
simply `return obj.outcome` would behave the same way, no?  But also, it looks like you can skip this function altogether and just add a `model_attr` to line 120 where you define the `outcome` field

2020-04-29 14:59 UTC, jmyatt commented on course_discovery/apps/course_metadata/search_indexes.py
> +    outcome = indexes.CharField(null=True, faceted=True)
I don't think you want `faceted=True` here since this is a long form text field (used for search and display but not faceting, like short_description and long_description)

2020-04-29 19:52 UTC, zamanafzal commented on course_discovery/apps/course_metadata/search_indexes.py
> +        return obj.outcome if obj.outcome else None
yes, you are right. let me add the `model_attr`.

2020-04-29 23:22 UTC, zamanafzal commented
@jmyatt Thank you for the feedback. I have incorporated it. Can you please spare some time and take a look again. Thanks

2020-05-04 13:07 UTC, jmyatt approved these changes
LGTM

2020-05-05 08:54 UTC, merged