Swang/ws 1009
openedx/course-discovery pull request #2656
Opened 2020-07-09 13:09 UTC by reillz10

2020-07-09 20:08 UTC, mikix commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        with self.assertNumQueries(42):
Could this be avoided by actually using the prefetch_queryset call that was added?

2020-07-09 20:29 UTC, reillz10 commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        with self.assertNumQueries(42):
Potentially, although it didn't avoid it locally when I updated the code to use it. That said, I might be doing something wrong.

2020-07-10 13:05 UTC, rgraber requested changes
We need to test the collaborator serializer beyond the empty set

2020-07-10 13:05 UTC, rgraber commented on course_discovery/apps/ietf_language_tags/migrations/0004_auto_20200618_1744.py
> +# Generated by Django 2.2.12 on 2020-06-18 17:44
remove this file. this one is one me, i need to wrap up this migration, but that will be a separate ticket

2020-07-10 13:06 UTC, reillz10 commented on course_discovery/apps/ietf_language_tags/migrations/0004_auto_20200618_1744.py
> +# Generated by Django 2.2.12 on 2020-06-18 17:44
👍

2020-07-10 13:07 UTC, JackedX approved these changes
⛵️LGTM

2020-07-10 13:17 UTC, mikix commented on course_discovery/apps/ietf_language_tags/migrations/0004_auto_20200618_1744.py
> +    ]
This was a forgotten migration that you're throwing in?

2020-07-10 13:17 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +class Collaborator(TimeStampedModel):
This seems awfully similar to a Person model, just dropping some (blankable) fields you don't care about. Is there a reason not to use that? Person models are used for Endorsements and as staff for CourseRuns.

So we have CourseEditors for Publisher writers. Person for instructors. And Collaborators for Studio writers?

(I also have a gut WW2 reaction to the word collaborators, but maybe that's just me.)

2020-07-10 13:17 UTC, mikix commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        with self.assertNumQueries(42):
I think that means it wasn't being used?

I mean, this test doesn't make any Collaborators so this is 3 extra queries to find nothing. I bet that should either be 0 or 1 as part of a big prefetch join?

2020-07-10 13:17 UTC, mikix commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        with self.assertNumQueries(42):
You don't have any tests that actually create and test the serialization of a Collaborator, with a factory and all that.

2020-07-10 13:44 UTC, reillz10 commented on course_discovery/apps/course_metadata/models.py
> +class Collaborator(TimeStampedModel):
Its probably more similar to a Organization model (although, presumably the collaborator could be an organization or a person), with the blankable fields and the specific dimensions that we want for the image. I wasn't sure if that would have any negative effects such as new school pages being built for these organizations.

![Screen Shot 2020-07-10 at 9 40 44 AM](https://user-images.githubusercontent.com/11048849/87160874-ad31f400-c291-11ea-9231-836fb6a0fdd1.png)

2020-07-10 15:42 UTC, reillz10 commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        with self.assertNumQueries(42):
added one in `test_serializers.py`

2020-07-10 17:00 UTC, reillz10 commented on course_discovery/apps/ietf_language_tags/migrations/0004_auto_20200618_1744.py
> +    ]
removed

2020-07-14 14:25 UTC, rgraber commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        with self.assertNumQueries(42):
I have a hunch about fixing this but would like to put that in the next PR (should be a pretty fast follow) to unblock some work in prospectus that will consume the new field.

2020-07-14 14:32 UTC, rgraber approved these changes

2020-07-14 15:03 UTC, mikix approved these changes
Sure!

2020-07-14 15:08 UTC, merged