WS-1180: Collaborator endpoints
openedx/course-discovery pull request #2662
Opened 2020-07-16 19:03 UTC by JackedX

Adds a GET, POST,  LIST endpoint at /api/v1/collaborators

2020-07-17 12:10 UTC, rgraber requested changes
Couple notes, also it would be good to include the update to the /courses endpoint (allowing it to update a course's collaborators based on a list of uuids) as part of this PR so we don't have to go through discovery release twice

2020-07-17 12:10 UTC, rgraber commented on course_discovery/apps/api/serializers.py
> +    @classmethod
Why do we need this?

2020-07-17 12:10 UTC, rgraber commented on course_discovery/apps/api/filters.py
> +
we only need to get by uuid so i don't think we need this filter

2020-07-17 12:10 UTC, rgraber commented on course_discovery/apps/api/v1/views/collaborators.py
> +    filterset_class = filters.CollaboratorFilter
I think we can get rid of the filter logic

2020-07-17 12:10 UTC, rgraber commented on course_discovery/apps/api/v1/views/collaborators.py
> +    queryset = serializers.CollaboratorSerializer.prefetch_queryset()
I don't think we need to specify this if the queryset is just Collaborators.objects.all()

2020-07-17 12:10 UTC, rgraber commented on course_discovery/apps/core/tests/factories.py
> +    name = (factory.Faker('first_name'), factory.Faker('last_name'))
I think there are factories for images that would be useful to have

2020-07-17 12:40 UTC, JackedX commented on course_discovery/apps/api/v1/views/collaborators.py
> +    queryset = serializers.CollaboratorSerializer.prefetch_queryset()
if I take out this queryset I get this error message

'CollaboratorViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.

2020-07-17 12:41 UTC, JackedX commented on course_discovery/apps/core/tests/factories.py
> +    name = (factory.Faker('first_name'), factory.Faker('last_name'))
K I'll work on this.

2020-07-17 12:42 UTC, rgraber commented on course_discovery/apps/api/v1/views/collaborators.py
> +    queryset = serializers.CollaboratorSerializer.prefetch_queryset()
Did not know that, thanks

2020-07-17 12:46 UTC, JackedX commented on course_discovery/apps/api/serializers.py
> +    @classmethod
Yeah we do actually :(

2020-07-17 12:46 UTC, JackedX commented on course_discovery/apps/api/v1/views/collaborators.py
> +    filterset_class = filters.CollaboratorFilter
Done

2020-07-17 13:32 UTC, albemarle commented on course_discovery/apps/api/serializers.py
> +        # choices shows the possiblity values via HTTP's OPTIONS verb
typo in "possible"

2020-07-20 13:43 UTC, JackedX commented on course_discovery/apps/api/filters.py
> +
removed

2020-07-20 15:26 UTC, JackedX commented on course_discovery/apps/core/tests/factories.py
> +    name = (factory.Faker('first_name'), factory.Faker('last_name'))
added FakeURL calls

2020-07-21 19:02 UTC, rgraber requested changes
Needs tests around update and I had a few questions, but is mostly there

2020-07-21 19:02 UTC, rgraber commented on course_discovery/apps/api/serializers.py
> +    def choices(self):
this is unused

2020-07-21 19:02 UTC, rgraber commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with django_assert_num_queries(FuzzyInt(63, 2)):
I'm surprised this went up since we already had collaborators in the CourseSerializer. Any idea what caused it?

2020-07-21 19:02 UTC, rgraber commented on course_discovery/apps/api/v1/tests/test_views/test_collaborators.py
> +class CollaboratorViewSetTests(OAuth2Mixin, SerializationMixin, APITestCase):
Need tests for /update

2020-07-21 19:02 UTC, rgraber commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.user = UserFactory(is_staff=True, is_superuser=True)
This is a little concerning, do you know why it had to be updated to superuser?

2020-07-21 19:02 UTC, rgraber commented on course_discovery/apps/api/v1/views/courses.py
> +            course.save()
A bulk add would save us a few trips to the database

2020-07-21 19:02 UTC, rgraber commented on course_discovery/apps/api/v1/views/courses.py
> +        if data.get('collaborators'):
see previous comment about bulk adds

2020-07-21 19:07 UTC, JackedX commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.user = UserFactory(is_staff=True, is_superuser=True)
yeah we don't need that anymore

2020-07-21 19:08 UTC, JackedX commented on course_discovery/apps/api/serializers.py
> +    def choices(self):
removed

2020-07-21 19:33 UTC, JackedX commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with django_assert_num_queries(FuzzyInt(63, 2)):
This happened on the build serve... I haven't been able to fail it locally

2020-07-21 19:33 UTC, JackedX commented on course_discovery/apps/api/v1/tests/test_views/test_collaborators.py
> +class CollaboratorViewSetTests(OAuth2Mixin, SerializationMixin, APITestCase):
will do

2020-07-22 12:52 UTC, JackedX commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with django_assert_num_queries(FuzzyInt(63, 2)):
reverted

2020-07-22 13:25 UTC, rgraber approved these changes
LGTM

2020-07-22 13:39 UTC, reillz10 approved these changes

2020-07-23 14:11 UTC, mikix commented on course_discovery/apps/api/serializers.py
> +            return Collaborator.objects.all()
Why would the collaborator class not have a model manager?

2020-07-23 14:11 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +    def get_image_url(self):
It seems confusing to name a property with a verb like that. I know `Person` does that with `get_profile_image_url`, but that is more of a mistake to not repeat than example to follow. I'd say follow the footsteps of `Course` and `CourseRun` and just call this `image_url`.

2020-07-23 14:11 UTC, mikix commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with django_assert_num_queries(FuzzyInt(55, 3)):
Did this get actually get flakier/fuzzier or did the base value just increase?

2020-07-23 14:11 UTC, mikix commented on course_discovery/apps/api/v1/views/collaborators.py
> +    permission_classes = (IsAuthenticated, IsCourseEditorOrReadOnly,)
`IsCourseEditorOrReadOnly` expects to be working on `Course` objects -- you can see that from its `has_object_permissions` code. You may want your own `IsCollaboratorEditorOrReadOnly` or something that is named better.

2020-07-23 14:11 UTC, mikix commented on course_discovery/apps/api/v1/views/collaborators.py
> +    pagination_class = PageNumberPagination
Please use `CursorPagination` for all new endpoints. It's got much better performance when iterating on larger data sets (not that this endpoint is likely to be in thousands, but better safe than sorry).

2020-07-23 14:11 UTC, mikix commented on course_discovery/apps/api/v1/views/collaborators.py
> +    metadata_class = MetadataWithRelatedChoices
Why this metadata class? That's useful if you want to include the full set of choices for a related field in your model in OPTIONS calls. Collaborator doesn't have related fields, right?

2020-07-23 14:11 UTC, mikix commented on course_discovery/apps/api/v1/views/collaborators.py
> +    def create(self, request, *args, **kwargs):
Is this method definition useful? It's exactly the same as `super().create` except that it has special handling for an exception from `perform_create`. Which, I'm not sure how useful that is.

Maybe we can just call the super instead of redefining it?

Same with update and partial_update below. I don't think we need any of this custom logic.

2020-07-23 14:11 UTC, mikix commented on course_discovery/apps/api/v1/views/collaborators.py
> +        return super(CollaboratorViewSet, self).list(request, *args, **kwargs)
Python3 style is to just call `super().list(...)` without the class name and self there.

2020-07-23 14:11 UTC, mikix commented on course_discovery/apps/api/v1/views/courses.py
> +                collaborators.append(Collaborator.objects.get(uuid=uuid))
`Collaborator.objects.filter(uuid__in=collaborators_uuid)` is just one lookup, not N. Same below in the update call.

2020-07-23 14:11 UTC, mikix commented on course_discovery/apps/api/v1/views/courses.py
> +            course.save()
You don't need `save()` here -- `add()` does the save already.

2020-07-23 14:11 UTC, mikix commented on course_discovery/apps/core/tests/factories.py
> +    name = (factory.Faker('first_name'), factory.Faker('last_name'))
Is that a tuple or a string that ends up being set?

2020-07-24 12:47 UTC, JackedX commented on course_discovery/apps/api/serializers.py
> +            return Collaborator.objects.all()
Well Django actually creates a default manager for all models... I don't need to do anything custom with this so I think a manager may just be extra overhead.

"By default, Django adds a Manager with the name objects to every Django model class. However, if you want to use objects as a field name, or if you want to use a name other than objects for the Manager, you can rename it on a per-model basis. "

https://docs.djangoproject.com/en/3.0/topics/db/managers/

2020-07-24 12:48 UTC, JackedX commented on course_discovery/apps/api/v1/views/collaborators.py
> +    def create(self, request, *args, **kwargs):
removed

2020-07-24 12:50 UTC, JackedX commented on course_discovery/apps/core/tests/factories.py
> +    name = (factory.Faker('first_name'), factory.Faker('last_name'))
suppose to be a string

2020-07-24 13:02 UTC, mikix commented on course_discovery/apps/api/serializers.py
> +            return Collaborator.objects.all()
Right. So what I'm saying is, why check `if Collaborator.objects:`? It should always be present.

2020-07-24 13:06 UTC, mikix commented on course_discovery/apps/core/tests/factories.py
> +    name = (factory.Faker('first_name'), factory.Faker('last_name'))
Right, but you are setting name as a tuple of strings. Like, in a console, play with `('a', 'b')` vs `'a' + 'b'` or whatever. Maybe the factory code does something smart with that though.

But it doesn't matter, you can just use `name = factory.Faker('name')` instead of breaking it up and stitching it back.

2020-07-24 13:18 UTC, JackedX commented on course_discovery/apps/api/serializers.py
> +            return Collaborator.objects.all()
ah that's what you meant... Python Phun

2020-07-24 13:21 UTC, JackedX commented on course_discovery/apps/core/tests/factories.py
> +    name = (factory.Faker('first_name'), factory.Faker('last_name'))
yeah I eventually did that ;)

2020-07-24 13:22 UTC, JackedX commented on course_discovery/apps/api/serializers.py
> +            return Collaborator.objects.all()
removed the if

2020-07-24 13:23 UTC, JackedX commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with django_assert_num_queries(FuzzyInt(55, 3)):
Not sure how to tell the difference

2020-07-24 16:02 UTC, JackedX commented on course_discovery/apps/api/v1/views/collaborators.py
> +    permission_classes = (IsAuthenticated, IsCourseEditorOrReadOnly,)
Thanks for the feedback updated...

I spoke with Rebecca and she's ok with replicating the Course permission for collaborators

2020-07-24 16:03 UTC, JackedX commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with django_assert_num_queries(FuzzyInt(55, 3)):
thanks for explaining the subtleties of this queries

2020-07-24 16:42 UTC, mikix approved these changes
Looks good!  Thanks for dealing with me.  :)

2020-07-24 16:42 UTC, mikix commented on course_discovery/apps/api/v1/views/collaborators.py
> +class CollaboratorViewSet(CompressedCacheResponseMixin, viewsets.ModelViewSet):
Removing the stub methods that just called super() is fine. But just FYI for why you'll see that pattern in Discovery is for the autogenerated swagger docs (http://localhost:18381/api-docs/)

The stubs were included just for their docstrings being a little specific ("list all Collaborators") vs whatever the default text is in swagger. I'm ambivalent on the value of that. But that's what they are doing when you see the pattern.

2020-07-24 17:05 UTC, JackedX commented on course_discovery/apps/api/v1/views/collaborators.py
> +class CollaboratorViewSet(CompressedCacheResponseMixin, viewsets.ModelViewSet):
ahh that makes sense I'll put them back

2020-07-24 17:15 UTC, JackedX commented
@mikix It was a learning experience! Thank you so much!

2020-07-27 17:06 UTC, merged