Add uniqueness constraints on Organization.uuid and .key
openedx/course-discovery pull request #2810
Opened 2020-10-28 18:12 UTC by kdmccormick

Throughout the Platform, we make assumptions around the
uniqueness of they Organization.key field (known as
Organization.short_name in edx-platform). As part of the
phase in of db-backed-organizations for all edx-platform
instances, it would be best to enforce this uniqueness at
the database level.

Since Discovery's course_metadata is the source of truth
for Organization data on edX.org, and pushes updates to
edx-platform's Organization table, it is best that it the
uniqueness is enforced in Discovery's database as well.

https://openedx.atlassian.net/browse/TNL-7645

2020-10-28 18:18 UTC, kdmccormick commented on course_discovery/apps/course_metadata/models.py
> +    )
Other than spacing, the change here is the addition of `unique=True` on both these fields.

2020-10-29 13:07 UTC, mikix requested changes

2020-10-29 13:07 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +        unique=True,
So the database is basically partitioned according to `partner`. Most unique model keys have `unique_together`s with `partner`, rather than being `unique=True` by themselves. Programs, courses, people, subjects, the whole course catalog basically is partitioned.

This is because each partner site is its own entity. If MITxPro's site (which doesn't exist anymore, but bear with me) wanted to also host the same key as edX's site, there's no reason we shoud stop them.

So I'd say key here at least should have a unique_together with `partner`.

UUID is more interesting. If the data we're holding can be synced around, then it's not insane to make a UUID unique only with a partner. (i.e. if MITxPro can have its own copy of this model that it and edX sync from the same place -- the UUID should be the same in that sense -- i.e. someone else owns the uuid and we are merely recording it)

For this case... now that disco owns the UUID, that's not true. We can probably have it be unique by itself. But I'm not confident that that will always be the case? It didn't use to be the case, we used to sync that data from elsewhere. So it also might be defensive to just have it be unique with partner (and that follows the general rules in course_metadata of keeping partitions walled off from each other). But I'm open to that being unnecessary here, especially if we want a way to uniquely represent objects between sites (which I don't think we generally do, anyone that talks to discovery needs to be site-aware of what site they are working with, even if just implicitly by what domain name they talk to discovery as).

2020-10-29 15:18 UTC, kdmccormick commented on course_discovery/apps/course_metadata/models.py
> +        unique=True,
@mikix Right! I always forget about `partner`. Thank you for pointing this out.

If I include `partner_id` in those queries, it becomes apparent `(partner, uuid)` and `(partner, key)` would both be currently valid unique-together constraints on stage and prod. For example:

```sql
mysql> select `partner_id`, `id`, `uuid`, `key`, `name` from course_metadata_organization where `key` in (select `key` from course_metadata_organization group by `key` having count(*) > 1) order by `key`;
+------------+-----+----------------------------------+-------------------------+---------------------------------------+
| partner_id | id  | uuid                             | key                     | name                                  |
+------------+-----+----------------------------------+-------------------------+---------------------------------------+
|          1 | 527 | 329a1e2658724fffb6f62b8769d5d43d | HarvardMedGlobalAcademy | Harvard Medical School Global Academy |
|          4 | 530 | 06151c47d2784a11b576c957cac2044d | HarvardMedGlobalAcademy |                                       |
|          4 | 960 | 3744a45bfee546b2803129b6ef4c6990 | HMSCMEOnline            | Harvard Medical School                |
|          1 | 962 | 527922ace6ac454ab46b3dcd40fdf6d7 | HMSCMEOnline            | HMSCMEOnline                          |
|          1 | 330 | 5a76f79ceb444b08985699fc0e7de14d | MITProfessionalX        | MIT Professional Education            |
|          2 | 637 | 2a4e1c88d541407481acb691e16f192b | MITProfessionalX        | MIT Professional Education            |
|          2 | 676 | 0c3ff91fad694574a0ff1771c2099aec | MITxPRO                 |                                       |
|          1 | 699 | 67f3816b26ad49e6875e2d45d2bdbc8a | MITxPRO                 | MIT xPRO                              |
+------------+-----+----------------------------------+-------------------------+---------------------------------------+
```
The reason I want these constraints is so that Discovery isn't pushing duplicate organizations to LMS, but since it does so based on `partner.organization_api_url` (which is only set for the `edX` partner), I feel comfortable with the unique-togethers. I would much rather do this than having to keep pushing on getting those rows deleted.

As for having `uuid` unique-alone or unique-together with partner, I can see both sides of the argument. For this PR, I'll stick with the looser constraint, and leave it to you folks if you wanted to tighten it to unique-alone later.

Would you be OK with this PR if it just added unique_together constraints for `(partner, uuid)` and `(partner, key)`?

2020-10-29 15:26 UTC, mikix commented on course_discovery/apps/course_metadata/models.py
> +        unique=True,
Yeah, unique_together for partner&uuid, and partner&key feel right to me.

And looking at code, it's actually already there!

2020-10-29 15:31 UTC, kdmccormick commented on course_discovery/apps/course_metadata/models.py
> +        unique=True,
Well, would you look at that.

Sorry for wasting your time!

2020-10-29 15:32 UTC, kdmccormick commented
Closing as unnecessary; see Mike's comment above.

2020-10-29 15:32 UTC, closed without merging