Created tab and fields for Sales Force.
openedx/course-discovery pull request #302
Opened 2016-09-07 12:09 UTC by waheedahmed

[ECOM-5110] (https://openedx.atlassian.net/browse/ECOM-5110)

**Acceptance Criteria:**

1. VERIFY that data for all fields required for publishing to Salesfore are shown as a tab on the course-run details page.
2. VERIFY that copy to clipboard can be done using a copy button for each field (rather than highlighting manually and copying)

**Screenshots:**
![screencapture-localhost-8004-publisher-course_runs-17-1473249979857](https://cloud.githubusercontent.com/assets/2851134/18311439/aef6284e-751d-11e6-8ec6-9f3f2553a606.png)

2016-09-07 12:51 UTC, waheedahmed commented
@awais786 @bderusha Please review.

2016-09-09 09:16 UTC, awais786 commented
@bderusha Please review.

2016-09-09 12:06 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_wrapper.py
> +from course_discovery.apps.course_metadata.models import CourseRun as CourseMetadataCourseRun
Can we import the Pacing directly here? This import is very broad

2016-09-09 12:07 UTC, bderusha commented
:+1: once Todos are resolved

2016-09-11 20:17 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_wrapper.py
> +from course_discovery.apps.course_metadata.models import CourseRun as CourseMetadataCourseRun
@bderusha I think we need to import the CourseRun here. Pacing directly not working.

2016-09-11 20:22 UTC, awais786 commented
@bderusha Would you please tell me what the Todos ? I did't find any information on the ticket.

2016-09-26 19:45 UTC, bderusha commented on course_discovery/templates/publisher/course_run_detail.html
> +        <button data-tab="#tab-5">{% trans "Sales Force" %}</button>
`Salesforce`  One word

2016-09-26 19:45 UTC, bderusha commented on course_discovery/templates/publisher/course_run_detail.html
> +            {% include 'publisher/course_run_detail/_sales_force.html' %}
same here `_salesforce.html` one word

2016-09-26 19:46 UTC, bderusha commented on course_discovery/templates/publisher/course_run_detail/_sales_force.html
> +                {% include "publisher/course_run_detail/clipboard.html" %}
Clipboard not required for booleans.  Please update here and everywhere a boolean is presented

2016-09-26 19:48 UTC, bderusha commented on course_discovery/apps/publisher/wrappers.py
> +        if self.wrapped_obj.pacing_type == 'self_paced':
please use `CourseMetadataCourseRun.Pacing.Self`

2016-09-26 19:49 UTC, bderusha requested changes
Looks good.  Will review again when all TODOs are addressed in the code

2016-09-28 11:44 UTC, waheedahmed commented
@bderusha All TODO's resolved please take another look.

2016-09-28 14:15 UTC, awais786 commented
👍

2016-09-29 13:31 UTC, bderusha commented
👍

2016-09-29 13:36 UTC, bderusha approved these changes

2016-09-29 13:49 UTC, merged