feat: upgrade pyjwt to version 2.1.0
openedx/course-discovery pull request #3086
Opened 2021-08-11 10:41 UTC by iamsobanjaved

2021-08-11 11:34 UTC, iamsobanjaved commented on Makefile
> +	sed 's/pyjwt\[crypto\]<2.0.0//g' requirements/common_constraints.txt > requirements/common_constraints.tmp
We are creating a local copy of the common constraints file and override/remove the global constraint which we don't need. This approach is used temporarily and will be improved in https://openedx.atlassian.net/browse/BOM-2721

2021-08-24 09:46 UTC, waheedahmed requested changes
One concern otherwise looks good.

2021-08-24 09:46 UTC, waheedahmed commented on requirements/local.txt
> +elasticsearch==7.14.0
`7.14.0` has some breaking changes, it broke the production when we deployed last time. I'm not sure why it's upgraded to `7.14.0` even we have a constraint for it https://github.com/edx/course-discovery/pull/3086/files#diff-86d5fe588ff2fc7dccb1f4cdd8019d4473146536e88d7a9ede946ea962a91acbR10?

2021-08-24 10:01 UTC, awais786 commented on requirements/local.txt
> +elasticsearch==7.14.0
I think PR created before the constraint.

2021-08-24 10:13 UTC, awais786 approved these changes

2021-08-24 10:16 UTC, waheedahmed commented on requirements/common_constraints.txt
> +elasticsearch<7.14.0
This is already in place inside `requirements/constraints.txt`.

2021-08-24 10:24 UTC, waheedahmed approved these changes

2021-08-24 10:43 UTC, merged