fix: update course_run api
openedx/course-discovery pull request #3123
Opened 2021-09-10 14:46 UTC by mubbsharanwar

- update course_run api to edit upgrade_deadline date using publisher app.

DISCO-1622

2021-09-16 08:04 UTC, waheedahmed requested changes
Also, update the Publisher PR.

2021-09-16 08:04 UTC, waheedahmed commented on course_discovery/apps/api/v1/views/course_runs.py
> +        print('studio api link ', course_run.course.partner.studio_url)
nit: remove this print statement.

2021-09-16 08:04 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +            defaults['upgrade_deadline'] = upgrade_deadline
We were supposed to expose the `upgrade_deadline_override` in Publisher instead of `upgrade_deadline` field.

2021-09-17 14:38 UTC, waheedahmed requested changes

2021-09-17 14:38 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +            upgrade_deadline_override=upgrade_deadline_override,
We need to add a check above this otherwise it will set null if the value is not sent in the PATCH request.

2021-09-17 14:38 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +            upgrade_deadline_override=upgrade_deadline_override,
Also, in my testing, it created duplicate seat objects instead of updating the existing ones.

2021-09-17 14:39 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +            upgrade_deadline_override=upgrade_deadline_override,
<img width="748" alt="Screenshot 2021-09-17 at 7 39 06 PM" src="https://user-images.githubusercontent.com/2851134/133801442-05d64509-08cc-4a41-8dcf-4ebd35960109.png">

2021-09-28 12:05 UTC, waheedahmed requested changes
One change otherwise 👍

2021-09-28 12:05 UTC, waheedahmed commented on course_discovery/apps/course_metadata/models.py
> +        if upgrade_deadline_override and seat_type.slug != Seat.AUDIT:
I guess the upgrade deadline is only meant for Verified seat types and we can update this condition like this:
```suggestion
        if upgrade_deadline_override and seat_type.slug != Seat.VERIFIED:
```

2021-09-28 12:41 UTC, mubbsharanwar commented on course_discovery/apps/course_metadata/models.py
> +        if upgrade_deadline_override and seat_type.slug != Seat.AUDIT:
if upgrade deadline is only meant for Verified seat types then condition should be like 
`if upgrade_deadline_override and seat_type.slug == Seat.VERIFIED:`

2021-09-28 12:47 UTC, waheedahmed approved these changes

2021-09-29 06:33 UTC, merged