feat: csv data loader
openedx/course-discovery pull request #3241
Opened 2021-12-29 15:58 UTC by DawoudSheraz

WIP

2022-01-07 14:41 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/utils.py
> +        if response.status_code == requests.codes.ok:  # pylint: disable=no-member
is this different from rest_framework.status? If not, we can use them instead.

2022-01-17 13:53 UTC, DawoudSheraz commented
cc: @ziafazal ready for review

2022-01-18 14:34 UTC, ziafazal requested changes
@DawoudSheraz I have completed first round of review overall looks good. I have few suggestions. 
One thing I have noticed if we have invalid data in CSV we can get stuck. For example the csv I used had **Upgrade Deadline Override Date** set to 06/23/2022 which resulted in this error
```Failed to publish commerce data for course-v1:edX+1RN8K+1T2022 to LMS. Verification deadline must be after the course mode upgrade deadlines.```
I then updated the **Upgrade Deadline Override Date** to 02/22/2022 to make it prior to **End Date** but the error did not go away(possibly because we can't update it from publisher APIs).
I think we should add some data validation in our loader to avoid such errors.

2022-01-18 14:34 UTC, ziafazal commented on course_discovery/apps/course_metadata/data_loaders/tests/mixins.py
> +import six
Using `six` does not make sense in in python 3.

2022-01-18 14:34 UTC, ziafazal commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            if not Organization.objects.filter(key=org_key).exists():
Should not we create the organization if it does not exist?

2022-01-18 14:34 UTC, ziafazal commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +        collaborators = [collaborator for collaborator in collaborators if collaborator.strip()]
nit: strip the value being added in the list `[collaborator.stript() for collaborator in collaborators if collaborator.strip()]`

2022-01-18 14:34 UTC, ziafazal commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +                course = Course.everything.get(key=course_key, partner=self.partner)
I think we should not use `get` with `everything` here and in statements below it sometimes return more than one record.
```
(Pdb) Course.everything.get(key=course_key, partner=self.partner)
*** course_discovery.apps.course_metadata.models.Course.MultipleObjectsReturned: get() returned more than one Course -- it returned 2!
(Pdb) Course.objects.get(key=course_key, partner=self.partner)
<Course: edX+MDVLL: id porro>
```

2022-01-18 16:00 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/tests/mixins.py
> +import six
Right, I will update this.

2022-01-18 16:01 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            if not Organization.objects.filter(key=org_key).exists():
Since the organization has other fields too(logo, description), we should not create org if not found.

2022-01-18 16:03 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +                course = Course.everything.get(key=course_key, partner=self.partner)
Yes, I have noted that down in https://openedx.atlassian.net/browse/PROD-2618. However, if the course is present in DB, what variant should we get ideally? Draft or live? The choice here matters. When filtering with `objects`, it filters draft out of queryset. That's why I was using `everything`

2022-01-18 16:04 UTC, DawoudSheraz commented
> @DawoudSheraz I have completed first round of review overall looks good. I have few suggestions. One thing I have noticed if we have invalid data in CSV we can get stuck. For example the csv I used had **Upgrade Deadline Override Date** set to 06/23/2022 which resulted in this error `Failed to publish commerce data for course-v1:edX+1RN8K+1T2022 to LMS. Verification deadline must be after the course mode upgrade deadlines.` I then updated the **Upgrade Deadline Override Date** to 02/22/2022 to make it prior to **End Date** but the error did not go away(possibly because we can't update it from publisher APIs). I think we should add some data validation in our loader to avoid such errors.

Yes, already noted on https://openedx.atlassian.net/browse/PROD-2618. However, we are not sure if the ExEd courses will have this verification deadline override applicable. Once we are certain of that, we can add appropriate checks where needed.

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +Data loader responsible for creating course and course runs entries in Database
We may add more along these lines: ...Database, push to studio and other services

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            self.reader = csv.DictReader(open(csv_path, 'r'))
do we have a plan to sanitize csv input?

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +                course_run = CourseRun.objects.filter_drafts(course=course).first()
do we need to check if `course_run` is found or not?

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            'expected_program_type': program_type if program_type in self.PROGRAM_TYPES else None,
What will `None` represent here?

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +                raise Exception(
where will this exception get caught?

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            data.get('primary_subject'),
do we need to add default return?

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +    def get_subject_slugs(self, *subjects):
do we need to verify value/entry from subject model?

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +        collaborators = [collaborator.strip() for collaborator in collaborators if collaborator.strip()]
why we are striping twice?

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +        # TODO: CSV would need to provide more information to identify staff members from other than names
For this I guess we are planning to add staff in separate function, right.

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/tests/mixins.py
> +            header = '{}{},'.format(header, title_case_key)
we can append header names in list and then use `",".join(header)`

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/tests/mixins.py
> +            lines = f"{lines[:-1]}\n"
same impl as in above comment

2022-01-25 21:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/tests/mock_data.py
> +VALID_COURSE_AND_COURSE_RUN_CSV_DICT = {
in dates please use date greater than 12 so that the format is understood easily. e.g. `12/25/2022`

2022-01-26 05:47 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +Data loader responsible for creating course and course runs entries in Database
Sure.

2022-01-26 05:47 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            self.reader = csv.DictReader(open(csv_path, 'r'))
https://openedx.atlassian.net/browse/PROD-2615 is responsible for this, once this PR merges.

2022-01-26 05:48 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +                course_run = CourseRun.objects.filter_drafts(course=course).first()
The course creation call creates one run for it too. Therefore, the course run will be present. But I guess having a check would not hurt.

2022-01-26 05:49 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            'expected_program_type': program_type if program_type in self.PROGRAM_TYPES else None,
For serializer to ignore this value.

2022-01-26 05:51 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            data.get('primary_subject'),
I think the function will be returning the empty list if none of the subject entries are present.

2022-01-26 05:51 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +                raise Exception(
https://github.com/openedx/course-discovery/pull/3241/files#diff-c981dbbc87edba29cfa41634f17d194a25a3bd209560c130628f027714f2c7d9R109

2022-01-26 05:52 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +    def get_subject_slugs(self, *subjects):
Ah, this is a tricky situation here. The subject objects should be present beforehand in the DB. If that assumption breaks, then yes. We can cater it in input validation ticket(shared above)

2022-01-26 05:53 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +        collaborators = [collaborator.strip() for collaborator in collaborators if collaborator.strip()]
For both if check and the assigned value.

2022-01-26 05:53 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +        # TODO: CSV would need to provide more information to identify staff members from other than names
Yeah, this is here for an initial approach to adding staff.

2022-01-26 05:54 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/tests/mixins.py
> +            header = '{}{},'.format(header, title_case_key)
Yeah, I can check it.

2022-01-26 05:54 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/tests/mixins.py
> +            lines = f"{lines[:-1]}\n"
I will give it a try

2022-01-26 05:56 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +        if response.status_code == requests.codes.ok:  # pylint: disable=no-member
How?

2022-01-26 18:43 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/tests/mixins.py
> +            header = '{}{},'.format(header, title_case_key)
This was causing an error due to some headers missing out in the CSV. Plus, we still need the for loop to convert the key from snake_case to Title case.

2022-01-26 20:54 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/tests/mixins.py
> +            header = '{}{},'.format(header, title_case_key)
This should work but not so important at this point.

```
        header = []
        for key in self.CSV_DATA_KEYS_ORDER:
            title_case_key = key.replace('_', ' ').title()
            header.append(title_case_key)
        
        header = ",".join(header)
```

2022-01-27 05:52 UTC, ziafazal approved these changes
👍

2022-01-27 06:31 UTC, waheedahmed reviewed
A couple of questions otherwise looks good!

2022-01-27 06:31 UTC, waheedahmed commented on course_discovery/apps/course_metadata/utils.py
> +                course.image.save(filename, ContentFile(response.content))
Course image field has some specific criteria, for example:

1. Image must be 1134x675 pixels in size
2. It must be JPEG or PNG
3. etc.

Are we handling those?

2022-01-27 06:31 UTC, waheedahmed commented on course_discovery/apps/course_metadata/utils.py
> +def download_and_save_course_image(course, image_url):
Looks like specific to the data loader only, can we make it a class function instead?

2022-01-27 07:59 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +def download_and_save_course_image(course, image_url):
Actually, no, I made this util function by moving out download and save logic from the management command https://github.com/openedx/course-discovery/blob/master/course_discovery/apps/course_metadata/management/commands/download_course_images.py.

2022-01-27 07:59 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +                course.image.save(filename, ContentFile(response.content))
Valid point, we can add those checks in a follow-up PR, covered under https://openedx.atlassian.net/browse/PROD-2615

2022-01-27 09:09 UTC, waheedahmed approved these changes

2022-01-27 10:30 UTC, merged