feat: Augmented the pathway models with new fields
openedx/course-discovery pull request #3251
Opened 2022-01-15 09:46 UTC by irfanuddinahmad

**Description**: This PR updated the learner pathway and pathway step models with the following new fields:
                            Status: active=published, inactive=not published
                            Scope: single enterprise, multiple enterprise, all enterprises
                            Enterprise Customer: UUID(s) of customers who should see this pathway. If blank, no one sees it. If blank AND type=all enterprises, all enterprises see it.
                            Banner image:  Banner image url.
                            Overview: The text field to describe the pathway.
                            Minimum Requirement: Minimum number of nodes required for step completion.

**JIRA**: [ENT-5274](https://openedx.atlassian.net/browse/ENT-5274)

2022-01-17 06:56 UTC, saleem-latif requested changes

2022-01-17 06:56 UTC, saleem-latif commented on course_discovery/apps/learner_pathway/models.py
> +    uuid = models.UUIDField(primary_key=True, default=uuid4, editable=False)
We should not have a default for this.

2022-01-17 06:56 UTC, saleem-latif commented on course_discovery/apps/learner_pathway/models.py
> +        max_length=16, null=False, blank=False, default=PathwayStatus.Inactive,
I think the default `null=False` and `blank=False` are default values so do not need to pass them explicitly.

2022-01-17 06:56 UTC, saleem-latif commented on course_discovery/apps/learner_pathway/models.py
> +        max_length=16, null=False, blank=False, default=PathwayScope.Single,
I think the default `null=False` and `blank=False` are default values so do not need to pass them explicitly.

2022-01-17 06:56 UTC, saleem-latif commented on course_discovery/apps/learner_pathway/models.py
> +        related_name='enterprise_uuids',
I think related name here should be `learner_pathways`

2022-01-17 06:56 UTC, saleem-latif commented on course_discovery/apps/learner_pathway/models.py
> +        help_text=("List of enterprises that can access the pathway. If blank, no one sees it. "
nit: change indentation to 
```
 help_text=_(
    "List of enterprises that can access the pathway. If blank, no one sees it. If blank AND scope=all, all enterprises get access"
)
 


```

2022-01-17 06:56 UTC, saleem-latif commented on course_discovery/apps/learner_pathway/models.py
> +        help_text=("List of enterprises that can access the pathway. If blank, no one sees it. "
ref: https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#breaking-long-lines

2022-01-17 06:56 UTC, saleem-latif commented on course_discovery/apps/learner_pathway/models.py
> +        blank=True,
Wouldn't it be better to skip `blank=True` since this column has a default value?

2022-01-17 08:02 UTC, muhammad-ammar requested changes
I am done with first pass of the review. Let me know once the PR is ready for second review.

* We also need to add unit tests.

2022-01-17 08:02 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/models.py
> +    banner_image_url = models.URLField(blank=True, null=True)
How the image will be uploaded to S3 bucket?

2022-01-17 08:02 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/models.py
> +            MinValueValidator(1)
Can you please explain how this validation works?

2022-01-17 08:02 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/models.py
> +    uuid = models.UUIDField(primary_key=True, editable=False)
How the data will be populated in this model?

2022-01-17 08:02 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/models.py
> +        max_length=16, default=PathwayScope.Single,
How we will ensure that in case of `single` scope, a pathway can be associated with multiple `enterprise_customer_uuids`?

2022-01-17 08:02 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/choices.py
> +    Multiple = ChoiceItem('multiple', _('Multiple'))
Do we have a definition of `multiple`?  Do we have a `max`?

2022-01-17 08:02 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/models.py
> +    banner_image_url = models.URLField(blank=True, null=True)
Shouldn't this be a required field?

2022-01-17 08:02 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/models.py
> +    overview = models.TextField(null=True, blank=True)
Shouldn't this be a required field?

2022-01-17 08:02 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/models.py
> +    def clean(self):
Please note the model clean method will only be called when saving a form. It will not be called when we save a model using model `save` method manually. Is this expected?

2022-01-17 08:02 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/models.py
> +            self.min_requirement = node_count
I think this will be confusing. As per my understanding, min requirement should be updated explicitly only through field.

2022-01-17 08:02 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/models.py
> +    uuid = models.UUIDField(primary_key=True, editable=False)
Also what about the backend call mentioned in the ticket?

2022-01-17 08:32 UTC, saleem-latif approved these changes
One more comment, other than that looks good 👍🏼

2022-01-17 08:32 UTC, saleem-latif commented on course_discovery/apps/learner_pathway/models.py
> +        verbose_name = _("Enterprise Customer")
nit: it would be better to be consistent and use single quoted string everywhere

2022-01-18 00:48 UTC, irfanuddinahmad commented on course_discovery/apps/learner_pathway/models.py
> +    banner_image_url = models.URLField(blank=True, null=True)
replaced with imagefield

2022-01-18 00:50 UTC, irfanuddinahmad commented on course_discovery/apps/learner_pathway/models.py
> +            MinValueValidator(1)
MinValueValidator¶
class MinValueValidator(limit_value, message=None)¶
Raises a ValidationError with a code of 'min_value' if value is less than limit_value, which may be a callable.
https://docs.djangoproject.com/en/4.0/ref/validators/

2022-01-18 00:52 UTC, irfanuddinahmad commented on course_discovery/apps/learner_pathway/models.py
> +    uuid = models.UUIDField(primary_key=True, editable=False)
Coordinating with ENT-5294 assignee. Separate PR required for the work to fetch the uuids from edx-enterprise

2022-01-18 00:52 UTC, irfanuddinahmad commented on course_discovery/apps/learner_pathway/models.py
> +        max_length=16, default=PathwayScope.Single,
To be managed at the form level.

2022-01-18 00:53 UTC, irfanuddinahmad commented on course_discovery/apps/learner_pathway/choices.py
> +    Multiple = ChoiceItem('multiple', _('Multiple'))
No max. Multiple is any number greater than 1.

2022-01-18 00:53 UTC, irfanuddinahmad commented on course_discovery/apps/learner_pathway/models.py
> +    banner_image_url = models.URLField(blank=True, null=True)
done

2022-01-18 00:54 UTC, irfanuddinahmad commented on course_discovery/apps/learner_pathway/models.py
> +    overview = models.TextField(null=True, blank=True)
No

2022-01-18 00:55 UTC, irfanuddinahmad commented on course_discovery/apps/learner_pathway/models.py
> +    def clean(self):
Can you suggest an alternative?

2022-01-18 01:01 UTC, irfanuddinahmad commented on course_discovery/apps/learner_pathway/models.py
> +            self.min_requirement = node_count
Raised a ValidationError

2022-01-18 07:22 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/utils.py
> +class UploadToFieldNamePath(FilePattern):
This class is already present [here](https://github.com/openedx/course-discovery/blob/f51ac139fb68ad901878eee0c62cae3551a45b11/course_discovery/apps/course_metadata/utils.py#L296-L315) We can use the that in our app.

2022-01-19 10:42 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/models.py
> +            raise ValidationError(_('Please use a minimum requirement less than the total number of requirements.'))
How about `Minimum requirement can not be greater than the total number of steps in the pathway`?

2022-01-19 10:49 UTC, irfanuddinahmad commented on course_discovery/apps/learner_pathway/models.py
> +            raise ValidationError(_('Please use a minimum requirement less than the total number of requirements.'))
then we have to say minimum steps instead of minimum requirement ...

2022-01-19 10:54 UTC, muhammad-ammar approved these changes

2022-01-19 11:26 UTC, merged