feat: new optional query param that extends fields
openedx/course-discovery pull request #3283
Opened 2022-02-08 20:42 UTC by alex-sheehan-edx

when `extra_fields` is passed as a query param to the program list view, it will include two additional fields of data- `expected_learning_items` and `price_ranges`

2022-02-09 15:02 UTC, waheedahmed requested changes
Instead of copying all the code from`MinimalProgramSerializer` can we simply extend this new class with it and just define the extra fields?

2022-02-09 15:16 UTC, waheedahmed commented on course_discovery/apps/api/v1/views/programs.py
> +            if hasattr(self, 'request') and self.request.query_params.get('extra_fields'):
nit: can we rename the query param to `extended` instead? `extra_fields` seems vague to me.

2022-02-09 15:19 UTC, waheedahmed commented on course_discovery/apps/api/v1/views/programs.py
> +            if hasattr(self, 'request') and self.request.query_params.get('extra_fields'):
And, I don't think we need `hasattr(self, 'request')` here since it's a DRF view so it should always be available.

2022-02-09 15:38 UTC, alex-sheehan-edx commented on course_discovery/apps/api/v1/views/programs.py
> +            if hasattr(self, 'request') and self.request.query_params.get('extra_fields'):
there's a test that doesn't include the request object so I added it as a buffer

2022-02-09 15:40 UTC, alex-sheehan-edx commented on course_discovery/apps/api/v1/views/programs.py
> +            if hasattr(self, 'request') and self.request.query_params.get('extra_fields'):
https://github.com/openedx/course-discovery/pull/3283/files#diff-cd4cde02ab46f0b84879b2513d7e2fa7c18b12a7fefc4c27ee6d2f4880bbc4a5R351-R353 this is the problematic test

2022-02-09 16:18 UTC, binodpant commented on course_discovery/apps/api/serializers.py
> +    When using the FlexFieldsSerializerMixin to get the courses field on a program,
do we actually use this mixin? is this doc line up to date?

2022-02-09 16:26 UTC, alex-sheehan-edx commented on course_discovery/apps/api/serializers.py
> +    When using the FlexFieldsSerializerMixin to get the courses field on a program,
I wanted to have all the same functionality as the minimal serializer which uses that mixin.

2022-02-09 20:46 UTC, binodpant commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        """ Verify that the `extra_fields` query param will result in an extended amount of fields returned. """
change `extra_fields` to `extended`

2022-02-09 21:31 UTC, binodpant commented on course_discovery/apps/api/serializers.py
> +    Eg: ?fields=courses,course_runs
discussed offline with Alex. Even though the filters options does work for some fields appraently it does not seem to work for courses. Hence we can't use it as is rightnow and this seems to be right approach for the time being. We can revisit if we can make the filters mixin work in lieu of this serializer in the future

2022-02-09 21:31 UTC, binodpant approved these changes
lgtm, tested locally by pulling branch

2022-02-10 06:42 UTC, waheedahmed commented on course_discovery/apps/api/v1/views/programs.py
> +            if hasattr(self, 'request') and self.request.query_params.get('extra_fields'):
If there is only one test, could we just pass the request there? I believe we should not add checks to fix some tests and instead correct them.

2022-02-10 06:45 UTC, waheedahmed approved these changes
One last suggestion otherwise 👍

2022-02-10 14:39 UTC, alex-sheehan-edx commented on course_discovery/apps/api/v1/views/programs.py
> +            if hasattr(self, 'request') and self.request.query_params.get('extra_fields'):
I totally agree! Let me see what I can do.

2022-02-10 17:55 UTC, merged