feat: add external identifier in csv loader
openedx/course-discovery pull request #3288
Opened 2022-02-14 05:43 UTC by DawoudSheraz

2022-02-14 07:39 UTC, azanbinzahid requested changes

2022-02-14 07:39 UTC, azanbinzahid commented on course_discovery/apps/api/serializers.py
> +            additional_metadata.save()
shouldn't this be inside the `if` just above?

2022-02-14 07:42 UTC, DawoudSheraz commented on course_discovery/apps/api/serializers.py
> +            additional_metadata.save()
Yes, please suggest this change so I can commit it directly.

2022-02-14 10:37 UTC, azanbinzahid approved these changes

2022-02-15 03:44 UTC, uzairr approved these changes

2022-02-15 05:17 UTC, merged