feat:add utils to transform 2u data
openedx/course-discovery pull request #3291
Opened 2022-02-15 09:59 UTC by uzairr

Add

2022-02-15 10:08 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/utils.py
> +    index_if_exist = lowercase.find('duration')
nit: we can do `>duration:` to be more inclusive there, we don't want to remove the actual word duration in the content if Duration info is not present on the first line. This might remove the need for `lowercase.find('>', 0, index_if_exist)`

2022-02-15 10:09 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/utils.py
> +    return base64.b64decode(data).decode('utf-8')
what happens if the content is not base64? To be on the safe side, we can add a check to decode only if the content is encoded in base64.

2022-02-15 10:10 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/tests/mock_data.py
> +BASE64STRING = 'aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8='
nit: BASE64_STRING

2022-02-15 10:10 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/tests/mock_data.py
> +SHORT_DESCRIPTION = '<p><strong>Duration:</strong> 10 weeks (excluding orientation)<br>\r\n</p><p>An effective digital marketing strategy\r\n</p>'
We should add a 2nd variant where no removal happens if duration information is not present.

2022-02-15 10:11 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/tests/test_utils.py
> +        Test the utility function format_testimonials
docstring updates

2022-02-15 10:28 UTC, azanbinzahid reviewed
Few more test cases would be needed to verify its functionality.

2022-02-15 10:28 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/utils.py
> +    return effort_vals
What will it return if an empty string is passed?

2022-02-15 10:58 UTC, uzairr commented on course_discovery/apps/course_metadata/data_loaders/utils.py
> +    index_if_exist = lowercase.find('duration')
good catch 👍 
partially it is correct but in the later one there is a possibility of a nested tag so the mentioned codeline would catch that use case i.e.
For example: `<p><strong>Duration:</strong> 10 weeks (excluding orientation)<br>\r\n</p><p>An effective digital marketing strategy\r\n</p>`

2022-02-15 12:33 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/utils.py
> +    if not is_base64(data):
this code pattern here seems confusing, if data is not base64, why would the base64 decode be called against it. Renaming would do the job here.

2022-02-15 12:34 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/tests/mock_data.py
> +    '<p>An effective digital marketing strategy\r\n</p>'
Like Azan said, we can have more scenarios here for test, just to be safe.

2022-02-15 12:34 UTC, DawoudSheraz approved these changes
follow-up nits, otherwise 👍🏽

2022-02-15 12:55 UTC, azanbinzahid commented
Please make sure to test on local publisher about various inputs.

2022-02-16 08:05 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/utils.py
> +    return data
As discussed internally, the duration information will remain within the HTML. We can remove this method.

2022-02-16 08:06 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/utils.py
> +    if not is_base64(data):
When testing on the local, this check caused issues when data was equal to empty string. Either we can hide the function behind if check or update this method.

2022-02-16 08:06 UTC, DawoudSheraz requested changes
Added comments/small changes to be done based on discussions.

2022-02-18 12:42 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/utils.py
> +    return False
Seems strange that we are decoding and encoding the value to check if the data is base64. If the data is not base64, the exception will be raised and that has not been handled in the caller function. This util method might not be needed if the decode method is wrapped in try/catch in the caller function and return original value if the decode fails.

2022-02-22 14:00 UTC, azanbinzahid approved these changes

2022-02-22 14:43 UTC, DawoudSheraz approved these changes

2022-02-22 14:44 UTC, merged