ECOM-5660 Add logo image url override for organizations
openedx/course-discovery pull request #330
Opened 2016-09-15 19:48 UTC by MatthewPiatetsky

@edx/ecommerce

2016-09-15 19:54 UTC, clintonb commented
Why is this necessary? Organization data currently comes from Drupal.

2016-09-15 19:54 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +            'small': (200, 101),
Are you sure this is the only variable we need? What about also store the original?

2016-09-15 19:55 UTC, schenedx reviewed
Is there a plan to also update the dataloader so we store the original logo image for the organization from the source?

2016-09-15 20:07 UTC, clintonb requested changes
The issue here is that we are pulling organization data from Drupal and LMS (Organizations API).

LMS: https://courses.edx.org/api/organizations/v0/organizations/MITx/
Drupal: https://prod-edx-mktg-edit.edx.org/sites/default/files/school/image/banner/mit_logo_200x101_0.png

The change you want is to the data loaders, and determining precedence of the data. Adding an override is not correct.

2016-09-15 22:38 UTC, MatthewPiatetsky commented
@edx/ecommerce I've updated the PR per @clintonb's comment. 
New github is being very confusing because you still see old comments like Simon's comment even though they are not relevant anymore.

2016-09-15 22:40 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            defaults['name'] = body['name']
```python
defaults.update({
  'name': body['name'],
  ...
})
```

2016-09-15 22:41 UTC, clintonb approved these changes

2016-09-16 13:11 UTC, schenedx approved these changes
👍 
I agree. My comment clearly is a relic in the past!

2016-09-16 14:55 UTC, merged