ECOM-5635 allow filter of unpublished course_runs
openedx/course-discovery pull request #331
Opened 2016-09-15 19:52 UTC by schenedx

@edx/ecommerce Please review

With this change, if the course_run is unpublished, we can filter it out in the program details API endpoint

2016-09-15 19:52 UTC, schenedx commented
The place in drupal that uses this querystring filter: https://github.com/edx/edx-mktg/pull/927

2016-09-15 21:40 UTC, mikedikan commented on course_discovery/apps/api/v1/views.py
> +            - name: published_course_runs_only
what is the - before name?

2016-09-15 21:41 UTC, mikedikan commented on course_discovery/apps/api/serializers.py
> +                'published_course_runs_only': self.context.get('published_course_runs_only', False)
can we put a trailing comma here?

2016-09-15 21:42 UTC, mikedikan requested changes
Comment and a question (minor)

2016-09-15 21:43 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +from course_discovery.apps.course_metadata.choices import CourseRunStatus
Alphabetize.

2016-09-15 21:44 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +    def test_with_published_only_querystring(self, course_run_status, published_course_runs_only):
Add a docstring explaining what you're testing.

2016-09-15 21:46 UTC, clintonb commented on course_discovery/apps/api/v1/views.py
> +            - name: published_course_runs_only
See http://django-rest-swagger.readthedocs.io/en/stable-0.3.x/yaml.html.

2016-09-15 21:46 UTC, clintonb approved these changes

2016-09-15 22:20 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +        context['published_course_runs_only'] = bool(int(self.request.GET.get('published_course_runs_only', 0)))
@schenedx you don't need to cast this to a boolean. Casting to an int is sufficient for your needs here.

2016-09-15 22:20 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
> +                'published_course_runs_only': self.context.get('published_course_runs_only', False)
You also don't need to provide a default here. The default default (None) is sufficient.

2016-09-15 22:20 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
> +        if self.context.get('published_course_runs_only', False):
Again, no explicit default is necessary.

2016-09-15 22:21 UTC, rlucioni reviewed
I left a little feedback for simplifying your code.

2016-09-15 22:28 UTC, rlucioni commented
@schenedx while working in this, did you consider extending https://github.com/edx/course-discovery/blob/master/course_discovery/apps/api/filters.py#L86? We use this filter mixin for our other querystring-based filtering, and it would make sense to keep it consistent, if possible.

2016-09-15 22:37 UTC, rlucioni commented
@schenedx I spoke with @clintonb briefly about the above; ignore me. The filters I was referring to are only useful for filtering the base queryset.

2016-09-16 00:45 UTC, rock345 commented on course_discovery/apps/api/serializers.py
> +from course_discovery.apps.course_metadata.choices import CourseRunStatus
Clinton please indicated if this is a nit or not!

2016-09-16 13:48 UTC, schenedx commented
@rlucioni @mikedikan Address all your comments. Please take another look.

2016-09-16 14:15 UTC, rlucioni approved these changes
LGTM

2016-09-16 14:21 UTC, merged