temp: add paid and unpaid executive course variants
openedx/course-discovery pull request #3310
Opened 2022-03-02 13:45 UTC by uzairr

2022-03-03 12:57 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +        VERIFIED, PROFESSIONAL, EXECUTIVE_EDUCATION, PAID_EXECUTIVE_EDUCATION, UNPAID_EXECUTIVE_EDUCATION
unpaid mode is not an entitlement mode

2022-03-03 12:58 UTC, DawoudSheraz requested changes
added comment to address

2022-03-07 13:46 UTC, DawoudSheraz approved these changes
Please add the link to Enrollment track Confluence page in the PR description so the reviewers can better understand the usage of this addition.

2022-03-07 14:32 UTC, azanbinzahid approved these changes

2022-03-08 07:23 UTC, waheedahmed reviewed
What is the difference between `EXECUTIVE_EDUCATION` and these new types? Is this just a rename and are we going to remove the old one?

2022-03-08 07:40 UTC, uzairr commented
@waheedahmed `EXECUTIVE_EDUCATION` mode was already part of the edX ecosystem but it was not been used for a longer time. The new types are the separate product lines which are created to import 2U courses and has nothing to do with it.

2022-03-08 07:59 UTC, waheedahmed approved these changes

2022-03-08 11:05 UTC, DawoudSheraz commented
Merging the PR because the test failure on mysql80 is a known flaky test. mysql80 is not a required check either. Re-running takes about 1 hours minimum which is wasting a lot of time.

2022-03-08 11:06 UTC, merged