feat: add organization alias course wide
openedx/course-discovery pull request #3318
Opened 2022-03-08 06:04 UTC by uzairr

To create a hierarchy inside an organization in a way that the
sub-departments of it are also reflected on course about page.

PROD-2719

2022-03-08 09:47 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +    organization_name_override = models.CharField(max_length=255, default=None, blank=True)
default=None seems weird.

2022-03-14 10:54 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +    organization_name_override = models.CharField(max_length=255, blank=True)
well, it is not name. short code to be precise. let's be consistent with the naming conventions here.

2022-03-14 18:06 UTC, DawoudSheraz commented on course_discovery/apps/api/serializers.py
> +    logo_image_override = ImageField(read_only=True, source='logo_image_override_url')
please update fied names in model and serializer:
- It is organization short code override, not name
- What logo override? Please specify that.

2022-03-14 18:07 UTC, DawoudSheraz commented on course_discovery/apps/api/serializers.py
> +    logo_image_override = ImageField(read_only=True, source='logo_image_override_url')
Why is logo field read_only? How will it work with API during making non-GET operations?

2022-03-14 18:08 UTC, DawoudSheraz reviewed
- Missing unit tets
- Field name updates

2022-03-15 13:06 UTC, DawoudSheraz reviewed
Nits and small updates

2022-03-15 13:06 UTC, DawoudSheraz commented on course_discovery/apps/api/serializers.py
> +    organization_shortcode = serializers.CharField(required=False)
nit: organization_short_code_override

2022-03-15 13:06 UTC, DawoudSheraz commented on course_discovery/apps/api/serializers.py
> +    org_logo_override = ImageField(required=False, source='org_logo_override_url')
nit: organization_logo_override

2022-03-15 13:06 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +    organization_shortcode = models.CharField(max_length=255, blank=True)
why is null=True not added here?

2022-03-15 13:06 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +    organization_shortcode = models.CharField(max_length=255, blank=True)
field name nits here too

2022-03-15 13:06 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +        upload_to=UploadToFieldNamePath(populate_from='name', path='media/course/org/logo_override/'),
what does `name` signify here?

2022-03-15 13:06 UTC, DawoudSheraz commented on course_discovery/apps/api/tests/test_serializers.py
> +        course.org_logo_override = course.image
can we have another image here, even though it is test, just to keep the differentation?

2022-03-15 13:06 UTC, DawoudSheraz commented on course_discovery/apps/api/tests/test_serializers.py
> +        assert serializer.data['org_logo_override'].get('src') is not None
assert against the src value

2022-03-15 13:06 UTC, DawoudSheraz commented on course_discovery/apps/api/serializers.py
> +            'skills', 'organization_shortcode', 'org_logo_override',
does including url here auto-downloads the object when saving?

2022-03-15 14:25 UTC, uzairr commented on course_discovery/apps/course_metadata/models.py
> +    organization_shortcode = models.CharField(max_length=255, blank=True)
making null and blank to `True` would create the two different situations for empty string so enabling one of them will avoid that scenario.

2022-03-15 14:33 UTC, uzairr commented on course_discovery/apps/course_metadata/models.py
> +        upload_to=UploadToFieldNamePath(populate_from='name', path='media/course/org/logo_override/'),
it is using `name` the same way as `uuid` for creating uniqueness.

2022-03-15 20:32 UTC, azanbinzahid requested changes
Please add views tests as well to test update API call via publisher. Precisely here: `course_discovery/apps/api/v1/tests/test_views/test_courses.py `

2022-03-15 20:32 UTC, azanbinzahid commented on course_discovery/apps/api/serializers.py
> +    organization_shortcode = serializers.CharField(required=False)
Do we need to add this explicitly in serializer? take an example of `full_description` field.

2022-03-15 20:32 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/models.py
> +    organization_shortcode = models.CharField(max_length=255, blank=True)
I guess it will be `null=False, blank=True` now?

2022-03-18 13:10 UTC, azanbinzahid reviewed
Looks good, just missing api/view tests. They will verify if API updates are working as expected or not.

2022-03-18 13:10 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/tests/factories.py
> +    organization_logo_override = factory.django.ImageField()
Do we also need `organization_short_code_override` in factory?

2022-03-18 17:33 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/factories.py
> +    organization_logo_override = factory.django.ImageField()
+1 here, this should be added in factory too.

2022-03-22 07:24 UTC, DawoudSheraz commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.assertDictEqual(response.data, self.serialize_course(course))
serialize_course call can be moved above and stored in a variable. Also, add an assertion explicitly against logo override

2022-03-22 07:26 UTC, DawoudSheraz reviewed
going to test on local before the approval

2022-03-22 07:47 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +        },
The logo field in Organization model does not have any variations defined there. We can keep the behavior consistent here, unless there is a reason for this.

2022-03-22 07:48 UTC, DawoudSheraz approved these changes
Tested locally on Firebox using Edit request feature to patch the data. The changes are working.

2022-03-22 11:14 UTC, azanbinzahid approved these changes

2022-03-22 11:14 UTC, azanbinzahid commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        course = CourseFactory()
If you are making a course from factory, you may already have these fields populated from factory and this patch req will update those.

2022-03-22 12:59 UTC, DawoudSheraz approved these changes

2022-03-24 12:36 UTC, azanbinzahid approved these changes

2022-03-24 14:18 UTC, waheedahmed approved these changes

2022-03-24 14:27 UTC, merged