refactor: make handling of optional fields flexible in CSV loader
openedx/course-discovery pull request #3342
Opened 2022-03-21 14:11 UTC by DawoudSheraz

### [PROD-2751](https://openedx.atlassian.net/browse/PROD-2751)

### Description

- Handle optional fields for CSV loader in a flexible way as to not break the flow if the data dict or column is not present in CSV
- If the data is present for an optional field, it would work as before. 
- Allow the override code field to be blank in the serializer.

2022-03-24 10:17 UTC, uzairr approved these changes
ensure the green build please

2022-03-24 13:49 UTC, azanbinzahid requested changes
I don't like the overall idea of `get_dict_key_value` utility function given a builtin method already exist. Please comment if it has additional benefits.

2022-03-24 13:49 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            'additional_information': self.get_dict_key_value(data, 'additional_information'),
`data.get(key, '')` was also fine.

2022-03-24 13:49 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            'external_identifier': data['external_identifier'],
`dict/key` function here?

2022-03-24 13:49 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +    def get_dict_key_value(self, data, key, value=''):
change value to `default_value`

2022-03-24 13:49 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +    def get_dict_key_value(self, data, key, value=''):
What if some fields accept `None` instead of `''`?

2022-03-24 13:55 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            'external_identifier': data['external_identifier'],
These are required fields for 2U Product lines.

2022-03-24 13:55 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +    def get_dict_key_value(self, data, key, value=''):
This is the default value. The caller can always provide a different value if '' is not the default value for a field.

2022-03-24 13:57 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            'additional_information': self.get_dict_key_value(data, 'additional_information'),
Well, the default value is set to '' for many string/html fields. Dictionary's get(key) returns None if the value is not found. That's why the util function was added to avoid repeating dict.get(key, '') pattern.

2022-04-01 07:24 UTC, azanbinzahid approved these changes

2022-04-01 12:48 UTC, merged