feat: add product type field
openedx/course-discovery pull request #3351
Opened 2022-03-31 07:41 UTC by uzairr

Add product type field in additional metadata model to distinguish
bootcamp and exEd courses.

PROD-2749

2022-04-06 12:27 UTC, DawoudSheraz reviewed
Looks good from my end, although a ddt test to verify the product types for different courses is missing.

2022-04-08 18:16 UTC, DawoudSheraz commented on course_discovery/apps/api/serializers.py
> +        return None
type is always present on the course. Did you run into a scenario where it was not the case?

2022-04-11 06:58 UTC, uzairr commented on course_discovery/apps/api/serializers.py
> +        return None
No i didn't, it is just a safer way to access a custom written attribute!

2022-04-11 08:28 UTC, DawoudSheraz commented on course_discovery/apps/api/serializers.py
> +        return None
Well, I would say there is no need for that, since the course will always have a course type.

2022-04-11 08:29 UTC, DawoudSheraz commented on course_discovery/apps/api/serializers.py
> +    course_type = serializers.SerializerMethodField()
Make this a read-only field.

2022-04-12 07:40 UTC, azanbinzahid requested changes
Please add field presence test in api test course views.

2022-04-12 07:40 UTC, azanbinzahid commented on course_discovery/apps/api/serializers.py
> +    course_type = serializers.SerializerMethodField()
How this addition will return type slug? What if we use `SlugRelated` field?

2022-04-12 23:15 UTC, uzairr commented on course_discovery/apps/api/serializers.py
> +    course_type = serializers.SerializerMethodField()
by default it is read-only: https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L1874

2022-04-13 07:41 UTC, azanbinzahid approved these changes

2022-04-13 07:59 UTC, DawoudSheraz approved these changes
- Once the build is green
- Update PR description to include the updated changes

2022-04-13 13:38 UTC, merged