Add title boosting for search queries
openedx/course-discovery pull request #340
Opened 2016-09-19 18:34 UTC by bderusha

Added title boosting the haystack way http://django-haystack.readthedocs.io/en/v2.5.0/boost.html?highlight=boosting#field-boost

@MatthewPiatetsky please have a look

2016-09-19 19:47 UTC, clintonb commented on course_discovery/apps/api/v1/views.py
> +    def filter_queryset(self, queryset):
Move to `filter_facet_queryset` above so that all children of `BaseHaystackViewSet` can take advantage of this functionality.

2016-09-19 19:48 UTC, clintonb commented on course_discovery/apps/course_metadata/search_indexes.py
> +TITLE_FIELD_BOOST = 25.0
Add a comment and link to docs explaining what this does, units, etc. For example, is this additive or multiplicative?

2016-09-19 19:50 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    score = serializers.SerializerMethodField()
Why is this necessary? Does DRF not simply render `result.score` as a float?

2016-09-19 19:50 UTC, clintonb approved these changes

2016-09-28 18:41 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +    score = serializers.SerializerMethodField()
talked to @bderusha, he said to remove score

2016-09-28 18:41 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/search_indexes.py
> +TITLE_FIELD_BOOST = 25.0
added comment

2016-09-28 18:49 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views.py
> +    def filter_queryset(self, queryset):
is the change I made what you meant?

2016-09-28 19:11 UTC, MatthewPiatetsky commented
@clintonb are your comments addressed?  
@edx/ecommerce bump

2016-09-28 19:25 UTC, clintonb approved these changes

2016-09-28 19:25 UTC, clintonb commented on course_discovery/apps/course_metadata/search_indexes.py
> +# http://django-haystack.readthedocs.io/en/v2.4.1/boost.html#field-boost
Nit: We use v2.5.0

2016-09-28 19:25 UTC, clintonb commented on course_discovery/apps/course_metadata/search_indexes.py
> +TITLE_FIELD_BOOST = 25.0
What's the justification for this multiplier?

2016-09-28 19:26 UTC, rlucioni requested changes

2016-09-28 19:26 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +        q = self.request.GET.get('q')
Preferred DRF style is to use `query_params` over `GET` (e.g., `q = self.request.query_params.get('q')`). http://www.django-rest-framework.org/api-guide/requests/#query_params

2016-09-28 19:26 UTC, rlucioni commented on course_discovery/apps/course_metadata/search_indexes.py
> +TITLE_FIELD_BOOST = 25.0
Has thought been given to making this configurable via the Django admin? Is this something we might want to tune without re-deploying the application?

2016-09-28 19:38 UTC, bderusha commented on course_discovery/apps/course_metadata/search_indexes.py
> +TITLE_FIELD_BOOST = 25.0
It requires a server restart to take affect since it is loaded when the class is loaded, so I didn't think a django-admin config was appropriate.  Do we have a way to kick the service like that in production if we did make it configurable?

2016-09-28 19:41 UTC, rlucioni commented on course_discovery/apps/course_metadata/search_indexes.py
> +TITLE_FIELD_BOOST = 25.0
@bderusha I see what you mean. I don't think so. Making this dynamic looks like it could be more involved than I thought.

2016-09-28 19:46 UTC, bderusha commented on course_discovery/apps/course_metadata/search_indexes.py
> +TITLE_FIELD_BOOST = 25.0
For our purposes the actual numerical value here doesn't matter so much as it's relation to the total amount of functional boosting that can be applied.

I chose this number after playing around with a dataset.  The max boost received from our boosting functions is ~6, having a boost of 25 for title gives most relevant titles a score higher than our other boosting (which is what we want).  But it's all relative.  If we altered our boosting functions to have a max score of 10 we would probably want to bump this number.  if we added a new function we can adjust the weights of all of them to keep the total at 6 and not require a deploy.

2016-09-28 19:50 UTC, clintonb commented on course_discovery/apps/course_metadata/search_indexes.py
> +TITLE_FIELD_BOOST = 25.0
@bderusha cool. Is this information documented someplace? If not, would you document it someplace, please?

2016-09-28 19:56 UTC, rlucioni commented on course_discovery/apps/course_metadata/search_indexes.py
> +TITLE_FIELD_BOOST = 25.0
A comment would be nice!

2016-09-28 19:59 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/search_indexes.py
> +TITLE_FIELD_BOOST = 25.0
added more to the comment

2016-09-28 20:07 UTC, rlucioni approved these changes

2016-10-03 18:51 UTC, merged