feat: include courses and course runs in learner pathway api
openedx/course-discovery pull request #3471
Opened 2022-06-10 08:45 UTC by sameenfatima78

JIRA: https://2u-internal.atlassian.net/browse/ENT-5916

Courses and Course Runs included in Steps:

<img width="1226" alt="Screenshot 2022-06-10 at 1 43 48 PM" src="https://user-images.githubusercontent.com/55431213/173027560-1370f7ee-fa64-4e65-bb01-5f70a007c7c1.png">

Courses and Course Runs included in Programs:
<img width="1047" alt="Screenshot 2022-06-10 at 1 43 57 PM" src="https://user-images.githubusercontent.com/55431213/173027599-47e372f9-4da2-47cd-b19f-f3bac2c9fdc6.png">

2022-06-10 10:18 UTC, muhammad-ammar commented on course_discovery/apps/learner_pathway/api/serializers.py
> +    courses = serializers.SerializerMethodField()
can we use `LearnerPathwayCourseMinimalSerializer` here instead of `serializers.SerializerMethodField`?

2022-06-10 10:39 UTC, sameenfatima78 commented on course_discovery/apps/learner_pathway/api/serializers.py
> +    courses = serializers.SerializerMethodField()
I also initially had planned to use it but that serializer expects to receive a `LearnerPathwayCourse` object. In our case, for Programs, we will have a `Course` object. Due to the clash in field sources (`key` instead of `course.key`), we cannot use this serializer.

2022-06-10 11:11 UTC, HammadAhmadWaqas requested changes

2022-06-10 11:11 UTC, HammadAhmadWaqas commented on course_discovery/apps/learner_pathway/api/serializers.py
> +    def get_courses(self, step):
Why we are calling it as `step`? its object of  LearnerPathwayProgram.

2022-06-10 11:11 UTC, HammadAhmadWaqas commented on course_discovery/apps/learner_pathway/api/serializers.py
> +        if program.courses:
program.courses here must be a queryset manager, it was always returning true, 
Also I don't think we need this check here as we are looping over program.courses.all()

2022-06-10 11:11 UTC, HammadAhmadWaqas commented on course_discovery/apps/learner_pathway/api/serializers.py
> +                if course.course_runs:
same problem here, 
1. its a manager
2. we don't need this check here as we are querying course_runs in next line.

2022-06-10 11:11 UTC, HammadAhmadWaqas commented on course_discovery/apps/learner_pathway/api/serializers.py
> +        return []
I think we can move this whole logic to LearnerPathwayProgram class. This way it would be reuseable.

2022-06-10 11:11 UTC, HammadAhmadWaqas commented on course_discovery/apps/learner_pathway/tests/test_serializer.py
> +                        'course_runs': [],
It would be great if we add test for course_runs

2022-06-10 11:11 UTC, HammadAhmadWaqas commented on course_discovery/apps/learner_pathway/api/v1/views.py
> +        query = Q(course__key__in=course_keys) | Q(course__course_runs__key__in=course_keys)
Can we add init test to test this logic?

2022-06-13 16:52 UTC, sameenfatima78 commented on course_discovery/apps/learner_pathway/api/serializers.py
> +    def get_courses(self, step):
fixed.

2022-06-13 16:52 UTC, sameenfatima78 commented on course_discovery/apps/learner_pathway/api/serializers.py
> +        if program.courses:
fixed

2022-06-13 16:52 UTC, sameenfatima78 commented on course_discovery/apps/learner_pathway/api/serializers.py
> +                if course.course_runs:
fixed

2022-06-13 16:52 UTC, sameenfatima78 commented on course_discovery/apps/learner_pathway/api/serializers.py
> +        return []
done

2022-06-13 16:53 UTC, sameenfatima78 commented on course_discovery/apps/learner_pathway/tests/test_serializer.py
> +                        'course_runs': [],
done

2022-06-13 16:53 UTC, sameenfatima78 commented on course_discovery/apps/learner_pathway/api/v1/views.py
> +        query = Q(course__key__in=course_keys) | Q(course__course_runs__key__in=course_keys)
done

2022-06-13 21:09 UTC, zamanafzal approved these changes

2022-06-14 07:00 UTC, HammadAhmadWaqas approved these changes
LGTM

2022-06-14 07:28 UTC, muhammad-ammar approved these changes

2022-06-14 07:33 UTC, merged