Don't read yet please
openedx/course-discovery pull request #349
Opened 2016-09-21 19:13 UTC by MatthewPiatetsky

![test](https://cloud.githubusercontent.com/assets/5958221/18725343/e7fe5c60-800d-11e6-92ff-4b20bcc50a43.gif)

2016-09-22 12:59 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +        setInterval(function(){
This is not a good approach. If you are having issues with listening for moving events another approach would be to add a button alongside the input which would submit the order.

2016-09-22 13:01 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +        setInterval(function(){
Could you not listen to the select2 ```change``` event (https://select2.github.io/options.html#events)?

2016-09-22 13:06 UTC, MatthewPiatetsky commented on course_discovery/static/js/sortable_select.js
> +        setInterval(function(){
You mean like an additional button?  
I think we should try to find an approach that doesn't sacrifice user experience, since we could reuse this elsewhere.  
I will try the select2 change event, though I don't know if the reordering triggers it

2016-09-22 13:09 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +        setInterval(function(){
I agree that the button is not ideal UX, but it would be preferable to having setInterval continuously running on the page and we could be more confident that all changes have been applied. The event listener approach is the preferred option.

2016-09-22 13:12 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +        setInterval(function(){
If the select2 change event doesn't work, the jQuery UI sortable one should http://api.jqueryui.com/sortable/#event-change

2016-09-22 13:29 UTC, MatthewPiatetsky commented on course_discovery/static/js/sortable_select.js
> +        setInterval(function(){
yup we both found the jquery UI event, that was the way to go!

2016-09-22 14:03 UTC, clintonb commented
The `SortedManyToMany` field has a default widget. While not great, it is usable. Did you consider it?

2016-09-22 14:07 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    courses = SortedManyToManyField(Course, related_name='programs')
Unless you modify the sorting in the serializer, this won't have any effect.

2016-09-22 14:43 UTC, MatthewPiatetsky commented
@clintonb the default widget allows you to filter, but you can't sort while filtered because the other options don't show up.  
When not filtered you have a huge dropdown of every course, which makes it very difficult to use

2016-09-22 14:45 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    courses = SortedManyToManyField(Course, related_name='programs')
good point, thanks!

2016-09-22 15:07 UTC, rlucioni commented on course_discovery/apps/course_metadata/admin.py
> +        js = ('//code.jquery.com/ui/1.10.3/jquery-ui.js',
What about installing this with npm or bower? I don't think we want to load this directly from jquery.com like this.

2016-09-22 15:09 UTC, rlucioni commented on course_discovery/apps/course_metadata/forms.py
> +        from dal import autocomplete
What's the motivation behind nesting this import and the one above?

2016-09-22 15:20 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    courses = SortedManyToManyField(Course, related_name='programs')
Talked with Lauren and Jasper, we went with a checkbox which determines whether ordering by date is used

2016-09-22 15:21 UTC, clintonb commented
The default widget allows you to filter and sort (drag-and-drop). The only downside to the default widget is the fact that when you filter, selected items appear in their original position. It might be simpler to make selected items appear at the beginning/end of the list than to write an entirely new widget.

Regardless of the approach, we should consider contributing this back to https://github.com/gregmuellegger/django-sortedm2m.

2016-09-22 15:24 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    courses = SortedManyToManyField(Course, related_name='programs')
(facepalm) Who else was involved in this decision? Has it been documented? This will lead to issues with folks wondering why pages have different sorting orders. We should avoid introducing alternate behaviors in this manner.

2016-09-22 15:38 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    courses = SortedManyToManyField(Course, related_name='programs')
Lauren and Jasper, if you disagree you can talk to them

2016-09-22 15:53 UTC, MatthewPiatetsky commented
@clintonb true, if the default widget was modified so that the selected options appeared at the top that would be usable, but imo the select2 option is more user friendly and consistent with our current experience.
This is what the default widget would behave like by default. 
We could certainly contribute back, though that would introduce a dependency on the django autocomplete light library which they might not want

(This is what the widget looks like by default for reference)
![old_widget3](https://cloud.githubusercontent.com/assets/5958221/18755700/2d1e0b9e-80bb-11e6-8eaf-d8dd031096e7.gif)

2016-09-22 17:45 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +        for (var j = 0; j < selectOptions.length; j++) {
All variables should be declared at the top of the function

2016-09-22 17:46 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +        for (var j = 0; j < selectOptions.length; j++) {
It is more performant to assign the length value to a variable instead of calculating it on each iteration.

2016-09-22 17:48 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +                           selectOptions[j].text + "</option>\n"
For consistency please continue using single quotes here, as used earlier in the file.

2016-09-22 17:48 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +        $(".field-courses ul.select2-selection__rendered").sortable({
For consistency please continue using single quotes here, as used earlier in the file.

2016-09-22 17:48 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +        var domSelector = ".field-courses .select2-selection--multiple";
For consistency please continue using single quotes here, as used earlier in the file.

2016-09-22 17:48 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/admin.py
> +        js = ('//code.jquery.com/ui/1.10.3/jquery-ui.js',
fixed

2016-09-22 17:48 UTC, AlasdairSwan requested changes

2016-09-22 17:48 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +        $(selectOptionsSelector).html(items.join(""));
For consistency please continue using single quotes here, as used earlier in the file.

2016-09-22 17:49 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/forms.py
> +        from dal import autocomplete
one above doesn't need to be nested, this one does because the Mixin is overriding functionality in the library, like you can see in the comment.  
Not sure what the right approach is here, perhaps to also open a PR to that library?

2016-09-22 18:21 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +    })
Missing ```;```

2016-09-22 18:21 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +    })
Missing ```;```

2016-09-22 18:22 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +                items.push('<option selected=\"selected\" value=\"' + selectOptions[j].id + '\">' +
Because you are using single quotes you don't need to escape the double quotes, i.e.  you can just do this;
```items.push('<option selected="selected" value="' + selectOptions[j].id + '">'```

2016-09-22 18:23 UTC, AlasdairSwan commented on course_discovery/static/js/sortable_select.js
> +                           selectOptions[j].text + '</option>\n'
Why the ```\n```?

2016-09-22 18:24 UTC, AlasdairSwan requested changes
Just some minor updates I missed on my first pass then should be good to merge.

2016-09-22 18:42 UTC, MatthewPiatetsky commented on course_discovery/static/js/sortable_select.js
> +                           selectOptions[j].text + '</option>\n'
This is generating html and in the existing html the options are on a new line, though I realized it would make more sense for this to be in the join.  
It would still work without the \n but the HTML would be different and less readable

2016-09-22 18:45 UTC, AlasdairSwan approved these changes
:shipit: 👍

2016-09-22 19:28 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
> +            courses, course_runs = list(program.courses.all()), list(program.course_runs)
Do you need to force queryset evaluation here?

2016-09-22 19:36 UTC, rlucioni commented on course_discovery/apps/course_metadata/admin.py
> +        js = ('bower_components/jquery-ui/ui/minified/jquery-ui.min.js',
@clintonb is this the right way to include these assets, or do they get copied somewhere else during static asset collection?

2016-09-22 19:36 UTC, rlucioni commented on course_discovery/apps/course_metadata/forms.py
> +    widgets.QuerySetSelectMixin = QuerySetSelectMixin2
Nitpick: add an empty line above this to make it a little more readable.

2016-09-22 19:51 UTC, rlucioni commented on course_discovery/apps/course_metadata/models.py
> +    courses = SortedManyToManyField(Course, related_name='programs')
Does this change require a migration?

2016-09-22 19:57 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +            courses, course_runs = list(program.courses.all()), list(program.course_runs)
it looks like they are being passed as context to a serializer which is expecting the type to be list

2016-09-22 19:58 UTC, rlucioni commented
@MatthewPiatetsky how does this affect query counts for the program list endpoint? Is there a performance cost for this new sorting?

2016-09-22 20:01 UTC, clintonb commented on course_discovery/apps/course_metadata/admin.py
> +        js = ('bower_components/jquery-ui/ui/minified/jquery-ui.min.js',
This is fine for now.

2016-09-22 20:33 UTC, MatthewPiatetsky commented
@rlucioni I added some tests, it seems like the number of queries is the same

2016-09-22 21:35 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
> +            courses, course_runs = list(program.courses.all()), list(program.course_runs)
Have you tried passing the querysets through to see what happens? Just curious.

2016-09-22 21:37 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        program = self.create_program()
I don't think this test is doing what you want, since you've redefined `program`. The one being retrieved isn't the one with start date sorting disabled.

2016-09-22 21:37 UTC, rlucioni commented on course_discovery/apps/course_metadata/models.py
> +    courses = SortedManyToManyField(Course, related_name='programs')
I see them. They don't need to be two separate migrations. If you remove them both then recreate migrations, you'll only have to add one.

2016-09-23 13:25 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    courses = SortedManyToManyField(Course, related_name='programs')
merged into one

2016-09-23 13:26 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +            courses, course_runs = list(program.courses.all()), list(program.course_runs)
seems like it works, nvm, they just needed to be iterable

2016-09-23 13:26 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/forms.py
> +    widgets.QuerySetSelectMixin = QuerySetSelectMixin2
done

2016-09-23 13:27 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        program = self.create_program()
Good point, now that I've fixed the test, it is actually 55 queries rather than 89 (which seems good?).
Or should I be concerned?

2016-09-26 15:28 UTC, rlucioni commented on course_discovery/apps/course_metadata/forms.py
> +            ordering = 'CASE %s END' % clauses
Nitpick: this is old-style string formatting. Please stick to new-style (i.e., `.format()`).

2016-09-26 15:28 UTC, rlucioni commented on course_discovery/apps/course_metadata/forms.py
> +            ).extra(select={'ordering': ordering}, order_by=('ordering',))
order_by shouldn't require a tuple for a single arg.

2016-09-26 15:33 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with self.assertNumQueries(55):
Is this unit test really reflective of the behavior we'd expect in production? You're using a program with one course and no ordering overrides. If the program instead had, say, three courses and an explicitly-defined ordering, how do things change?

Relatedly, have you had a chance to use the debug toolbar to understand what this does to query counts when using the program list endpoint? I don't think the unit test is necessarily sufficient. We don't want to introduce queries that scale linearly in the size of the response. @bderusha or I can help you if you have questions.

2016-09-26 15:51 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/forms.py
> +            ordering = 'CASE %s END' % clauses
changed to format

2016-09-26 15:51 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/forms.py
> +            ).extra(select={'ordering': ordering}, order_by=('ordering',))
I think it does here, if I make it a string I get an error loading the page

2016-09-26 15:52 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with self.assertNumQueries(55):
I added two tests with the sorting toggled on and off and 3 courses, is that better?  
For the django toolbar, I loaded this page that I was using for testing on master, and then on my branch with the sorting button checked and unchecked. I got 24 SQL queries each time
http://localhost:8008/api/v1/programs/03a198ae-98c2-4a10-ab99-2c5ec423abb5/

2016-09-26 16:00 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with self.assertNumQueries(55):
@MatthewPiatetsky did that course you were using to test with have courses and an explicit ordering defined? You should also be checking the list view (/api/v1/programs/) for several programs. I don't know if the unit test is sufficient because I don't know how the sorted m2m handles sorting. As it is, you don't seem to be defining any sort order in the tests.

2016-09-26 17:45 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with self.assertNumQueries(55):
@rlucioni With this field type, I believe the courses are always stored in a sorted order (the one defined in the widget before you click save). I was testing the number of queries here rather than the sorting, but I can explicitly verify the order as well (it will be the order of the courses in the list)

2016-09-26 21:44 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with self.assertNumQueries(55):
I fixed the tests on this PR and the number of queries did not change in my local testing, so I think I've addressed your comments

2016-09-27 17:30 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        program = ProgramFactory(courses=course_list, order_courses_by_start_date=False)
Instead of duplicating this test code, use ddt to provide both Boolean arguments to one test method.

2016-09-27 17:31 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        self.assertEqual(course_list, list(program.courses.all()))  # pylint: disable=no-member
Nitpick: As before, converting to a list like this shouldn't be necessary. Querysets are iterable.

2016-09-27 17:31 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with self.assertNumQueries(55):
@MatthewPiatetsky let's chat to close the loop on this one. I may not have been clear enough earlier.

2016-09-27 18:13 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        program = ProgramFactory(courses=course_list, order_courses_by_start_date=False)
good point, thanks!

2016-09-27 18:14 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        self.assertEqual(course_list, list(program.courses.all()))  # pylint: disable=no-member
I believe assertEqual does a direct equality comparison and a list is a different type from a queryset. assertEqual doesn't return true if I don't evaluate the queryset to a list here. (i tried it)

2016-09-27 18:35 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        self.assertEqual(course_list, list(program.courses.all()))  # pylint: disable=no-member
Good to know, thanks.

2016-09-27 19:58 UTC, rlucioni approved these changes

2016-09-27 20:04 UTC, merged