Added property to Programs to denote 2U Degree
openedx/course-discovery pull request #3502
Opened 2022-06-28 17:02 UTC by aheykamp2u

https://2u-internal.atlassian.net/browse/WS-2986

Description:
This PR adds a property to Program models and Algolia Proxy Models which denotes whether a Program is a 2U degree or not. This property is temporary and will go away when we consolidate edX and 2u degrees in prospectus views in a future ticket.

Reason: 
This field will greatly simplify code in Prospectus around 2u Degrees and excluding them from parts of the Prospectus experience.

Changes:
Added is_2u_degree field to models.py and algolia_models.py. There are changes to the program serializer as well to make this field available in the API.

2022-06-28 17:02 UTC, openedx-webhooks commented
Thanks for the pull request, @aheykamp2u!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-06-29 19:26 UTC, azanbinzahid requested changes
- to update ticket link in description
- to add test in `api/v1/tests/test_views/test_programs`
- to add this filed into list_filters in admin view

2022-06-29 19:26 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/models.py
> +
Do we have a reason for adding this in `Program` model rather than `Degree`? If yes, can we rename it to use `program` suffix instead of `degree` corresponding to the model it is in?

2022-07-06 20:17 UTC, aheykamp2u commented on course_discovery/apps/course_metadata/models.py
> +
The issue I see here is that we query for programs in prospectus, not degrees directly. We need some way to differentiate them when we're working with a collection of programs, or to easily filter them out when we query the programs.

This field is also temporary. In the future, we're going to be treating degrees from edx or from 2U the same once we unify them under one view.

Given that, would you still want me to put this on the degree model itself?

2022-07-06 21:34 UTC, azanbinzahid commented
quick tip: you can run quality tests locally with `pylint` and `pycodestyle --config=`, also follow conventional commit message to pass PR tests

2022-07-14 10:35 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/algolia_models.py
> +        return hasattr(self, 'degree') and hasattr(self.degree, 'additional_metadata')
Why isn't the property from the Program model used here? Why is there a need to re-write the check within the Algolia model

2022-07-14 10:37 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +
While this is a temporary field, I also think that we can either rename the property or move the property to Degree. Moving the property to Degree will mean having an additional check in Algolia to find if the Program object has an associated Degree.

2022-07-14 10:38 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/search_indexes/documents/program.py
> +    is_2u_degree = fields.BooleanField()
did you verify the index is working as expected after running update_index on local?

2022-07-14 10:39 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_algolia_models.py
> +        program = AlgoliaProxyProgramFactory(partner=self.__class__.edxPartner)
while I see `self.__class__.edxPartner` has been used in existing tests, any ideas why is it like that?

2022-07-14 10:41 UTC, DawoudSheraz reviewed
- left a few comments
- The commit type should be temp, not feat, since this field is meant to be a temporary addition.

2022-07-18 15:19 UTC, aheykamp2u commented on course_discovery/apps/course_metadata/models.py
> +
If I renamed it to 'is_2u_degree_program', would that be acceptable?

2022-07-18 17:37 UTC, aheykamp2u commented on course_discovery/apps/course_metadata/algolia_models.py
> +        return hasattr(self, 'degree') and hasattr(self.degree, 'additional_metadata')
When I use the is_2u_degree model property in the algolia model, it causes a recursive error in the tests.

2022-07-19 06:38 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +
Yes, that would work.

2022-07-19 06:39 UTC, DawoudSheraz approved these changes
A rename nit to address before the merge.

2022-07-20 06:49 UTC, DawoudSheraz commented
Please squash the commits.

2022-07-21 05:24 UTC, DawoudSheraz commented
Azan requested changes that have been resolved. However, Github is blocking merge until requested changes are addressed. I will be using admin rights to merge this PR.

2022-07-21 05:24 UTC, merged