fix: "search-all-list" api endpoint and api tests
openedx/course-discovery pull request #3518
Opened 2022-07-07 12:08 UTC by bilaltahir21

Jira: [ENT-5898](https://2u-internal.atlassian.net/jira/software/c/projects/ENT/boards/629?modal=detail&selectedIssue=ENT-5898)

2022-07-07 12:08 UTC, openedx-webhooks commented
Thanks for the pull request, @bilaltahir21!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-07-13 11:06 UTC, openedx-webhooks commented
@bilaltahir21 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/3518&entry.1484655318=https://github.com/bilaltahir21&entry.752974735=2022-07-07+12:08&entry.1917517419=2022-07-13+11:06&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->

2022-07-13 11:40 UTC, HammadAhmadWaqas requested changes

2022-07-13 11:40 UTC, HammadAhmadWaqas commented on course_discovery/apps/course_metadata/search_indexes/serializers/course.py
> +        ignored_params = []
As we are using it anymore, Can we remove this variable?

2022-07-13 11:40 UTC, HammadAhmadWaqas commented on course_discovery/apps/course_metadata/search_indexes/serializers/course.py
> +            if should_include_course_run(course_run, dict(request.GET), exclude_expired)
Query params are being sent with post data. so `request.GET` might not work here.

2022-07-14 10:05 UTC, bilaltahir21 commented on course_discovery/apps/course_metadata/search_indexes/serializers/course.py
> +        ignored_params = []
Removed.

2022-07-14 10:06 UTC, bilaltahir21 commented on course_discovery/apps/course_metadata/search_indexes/serializers/course.py
> +            if should_include_course_run(course_run, dict(request.GET), exclude_expired)
Replaced it with "query_params" and added another test for post request.

2022-07-18 09:05 UTC, HammadAhmadWaqas commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def test_results_filtered_by_exclude_expired_course_run_post(self):
Can we use `ddt` here?

2022-07-18 10:41 UTC, bilaltahir21 commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def test_results_filtered_by_exclude_expired_course_run_post(self):
Used DDT and changed serializer too.

2022-07-18 14:11 UTC, HammadAhmadWaqas approved these changes

2022-07-18 14:11 UTC, HammadAhmadWaqas commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        response = None
Why we need to define response=None here?

2022-07-18 14:26 UTC, bilaltahir21 commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        response = None
It is because we need `response` parameter outside the scope of `if` statement.

2022-07-19 09:20 UTC, openedx-webhooks commented
@bilaltahir21 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/3518&entry.1484655318=https://github.com/bilaltahir21&entry.752974735=2022-07-07+12:08&entry.1917517419=2022-07-19+09:20&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->

2022-07-20 19:41 UTC, natabene commented
@bilaltahir21 I am working with HelpDesk to get you added to the list. Sorry for the inconvenience.

2022-07-27 16:27 UTC, natabene commented
@bilaltahir21 You CLA is all set. Now please edit the title and save (like add a space) and this will trigger the check to re-run and it will turn green. Can you please also remove the open-source-contribution label for me?

2022-07-27 16:38 UTC, bilaltahir21 commented
@natabene thank you very much 🙂 And I don't have access to add or remove labels from the pull request.

2022-07-29 03:15 UTC, sameenfatima78 approved these changes

2022-08-01 11:31 UTC, uzairr approved these changes
please add the implementation details with context in PR description. 👍

2022-08-02 12:49 UTC, merged