feat: [WS-3083] add value per click to courses and programs
openedx/course-discovery pull request #3531
Opened 2022-07-20 13:25 UTC by srwang

Adds value per click to courses and programs to allow algolia to weigh search results by this field.

See https://2u-internal.atlassian.net/browse/WS-3083

2022-07-20 14:35 UTC, bseverino requested changes

2022-07-20 14:35 UTC, bseverino commented on course_discovery/apps/course_metadata/models.py
> +    value_per_click = models.IntegerField(null=True, blank=True)
based on the AC can you split these into two fields each, one for US and one for international?

2022-07-20 14:35 UTC, bseverino commented on course_discovery/apps/course_metadata/index.py
> +                          'desc(recent_enrollment_count)', 'desc(value_per_click)']
I think we want to hold off on using this field for custom ranking just yet - we just want to pass it in without doing anything with it until [WS-3137](https://2u-internal.atlassian.net/browse/WS-3137)

2022-07-20 16:25 UTC, bseverino approved these changes

2022-07-26 05:54 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +    value_per_click_international = models.IntegerField(null=True, blank=True, default=0)
Both PR and ticket do not specify why is there a need for two fields? Add help text explaining these fields.

2022-07-26 05:56 UTC, DawoudSheraz reviewed
- Added a question for more clarity on the changes being added in this PR
- Make sure the PR is only adding one migration file. Squash your migrations or recreate them in a single file.
- Make PR descriptive to explain why are the fields being added
- Is there no use of these fields in ElasticSearch documents and ES document APIs?

2022-07-26 15:41 UTC, srwang commented
> * Added a question for more clarity on the changes being added in this PR
> * Make sure the PR is only adding one migration file. Squash your migrations or recreate them in a single file.
> * Make PR descriptive to explain why are the fields being added
> * Is there no use of these fields in ElasticSearch documents and ES document APIs?

Thanks Darwould. 

I've made these changes.

Nope, these fields will not be used in the ES APIs.

2022-07-28 04:40 UTC, DawoudSheraz reviewed
The changes look good. A question: I was seeing another PR by @bseverino , https://github.com/openedx/course-discovery/pull/3530, which is adding value per lead fields to the products. Why can't the lead and value fields be transformed into a separate model and that model is then linked to Program and Courses? The intent of the fields seems similar to me and it would make sense to add these related fields in a separate model.

2022-07-28 06:01 UTC, uzairr approved these changes
looks pretty straight forward! approved from my side once @DawoudSheraz concern is addressed!

2022-07-28 17:42 UTC, bseverino commented
Thank you both! We've condensed these PRs into one, and split the fields into a separate model as per @DawoudSheraz's suggestion: https://github.com/openedx/course-discovery/pull/3530

2022-10-19 05:51 UTC, closed without merging