feat: add a signal on update degree
openedx/course-discovery pull request #3539
Opened 2022-07-28 08:26 UTC by Ali-D-Akbar

[PROD-2902](https://2u-internal.atlassian.net/browse/PROD-2902)
Adds a signal to be used in [taxonomy-connector](https://github.com/openedx/taxonomy-connector/pull/94)

Steps to verify:
1. set `FIRE_UPDATE_DEGREE_SKILLS_SIGNAL` to True
2. clone [taxonomy-connector](https://github.com/openedx/taxonomy-connector/) in `src` folder and checkout [this branch](https://github.com/openedx/taxonomy-connector/pull/94) in taxonomy-connector
3. in discovery shell, run `pip install -e ../../../src/taxonomy-connector/`
4. Run degree ingestion for a csv file once then change `overview` field and run the ingestion again
5. Notice a logged message similar to this: `'Signal fired to update degree skills. Degree: [%s]'`

2022-07-28 08:58 UTC, AliAdnanSohail requested changes

2022-07-28 08:58 UTC, AliAdnanSohail commented on course_discovery/apps/course_metadata/data_loaders/degrees_loader.py
> +        degree = Degree.objects.filter(marketing_slug=data['slug'], overview=data['overview'])
Rather we trigger signal in data loader, can we move this to model level? So if Degree is changed from any other place like Admin or publisher. It will trigger this signal from there as well? 
We can use `post_save` callback on model level, so if this model is updated from anywhere it will trigger this signal

May be this link will help you
https://docs.djangoproject.com/en/4.0/ref/signals/#post-save

2022-07-28 09:03 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/data_loaders/degrees_loader.py
> +        degree = Degree.objects.filter(marketing_slug=data['slug'], overview=data['overview'])
Okay, I'll do that instead.

2022-07-29 06:08 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/degrees_loader.py
> +        degree = Degree.objects.filter(marketing_slug=data['slug'], overview=data['overview'])
Yes, I second Ali Adnan's comment here. The data loader is used for a limited set of data. This solution should be for Programs model as a whole.

2022-08-01 08:14 UTC, AliAdnanSohail approved these changes

2022-08-01 08:16 UTC, AliAdnanSohail approved these changes
Wait for the green build, then it seems good to me

2022-08-02 07:12 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +                    previous_obj and not previous_obj.is_active:
This condition can be simplified or converted into a util method for readability purposes.

2022-08-02 07:13 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    @override_switch('publish_program_to_marketing_site', True)
Why should this switch be on?

2022-08-02 07:14 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_models.py
> +            assert mock_signal_send.call_count == 1
MarketingSitePublisher is not impacting the signal because the signal is sent in a different execution block. I am not sure why this has been done.

2022-08-02 07:15 UTC, DawoudSheraz reviewed
A few questions to address.

2022-08-02 08:30 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    @override_switch('publish_program_to_marketing_site', True)
This is needed for publishing on marketing.

2022-08-02 08:30 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/tests/test_models.py
> +            assert mock_signal_send.call_count == 1
https://github.com/openedx/course-discovery/blob/a2f571d2db3e858378b5b6c66df65b45a8ee98c3/course_discovery/apps/course_metadata/models.py#L2752

2022-08-02 08:32 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/models.py
> +                    previous_obj and not previous_obj.is_active:
Please let me know if there's a better way to write this condition.

2022-08-03 10:06 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +                    previous_obj and not previous_obj.is_active:
Why is there a need to check on the old object? Isn't setting + is_active enough?

2022-08-03 10:08 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    @override_switch('publish_program_to_marketing_site', True)
The skill update signal code block does not seem to come under `publish_program_to_marketing_site` flow? Why is this needed then? Can't it be kept as off?

2022-08-03 10:09 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    @override_switch('publish_program_to_marketing_site', True)
Oh, nevermind, got my answer in the upcoming comments.

2022-08-03 10:11 UTC, DawoudSheraz approved these changes
- nit comment/question
- Rebase before merge.

2022-08-03 11:02 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/models.py
> +                    previous_obj and not previous_obj.is_active:
We're checking it so that if the the program status is changed in the recent save. Otherwise, it will always trigger the signal in case program status is active/published. We want to trigger from unpublish to publish state only.

2022-08-03 11:07 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +                    previous_obj and not previous_obj.is_active:
So let's say the overview field of a program is updated. What will happen then?

2022-08-03 11:26 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/models.py
> +                    previous_obj and not previous_obj.is_active:
It won't send the signal. Aren't we just updating Program upon publish only according to the ADR? 
`When a program is published in Discovery, emit a signal indicating the program skills must be updated.`

2022-08-03 19:24 UTC, merged

2022-08-04 04:47 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +                    previous_obj and not previous_obj.is_active:
Well, this was not meant literally only on publish. For the courses, if the setting is on and if any skill-related field is changed, the course skill update signal is re-sent. Please check https://github.com/openedx/course-discovery/blob/master/course_discovery/apps/api/v1/views/courses.py#L399-L404. You will need a similar mechanism here.