fix: fixing incorrect course keys
openedx/course-discovery pull request #3543
Opened 2022-08-02 13:41 UTC by kiram15

Our PM made a mistake when fetching the course keys, here are the updated ones along with error handling.

2022-08-02 21:43 UTC, Ali-D-Akbar requested changes
As I said in the previous PR, rather than using the constant file, it may be better to use a config model to store the file through django admin. In my suggested approach, you wouldn't have to create another PR to update the course keys data.

This way, we'll need another PR to remove the constants file.

2022-08-02 21:43 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/management/commands/backfill_enterprise_inclusion.py
> +from ast import Or
What is this import used for?

2022-10-26 01:51 UTC, mphilbrick211 commented
@azanbinzahid would you mind taking a look at these changes? Thank you!

2022-10-26 13:27 UTC, azanbinzahid approved these changes

2022-11-01 10:23 UTC, DawoudSheraz commented
@kiram15 Hi, is this still needed? Thanks

2022-12-07 22:08 UTC, mphilbrick211 commented
Hi @kiram15 - just following up on this. Please let us know if you plan to proceed with this pull request. Thanks!

2022-12-21 19:45 UTC, closed without merging