feat: add exec_ed_2u variant_id field to AdditionalMetadata, and inge…
openedx/course-discovery pull request #3544
Opened 2022-08-02 21:43 UTC by christopappas

…stion flow

2022-08-08 19:28 UTC, azanbinzahid requested changes

2022-08-08 19:28 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/management/commands/tests/test_populate_executive_education_data_csv.py
> +        assert data_row['Variant Id'] == 'test_id'
do we expect this in UUID format?

2022-08-08 19:28 UTC, azanbinzahid commented on course_discovery/apps/course_metadata/migrations/0290_additionalmetadata_variant_id.py
> +        ('course_metadata', '0289_degree_loader_configuration'),
we have new migrations after this, so please rebase and add new migration.

2022-08-10 07:48 UTC, azanbinzahid approved these changes
Reminder to re base before merge.

2022-08-10 12:52 UTC, DawoudSheraz approved these changes

2022-08-10 15:00 UTC, merged