feat: make created available for learner pathways in search/all
openedx/course-discovery pull request #3572
Opened 2022-08-24 16:10 UTC by sameenfatima78

2022-08-25 08:29 UTC, sameenfatima78 reviewed
@DawoudSheraz Hi, can you please review these changes. Thanks

2022-08-25 08:30 UTC, sameenfatima78 commented
@HammadAhmadWaqas @saleem-latif I can't seem to tag you for review so posting it here.

2022-08-25 08:51 UTC, saleem-latif approved these changes

2022-08-25 09:23 UTC, HammadAhmadWaqas requested changes

2022-08-25 09:23 UTC, HammadAhmadWaqas commented on course_discovery/apps/course_metadata/search_indexes/documents/learner_pathway.py
> +    created = fields.DateField()
I think we are not using this field, We are using created directly from object, So this line can be removed

2022-08-25 13:24 UTC, sameenfatima78 commented on course_discovery/apps/course_metadata/search_indexes/documents/learner_pathway.py
> +    created = fields.DateField()
Actually we need this field otherwise we end up with this error on `search/all` endpoint: 
 
<img width="461" alt="Screenshot 2022-08-25 at 6 19 03 PM" src="https://user-images.githubusercontent.com/55431213/186676492-9d638238-d853-4c25-9b4f-f583edd2b883.png">

2022-08-25 14:12 UTC, ansabgillani approved these changes

2022-08-25 18:30 UTC, Ali-D-Akbar approved these changes
Not a blocker but Can we have a named migration instead?

2022-08-26 10:00 UTC, DawoudSheraz approved these changes

2022-08-26 10:11 UTC, HammadAhmadWaqas approved these changes

2022-08-26 12:48 UTC, merged