Ecom 5435 django ses
openedx/course-discovery pull request #360
Opened 2016-09-29 11:14 UTC by awais786

Integrating django-ses.
Updating email backend configuration.

2016-09-29 11:46 UTC, awais786 commented
https://github.com/edx/configuration/pull/3399

2016-09-29 11:46 UTC, awais786 commented
@bderusha @clintonb Please review this PR.

2016-09-29 12:47 UTC, clintonb requested changes

2016-09-29 12:47 UTC, clintonb commented on requirements/base.txt
> +django-ses==0.8.1
I'm seeing no code that requires this outside of production. If this is intended to be used locally, please add some example settings to `private.py.example`; otherwise, move this to `production.txt`.

2016-09-29 12:47 UTC, clintonb commented on course_discovery/settings/production.py
> +
This is an unnecessary addition. The comment belongs adjacent to the code it is commenting.

2016-09-29 12:47 UTC, clintonb commented on course_discovery/settings/production.py
>  # This may be overridden by the YAML in PROGRAMS_CFG, but it should be here as a default.
Correct PROGRAMS_CFG to DISCOVERY_CFG.

2016-09-29 13:03 UTC, clintonb commented on course_discovery/settings/private.py.example
> +
Add some comments.

2016-09-29 13:04 UTC, clintonb commented on course_discovery/settings/private.py.example
> +
Link to the django-ses docs, and explain what all this is for. Put yourself in the shoes of an OpenEdX user who may have never used SES before

2016-09-29 13:16 UTC, clintonb commented
Also, please provide a more informative commit message than the ticket number. This article has a good guideline: http://chris.beams.io/posts/git-commit/.

2016-09-29 20:17 UTC, awais786 commented
@bderusha @clintonb Please review this PR again.

2016-09-29 20:51 UTC, clintonb approved these changes

2016-09-30 16:05 UTC, bderusha requested changes

2016-09-30 16:05 UTC, bderusha commented on course_discovery/settings/private.py.example
> +AWS_ACCESS_KEY_ID='replace-me'
NIT: consistent spaces around the `=` sign

2016-09-30 16:05 UTC, bderusha commented on course_discovery/settings/private.py.example
> +AWS_SECRET_ACCESS_KEY='replace-me'
and here

2016-09-30 16:05 UTC, bderusha commented on course_discovery/settings/production.py
> +    vars().update(EMAIL_CONFIG)
Added a comment here: https://github.com/edx/configuration/pull/3399

Might impact this work if we decide to change it.

2016-10-05 15:20 UTC, bderusha requested changes

2016-10-05 15:20 UTC, bderusha commented on course_discovery/settings/private.py.example
> +documentation https://github.com/django-ses/django-ses.
Add `#` to make this a comment

2016-10-05 15:20 UTC, bderusha commented on requirements/base.txt
> +django-ses==0.8.1
@awais786 Is django-ses the best choice for local dev email?  My gut says no and that this should live in production.txt only.  Thoughts?

2016-10-05 19:47 UTC, awais786 commented
@bderusha Please review again.

2016-10-06 16:45 UTC, bderusha approved these changes

2016-10-06 16:45 UTC, bderusha commented on course_discovery/settings/private.py.example
> +For default email backend following settings require
Add `#` to make this a comment when it's copied to a .py file

2016-10-06 16:45 UTC, bderusha commented on course_discovery/settings/private.py.example
> +For django-ses following credentials require for sending emails. For more details check the
Add `#` to make this a comment when it's copied to a .py file

2016-10-19 07:17 UTC, merged