Awais786/ecom 5496
openedx/course-discovery pull request #362
Opened 2016-09-30 09:25 UTC by awais786

WIP:

Adding new page for adding publisher course.

2016-10-04 12:36 UTC, awais786 commented
![screencapture-127-0-0-1-8009-publisher-courses-new-1475584478558](https://cloud.githubusercontent.com/assets/445320/19074322/0f5f69ac-8a59-11e6-885b-b7b2549b286c.png)

2016-10-04 12:48 UTC, waheedahmed requested changes
First pass complete, let me know when its ready for review again.

2016-10-04 12:48 UTC, waheedahmed commented on course_discovery/apps/publisher/urls.py
> +    url(r'^course/(?P<pk>\d+)/view/$', views.ReadOnlyView.as_view(), name='publisher_courses_readonly'),
```courses/``` instead of ```course/```.

2016-10-04 12:48 UTC, waheedahmed commented on course_discovery/static/sass/publisher/course_detail.scss
> +.layout-full {
Change it to ```publisher-layout``` and add it to required places, please do not modify UXPL classes.

2016-10-04 12:48 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +    <h2 class="layout-title">{% trans "Base information" %}</h2>
Add ```publisher-layout``` class here.

2016-10-04 12:48 UTC, waheedahmed commented on course_discovery/templates/publisher/course_form_edit.html
> +    <div class="layout-full layout">
```publisher-layout``` and also here.

2016-10-04 12:48 UTC, waheedahmed commented on course_discovery/templates/publisher/view_course_form.html
> +<div class="layout-full layout">
And here ```publisher-layout```.

2016-10-04 12:54 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +<div class="layout-full layout">
Also here ```publisher-layout```.

2016-10-04 12:55 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +<div class="layout-full layout">
And here `publisher-layout`

2016-10-04 12:55 UTC, waheedahmed commented on course_discovery/templates/publisher/course_form_edit.html
> +    <div class="layout-full layout">
Add class ```publisher-layout```.

2016-10-04 12:55 UTC, waheedahmed commented on course_discovery/templates/publisher/view_course_form.html
> +    <div class="layout-full layout">
Add class ```publisher-layout```.

2016-10-04 13:48 UTC, awais786 commented
@bderusha You can review the PR.

2016-10-05 07:42 UTC, waheedahmed commented on course_discovery/apps/publisher/forms.py
> +    contacted_partner_manager = forms.BooleanField(
According to wireframes ```target_content``` should also be a ```RadioSelect```.

2016-10-05 08:27 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +                    run_course.save()
Add `changed_by` to course run also.

2016-10-05 08:28 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +                    seat.save()
And add ```changed_by``` in seat too.

2016-10-05 08:59 UTC, awais786 commented
@waheedahmed its all done.

2016-10-05 09:24 UTC, waheedahmed approved these changes

2016-10-05 09:32 UTC, waheedahmed approved these changes
Just minor changes required, otherwise looks good

2016-10-05 09:32 UTC, waheedahmed commented on course_discovery/templates/publisher/view_course_form.html
> +        <h2 class="layout-title">Course information</h2>
Add translation.

2016-10-05 09:32 UTC, waheedahmed commented on course_discovery/templates/publisher/view_course_form.html
> +                <div class="field-title">INSTITUTION INFORMATION</div>
Add ```trans```.

2016-10-05 09:32 UTC, waheedahmed commented on course_discovery/templates/publisher/view_course_form.html
> +    <h2 class="layout-title">Base information</h2>
Add ```trans```.

2016-10-05 09:32 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +    <h4 class="hd-4">{% trans "Course Form" %}</h4>
Remove this h4, nothing in wireframes like this.

2016-10-05 09:32 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +            <h4 class="hd-4">{% trans "Course Form" %}</h4>
Remove this too, nothing in wireframes here.

2016-10-05 09:32 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +{% trans "Course Form" %}
Change it to "New Course"

2016-10-05 09:32 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        messages.error(request, _('Pass the valid values.'))
Please fill all required fields.

2016-10-05 10:46 UTC, awais786 commented
@bderusha Please review.

2016-10-05 14:25 UTC, awais786 commented
@ahsan-ul-haq Please review this PR.

2016-10-05 15:11 UTC, bderusha requested changes

2016-10-05 15:11 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +        self.fields['expected_learnings'].label = 'Expected Learnings'
Any reason why all of these are implemented here instead of on the model?

2016-10-05 15:11 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +        widget=forms.RadioSelect(choices=((1, "Yes"), (0, "No"))), initial=0, required=False
translation

2016-10-05 15:11 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +        widget=forms.RadioSelect(choices=((1, "Yes"), (0, "No"))), initial=0, required=False
translation

2016-10-05 15:11 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +        self.fields['expected_learnings'].label = 'Expected Learnings'
Also, regardless of where these live they need to be marked for translation

2016-10-05 15:11 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +        self.fields['target_content'].label = 'Priority content'
Same question as above.  Why here and not on the model? Also add translation

2016-10-05 15:11 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +            self.add_error('price', 'Only honor/audit seats can be without price.')
translation

2016-10-05 15:11 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +            self.add_error('price', 'Only honor/audit seats can be without price.')
also please add an error test case

2016-10-05 15:11 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    institution = models.ForeignKey(
Is this necessary?  We should be able to get this from the permission assignment.  Something like this? http://stackoverflow.com/questions/378303/how-to-get-a-list-of-all-users-with-a-specific-permission-group-in-django

2016-10-05 15:11 UTC, bderusha commented on course_discovery/static/sass/publisher/course_detail.scss
> +      margin-right: 10px;
RTL support

2016-10-05 15:11 UTC, bderusha commented on course_discovery/templates/publisher/add_course_form.html
> +                            {% trans "If the course falls in a sequence, our titling convention is: Course Title: Subtitle" %}
These three lines will be very strange to translate.  Please make one block and include line breaks dynamically

2016-10-05 15:11 UTC, bderusha commented on course_discovery/templates/publisher/add_course_form.html
> +        <div class="field-title">{% trans "FULL DESCRIPTION" %}</div>
Why all caps?

2016-10-05 15:11 UTC, bderusha commented on course_discovery/templates/publisher/add_course_form.html
> +</div>
please indent these properly

2016-10-05 15:12 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +    institution = models.ForeignKey(
We discussed this yesterday that if a user select some thing from drop-down then we should store it in db.

2016-10-05 15:15 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +        self.fields['expected_learnings'].label = 'Expected Learnings'
If i add them in model then need to create a migration. So just to avoid the migration i did them in forms.
For translations i will update them.

what's your recommendation for these label ?

2016-10-05 18:40 UTC, awais786 commented on course_discovery/templates/publisher/add_course_form.html
> +                            {% trans "If the course falls in a sequence, our titling convention is: Course Title: Subtitle" %}
In fact I mixed up lines. Now I have translate each line individually and it looks meaningful.

2016-10-05 18:53 UTC, awais786 commented on course_discovery/templates/publisher/add_course_form.html
> +        <div class="field-title">{% trans "FULL DESCRIPTION" %}</div>
Its a block that's why. In mockup blocks are all caps.

2016-10-05 19:35 UTC, awais786 commented
@bderusha I have implemented all changes. 
I have update the strings in model and add the migration.
Add the test cases for price.

2016-10-06 12:05 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +    institution = models.ForeignKey(
I have removed this field.

2016-10-06 12:08 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +    institution = models.ForeignKey(
Instead I am using guaridan method to get the group. 
[get_groups_with_perms](http://django-guardian.readthedocs.io/en/stable/api/guardian.shortcuts.html#get-groups-with-perms)

2016-10-06 12:38 UTC, awais786 commented
@bderusha I have removed the institution field from model.  Instead I have created the property for course to get the group using guardian method. It's ready to merge now.

2016-10-06 14:58 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +        self.fields['expected_learnings'].label = 'Expected Learnings'
I don't care where they live so long as we're consistent.  Either have all labels live here or all labels live on the model, but not both.

2016-10-06 16:19 UTC, bderusha approved these changes

2016-10-06 16:19 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +from guardian.shortcuts import assign_perm
please move this back.  `guardian` is a 3rd party import and should be group with the middle group

2016-10-07 07:42 UTC, merged