feat: add management command to populate course_length
openedx/course-discovery pull request #3637
Opened 2022-10-07 12:57 UTC by muneebGH

2022-10-10 05:07 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +Django management command to populate course_length in Course model by fetching data from snowflake.
will this be one-time-only job?

2022-10-10 09:16 UTC, HammadAhmadWaqas requested changes
Can we add unit tests here as well?

2022-10-10 09:16 UTC, HammadAhmadWaqas commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +                    course.save()
`if should_commit` check should be just on the save call.

2022-10-10 09:16 UTC, HammadAhmadWaqas commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +        LOGGER.info('[Populate Course Length] Execution completed.')
can we add statics here as well to know how many courses have been successfully updated and how many failed, maybe adding failed course ids would also be helpful in future debugging.

These statistics should come with the -no-commit option as well.

2022-10-10 10:13 UTC, irfanuddinahmad commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +Django management command to populate course_length in Course model by fetching data from snowflake.
This will be run on a regular cadence ... once or twice a month

2022-10-11 22:12 UTC, muneebGH commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +                    course.save()
done

2022-10-11 22:12 UTC, muneebGH commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +        LOGGER.info('[Populate Course Length] Execution completed.')
done

2022-10-11 22:15 UTC, muneebGH commented
Some tests will be failing because there are some assertions in my test cases which checks property added in [this PR](https://github.com/openedx/course-discovery/pull/3631). So until that is not merged, these wont pass, and after that, hopefully they will pass automatically.

2022-10-12 07:39 UTC, saleem-latif approved these changes
Once questions, other than that looks Good 👍

2022-10-12 07:39 UTC, saleem-latif commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +                if should_commit:
Do we want to add a log message if `should_commit` is `False`?

2022-10-12 07:43 UTC, ansabgillani commented
Can you add some running data based on the queries in the description? Hard time understanding them.

2022-10-12 09:36 UTC, muhammad-ammar approved these changes
Great Work!

2022-10-12 10:54 UTC, ansabgillani approved these changes

2022-10-12 11:46 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +QUERY = '''
nit: please move this query to the constants.py file.

2022-10-12 11:48 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +QUERY = '''
Also, is a query the only way to fetch the information? Is there no other interface to fetch the needed information?

2022-10-12 11:48 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +            password=settings.SNOWFLAKE_SERVICE_USER_PASSWORD,
Do these values exist in stage and prod settings for discovery?

2022-10-12 11:50 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +                course = Course.objects.get(uuid=course_uuid)
In Discovery, there are 2 versions of a course; draft and non-draft. Both of them would need an update to keep the data in sync. The object manager on Course object has been overridden to return non-draft versions. You would want to use `Course.everything.filter(uuid=uuid)` to get both versions of the course.

2022-10-12 11:52 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +                course = Course.objects.get(uuid=course_uuid)
Ref: https://github.com/openedx/course-discovery/blob/master/course_discovery/apps/course_metadata/models.py#L1060

2022-10-12 11:53 UTC, DawoudSheraz commented on requirements/constraints.txt
> +# pinning because of dependency conflict while installing snowflake-connector-python
nit: Please add which parent dependency is causing the conflicts

2022-10-12 11:53 UTC, DawoudSheraz reviewed
Left some comments to address.

2022-10-12 15:15 UTC, muneebGH commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +            password=settings.SNOWFLAKE_SERVICE_USER_PASSWORD,
yes they do

2022-10-13 10:42 UTC, muneebGH commented on requirements/constraints.txt
> +# pinning because of dependency conflict while installing snowflake-connector-python
done

2022-10-13 10:43 UTC, muneebGH commented on requirements/constraints.txt
> +# pinning because of dependency conflict while installing snowflake-connector-python
https://github.com/snowflakedb/snowflake-connector-python/issues/1259

this is the exact issue and i also have got approval from @UsamaSadiq for pinning, as done in edx-platform as well.

2022-10-13 10:51 UTC, muneebGH commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +QUERY = '''
afaik i dont think there is a way to do this using snowflake-python-connector, @muhammad-ammar can you please confirm?

2022-10-13 11:10 UTC, muneebGH commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +                course = Course.objects.get(uuid=course_uuid)
done

2022-10-13 11:14 UTC, muneebGH commented on course_discovery/apps/course_metadata/management/commands/populate_course_length.py
> +                if should_commit:
done

2022-10-13 13:32 UTC, muneebGH commented
@DawoudSheraz I have incorporated the feedback, please review

2022-10-14 05:36 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/management/test_populate_course_length.py
> +                log.records[3].message
nit: With LogCapture, you can do the following for checking the presence of logs:
```
log_capture.check_present(
(LOGGER_NAME, log_level, log_string),
.....
)
```

2022-10-14 05:36 UTC, DawoudSheraz approved these changes

2022-10-14 05:36 UTC, DawoudSheraz commented
- Please squash the commits

2022-10-17 10:33 UTC, muneebGH commented on course_discovery/apps/course_metadata/tests/management/test_populate_course_length.py
> +                log.records[3].message
done

2022-10-17 11:55 UTC, muneebGH commented
@DawoudSheraz I have made the requested changes and squashed the commits, please merge the PR if it looks good. 🤞

2022-10-17 12:05 UTC, merged