feat: add configuration for certificate program type
openedx/course-discovery pull request #3649
Opened 2022-10-20 16:36 UTC by DawoudSheraz

### [PROD-3001](https://2u-internal.atlassian.net/browse/PROD-3001)

### Description

- Add Certificate program type configuration basis

2022-10-21 10:43 UTC, AliAdnanSohail requested changes

2022-10-21 10:43 UTC, AliAdnanSohail commented on course_discovery/apps/api/v1/views/affiliates.py
> +                program_type = ProgramType.objects.get(slug=program_type_slug)
Can we do this something like

```
excluded_program_slugs = [ProgramType.MASTERS, ProgramType.BACHELORS, ProgramType.DOCTORATE, ProgramType.LICENSE, ProgramType.CERTIFICATE]

excluded_program_types = ProgramType.objects.get(slug__in=excluded_program_slugs)
```

It can reduce number of DB queries

2022-10-21 10:45 UTC, DawoudSheraz commented on course_discovery/apps/api/v1/views/affiliates.py
> +                program_type = ProgramType.objects.get(slug=program_type_slug)
Yeah, thanks for pointing it out. Although It will be objects.filter, not get().

2022-10-21 12:51 UTC, AliAdnanSohail approved these changes

2022-10-24 14:52 UTC, azanbinzahid approved these changes

2022-10-24 21:35 UTC, uzairr approved these changes

2022-10-27 13:14 UTC, merged