Added header/footer.
openedx/course-discovery pull request #367
Opened 2016-10-04 07:54 UTC by waheedahmed

[ECOM-5284] (https://openedx.atlassian.net/browse/ECOM-5284)

As a Publisher user, I would like to see a consistent edX Header/Footer as I navigate throughout the Publisher experience. 

See sub-task for Header/Footer details.

Assumptions:
There's a separate story for profile/setting changes
Visual design (skinning) will be provided and to be integrated later

**Acceptance Criteria:**

1. Validate the header/footer matches the wireframe.
2. Validate the links on the header/footer work.
3. Validate the header/footer is persistent throughout every page as navigating through the Publisher.

![screencapture-localhost-8004-publisher-course_runs-1475567322324](https://cloud.githubusercontent.com/assets/2851134/19066223/a2a309a8-8a31-11e6-8cf1-9a869cf0cf09.png)

2016-10-04 09:29 UTC, waheedahmed commented
@awais786 @bderusha Please review.

2016-10-05 10:36 UTC, awais786 commented
👍

2016-10-05 14:20 UTC, ahsan-ul-haq commented on course_discovery/static/sass/publisher/course_detail.scss
> +                    float: right;
use float(right)

2016-10-05 14:20 UTC, ahsan-ul-haq commented on course_discovery/static/sass/publisher/course_detail.scss
> +                    margin-right: 14.28571%;
use `@include margin-right(14.28571%);`

2016-10-05 14:20 UTC, ahsan-ul-haq commented on course_discovery/static/sass/publisher/course_detail.scss
> +                        margin-right: 20px;
use `@include margin-right(20px);`

2016-10-05 14:20 UTC, ahsan-ul-haq commented on course_discovery/static/sass/publisher/course_detail.scss
> +                    float: left;
use `@include float(left)`

2016-10-05 14:20 UTC, ahsan-ul-haq commented on course_discovery/templates/footer.html
> +            <p>&copy; {{ current_year }} <a data-rel="edx.org" href="https://wwww.edx.org" rel="external">{{ platform_name }}</a>.</p>
I don't think href should be hardcoded here.

2016-10-05 15:16 UTC, bderusha requested changes
Code looks fine.  I have questions about the content.  How is this supposed to work for openedx? white label?

2016-10-05 15:16 UTC, bderusha commented on course_discovery/templates/footer.html
> +                <a data-rel="edx.org" href="https://www.edx.org/edx-terms-service">{% trans "Terms of Service" %}</a>
we can't hardcode edx links.  These need to be dynamic

2016-10-05 15:16 UTC, bderusha commented on course_discovery/templates/footer.html
> +                <a data-rel="edx.org" href="https://www.edx.org/edx-privacy-policy">{% trans "Privacy Policy" %}</a>
same here

2016-10-05 15:16 UTC, bderusha commented on course_discovery/templates/footer.html
> +                        EdX, Open edX, Studio, and the edX and Open edX logos are registered trademarks or trademarks of {{link_start}}edX Inc.{{link_end}}
What about white label?  How does this work?  @mattdrayer ?

2016-10-05 15:16 UTC, bderusha commented on course_discovery/templates/footer.html
> +            <p>&copy; {{ current_year }} <a data-rel="edx.org" href="https://wwww.edx.org" rel="external">{{ platform_name }}</a>.</p>
Can't hardcode `www.edx.org` here.  What if the PLATFORM is not edx?

2016-10-05 15:28 UTC, mattdrayer commented on course_discovery/templates/footer.html
> +                        EdX, Open edX, Studio, and the edX and Open edX logos are registered trademarks or trademarks of {{link_start}}edX Inc.{{link_end}}
@douglashall should take a look as well -- in the LMS code we have a setting called PLATFORM_NAME which we use to cover certain presentation scenarios.

2016-10-05 15:36 UTC, douglashall commented on course_discovery/templates/footer.html
> +                        EdX, Open edX, Studio, and the edX and Open edX logos are registered trademarks or trademarks of {{link_start}}edX Inc.{{link_end}}
In LMS we have a settings override mechanism which makes use of a `SiteConfiguration` model which allows us to override settings like `PLATFORM_NAME`. We would like to get to a point where there is a python package that contains multitenant related utilities like this. We are not there yet. For the time being you could implement a similar settings override mechanism in this service.

2016-10-05 15:46 UTC, clintonb commented on course_discovery/static/sass/publisher/course_detail.scss
> +                        margin-right: 20px;
Why the use of `@include` for basic CSS properties?

2016-10-05 16:28 UTC, mattdrayer commented on course_discovery/templates/footer.html
> +                        EdX, Open edX, Studio, and the edX and Open edX logos are registered trademarks or trademarks of {{link_start}}edX Inc.{{link_end}}
Does it make sense to leverage the Partner model here?  That's essentially the multi-tenant concept in this service:  https://github.com/edx/course-discovery/blob/master/course_discovery/apps/core/models.py#L59

2016-10-05 16:30 UTC, douglashall commented on course_discovery/templates/footer.html
> +                        EdX, Open edX, Studio, and the edX and Open edX logos are registered trademarks or trademarks of {{link_start}}edX Inc.{{link_end}}
I'd prefer to stick with the Site/SiteConfiguration paradigm to solve the specific problem that is being raised here.

2016-10-06 09:14 UTC, ahsan-ul-haq commented on course_discovery/static/sass/publisher/course_detail.scss
> +                        margin-right: 20px;
I think we need to provide rtl support if we don't need that now then its fine with me.

2016-10-06 11:36 UTC, waheedahmed commented on course_discovery/templates/footer.html
> +            <p>&copy; {{ current_year }} <a data-rel="edx.org" href="https://wwww.edx.org" rel="external">{{ platform_name }}</a>.</p>
@bderusha I thought it is an in house app only for edX.

2016-10-06 12:24 UTC, clintonb commented on course_discovery/static/sass/publisher/course_detail.scss
> +                        margin-right: 20px;
Got it. I haven't dealt with RTL, so I'll defer to you.

2016-10-06 12:40 UTC, waheedahmed commented
@bderusha Removed the hardcoded edX links and also addressed other comments, please take another look.
Created a new story [ECOM-5959] (https://openedx.atlassian.net/browse/ECOM-5959) to generate dynamic links using Site/SiteConfiguration or Partner model.

2016-10-06 16:24 UTC, bderusha approved these changes
Provided that we do the additional work to fix the links in https://openedx.atlassian.net/browse/ECOM-5959 this looks good to me

2016-10-07 07:09 UTC, merged