feat: add TaxiForm metadata to Program model
openedx/course-discovery pull request #3683
Opened 2022-11-09 18:12 UTC by TheEarlyNerd

## Description
This PR adds a TaxiForm class which describes the fields needed to add a TaxiForm lead capture form to a Program about page.

## Related Ticket
[WS-3515](https://2u-internal.atlassian.net/browse/WS-3515)

2022-11-09 19:44 UTC, bseverino requested changes
Couple things along with the inline comments:

1. Add an admin page for `TaxiForm`, and also add the new field for `Program` https://github.com/openedx/course-discovery/blob/master/course_discovery/apps/course_metadata/admin.py
2. Add the new field to `ProgramSerializer` https://github.com/openedx/course-discovery/blob/8d5e095953e620d5783a254a43238f0071c68096/course_discovery/apps/api/serializers.py#L1761
3. Run migrations locally to generate a migration file

You can reference older PRs (https://github.com/openedx/course-discovery/pull/3427/files is a good one)

2022-11-09 19:44 UTC, bseverino commented on course_discovery/apps/course_metadata/models.py
> +    taxiForm = models.OneToOneField(
This should be a field on the `Program` model instead (also rename to `taxi_form` for consistency)

2022-11-09 19:44 UTC, bseverino commented on course_discovery/apps/course_metadata/models.py
> +class TaxiForm:
Remember to inherit a model class here (`TimeStampedModel` should be fine)

2022-11-09 19:44 UTC, bseverino commented on course_discovery/apps/course_metadata/tests/factories.py
> +class TaxiFormFactory(factory.django.DjangoModelFactory):
this looks good - you'll want to use this in the tests for program serializer https://github.com/openedx/course-discovery/blob/master/course_discovery/apps/api/tests/test_serializers.py

2022-11-10 10:07 UTC, Ali-D-Akbar reviewed
Changes look good to me. Can you add model tests for `TaxiForm`?

2022-11-10 10:15 UTC, Ali-D-Akbar requested changes
There is no migration created for `TaxiForm`. Please create one by running the following inside discovery-shell:
`./manage.py makemigrations course_metadata`

2022-11-17 07:43 UTC, Ali-D-Akbar approved these changes

2022-11-17 07:43 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/tests/factories.py
> +    form_id = FuzzyText()
if this is an int, you can use `FuzzyInt` instead.

2022-11-17 10:31 UTC, ansabgillani approved these changes

2022-11-17 18:50 UTC, bseverino approved these changes

2022-11-17 18:51 UTC, merged