feat: xblock metadata provider in taxonomy support
openedx/course-discovery pull request #3692
Opened 2022-11-16 06:20 UTC by navinkarkera

## Description

Implements `XBlockMetadataProvider` based on `abstract XBlockMetadataProvider` from https://github.com/openedx/taxonomy-connector/pull/119 in [taxonomy/providers/xblock_metadata.py](https://github.com/openedx/taxonomy-connector/pull/119/files#diff-8141029820d082f307303dc4a5e1ece9f42d4b78715ecbda3437e53271e1af78). Utilizes `index_dictionary` from course blocks api added in https://github.com/openedx/edx-platform/pull/31273 to fetch text representation of xblock.

Currently the provider supports `video` and `vertical` block types, configured via `TAXONOMY_XBLOCK_SUPPORTED_TYPES` setting. It combines `index_dictionary` text from all children blocks.

## Supporting information

- `Private-ref`: [BB-6887](https://tasks.opencraft.com/browse/BB-6887)
- https://github.com/openedx/taxonomy-connector/pull/119
- https://github.com/openedx/edx-platform/pull/31273

## Testing instructions

- Checkout https://github.com/openedx/edx-platform/pull/31273 to get `index_dictionary` in blocks api
- Start `lms` and `discovery` service in devstack using `make lms-up discovery-up`
- Open discovery shell using `make discovery-shell`
- Open django shell using `./manage.py shell`
- Run below commands to make
```python
from course_discovery.apps.taxonomy_support.providers import DiscoveryXBlockMetadataProvider
provider = DiscoveryXBlockMetadataProvider()
course_blocks = provider.get_all_xblocks_in_course("course-v1:edX+DemoX+Demo_Course")
print(next(course_blocks) # run few times to check fetched data
block = provider.get_all_xblocks_in_course("block-v1:edX+DemoX+Demo_Course+type@vertical+block@vertical_0270f6de40fc")
print(block)
```

**Troubleshooting**

If course blocks api raises an error related to `index_dictionary` transformer, run below commands and try again.
- `make lms-shell`
- `python setup.py install`
- `make lms-restart`

2022-11-16 06:20 UTC, openedx-webhooks commented
Thanks for the pull request, @navinkarkera!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-11-22 02:08 UTC, mphilbrick211 commented
@azanbinzahid - could you please take a look at this and allow tests to run?

2022-11-22 11:09 UTC, azanbinzahid commented
> @azanbinzahid - could you please take a look at this and allow tests to run?

Hi @mphilbrick211, apologies for the inconvenience. Team, please take a look @ansabgillani @DawoudSheraz @Ali-D-Akbar

2022-11-22 15:03 UTC, navinkarkera commented on requirements/production.txt
> +    # FIXME: remove this once a new tag is pushed in taxaonomy-connector
Temporarily added this to make CI/CD work.
**Note to self: Remove this and update to latest taxonomy version before merge**

2022-11-23 07:27 UTC, navinkarkera commented on requirements/production.txt
> +    # FIXME: remove this once a new tag is pushed in taxaonomy-connector
@ansabgillani Thank you! Although it did not work as CI is using `local.txt` which I missed to update. Please run the tests again. Sorry.

2022-11-23 08:31 UTC, Ali-D-Akbar commented on requirements/production.txt
> +    # FIXME: remove this once a new tag is pushed in taxaonomy-connector
The tests have been run. Do you have the access to [taxonomy-connector](https://github.com/openedx/taxonomy-connector/commits/master) to release a new version? If not, I can get this released so you can run `make upgrade` to update the version for taxonomy-connector. Just let me know about it.

2022-11-23 09:21 UTC, navinkarkera commented on requirements/production.txt
> +    # FIXME: remove this once a new tag is pushed in taxaonomy-connector
@Ali-D-Akbar Thank you! Fixed commit lint issue as well as a failing test (although this was working locally, lets see if the change works).

>Do you have the access to [taxonomy-connector](https://github.com/openedx/taxonomy-connector/commits/master) to release a new version? If not, I can get this released so you can run make upgrade to update the version for taxonomy-connector. Just let me know about it.

I don't have the access to create new versions, but we are in discussion with @irfanuddinahmad and @sameenfatima78 for taxonomy-connector MR. Maybe you guys can coordinate and release. Thank you for your help.

2022-11-23 10:30 UTC, sameenfatima78 commented on requirements/production.txt
> +    # FIXME: remove this once a new tag is pushed in taxaonomy-connector
@navinkarkera We'll need to merge the PR in taxonomy-connector first before merging and releasing a new version here.  Could you please update the release version in this PR? https://github.com/openedx/taxonomy-connector/pull/119

2022-11-23 11:16 UTC, navinkarkera commented on requirements/production.txt
> +    # FIXME: remove this once a new tag is pushed in taxaonomy-connector
@sameenfatima78 Yes, I meant releasing a new version in taxonomy-connector.

2022-11-23 11:47 UTC, farhaanbukhsh requested changes
I am still trying to test on local devstack but there are few comments which I could get while reading the code :)

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/core/api_client/lms.py
> +                blocks = blocks[response_root_key]
```suggestion
                blocks = blocks.get(response_root_key, None)
```

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/core/api_client/lms.py
> +        except (RequestException, KeyError) as exception:
If we can use `.get` we can avoid using and catching "KeyError" exception

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/core/api_client/lms.py
> +        query_parameters_str = urlencode(query_parameters, safe=":")
```suggestion
        encoded_query_parameters = urlencode(query_parameters, safe=":")
```

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/core/api_client/lms.py
> +        Get xblocks metadata for given block_id
```suggestion
        Get xblock metadata for given block_id.
```

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/core/api_client/lms.py
> +        return self._get_blocks_data(block_id, cache_key, query_parameters, resource, response_root_key="blocks")
Shouldn't query param encoding be done on for this as well?

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/taxonomy_support/providers.py
> +        Get lms client with default partner object
```suggestion
        Get lms client with default partner object.
```

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/taxonomy_support/providers.py
> +        Recursively combines content values in all children blocks
```suggestion
        Recursively combines content values in all children blocks.
```

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/taxonomy_support/providers.py
> +        content_set = self._get_block_content(cur_block["id"])
```suggestion
        content_set = self._get_block_content(cur_block.get("id", None))
```

This might raise a KeyError if id is not found.

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/taxonomy_support/providers.py
> +            content_set.update(self._combine_text_data(child_block, all_blocks))
```suggestion
            if child_block:
               content_set.update(self._combine_text_data(child_block, all_blocks))
```

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/taxonomy_support/providers.py
> +        the form of a XBlockContent.
```suggestion
        Get list of xblocks matching the given xblock UUIDs and return them in
        the form of XBlockContent.
```

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/taxonomy_support/providers.py
> +            ))
```suggestion
            if parent_block:
              content = "\n".join(self._combine_text_data(parent_block, all_blocks))
              blocks_data.append(XBlockContent(
                  key=parent_block.get("id"),
                  content_type=parent_block.get("type"),
                  content=content,
              ))
```

2022-11-23 11:47 UTC, farhaanbukhsh commented on course_discovery/apps/taxonomy_support/providers.py
> +            if block["type"] not in settings.TAXONOMY_XBLOCK_SUPPORTED_TYPES:
same as above

2022-11-23 11:55 UTC, navinkarkera commented on course_discovery/apps/core/api_client/lms.py
> +                blocks = blocks[response_root_key]
If the key is missing, we want to log that the request failed instead of assuming that the api returned no blocks.

2022-11-23 11:55 UTC, navinkarkera commented on course_discovery/apps/core/api_client/lms.py
> +        except (RequestException, KeyError) as exception:
Same as above. :)

2022-11-23 11:57 UTC, farhaanbukhsh commented on course_discovery/apps/core/api_client/lms.py
> +                blocks = blocks[response_root_key]
We are logging it when we check for `if blocks`, am I missing something? 😇

2022-11-23 11:57 UTC, navinkarkera commented on course_discovery/apps/core/api_client/lms.py
> +        return self._get_blocks_data(block_id, cache_key, query_parameters, resource, response_root_key="blocks")
It was required above specifically for `:` in course_keys in query_params. Not required in this case.

2022-11-23 12:14 UTC, navinkarkera commented on course_discovery/apps/core/api_client/lms.py
> +                blocks = blocks[response_root_key]
@farhaanbukhsh The cache and the log message both are different in case of missing key.

2022-11-23 12:16 UTC, sameenfatima78 commented on requirements/production.txt
> +    # FIXME: remove this once a new tag is pushed in taxaonomy-connector
Ah okay, I can take care of that if you don't have access right now.

2022-11-23 16:28 UTC, farhaanbukhsh commented
Hey @navinkarkera thank you for the amazing work, I am trying to test the code with the instructions you provided and I am getting

![image](https://user-images.githubusercontent.com/7670449/203597974-b7a3ee2a-c5b2-4650-b46e-02099f3d928a.png)


LMS logs

```
edx.devstack.lms  | During handling of the above exception, another exception occurred:
edx.devstack.lms  | 
edx.devstack.lms  | Traceback (most recent call last):
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/content/block_structure/manager.py", line 96, in get_collected
edx.devstack.lms  |     block_structure = BlockStructureFactory.create_from_store(
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/content/block_structure/factory.py", line 86, in create_from_store
edx.devstack.lms  |     return block_structure_store.get(root_block_usage_key)
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/content/block_structure/store.py", line 99, in get
edx.devstack.lms  |     serialized_data = self._get_from_store(bs_model)
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/content/block_structure/store.py", line 190, in _get_from_store
edx.devstack.lms  |     raise BlockStructureNotFound(bs_model.data_usage_key)
edx.devstack.lms  | openedx.core.djangoapps.content.block_structure.exceptions.BlockStructureNotFound: Block structure not found; data_usage_key: block-v1:edX+DemoX+Demo_Course+branch@draft-branch+version@637e0bef5d758277968b2140+type@course+block@course
edx.devstack.lms  | 
edx.devstack.lms  | During handling of the above exception, another exception occurred:
edx.devstack.lms  | 
edx.devstack.lms  | Traceback (most recent call last):
edx.devstack.lms  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
edx.devstack.lms  |     response = get_response(request)
edx.devstack.lms  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
edx.devstack.lms  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
edx.devstack.lms  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
edx.devstack.lms  |     return view_func(*args, **kwargs)
edx.devstack.lms  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
edx.devstack.lms  |     return self.dispatch(request, *args, **kwargs)
edx.devstack.lms  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
edx.devstack.lms  |     return bound_method(*args, **kwargs)
edx.devstack.lms  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
edx.devstack.lms  |     response = self.handle_exception(exc)
edx.devstack.lms  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
edx.devstack.lms  |     response = handler(request, *args, **kwargs)
edx.devstack.lms  |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/rest_framework/generics.py", line 199, in get
edx.devstack.lms  |     return self.list(request, *args, **kwargs)
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/course_api/blocks/views.py", line 227, in list
edx.devstack.lms  |     get_blocks(
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/course_api/blocks/api.py", line 122, in get_blocks
edx.devstack.lms  |     blocks = course_blocks_api.get_course_blocks(
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/course_blocks/api.py", line 107, in get_course_blocks
edx.devstack.lms  |     return get_block_structure_manager(starting_block_usage_key.course_key).get_transformed(
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/content/block_structure/manager.py", line 65, in get_transformed
edx.devstack.lms  |     block_structure = collected_block_structure.copy() if collected_block_structure else self.get_collected()
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/content/block_structure/manager.py", line 105, in get_collected
edx.devstack.lms  |     block_structure = self._update_collected()
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/content/block_structure/manager.py", line 128, in _update_collected
edx.devstack.lms  |     BlockStructureTransformers.collect(block_structure)
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/content/block_structure/transformers.py", line 78, in collect
edx.devstack.lms  |     transformer.collect(block_structure)
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/course_blocks/transformers/user_partitions.py", line 51, in collect
edx.devstack.lms  |     SplitTestTransformer.collect(block_structure)
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/lms/djangoapps/course_blocks/transformers/split_test.py", line 45, in collect
edx.devstack.lms  |     root_block = block_structure.get_xblock(block_structure.root_block_usage_key)
edx.devstack.lms  |   File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/content/block_structure/block_structure.py", line 815, in get_xblock
edx.devstack.lms  |     return self._xblock_map[usage_key]
edx.devstack.lms  | KeyError: BlockUsageLocator(CourseLocator('edX', 'DemoX', 'Demo_Course', 'draft-branch', ObjectId('637e0bef5d758277968b2140')), 'course', 'course')
edx.devstack.lms  | [23/Nov/2022 16:24:25] "GET /api/courses/v1/blocks/block-v1:edX+DemoX+Demo_Course+branch@draft-branch+version@637e0bef5d758277968b2140+type@vertical+block@4a1bba2a403f40bca5ec245e945b0d76?all_blocks=True&depth=all&requested_fields=children HTTP/1.1" 500 418770
```


I am using the key that is fetched in the `get_all_xblocks_in_course` to fetch `get_xblocks`. Let me know if I am missing something!

2022-11-24 06:35 UTC, navinkarkera commented
@farhaanbukhsh This seems like an issue with [course-blocks API](https://github.com/openedx/edx-platform/blob/54507c1e083990ef9d9c8022027332818bd05595/lms/djangoapps/course_api/blocks/views.py#L27-L115). Anyway, the `get_xblocks` method will not be used to fetch data for draft version (we only want published versions) and even if it is accidentally used for a draft version, it logs an exception and returns data for all other passed items. Is that acceptable or do you feel differently?

2022-11-24 06:41 UTC, navinkarkera commented
Also the test failing in CI seems to be passing locally and the changes in this MR should not have any effect on this test.
![image](https://user-images.githubusercontent.com/10894099/203711902-05faa06d-9a6f-4978-8e3c-575cc75429c6.png)
Please re-run the test if possible.

2022-11-24 10:45 UTC, farhaanbukhsh commented on course_discovery/apps/core/api_client/lms.py
> +                blocks = blocks[response_root_key]
Alright 👍🏾

2022-11-24 10:45 UTC, farhaanbukhsh commented on course_discovery/apps/core/api_client/lms.py
> +        return self._get_blocks_data(block_id, cache_key, query_parameters, resource, response_root_key="blocks")
okay!

2022-11-24 11:21 UTC, farhaanbukhsh approved these changes
👍 

I have added a few nits, but over all the PR looks good.

- ✅ I tested this: by running and testing the provider locally on the devstack.
- ✅  I read through the code
- ❌  I checked for accessibility issues
- ❌  Includes documentation
- ❌  I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

2022-11-24 11:21 UTC, farhaanbukhsh commented on course_discovery/apps/taxonomy_support/providers.py
> +                ))
Nit:
```suggestion
                blocks_data.append(XBlockContent(
                    key=parent_block.get("id"),
                    content_type=parent_block.get("type"),
                    content=content,
                ))
```

2022-11-24 11:21 UTC, farhaanbukhsh commented on course_discovery/apps/taxonomy_support/providers.py
> +                )
Nit:
```suggestion
                yield XBlockContent(
                    key=block.get("id"),
                    content_type=block.get("type"),
                    content=content,
                )
```

2022-11-24 11:21 UTC, farhaanbukhsh commented on course_discovery/apps/taxonomy_support/providers.py
> +            content_set = set()
Nit:
```suggestion
        content_set = set()
        if block_id:
            content_set = self._get_block_content(block_id)
```

2022-11-30 16:38 UTC, mphilbrick211 commented
Hi @awaqargillani! Could you please take a look at this and allow tests to run?

2022-11-30 17:09 UTC, mphilbrick211 commented
@navinkarkera looks like you have branch conflicts that need to be resolved to push this through.

2022-12-06 07:41 UTC, navinkarkera commented
@mphilbrick211 @ansabgillani @sameenfatima78  This is now ready for merge (checked all required items in pre-merge checklist).

2022-12-06 11:18 UTC, sameenfatima78 approved these changes

2022-12-06 13:40 UTC, navinkarkera commented
@DawoudSheraz @Ali-D-Akbar Can you please help merge this MR.

2022-12-15 07:10 UTC, navinkarkera commented
@DawoudSheraz @Ali-D-Akbar @mphilbrick211 @ansabgillani Please merge this MR if no further changes are required.

2022-12-21 19:41 UTC, mphilbrick211 commented
Hi @navinkarkera! We're looking into having tests enabled for you.

2022-12-22 13:56 UTC, mphilbrick211 commented
Hi @navinkarkera! Your tests were enabled, but you have some that failed and will need to be re-run. You'll also need to rebase to resolve the branch date issue.

2022-12-22 14:29 UTC, navinkarkera commented
> Hi @navinkarkera! Your tests were enabled, but you have some that failed and will need to be re-run. You'll also need to rebase to resolve the branch date issue.

@mphilbrick211 Thanks you. Fixed the quality issues, but the test is passing locally and it has no relation to this MR. Please re-run the tests.

2022-12-27 17:19 UTC, mphilbrick211 commented
Hi @navinkarkera - I am unable to run the tests, but I believe you should be able to. If you are running into issues, please let me know.

2022-12-28 07:10 UTC, navinkarkera commented
@mphilbrick211 I can only rebase with master but the workflow needs approval.
![image](https://user-images.githubusercontent.com/10894099/209772922-c479b450-76cd-48c6-bef8-3dc9905b337a.png)

2022-12-28 07:14 UTC, DawoudSheraz commented
> @mphilbrick211 I can only rebase with master but the workflow needs approval. ![image](https://user-images.githubusercontent.com/10894099/209772922-c479b450-76cd-48c6-bef8-3dc9905b337a.png)

I have given Approve and Run on this PR before. Not sure why it is asking again.

2022-12-28 14:27 UTC, navinkarkera commented
@DawoudSheraz  Thank you.

It did ran successfully.
![image](https://user-images.githubusercontent.com/10894099/209826687-148f6fb3-13c3-4e46-8d89-6aa7cbf4e02f.png)

But the master was updated and I had to rebase again. Someone would need to approve it again (till my MR is merged each run of workflow requires approval).

2022-12-28 15:15 UTC, DawoudSheraz commented on course_discovery/apps/taxonomy_support/tests/test_providers.py
> +        resource = 'api/courses/v1/blocks/'
you can add a settings/constants variable for this. This has been used in client file too.

2022-12-28 15:18 UTC, DawoudSheraz approved these changes
A few nits, but overall good. A question: how/where will this be used? The blocks API is an important and sometimes expensive API. I am just wondering how often LMS will be hit to get blocks data.

2022-12-28 16:41 UTC, navinkarkera commented on course_discovery/apps/taxonomy_support/tests/test_providers.py
> +        resource = 'api/courses/v1/blocks/'
Done.

2022-12-28 16:44 UTC, navinkarkera commented
> A few nits, but overall good. A question: how/where will this be used? The blocks API is an important and sometimes expensive API. I am just wondering how often LMS will be hit to get blocks data.

@DawoudSheraz Whenever a block is published and when we run `refresh_xblock_skills` management command. Please find related MRs below:
- https://github.com/openedx/taxonomy-connector/pull/129
- https://github.com/openedx/edx-platform/pull/31350

2022-12-28 21:30 UTC, ansabgillani approved these changes

2022-12-29 07:17 UTC, DawoudSheraz approved these changes

2022-12-29 07:17 UTC, merged

2022-12-29 07:17 UTC, openedx-webhooks commented
@navinkarkera 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/3692&entry.1484655318=https://github.com/navinkarkera&entry.752974735=2022-11-16+06:20&entry.1917517419=2022-12-29+07:17&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->