feat: Add customProgramDuration field to Programs
openedx/course-discovery pull request #3701
Opened 2022-11-25 02:47 UTC by gilsantosjulian

Description
This PR adds a Program Duration Override filed on Programs model, which describes the months in which a Program can takes. This filed override the current value that is has been displayed in the frontend side (Prospectus)

See an example - Right side - 9 months:
[iux-information-systems](https://www.edx.org/micromasters/iux-information-systems?index=product&queryID=079a2394626ce063d46d4e7db87e5d8f&position=1&linked_from=autocomplete&c=autocomplete)

Screenshot
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/23086872/203890274-d5ee65fd-793b-40f7-a0f7-fac14d640699.png">

Related Ticket
[WS-3462](https://2u-internal.atlassian.net/browse/WS-3462)

2022-11-25 19:20 UTC, Ali-D-Akbar requested changes
Failing tests. Look into the fact if you need the field in Degree api or not. If yes, be sure to add it in it's serializer.

2022-11-25 19:20 UTC, Ali-D-Akbar commented on course_discovery/apps/api/serializers.py
> -            'specializations', 'program_duration_override'
Do we not want this data for degrees api?

2022-11-25 20:22 UTC, gilsantosjulian commented on course_discovery/apps/api/serializers.py
> -            'specializations', 'program_duration_override'
We want it, I updated it to keep it

2022-11-28 14:38 UTC, Ali-D-Akbar approved these changes
The changes indeed look good but please verify your changes on local and make sure this is the intended changes.

2022-11-28 17:44 UTC, ansabgillani approved these changes

2022-11-28 21:29 UTC, merged