feat: transform contentful fields and index in algolia
openedx/course-discovery pull request #3714
Opened 2022-12-05 06:54 UTC by Ali-D-Akbar

[PROD-3024](https://2u-internal.atlassian.net/browse/PROD-3024)
TBA

2022-12-12 12:28 UTC, AliAdnanSohail requested changes

2022-12-12 12:28 UTC, AliAdnanSohail commented on course_discovery/apps/course_metadata/algolia_models.py
> +        for key, value in contentful_product:
Shouldn't we move all these fields in a separate dict in Algolia? Or there is any requirement or use case to keep each key separately?
If we keep all fields separate in Algolia not in a specific dict, then there will be a big difference between Algolia Bootcamp product and Algolia non-bootcamp product

2022-12-12 14:02 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/algolia_models.py
> +        for key, value in contentful_product:
+1 on this.

2022-12-13 07:09 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/algolia_models.py
> +        for key, value in contentful_product:
Hmmm, I'm not sure if this was their requirement to keep separate values. We can keep this in a dict for now...

2022-12-13 11:52 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +        })
Please add some logs here to keep track of the fetch process.

2022-12-13 11:53 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +        'include': include
Please update docstring to showcase these changes.

2022-12-13 11:53 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +    limit = 10
Why is limit so small here?

2022-12-13 11:54 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +def traverse_plain_text(dictt, key):
nit: rename dictt.

2022-12-13 11:54 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +    Recursive function to extract a list of values of all the keys containing plain text.
Please add info in the docstring showcasing the structure of dict and list.

2022-12-13 11:55 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +def traverse_plain_text(dictt, key):
nit: Since this is only needed for contentful data, update the method name.

2022-12-13 11:55 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +    text_key = 'value'
nit: no need to declare this variable.

2022-12-13 11:57 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +def transform_bootcamp_contentful_data():
nit: fetch and transform bootcamp contentful data. 

Also, it would be a good idea to move contentful-related methods into a separate utils file. I can expect we would add more utils once the code reaches production and contentful is expanded upon.

2022-12-13 11:58 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +
nit: create small utils methods for each data key and call them here. It will make code readable and easy to follow.

2022-12-13 11:59 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +    contentful_bootcamp_page_entries = get_data_from_contentful('bootCampPage')
nit: These contentful specific keys can be read from settings. It will make it easier to override them for dev and testing environment when needed. The current flow makes it very specific to internal use.

2022-12-13 12:03 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/contentful_bootcamp_mock_data.py
> +    'heading': 'The support you need to transform your career.',
- Run formatter on this file to organize dicts
- Use lorem ipsum or random text. The current content has similarities to edx.org public data which might impact search engines (Github being public).

2022-12-13 12:05 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/index.py
> +                     'skills', 'bootcamp_contentful_fields',)
instead of bootcamp_contentful_fields, lets use contentful_fields. Bootcamp becomes specific to a particular product.

2022-12-13 12:06 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/index.py
> +        contentful_bootcamp_data = transform_bootcamp_contentful_data()
nit: rename to contentful_data.

2022-12-13 12:08 UTC, DawoudSheraz reviewed
Left a few followup comments.

2022-12-14 06:44 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/utils.py
> +    limit = 10
I tried to fetch larger count number like 50 but that sometimes gives an error like "data is too big, cannot be fetched".

2022-12-14 07:02 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/utils.py
> +    limit = 10
`Response size too big. Maximum allowed response size: 7340032B.`

2022-12-14 07:05 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/utils.py
> +        })
logging like this:
<img width="1665" alt="Screenshot 2022-12-14 at 12 05 13 PM" src="https://user-images.githubusercontent.com/52413434/207528594-d16d7de0-a9eb-4f12-ae54-3b9b414a52c3.png">

2022-12-14 09:04 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/tests/contentful_bootcamp_mock_data.py
> +    'heading': 'The support you need to transform your career.',
Looks uglier when formatter is run, specifically the rich_text dicts:
<img width="1251" alt="Screenshot 2022-12-14 at 2 03 39 PM" src="https://user-images.githubusercontent.com/52413434/207552639-2a3f19e3-c691-4da4-b5ca-9ac2a52a2b5e.png">

2022-12-15 05:14 UTC, ansabgillani commented on course_discovery/apps/course_metadata/algolia_models.py
> +        if not contentful_data or product_uuid not in contentful_data:
Just use 
`if contentful_data and product_uuid in contentful_data:`
`self.product.contentful_fields = contentful_data[product_uuid]`

2022-12-15 05:15 UTC, ansabgillani commented on course_discovery/apps/course_metadata/contentful_utils.py
> +    for k, v in rich_text_dict.items():
Use proper variable names.

2022-12-15 05:19 UTC, ansabgillani commented on course_discovery/apps/course_metadata/contentful_utils.py
> +        elif isinstance(v, dict):
Add inline comment '# checking if the value is a nested dict'

2022-12-15 05:19 UTC, ansabgillani commented on course_discovery/apps/course_metadata/contentful_utils.py
> +        elif isinstance(v, list):
Same as above

2022-12-15 05:23 UTC, ansabgillani commented on course_discovery/apps/course_metadata/contentful_utils.py
> +def get_data_from_contentful(content_type):
Can you convert all these functions in a class like BootcampContentful utils with a bunch of private functions? It might be confusing when Degrees functions are added here.

2022-12-15 06:26 UTC, DawoudSheraz commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        with self.assertNumQueries(expected_queries, threshold=2):  # CI sometimes adds a bunch of query
nit: a bunch of queries

2022-12-15 06:27 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/algolia_models.py
> +        if not contentful_data or product_uuid not in contentful_data:
+1 to this. return in init also seems weird.

2022-12-15 06:30 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/contentful_utils.py
> +    return total_entries
We should think about caching this response. There are quite a bunch of API calls here that can overwhelm the Contentful system if there is ever a need to index in a short period of time.

2022-12-15 06:31 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/contentful_utils.py
> +        elif isinstance(v, dict):
and add \n after adding the value.

2022-12-15 06:31 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/contentful_utils.py
> +    return ''.join(extract_plain_text_from_rich_text(rich_text))
oh, ignore my \n comment above. Do this here instead.

2022-12-15 06:32 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/contentful_utils.py
> +            print(faq_items)
remove this print.

2022-12-15 06:33 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/contentful_utils.py
> +    contentful_bootcamp_page_entries = get_data_from_contentful(settings.BOOTCAMP_CONTENTFUL_CONTENT_TYPE)
BOOTCAMP_CONTENTFUL_CONTENT_TYPE -- has this been added in a prior PR?

2022-12-15 06:34 UTC, DawoudSheraz approved these changes
I have not tested it locally. Overall, looks good.

2022-12-15 08:36 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/contentful_utils.py
> +        elif isinstance(v, dict):
I'm not adding `\n` because it breaks sentences in the middle.

2022-12-15 08:38 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/contentful_utils.py
> +def get_data_from_contentful(content_type):
I think these functions will eventually be reused with Degree work so keeping them public will aid us in degree work.

2022-12-15 08:40 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/contentful_utils.py
> +    return ''.join(extract_plain_text_from_rich_text(rich_text))
Breaks sentences. I don't think we'd need something like this here.

2022-12-15 08:40 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/contentful_utils.py
> +    contentful_bootcamp_page_entries = get_data_from_contentful(settings.BOOTCAMP_CONTENTFUL_CONTENT_TYPE)
https://github.com/edx/edx-internal/pull/7514

2022-12-15 12:16 UTC, AliAdnanSohail requested changes

2022-12-15 12:16 UTC, AliAdnanSohail commented on course_discovery/apps/course_metadata/algolia_models.py
> +                     'product_meta_title', 'contentful_fields'
Will query be searched in `contentful_fields`? If not, then we should add this in search_fields

2022-12-15 15:27 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/algolia_models.py
> +                     'product_meta_title', 'contentful_fields'
The decision for now is to do it like this. Ideally, we'd first like to check how the data looks like and what kind of effects it will have on the searches.
Besides, I don't think that the search field should be a nested object.

2022-12-15 15:58 UTC, AliAdnanSohail approved these changes

2022-12-16 11:24 UTC, merged