Updated i18n-tool version, .travis.yml and Makefile files
openedx/course-discovery pull request #374
Opened 2016-10-07 09:23 UTC by iivic

@clintonb Review changes.

2016-10-12 12:02 UTC, iivic commented
Please review latest changes. @clintonb

2016-10-12 13:02 UTC, clintonb requested changes

2016-10-12 13:02 UTC, clintonb commented on Makefile
> +requirements: requirements.js
Revert. There may be workflows that depend on this.

2016-10-12 13:02 UTC, clintonb commented on .travis.yml
> -    - make requirements.js
Revert.

2016-10-12 13:02 UTC, clintonb commented on .travis.yml
> +    - make detect_changed_source_translations
`make validate_translations`

2016-10-14 09:31 UTC, iivic commented
@clintonb I can't figure out why `make validate_translations` detect changes. Locally the source files are current. Can you take a look?

2016-10-14 18:08 UTC, clintonb approved these changes
My fixup should resolve the build issue. Remember to squash before merging.

2016-10-14 18:08 UTC, clintonb commented on .travis.yml
> -
Revert.

2016-10-17 08:30 UTC, merged

2016-10-17 08:38 UTC, iivic commented
Thank you for the help. So the problem were the files that shouldn't be extracted?

2016-10-17 12:43 UTC, clintonb commented
@iivic yes. We don't normally translate our documentation; although, we probably should consider doing so at some point.