feat: add googleapiclent to communicate with drive images
openedx/course-discovery pull request #3740
Opened 2022-12-27 19:57 UTC by AfaqShuaib09

[PROD-2903](https://2u-internal.atlassian.net/browse/PROD-2903?atlOrigin=eyJpIjoiM2EzZTFjNjk4ZDFlNDFhYWFkZDhhYTRmNzc2MDE5M2EiLCJwIjoiaiJ9)

2022-12-27 19:57 UTC, openedx-webhooks commented
Thanks for the pull request, @AfaqShuaib09!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-12-27 22:46 UTC, mphilbrick211 commented
Hi @AfaqShuaib09! Thanks for your submission! It looks like you'll need to fill out a CLA form in order to continue. I see you are at Arbisoft - do you know if you are covered by an existing entity agreement between Arbisoft and Open edX? If you are not, you'll need to fill out the individual CLA form as instructed above. Thank you!

2022-12-28 10:12 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +            logger.info('Image for course [%s] successfully updated.', course.key)
This will cause tests to break. Not all download URLs are Google Drive links.

2022-12-28 19:04 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/utils.py
> +            logger.info('Image for course [%s] successfully updated.', course.key)
updated

2022-12-28 21:08 UTC, ansabgillani commented on course_discovery/apps/course_metadata/googleapi_client.py
> +            logging.info(f'[File Found]: Opening google file {file_id}')
Change this logger message to something more identifiable, like `Found file x on request y`

2022-12-28 21:10 UTC, ansabgillani commented on course_discovery/apps/course_metadata/googleapi_client.py
> +        if match:
`return match.group(1) if match else None`

2022-12-28 21:11 UTC, ansabgillani commented on course_discovery/apps/course_metadata/googleapi_client.py
> +        return None
`return None` in a `finally` clause. This exception handling isn't a good practice.

2022-12-28 21:12 UTC, ansabgillani commented on course_discovery/apps/course_metadata/googleapi_client.py
> +        return None
Or maybe, you can initialise content by None and return content in finally clause

2022-12-28 21:13 UTC, ansabgillani commented on course_discovery/apps/course_metadata/utils.py
> +            # To get file-type/extension of the image
Do we need this comment?

2022-12-28 21:15 UTC, ansabgillani commented on course_discovery/apps/course_metadata/utils.py
> +            # TODO: Get field from _meta.get_field. Tried that approach initially but was getting
Why this TODO?

2022-12-28 21:16 UTC, ansabgillani requested changes
Added some comments

2022-12-29 08:23 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/googleapi_client.py
> +            logging.info(f'[File Found]: Opening google file {file_id}')
Done. logger message updated to `logger.info(f'[File Found]: Found google file {file_id} on requesting {url}')`

2022-12-29 08:24 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/googleapi_client.py
> +        return None
updated

2022-12-29 08:24 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/utils.py
> +            # To get file-type/extension of the image
Nope. added just for clarification
Removed

2022-12-29 08:24 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/utils.py
> +            # TODO: Get field from _meta.get_field. Tried that approach initially but was getting
This comment was previously added by the azanbinzahid.  I'm not sure if this is still relevant

2022-12-29 11:14 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +            content = google_api_client.download_file_by_url(image_url)
nit: combine this into a method where input is drive URL and output is metadata, content.

2022-12-29 11:15 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +def is_drive_url(url):
nit: is_google_drive_url

2022-12-29 11:15 UTC, DawoudSheraz requested changes
Relevant unit tests missing.

2022-12-29 11:16 UTC, AliAdnanSohail commented on course_discovery/apps/course_metadata/utils.py
> +            content = google_api_client.download_file_by_url(image_url)
You can create a new method in utils, which can be used anywhere where we need to download some file from google drive

2022-12-29 13:07 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/utils.py
> +            content = google_api_client.download_file_by_url(image_url)
done

2022-12-30 07:52 UTC, ansabgillani approved these changes

2022-12-30 12:02 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +        assert is_google_drive_url('https://example.com/image.jpg') is False
- these tests can be added to existing utils. 
- Both tests can be combined to a single test, catering to different data via ddt.

2022-12-30 15:51 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +        assert is_google_drive_url('https://example.com/image.jpg') is False
updated

2023-01-02 06:41 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/googleapi_client.py
> +    API Client for Google API to communicate with drive images
nit: to communicate with Google Drive. The methods are generic here, I suspect they can be used for other purposes too.

2023-01-02 06:42 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +    ]
nit: you dont need to define a method for the tests Just have them as class variables for GoogleAPIClientTests if they are used for multiple tests, otherwise define only on the tests where they are used.

2023-01-02 06:42 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +    @mock.patch('course_discovery.apps.course_metadata.googleapi_client.build')
add space after GoogleAPIClientTests

2023-01-02 06:44 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +        file_id = client.get_file_id_from_url(file_url)
assert on the service method execution too.

2023-01-02 06:44 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +        )
same, assert on the service method execution. Only checking the logs is not enough.

2023-01-02 06:45 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +            mock_get_file_from_drive_link.return_value = (self.IMG_CONTENT, 'image/jpeg')
why is this needed? Move them before assertions if they are required, else remove this.

2023-01-02 06:46 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +            mock_requests_get.return_value = self.mock_image_response(course.card_image_url, body=b'invalid content',
same question as above.

2023-01-02 06:46 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +    @mock.patch('course_discovery.apps.course_metadata.utils.requests.get')
please use `responses` to mock requests

2023-01-02 06:47 UTC, DawoudSheraz reviewed
left a few more followup comments

2023-01-02 08:14 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/googleapi_client.py
> +    API Client for Google API to communicate with drive images
Nope
As we are using drive v3 service. These methods are used only for communicating with Google Drive only
![image](https://user-images.githubusercontent.com/78806673/210202228-affcbd92-5df9-4c93-9bab-fd4249b3aef4.png)

2023-01-02 08:14 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +    ]
Yup, this data is used for multiple tests in the class
If i want to have them as a class variable it can't be referred in @ddt.data
![image](https://user-images.githubusercontent.com/78806673/210202981-689f7f41-a0a6-4ed4-8098-f024cb740845.png)
can I make a new file `constants.py` in tests folder and import them here?

2023-01-02 08:14 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +    @mock.patch('course_discovery.apps.course_metadata.googleapi_client.build')
fixed

2023-01-02 08:14 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +        file_id = client.get_file_id_from_url(file_url)
updated
I followed previously the gspread tests convention to check the logs only
`test_gspread.py`
![image](https://user-images.githubusercontent.com/78806673/210204441-ba345207-06d9-4ce3-8ea2-787c2b503f51.png)

2023-01-02 08:14 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +        )
done

2023-01-02 08:14 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +            mock_get_file_from_drive_link.return_value = (self.IMG_CONTENT, 'image/jpeg')
To mock the request response return value, so that function proceeds further to convert and store this in the course and program model.

2023-01-02 08:14 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +            mock_requests_get.return_value = self.mock_image_response(course.card_image_url, body=b'invalid content',
To mock the request response value, so that function proceeds further to convert and store this in the course and program model
The function calls in both cases are different 
in the case of the drive link I have to mock the response GoogleAPI client by calling `get_file_from_drive_link` and for simple image link i mock the request_library return value

2023-01-02 08:14 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +    @mock.patch('course_discovery.apps.course_metadata.utils.requests.get')
done.
using the response library to mock the image data
![image](https://user-images.githubusercontent.com/78806673/210207011-e1846792-2a37-419e-a575-5bf9d5812505.png)
![image](https://user-images.githubusercontent.com/78806673/210207043-c309597f-5622-41ce-9032-0fc78a8d0e76.png)

2023-01-02 09:05 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +    ]
No, it can be referred to in ddt.data when it is class-level variable. There would be no self or cls. Just add variable name in ddt.data

2023-01-02 09:07 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +            mock_get_file_from_drive_link.return_value = (self.IMG_CONTENT, 'image/jpeg')
Ok, move them before assertion then.

2023-01-02 09:09 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +            mock_requests_get.return_value = self.mock_image_response(course.card_image_url, body=b'invalid content',
Ah, in that case, you can split this test into two separate tests. This if-else looks weird and it is better to have a separate unit test if the case is special.

2023-01-02 09:20 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +    ]
Done

2023-01-02 09:52 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/googleapi_client.py
> +    API Client for Google API to communicate with drive images
Yes, but we can interact with any drive item, not just images, Correct?

2023-01-02 09:53 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/googleapi_client.py
> +        finally:
nit: you don't need `finally` here. Just return content outside try/catch.

2023-01-02 09:53 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/googleapi_client.py
> +    API Client for Google API to communicate with drive images
yes

2023-01-02 09:54 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +    ]
Is it? The method is still there.

2023-01-02 09:55 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +    return (('https://www.example.com',), ('https://docs.google.com/uc?id=abcd123id',))
Convert this method into class level variable.

2023-01-02 09:57 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/googleapi_client.py
> +        finally:
done

2023-01-02 09:59 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_googleapi.py
> +    ]
fixed. Working on seperating tests for drive and requests library

2023-01-02 10:00 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +    return (('https://www.example.com',), ('https://docs.google.com/uc?id=abcd123id',))
Already done. Working on seperation of tests for drive api and requests library. I will push the changes after updating them

2023-01-02 14:22 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +    @ddt.data(('https://docs.google.com/uc?id=abcd123id',))
no need to have this as ddt.data anymore because there is only one entry in the data. Declare it inside unit test.

2023-01-02 14:23 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +    @mock.patch('course_discovery.apps.course_metadata.utils.requests.get')
- remove the mock patch on requests.get
- In unit test, add responses.add to register the network call and mock the response

2023-01-02 14:25 UTC, DawoudSheraz approved these changes
- A few updates to be made in unit tests for the correct use of responses
- Get a review from @AliAdnanSohail

2023-01-02 17:34 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +    @mock.patch('course_discovery.apps.course_metadata.utils.requests.get')
done

2023-01-12 13:54 UTC, merged

2023-01-12 13:54 UTC, openedx-webhooks commented
@AfaqShuaib09 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/3740&entry.1484655318=https://github.com/AfaqShuaib09&entry.752974735=2022-12-27+19:57&entry.1917517419=2023-01-12+13:54&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->