Implementing emails sending functionality.
openedx/course-discovery pull request #377
Opened 2016-10-08 08:56 UTC by awais786

WIP

2016-10-08 09:35 UTC, awais786 commented
@tasawernawaz @ahsan-ul-haq @waheedahmed @jareerahsan Please review.

2016-10-08 10:04 UTC, ahsan-ul-haq requested changes

2016-10-08 10:04 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/models.py
> +        """ Returns queryset of all User objects with any object permissions for the given course."""
doc string should be less than 80 characters per line

2016-10-08 10:04 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/models.py
> +        ]
you could do that like this as well
```
if not hasattr(user, 'attributes') or user.attributes.enable_email_notification
```
It will check if there is no user attribute than add in emails otherwise if there is user attribute then check if email notification is enabled

2016-10-08 10:04 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher_comments/emails.py
> +from django.core.mail import get_connection
django imports should be in 2nd block

2016-10-08 10:04 UTC, ahsan-ul-haq commented on course_discovery/templates/publisher/email/comment.html
> +        <p>{{ comment }}</p>
Don't we need to translate comment as well?

2016-10-08 10:04 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher_comments/emails.py
> +        subject = _("New comment added in {title}'s {model_name}.").format(
I don't think it would be right to use model name here

2016-10-08 10:33 UTC, awais786 commented on course_discovery/apps/publisher_comments/emails.py
> +        subject = _("New comment added in {title}'s {model_name}.").format(
New comment added in Computer Science's Seat. So it looks clear comment is added in course's seat.

2016-10-10 08:16 UTC, ahsan-ul-haq requested changes

2016-10-10 08:16 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.group_a = factories.GroupFactory(name="Test Group A")
either use `"` or `'`

2016-10-10 08:16 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +        """ Verify that after adding a comment against a course emails send to multiple users
limit doc string 80 characters per line

2016-10-10 08:16 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +    def test_email_without_different_group(self):
add tests before methods

2016-10-10 08:16 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +    def _generate_comment(self, content_object, user, comment):
Why not using factory directly instead of creating this method

2016-10-10 08:16 UTC, ahsan-ul-haq commented on course_discovery/settings/base.py
> +PUBLISHER_FROM_EMAIL = 'test@example.com'
This should be added in test settings.

2016-10-10 08:16 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +from guardian.shortcuts import assign_perm
Alphabetize

2016-10-10 08:16 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/tests/test_model.py
> +from course_discovery.apps.publisher.tests.factories import UserAttributeFactory
If `factories` is imported a line above then why importing `UserAttributeFactory` here?

2016-10-10 15:36 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_model.py
> +from course_discovery.apps.publisher.tests.factories import UserAttributeFactory
UserFactory is coming from core but UserAttributeFactory belongs to publisher.

2016-10-10 15:55 UTC, awais786 commented on course_discovery/settings/base.py
> +PUBLISHER_FROM_EMAIL = 'test@example.com'
This file is importing in test.py. For production I will create the configuration PR for secure vars.

2016-10-11 14:14 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/tests/test_model.py
> +from course_discovery.apps.publisher.tests.factories import UserAttributeFactory
I am talking about `from course_discovery.apps.publisher.tests import factories` one line above this

2016-10-11 15:57 UTC, awais786 commented
@rlucioni @bderusha  Please review this PR. If you guys are busy please let me know I will tag other people in cambridge.

2016-10-11 20:18 UTC, rlucioni commented
@awais786 I'm not able to look at this right now. Please tag @edx/ecommerce when looking for a review from the Cambridge team.

2016-10-11 20:22 UTC, awais786 commented
@edx/ecommerce Please review this PR.

2016-10-13 09:03 UTC, ahsan-ul-haq approved these changes

2016-10-13 14:04 UTC, awais786 commented
@edx/ecommerce Please review this PR.

2016-10-13 14:51 UTC, clintonb requested changes

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +        connection = get_connection()
This is not necessary. Calling `email_msg.send()` will use the default backend.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +            comment(Generic Content Type): Comment Object
`comment (Comment): Comment object`

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +        if comment.content_type.model_class() == CourseRun:
Nit: Add a newline above this to clean this up a bit.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +        if comment.content_type.model_class() == CourseRun:
Also, create a variable for `comment.content_type.model_class()` instead of looking it up twice.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +        log.error(str(e))
Use `log.exception`.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/models.py
Remove this newline.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/models.py
>  class Comments(CommentAbstractModel):
`Comment` (singular)

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +    """ Tests for the Email functionality for course, course-run
"e-mail". Move this to one line.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +        self.user = UserFactory(email='test@test-edx.org')
If you aren't using the custom email address, don't bother adding it to the factory. Doing so is confusing.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +        self.course = factories.CourseFactory()
```python
self.seat = factories.SeatFactory()
self.course_run = self.seat.course_run
self.course = self.course_run.course
```

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +        # For user_2 user-attribute is not created. So he is eligible for mails.
Move this note above the two factory calls.

```python
# NOTE: We intentionally do NOT create an attribute for user_2. By default this user WILL receive email notifications.
```

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +        self.assertEqual(len(mail.outbox[0].to), 2)
This is not necessary given the assertion above.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +    def _assert_data(self, content_object, test_comment, title):
`assert_comment_email_sent`

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +        self.assertIn(test_comment, mail.outbox[0].body.strip())
Make a variable for the body.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +            self.course_run, comment, self.course.title
One line.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +            comment='test',
Remove. This value is never used.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +            comment=test_comment,
Remove. Use the factory-generated text.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +            comment=comment,
Remove. Use the factory-generated text.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +            comment=comment,
Remove. Use the factory-generated text.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +            comment='test',
Remove. This value is never used.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +            comment=test_comment,
Remove. Use the factory-generated text.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +        CommentFactory(
This call is replicated a lot. Make a helper method:

```python
def create_comment(self, content_object):
  return CommentFactory(content_object=content_object, user=self.user, site=self.site)
```

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_views.py
> +        self.seat = factories.SeatFactory(course_run=self.course_run, type=Seat.PROFESSIONAL, credit_hours=0)
Start with the `Seat`, and the factory will make the `Course` and `CourseRun`:

```python
self.seat = factories.SeatFactory(type=Seat.PROFESSIONAL, credit_hours=0)
self.course_run = self.seat.course_run
self.course = self.course_run.course
```

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_views.py
> +        self.assertEqual(len(mail.outbox), 2)
This is a random assertion. Make a separate test for it.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_views.py
> +        for num in range(1, 10):    # pylint: disable=unused-variable
Why 10? Why not 2?

2016-10-13 14:51 UTC, clintonb commented on course_discovery/settings/base.py
> +PUBLISHER_FROM_EMAIL = 'SET-ME-PLEASE'
If someone were to enable emails with this value set, what would happen? If the value is set to `None` will it fail catastrophically (e.g. raised exception)? It would be great if we failed in a way that raised an error, so that issues are not squashed.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/templates/publisher/email/comment.html
> +        <p>{{ comment }}</p>
Nope.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/templates/publisher/email/comment.html
> +        <p>{% trans "Hi," %}</p>
Let's make this more useful:

```html
<p>{{ comment.user.first_name }} commented on a {{ object_type }} belonging to the course {{ course.title }} ({{ course.key }}).
</p>

<p>
{{ comment.comment }}
</p>

<p>
<a href="">View comment</a>
</p>
```

2016-10-13 14:51 UTC, clintonb commented on course_discovery/templates/publisher/email/comment.txt
> +{% load i18n %}
See comment about the HTML version. Make this message actionable.

2016-10-13 14:51 UTC, clintonb commented on course_discovery/templates/publisher/email/email_base.html
> +            <table>
Why are you nesting tables?

2016-10-13 20:07 UTC, awais786 commented on course_discovery/settings/base.py
> +PUBLISHER_FROM_EMAIL = 'SET-ME-PLEASE'
With None it will raise following error.
`Message: 'SESAddressNotVerifiedError: 400 Email address is not verified.\n<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">\n  <Error>\n    <Type>Sender</Type>`

2016-10-13 20:11 UTC, awais786 commented on course_discovery/settings/base.py
> +PUBLISHER_FROM_EMAIL = 'SET-ME-PLEASE'
I have set it to None in base.py.

2016-10-13 20:21 UTC, awais786 commented on course_discovery/settings/base.py
> +PUBLISHER_FROM_EMAIL = 'SET-ME-PLEASE'
In-fact without proper verified email address it will raise the error.

2016-10-14 02:02 UTC, clintonb requested changes

2016-10-14 02:02 UTC, clintonb commented on course_discovery/templates/publisher/email/comment.txt
> +{% trans "Thanks," %}
Drop this. There is nothing to thank anyone for.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/templates/publisher/email/comment.txt
> +{% trans "To view the detail page, visit the following link." %}
```
{% trans "View comment:" %} {{ page_url }}
```

2016-10-14 02:02 UTC, clintonb commented on course_discovery/templates/publisher/email/comment.html
> +        <p>{% trans "Thanks," %}</p>
Drop.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/settings/test.py
> +DISCOVERY_URL_ROOT = 'http://test/'
This is not multi-tenant-friendly. The host should come from the `Site` model.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/settings/base.py
> +PUBLISHER_FROM_EMAIL = None
I noticed there are no docs for the Publisher app in the `docs/` directory. This is a good time to initiate that documentation and document this setting, along with the general email functionality.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_views.py
> +        for num in range(1, 2):    # pylint: disable=unused-variable
If you are going to use the variable use `__`.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +
Third-party imports should be grouped together.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +# pylint: disable=no-member
What is this for? Disabling Pylint for an entire file is rarely needed.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +        log.exception(str(e))
See the docs at https://docs.python.org/3/library/logging.html#logging.Logger.exception. You don't need to touch the exception. You need to log a useful message.

```python
try:
 ...
except Exception:  # pylint: disable=broad-except
  log.exception('Failed to send email notifications for comment %s', comment.id)
```

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +        subject = _("New comment added in {title}'s {model_name}.").format(
1. Single quotes.
2. Remove the period at the end of the subject line.

Check with the PMs to determine if having the course title is more useful than the course ID, or both.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +            page_url = reverse('publisher:publisher_course_run_detail', args=[publisher_obj.id])
`object_path` is a more accurate variable name.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +            page_url = reverse('publisher:publisher_seats_edit', args=[publisher_obj.id])
Why does this point to the edit page instead of the detail page?

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +            'page_url': urljoin(settings.DISCOVERY_URL_ROOT, page_url)
```python
'https://{host}{path}'.format(host=comment.site.domain.strip('/'), path=object_path)
```

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher/urls.py
> -    url(r'^course_runs/(?P<pk>\d+)/$', views.CourseRunDetailView.as_view(), name='publisher_course_run_detail'),
Now would be a great time to group/namespace these URLs. Waiting until later will be painful. See https://github.com/edx/edx-analytics-dashboard/blob/master/analytics_dashboard/courses/urls.py for an example of grouping. This doesn't have to be done in this PR, but it should happen soon.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher/urls.py
>      url(r'^course_runs/new$', views.CreateCourseRunView.as_view(), name='publisher_course_runs_new'),
Use a trailing slash for all URLs. (Not a prerequisite for merging this PR.)

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_model.py
> +    def _assert_false_permissions(self, user, course):
```python
def assert_user_cannot_view_course(self, user, course):
  """ Asserts the user can NOT view the course. """
  ...
```

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_model.py
> +    def _assert_true_permissions(self, user, course):
```python
def assert_user_can_view_course(self, user, course):
  """ Asserts the user can view the course. """
  ...
```

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher/models.py
>          return available_groups[0] if available_groups else None
Why only one group? It's not clear what this method is doing. Also, a property name should not be prefixed with `get_` or `set_`.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher/models.py
>          return available_groups[0] if available_groups else None
Additionally, `assign_user_groups` above is only used in tests. It should be removed.

2016-10-14 02:02 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_model.py
> +        """ Verify that method returns the institution against the course."""
Please clarify this docstring, and the one for the method being tested. It is not clear what the method is returning.

2016-10-14 06:14 UTC, awais786 commented on course_discovery/apps/publisher_comments/emails.py
> +        log.exception(str(e))
I did that to see the exact message. I have updated this now.

2016-10-14 07:11 UTC, awais786 commented on course_discovery/apps/publisher/urls.py
> -    url(r'^course_runs/(?P<pk>\d+)/$', views.CourseRunDetailView.as_view(), name='publisher_course_run_detail'),
I have created the ticket for this https://openedx.atlassian.net/browse/ECOM-6109.

2016-10-14 09:38 UTC, awais786 commented on course_discovery/apps/publisher_comments/models.py
>  class Comments(CommentAbstractModel):
I will do this change in other story [ECOM-6110](https://openedx.atlassian.net/browse/ECOM-6110). Otherwise this PR will become too large.

2016-10-14 10:05 UTC, awais786 commented on course_discovery/apps/publisher_comments/emails.py
> +            page_url = reverse('publisher:publisher_seats_edit', args=[publisher_obj.id])
At the moment all pages are in re-designing phase. Once we implement all pages then we will update these links accordingly.

2016-10-14 12:42 UTC, clintonb commented on course_discovery/apps/publisher/mixins.py
> -            publisher_object.assign_user_groups(user)
If this is the same method as below, I was wrong about it not being used, and it should remain.

2016-10-14 12:45 UTC, clintonb commented on course_discovery/apps/publisher/models.py
>          return available_groups[0] if available_groups else None
This docstring is much better, but now I'm confused as to why you're only returning the first group. Clearly an assumption is being made about group ordering. What is that assumption? How can we go from assumption to certainty?

2016-10-17 10:50 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
> -            publisher_object.assign_user_groups(user)
I have remove this method. Because previously we were assigning permissions according to the request.user's group. But now implementation has been changes and author will choose the group/institution from the dropdown.

2016-10-17 10:56 UTC, awais786 commented on course_discovery/apps/publisher/models.py
>          return available_groups[0] if available_groups else None
At the moment course will belong to the one institution only. 
And course creation page has the the dropdown to select the group. According to the group/institution only that group users can view that object.  So its not possible that course will belong with multiple groups. 

@bderusha FYI

2016-10-17 10:58 UTC, awais786 commented
@clintonb please review this PR again.

2016-10-17 13:13 UTC, clintonb requested changes
@awais786 you've asked for another review; but, you haven't addressed all of the comments from the earlier review. Please address all comments—if you aren't going to accept the recommended change, just provide a reason why not—before requesting additional reviews.

2016-10-17 13:13 UTC, clintonb commented on course_discovery/apps/publisher/models.py
>          return available_groups[0] if available_groups else None
I courses can only be associated with one institution that should be fully enforced, or you should fully support multiple institutions in the backend and enforce the single institution at the front-end level. Besides being confusing to later developers, I can see this leading to confusion and errors in the future due to the single group assumption only being enforced here (and not informing the user/developer of the error when they attempt to add another institution).

2016-10-17 13:13 UTC, clintonb commented on course_discovery/apps/publisher/models.py
>      def assign_permission_by_group(self, institution):
Unrelated: why is this a public method? I would expect this to be a private method called only only when modifying institutions. See https://docs.djangoproject.com/en/1.10/ref/signals/#django.db.models.signals.m2m_changed.

2016-10-17 13:13 UTC, clintonb commented on course_discovery/apps/publisher/models.py
> +    def get_group_users(self):
This is only used in the method below. This doesn't need exist, and it's misnamed—properties should not be prefixed with `get_` or `set_`.

2016-10-17 13:24 UTC, awais786 commented on course_discovery/apps/publisher/urls.py
>      url(r'^course_runs/new$', views.CreateCourseRunView.as_view(), name='publisher_course_runs_new'),
I have created the seperate ticket for this change.
https://openedx.atlassian.net/browse/ECOM-6109

2016-10-17 14:35 UTC, awais786 commented on course_discovery/apps/publisher/models.py
>      def assign_permission_by_group(self, institution):
I did not understand the purpose of m2m_changed here. 
[institution](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/publisher/forms.py#L49) is form field.

2016-10-17 14:40 UTC, clintonb commented on course_discovery/apps/publisher/models.py
>      def assign_permission_by_group(self, institution):
Institution is a form field that ultimately sets a value on the model. If that is the field that truly determines which institutions can access the course, you should be triggering permissions based on changes to that field. For example, say you need to modify the institution via Django admin. Your current implementation will not support changing permissions in that case.

If you implement permissions at the model level you don't have to worry about any of these issues, because you've implemented at the lowest possible level.

2016-10-17 14:42 UTC, awais786 commented on course_discovery/apps/publisher/models.py
>      def assign_permission_by_group(self, institution):
And institution value is not saving in db its just use to assign the permission on the course.

2016-10-17 14:51 UTC, clintonb commented on course_discovery/apps/publisher/models.py
>      def assign_permission_by_group(self, institution):
That does not seem ideal, and opens up interesting permissions issues. For example, say you have a course owned by MIT. If permissions are not directly linked to the value of the institution field, you could end up in a situation where the MIT-owned course is *not* visible to MIT users or made visible to non-MIT institution users.

2016-10-17 18:40 UTC, awais786 commented on course_discovery/apps/publisher/models.py
>      def assign_permission_by_group(self, institution):
For this scenario [django-guardian->get-groups-with-perms](http://django-guardian.readthedocs.io/en/stable/api/guardian.shortcuts.html#get-groups-with-perms)  provides us the group against the course. But I agree with you this value should be save in db. This is what we did earlier but later dropped the field after some discussion. I am adding @bderusha here for his thoughts and if all agrees here I will create the separate ticket to store  the group against a course and it should be OneToOneField because each course can associated with one group only Or It can be manytomany as well if in future multiple groups can be assigned to one course.

2016-10-17 18:45 UTC, awais786 commented on course_discovery/settings/base.py
> +PUBLISHER_FROM_EMAIL = None
Ticket for documentation https://openedx.atlassian.net/browse/ECOM-6139

2016-10-17 18:58 UTC, clintonb commented on course_discovery/settings/base.py
> +PUBLISHER_FROM_EMAIL = None
Umm...this hasn't yet merged. The documentation should be part of this commit. We've gotten quite lax with our documentation practices over the last few months. A ticket is nice, but I can easily see that ticket being ignored for "higher priority" work in the future.

2016-10-17 19:19 UTC, awais786 commented on course_discovery/templates/publisher/email/comment.txt
> +{% load i18n %}
Done according to the HTML.

2016-10-17 19:20 UTC, awais786 commented on course_discovery/settings/base.py
> +PUBLISHER_FROM_EMAIL = None
Fine I will add the documentation in this commit.

2016-10-18 11:05 UTC, awais786 commented on course_discovery/settings/base.py
> +PUBLISHER_FROM_EMAIL = None
I have added the documentation part here. I just add one setting variable here because we have already defined all variables in private.py.

2016-10-18 11:14 UTC, awais786 commented on course_discovery/apps/publisher/models.py
>          return available_groups[0] if available_groups else None
I have created a separate ticket for this purpose.
https://openedx.atlassian.net/browse/ECOM-6142

2016-10-18 11:14 UTC, awais786 commented on course_discovery/apps/publisher/models.py
>      def assign_permission_by_group(self, institution):
I have created a separate ticket for this purpose.
https://openedx.atlassian.net/browse/ECOM-6142

2016-10-18 19:11 UTC, awais786 commented
@clintonb I have double checked to make sure all requested changes are fixed. I have created few tickets to fix all things separately.  I have added translations files and initial documentation file also.

2016-10-19 16:57 UTC, awais786 commented
@clintonb I have double checked to make sure all requested changes are fixed. I have created few tickets to fix all things separately. I have added translations files and initial documentation file also.

2016-10-19 17:43 UTC, clintonb reviewed
I am headed out on vacation. Someone else from @edx/ecommerce needs to finish reviewing.

2016-10-19 17:43 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.user1 = UserFactory(email='test@example.com')
Given that none of these names matter to your tests, they should be removed. It's extraneous information.

2016-10-19 17:43 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_model.py
> +        self._assign_assert()
This is called once. It doesn't need to be a separate method.

2016-10-19 17:43 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +            subject = 'New comment added in Course-run : {title}-{pacing_type}-{start}'.format(
Mark for translation.

2016-10-19 17:43 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +            subject = 'New comment added in Seat : {title}-{pacing_type}-{start}-{type}'.format(
Mark for translation.

2016-10-19 17:43 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +            subject = 'New comment added in Course : {title}'.format(title=course.title)
Mark for translation.

2016-10-19 17:43 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +        email_msg.attach_alternative(html_content, "text/html")
Single quotes.

2016-10-19 18:43 UTC, awais786 commented
@edx/ecommerce Please review this PR. All requested changes are fixed.

2016-10-20 13:32 UTC, awais786 commented
@edx/ecommerce Please review this PR. @clintonb already reviewed this PR but it needs final review.

2016-10-20 13:40 UTC, awais786 commented
@bderusha Please review this PR.

2016-10-20 15:35 UTC, bderusha requested changes

2016-10-20 15:35 UTC, bderusha commented on course_discovery/apps/publisher_comments/emails.py
> +        elif comment_class == Seat:
Seats are not a top level object that we have pages for.  We should not be emailing people links to seat pages.  A seat change should result in an email about the course_run

2016-10-20 15:35 UTC, bderusha commented on course_discovery/apps/publisher_comments/emails.py
> +        if comment_class == CourseRun:
Rather than checking for the class, the duck-typing approach would be to give each class a method which can be called that returns the appropriate data.

e.g. `.url_path` or `.email_subject`

2016-10-20 15:35 UTC, bderusha commented on course_discovery/apps/publisher_comments/emails.py
> +def setup_email_for_comment(comment):
Method name could be better.  This method does more than just setup the email.  It sends it too.  That is not clear

2016-10-20 15:59 UTC, awais786 commented on course_discovery/apps/publisher_comments/emails.py
> +        elif comment_class == Seat:
Do you mean comment cannot be made against a seat object ?

2016-10-20 16:27 UTC, bderusha commented on course_discovery/apps/publisher_comments/emails.py
> +        elif comment_class == Seat:
Correct, based on the new designs I don't see how this is possible

2016-10-20 16:29 UTC, awais786 commented on course_discovery/apps/publisher_comments/emails.py
> +        if comment_class == CourseRun:
@bderusha each comment hold the content type of different models. That's why I am checking the class. And there is no data which we need here.

2016-10-20 16:33 UTC, awais786 commented on course_discovery/apps/publisher_comments/emails.py
> +        elif comment_class == Seat:
Removed

2016-10-24 16:34 UTC, awais786 commented
@edx/ecommerce Please review this PR.

2016-10-24 21:01 UTC, awais786 commented
@clintonb Please review this PR.

2016-10-25 01:45 UTC, clintonb requested changes

2016-10-25 01:45 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.group_a = factories.GroupFactory(name='Test Group A')
Unless these names are relevant for testing, they should be removed. They are extraneous noise.

2016-10-25 01:45 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_model.py
> +        """ Verify that method returns the emails against the course group."""
Verify the method returns the email addresses of users who are permitted to access the course AND have not disabled email notifications.

2016-10-25 01:45 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_model.py
> +        """ Verify that method returns the institution against the course."""
Verify the method returns groups permitted to access the course.

2016-10-25 01:45 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_model.py
> +        # After making user1 enable_email_notification as false it should not appear in
The email addresses of users who have disabled email notifications should NOT be returned.

2016-10-25 01:45 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +        self.user = UserFactory(first_name='test-user1')
The factory will generate a first name for you. See https://github.com/edx/course-discovery/pull/396.

2016-10-25 01:45 UTC, clintonb commented on course_discovery/apps/publisher_comments/tests/test_views.py
> +        self.user = UserFactory(is_staff=True, is_superuser=True, email='test@example.com')
The factory will generate a email for you. See https://github.com/edx/course-discovery/pull/396.

2016-10-25 01:45 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +            subject = _('New comment added in Course-run : {title}-{pacing_type}-{start}').format(
Remove the space before the colon.

2016-10-25 01:45 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +            subject = _('New comment added in Course : {title}').format(title=course.title)
Remove the space before the colon.

2016-10-25 01:45 UTC, clintonb commented on course_discovery/apps/publisher_comments/emails.py
> +            subject = _('New comment added in Course-run : {title}-{pacing_type}-{start}').format(
"course run" (no hyphen)

2016-10-25 01:45 UTC, clintonb commented on course_discovery/templates/publisher/email/comment.txt
> +{% blocktrans with first_name=comment.user.first_name object_type=object_type|lower title=course.title number=course.number %}
Use the `trimmed` option to eliminate whitespace. See https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#blocktrans-template-tag for more info. Remember to update the translations, and ensure there are no newline characters in the source files, once this change is made.

2016-10-25 01:45 UTC, clintonb commented on course_discovery/templates/publisher/email/email_base.html
> +<html lang="en">
This content will be translated. The language should be set to the current/request language. See https://docs.djangoproject.com/en/dev/topics/i18n/translation/#get-current-language.

2016-10-25 01:45 UTC, clintonb commented on docs/publisher.rst
> +===============
The underlining elements should not extend beyond the width of the text being underlined.

2016-10-25 01:45 UTC, clintonb commented on docs/publisher.rst
> +-----------------------------------
The underlining elements should not extend beyond the width of the text being underlined.

2016-10-25 01:45 UTC, clintonb commented on docs/publisher.rst
> +You can use different email backend for sending emails as defined in django configuration.
Since the publisher tool uses the built-in Django email functionality, any Django email backend can be used. For info on configuring email backends see https://docs.djangoproject.com/en/1.10/topics/email/.

We at edX.org use Amazon's Simple Email Service (SES) (https://aws.amazon.com/ses/). If you'd also like to use SES, the django-ses (https://github.com/django-ses/django-ses) is installed as a base requirement. Simply define values for the settings below to configure the backend.

2016-10-25 01:45 UTC, clintonb commented on docs/publisher.rst
> +The ``publisher`` app at :file:`course_discovery/apps/publisher` is for A single point information management
The ``publisher`` tool is an information management system that supports the course authoring, review, and approval workflow. The tool manages courses as they transition through the lifecycle of creation (across various subsystems), release/publication to the edX.org marketing site, and eventual retirement/archival.

Note: This app is primarily built for the edX.org use case.

2016-10-25 01:45 UTC, clintonb commented on docs/publisher.rst
> +For emails functionality you can update your local settings (ideally in :file:`course_discovery/settings/private.py`).
The publisher tool supports notifying responsible parties when users comment on courses and course runs. Notifications are sent via Django's email backend. In order to send emails the `enable_publisher_comment_email_notifications` switch must be activated, and the following settings must be defined:

2016-10-25 01:45 UTC, clintonb commented on course_discovery/apps/publisher_comments/models.py
> +    if waffle.switch_is_active('enable_emails'):
1. Rename this to `'enable_publisher_comment_email_notifications'` so that is perfectly clear what this switch affects.
2. Add a migration creating this switch, and defaulting it to the inactive state.

2016-10-25 01:45 UTC, clintonb commented on docs/publisher.rst
> +For default email backend SMTP, following settings are require
Remove this section and simply link to the Django docs.

2016-10-25 01:45 UTC, clintonb commented on course_discovery/templates/publisher/email/comment.html
> +<br>
This doesn't seem necessary.

2016-10-25 04:09 UTC, awais786 commented on course_discovery/apps/publisher_comments/models.py
> +    if waffle.switch_is_active('enable_emails'):
I renamed this to `enable_publisher_email_notifications` so that it can be use for all kinds of emails.

2016-10-25 14:42 UTC, awais786 commented
@clintonb PR is ready for final review.

2016-10-25 14:48 UTC, clintonb approved these changes

2016-10-25 14:48 UTC, clintonb commented on course_discovery/apps/publisher/migrations/0013_create_enable_email_notifications_switch.py
> +        migrations.RunPython(create_switch, reverse_code=delete_switch),
Nit: No need for the kwarg: `migrations.RunPython(create_switch, delete_switch),`

2016-10-25 14:48 UTC, clintonb commented on docs/publisher.rst
> +We at edX.org use Amazon's Simple Email Service (SES) (https://aws.amazon.com/ses/). If you'd also like to use SES, the django-ses (https://github.com/django-ses/django-ses) is installed as a base re
The URLs in parentheses should be setup as proper RST links.

2016-10-25 14:48 UTC, clintonb commented on docs/publisher.rst
> +https://docs.djangoproject.com/en/1.10/topics/email/#smtp-backend
You don't really need this section. We've already linked to the Django docs. We only provide SES info because we include that functionality.

2016-10-26 08:53 UTC, merged