feat: introduce field trackers in Course and Program models
openedx/course-discovery pull request #3771
Opened 2023-01-22 22:07 UTC by ansabgillani

[PROD-3083](https://2u-internal.atlassian.net/browse/PROD-3083)

2023-01-23 11:35 UTC, Ali-D-Akbar requested changes
Tests and description require some updated.
Also, please add some mechanism to test these changes on local and how this can be used to filter changed objects.

2023-01-23 11:35 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/model_utils.py
> +def has_model_changed(field_tracker, external_keys=[]):
Docstring for the file

2023-02-22 11:03 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +        else:
This needs a comment/docstring as to why double if is needed.

2023-02-22 11:05 UTC, DawoudSheraz reviewed
Most changes make sense.  Although PR can use some extra unit tests for Fieldtracker and last modified testing

2023-02-24 09:33 UTC, Ali-D-Akbar approved these changes
Great work. Looks very promising to fix our underlying issue. 👍

2023-03-06 14:06 UTC, AliAdnanSohail approved these changes

2023-03-10 06:33 UTC, zawan-ila approved these changes

2023-03-17 09:29 UTC, merged