feat: add course_type in AdditionalMetadata
openedx/course-discovery pull request #3773
Opened 2023-01-23 07:34 UTC by Ali-D-Akbar

[PROD-3101](https://2u-internal.atlassian.net/browse/PROD-3101)
Adds a new `course_type` field in AdditionalMetadata for exec-ed courses.

2023-01-23 13:13 UTC, AliAdnanSohail requested changes

2023-01-23 13:13 UTC, AliAdnanSohail commented on course_discovery/apps/course_metadata/choices.py
> +    ShortCourse = ChoiceItem('short-course', _('Short Course'))
choices are 
`short_course`
`sprint`
`course_stack`

please replace `-` to `_`

2023-01-23 13:19 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/choices.py
> +    ShortCourse = ChoiceItem('short-course', _('Short Course'))
done

2023-01-24 04:18 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +    external_course_type = models.CharField(
suggestion: Since this field is mainly to identify the various external content types, the field can be renamed to something on the terms of "course_marketing_type, course_marketing_category", etc. Plus, since this field is. being added in AdditionalMetadata which is not restricted to ExecEd, please remove references to ExecEd in field's help text.

2023-01-24 04:19 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/choices.py
> +class ExecutiveEducationCourseType(DjangoChoices):
Rather than restricting to ExecEd, this should be the external products' marketing category. This will allow adding. Bootcamp here too.

2023-01-24 06:10 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/models.py
> +    external_course_type = models.CharField(
I think using the _external_ keyword along with _course_marketing_type_ would be better. I'll remove references to exec ed tho.

2023-01-24 09:13 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/choices.py
> +class ExecutiveEducationCourseType(DjangoChoices):
Done

2023-01-24 11:17 UTC, AliAdnanSohail commented on course_discovery/apps/course_metadata/models.py
> +    external_course_type = models.CharField(
@Ali-D-Akbar - Can we use `external_marketing_type` name for this? remove `course` from the field name, because this field is in additional_metadata and we can use this model for Program as well

2023-01-24 17:41 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/choices.py
> +    CourseStack = ChoiceItem('course_stack', _('Course Stack'))
bootcamp missing. Or do we plan to keep it null for Bootcamps?

2023-01-24 17:42 UTC, DawoudSheraz approved these changes
Once CI is green.

2023-01-24 17:48 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/choices.py
> +    CourseStack = ChoiceItem('course_stack', _('Course Stack'))
For now, I guess keeping it null makes sense as there isn't any specific external course type for this.

2023-01-25 09:16 UTC, AliAdnanSohail approved these changes

2023-01-26 06:41 UTC, merged