feat: get products details using get smarter api client
openedx/course-discovery pull request #3777
Opened 2023-01-26 20:00 UTC by AfaqShuaib09

[PROD-3116](https://2u-internal.atlassian.net/browse/PROD-3116)

###Overview:
This PR covers the get products details from getsmarter API using the getsmarter API client. It also covers the generation oauth2 token for the getsmarter API client. The access token is generated by the getsmarter API and is valid for 24 hours plus it has a functionality to get cache the access token.

#### Todos
- [ ] Add environment variables to the `edx-internal` repo for getsmarter API (both stage and prod)

#### Testing Instructions
- To test it locally set the following variables in your `private.py` file
    - `GETSMARTER_CLIENT_ID`
    - `GETSMARTER_CLIENT_SECRET`
    - `GETSMARTER_API_URL`
    - `GETSMARTER_PRODUCTS_DETAILS_URL`
    - `GETSMARTER_PROVIDER_URL`

2023-01-26 20:00 UTC, openedx-webhooks commented
Thanks for the pull request, @AfaqShuaib09!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-01-27 17:49 UTC, mphilbrick211 commented
Hi @AfaqShuaib09! Just checking to see if this is ready for review? If so, you'll need to resolve the branch date error first. Thanks!

2023-01-31 13:49 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +    @mock.patch('course_discovery.apps.course_metadata.utils.GetSmarterEnterpriseApiClient')
responses.activate is missing.

2023-01-31 13:51 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +def get_products_details_using_getsmarter_client(getsmarter_client_credentials):
nit: fetch_getsmarter_products.

2023-01-31 13:51 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +
unnecessary empty line.

2023-01-31 13:52 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +            logger.info(f"Products found in API response: {response}")
response dict will be very large. Ideally, print the length of response.

2023-01-31 13:53 UTC, DawoudSheraz reviewed
Left a few comments.

2023-02-03 16:48 UTC, openedx-webhooks commented
Thanks for the pull request, @AfaqShuaib09!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-02-08 08:45 UTC, ansabgillani commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +    @pytest.mark.skip(reason='elasticsearch has some sort of failure and returns 0 records with status 400')
use `unittest.skip`

2023-02-08 08:45 UTC, ansabgillani approved these changes

2023-02-08 14:29 UTC, Ali-D-Akbar requested changes
Some changes that can be done to improve the code quality.

2023-02-08 14:29 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/utils.py
> +    """ Returns the products details for the getsmarter API """
nit: from the getsmarter API

2023-02-08 14:29 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/utils.py
> +        logger.error(f"Failed to retrieve products from getsmarter API: {ex}")
suggestion: can these messages be a bit different?

2023-02-08 14:29 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/utils.py
> +        provider_url=getsmarter_client_credentials['PROVIDER_URL'], api_url=getsmarter_client_credentials['API_URL']
Why are we still sending these settings through arguments? Aren't these settings available from edx-internal?

2023-02-08 14:29 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +        self.getsmarter_client_credentials = settings.GETSMARTER_CLIENT_CREDENTIALS
Suggestion: We can make separate dict in `settings/test.py`

2023-02-08 14:29 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/utils.py
> +        provider_url=getsmarter_client_credentials['PROVIDER_URL'], api_url=getsmarter_client_credentials['API_URL']
You can use them directly from `settings.GETSMARTER_CLIENT_CREDENTIALS.CLIENT_ID`

2023-02-08 20:55 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +        self.getsmarter_client_credentials = settings.GETSMARTER_CLIENT_CREDENTIALS
Done

2023-02-08 20:55 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/utils.py
> +        provider_url=getsmarter_client_credentials['PROVIDER_URL'], api_url=getsmarter_client_credentials['API_URL']
Removed client credentials from functional and passed them directly to the functiom
`settings..GETSMARTER_CLIENT_CREDENTIALS` is a dict so i think we can't refer its keys like object attribute

2023-02-09 04:09 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/utils.py
> +        provider_url=getsmarter_client_credentials['PROVIDER_URL'], api_url=getsmarter_client_credentials['API_URL']
Ah yes, it's a dict so you can use it in a `dict['key']` way.

2023-02-09 06:26 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_utils.py
> +        self.getsmarter_client_credentials = settings.GETSMARTER_CLIENT_CREDENTIALS
nit: We dont need self.__ variable. Use settings variable directly where needed.

2023-02-09 06:27 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/utils.py
> +    method = 'GET'
no need to define this special variable.

2023-02-09 06:28 UTC, DawoudSheraz commented on course_discovery/settings/test.py
> +}
missing end of file line.

2023-02-09 06:28 UTC, DawoudSheraz approved these changes
- A few nit comments
- Please update PR description to include the tests of skipped test

2023-02-13 15:49 UTC, Ali-D-Akbar approved these changes

2023-02-13 17:12 UTC, merged

2023-02-13 17:12 UTC, openedx-webhooks commented
@AfaqShuaib09 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/3777&entry.1484655318=https://github.com/AfaqShuaib09&entry.752974735=2023-01-26+20:00&entry.1917517419=2023-02-13+17:12&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->