Added email notification ON/OFF switch.
openedx/course-discovery pull request #378
Opened 2016-10-08 12:44 UTC by waheedahmed

[ECOM-5408] (https://openedx.atlassian.net/browse/ECOM-5408)

As a Publisher user, I would like to be able to easily turn email notifications ON/OFF from the header.

**Design:** http://cim31f.axshare.com/course_runs.html

**AC's:**
Validate I can access the Email notification ON/OFF setting from the userid link
Validate I can turn the setting ON/OFF from the userid link on the header

**Screenshots:**
<img width="502" alt="screen shot 2016-10-08 at 5 41 56 pm" src="https://cloud.githubusercontent.com/assets/2851134/19213215/99d9aa5c-8d7e-11e6-8826-7a3f2c1fb24c.png">

<img width="457" alt="screen shot 2016-10-08 at 5 43 17 pm" src="https://cloud.githubusercontent.com/assets/2851134/19213222/c12badd0-8d7e-11e6-9806-d92bf336b75a.png">

2016-10-08 12:45 UTC, waheedahmed commented
@awais786 @ahsan-ul-haq @tasawernawaz @jareerahsan Please review.

2016-10-13 14:41 UTC, ahsan-ul-haq requested changes

2016-10-13 14:41 UTC, ahsan-ul-haq commented on course_discovery/apps/core/tests/test_context_processors.py
>  from course_discovery.apps.core.context_processors import core
alphabetize

2016-10-13 14:41 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/tests/test_utils.py
> +from course_discovery.apps.publisher.utils import is_email_notification_enabled
alphabetize

2016-10-13 14:41 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertEqual(is_email_notification_enabled(user), False)
why not using `self.user`

2016-10-13 14:41 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/views.py
> +        on_off_text = _('OFF')
can't you use enabled/disabled.

2016-10-13 14:41 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/utils.py
> +
add arguments in docstring as well

2016-10-14 07:35 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_utils.py
> +from course_discovery.apps.publisher.utils import is_email_notification_enabled
@ahsan-ul-haq Whats wrong in it?

2016-10-14 07:39 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertEqual(is_email_notification_enabled(user), False)
@ahsan-ul-haq I'm getting the same user at line 968, if we don't get it again, ```attributes``` attr will not be available. Adding a explaining comment.

2016-10-14 08:00 UTC, waheedahmed commented
@ahsan-ul-haq Addressed your comments, please take another look.

2016-10-14 10:34 UTC, ahsan-ul-haq requested changes

2016-10-14 10:34 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/tests/test_utils.py
> +# pylint: disable=no-member
Don't disable pylint for entire file.

2016-10-14 10:34 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/tests/test_utils.py
> +        """ Test email notification is enabled for the user."""
Test is email notification enabled for the user or not.

2016-10-14 10:52 UTC, ahsan-ul-haq approved these changes

2016-10-14 10:53 UTC, waheedahmed commented
@edx/ecommerce Please review this PR.

2016-10-14 12:52 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertEqual(is_email_notification_enabled(user), False)
This the correct behavior for reloading objects from the database. Please add a comment above the get() call explaining what you're doing.

2016-10-14 13:16 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertEqual(is_email_notification_enabled(user), False)
Done

2016-10-14 13:31 UTC, clintonb requested changes

2016-10-14 13:31 UTC, clintonb commented on course_discovery/apps/core/context_processors.py
> +from course_discovery.apps.publisher.utils import is_email_notification_enabled
The `core` app should never have dependencies on other local apps. This app is intended to house the functionality needed by other apps and should be free of dependencies that might lead to circular dependencies down the line. 

Move this to a context processor in the `publisher` app.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_utils.py
> +from course_discovery.apps.publisher.utils import is_email_notification_enabled
I see nothing wrong here.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_utils.py
> +        self.assertEqual(is_email_notification_enabled(self.user), True)
Move this to its own test case.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_utils.py
> +        # Create a `UserAttribute` object for user
This comment is not necessary.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_utils.py
> +        # Verify that by default email notification is enabled for the user with `UserAttribute`
Suggested edit: Verify notifications are enabled for users with associated attributes, but no explicit value set for the `enable_email_notification` attribute.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
>  from course_discovery.apps.publisher_comments.tests.factories import CommentFactory
Alphabetize.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertEqual(is_email_notification_enabled(user), False)
Also, just reassign `self.user`.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        response = self.client.post(self.toggle_email_settings_url, data={'is_enabled': 'true'})
De-dupe. Move this and the lines below to an assertion method.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/apps/publisher/urls.py
> +        r'^user/toggle/email_settings/$',
This is fine for now. The next time a configuration toggle is added, this should be refactored to a RESTful API that handles all user attributes.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        switch_label = _('OFF')
This endpoint should not care about display values. That should be handled at the display layer in the template or JavaScript.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        user_attribute, is_created = UserAttributes.objects.get_or_create(  # pylint: disable=unused-variable
Instead of disabling pylint, set the unused variables name to `__`.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/static/js/jquery.cookie.js
> +/*!
This is a pretty old version of this library. See https://github.com/js-cookie/js-cookie. Also, front-end dependencies should be managed by `bower`, not committed directly to the repository.

2016-10-14 13:31 UTC, clintonb commented on course_discovery/static/js/utils.js
> +        $title = $(".nav-account").find('.title');
Why was this changed?

2016-10-14 13:31 UTC, clintonb commented on course_discovery/static/js/utils.js
> +    $("#email-switch").change(function(e) {
This doesn't belong in `utils.js`. That name implies a collection ignore utility functions. Much of the code in this file should be organized in `publisher/views/navbar.js`.

2016-10-17 19:13 UTC, waheedahmed commented
@clintonb Please take another look.

2016-10-19 17:38 UTC, clintonb reviewed
I am headed out on vacation. Someone else from @edx/ecommerce will need to review.

2016-10-19 17:38 UTC, clintonb commented on course_discovery/apps/publisher/context_processors.py
> +def publisher(_request):
Use `request`. The `_` prefix is reserved for _unused_ variables.

2016-10-19 17:38 UTC, clintonb commented on course_discovery/apps/publisher/context_processors.py
> +    """ Site-wide context processor. """
Remove. This docstring doesn't add any value. It's obvious based on the file what this is.

2016-10-19 17:38 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_context_processors.py
> +        self.assertDictEqual(publisher(request), {'is_email_notification_enabled': True})
What about the negative case? Also, you should be comparing with `course_discovery.apps.publisher.utils.is_email_notification_enabled`.

2016-10-19 17:38 UTC, clintonb commented on course_discovery/static/js/publisher/views/navbar.js
> +            _this = this;
Why are you doing this?

2016-10-19 17:38 UTC, clintonb commented on course_discovery/static/js/publisher/views/navbar.js
> +            isEnabled = true
Missing semi-colon.

2016-10-19 17:38 UTC, clintonb commented on course_discovery/static/js/publisher/views/navbar.js
> +        if(_this.checked) {
Why not set this in the variable declaration above?

2016-10-20 08:33 UTC, waheedahmed commented
@edx/ecommerce Can someone else take a final look on this PR? Clinton is out for couple of days.

2016-10-20 13:42 UTC, waheedahmed commented
@bderusha Please take a final look on this PR.

2016-10-20 14:59 UTC, bderusha approved these changes

2016-10-21 07:40 UTC, merged

2016-12-02 16:59 UTC, clintonb commented on course_discovery/urls.py
> +    url(r'^i18n/', include('django.conf.urls.i18n')),
Why is this here? It is not used correctly. See https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#language-prefix-in-url-patterns.