Afaq/prod 3117
openedx/course-discovery pull request #3785
Opened 2023-02-01 09:06 UTC by AfaqShuaib09

### [PROD-3117](https://2u-internal.atlassian.net/browse/PROD-3117)

2023-02-01 09:06 UTC, openedx-webhooks commented
Thanks for the pull request, @AfaqShuaib09!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-02-01 20:50 UTC, mphilbrick211 commented
Hi @AfaqShuaib09! Thank you for your contribution! It looks like your CLA is all set, so you should be good to re-run the failing tests.

2023-02-07 14:44 UTC, mphilbrick211 commented
Hi @AfaqShuaib09 - just checking in to see if this pull request is ready to review? If so, you'll need to address the branch date error. Thanks!

2023-02-09 07:14 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +            '--getsmarter_flag',
nit: use_getsmarter_api_client

2023-02-16 07:47 UTC, Ali-D-Akbar reviewed
Added some comments to be addressed before approval.

2023-02-16 07:47 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +                    product['universityAbbreviation'] = OrganizationMapping.objects.get(external_organization_code=product['universityAbbreviation']).organization.key  # pylint: disable=line-too-long
nit: the readability can be improved here by breaking the link.

2023-02-16 07:47 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +                    product['universityAbbreviation'] = OrganizationMapping.objects.get(external_organization_code=product['universityAbbreviation']).organization.key  # pylint: disable=line-too-long
Also, add an inline comment explaining what this check is all about.

2023-02-16 07:47 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/management/commands/tests/test_populate_executive_education_data_csv.py
> +                CommandError, 'auth_token or dev_input_json or getsmarter_flag should be provided to perform data transformation.'  # pylint: disable=line-too-long
I think breaking the line is better than disabling pylint. 🤔

2023-02-16 07:47 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/models.py
> +class OrganizationMapping(models.Model):
dostring missing

2023-02-16 07:47 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/models.py
> +            Source and external_organization_code are unique together
nit: one extra tab has been added here.

2023-02-16 07:47 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/tests/factories.py
> +class OrganizationMappingFactory(factory.django.DjangoModelFactory):
docstring missing

2023-02-16 07:47 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/utils.py
> +                                                 url=settings.GETSMARTER_CLIENT_CREDENTIALS['PRODUCTS_DETAILS_URL']+
Use fstring instead of concatenating string.

2023-02-16 07:47 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/models.py
> +        unique_together = ('source', 'external_organization_code')
The docstring doesn't seem necessary here as it is obvious by this line

You can write this instead:
```
        """
        Meta options.
        """
```

2023-02-16 08:14 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/factories.py
> +class OrganizationMappingFactory(factory.django.DjangoModelFactory):
None of the model factory class containing docstring. Should I add it here?

2023-02-17 09:14 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +                    product['universityAbbreviation'] = OrganizationMapping.objects.get(external_organization_code=product['universityAbbreviation']).organization.key  # pylint: disable=line-too-long
inline comment added, if i try to break the line, it shows me pylint quality error `if condition and normal line at the same level` and when i indent this statement, it shows `overindented line quality error`

2023-02-20 16:06 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +                    product['universityAbbreviation'] = OrganizationMapping.objects.get(external_organization_code=product['universityAbbreviation']).organization.key  # pylint: disable=line-too-long
This is very hard to read. Convert this into a util method.

2023-02-20 16:07 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +                    product['universityAbbreviation'] = OrganizationMapping.objects.get(external_organization_code=product['universityAbbreviation']).organization.key  # pylint: disable=line-too-long
Also, add proper logging if a mapping record is not found.

2023-02-20 16:09 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +    Model to map external organization codes to edX/Discovery organizations codes.
Instead of edX/Discovery, add appropriate docstrings to mention how to map internal organizations with corresponding orgs in an external product source

2023-02-20 16:10 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +    external_organization_code = models.CharField(max_length=255)
please add help text on this field.

2023-02-22 07:55 UTC, AliAdnanSohail requested changes

2023-02-22 07:55 UTC, AliAdnanSohail commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +    def map_external_org_code_to_internal_org_code(self, external_org_code):
@AfaqShuaib09 - We should pass `source` as well, because we are getting more sources in future and there could b some case where external_org_code could be same but source is different

2023-02-22 07:55 UTC, AliAdnanSohail commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +        if OrganizationMapping.objects.filter(external_organization_code=external_org_code):
Rather than filtering object twice (we are doing 2 DB calls), you can filter once and use results in this if condition and line: 105
for example:

```
org_mapping = OrganizationMapping.objects.filter(external_organization_code=external_org_code)
if org_mapping:
  logger.info('Found corresponding internal organization against external org_code [%s]', external_org_code)
  org_mapping.first().organization.key
else:
  logging.warning('Unable to find corresponding internal organization against external org_code [%s]',
                            external_org_code)
            return external_org_code
```

2023-02-22 07:55 UTC, AliAdnanSohail commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +        if OrganizationMapping.objects.filter(external_organization_code=external_org_code):
Also if we will add source in this filtering, we will update logs as well

2023-03-09 20:06 UTC, mphilbrick211 commented
Hi @AliAdnanSohail! Friendly ping on this to review. Thanks!

CC: @kashifch if this is something you can help with!

In the meantime, @AfaqShuaib09 - would you mind resolving the branch conflicts?

2023-04-04 06:53 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/emails.py
> +        # create a temporary file to store the json data
There is no need for this comment. The code is self-explanatory.

2023-04-04 06:54 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/import_course_metadata.py
> +                    products_json = list(csv.DictReader(csv_file))
Why is this being done for csv_path only?

2023-04-04 06:56 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/ingest_executive_education_data.py
> +            choices=['EXECUTIVE_EDUCATION'],
No need for this.

2023-04-04 06:57 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/ingest_executive_education_data.py
> +    help = 'Ingest executive education course data from a CSV file.'
nit: ingest_getsmarter_data is better name for command to make it specific to source here.

2023-04-04 06:58 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +            default='2u',
no need to keep this default value, you can use openedx or edx here.

2023-04-04 07:00 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_emails.py
> +            },
move this to constants or some other file. I think I have seen this data in another file.

2023-04-04 07:04 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/ingest_executive_education_data.py
> +                             product_type=product_type, product_source=product_source)
A Todo for followup PR, there can be some issues with data transformation during **populate_executive_education_data_csv**. we might want to ensure that even if there is an error in transformation, make sure it is present in CSV so that ingestion error summary is correct reflection of data. Since this PR is already quite huge, lets tackle this in a followup PR.

2023-04-04 07:05 UTC, DawoudSheraz reviewed
Overall, very nice work on this. Few comments and questions have been added.

2023-04-04 09:11 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/management/commands/import_course_metadata.py
> +                    products_json = list(csv.DictReader(csv_file))
`import_course_metadata` mgmt command includes two options, namely `csv_path` or `gspread_client`.In the case of csv_path where tempfile is being used, the products_json file needs to be attached as an email attachment. However, if gspread_client is being used, the product_data record is already maintained in the sheet.

2023-04-04 10:56 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/management/commands/ingest_executive_education_data.py
> +                             product_type=product_type, product_source=product_source)
ok sure

2023-04-04 18:56 UTC, zawan-ila approved these changes
Left some comments. Some of them for my own enlightenment.

2023-04-04 18:56 UTC, zawan-ila commented on course_discovery/apps/course_metadata/emails.py
> +    products_json = ingestion_details.pop('products_json') if 'products_json' in ingestion_details else None
How about `ingestion_details.pop('products_json', None)` ?

2023-04-04 18:56 UTC, zawan-ila commented on course_discovery/apps/course_metadata/emails.py
> +            email_msg.attach(filename=PRODUCTS_JSON_FILE_NAME, content=json_file.read(), mimetype='application/json')
It seems like you write data to a tempfile and then read the same data back. Is it possible to remove this usage of tempfile?

2023-04-04 18:56 UTC, zawan-ila commented on course_discovery/apps/course_metadata/management/commands/ingest_getsmarter_data.py
> +            help='Slug of product source with whom the ingested courses are to be linked.',
Will all getSmarter courses not have the same `product_source`?

2023-04-04 18:56 UTC, zawan-ila commented on course_discovery/apps/course_metadata/management/commands/ingest_getsmarter_data.py
> +        except Exception as ex:
nit: I think it is better to name this `exc`?

2023-04-04 18:56 UTC, zawan-ila commented on course_discovery/apps/course_metadata/tests/test_emails.py
> +        assert email.attachments[0][1] == str(json.dumps(self.PRODUCTS_DATA))
Is the `str` necessary here?

2023-04-04 20:15 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/tests/test_emails.py
> +        assert email.attachments[0][1] == str(json.dumps(self.PRODUCTS_DATA))
`json.dumps` already returning a string so we can remove it from here

2023-04-04 20:16 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/management/commands/ingest_getsmarter_data.py
> +            help='Slug of product source with whom the ingested courses are to be linked.',
yes and the `product source` would be `2u`

2023-04-04 20:16 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/emails.py
> +            email_msg.attach(filename=PRODUCTS_JSON_FILE_NAME, content=json_file.read(), mimetype='application/json')
hmmm... looking into it, let me try it on some dummy django project and get back to you

2023-04-04 20:16 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/emails.py
> +    products_json = ingestion_details.pop('products_json') if 'products_json' in ingestion_details else None
I was also thinking the same after seeing your fix PR 😅

2023-04-04 20:28 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/management/commands/ingest_getsmarter_data.py
> +            help='Slug of product source with whom the ingested courses are to be linked.',
done

2023-04-04 20:28 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/emails.py
> +            email_msg.attach(filename=PRODUCTS_JSON_FILE_NAME, content=json_file.read(), mimetype='application/json')
done

2023-04-05 06:03 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +            default='2u',
still remaining to be addressed.

2023-04-05 06:05 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/tests/test_ingest_getsmarter_data.py
> +        mock_get_smarter_client.return_value.request.return_value.json.return_value = self.mock_get_smarter_client_response()  # pylint: disable=line-too-long
why can't self.products_dataa be used here directly? Why make an additional call?

2023-04-05 06:06 UTC, DawoudSheraz approved these changes
a few comments are to be addressed before merging.

2023-04-05 08:12 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +            default='2u',
Ah.. I forgot to update this
fixed

2023-04-05 08:13 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/management/commands/tests/test_ingest_getsmarter_data.py
> +        mock_get_smarter_client.return_value.request.return_value.json.return_value = self.mock_get_smarter_client_response()  # pylint: disable=line-too-long
we can use `self.products_data` directly here. I created a function before to increase readability.

2023-04-05 08:51 UTC, AliAdnanSohail commented on course_discovery/apps/course_metadata/emails.py
> +        email_msg.attach(filename=PRODUCTS_JSON_FILE_NAME, content=products_json, mimetype='application/json')
nit: I think we don't need to create this constant, this is just file name which will be displayed in email as file name. And in our system we are not using any where else. So we can directly pass the name and remove this constant

2023-04-05 08:53 UTC, AliAdnanSohail commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +            external_org_code (str): External organization code
nit: missing second argument doc string

2023-04-05 08:55 UTC, AliAdnanSohail approved these changes
Just make sure to update existing and new command in edx-internal if required

2023-04-07 10:05 UTC, openedx-webhooks commented
Thanks for the pull request, @AfaqShuaib09!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-04-10 18:59 UTC, merged

2023-04-10 18:59 UTC, openedx-webhooks commented
@AfaqShuaib09 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/3785&entry.1484655318=https://github.com/AfaqShuaib09&entry.752974735=2023-02-01+09:06&entry.1917517419=2023-04-10+18:59&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->