ECOM-5680 Sortable organizations in admin program form
openedx/course-discovery pull request #380
Opened 2016-10-12 21:06 UTC by MatthewPiatetsky

Don't read yet

2016-10-13 15:46 UTC, rlucioni commented on course_discovery/static/js/sortable_select.js
> +        sortableSelect('.field-credit_backing_organizations');
I wonder if these fields should be configurable or otherwise more visible. Just a thought.

2016-10-13 15:46 UTC, rlucioni approved these changes

2016-10-13 15:49 UTC, MatthewPiatetsky commented on course_discovery/static/js/sortable_select.js
> +        sortableSelect('.field-credit_backing_organizations');
Do you have thoughts on how that could work?  
Can I use django to add a specific class to these fields?  
Currently I'm just including sortable_select.js in the Meta class of ProgramAdmin

2016-10-13 18:01 UTC, clintonb requested changes

2016-10-13 18:01 UTC, clintonb commented on course_discovery/static/js/sortable_select.js
>          visibleCourseTitlesLength,
This seems very field-specific. This file needs to be cleaned to make it generic to any field.

2016-10-13 18:01 UTC, clintonb commented on course_discovery/static/js/sortable_select.js
> +        sortableSelect('.field-credit_backing_organizations');
You should be making a custom widget. See https://docs.djangoproject.com/en/1.10/ref/forms/widgets/. It may be easier to use an existing widget.

2016-10-13 20:58 UTC, MatthewPiatetsky commented on course_discovery/static/js/sortable_select.js
>          visibleCourseTitlesLength,
good point, I just updated it to be more generic, and rather than specifying specific fields in the file, I have it looking for a class set on widget initialization

2016-10-13 21:01 UTC, MatthewPiatetsky commented on course_discovery/static/js/sortable_select.js
> +        sortableSelect('.field-credit_backing_organizations');
we were already using the django autocomplete light widget and this was just extending some functionality they did not have.  
We could try contributing back, though just because this functionality could be useful for us, doesn't necessarily mean they'll want to accept/maintain it

2016-10-13 21:08 UTC, clintonb commented on course_discovery/static/js/sortable_select.js
> +        sortableSelect('.field-credit_backing_organizations');
A proper widget should not have hard-coded class names. Those should be derived from the field passed to the template. We don't have to contribute this back to the main repo; but, we should not be hardcoding field names in our own code.

2016-10-13 21:12 UTC, MatthewPiatetsky commented on course_discovery/static/js/sortable_select.js
> +        sortableSelect('.field-credit_backing_organizations');
Do you mean the classes I hardcode above? That diff is outdated.  
If you mean my current approach, I think I could use some more details on what you're suggesting

2016-10-13 21:13 UTC, clintonb reviewed
I approve of the implementation; but, I would like to see tests before approving this to be merged. This form is pretty important, and we aren't testing it at all. See https://docs.djangoproject.com/en/1.8/topics/testing/tools/#liveservertestcase.

2016-10-13 21:23 UTC, MatthewPiatetsky commented
@clintonb I don't object to writing functional tests, but maybe that should be a separate ticket we pull into the sprint (we could mark it as blocking to this ticket/PR)?  
It seems this repo doesn't have much in way of these tests, and before we pick a path to go down, it would be useful to consult with the team, especially @AlasdairSwan.
For example, maybe we would want to go with the karma setup we have on the marketing site rather than selenium (and having a separate suite of front end tests could be useful).

2016-10-13 21:26 UTC, clintonb commented
This repo has a lot of tests actually. I wrote many of them. 😉 We've been discussing testing for quite some time now. It's time we actually wrote some tests. Selenium tests are quick and easy to write, and meet our needs of testing the UI as the user would. I see no reason to introduce another testing tool unnecessarily.

2016-10-13 21:37 UTC, MatthewPiatetsky commented
I was discussing functional tests, not unit tests. (If you use functional to mean something different, I use it to refer to browser based tests).
The only file I see with selenium tests is affiliate_cookie_tests, if I'm missing other selenium tests let me know.

Not objecting to selenium, (in fact I think it has functionality that would be better suited to this case than JS focused test runners), but nevertheless, that seems to me like something we should discuss. 
If we decided we want to standardize on a specific framework for functional tests and it wasn't selenium, it would be easier to do that now, than when we already had a bunch of selenium tests written and then rewriting those. I'm fine with not merging this PR until we do that.

I know we have tickets focused around front end technologies, https://openedx.atlassian.net/browse/ECOM-5776, and we may want to do similar thinking about front end test frameworks.

2016-10-13 21:42 UTC, clintonb commented
Ignore the `acceptance_tests` directory for now. You can use `DjangoLiveServerTestCase` to create functional tests alongside the unit tests in in `course_metadata/tests/test_admin.py`. The advantage of this is that you get Django setup for free. Additionally, these Selenium tests will easily transfer to `acceptance_tests` if/when we decide to make that change.

2016-10-14 15:26 UTC, MatthewPiatetsky commented
ok, I have some thoughts, but I will save them until we start work on acceptance tests in catalog and I will write selenium tests for this particular page

2016-10-14 18:18 UTC, MatthewPiatetsky commented
@clintonb I added a starting point, but what kind of stuff do we want to test in this test?

2016-10-14 18:32 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +class AdminTests(TestCase, LiveServerTestCase):
There should be two classes. Leave the existing tests. Add a new test class, `ProgramAdminFunctionalTests`, for your new tests.

2016-10-14 20:03 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        # Make sure that all expected fields are present
All you need to test, for this PR, are the fields you modified.

2016-10-17 17:16 UTC, MatthewPiatetsky commented
@clintonb I've updated the test, and it works locally (consistently), but not on Travis (consistently), so don't think the issue is a flappy test. Any ideas?

2016-10-17 17:19 UTC, clintonb commented
@MatthewPiatetsky it seems you have a sorting error. What have you done to investigate/fix?

2016-10-17 17:24 UTC, clintonb commented on package.json
> -    "requirejs": "^2.2.0"
Why are these changes necessary?

2016-10-17 17:25 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.browser = webdriver.Chrome('node_modules/chromedriver/bin/chromedriver')
Use Firefox. This might be the source of your trouble with Travis.

2016-10-17 17:30 UTC, MatthewPiatetsky commented on package.json
> -    "requirejs": "^2.2.0"
I added chromedriver

2016-10-17 17:30 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.browser = webdriver.Chrome('node_modules/chromedriver/bin/chromedriver')
will try Firefox

2016-10-17 17:47 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.browser = webdriver.Chrome('node_modules/chromedriver/bin/chromedriver')
@clintonb don't need to change package.json now that I am using Firefox, though error is still present.
I may try some other implementations, but could be slow if I can't reproduce issue locally.

2016-10-17 18:01 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +class ProgramAdminFunctionalTests(TestCase, LiveServerTestCase):
You only need `LiveServerTestCase` here.

2016-10-18 17:32 UTC, clintonb requested changes

2016-10-18 17:32 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.browser.set_window_size(548, 768)
Why such an arbitrary size? Why not something more common (e.g. 1024x768)? Can we open the browser at this size?

Do this as part of `setUp()` in case future tests run into this issue. Also, add a comment explaining why this is necessary.

2016-10-18 17:32 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        # Drag and drop
This all reads like a wall of text. Add a new line before each comment to make this method a bit more legible.

2016-10-18 17:32 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +                            'row2  empty-form', 'row1  dynamic-Program_individual_endorsements',
`'row2  empty-form'` is duplicated numerous times, and it is not clear if there is any value to validating its presence.

2016-10-18 17:32 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.browser.find_elements_by_tag_name('input')[-1].click()
This is brittle. You can get the submit button by finding the element matching `input[type=submit]`.

2016-10-18 17:32 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        username = self.browser.find_element_by_id("id_username")
Single quotes here and below.

2016-10-18 17:32 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        domain = 'http://localhost:8081'
This is brittle and will break if we ever change the arguments. Use `self.live_server_url`.

2016-10-18 17:32 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.browser.implicitly_wait(3)
Add a comment explaining the need for the wait.

2016-10-18 17:32 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +
Remove this newline.

2016-10-18 17:44 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +
removed

2016-10-18 17:45 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.browser.implicitly_wait(3)
think in the end it ended up being not necessary

2016-10-18 17:45 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        domain = 'http://localhost:8081'
changed

2016-10-18 17:45 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        username = self.browser.find_element_by_id("id_username")
changed

2016-10-18 17:45 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.browser.find_elements_by_tag_name('input')[-1].click()
changed

2016-10-18 17:46 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +                            'row2  empty-form', 'row1  dynamic-Program_individual_endorsements',
This was the list of classes that the top level field elements have on the form.  
I could do some sort of contains rather than an assertEqual, though it could be useful to know if something little changed in the form?

2016-10-18 17:47 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        # Drag and drop
added new lines

2016-10-18 17:48 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.browser.set_window_size(548, 768)
If we will be doing computations that could have to do with window size, would be good to have window size closer to what we're getting on travis.
I got this window size by printing the window size during a travis test run.  
(moved and added comment)

2016-10-18 17:50 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +                            'row2  empty-form', 'row1  dynamic-Program_individual_endorsements',
I don't think there is much value in knowing if order shifted. We really only care that the fields are present on the page.

2016-10-18 17:50 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +                            'row2  empty-form', 'row1  dynamic-Program_individual_endorsements',
ok will adjust

2016-10-18 18:05 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +                            'row2  empty-form', 'row1  dynamic-Program_individual_endorsements',
adjusted to only check classes that contain the field name

2016-10-18 18:12 UTC, clintonb approved these changes

2016-10-18 18:18 UTC, merged