Exclude deleted programs from course and course_run api
openedx/course-discovery pull request #381
Opened 2016-10-12 21:06 UTC by schenedx

Please review @edx/ecommerce 
Originally, the associated programs array in the course and course_run api object would include all programs regardless of status. With this change, the deleted programs are filtered. Only the query string parameter include_deleted_programs will list out all associated programs
ECOM-5729

2016-10-13 15:12 UTC, rlucioni requested changes

2016-10-13 15:12 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
> +            eligible_programs = obj.programs.all()
An if/else seems appropriate here, to help with readability.

2016-10-13 15:12 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
> +            eligible_programs = obj.programs.all()
If/else might make this a little easier to read, too.

2016-10-13 15:12 UTC, rlucioni commented on course_discovery/apps/api/tests/test_serializers.py
> +    def test_exlude_deleted_programs(self):
s/exlude/exclude

2016-10-13 15:12 UTC, rlucioni commented on course_discovery/apps/api/tests/test_serializers.py
> +        super(CourseWithProgramsSerializerTests, self).setUp()
`super()` is smarter in Python 3. You can just do `super().setUp()`, both here an anywhere else you're adding a call to super.

2016-10-13 15:12 UTC, rlucioni commented on course_discovery/apps/api/tests/test_serializers.py
> +    def test_exlude_deleted_programs(self):
s/exlude/exclude

2016-10-13 15:12 UTC, rlucioni commented on course_discovery/apps/api/tests/test_serializers.py
> +        self.serializer_context.update({'include_deleted_programs': 1})
Minor, but there's no need to call `update()` if you're adding a single key. You can do this more concisely as `self.serializer_context['include_deleted_programs'] = 1`.

2016-10-13 15:12 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        with self.assertNumQueries(13):
Do we know what these extra queries are? Are any duplicated unnecessarily?

2016-10-13 15:12 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +            - name: include_deleted_program
Make this plural to match the expected querystring param.

2016-10-13 15:12 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +            - name: include_deleted_program
Make this plural to match the expected querystring param.

2016-10-13 15:12 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +            self.assertEqual(response.data.get('programs'), [])
Both here and below, you can try folding these assertions together into one using Django's [`assertContains()`](https://docs.djangoproject.com/en/1.10/topics/testing/tools/#django.test.SimpleTestCase.assertContains). It's useful any time you need to assert on response data while also checking status code.

2016-10-13 16:37 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +            eligible_programs = obj.programs.all()
Either an if-else, or start with all programs, and filter from there.

2016-10-13 16:41 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +    def test_exlude_deleted_programs(self):
Use a mixin to de-dupe these methods.

2016-10-13 16:42 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +        eligible_programs = obj.programs.exclude(status=ProgramStatus.Deleted)
Similar to the line above, filter in Python to avoid an extra database call.

2016-10-13 16:44 UTC, clintonb requested changes
We should figure out how to avoid the extra database calls. Filtering in Python should fix this.

2016-10-14 15:34 UTC, schenedx commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +            self.assertEqual(response.data.get('programs'), [])
I don't understand why you think `assertContains()` would cover both asserts here. The second assert I am doing make sure the `programs` array is empty. I don't know if we can use `assertContains()' for that, can we?

2016-10-14 16:48 UTC, schenedx commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        with self.assertNumQueries(13):
I digged into it and found I did make extra query unnecessarily. I have updated the serializer to avoid the extra query

2016-10-14 16:50 UTC, schenedx commented on course_discovery/apps/api/tests/test_serializers.py
> +    def test_exlude_deleted_programs(self):
@clintonb Which two method you think we can dedupe?

2016-10-14 17:01 UTC, schenedx commented
@clintonb I made changes according to review suggestions. Please take another review pass.

2016-10-17 14:27 UTC, clintonb approved these changes
With the exception of the increase in query count, everything looks good.

2016-10-17 14:27 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +        if self.context.get('include_deleted_programs'):
Nit

```python
eligible_programs = obj.programs.all()

if self.context.get('include_deleted_programs'):
  eligible_programs = eligible_programs.exclude(status=ProgramStatus.Deleted)
```

2016-10-17 14:27 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        with self.assertNumQueries(19):
Why do we still have an increase?

2016-10-17 14:27 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +        if self.context.get('include_deleted_programs'):
Actually...this might be the source of the query count increase. Try filtering via Python, as you do above, to see if that resolves the issue.

2016-10-17 14:45 UTC, schenedx commented on course_discovery/apps/api/serializers.py
> +        if self.context.get('include_deleted_programs'):
@clintonb Unfortunately, that's the incorrect logic. Should really be either:

``` python
eligible_programs = obj.programs.all()
if not self.context.get('include_deleted_programs'):
    eligible_programs = eligible_programs.exclude(status=ProgramStatus.Deleted)
```

or

``` python
eligible_programs = obj.programs.exclude(status=ProgramStatus.Deleted)
if self.context.get('include_deleted_programs'):
    eligible_programs = obj.programs.all()
```

For the first variation, @rlucioni gave me the feedback on difficulty to read.
For the second variation that actually introduces 3 extra unnecessary DB queries if we do want all programs.
That's why the `if` and `else` statement.

2016-10-17 14:47 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +        if self.context.get('include_deleted_programs'):
@schenedx try filtering via Python to see if that removes the extra database call.

2016-10-17 14:48 UTC, schenedx commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        with self.assertNumQueries(19):
It's related to the `exclude()` call. What happens is, if the course has empty Programs reference in DB, the `exclude()` call for the querySet will make a call anyways to make sure exclusion logic has been applied, even on an empty set. I don't know how I can get around this.

2016-10-17 14:52 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        with self.assertNumQueries(19):
Filter in Python.

2016-10-17 15:01 UTC, schenedx commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        with self.assertNumQueries(19):
@clintonb I tried that. Filter in Python won't save queries here. What happens is, when filter in python, you have to first get the set of Programs associated with the course, even if that set is empty. That get call is already a extra query down in DB. It has essentially the same effect of the exclude call. What's worse is that, if we only filter in python, if there are programs associated with the course, the query count will increase by additional 2 for getting Partners and getting ProgramType from DB

2016-10-17 15:48 UTC, merged