Added new course run form.
openedx/course-discovery pull request #382
Opened 2016-10-13 07:57 UTC by waheedahmed

[ECOM-5175] (https://openedx.atlassian.net/browse/ECOM-5175)

As a course team member, I would like to have help text and examples on the Course run data entry form so that it's easy for me to complete the form.

**Design:**
http://cim31f.axshare.com/#g=1&p=new_run

**Acceptance Criteria:**

1. Validate that the data entry form contains help text and examples as shown in the wireframe above.

**Screenshots:**
![screencapture-localhost-8004-publisher-course_runs-new-1475671761707](https://cloud.githubusercontent.com/assets/2851134/19113637/140f9fb4-8b24-11e6-8977-6a167da95398.png)

<img width="994" alt="screen shot 2016-10-05 at 5 49 03 pm" src="https://cloud.githubusercontent.com/assets/2851134/19113644/1b646dc6-8b24-11e6-9a13-bfa64bbf158a.png">

2016-10-13 11:03 UTC, waheedahmed commented
@awais786 @jareerahsan @ahsan-ul-haq @tasawernawaz Please review.

2016-10-14 10:21 UTC, tasawernawaz requested changes

2016-10-14 10:21 UTC, tasawernawaz commented on course_discovery/apps/publisher/views.py
> +                team_admin = get_object_or_404(User, pk=course_form.data['team_admin'])
We can check this at start of `if` condition.

2016-10-14 10:21 UTC, tasawernawaz commented on course_discovery/apps/publisher/views.py
> +        if course and course_number and run_form.is_valid() and seat_form.is_valid():
We can also check here `course_form` validation.

2016-10-14 10:21 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
>          self.course_run_dict['start'] = '2050-07-08 05:59:53'
Avoid using hardcoded dates.

2016-10-14 10:21 UTC, tasawernawaz commented on course_discovery/templates/publisher/add_courserun_form.html
> +            {{ message }}
Do we need to translate `message` ?

2016-10-14 10:21 UTC, tasawernawaz commented on course_discovery/templates/publisher/add_courserun_form.html
> +    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
Why we are adding `.css` file under js block ?

2016-10-14 13:19 UTC, waheedahmed commented on course_discovery/templates/publisher/add_courserun_form.html
> +            {{ message }}
@tasawernawaz No, we are already translating them at backend.

2016-10-14 13:21 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        if course and course_number and run_form.is_valid() and seat_form.is_valid():
@tasawernawaz Don't need to check ```course_form``` validation, because we are only creating course run and seat here against course object.

2016-10-14 13:23 UTC, waheedahmed commented on course_discovery/templates/publisher/add_courserun_form.html
> +    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
@tasawernawaz Actually we don't need `jquery-ui.css` now, removing. Good catch.

2016-10-14 13:29 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +                team_admin = get_object_or_404(User, pk=course_form.data['team_admin'])
No need to do that, we will always get a value for this from parent course.

2016-10-17 11:25 UTC, waheedahmed commented
@tasawernawaz Please take another look.

2016-10-17 11:28 UTC, tasawernawaz approved these changes

2016-10-17 11:31 UTC, waheedahmed commented
@edx/ecommerce Please Review.

2016-10-17 14:18 UTC, clintonb requested changes

2016-10-17 14:18 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
>          self.course_run = factories.CourseRunFactory()
It's not clear why you are keeping this around as an instance variable. If you need a dictionary, see http://factoryboy.readthedocs.io/en/latest/recipes.html#converting-a-factory-s-output-to-a-dict.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.course_run_dict['start'] = str(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
1. There is no need to cast a string to a string.
2. Use single quotes.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/apps/publisher/urls.py
> +        r'^courses/(?P<parent_course_id>\d+)/course_runs/new$',
Include a trailing slash.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +class CreateCourseRunView(CreateCourseView):
You're definitely going to need to update the docstring explaining why you're inheriting from the seemingly unrelated `CreateCourseView`.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        course_number = course_form.data['number']
Shouldn't course number come from the course? Why is it coming from the form?

2016-10-17 14:18 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        if course and course_number and run_form.is_valid() and seat_form.is_valid():
If there is no need to validate the form, why is it being used? It seems you should be using data from the `Course` that is specified on the URL. If that is the case, do that instead of dealing with an unnecessary form.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +                    course.number = course_number
This doesn't seem that it should ever be changing once created.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +                messages.error(request, str(e))
Avoid displaying exception messages to users. It's just noise. You should do two things:
1. Display user-friendly error message. This may include the basic exception message, but not the full stack trace.
2. ALWAYS use [`logging.exception()`](https://docs.python.org/3/library/logging.html#logging.Logger.exception) to log the error and stack trace. The value passed to this method should be a developer-friendly message (e.g. "Unable to save course run for course %s."). The method will handle logging the exception and stack trace.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +                    seat = seat_form.save(commit=False)
What's the point of these two calls with `commit=False`? If there is extra processing that needs to be done, do so on the forms, not here. That way your forms are truly re-usable and independent of the parent view.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/templates/publisher/add_courserun_form.html
> +{% block title %}
Add a newline to keep this legible.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/templates/publisher/add_courserun_form.html
> +<div class="alert-messages">
This should be inside the if-clause. This entire block should be moved to a partial that can be shared by multiple pages.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/templates/publisher/add_courserun_form.html
> +<form class="form" method="post" action="" enctype="multipart/form-data">
Either include the action, or remove the attribute.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/templates/publisher/add_courserun_form.html
> +<div class="course-information">
Add some tabs. The lack of tabs makes this a bit confusing to read.

2016-10-17 14:18 UTC, clintonb commented on course_discovery/templates/publisher/add_courserun_form.html
> +        $(document).ready(function () {
Why is this not in the above file, or its own file?

2016-10-18 07:07 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
>          self.course_run = factories.CourseRunFactory()
@clintonb Yes, we need a dictionary but also need the object in tests to verify the values.

2016-10-18 07:31 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        if course and course_number and run_form.is_valid() and seat_form.is_valid():
@clintonb We are using two fields `course_form.number` and `course_form.team_admin` from`course_form` and auto populating their values and user can change values of those fields according to wireframes, we can't call validate on that form because it will always going to fail due to only two fields.

2016-10-18 07:32 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        course_number = course_form.data['number']
@clintonb It can be changed according to wireframes.

2016-10-18 08:25 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +                    course.number = course_number
@clintonb It can be changed according to wireframes, adding if-clause to check if changed than assign.

2016-10-18 08:49 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +                    seat = seat_form.save(commit=False)
@clintonb Need to assign `ForeignKey` objects before committing them to DB.

2016-10-18 08:58 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +class CreateCourseRunView(CreateCourseView):
@clintonb Inherited it from ```CreateCourseView``` to reuse the code but I end up in a situation where I can't use the code from it and need to override the functionality, removing it.

2016-10-18 11:03 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +                    seat = seat_form.save(commit=False)
Refactored this view with custom save method for forms.

2016-10-18 13:57 UTC, waheedahmed commented
@clintonb Addressed your comments, please take another look.

2016-10-19 17:35 UTC, clintonb reviewed
I am going on vacation until Monday. I don't want to hold up progress; but, the form structure is concerning, along with the usage of custom save methods. You might investigate FormSets to determine if they may be helpful to simplify the logic here.

2016-10-19 17:35 UTC, clintonb commented on course_discovery/apps/publisher/forms.py
> +    number = forms.CharField(label=_('Course Number'), required=True, max_length=255)
This maximum length differs from that on the model (50). Remove the `max_length` kwargs. The model validation will handle that.

2016-10-19 17:35 UTC, clintonb commented on course_discovery/apps/publisher/forms.py
> +        self.cleaned_data['pacing_type'] = CourseRunPacing.Instructor
Minor: `self.cleaned_data['pacing_type'] = CourseRunPacing.Self if self.cleaned_data['is_self_paced'] else CourseRunPacing.Instructor`

2016-10-19 17:35 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +    course_form = CustomCourseForm
I'm still failing to see why this is here. You are not modifying the course. You don't need a form for it.

2016-10-19 17:35 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +    def get(self, request, *args, **kwargs):
I'm fairly certain you get this for free from `CreateView`.

2016-10-20 12:40 UTC, waheedahmed commented
@clintonb We don't need FormSets here because we are not adding multiple objects of a single item, we have three different forms.

2016-10-20 12:40 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +    course_form = CustomCourseForm
@clintonb We are modifying two fields of course.

2016-10-20 13:20 UTC, waheedahmed commented
@edx/ecommerce Can anyone else review this PR? Clinton is out until Monday.

2016-10-20 13:42 UTC, waheedahmed commented
@bderusha Please take a look on this PR.

2016-10-25 11:51 UTC, waheedahmed commented
@clintonb I just realized that this story was only to implement help text and examples for new course run form according to wireframes, so created a new ticket [ECOM-6208] (https://openedx.atlassian.net/browse/ECOM-6208) to implement the backend for course run form.

Please take another look on this PR.

2016-10-25 14:09 UTC, clintonb requested changes
It is strange to me that the UI is being implemented without the actual form backend (now moved to ECOM-6208). That order of operations removes the context necessary to properly review this request. I recommend getting the backend in order, and returning to this once that work is done. 

Without a backend, this work is incomplete; and, I would prefer not to merge incomplete code to the master branch. A feature branch should be used in such cases.

2016-10-25 14:09 UTC, clintonb commented on course_discovery/apps/publisher/forms.py
> +    is_self_paced = forms.BooleanField(label=_('Yes, course will be Self-Paced'), required=False)
Update: "Indicate if this course will be self-paced or instructor-paced".

2016-10-25 14:09 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +    def post(self, request, *args, **kwargs):
Remove this until you get to ECOM-6208.

2016-10-25 14:09 UTC, clintonb commented on course_discovery/templates/publisher/add_courserun_form.html
> +                            <div class="field-title">{% trans "COURSE TITLE" %}</div>
Why is this in all-caps?

2016-10-25 14:09 UTC, clintonb commented on course_discovery/templates/publisher/add_courserun_form.html
> +                                            <a href="#">{% trans "View our documentation for more help" %}</a>
Where is this supposed to go?

2016-10-25 14:09 UTC, clintonb commented on course_discovery/templates/publisher/add_courserun_form.html
> +                            <div class="field-title">{% trans "COURSE START DATE" %}</div>
Why is this in all-caps?

2016-10-25 14:09 UTC, clintonb commented on course_discovery/templates/publisher/add_courserun_form.html
> +                                        <span class="required">* {% trans "required" %}</span>
Put this inside a conditional:

``` Django
{% if course_form.title.field.required %}<span class="required">* {% trans "required" %}</span>{% endif %}
```

2016-10-25 14:20 UTC, waheedahmed commented on course_discovery/apps/publisher/forms.py
> +    is_self_paced = forms.BooleanField(label=_('Yes, course will be Self-Paced'), required=False)
@clintonb Its in the provided wireframes.

2016-10-25 14:21 UTC, waheedahmed commented on course_discovery/templates/publisher/add_courserun_form.html
> +                            <div class="field-title">{% trans "COURSE TITLE" %}</div>
@clintonb Its according to provided wireframes.

2016-10-25 14:21 UTC, waheedahmed commented on course_discovery/templates/publisher/add_courserun_form.html
> +                            <div class="field-title">{% trans "COURSE START DATE" %}</div>
@clintonb Its according to provided wireframes.

2016-10-26 15:01 UTC, waheedahmed commented
@clintonb Please take final look, created a PR https://github.com/edx/course-discovery/pull/401 for backend against this branch.

2016-11-07 19:08 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +    start = forms.DateTimeField(required=True, label=_('Course start date'))
NIT: consistency.  Labels first, then required.

2016-11-07 19:12 UTC, bderusha approved these changes

2016-11-07 19:13 UTC, bderusha commented
@waheedahmed Please resolve the conflicts and squash the commits

2016-11-18 17:50 UTC, merged