[Work In Progress] Allow course length in program to be represented as a range of weeks
openedx/course-discovery pull request #387
Opened 2016-10-18 16:26 UTC by MatthewPiatetsky

ECOM-5946,ECOM-6019,ECOM-6020,ECOM-6021,ECOM-6024

2016-10-18 19:16 UTC, clintonb requested changes

2016-10-18 19:16 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +        weeks_to_complete = data.get('field_course_required_weeks')
This should be cast to an integer.

2016-10-18 19:16 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +        elif start and end:
How likely is this clause to be invoked? In other words, how many courses, if any, are missing data for `field_course_required_weeks`? Given that the marketing site is not our source of truth for the end date, I can see this becoming problematic.

2016-10-18 19:16 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        help_text=_('Estimated number of weeks needed to complete a course run.'))
`'Estimated number of weeks needed to complete this course run'`

2016-10-18 19:16 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        help_text=_('Estimated number of weeks needed to complete a course run.'))
Also, there is no migration for this field.

2016-10-18 19:16 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    weeks_to_complete = models.PositiveSmallIntegerField(
Is there a task to remove this field? It should be removed fairly quickly after this is released. I see no reason to keep this around for any amount of time beyond the initial release.

2016-10-18 19:16 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    def _course_run_weeks_to_complete(self):
`@cached_property`

2016-10-18 19:16 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +                                          weeks_to_complete=randrange(1, 10))
This is not necessary given your factory changes.

2016-10-18 19:47 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +        elif start and end:
I believe that the majority of courses do not have field_course_required_weeks

2016-10-18 19:49 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +        help_text=_('Estimated number of weeks needed to complete a course run.'))
what about 0031_courserun_weeks_to_complete.py?  
will change

2016-10-18 19:50 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    weeks_to_complete = models.PositiveSmallIntegerField(
There was no task currently to remove it.  
Should it be removed as part of this PR?  
Or should I create a ticket to remove this field?

2016-10-18 20:00 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +        weeks_to_complete = data.get('field_course_required_weeks')
updated

2016-10-18 20:24 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    def _course_run_weeks_to_complete(self):
@clintonb  
I think this property is the thing generating extra queries.  
Is that ok if the caching will cause it to not scale with the size of the input?

2016-10-20 14:33 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +    weeks_to_complete = models.PositiveSmallIntegerField(
@MatthewPiatetsky Create a new devtask story to remove. We should not remove db columns as part of the existing deployment. Let's only remove db columns when the new code is in production and stable.

2016-10-20 14:36 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +        course_run_weeks_to_complete = self._course_run_weeks_to_complete
#nitpick Why the temp local variable while you can just reference `self._course-run_weeks_to_complete` directly?

2016-10-20 14:37 UTC, bderusha approved these changes
A few minor comments, but otherwise looks good.  👍

2016-10-20 14:37 UTC, bderusha commented on course_discovery/apps/api/tests/test_serializers.py
> +            'weeks_to_complete_min': program.weeks_to_complete_min,
didn't we talk about making this more accurately named to something that makes it clear that it is talking about an individual course completion?

2016-10-20 14:37 UTC, bderusha commented on course_discovery/apps/course_metadata/models.py
> +    weeks_to_complete = models.PositiveSmallIntegerField(
Create a ticket please

2016-10-20 14:38 UTC, schenedx commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with self.assertNumQueries(87):
Could you explain why the number of query increase here? If not, can you dig in and see if we can avoid it?

2016-10-20 14:41 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +        course_run_weeks_to_complete = self._course_run_weeks_to_complete
I didn't want to incur extra queries, but now that I'm using cached_property this is fine.
addressed.

2016-10-20 14:41 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +        course_run_weeks_to_complete = self._course_run_weeks_to_complete
addressed.

2016-10-20 14:42 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with self.assertNumQueries(87):
This bit of code here is generating extra queries.
```
    @cached_property
    def _course_run_weeks_to_complete(self):
        return [course_run.weeks_to_complete for course_run in self.course_runs
                if course_run.weeks_to_complete is not None]

```
I talked to @clintonb about it, and given that it is a limited number of additional queries and does not affect the Program List endpoint he was ok with it.
We can't actually prefetch properties that are calculated at runtime (though the caching helps a bit).  
If you have other ideas let me know.

2016-10-20 14:46 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> +            'weeks_to_complete_min': program.weeks_to_complete_min,
I forget, but do you have thoughts on a better name?  
We could do course_run_min_weeks_to_complete though that might be a bit too verbose and still confusing

2016-10-20 14:49 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    weeks_to_complete = models.PositiveSmallIntegerField(
ticket https://openedx.atlassian.net/browse/ECOM-6170

2016-10-20 14:57 UTC, schenedx approved these changes
👍

2016-10-20 15:22 UTC, MatthewPiatetsky commented
Thank you @bderusha and @schenedx for the reviews, I think I addressed @clintonb's comments, so I will merge, but happy to address further comments when you're back.

2016-10-20 17:52 UTC, merged