Update Search Indexer to exclude unpublished programs
openedx/course-discovery pull request #389
Opened 2016-10-18 19:57 UTC by mikedikan

Exclude when nested unpublished programs are under course runs on course run search endpoint.

ECOM-6147

@schenedx & @clintonb for review

2016-10-18 20:10 UTC, schenedx requested changes
I think it's worth adding another view level test to ensure the correctness as well as the query count

2016-10-18 20:10 UTC, schenedx commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        program = factories.ProgramFactory(courses=courses)
I think it would be easier we combine line 168 and 169 with just `factories.ProgramFactory(courses=[self.course_run.course])`

2016-10-18 20:10 UTC, schenedx commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        other_program = factories.ProgramFactory(courses=courses, status=ProgramStatus.Unpublished)
You can just do `factories.ProgramFactory(courses=[self.course_run.course], status=ProgramStatus.Unpublished)`

2016-10-18 20:28 UTC, clintonb requested changes

2016-10-18 20:28 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        all_programs = [program for program in self.programs.all() if program.status != ProgramStatus.Unpublished]
Combine into a single loop.

2016-10-18 20:28 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        self.assertCountEqual(self.course_run.program_types, [program.type.name])
What does count matter? Check the actual values.

2016-10-18 20:41 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        all_programs = [program for program in self.programs.all() if program.status != ProgramStatus.Unpublished]
Also, move the comment to a docstring for the property.

2016-10-19 15:04 UTC, mikedikan commented on course_discovery/apps/course_metadata/models.py
> +        all_programs = [program for program in self.programs.all() if program.status != ProgramStatus.Unpublished]
Why combine into a single loop? This seems easier to read...

2016-10-19 15:07 UTC, mikedikan commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        program = factories.ProgramFactory(courses=courses)
I was mimicking the approach in the method above - should we change both places so it's consistent?

2016-10-19 15:07 UTC, mikedikan commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        other_program = factories.ProgramFactory(courses=courses, status=ProgramStatus.Unpublished)
See comment above

2016-10-19 15:18 UTC, mikedikan commented
@clintonb @schenedx please rereview

2016-10-19 15:53 UTC, schenedx approved these changes
👍

2016-10-20 12:12 UTC, merged