feat: Add a command to manage program subscription
openedx/course-discovery pull request #3909
Opened 2023-04-26 04:08 UTC by uzairr

In order to add subscriptions for the existing programs, a management command is added.It will process the programs based on their uuids and attach it to its subscription.

PROD-3209

2023-04-26 09:59 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +        )
How/why are these arguments used here?  Both are irrelevant.

2023-04-26 10:01 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +        program_loader_config = ProgramDataLoaderConfiguration.current()
The name of the loader config can be better. It should be ProgramSubscriptionDataLoader or something along these lines. ProgramDataLoaderConfiguration feel likes a complete program is being loaded.

2023-04-26 10:02 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +                reader = gspread_client.read_data(product_config)
PRODUCT_METADATA_MAPPING is used for external products' ingestion. Please add some other setting variable for this.

2023-04-26 10:06 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +                reader = gspread_client.read_data(product_config)
Also, why is gspread flow needed here? Shouldn't the data loader config be enough here?

2023-04-26 10:07 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +                )
Please add in logs if Subscription and Price are created/updated.

2023-04-26 10:10 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +
If we are using LoaderConfig, this argument wont be of much help in this mgt. command.

2023-04-26 10:14 UTC, DawoudSheraz commented on course_discovery/settings/base.py
>  }
This is not needed here. If we are taking inspiration from other loaders, we should only use the items that are applicable in this case and not ditto copy every different path.

2023-04-26 10:15 UTC, DawoudSheraz requested changes
- Unit tests are missing
- Questions and feedback on some of the implementation approaches.

2023-04-26 11:17 UTC, uzairr commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +                reader = gspread_client.read_data(product_config)
gspread is needed as the data is needed to be imported from Spreadsheet.It is specifically communicated.Based on this requirement, product type and product source is naturally desired and i think it will make it flexible for the future in the context of sources other than ponderosa.

2023-04-26 11:19 UTC, uzairr commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +        )
they are needed in terms of having a generic implementation for not only ponderosa but for all future subscription ingestion.

2023-04-26 11:23 UTC, uzairr commented on course_discovery/settings/base.py
>  }
its not about ditto copy thing, the only thing which is debatable here is `ERROR_TAB_ID`. Other than this, nothing is irrelevant.

2023-04-26 16:14 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +        )
How? Subscription is related to Product and product is already linked to a source.

2023-04-26 16:17 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +                reader = gspread_client.read_data(product_config)
- Did we discuss the usage of spreadsheets for subscription addition? I am under the impression that the team will be using admin + Jenkins for this. I don't know how this will be useful for them if this is going to be limited run operation.

2023-04-26 21:02 UTC, uzairr commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +                reader = gspread_client.read_data(product_config)
Initially i was also under the same impression but later on, an explicit request came to fetch data from Google sheet.Maybe, later on down the road, they will make changes at their own.

2023-04-27 13:51 UTC, Ali-D-Akbar approved these changes

2023-04-28 04:59 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +            raise  # re-raising exception to avoid moving the code flow
nit: raise CommandError here.

2023-04-28 05:00 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/manage_program_subscription.py
> +                )
raise will stop the command execution. The error should be logged so that execution can keep on happening for other rows.

2023-04-28 05:02 UTC, DawoudSheraz approved these changes
A few nits/comments to address before merge.

2023-04-28 16:18 UTC, uzairr commented
All comments and suggestions are addressed.i ll going to merge it as the build will pass

2023-04-28 22:59 UTC, merged