feat: add status fields for external courses
openedx/course-discovery pull request #3932
Opened 2023-05-09 11:00 UTC by zawan-ila

### [PROD-3326](https://2u-internal.atlassian.net/browse/PROD-3326)

### Description

- Add more choices to external product status
- Expect explicit external status field from executive education API
- Allow disabling archival flow based on product source
- Update availability handling for external courses
- Update indexing handling for executive education courses

2023-05-10 06:40 UTC, Ali-D-Akbar requested changes

2023-05-10 06:40 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/algolia_models.py
> +        # Some Executive Education courses should not be indexed
This comment can be rephrased or even removed tbh.
`Archived or its equivalent Executive Education courses should not be indexed`

2023-05-10 06:40 UTC, Ali-D-Akbar commented on course_discovery/settings/test.py
> +EXTERNAL_PRODUCT_STATUS_UNAVAILABLE = [ExternalProductStatus.Archived, ExternalProductStatus.Cancelled, ExternalProductStatus.Completed]
Perhaps we can say `EXTERNAL_PRODUCT_STATUS_UNAVAILABLE` are the archived statuses.
I'd suggest using one of them

2023-05-10 06:40 UTC, Ali-D-Akbar commented on course_discovery/settings/base.py
> +CSV_LOADER_DO_NOT_ARCHIVE_SOURCE_SLUGS = ['2u']
We should move these mappings to edx-internal as we're not keeping external product line information in discovery.

2023-05-25 07:08 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/algolia_models.py
> +                                                 ExternalProductStatus.Completed]:
nit: having a model-level method called here would be better.

2023-05-25 07:08 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/algolia_models.py
> +                                                 ExternalProductStatus.Completed]:
What I am suggesting is to make this model method & call that here.

2023-05-25 07:13 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +        if [self.product_source.slug, self.product_type] in settings.INGESTION_ARCHIVAL_FLOW_EXCLUDED_SOURCE_PRODUCT_PAIRS:  # pylint: disable=line-too-long
Ah,  this seems a bit too fragile. We can do it better.

2023-05-25 07:14 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/tests/test_csv_loader.py
> +                    # product_source="2u"
remove this commented code.

2023-05-25 07:14 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/tests/test_csv_loader.py
> +            # product_source=SourceFactory(slug='2u')
remove this commented code.

2023-05-25 07:16 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +            return _('Archived')
Make or break moment ✨ 
The docstring can be updated.

2023-05-25 07:17 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/tests/test_algolia_models.py
> +        (ExternalProductStatus.Marketing_Test, True),
to update docstring for the test.

2023-05-25 07:18 UTC, DawoudSheraz reviewed
Left a few followup comments.

2023-05-25 21:02 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/models.py
> +            return _('Archived')
Can we add dict mapping here to map these statuses instead of if's here?
like:
```python
PRODUCT_STATUS = {
       ExternalProductStatus.Published :  _('Current'),
       ExternalProductStatus.Active : _('Current'),
       ExternalProductStatus.Scheduled: _('Starting Soon'),
      .......
}

PRODUCT_STATUS.get(additional_metadata.product_status, _('Archived))

2023-05-31 05:12 UTC, zawan-ila commented on course_discovery/apps/course_metadata/algolia_models.py
> +                                                 ExternalProductStatus.Completed]:
Hmm. I don't see how this is useful at the model level. Furthermore, I think it would be helpful to keep all should_index logic in one place.

2023-05-31 05:13 UTC, zawan-ila commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +        if [self.product_source.slug, self.product_type] in settings.INGESTION_ARCHIVAL_FLOW_EXCLUDED_SOURCE_PRODUCT_PAIRS:  # pylint: disable=line-too-long
I don't like it either. Please suggest any alternatives.

2023-05-31 05:15 UTC, zawan-ila commented on course_discovery/apps/course_metadata/models.py
> +            return _('Archived')
@DawoudSheraz I think the docstring is fine as is..

@AfaqShuaib09 I don't see any significant benefits of that. I feel it looks nicer as is. Still if it is a blocker, let me know and I'll update it.

2023-05-31 05:15 UTC, zawan-ila commented on course_discovery/apps/course_metadata/tests/test_algolia_models.py
> +        (ExternalProductStatus.Marketing_Test, True),
Done

2023-05-31 05:19 UTC, zawan-ila commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +            'product_status': product_dict['variant'].get('status', ExternalProductStatus.Published), # Remove this default later
@DawoudSheraz @AfaqShuaib09 What are your thoughts on this default here? I have added it just in case we merge stuff and the api is not updated yet. Eventually we should remove it.

2023-05-31 05:27 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +        if [self.product_source.slug, self.product_type] in settings.INGESTION_ARCHIVAL_FLOW_EXCLUDED_SOURCE_PRODUCT_PAIRS:  # pylint: disable=line-too-long
We can use nested dicts SOURCE_TYPE_ARCHIVE_CONFIG,like {'edx': {'audit':  "True"}}. The presence of value in dict should imply that archive is not needed.  Note that this is one suggestion and not The suggestion.

2023-05-31 05:33 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +            'product_status': product_dict['variant'].get('status', ExternalProductStatus.Published), # Remove this default later
👍🏽

2023-05-31 05:37 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +            return _('Archived')
Using dict as Afaq suggested will remove the unnecessary if conditions and make code readable. This is one of the common patterns in Python, to use dicts to replace if conditions. Not mandatory, in my opinion.
https://towardsdatascience.com/dictionary-as-an-alternative-to-if-else-76fe57a1e4af

2023-07-18 11:18 UTC, AfaqShuaib09 approved these changes

2023-07-18 11:18 UTC, AfaqShuaib09 commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            return
nit: you can break down the line instead of disabling pylint here.

2023-07-18 11:50 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            return
Isn't this settings dict of lists?

2023-07-18 11:53 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +            'product_status': product_dict['variant'].get('status', ExternalProductStatus.Published), # Remove this default later
Isn't this now being handled in CSV loader?

2023-07-18 11:54 UTC, DawoudSheraz commented on course_discovery/apps/course_metadata/models.py
> +            return _('Archived')
nit: the dict will make this code more readable.

2023-07-18 14:16 UTC, zawan-ila commented on course_discovery/apps/course_metadata/data_loaders/csv_loader.py
> +            return
nice catch! I've updated to `[]`

2023-07-18 14:17 UTC, zawan-ila commented on course_discovery/apps/course_metadata/models.py
> +            return _('Archived')
updated

2023-07-18 14:20 UTC, zawan-ila commented on course_discovery/apps/course_metadata/management/commands/populate_executive_education_data_csv.py
> +            'product_status': product_dict['variant'].get('status', ExternalProductStatus.Published), # Remove this default later
If you are talking about this branch, then yes we do set the default to `ExternalProductStatus.Published`. But if we do not provide a default here, and the data is not in the api, I believe it will write `None` in the csv which the default in the csv_loader probably will not override.

Evenntually, I'd like to do `product_dict['variant']['product_status']` here so that we get a KeyError in case the API is missing the status.

2023-07-18 19:48 UTC, Ali-D-Akbar approved these changes
Just a comment by me

2023-07-18 19:48 UTC, Ali-D-Akbar commented on course_discovery/settings/base.py
> +}
Do we wanna keep this in base? This can be moved to edx-internal.

2024-01-22 07:10 UTC, DawoudSheraz commented
Closing this as this might not be needed for now.

2024-01-22 07:10 UTC, closed without merging