Publisher app global admin flag
openedx/course-discovery pull request #397
Opened 2016-10-25 09:22 UTC by awais786

Create the is_global_admin flag in UserAttributes table. 
User having this value will be a super-user for publisher app.

https://openedx.atlassian.net/browse/ECOM-5950

2016-10-25 09:28 UTC, awais786 commented
@ahsan-ul-haq @tasawernawaz @waheedahmed Please review.

2016-10-25 13:14 UTC, clintonb requested changes
Why the user attribute instead of a Django group?

2016-10-25 13:40 UTC, awais786 commented
@edx/ecommerce Please review this PR.

2016-10-25 13:44 UTC, awais786 commented
@clintonb This user will be the super user for the publisher app only. That's why add the field in UserAttributes table. This table will specifically hold the value for publisher app users.

@bderusha FYI

2016-10-25 14:12 UTC, clintonb commented
@awais786 I get that; but, on previous pull requests you're using Django Guardian and groups. Now you've added a custom attribute. Using a custom attribute will require you to make custom handlers to process that attribute. If you use a Django group, you can take advantage of all of the functionality that already exists in Django with minimal custom work.

2016-10-25 14:34 UTC, clintonb commented
@awais786 I wrote up a quick example of using a group: https://github.com/edx/course-discovery/commit/6ef5118c5faba4e2b9dc3c7d693e8915c705bb71

2016-10-25 14:42 UTC, awais786 commented
@clintonb commits looks good. I will update my PR that way.

2016-11-07 19:19 UTC, bderusha commented on course_discovery/apps/publisher/migrations/0013_create_admin_group.py
> +ADMIN_GROUP_NAME = 'Publisher Admins'
Can we import this from `constants`?

2016-11-07 19:19 UTC, bderusha commented on course_discovery/apps/publisher/utils.py
> +def is_global_admin(user):
can we call this `is_publisher_admin`

2016-11-07 19:19 UTC, bderusha commented on course_discovery/apps/publisher/utils.py
> +def is_global_admin(user):
and rename the appropriate tests

2016-11-15 12:54 UTC, closed without merging