Implemented course run form backend
openedx/course-discovery pull request #401
Opened 2016-10-26 14:47 UTC by waheedahmed

Backend for course run form to save new course run and seat for parent course also updating two course fields.

Base PR: https://github.com/edx/course-discovery/pull/382

2016-10-26 15:00 UTC, waheedahmed commented
@clintonb Please review this PR, I'll update the translation later.

2016-10-28 10:29 UTC, waheedahmed commented
@awais786 @ahsan-ul-haq @tasawernawaz Please review this PR.

2016-10-28 12:41 UTC, waheedahmed commented
@edx/ecommerce Can someone please take a look at this PR.

2016-11-02 19:30 UTC, waheedahmed commented
@bderusha Please review this PR.

2016-11-07 19:26 UTC, bderusha requested changes
Looks good for the most part.  A few comments and please resolve failing tests

2016-11-07 19:26 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +                logger.exception('Unable to save course run for course [%s].', course.title)
can we log the ID instead of the title

2016-11-07 19:26 UTC, bderusha commented on course_discovery/templates/publisher/add_courserun_form.html
> +                                        <div id="field-team-admin" {% if parent_course.team_admin and not course_form.team_admin.errors %}class="hidden"{% endif %}>
Can we extract this beefy conditional out into the view and call something easier to read here like `if team_admin_hidden`

2016-11-09 11:41 UTC, waheedahmed commented
@bderusha Take another look please.

2016-11-14 18:25 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +        ctx = self.get_context_data()
full variable names please.  `context`

2016-11-14 18:26 UTC, bderusha approved these changes
One tiny change. then :shipit:

2016-11-18 10:28 UTC, ahsan-ul-haq requested changes

2016-11-18 10:28 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/views.py
> +        user = self.request.user
why using `self.request.user` instead of `request.user`

2016-11-18 10:28 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/tests/test_views.py
> +            self.assertEqual(response.status_code, 400)
could you check messages here as well to verify reason of why run and seat was not created.

2016-11-18 12:51 UTC, waheedahmed commented
@ahsan-ul-haq Addressed your comments, please take another look.

2016-11-18 13:54 UTC, ahsan-ul-haq approved these changes

2016-11-18 13:54 UTC, merged