[WIP] Squash migrations
openedx/course-discovery pull request #403
Opened 2016-10-26 19:30 UTC by MatthewPiatetsky

2016-10-26 20:05 UTC, clintonb requested changes

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +def update_subjects(apps, schema_editor):
This was a data fix. This is not needed for new installations; therefore, it does not need to be present in squashed migrations.

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +def update_organizations(apps, schema_editor):
Same as above. Remove.

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +        migrations.AddField(
There should be few, if any, calls to `AddField()`. Django is being a bit conservative with many of these. http://www.rkblog.rk.edu.pl/w/p/squashing-and-optimizing-migrations-django/ has some info; but, ultimately, you will need to modify some of these by hand.

When I last squashed migrations I removed all migrations and generated initial migrations. This provides a baseline from which you can pull operations into your squashed migration. Ideally, you should end up with the following operations:

1. Create models
2. Create circular foreign keys (if any)
3. Perform data operations (if any)

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +        migrations.RunPython(
Remove.

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +        migrations.RunPython(
Remove.

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +        migrations.RunPython(
Remove.

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +            field=mod
Remove.

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +            field=mod
Remove.

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +            field=mod
Remove.

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +            field=mod
Remove.

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +            field=mod
This should remain.

2016-10-26 20:05 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +        migrations.RunPython(
This should remain.

2016-10-26 20:23 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +        migrations.AddField(
I see, sounds like I'll need to do a bit more reading into this.
The ticket I looked at https://openedx.atlassian.net/browse/ECOM-5777 provided this link as the instructions https://docs.djangoproject.com/en/1.10/topics/migrations/#migration-squashing
This suggested squashing migrations by using the squashmigrations command.
Are you saying I should instead do this by removing the migrations and generating brand new ones?
Or should I go from the output of the squashmigrations command and tweak it.

2016-10-26 21:12 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +        migrations.AddField(
I'm saying the `squashmigrations` management command is not perfect. In order to get to an ideal case, and minimize database calls, you will need to handcraft some of the migrations.

2016-10-26 21:24 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +        migrations.AddField(
You say there should be few calls to AddField.  
In this migration I see 112 calls to AddField.
Is the issue that some of these are added and removed?  
There are 55 calls to RemoveField and not all match an add field, but even then, there would still be many AddField left over. What is the issue with the rest?

2016-10-27 14:58 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_catalog_extensions/migrations/0001_create_program_types.py
> +        ('course_metadata', '0001_squashed_0033_courserun_mobile_available'),
Is this what I want to do with these dependencies?

2016-10-27 15:04 UTC, MatthewPiatetsky commented
@clintonb What I currently have I got by removing all the course_metadata migrations, creating initial migrations, then adding back the data migrations at the end except the ones you said to remove.
What is the best way to test this locally?
I'm not sure how to get my database in the same state as staging prod and then run the squashed migrations the same way they will be run on deployment

2016-10-27 19:26 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +        migrations.AddField(
@clintonb the initial migrations when I ran them still generated 18 AddField's, is there a reason these fields need to be in AddField rather than CreateModel?

2016-10-27 19:43 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +            code=clear_slug_values,
Remove.

2016-10-27 19:43 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +            code=remove_duplicate_courses,
Remove.

2016-10-27 19:43 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +            code=add_uuid_to_courses_and_course_runs,
Remove.

2016-10-27 19:43 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +            code=delete_partnerless_courses,
Remove.

2016-10-27 19:43 UTC, clintonb commented on course_discovery/apps/edx_catalog_extensions/migrations/0001_create_program_types.py
> +        ('course_metadata', '0001_squashed_0033_courserun_mobile_available'),
Yes.

2016-10-27 19:43 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0001_squashed_0033_courserun_mobile_available.py
> +        migrations.AddField(
A cursory glance points to that being the most likely reason. You can try manually reordering.

2016-10-28 13:19 UTC, MatthewPiatetsky commented
@clintonb I manually reordered the models and put the remaining add field operations in.  
(though that particular change doesn't seem to have had any effect on the time)

2016-10-28 13:51 UTC, clintonb approved these changes
This looks good. Now we need to do the same for the other apps; however, I would do those after this makes it to stage/production.

2016-10-31 15:08 UTC, mikedikan approved these changes
Approving after face to face discussion

2016-11-01 19:59 UTC, merged

2016-11-02 03:38 UTC, clintonb commented
@MatthewPiatetsky please remember to squash your commits in the future, unless the commits represent distinct changes. This will help keep the commit history clean and making it easier to use `git bisect` for debugging (if necessary). [Git's fixup/autosquash functionality](https://robots.thoughtbot.com/autosquashing-git-commits) makes squashing pretty easy.