Sort CourseRunViewSet queryset by start date [SOL-1975]
openedx/course-discovery pull request #405
Opened 2016-10-27 09:50 UTC by iivic

Offers on ecommerce offer landing page should be sorted by course start date. Ecommerce is getting the results with a limit of 50 which means that the sorting needs to be done every time new results come in. This will result in constant changes on the page (bad user experience). Because of that I did the sorting in this repo.
https://openedx.atlassian.net/browse/SOL-1975
Please review @bderusha  @mjfrey

2016-10-27 11:58 UTC, clintonb requested changes
We sort by key by default to make the responses predictable. If you want other sort possibilities use [`OrderingFilter`](http://www.django-rest-framework.org/api-guide/filtering/#orderingfilter) and ensure that all ordering fields are indexed to avoid performance issues.

2016-10-28 10:29 UTC, iivic commented
@clintonb When I add OrderingFilter filter_backends and make a GET request with the ordering parameter this happens AttributeError: 'SearchQuerySetWrapper' object has no attribute 'order_by'.
I'm not sure how to approach this issue. Any advice?

2016-10-28 14:52 UTC, clintonb commented
@iivic update `SearchQuerySetWrapper`. It's essentially a proxy to `SearchQuerySet` that aids in making it look more like `QuerySet` and better handle iteration/pagination. To make it a proper proxy, replace the `count()` method with the following:

```python
def __getattr__(self, item):
    try:
        super().__getattr__(item)
    except AttributeError:
        # If the attribute is not found on this class, 
        # proxy the request to the SearchQuerySet.
        return getattr(self.qs, item)
```

2016-11-02 12:19 UTC, iivic commented
Comments addressed. Please review changes.

2016-11-02 12:38 UTC, clintonb approved these changes
1. Add a migration.
2. Squash your commits.

2016-11-02 12:38 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        """ Verify the endpoint returns a list of all catalogs sorted by key (default sorting). """
Revert.

2016-11-02 12:38 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    start = models.DateTimeField(null=True, blank=True, db_index=True)
This needs a migration.

2016-11-02 13:53 UTC, mjfrey approved these changes

2016-11-03 11:31 UTC, merged