Implement backend to save course key for already created course run.
openedx/course-discovery pull request #406
Opened 2016-10-27 10:38 UTC by waheedahmed

[ECOM-6178] (https://openedx.atlassian.net/browse/ECOM-6178)

Implement the backend to save course run key in pending studio instances and send an email to course team with subject "Studio instance created".

2016-10-27 11:54 UTC, waheedahmed commented
@awais786 @tasawernawaz @ahsan-ul-haq Please review this PR.

2016-10-27 13:00 UTC, waheedahmed commented
@edx/ecommerce Please review this PR.

2016-10-27 18:49 UTC, bderusha requested changes

2016-10-27 18:49 UTC, bderusha commented on course_discovery/apps/publisher/emails.py
> +            'run_page_url': 'https://{host}{path}'.format(
`course_run_page_url`

2016-10-27 18:49 UTC, bderusha commented on course_discovery/apps/publisher/urls.py
> +        r'^course_runs/(?P<pk>\d+)/update/course_key/$',
this should be a post request to `course_runs/(?P<pk>\d+)`.   

[RESTful Naming](http://www.restapitutorial.com/lessons/restfulresourcenaming.html)

2016-10-28 09:47 UTC, waheedahmed commented on course_discovery/apps/publisher/emails.py
> +            'run_page_url': 'https://{host}{path}'.format(
@bderusha Its course run detail page url in publisher not for studio.

2016-10-28 09:49 UTC, waheedahmed commented on course_discovery/apps/publisher/emails.py
> +            'run_page_url': 'https://{host}{path}'.format(
changed to ```course_run_page_url```.

2016-10-28 09:51 UTC, awais786 approved these changes

2016-10-28 09:51 UTC, awais786 commented on course_discovery/apps/publisher/emails.py
> +    """ Send an email to course team on course key save.
Please update this doc string. Method name and doc string does not match and not explain the purpose of method.

2016-10-28 09:55 UTC, waheedahmed commented on course_discovery/apps/publisher/emails.py
> +    """ Send an email to course team on course key save.
Done.

2016-10-28 10:28 UTC, waheedahmed commented
@bderusha Please take another look.

2016-11-01 12:06 UTC, waheedahmed commented
Closing this in favor of https://github.com/edx/course-discovery/pull/410.

2016-11-01 12:06 UTC, closed without merging