feat: upgrade to Django 4.2
openedx/course-discovery pull request #4088
Opened 2023-09-12 16:19 UTC by gsueros

Issue: [edx/upgrades#207](https://github.com/openedx/public-engineering/issues/207)
Upgrade to Django 4.2

2023-09-12 16:19 UTC, openedx-webhooks commented
Thanks for the pull request, @gsueros!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2023-09-12 16:43 UTC, eLRuLL commented
@e0d could you please enable tests to run for this PR?

2023-09-12 17:10 UTC, e0d commented
Yep, done.

2023-09-12 17:39 UTC, gsueros commented
@irtazaakram I saw this PR https://github.com/openedx/course-discovery/pull/4086 related to the same issue about Django upgrade to 4.2, is this feature still needed?. Also there are test errors related to Django32 support, we have to keep support for Django32 or it should be removed from the repository.

2023-09-13 06:39 UTC, UsamaSadiq commented on .github/workflows/ci.yml
> +    - uses: actions/checkout@v3
We can skip the indentation only changes for now so only the relevant changes will be present in the PR. It'll make it easier to review the changes for the reviewer.

2023-09-13 06:39 UTC, UsamaSadiq commented on tox.ini
> +django_settings_module = course_discovery.settings.test
Reverting this back should resolve the bulk test failure across shards.
```suggestion
DJANGO_SETTINGS_MODULE = course_discovery.settings.test
```

2023-09-13 06:39 UTC, UsamaSadiq commented on requirements/constraints.txt
> +# -c common_constraints.txt
We are looking to do it in steps. First, add support without breaking tests for Django 3.2, then upgrade to Django 4.2 in a follow up PR. The breaking changes will be handled in the follow up PR.

2023-09-13 07:16 UTC, awais786 commented on .github/workflows/ci.yml
> +      if: matrix.db-version == 'mysql57'    # TODO: Remove this condition when removing 'mysql57' db-version.
Use mysql80.

2023-09-14 21:31 UTC, gsueros commented on requirements/constraints.txt
> +# -c common_constraints.txt
@UsamaSadiq do you recommend that I should revert the changes in the requirements resulting from updating Django to 4.2? and only keep changes for the 2 first steps in this issue https://github.com/openedx/public-engineering/issues/207 ?

2023-09-15 16:12 UTC, gsueros commented on .github/workflows/ci.yml
> +    - uses: actions/checkout@v3
@UsamaSadiq  Done!

2023-09-15 16:12 UTC, gsueros commented on tox.ini
> +django_settings_module = course_discovery.settings.test
Restored, thanks.

2023-09-15 17:21 UTC, gsueros commented
@e0d please could you help me to enable test to run in the PR?

2023-09-18 08:04 UTC, UsamaSadiq commented
@gsueros I've made an intermediate PR https://github.com/openedx/course-discovery/pull/4091 to handle the deprecation warnings separately. You can rebase your PR once it has been merged. This'll help you in weeding out the extra changes.

2023-09-18 08:27 UTC, UsamaSadiq commented on requirements/constraints.txt
> +# -c common_constraints.txt
Instead of commenting the `common_constraints.txt` file, we have a method to override any global constraint coming from common_constraints instead. 
You can update the Django version override from `Django<2.3` to `Django<3.2` in the line https://github.com/openedx/course-discovery/blob/master/Makefile#L64 instead and it'll override the global Django constraint.

2023-09-18 17:10 UTC, gsueros commented
@e0d please could you help me to enable test to run in the PR?

2023-09-18 17:11 UTC, gsueros commented on requirements/constraints.txt
> +# -c common_constraints.txt
@UsamaSadiq Done. Also I regenerated all requirements to be sure if everything it's OK.

2023-09-18 17:12 UTC, gsueros commented on .github/workflows/ci.yml
> +      if: matrix.db-version == 'mysql57'    # TODO: Remove this condition when removing 'mysql57' db-version.
@awais786 Done.

2023-09-19 08:21 UTC, UsamaSadiq commented on Makefile
> +	pip3 install -q -r requirements/pip_tools.txt
We shouldn't need to use pip3 since the workflow already runs in a `Python3.8` env which points to pip3 by default.

2023-09-19 08:21 UTC, UsamaSadiq commented on course_discovery/settings/base.py
> -USE_L10N = True
This change is not necessary for Django 4.2 since it is still supported so we can keep this for now.

2023-09-19 08:23 UTC, UsamaSadiq commented on requirements/common_constraints.txt
> +Django<=4.2
You shouldn't need to manually update `common_constraints.txt` file since it'll be overrided in Makefile.

2023-09-19 08:23 UTC, UsamaSadiq commented on requirements/constraints.txt
>  # The latest version require Django 4.0, remove once we have upgraded to Django 4.0
Let's also remove the comment related to the removed pin.

2023-09-19 08:45 UTC, UsamaSadiq requested changes
Hi @gsueros I've updated the issue description according to our internal discussion. We are no longer planning to provide backward compatibility with Django 3.2 so you can follow the instructions and remove the Django 3.2 related envs as well.

2023-09-19 22:27 UTC, gsueros commented on Makefile
> +	pip3 install -q -r requirements/pip_tools.txt
Done.

2023-09-19 22:28 UTC, gsueros commented on course_discovery/settings/base.py
> -USE_L10N = True
Done.

2023-09-19 22:28 UTC, gsueros commented on requirements/common_constraints.txt
> +Django<=4.2
@UsamaSadiq Done.

2023-09-19 22:28 UTC, gsueros commented on requirements/constraints.txt
>  # The latest version require Django 4.0, remove once we have upgraded to Django 4.0
Removed.

2023-09-19 22:31 UTC, gsueros commented
@UsamaSadiq already removed 3.2 backward compatibility, please could you enable to run CI tasks.

2023-09-19 22:34 UTC, gsueros commented on course_discovery/settings/base.py
> +STORAGES = {
@UsamaSadiq `Django 4.2` deprecates `STATICFILES_STORAGE` but has this bug https://code.djangoproject.com/ticket/34773, that is fixed in `Django 4.2.5`. Should we use `Django >= 4.2.5` to avoid issues with `STORAGES `?

2023-09-20 08:04 UTC, UsamaSadiq commented on course_discovery/settings/base.py
> +STORAGES = {
Our requirements structure will fetch the latest patch version so we don't need to have a minimum version constraint.

2023-09-20 08:40 UTC, UsamaSadiq commented
@gsueros please rebase your PR to the latest master branch. The PyMemcache backend migration change has been merged in the master branch which is needed to run the tests successfully with Django 4.2

2023-09-20 08:42 UTC, Ali-D-Akbar approved these changes

2023-09-20 08:47 UTC, Ali-D-Akbar reviewed
I approved the wrong PR so please disregard my approval.

2023-09-20 09:23 UTC, AfaqShuaib09 reviewed
Seems like issue is with the MultiSelectField
`countries = MultiSelectField(choices=COUNTRIES, null=True, blank=True)`
https://github.com/openedx/course-discovery/actions/runs/6241579132/job/16955605638?pr=4088

2023-09-21 04:30 UTC, gsueros commented
@UsamaSadiq this branch was already updated with the  PR about PyMemcache backend migration. I've just updated to  `PyMemcachedCache`  in  `.ci/docker-compose-ci.yml` and executed `make static` because calling `python manage.py collectstatic -v 0 --noinput` is causing the tests to fail. Please enable to run again the test.

2023-09-21 11:08 UTC, awais786 commented
@gsueros can you try this solution in this PR.
https://github.com/goinnn/django-multiselectfield/issues/134#issuecomment-1318886624

2023-09-21 14:01 UTC, gsueros commented
@awais786 thanks, actually I think this a good solution since we don't have any response for this issue.

2023-09-21 19:47 UTC, UsamaSadiq commented
@gsueros to resolve the back and forth communication delay and yoru effort to make the PR ready with minimal changes, I've went ahead and merged the PR https://github.com/openedx/course-discovery/pull/4101 to enable Django 4.2 support in tests. 
You can rebase your PR and now you'll only need to remove the django42 related changes, rest of the changes should be fixed and tests will pass as well.

2023-09-22 04:54 UTC, gsueros commented
@UsamaSadiq already  removed Django 4.2 related changes, also verified once more the requirements. Please enable tests workflow to verify if everything pass.

2023-09-22 05:05 UTC, UsamaSadiq commented on .ci/docker-compose-ci.yml
> -      - "mysql57"
We can also remove the MySql57 container defined above in the docker-compose-ci file.

2023-09-22 05:05 UTC, UsamaSadiq commented on Makefile
> +	sed 's/Django<4.0/Django<=4.2/g' requirements/common_constraints.txt > requirements/common_constraints.tmp
We can remove above sed commands as well since those constraints are no more included in global constraints.

2023-09-22 05:44 UTC, gsueros commented on .ci/docker-compose-ci.yml
> -      - "mysql57"
Done.

2023-09-22 05:44 UTC, gsueros commented on Makefile
> +	sed 's/Django<4.0/Django<=4.2/g' requirements/common_constraints.txt > requirements/common_constraints.tmp
Done.

2023-09-22 06:23 UTC, UsamaSadiq approved these changes
Changes look fine to me. We can attempt to merge this once production mysql has been updated to mysql80 and all tests are perfectly passing on this PR.

2023-09-22 07:17 UTC, UsamaSadiq requested changes

2023-09-22 07:17 UTC, UsamaSadiq commented on tox.ini
>      django32: -r requirements/django.txt
This line needs to be removed. 
```suggestion
```

2023-09-22 07:17 UTC, UsamaSadiq commented on tox.ini
>      django42: -r requirements/django42.txt
We need to use default django.txt now
```suggestion
    django42: -r requirements/django.txt
```

2023-09-22 07:20 UTC, gsueros commented on tox.ini
>      django42: -r requirements/django42.txt
@UsamaSadiq done.

2023-09-22 07:36 UTC, UsamaSadiq commented
@gsueros Let's run `make upgrade` to update the requirements and include the `django-admin-sortable2` back in the `local.txt` requirements which was removed for django 42 support.

2023-09-22 11:02 UTC, UsamaSadiq approved these changes

2023-09-22 11:03 UTC, UsamaSadiq commented
@gsueros A huge bundle of thanks for the efforts on this PR. This will be merged soon after removing the required mysql57 tests from CI settings once MySQL80 has been deployed to production.

2023-09-22 13:53 UTC, gsueros commented
> @gsueros A huge bundle of thanks for the efforts on this PR. This will be merged soon after removing the required mysql57 tests from CI settings once MySQL80 has been deployed to production.

@UsamaSadiq Thanks for the support in the upgrtade process. I will be attentive to new reviews and that it can be satisfactorily merge.

2023-09-26 12:45 UTC, awais786 commented
@gsueros can you please add this in `base.py`

Django 4.0+ uses zoneinfo if this is not set. We can remove this and
migrate to zoneinfo after Django 4.2 upgrade. See more on following url
https://docs.djangoproject.com/en/4.2/releases/4.0/#zoneinfo-default-timezone-implementation

USE_DEPRECATED_PYTZ = True

2023-09-26 16:29 UTC, gsueros commented
@awais786 just added this flag USE_DEPRECATED_PYTZ = True to `base.py`.

2023-10-03 01:30 UTC, mphilbrick211 commented
Hi @UsamaSadiq and @awais786! Would one of you be able to please re-enable the tests to run on this PR? Thanks!

2023-10-03 18:58 UTC, awais786 commented
@gsueros please rebase.

2023-10-03 23:34 UTC, gsueros commented
> @gsueros please rebase.

@awais786 rebased.

2023-10-04 04:59 UTC, openedx-webhooks commented
@gsueros Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/4088&entry.1484655318=https://github.com/gsueros&entry.752974735=2023-09-12+16:19&entry.1917517419=2023-10-04+04:59&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->

2023-10-04 05:43 UTC, awais786 commented
These waiting checks ` django32, mysql57` and others need to remove from workflow. Only owning team can do this.

2023-10-05 17:02 UTC, iamsobanjaved commented on requirements/django.txt
> +django==4.2
Can you re-run the make upgrade, so Django has latest patch version

2023-10-05 19:26 UTC, gsueros commented on requirements/django.txt
> +django==4.2
@iamsobanjaved   Done.

2023-10-05 19:34 UTC, openedx-webhooks commented
@gsueros Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/4088&entry.1484655318=https://github.com/gsueros&entry.752974735=2023-09-12+16:19&entry.1917517419=2023-10-05+19:33&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->

2023-10-05 19:36 UTC, awais786 commented
@Ali-D-Akbar Please review this PR. 
In this PR you have to remove dango32+mysql57  checks from github works flow.

2023-10-05 19:39 UTC, awais786 commented
@gsueros did you run makemigration and migrate command ? Please run these command once to make sure nothing happens.

2023-10-05 19:54 UTC, UsamaSadiq commented
@gsueros please squash your commits and rebase with the latest master branch. It'll help you avoid making mistakes when resolving conflicts during the rebase step.

2023-10-06 05:59 UTC, gsueros commented
> @gsueros did you run makemigration and migrate command ? Please run these command once to make sure nothing happens.

Done.

2023-10-06 06:00 UTC, gsueros commented
> @gsueros please squash your commits and rebase with the latest master branch. It'll help you avoid making mistakes when resolving conflicts during the rebase step.

@UsamaSadiq Done.

2023-10-06 12:21 UTC, openedx-webhooks commented
@gsueros Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/4088&entry.1484655318=https://github.com/gsueros&entry.752974735=2023-09-12+16:19&entry.1917517419=2023-10-06+12:21&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->

2023-10-06 12:45 UTC, awais786 commented
@gsueros tests are not running

giving following error `use allowlist_externals to allow it`

2023-10-06 12:58 UTC, UsamaSadiq commented
@gsueros would you please add me as a maintainer in your fork so I can help you in fixing these issues and make the PR ready to merge as soon as possible. Right now, I am only able to guide you step by step which is taking time and we've reached our deadline for the branch cut for next release of openedx (branch release is expected on upcoming Tuesday).

2023-10-06 14:16 UTC, gsueros commented
> @gsueros would you please add me as a maintainer in your fork so I can help you in fixing these issues and make the PR ready to merge as soon as possible. Right now, I am only able to guide you step by step which is taking time and we've reached our deadline for the branch cut for next release of openedx (branch release is expected on upcoming Tuesday).

@UsamaSadiq I already send you and ivitation.

2023-10-06 14:23 UTC, openedx-webhooks commented
@gsueros Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/4088&entry.1484655318=https://github.com/gsueros&entry.752974735=2023-09-12+16:19&entry.1917517419=2023-10-06+14:23&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->

2023-10-07 10:40 UTC, awais786 commented on requirements/production.txt
> +django==4.2.6
Version upgraded.

2023-10-07 10:44 UTC, awais786 approved these changes

2023-10-12 20:37 UTC, kdmccormick commented
I've made the Django3.2 checks optional so that this PR can merge whenever it's ready.

2023-10-16 12:17 UTC, merged

2023-10-16 12:17 UTC, openedx-webhooks commented
@gsueros 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/course-discovery&entry.867055334=https://github.com/openedx/course-discovery/pull/4088&entry.1484655318=https://github.com/gsueros&entry.752974735=2023-09-12+16:19&entry.1917517419=2023-10-16+12:17&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->

2023-10-18 08:42 UTC, awais786 commented
@gsueros congrats !!!

2023-10-18 12:28 UTC, gsueros commented
> @gsueros congrats !!!

Thanks.