Implement backend to save course key for already created course run.
openedx/course-discovery pull request #410
Opened 2016-11-01 12:05 UTC by waheedahmed

[ECOM-6178](https://openedx.atlassian.net/browse/ECOM-6178)

Implement the backend to save course run key in pending studio instances and send an email to course team with subject "Studio instance created".

2016-11-01 14:43 UTC, waheedahmed commented
@bderusha Please review this PR, I closed previous PR https://github.com/edx/course-discovery/issues/406 and created this new one to include the ajax call from dashboard.

2016-11-02 18:25 UTC, bderusha requested changes

2016-11-02 18:25 UTC, bderusha commented on course_discovery/apps/publisher/emails.py
> +        template = get_template(txt_template)
NIT: use distinct variable names for the templates.  e.g. `txt_template = get_template(txt_template_path)`

2016-11-02 18:25 UTC, bderusha commented on course_discovery/apps/publisher/emails.py
> +        logger.exception('Failed to send email notifications for course_run [%s]', course_run.id)
please add an error case in the tests for this

2016-11-02 18:25 UTC, bderusha commented on course_discovery/apps/publisher/emails.py
> +        to_addresses = course_run.course.get_group_users_emails()
Question:  Can we BCC these email addresses?

2016-11-02 18:25 UTC, bderusha commented on course_discovery/static/js/publisher/views/dashboard.js
> +                alertTimeout(10000, '.studio-instance-success');
Is this part of any acceptance criteria?  I don't remember seeing anything about the message going away.

2016-11-02 18:25 UTC, bderusha commented on course_discovery/static/js/publisher/views/dashboard.js
> +                    "studioLinkTag": "<a hrep=''>"+ courseKeyValue +"</a>",
`href`

2016-11-03 07:04 UTC, awais786 commented on course_discovery/apps/publisher/emails.py
> +        to_addresses = course_run.course.get_group_users_emails()
@waheedahmed add a separate story for this.

2016-11-03 09:29 UTC, waheedahmed commented on course_discovery/apps/publisher/emails.py
> +        to_addresses = course_run.course.get_group_users_emails()
@bderusha Sure, done.

@awais786 I think you can create a new story for other email functionalities.

2016-11-03 10:01 UTC, waheedahmed commented
Dear @bderusha addressed all your comments, please take another look.

2016-11-03 20:00 UTC, bderusha commented on course_discovery/apps/publisher/emails.py
> +        email_msg = EmailMultiAlternatives(subject, plain_content, from_address, bcc=to_addresses)
Just want to double check that this works without anything in the `to` field.  If not we may need to setup some dummy `to` address.  Can you confirm either way?

2016-11-03 20:00 UTC, bderusha approved these changes

2016-11-04 09:51 UTC, waheedahmed commented on course_discovery/apps/publisher/emails.py
> +        email_msg = EmailMultiAlternatives(subject, plain_content, from_address, bcc=to_addresses)
@bderusha Its working fine with nothing in ```to``` field.

2016-11-04 09:52 UTC, waheedahmed commented on course_discovery/apps/publisher/emails.py
> +        email_msg = EmailMultiAlternatives(subject, plain_content, from_address, bcc=to_addresses)
<img width="901" alt="screen shot 2016-11-04 at 2 51 39 pm" src="https://cloud.githubusercontent.com/assets/2851134/20001496/46e20d00-a29e-11e6-81c8-1bb67b980459.png">

2016-11-04 11:20 UTC, awais786 approved these changes

2016-11-04 11:20 UTC, awais786 commented on course_discovery/apps/publisher/emails.py
> +        to_addresses = course_run.course.get_group_users_emails()
bcc_addresses

2016-11-04 11:20 UTC, awais786 commented on course_discovery/apps/publisher/views.py
> +class UpdateCourseKeyView(mixins.LoginRequiredMixin, mixins.ViewPermissionMixin, UpdateAPIView):
Why using ViewPermissionMixin here ?

2016-11-04 11:24 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +class UpdateCourseKeyView(mixins.LoginRequiredMixin, mixins.ViewPermissionMixin, UpdateAPIView):
@awais786 We need to check the permission of the user on object who is adding the course key.

2016-11-04 11:24 UTC, waheedahmed commented on course_discovery/apps/publisher/emails.py
> +        to_addresses = course_run.course.get_group_users_emails()
I think no need to change this.

2016-11-04 11:44 UTC, waheedahmed commented
I'll merge it when @awais786's PR https://github.com/edx/course-discovery/pull/421 is ready to merge.

2016-11-11 12:31 UTC, awais786 commented
@waheedahmed @bderusha I am closing this PR. I have opened the new PR.
I have already merged my PR into master and this PR is created from my branch. So I have to close it create the new one from master.
New PR https://github.com/edx/course-discovery/pull/435

2016-11-11 12:31 UTC, closed without merging

2016-11-11 12:37 UTC, awais786 commented
Also bcc is not working with django-ses. So I have moved this back to `to`.  I will file a separate to implement this.