Awais786/ecom 6240 tabs design with sass
openedx/course-discovery pull request #421
Opened 2016-11-04 10:02 UTC by awais786

WIP

2016-11-04 11:02 UTC, waheedahmed requested changes

2016-11-04 11:02 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +    page_size = 5
Do we need this now?

2016-11-04 11:02 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        need_studio_request_courses = unpublished_courseruns.filter(lms_course_id__isnull=True)
Change it to ```studio_request_courses```.

2016-11-04 11:02 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        context['need_studio_request_courses'] = [CourseRunWrapper(course_run) for course_run in need_studio_request_courses]
Change it to ```studio_request_courses```.

2016-11-04 11:02 UTC, waheedahmed commented on course_discovery/static/sass/publisher/dashboard.scss
> +      float: left;
RTL support.

2016-11-04 11:02 UTC, waheedahmed commented on course_discovery/templates/publisher/dashboard.html
> +        $(document).ready(function() {
Move this JavaScript to its own file ```dashboard.js```.

2016-11-04 11:21 UTC, waheedahmed approved these changes

2016-11-04 12:21 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +        published_state = factories.StateFactory(name=State.PUBLISHED)
Why storing in variables? Just assign them directly to ```state```.

2016-11-04 13:52 UTC, awais786 commented
![screencapture-127-0-0-1-8009-publisher-dashboard-1478267360056](https://cloud.githubusercontent.com/assets/445320/20007738/839cf126-a2bf-11e6-85c7-84c8a6b789b1.png)

2016-11-04 14:24 UTC, awais786 commented
@edx/ecommerce Please review this PR.

2016-11-07 19:03 UTC, awais786 commented
@edx/ecommerce Please review this PR.

2016-11-07 19:09 UTC, clintonb commented
@awais786 please rebase and squash before the review.

2016-11-07 19:44 UTC, bderusha requested changes

2016-11-07 19:44 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +            self.assertContains(response, '<div id="tab-studio" class="tab-content active">')
For HTML elements please extract them into well-named variables e.g. `studio_requests_tab_active`

2016-11-07 19:44 UTC, bderusha commented on course_discovery/static/js/publisher/views/dashboard.js
> +        $(".tab-content").not(tab).css("display", "none");
I have many questions about accessibility of tabs.
https://openedx.atlassian.net/wiki/display/FEDX/Tabs+Component

@cptvitamin What is the latest recommendation for tabs today?

2016-11-07 19:44 UTC, bderusha commented on course_discovery/templates/publisher/dashboard.html
> +            <li {% if studio_count == 0 %}class="active"{% endif %}><a href="#tab-progress"><span>0</span>{% trans "IN PROGRESS" %}</a></li>
Similar a11y question about using anchor tags for tabs

cc: @cptvitamin

2016-11-07 19:44 UTC, bderusha commented on course_discovery/templates/publisher/dashboard.html
> +            <div id="tab-progress" class="tab-content {% if studio_count == 0 %}active{% endif %}"></div>
NIT: just to ensure we always have an active tab can this be `if studio_count <= 0`

2016-11-07 19:44 UTC, bderusha commented on course_discovery/templates/publisher/dashboard.html
> +                                {% trans "Studio URL" %}
`Studio Course Run Key`

2016-11-07 20:16 UTC, cptvitamin commented on course_discovery/static/js/publisher/views/dashboard.js
> +        $(".tab-content").not(tab).css("display", "none");
@awais786 @bderusha The [Tabs Component](https://openedx.atlassian.net/wiki/display/FEDX/Tabs+Component) document you referenced is up to date. To summarize, a Tab Panel Widget consists of a single "tablist" with any number of "tabs" only one of which can be selected at any given time. Each tab controls a corresponding "tabpanel".  Tabpanels can be displayed either on focus of their corresponding tab, or on explicit selection with the keyboard or mouse. The defining characteristic of a tab panel widget is that the tablist has a single tab stop, meaning if you are using the keyboard, only one of the tabs is accessible using the TAB key.  Subsequent presses of the tab key will move you into the active tab, not to the next tab in the sequence. Keyboard users use the arrow keys to move between tabs.

2016-11-07 20:18 UTC, cptvitamin commented on course_discovery/templates/publisher/dashboard.html
> +            <li {% if studio_count == 0 %}class="active"{% endif %}><a href="#tab-progress"><span>0</span>{% trans "IN PROGRESS" %}</a></li>
@awais786 @bderusha typically, natively focusable elements (like links or buttons) are not used for the tabs because tablists are only supposed to ahve a single tabstop. Typically, you create a list of elements, only one of which has a tabindex=0. Once that element has focus, the user can use the arrowkeys to move to the next tab in the sequence, upon which, that element would get the tabindex=0 and it would be removed from any other.

2016-11-09 12:06 UTC, awais786 commented
<img width="1010" alt="screen shot 2016-11-09 at 5 05 52 pm" src="https://cloud.githubusercontent.com/assets/445320/20137836/cc5b89d0-a69e-11e6-95e0-8c165e957378.png">

2016-11-09 12:07 UTC, awais786 commented
@cptvitamin @bderusha Please review this PR again.

2016-11-09 14:15 UTC, cptvitamin commented
@awais786 can I manually test this somewhere?

2016-11-09 15:27 UTC, awais786 commented
@cptvitamin I don't have the sandbox for discovery.  And it's time consuming task. I can send you offline page with all css/js.

2016-11-09 17:20 UTC, cptvitamin requested changes
The tab control works great.  Nice work!

2016-11-09 17:20 UTC, cptvitamin commented on course_discovery/templates/publisher/dashboard/studio_requests.html
> +                                <input type="text" class="field-input input-text small" />
This input needs a label. The label should consist of its generic purpose and the course it applies to:

If the course name is AC101 the label should be:
AC101 Studio Course Run Key

This is best done using the aria-labelledby attribute which takes a space separated list of IDrefs. However, both pieces of data will need a unique ID to reference. 

Given:
`<th id="column-title">{% trans "Studio Course Run Key" %} </th>` 
`<td class="sorting_1" id="course-title-0"><a href="">AC101</a></td>` 
You would have this:
`<input type="text" class="field-input input-text small" aria-labelledby="course-title-0 column-title" />`

2016-11-09 17:20 UTC, cptvitamin commented on course_discovery/templates/publisher/dashboard/studio_requests.html
> +                    <tr>
for some reason, a `role="row"` is being added here.  It is redundant and will actually trigger test failures. Please remove it.

2016-11-09 17:20 UTC, cptvitamin commented on course_discovery/templates/publisher/dashboard/studio_requests.html
> +                    <th>
These table headers are sortable. They require a ```role="button"``` However, that would override their default semantics of a table header, which is also important. I recommend leaving the ```th``` alone and adding a button as a child that is used to sort the column. Move all the aria-attributes you have on the ```th``` to the button (aria-controls, aria-label, aria-sort)

2016-11-09 17:20 UTC, cptvitamin commented on course_discovery/static/sass/publisher/dashboard.scss
> +      text-transform: uppercase;
Can we title case this? uppercase causes a lot of problems for accessibility/legibility/readability

2016-11-09 17:20 UTC, cptvitamin commented on course_discovery/templates/publisher/dashboard/studio_requests.html
> +                                <button class="btn-inline">{% trans "ADD" %}</button>
Can we title case this? uppercase causes a lot of problems for accessibility/legibility/readability. The Screen reader announces this as A D D, not Add.

2016-11-09 17:20 UTC, cptvitamin commented on course_discovery/static/sass/publisher/dashboard.scss
> +        }
Can we add a :focus state there that is different from is-active? Currently, when you tab to the active/selected tab, there is no visual focus indicator to tell you that is where your focus is.

2016-11-09 17:26 UTC, awais786 commented on course_discovery/templates/publisher/dashboard/studio_requests.html
> +                    <th>
@cptvitamin I am using the plugin for sorting/paging purpose. Following attributes appear by the plugin.
`<th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="
                        Course Name
                    : activate to sort column descending" aria-sort="ascending">
                        Course Name
                    </th>`

[datatables example](https://datatables.net/examples/basic_init/table_sorting.html)

2016-11-09 17:27 UTC, awais786 commented on course_discovery/templates/publisher/dashboard/studio_requests.html
> +                    <tr>
This is due to the plugin.

2016-11-09 19:32 UTC, awais786 commented
@bderusha @cptvitamin We are using plugin for the pagination and sorting purpose. So few things are auto generated. I would suggest to create a separate ticket for complete accessibility implementation.

2016-11-10 11:27 UTC, awais786 commented on course_discovery/static/sass/publisher/dashboard.scss
> +        }
Added focus state here.

2016-11-10 11:30 UTC, awais786 commented
@cptvitamin I have implemented most of things. Few things are due to the plugin. 
@bderusha FYI

2016-11-10 14:44 UTC, awais786 commented
@bderusha Please review this PR.

2016-11-10 16:04 UTC, cptvitamin commented
@awais786 please ping me when this is in production so I can conduct another review and log any remaining issues.

2016-11-10 18:14 UTC, awais786 commented
@bderusha Please review this PR again.
I have created a separate ticket for accessibility.
https://openedx.atlassian.net/browse/ECOM-6341

2016-11-10 19:31 UTC, bderusha approved these changes
Few minor things.  Otherwise looks good!

2016-11-10 19:31 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +        ).select_related('course').all().order_by('-state__modified')
we should also use `select_related('state')` here

2016-11-10 19:31 UTC, bderusha commented on course_discovery/templates/publisher/dashboard/studio_requests.html
> +    <p>{% trans "The list below are the are course that need a studio instance to start development." %}</p>
`The list below are the courses that need a studio instance to start development.`

2016-11-10 19:36 UTC, bderusha commented
@cptvitamin Just to be clear as to why we are pushing the DataTables plugin specific a11y concerns.   This feature is part of an MVP which will be piloted with a small group.  We want to ensure that the pilot group finds the feature-set valuable first. Once it has been validated we will determine if we can make the plugin meet our a11y standards or if we need to roll our own.

2016-11-11 07:35 UTC, merged