[Work In Progress] Get username from token
openedx/course-discovery pull request #424
Opened 2016-11-07 19:39 UTC by MatthewPiatetsky

Also only allow JWT tokens

2016-11-07 19:42 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        response = self._make_request(initial_page, username)
If this is in fact only necessary for the CoursesApi it seems like we probably don't want to put the username variable in the abstract data loader, using self outside the init is a pylint error, which is I'm passing it here (though we could disable it)

2016-11-07 19:42 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            username = jwt.decode(self.access_token, verify=False).get('preferred_username', '')
verify=False just pulls out the information without verifying the signature

2016-11-07 19:47 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            username = ''
If we can't get the username from the token just fall back to what the result of not passing a username to the course api would be. (If this is in fact the behavior that is happening being explicit about it could at least alleviate some of the confusion)

2016-11-07 19:48 UTC, clintonb requested changes

2016-11-07 19:48 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        response = self._make_request(initial_page, username)
Update `AbstractDataLoader` to accept `kwargs`. Pass the username as a `kwarg` and store it for this particular data loader. Move all of the decoding logic up to the management command level.

2016-11-07 19:48 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            username = jwt.decode(self.access_token, verify=False).get('preferred_username', '')
Move this to the management command. Keep verification since we should always have a valid token.

2016-11-07 20:27 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            username = jwt.decode(self.access_token, verify=False).get('preferred_username', '')
isn't the secret for encoding the JWT token set in LMS or the extension that LMS uses?  
If catalog does not have that wouldn't I fail on signature verification?

2016-11-07 20:33 UTC, MatthewPiatetsky commented
did we want to remove the ability to pass token_type or remove the ability to pass a token command line altogether?

2016-11-07 20:35 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/data_loaders/__init__.py
> +    SUPPORTED_TOKEN_TYPES = ('jwt',)
Should we remove this? Or keep if in the future we might use other types of tokens?

2016-11-07 21:24 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/__init__.py
> +    SUPPORTED_TOKEN_TYPES = ('jwt',)
We should remove the ability to pass in a token altogether. We've never actually used it.

2016-11-07 21:25 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/data_loaders/__init__.py
> +    SUPPORTED_TOKEN_TYPES = ('jwt',)
Ok. We actually say to use it here https://open-edx-course-catalog.readthedocs.io/en/latest/course_metadata.html#retrieving-course-metadata but I can update that

2016-11-07 21:28 UTC, clintonb requested changes

2016-11-07 21:28 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +
Revert.

2016-11-07 21:28 UTC, clintonb commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +                    except jwt.exceptions.DecodeError:
If decode fails, the entire command should fail. There is clearly something wrong with the token.

2016-11-07 21:28 UTC, clintonb commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +                        username = jwt.decode(access_token, verify=False).get('preferred_username', '')
If the token doesn't contain the `preferred_username` claim, the command should fail.

2016-11-07 21:28 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/__init__.py
> +    SUPPORTED_TOKEN_TYPES = ('jwt',)
Correction: it is used by `ManagementViewSet.refresh_course_metadata()` which should also be removed.

2016-11-07 21:31 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/__init__.py
> +    SUPPORTED_TOKEN_TYPES = ('jwt',)
Update the docs, too.

2016-11-08 16:52 UTC, rlucioni requested changes
@MatthewPiatetsky left some comments inline. Let's keep an eye on https://github.com/edx/course-discovery/pull/404#pullrequestreview-7261966. I still think fixing that API is preferable to making changes here.

2016-11-08 16:52 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            except Exception:
Keep this exception handler confined to the token request. The decode should occur outside of it, in case, say, the preferred_username key is missing. If that were to occur, the message logged below would be confusing.

2016-11-08 16:52 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +ACCESS_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6ImpvaG4ifQ.SFJ4FVliPTP27EhxLHeTHDJJ6bTanoHFq-DWtMg
Generate this in test code instead of hardcoding it.

2016-11-08 18:21 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +ACCESS_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6ImpvaG4ifQ.SFJ4FVliPTP27EhxLHeTHDJJ6bTanoHFq-DWtMg
why, isn't the actual token generation something that happens in the extension in LMS? There isn't actually code to test in this management command that generates a token

2016-11-08 19:09 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +ACCESS_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6ImpvaG4ifQ.SFJ4FVliPTP27EhxLHeTHDJJ6bTanoHFq-DWtMg
In production-like deployments, JWTs come from our auth provider, which happens to be from the LMS. However, that doesn't preclude you from generating your own tokens for testing, which you can do with the `jwt` module. Doing that allows you to more clearly show what's being encoded in the token, and makes it easier to change in the future.

2016-11-08 22:42 UTC, MatthewPiatetsky commented
@clintonb @rlucioni I think I've addressed most of your feedback. 
As to the discussion on the other PR, I don't have a strong opinion on any approach, but it sounds like there are some differences of opinion. How do we think we will come to a decision?
(Note that most of the changes in this PR do not relate to pulling the username from the token, so if we decide not to do that, I can just remove those sections)

2016-11-09 00:39 UTC, clintonb requested changes

2016-11-09 00:39 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/tests/mixins.py
>      @ddt.data(
`ddt` is no longer needed here.

2016-11-09 00:39 UTC, clintonb commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +        token_type = 'JWT'
This variable is not necessary.

2016-11-09 00:39 UTC, clintonb commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            logger.info('No access token provided. Retrieving access token using client_credential flow...')
Update this: `Retrieving access token for partner [{partner.short_code}]...`

2016-11-09 00:39 UTC, clintonb commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +            'access_token': str(jwt.encode({'preferred_username': 'bob'}, 'secret', algorithm='HS256'), 'utf-8'),
Store this in the constant.

2016-11-09 00:39 UTC, clintonb commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +            def raise_exception():
This seems dirty. Mock `EdxRestApiClient.get_oauth_access_token()` so that it raises an exception.

2016-11-09 16:04 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +            def raise_exception():
isn't that what I'm doing in mock_access_token_api?

2016-11-09 16:28 UTC, clintonb commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +            def raise_exception():
The idea is the same. However, `mock_access_token_api` mocks the HTTP response, not `EdxRestApiClient.get_oauth_access_token()`. 

I find the implementation below to be a bit cleaner than making fake functions.

``` python
with mock.patch('edx_rest_api_client.clientEdxRestApiClient.get_oauth_access_token', side_effect=Exception):
  ...
```

2016-11-09 16:32 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +        token_type = 'JWT'
It is used in a few places in this file. I could remove the need for specifying token type altogether, but imo it is helpful to explicitly clarify what the token_type is so people have an easier time understanding the auth.

2016-11-09 16:33 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +            def raise_exception():
got it, thanks!

2016-11-09 17:38 UTC, MatthewPiatetsky commented
@edx/ecommerce talked with @rlucioni @mikedikan during standup I believe the approach we settled on was finish this PR to get things working and simultaneously settle on an approach that everyone is happy with on the other discussion, and then create a dev story and pick it up (potentially next sprint)

2016-11-09 18:55 UTC, rlucioni requested changes

2016-11-09 18:55 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
Why are you passing `verify=False` here? I understand that all we need to do here is read the contents of the token, but is it wise to do away with token verification in this context?

2016-11-09 18:55 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +ACCESS_TOKEN = str(jwt.encode({'preferred_username': 'bob'}, 'secret', algorithm='HS256'), 'utf-8')
The algorithm should already be specified in settings. Do you really need to provide it again here?

2016-11-09 18:55 UTC, rlucioni commented on docs/course_metadata.rst
> +    $ ./manage.py refresh_course_metadata
Also change the line above this that refers to the JWT. Maybe make a note that the command retrieves it's own access token via the client credentials grant.

2016-11-09 19:29 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
I was getting a signature verification error presumably because I don't know what the secret is if the secret is stored in LMS, so I can't verify the signature if I'm not in the LMS

2016-11-09 19:33 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +ACCESS_TOKEN = str(jwt.encode({'preferred_username': 'bob'}, 'secret', algorithm='HS256'), 'utf-8')
changed

2016-11-09 19:33 UTC, MatthewPiatetsky commented on docs/course_metadata.rst
> +    $ ./manage.py refresh_course_metadata
changed

2016-11-09 19:48 UTC, clintonb commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
We do have the secret. Look at `settings.JWT_AUTH['JWT_SECRET']`.

2016-11-09 19:56 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
But the token gets generated in the LMS and verified by the LMS.
We do not pass the JWT_SECRET to LMS when it generates its token, only the OpenID client key/secret pair.
So the JWT_SECRET in course_discovery could be different from the one in LMS, (and probably is) right?

2016-11-09 20:00 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
We currently use symmetric keys. The secrets are the same.

2016-11-09 20:06 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
Locally, JWT_SECRET_KEY is not set for either, so it should fall back to SECRET_KEY
I checked the SECRET_KEY in my local catalog and local platform and they are not the same

2016-11-09 20:22 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
They are the same in working, production-like environments. We define values for JWT_SECRET_KEY in private settings specific to each developer.

2016-11-09 20:35 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
so what should we do to make it work locally?  
And what if I want to point my local catalog to stage or prod LMS, if I don't want to run my local LMS  
Then I don't know what those secrets are, or if I am able to go to the environment and find out I will need to update my local settings everytime the secret changes  
This seems like a major complication to use this command locally

2016-11-09 20:59 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
That's a fair point, forcing verification here would require access to the signing token from the LMS you're pointing at. What's at stake if we opt not to verify the token here? We might end up trying to use a bad username on some requests? That doesn't seem like a big deal. Thoughts?

2016-11-09 21:11 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
Since LMS is the one actually responsible for generating and verifying the token, it doesn't seem necessary to me to verify it on the catalog side. I would hope that if LMS cannot create a token, it would fail on token creation, rather than giving back some sort of broken token

2016-11-10 15:18 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
@MatthewPiatetsky anyone using/trusting the token is responsible for verifying its validity, not just the LMS. That said, in this context, I don't see any harm in extracting the username without checking the signature. I'm in favor of what you have here, unless @clintonb is opposed.

2016-11-10 15:31 UTC, clintonb approved these changes
Remember to squash your commits, and delete your branch after merging.

2016-11-10 15:31 UTC, clintonb commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +    def mock_access_token_api(self, requests_mock=None, callback=None):
The changes here are not necessary.

2016-11-10 15:31 UTC, clintonb commented on course_discovery/apps/course_metadata/management/commands/refresh_course_metadata.py
> +            username = jwt.decode(access_token, verify=False)['preferred_username']
This is fine as-is.

2016-11-10 15:31 UTC, clintonb commented on docs/course_metadata.rst
> +This command retrieves a JWT access token from the LMS instance that your OpenID Connect URL points to.
The command retrieves a JWT access token from the configured OpenID Connect provider.

2016-11-10 15:40 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +    def mock_access_token_api(self, requests_mock=None, callback=None):
thanks, changed

2016-11-10 15:40 UTC, MatthewPiatetsky commented on docs/course_metadata.rst
> +This command retrieves a JWT access token from the LMS instance that your OpenID Connect URL points to.
changed

2016-11-10 15:51 UTC, rlucioni approved these changes

2016-11-10 18:11 UTC, merged