feat: adding course run statuses to programs/pathways
openedx/course-discovery pull request #4248
Opened 2024-01-26 00:55 UTC by kiram15

Adding in the course_run_status variable for both programs and pathways as both can be added under highlights (along with courses).

2024-01-29 17:23 UTC, marlonkeating requested changes

2024-01-29 17:23 UTC, marlonkeating commented on course_discovery/apps/course_metadata/models.py
> +    def course_run_statuses(self):
Code looks identical to Program.course_run_statuses, can we have it in a helper method?

2024-01-29 17:23 UTC, marlonkeating commented on course_discovery/apps/api/tests/test_serializers.py
> +        # expected['course_run_statuses'] = []
Commented code needed?

2024-01-29 18:16 UTC, kiram15 commented on course_discovery/apps/course_metadata/models.py
> +    def course_run_statuses(self):
The three look similar but they have different things that they loop through depending on the original model, and I feel like showing what its looping through instead of abstracting it makes the code more readable

2024-01-29 19:14 UTC, marlonkeating commented on course_discovery/apps/course_metadata/models.py
> +    def course_run_statuses(self):
As far as I can see, the only line that really differs between the 3 methods is
`for course_run in some_list_of_course_runs:`

In my view that shared structure, along with the common business logic (that we would ideally like to change in as few places as possible should it change in the future) makes this a prime candidate for using a single helper method.

2024-01-29 21:47 UTC, marlonkeating requested changes

2024-01-29 21:47 UTC, marlonkeating commented on course_discovery/apps/course_metadata/utils.py
> +    return sorted(list(statuses))
We're also sorting `statuses` in the functions that use this helper.  We can do it either place I think, but we only need to do it once.

2024-01-29 21:47 UTC, marlonkeating commented on course_discovery/apps/course_metadata/utils.py
> +def get_course_run_statuses(statuses, course_runs):
nit: The `statuses` Set is always empty in all the places this is called.  Do we expect to pass in non-empty Sets in the future, or could we just create the empty set in this method?

2024-01-29 22:26 UTC, marlonkeating commented on course_discovery/apps/course_metadata/models.py
> +        return get_course_run_statuses(statuses, self.course_runs.all())
Should we be sorting here like we are in the other places?

2024-01-29 22:42 UTC, marlonkeating approved these changes

2024-01-30 19:23 UTC, Ali-D-Akbar reviewed
Just a suggestion before approval.

2024-01-30 19:23 UTC, Ali-D-Akbar commented on course_discovery/apps/course_metadata/models.py
> +        return sorted(list(statuses))
In this example, we may have a lot of DB queries for statuses of each course_run in each course in each program.

A better approach would be to have `programs = self.programs.prefetch_related('courses__course_runs')` before all of this hence all of this is done in one single DB call for each program.

2024-02-01 15:54 UTC, Ali-D-Akbar approved these changes

2024-02-01 15:55 UTC, merged