Fix: [ENT-8400]: added transcript_languages_search_facet_names to CourseRunSerializer
openedx/course-discovery pull request #4302
Opened 2024-03-26 16:05 UTC by mahamakifdar19

### Ticket
[ENT-8400](https://2u-internal.atlassian.net/browse/ENT-8400)

### Description
- Reapplies PR [4269](https://github.com/openedx/course-discovery/pull/4296) that was reverted and resolves the mentioned issue. 
- The error occurred because the language `Tagalog` was stored in the `LanguageTag` model without a corresponding 'name_t' (Name for translation) in the `LanguageTagTranslation` model. This caused an error when the existing `get_search_facet_display` method looked for a corresponding name for translation.

### Resolution
 I've added a validation check to verify the existence of the corresponding `name_t` (Name for translation) in the `LanguageTagTranslation` model before accessing it, furthermore I have disabled the translation flag for `get_transcript_languages_search_facet_names` because we do not require translated transcript language names, and not all languages stored in transcript_languages have a corresponding name for translation stored.

```
File "/edx/app/discovery/discovery/course_discovery/apps/api/serializers.py", line 1096, in get_transcript_languages_search_facet_names
    transcript_languages_facet_names.append(language.get_search_facet_display(translate=True))
  File "/edx/app/discovery/discovery/course_discovery/apps/ietf_language_tags/models.py", line 29, in get_search_facet_display
    return self.translated_macrolanguage if translate else self.macrolanguage
  File "/edx/app/discovery/discovery/course_discovery/apps/ietf_language_tags/models.py", line 22, in translated_macrolanguage
    return self.name_t.split('-')[0].strip()
  File "/edx/app/discovery/venvs/discovery/lib/python3.8/site-packages/parler/fields.py", line 142, in __get__
    translation = instance._get_translated_model(use_fallback=True, meta=meta)
  File "/edx/app/discovery/venvs/discovery/lib/python3.8/site-packages/parler/models.py", line 620, in _get_translated_model
    raise meta.model.DoesNotExist(
parler.models.DoesNotExist: language tag does not have a translation for the current language!
language tag ID #tl, language=en (tried fallbacks en)
Attempted to read attribute name_t.
```

2024-03-26 16:53 UTC, DawoudSheraz commented on course_discovery/apps/api/tests/test_serializers.py
> +            'transcript_languages_search_facet_names': None
It would be good to have an actual test case in here, as it would have caught the issue before.

2024-03-26 16:54 UTC, DawoudSheraz commented on course_discovery/apps/api/serializers.py
> +                            'enterprise_subscription_inclusion', 'transcript_languages_search_facet_names')
method fields are read_only by default, you don't need it explicitly here https://www.django-rest-framework.org/api-guide/fields/#serializermethodfield

2024-03-27 05:39 UTC, saleem-latif requested changes

2024-03-27 05:39 UTC, saleem-latif commented on course_discovery/apps/api/serializers.py
> +            return None
I think it would be better to return en empty list here, to keep the return type consistent.

2024-03-27 05:39 UTC, saleem-latif commented on course_discovery/apps/api/serializers.py
> +            return None
If you agree with the above, then this can be refactored into
```
return [
    lang.get_search_facet_display() for lang in obj.transcript_languages.all()
]
```

2024-03-27 08:00 UTC, mahamakifdar19 commented on course_discovery/apps/api/serializers.py
> +            return None
> I think it would be better to return en empty list here, to keep the return type consistent.

@saleem-latif returning None because this attribute will be stored as is in Algolia, and Algolia treats None values by ignoring and not storing them. However, I am uncertain about how Algolia will handle an empty list..
Reference: https://github.com/openedx/enterprise-catalog/blob/64bcd04cb9874ad8efef221c06a904935f2bdebc/enterprise_catalog/apps/catalog/algolia_utils.py#L443

2024-03-27 10:01 UTC, saleem-latif commented on course_discovery/apps/api/serializers.py
> +            return None
@mahamakifdar19 We already have fields in Algolia with empty list as values. I think empty list are acceptable.

I think we should not have conditional fields in Algolia, Having a field with empty list is better than not having thee field for empty values. Does that make sense?

2024-03-27 10:15 UTC, saleem-latif approved these changes
Looks Good 👍🏼

2024-03-27 11:24 UTC, DawoudSheraz approved these changes

2024-03-27 12:07 UTC, merged