Published course run tabs
openedx/course-discovery pull request #437
Opened 2016-11-11 18:09 UTC by awais786

Implement published course run tab.

I have closed the previous PR https://github.com/edx/course-discovery/pull/431.

2016-11-11 18:18 UTC, awais786 commented
<img width="992" alt="screen shot 2016-11-11 at 11 16 45 pm" src="https://cloud.githubusercontent.com/assets/445320/20225403/f18e7de4-a864-11e6-8334-812b079be87a.png">

2016-11-11 18:18 UTC, awais786 commented
@ahsan-ul-haq @tasawernawaz @waheedahmed Please review this PR.

2016-11-14 10:46 UTC, ahsan-ul-haq requested changes

2016-11-14 10:46 UTC, ahsan-ul-haq commented on course_discovery/templates/publisher/dashboard/published.html
> +    <p>{% trans "Looks like you haven't publish a course yet" %}</p>
change it to `Looks like you haven't published any course yet`

2016-11-14 10:50 UTC, awais786 commented
@edx/ecommerce Please review this PR.

2016-11-14 10:57 UTC, ahsan-ul-haq approved these changes

2016-11-14 18:38 UTC, bderusha approved these changes

2016-11-14 18:38 UTC, bderusha commented on course_discovery/templates/publisher/dashboard/published.html
> +            The list below contains all course runs previews for course team approved. Once approved, {{ platform_name }} Marketing team will publish the course and you will be notified via email whe
`The list below contains all course runs published in the past {days} days`

2016-11-15 09:26 UTC, merged