Awais786/ecom 6221 preview course runs tabs
openedx/course-discovery pull request #438
Opened 2016-11-14 14:39 UTC by awais786

WIP:

2016-11-14 14:48 UTC, awais786 commented
<img width="997" alt="screen shot 2016-11-14 at 7 47 59 pm" src="https://cloud.githubusercontent.com/assets/445320/20269017/494c7320-aaa3-11e6-95b6-ec21a7c2ec92.png">

2016-11-14 14:49 UTC, awais786 commented
@ahsan-ul-haq  @tasawernawaz Please review this PR.

2016-11-15 11:41 UTC, ahsan-ul-haq requested changes

2016-11-15 11:41 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/models.py
> +    preview_url = models.URLField(null=True, blank=True, help_text=_("Drupal preview page url."))
Change it to `drupal_preview_url`

2016-11-15 11:41 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/tests/test_views.py
> +    def assert_dashboard_response(self, unpublished_count, published_count, studio_requests, preview_count):
please add doc string

2016-11-15 11:56 UTC, ahsan-ul-haq approved these changes

2016-11-16 04:19 UTC, awais786 commented
@edx/ecommerce Please review this PR.

2016-11-16 15:25 UTC, awais786 commented
@edx/ecommerce Please review this PR.

2016-11-16 16:19 UTC, schenedx commented on course_discovery/templates/publisher/dashboard/studio_requests.html
> +                {% for course_run in studio_course_runs %}
Why do we need this change here? I don't see any reference in the rest of this PR about this change

2016-11-16 16:19 UTC, schenedx approved these changes
Just a question. LGTM 👍

2016-11-16 16:31 UTC, awais786 commented on course_discovery/templates/publisher/dashboard/studio_requests.html
> +                {% for course_run in studio_course_runs %}
Revert the variable name.

2016-11-16 17:22 UTC, clintonb commented on course_discovery/apps/publisher/models.py
> +    drupal_preview_url = models.URLField(null=True, blank=True, help_text=_("Drupal preview page url."))
`preview_url`. We won't use Drupal forever. Also, the help text is not useful and should be removed.

2016-11-16 17:22 UTC, clintonb commented on course_discovery/apps/publisher/tests/factories.py
> +    drupal_preview_url = FuzzyText(prefix='https://example.com/')
`preview_url`

2016-11-16 17:22 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +    def assert_dashboard_response(self, unpublished_count, published_count, studio_requests, preview_count):
The method is a bit unreasonable. A good assertion should do one thing well. You're doing 5. This should be split into five separate methods. One simply retrieves the response and checks the status code. The others take the response and validate the various counts and UI text.

2016-11-16 17:22 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        # change the state to need final approval
This should be a separate test method.

2016-11-16 17:22 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        # state remains to need final approval but remove the preview url
This should be a separate test method.

2016-11-16 17:22 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        context['preview_course_runs'] = [CourseRunWrapper(course_run) for course_run in preview_course_runs]
What is `CourseRunWrapper`, and why is it necessary?

2016-11-16 17:22 UTC, clintonb commented on course_discovery/templates/publisher/dashboard.html
> +            {% include "publisher/dashboard/preview_ready.html" %}
The names of partial templates generally start with an underscore (e.g. `publisher/dashboard/_preview_ready.html`) to avoid confusion.

2016-11-16 17:22 UTC, clintonb commented on course_discovery/templates/publisher/dashboard/preview_ready.html
> +        <p class="empty-courserun-text">{% trans "There are no course-runs in preview for ready state." %}</p>
There are no course runs marked for preview.

2016-11-16 17:22 UTC, clintonb commented on course_discovery/templates/publisher/dashboard/preview_ready.html
> +    <p>{% trans "The list below contains all course runs preview for course team approved. Once approved, edX Marketing will publish the course and you will be notified via email when the course is l
Avoid edX branding in translated strings.

The list below contains all course runs awaiting course team approval. Once approved, the marketing team will push the course run. you will be notified via email when the course runs are live on the production site.

2016-11-16 17:22 UTC, clintonb commented on course_discovery/templates/publisher/dashboard/preview_ready.html
> +                        {% trans "Institution" %}
Why institution rather than organization?

2016-11-16 17:22 UTC, clintonb commented on course_discovery/templates/publisher/dashboard/preview_ready.html
> +                        <td>{% if course_run.course.group_institution %}{{ course_run.course.group_institution }}{% endif %}</td>
When/why would a course not have an institution/organization associated?

2016-11-16 17:22 UTC, clintonb commented on course_discovery/static/js/publisher/views/dashboard.js
> +     $('.data-table-preview').addClass('nowrap').DataTable({
Why the call to `addClass()`? Just set the class in the HTML template. The same for the table above.

2016-11-16 17:22 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        ).select_related('state').all().order_by('-state__modified')
The call to `.all()` doesn't do anything, and should be removed.

2016-11-17 09:17 UTC, awais786 commented on course_discovery/templates/publisher/dashboard/preview_ready.html
> +                        <td>{% if course_run.course.group_institution %}{{ course_run.course.group_institution }}{% endif %}</td>
Each course should have a institution/organization. Removed the if condition.

2016-11-17 10:45 UTC, awais786 commented on course_discovery/apps/publisher/views.py
> +        context['preview_course_runs'] = [CourseRunWrapper(course_run) for course_run in preview_course_runs]
The main purpose is to access course-run parent object attributes via wrapper. Instead of accessing directly into templates.

2016-11-17 11:21 UTC, awais786 commented on course_discovery/templates/publisher/dashboard/preview_ready.html
> +                        {% trans "Institution" %}
I have asked this from Deen and Roderick.I will update you with their response.

2016-11-17 12:55 UTC, awais786 commented
@clintonb You can preview this PR again.

2016-11-17 13:23 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        context['preview_course_runs'] = [CourseRunWrapper(course_run) for course_run in preview_course_runs]
Unless the course run-to-course relationship, and the model fields, are changing with a high amount of frequency, this seems like an unnecessary proxy. It's almost as if you're prematurely generalizing your template.

2016-11-17 18:21 UTC, awais786 commented
@clintonb Please review this PR. I have made all required changes.

2016-11-18 12:52 UTC, awais786 commented
@clintonb should i merge this PR now ?

2016-11-18 13:19 UTC, clintonb approved these changes

2016-11-18 13:41 UTC, merged