Add kwargs to parallel loader
openedx/course-discovery pull request #440
Opened 2016-11-15 17:30 UTC by MatthewPiatetsky

@edx/ecommerce 
Thanks @schenedx for finding this issue.  
Didn't notice this locally before because I didn't have the waffle switch on.

2016-11-15 17:35 UTC, schenedx approved these changes
👍

2016-11-15 17:49 UTC, rlucioni approved these changes

2016-11-15 19:53 UTC, clintonb requested changes
This needs tests. Clearly, the lack of tests allowed this bug to go unnoticed.

2016-11-15 21:08 UTC, MatthewPiatetsky commented
@clintonb looks like there actually is a test with the flag on and in fact the job does not run properly when the flag is on and we are not asserting that it worked successfully  
Looking into it

2016-11-16 18:28 UTC, schenedx commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +        partner = self.partner
Why do you need this line? Just to save `self.` in the statements below?

2016-11-16 18:31 UTC, schenedx commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +            with mock.patch('concurrent.futures.ProcessPoolExecutor.submit') as mock_executor:
Instead of mock `concurrent.futures.ProcessPoolExecutor.submit`, don't you want to mock the `execute_parallel_loader` function instead? And check the call arguments to ensure `**loader_kwargs` is passed in?

2016-11-16 18:33 UTC, schenedx requested changes
I think the test is checking the wrong function for parallel execution.

2016-11-16 18:34 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +        partner = self.partner
yeah

2016-11-16 18:36 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +            with mock.patch('concurrent.futures.ProcessPoolExecutor.submit') as mock_executor:
hmm..well if I don't mock the original call then I might as well mock execute_loader, right?

2016-11-16 18:39 UTC, schenedx commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +            with mock.patch('concurrent.futures.ProcessPoolExecutor.submit') as mock_executor:
Yeah, mock `execute_loader` is fine. Make sure you check the arguments passed in

2016-11-16 18:40 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +            with mock.patch('concurrent.futures.ProcessPoolExecutor.submit') as mock_executor:
actually I just tried both and seems both do not work with this approach (for the same reasons that other approaches were not working, where the mocks don't work on the subprocesses) thoughts?

2016-11-16 18:48 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +    def test_refresh_course_metadata(self):
If you're going to break things up like this, make it clear in the name of this test that the pipeline is being executed serially.

2016-11-16 18:48 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +            with mock.patch('concurrent.futures.ProcessPoolExecutor.submit') as mock_executor:
@MatthewPiatetsky what you have here is what I was suggesting earlier. I think this is the closest we can get without figuring out how to set up mocks in separate processes.

2016-11-16 18:48 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +                mock_executor.assert_has_calls(expected_calls, any_order=True)
In this serial case, the order of the calls is deterministic. The calls should be executed in the order defined by the pipeline.

2016-11-16 18:48 UTC, rlucioni commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +                expected_calls = [mock.call(execute_parallel_loader, loader_class, self.partner, api_url,
I would spread this across several lines to make it easier to read.

2016-11-16 18:49 UTC, schenedx commented on course_discovery/apps/course_metadata/management/commands/tests/test_refresh_course_metadata.py
> +            with mock.patch('concurrent.futures.ProcessPoolExecutor.submit') as mock_executor:
@rlucioni @MatthewPiatetsky I think I get it now. This works for now.

2016-11-16 18:50 UTC, schenedx approved these changes
👍

2016-11-16 18:54 UTC, clintonb approved these changes
Squash your commits, and add the ticket number to the commit description.

2016-11-16 18:57 UTC, MatthewPiatetsky commented
@clintonb added the ticket number, but I had intentionally made two commits, because it seemed like the tests were not directly related to the other change. However, I assume we generally don't make separate commits for tests, so will squash

2016-11-16 19:02 UTC, clintonb commented
@MatthewPiatetsky the tests are definitely related. We prefer to fix bugs once. The key to ensuring that is a good test suite. A bug fix is incomplete without tests.

2016-11-16 19:20 UTC, merged