Work In Progress, ignore for now
openedx/course-discovery pull request #447
Opened 2016-11-21 15:26 UTC by MatthewPiatetsky

ECOM-4738 Add Typeahead endpoint to course discovery

2016-11-21 21:57 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +        authoring_organizations = [json.loads(org) for org in result.authoring_organization_bodies]
The org key is stored as its own field in the index for course_runs, but not programs

2016-11-21 21:58 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views.py
> +    def list(self, request, *args, **kwargs):
There may be a cleaner way to do this using DRF/Haystack built ins that I am not familiar with

2016-11-22 18:27 UTC, rlucioni requested changes

2016-11-22 18:27 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +        course_runs = [course_run for course_run in results if course_run.get('content_type') == 'courserun'][:3]
What up with the array slicing here and below? Is there a more readable way to do this?

2016-11-22 18:27 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +            item.pop('content_type', None)
You're using three loops here to do what you could do with one. You should only have to iterate across results once, decide if something is a course run or a program, and pop the content type.

2016-11-22 18:27 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        querystring = querystring or {}
This keyword argument doesn't appear to be used. Remove it?

2016-11-22 18:27 UTC, rlucioni commented on course_discovery/apps/api/tests/test_serializers.py
> +class TypeaheadProgramSearchSerializerTests(TestCase):
This test class is very similar to the one above. Have you considered implementing a single shared `TypeaheadSerializerTestBase` which you can then subclass for testing course run and program serialization?

2016-11-22 18:27 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
> +    def get_alias(self, result):
I would either leave a comment about what an "alias" is, or I would choose a better name for it to begin with.

2016-11-22 18:31 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +    def get_alias(self, result):
This was the preexisting name in the current typeahead, but I think renaming would be a good idea. Any ideas?

2016-11-22 18:38 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> +class TypeaheadProgramSearchSerializerTests(TestCase):
Could you clarify how this would work, given that all the methods are slightly different I'm not sure what would be in the base class

2016-11-22 18:50 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +    def get_alias(self, result):
Nvm Jasper said it is "literally an alias" so I added a comment

2016-11-22 19:22 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
> +    def get_alias(self, result):
So is "alias" a standard term for that? I was thinking something along the lines of "caption" or "subtitle" would be more descriptive.

2016-11-22 19:22 UTC, rlucioni commented on course_discovery/apps/api/tests/test_serializers.py
> +class TypeaheadProgramSearchSerializerTests(TestCase):
I guess you'd just end up with a single method in the base class which serialized some object and compared it to an expected structure. Maybe not the most useful thing, in retrospect. Feel free to ignore.

2016-11-22 19:22 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +        response.data = {'course_runs': course_runs[:3], 'programs': programs[:3]}
Please include a comment explaining that the slicing is meant to limit the size of each category to 3 results.

Also, thoughts about exiting the loop above when the `course_runs` and `programs` contain 3 items? I can see that loop doing a bunch of wasted work.

2016-11-22 19:27 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views.py
> +        response.data = {'course_runs': course_runs[:3], 'programs': programs[:3]}
hmm..adding the if statement would also be some overhead, but I suppose it limits the worst case (in the average case it probably depends on the query, some would have few results and some would have many), makes sense to me

2016-11-22 19:30 UTC, mikedikan commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        data.pop('content_type')
Can you add a comment about why you remove content_type from the response?

2016-11-22 19:30 UTC, mikedikan commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        data.pop('content_type')
see above

2016-11-22 19:43 UTC, schenedx commented on course_discovery/apps/api/serializers.py
> +    def get_alias(self, result):
@MatthewPiatetsky I think this is confusing to me as well. Why do you think this `alias` name here makes more sense? Even with the comment, I am confused.

2016-11-22 19:43 UTC, schenedx approved these changes
Just a question on `Alias` field. Rest LGTM 👍

2016-11-22 20:09 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        data.pop('content_type')
See the sample response in my description, we know the type based on which list each item is a part of, so we don't need the content_type

2016-11-22 20:56 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views.py
> +        response.data = {'course_runs': course_runs[:3], 'programs': programs[:3]}
let me know if this is what you were thinking

2016-11-22 22:00 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +            item_type = item.pop('content_type', None)
You appear to be doing this in the serializer. Is it necessary here as well?

2016-11-22 22:00 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +            elif len(programs) == 3 and len(course_runs) == 3:
Let's try to avoid hardcoding magic numbers like this. The result count (3, in this case) should be a constant defined at the top of the file, or in settings.

2016-11-22 22:02 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +            item_type = item.pop('content_type', None)
I'm sorry, I was looking at test code. However, could you do this in the serializer by just excluding the `content_type` field?

2016-11-22 22:02 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +                break
I also don't see a test case covering this branch.

2016-11-22 22:03 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views.py
> +            item_type = item.pop('content_type', None)
I was including the content_type field there so I would know if something is a courserun or program. Otherwise I wouldn't know

2016-11-22 22:05 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +            item_type = item.pop('content_type', None)
Understood, ignore me.

2016-11-22 22:10 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views.py
> +            elif len(programs) == 3 and len(course_runs) == 3:
fixed

2016-11-22 22:10 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views.py
> +                break
good point, didn't think of that when I addressed your other comment. added.

2016-11-22 22:36 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +        # Retrieve first 3 results for course runs and programs
This comment is going to get stale if the result count value changes. Your code is now clear enough that I don't think this comment is necessary, so I'd remove it.

2016-11-22 22:37 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views.py
> +        # Retrieve first 3 results for course runs and programs
ok removed

2016-11-22 22:38 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        course_runs = CourseRunFactory.create_batch(3)
Don't assume 3, import the constant you defined in the views.

2016-11-22 22:39 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def test_typeahead_multiple_results(self):
Since this test case only creates a `RESULT_COUNT` number of course and programs, you're not going to hit the break you've added. You could do `RESULT_COUNT + 1` to exercise all branches.

2016-11-22 22:40 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        course_runs = CourseRunFactory.create_batch(3)
good idea, changed

2016-11-22 22:41 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def test_typeahead_multiple_results(self):
actually good point, this makes me realize that the condition is currently incorrect, it should be >= RESULT_COUNT-1

2016-11-22 22:41 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +from course_discovery.apps.api.v1.views import RESULT_COUNT
Nitpick: keep your imports in alphabetical order, please.

2016-11-22 22:46 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        response_data = json.loads(response.content.decode('utf-8'))
Can you use https://docs.djangoproject.com/en/1.9/topics/testing/tools/#django.test.Response.json?

2016-11-22 22:55 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def test_typeahead_multiple_results(self):
changed

2016-11-22 22:55 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +from course_discovery.apps.api.v1.views import RESULT_COUNT
fixed

2016-11-22 22:55 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        response_data = json.loads(response.content.decode('utf-8'))
changed

2016-11-23 02:40 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        self.assertEqual(len(response_data['course_runs']), 3)
Again, don't assume 3. You want to assert that the result count equals `RESULT_COUNT`.

2016-11-23 02:40 UTC, rlucioni commented on course_discovery/apps/api/v1/views.py
> +            if item_type == 'courserun' and len(course_runs) < RESULT_COUNT:
Minor, but it's a little cleaner to avoid recomputing these lengths. Just do each one once:
```py
course_run_count = len(course_run)
program_count = len(programs)

if item_type == 'courserun' and course_run_count < RESULT_COUNT:
    ...
```

2016-11-23 02:40 UTC, rlucioni commented on course_discovery/apps/api/tests/test_serializers.py
> +        program = ProgramFactory(authoring_organizations=[authoring_organization])
What about the case of a program with two authoring organizations? Your code handles that gracefully, but I don't see it covered here.

2016-11-23 02:41 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        programs = ProgramFactory.create_batch(RESULT_COUNT + 1)
These variables (`course_runs`, `programs`) are unused.

2016-11-23 03:52 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        self.assertEqual(len(response_data['course_runs']), 3)
fixed

2016-11-23 03:53 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views.py
> +            if item_type == 'courserun' and len(course_runs) < RESULT_COUNT:
not sure if this actually creates savings, but changed

2016-11-23 03:53 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> +        program = ProgramFactory(authoring_organizations=[authoring_organization])
added test in serializer and view tests

2016-11-23 03:53 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        programs = ProgramFactory.create_batch(RESULT_COUNT + 1)
removed

2016-11-23 17:44 UTC, rlucioni approved these changes

2016-11-28 15:40 UTC, merged