WIP: Implemented change course role assignment.
openedx/course-discovery pull request #455
Opened 2016-11-28 12:41 UTC by waheedahmed

[ECOM-6207](https://openedx.atlassian.net/browse/ECOM-6207)

2016-11-28 19:29 UTC, bderusha requested changes
A few minor things, but overall this looks good

2016-11-28 19:29 UTC, bderusha commented on course_discovery/apps/publisher/urls.py
> +        r'^courses/(?P<course_id>\d+)/change/role_assignment/$',
`r'^courses/(?P<course_id>\d+)/role_assignments/$',`

2016-11-28 19:29 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +            if not mixins.check_view_permission(request.user, course):
Should this be the first thing we check before doing any work?

2016-11-29 12:13 UTC, waheedahmed commented
Base branch merged into master, closing this PR and created against master https://github.com/edx/course-discovery/pull/458.

2016-11-29 12:13 UTC, closed without merging