Implemented change course role assignment.
openedx/course-discovery pull request #458
Opened 2016-11-29 12:13 UTC by waheedahmed

[ECOM-6207](https://openedx.atlassian.net/browse/ECOM-6207)

**Screenshots:**
<img width="393" alt="screen shot 2016-11-28 at 5 42 29 pm" src="https://cloud.githubusercontent.com/assets/2851134/20668731/2e5dd8f2-b592-11e6-9a40-7c52f17a99a3.png">
<img width="386" alt="screen shot 2016-11-28 at 5 44 43 pm" src="https://cloud.githubusercontent.com/assets/2851134/20668782/654c5b72-b592-11e6-9260-071f9d68dc08.png">
<img width="380" alt="screen shot 2016-11-28 at 5 42 50 pm" src="https://cloud.githubusercontent.com/assets/2851134/20668730/2e5bf8de-b592-11e6-8257-e36810942892.png">
<img width="375" alt="screen shot 2016-11-28 at 5 43 02 pm" src="https://cloud.githubusercontent.com/assets/2851134/20668729/2e5a48a4-b592-11e6-90b9-3594e984f3c8.png">

2016-11-29 12:17 UTC, waheedahmed commented
Base branch was merged into master, closed this PR https://github.com/edx/course-discovery/issues/455 and created this against master.

@bderusha Addressed your comments and added tests, please take another look.

@awais786 , @tasawernawaz , @ahsan-ul-haq Please review.

2016-11-29 12:22 UTC, waheedahmed commented
I'll update the translation later.

2016-11-29 14:40 UTC, clintonb commented on course_discovery/apps/publisher/models.py
> +            ('course', 'user', 'role'),
Should a user be able to have more than one role for a course run?

2016-11-29 14:40 UTC, clintonb commented on course_discovery/apps/publisher/tests/factories.py
> +    UserAttributes)
Nit: add a newline

2016-11-29 14:40 UTC, clintonb commented on course_discovery/apps/publisher/models.py
> +        (COURSE_TEAM, _('Course Team')),
Use `DjangoChoices`.  See `/course_discovery/apps/course_metadata/choices.py` and https://github.com/bigjason/django-choices.

2016-11-29 14:40 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +class CourseRoleAssignmentView(mixins.LoginRequiredMixin, View):
This looks an awful lot like an API endpoint. Why isn't it one?

2016-11-29 14:40 UTC, clintonb commented on course_discovery/static/sass/publisher/publisher.scss
> +}
Add a new line.

2016-11-29 14:40 UTC, clintonb commented on course_discovery/templates/comments/comments_list.html
>  {% load i18n %}
Partials should be prefixed with an underscore (e.g. `_comments_list.html`).

2016-11-29 14:40 UTC, clintonb commented on course_discovery/templates/comments/add_auth_comments.html
>  {% load staticfiles %}
Partials should be prefixed with an underscore (e.g. `_add_auth_comments.html`).

2016-11-29 14:40 UTC, clintonb commented on course_discovery/templates/publisher/course_run_detail.html
> +                <button data-tab="#tab-2">{% trans "STUDIO" %}</button>
Add translators comments explaining what these are. CAT, for example, is not the animal. It's an acronym for Course Administration Tool.

2016-11-30 09:39 UTC, waheedahmed commented on course_discovery/apps/publisher/models.py
> +            ('course', 'user', 'role'),
@clintonb No, one user can have only one role for a course.

2016-11-30 13:49 UTC, clintonb commented on course_discovery/apps/publisher/models.py
> +            ('course', 'user', 'role'),
In that case, role should be removed from your compound key.

2016-11-30 13:52 UTC, waheedahmed commented on course_discovery/apps/publisher/models.py
> +            ('course', 'user', 'role'),
You are right, thanks.

2016-11-30 14:52 UTC, waheedahmed commented on course_discovery/apps/publisher/models.py
> +            ('course', 'user', 'role'),
@clintonb We just discussed it with Deen and he said a user can have more than one role for a course, so I'm changing it back to ```('course', 'user', 'role')```.

2016-12-02 12:49 UTC, waheedahmed commented
@clintonb Please review this PR.

2016-12-02 22:43 UTC, clintonb requested changes
The role change work seems to be interspersed with the movement of comment templates. Please separate this into separate commits/PRs to make this simpler to review.

2016-12-02 22:43 UTC, clintonb commented on course_discovery/apps/publisher/admin.py
> +admin.site.register(CourseUserRole)
Use a raw ID field for the user field. See my comment on https://github.com/edx/course-discovery/pull/470.

2016-12-02 22:43 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +class CourseRoleAssignmentView(mixins.LoginRequiredMixin, UpdateAPIView):
These API views should be separated from other views either as a separate module (e.g. `views/api.py`) or Django app.

`LoginRequiredMixin` should not be used for an API view; that's what the `authentication_classes` variable is for. See http://www.django-rest-framework.org/api-guide/authentication/.

2016-12-02 22:43 UTC, clintonb commented on course_discovery/apps/publisher/serializers.py
> +        fields = ('user',)
Expose all the fields—user, course, role. Set those that need to be read-only to be read-only.

2016-12-02 22:43 UTC, clintonb commented on course_discovery/apps/publisher/permissions.py
> +class PublisherPermission(BasePermission):
This name is confusing since it doesn't accurately describe the permission. `CanViewAssociatedCourse` seems like a better name. Update the docstring as well.

2016-12-02 22:43 UTC, clintonb commented on course_discovery/apps/publisher/permissions.py
> +def check_role_assignment_permission(user):
This is not secure. This permission returns `True` for any user with any course or organization role. That would mean this permission *must always* be paired with another more restrictive class to be effective. Given that, this should either be a mixin or merged with the other permission class.

2016-12-02 22:43 UTC, clintonb commented on course_discovery/static/js/publisher/views/course_detail.js
> +                console.log("There was an error in changing role.");
Logging to the console does nothing for the user. Display a message to the user.

2016-12-02 22:43 UTC, clintonb commented on course_discovery/static/js/publisher/views/course_detail.js
> +            apiEndpoint = $(this).data("apiEndpoint"),
`data('api-endpoint')`

2016-12-02 23:11 UTC, clintonb requested changes
I'm going to need to see a lot more comments before I can approve this. Say this code sits idle for a couple months, and we find a bug. How long will it take to remember what the code is supposed to be doing?

As is, I'm not entirely sure what you're trying to do. And that's after reading the ticket and related comments. Your code needs to be commented to make it easier for future developers—including future you—to understand it without having to mentally interpret every single line.

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        course_run = CourseRunWrapper(context['object'])
This is a wall of text. Space this out and (more importantly) add comments explaining what what this code is supposed to be doing.

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +    def get_roles_data(self, role_widgets, user_roles, course_roles):
Add a docstring explaining the purpose of this method. Also, consider changing the name to be less generic. The method is called `get_roles_data` but it's not returning anything.

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +
None of the newlines here are necessary.

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        """ Verify that user can change course role assignment. """
This docstring contradicts a comment below: verify that coordinator can't change reviewer role for this course. It seems like you need two tests here. Your docstrings and comments, when discussing permissions, should be explicit about *which* users can, or cannot, perform an action.

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/urls.py
> +        name='publisher_change_role_assignment'
`change_role_assignment`

Your URL patterns are already under the `publisher` namespace.

Given that this is actually an API view, I would namespace the API-endpoints: `publisher:api:course_role_assignments`

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.client.logout()
This, and the lines below, should be refactored into an assertion method. This method can be used here and in the test above.

```python
def assert_user_cannot_change_course_role(self, user):
    """ Asserts the given user CANNOT change CourseUserRole objects. """
    self.client.logout()
    self.client.login(username=user.username, password=USER_PASSWORD)

    response = self.client.patch(
        self.change_assignment_url,
        data=json.dumps({'user': user.id}),
        content_type=JSON_CONTENT_TYPE
    )
    self.assertEqual(response.status_code, 403)

```

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.user.groups.add(reviewer_group)
Name your users appropriately: `self.marketing_user`.

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.user2 = UserFactory()
`self.other_marketing_user`

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        # Create a coordinator group and assign it to user3.
Move this comment up, above the user creation.

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.user3 = UserFactory()
`self.partner_coordinator`

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.user_default_role = factories.OrganizationUserRoleFactory(
This does not need to be an instance variable.

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +    def assert_role_assignment(self, response, user, expected_json):
Add a docstring explaining the purpose of this method.

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +    """ Tests for `CourseRoleAssignmentView` """
This docstring is not necessary.

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +            data=json.dumps({'user': self.user2.id}),
`self.user2.id` can be any integer. You should not be referencing `self.user`.

2016-12-02 23:11 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +    def assert_role_assignment(self, response, user, expected_json):
Actually, this assertion method doesn't need to exist. It's only used in one location.

2016-12-06 11:55 UTC, waheedahmed commented
@clintonb There are some requirement changes for this ticket, we added those on the ticket and also in the description of this PR. Kindly take another look, also addressed all your concerns.

2016-12-06 19:13 UTC, waheedahmed commented
@clintonb Please review this PR.

2016-12-08 03:12 UTC, clintonb requested changes
This functionality needs to be tested. This will probably be easiest accomplished with [`LiveServerTestCase`](https://docs.djangoproject.com/en/1.10/topics/testing/tools/#liveservertestcase).

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        for x in range(3):      # pylint: disable=unused-variable
` for __ in range(3):`

Pylint ignores `__`.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        organization = OrganizationFactory(name='testX')
Get rid of this name given that it is never referenced in any of your tests.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        organization = OrganizationFactory(name='testX')
Get rid of this name given that it is never referenced in any of your tests.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        # assign course view permission to internal user group
This comment is not necessary.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        for user, role in zip(self.other_internal_users, PublisherUserRole.choices):
Add a comment explaining what you're doing here, and why it's necessary.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        """ Test that non internal user can't change role assignment. """
Verify non-internal users cannot change role assignments.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/api/urls.py
> +from course_discovery.apps.publisher.api import views as api_views
Just `views`. I doubt you'll have any other views in this file.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/api/urls.py
> +    url(
One line.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        """ Verify that internal user can change course role assignment for
Does it matter that they can change all three? If not, we shouldn't waste time testing this three times.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        for user_course_role in self.course.course_user_roles.all():
If you must test all three of these, use `ddt`. In general, I'm not a fan of for-loops in tests. Without proper logging, it is difficult to know for which element in the list the test failed.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/api/views.py
> +"""
This docstring is not necessary. We can infer this information from the file path.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/api/views.py
> +    """ Course Role Assignment View. """
This docstring is not necessary.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/permissions.py
> +from rest_framework.permissions import BasePermission
This file, and its tests, belongs in the `api` sub-package.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/serializers.py
> +class RoleAssignmentSerializer(serializers.ModelSerializer):
This class, and its tests, belongs in the `api` sub-package. Please file a ticket to move the other API views and serializers.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/serializers.py
> +class RoleAssignmentSerializer(serializers.ModelSerializer):
`CourseUserRoleSerializer`

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_utils.py
> +        self.assertFalse(self.user.groups.filter(name=INTERNAL_USER_GROUP_NAME).exists())
I'm not sure there is much value in testing the condition where the group does not exist. Instead, test the case where group exists, but the user is not in the group.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/utils.py
> +def get_all_internal_user():
`get_internal_users`

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/utils.py
> +    """ Get all internal user's. """
```python
"""
Returns a list of all internal users

Returns:
  list
"""
```

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/utils.py
> +    return User.objects.filter(groups__name=INTERNAL_USER_GROUP_NAME)
Cast this to a list given that it does not need to be a `QuerySet`. Remember to update your tests.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        # initialize `CourseRunWrapper` on `CourseRun` object
This comment is not necessary.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        # assign it back to object in context.
This comment is not necessary.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        course_run = CourseRunWrapper(context['object'])
You can clean this up by overriding `get_object()`. Also, consider setting [`context_object_name`](https://docs.djangoproject.com/en/1.10/ref/class-based-views/mixins-multiple-object/#django.views.generic.list.MultipleObjectMixin.context_object_name) to provide a more informative name.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +            course_roles = course_run.course.course_user_roles.all().exclude(role=PublisherUserRole.CourseTeam)
I don't think you need `.all()` here.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +    def get_role_widgets_data(self, course_roles):
Add a docstring explaining what's going on here.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/templates/publisher/course_run_detail.html
> +                {% comment %}Translators: It's an edX tool to build courses{% endcomment %}
Studio is an edX tool for course creation.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/templates/publisher/course_run_detail.html
> +                {% comment %}Translators: It's an acronym for Course Administration Tool{% endcomment %}
CAT is an acronym for Course Administration Tool.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/templates/publisher/course_run_detail.html
> +                <button data-tab="#tab-4">{% trans "DRUPAL" %}</button>
We should call this "Marketing Site".

2016-12-08 03:12 UTC, clintonb commented on course_discovery/templates/publisher/course_run_detail.html
> +                <button data-tab="#tab-5">{% trans "Salesforce" %}</button>
Salesforce is a brand name, and should not be translated.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/static/js/publisher/views/course_detail.js
> +        var headers = {
Move `headers` outside this function. There is no need to read the cookie multiple times.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/static/js/publisher/views/course_detail.js
> +    $(".btn-change-assignment").click(function(e){
At some point we will write this down, but use single quotes throughout JavaScript files.

2016-12-08 03:12 UTC, clintonb commented on course_discovery/templates/publisher/course_run_detail/_approval_widget.html
> +                <div id="user-role-container-{{ role_widget.user_course_role.role }}">
Use camelCase for ID attributes.

2016-12-08 09:22 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        course_run = CourseRunWrapper(context['object'])
Using ```get_object()``` here but setting ```context_object_name``` will be a big change, we will do that in cleanup.

2016-12-08 09:25 UTC, waheedahmed commented on course_discovery/templates/publisher/course_run_detail.html
> +                <button data-tab="#tab-4">{% trans "DRUPAL" %}</button>
This was provided in design prototype and on ticket.

2016-12-08 10:00 UTC, waheedahmed commented on course_discovery/apps/publisher/serializers.py
> +class RoleAssignmentSerializer(serializers.ModelSerializer):
Created the requested ticket [ECOM-6574](https://openedx.atlassian.net/browse/ECOM-6574).

2016-12-08 10:06 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +    def get_role_widgets_data(self, course_roles):
Added.

2016-12-08 10:20 UTC, waheedahmed commented
@clintonb Addressed all your comments, please take another look.

2016-12-13 07:35 UTC, waheedahmed commented
@clintonb Kindly take another look on this PR.

2016-12-13 21:29 UTC, bderusha commented on course_discovery/templates/comments/add_auth_comments.html
>  {% load staticfiles %}
@waheedahmed this still needs to be addressed

2016-12-13 21:29 UTC, bderusha commented on course_discovery/templates/comments/comments_list.html
>  {% load i18n %}
@waheedahmed this still needs to be addressed

2016-12-13 22:00 UTC, clintonb approved these changes

2016-12-13 22:00 UTC, clintonb commented on course_discovery/apps/publisher/api/serializers.py
> +"""Publisher Api Serializers"""
Nit: API

2016-12-13 22:00 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_serializers.py
> +        serializer = self.serializer_class(self.course_user_role)
`serializer = self.serializer_class(self.course_user_role, context={'context': self.request})`

2016-12-13 22:00 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_serializers.py
> +"""Tests Publisher Api Serializers."""
Nit: API

2016-12-13 22:00 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        self.assertJSONEqual(str(response.content, encoding='utf8'), expected_json)
`self.assertDictEqual(response.data, expected)`

2016-12-13 22:00 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_serializers.py
> -        expected = serializer.validate(serializer.data)
This change is not necessary. The older version is clearer.

2016-12-13 22:00 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        for user in [self.user, pc_user, marketing_user, publisher_user]:
`internal_user_group.user_set.add(*(self.user, pc_user, marketing_user, publisher_user))`

2016-12-14 07:27 UTC, awais786 approved these changes

2016-12-14 07:50 UTC, waheedahmed commented on course_discovery/templates/comments/comments_list.html
>  {% load i18n %}
@bderusha We decided to do it in its own PR.

2016-12-14 07:58 UTC, merged