WIP Ignore for now
openedx/course-discovery pull request #459
Opened 2016-11-29 16:42 UTC by MatthewPiatetsky

2016-11-29 20:19 UTC, bderusha reviewed
Code looks good, but I have some performance concerns about this type of double wildcard search.  Have we/can we test this?

2016-11-29 20:27 UTC, MatthewPiatetsky commented
@bderusha this endpoint isn't yet used by anything, so yeah I was going to do load testing on the load test environment, but yeah I was concerned about performance as well. I'm not sure if there is a more efficient approach to implementing this.

2016-11-29 20:37 UTC, bderusha commented
I wonder if there is a way to create an index of typeahead searches, so that rather than scanning everything front and back for a match we are doing exact match on partial words.

In theory we want a query like "one" to match `Done and done`, `The one big thing`, `Onerous Opinions`, `One + one`

In practice however we may be safe in assuming that users searching for "one" do not NEED `Done and done` as a result.

Therefore If we created an index of partial words e.g. "One", "Oner", "Onero", "Onerou", "Onerous"
we could match documents based on that without a performance penalty.

That said. Let's load test this.  We only have a few thousand documents.  This may be a WAY premature optimization.

2016-11-29 21:20 UTC, clintonb requested changes

2016-11-29 21:20 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        course_run = CourseRunFactory(title="Python")
Use a constant.

2016-11-29 21:20 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +            CourseRunFactory(title="Test{}".format(i))
Use a constant.

2016-11-29 21:20 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        course_run = CourseRunFactory(title="Design", authoring_organizations=authoring_organizations)
Use a constant.

2016-11-29 21:20 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        course_run = CourseRunFactory(title="Learn Data Science")
Use a constant.

2016-11-29 21:20 UTC, clintonb commented on course_discovery/apps/api/v1/views.py
> +        query = 'title:*{}*'.format(query.lower())
Why only title?

2016-11-29 21:20 UTC, clintonb commented on course_discovery/apps/api/v1/views.py
>      index_models = (CourseRun, Program,)
This is not used.

2016-11-29 21:20 UTC, clintonb commented on course_discovery/apps/api/v1/views.py
>          response = super(TypeaheadSearchViewSet, self).list(request, *args, **kwargs)
This is quite odd. You're doing too much work here. Just bypass the base class altogether:

```python
# serializers.py
class TypeaheadItemSerializer(serializers.Serializer):
  class Meta:
    # TODO Add other fields that will actually be displayed
    fields = ('title',)

class TypeaheadSearchSerializer(serializers.Serializer):
  course_runs = TypeaheadItemSerializer(many=True)
  programs = TypeaheadItemSerializer(many=True)

# views.py
class TypeaheadSearchView(APIView):
  def get_results(self, query):
    # TODO Do the search
    return course_runs, programs

  def get(self, request, format=None):
    course_runs, programs = self.get_results(request.GET['q'])
    serializer = TypeaheadSearchSerializer(data={'course_runs': course_runs, 'programs': programs)
    return Response(serializer.data, status=status.HTTP_200_OK)
```

2016-11-29 23:23 UTC, MatthewPiatetsky commented
@bderusha 
I will probably need to add to the load tests since I don't think they're currently testing this, but I believe for peak load should we can say 120 rpm (average is around 50)
Local response time for the search/typeahead endpoint seems to be around 150-250 ms and search/all is around 250-350 ms

2016-11-29 23:25 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views.py
>          response = super(TypeaheadSearchViewSet, self).list(request, *args, **kwargs)
Thanks for the help! 
I'm still new to DRF and I figured there was probably a simpler way to do what I was trying to do.

2016-11-29 23:35 UTC, clintonb requested changes

2016-11-29 23:35 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +        """ Value of the grey text next to the typeahead result title. """
The API doesn't care about display values. This docstring should go.

2016-11-29 23:35 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +        return result.org
Why not expose this as an actual field named `org`?

2016-11-29 23:35 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    def get_additional_details(self, result):
Why not expose this as a field named `orgs`?

2016-11-29 23:35 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +        return ', '.join([org['key'] for org in authoring_organizations])
The API should not be formatting for display. Return the array and do the formatting client-side.

2016-11-29 23:35 UTC, clintonb commented on course_discovery/apps/api/v1/views.py
> +            raise ParseError("missing required q parameter")
Do this validation in `get()`. `get_results` shouldn't care about query strings.

2016-11-29 23:35 UTC, clintonb commented on course_discovery/apps/api/v1/views.py
> +        course_runs = SearchQuerySet().models(CourseRun).raw_search(query)[:RESULT_COUNT]
Move `RESULT_COUNT` to be a constant on this view. It's not really needed outside of this view and its tests.

2016-11-30 16:07 UTC, MatthewPiatetsky commented
@clintonb @bderusha have I addressed your comments?

2016-11-30 17:33 UTC, clintonb approved these changes
Please address the comments before merging.

2016-11-30 17:33 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    orgs = serializers.SerializerMethodField()
`orgs` implies multiple orgs. This should be `org`, and you can drop the method. For future reference, you can alias fields by using the [`source` parameter](http://www.django-rest-framework.org/api-guide/fields/#source).

2016-11-30 17:33 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +        """ Value of the grey text next to the typeahead result title. """
This docstring is irrelevant.

2016-11-30 17:33 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +            'orgs': [program.authoring_organizations.first().key]
For completeness this should be the keys of all of the organizations: `list(program.authoring_organizations.all().values_list('key', flat=True))`.

2016-11-30 17:33 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
This newline shouldn't be here. All of the imports should be alphabetized.

2016-11-30 17:33 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        for i in range(RESULT_COUNT):
Create more items to ensure your limits are actually working: `range(RESULT_COUNT) + 1`.

2016-11-30 17:33 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
>          """ Test typeahead response with max number of course_runs and programs. """
Verify the typeahead responses always returns a limited number of results, even if there are more hits.

2016-11-30 17:33 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        self.assertDictEqual(response_data, {'course_runs': [self.serialize_course_run(course_run)],
Nit: Move the dictionary to a variable.

2016-11-30 17:33 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        """ Test typeahead response with missing q parameter. """
Verify the view raises an error if the 'q' query string parameter is not provided.

2016-11-30 17:33 UTC, clintonb commented on course_discovery/apps/api/v1/views.py
> +            raise ParseError("missing required q parameter")
The 'q' querystring parameter is required for searching.

2016-11-30 17:43 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +    orgs = serializers.SerializerMethodField()
Currently implementation of the indexed field assumes that there is one org, but we know we will have course runs with multiple orgs at some point in the future. This was the reason I put orgs, but I suppose if we don't fully support multiple orgs I can put org for now and we can change it to orgs in the future

2016-11-30 17:44 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    orgs = serializers.SerializerMethodField()
That would be best. True multi-organization courses are a long ways out. I haven't even heard them discussed.

2016-11-30 19:23 UTC, bderusha approved these changes

2016-11-30 19:25 UTC, merged