Awais786/ecom 6142
openedx/course-discovery pull request #460
Opened 2016-11-29 19:32 UTC by awais786

WIP:

2016-11-29 19:43 UTC, awais786 commented
@bderusha PR is in progress. Just take an overview and let me know if things looks fine.

2016-11-29 19:45 UTC, awais786 commented
Instead of loading the groups in form. I am loading the GroupOrganization table there.

2016-11-30 00:45 UTC, bderusha reviewed
Looks good.  A few minor comments

2016-11-30 00:45 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +                    organization = get_object_or_404(GroupOrganization, pk=course_form.data['organization'])
prefer `group_organization` as a variable name

2016-11-30 00:45 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +                    # course.assign_permission_by_group(institution)
If this is not needed we should remove it

2016-11-30 17:21 UTC, awais786 commented
Due to the organization base permissions I have to fix all the test cases also some mixins.  But we have to update them also in future stories.

2016-11-30 18:00 UTC, awais786 commented
@bderusha I don't think we need to add any permissions in this PR. 
I can close this sub-task without any implementation https://openedx.atlassian.net/browse/ECOM-6412?

2016-11-30 18:49 UTC, awais786 commented
@bderusha please review this PR again.

2016-12-01 07:44 UTC, awais786 commented
@waheedahmed @tasawernawaz @ahsan-ul-haq Please review this.

2016-12-01 18:26 UTC, awais786 commented
@bderusha Please review this PR.

2016-12-01 22:13 UTC, bderusha requested changes

2016-12-01 22:13 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +    return user.is_staff or (course and course.get_group_from_organizations() in user.groups.all())
This is no longer checking the view permission.  We should be leveraging django's permision checking syntax as much as possible.

```
return user.is_staff or any([user.has_perm(Course.VIEW_PERMISSION, organization) for organization in course.organizations])
```

2016-12-01 22:13 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +        """ Returns the first group associated with organizations."""
This docstring is confusing to me.  Do we allow multiple groups to be associated with an organization?

2016-12-01 22:13 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +        group = self.get_group_from_organizations()
Again, we should be getting users with permissions on the org objects directly, not just checking for groups.

2016-12-01 22:13 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +        groups = [grp_org.publisher_organizations.group for grp_org in self.organizations.all()]
verbose variables please. `group_organization`

2016-12-01 22:13 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_emails.py
> +        cls.group_organization_1 = factories.GroupOrganizationFactory()
if there is only one `group_organization` there is no need to number it.  Or we need to number `user` as `user_1`.  Either way is fine by me as long as we are consistent.

2016-12-01 22:13 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_model.py
> +        """ Verify that only group associated users can view the course. """
We will need to update this test to `""" Verify that only users with permissions on the org can view the course. """`

2016-12-01 22:13 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +        # self.assertEqual(course.group_institution, self.group_organization_1)
Delete if not needed

2016-12-02 02:14 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> -    def assign_permission_by_group(self, institution):
@bderusha so we should assign the permission here. I had remove this

2016-12-02 07:22 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
> +    return user.is_staff or (course and course.get_group_from_organizations() in user.groups.all())
It mean we have to assign permissions on org object ?

2016-12-02 07:28 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
> +    return user.is_staff or (course and course.get_group_from_organizations() in user.groups.all())
Yesterday we decided we will not assign permissions thats close the sub-task also.

2016-12-06 11:18 UTC, awais786 commented
@bderusha Please review this PR.

2016-12-06 18:39 UTC, awais786 commented
@bderusha Please review this PR.

2016-12-08 04:48 UTC, bderusha requested changes
Still confused about some of the permission settings.  Also I think we need to updated the name of the class.  Sorry for springing it on you kind of late in the PR process.

2016-12-08 04:48 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +    organization = forms.ModelChoiceField(queryset=GroupOrganization.objects.all(), required=True)
Why are we doing it this way?  Why not just attach the actual org

2016-12-08 04:48 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    def assign_permission_by_group(self, group):
I still don't understand why we need to assign permissions in the code here.  Please explain?

2016-12-08 04:48 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    def group_organization(self):
The course should not need access to this and if it does (please provide reasoning) it needs to return ALL of them not just the first one.

2016-12-08 04:48 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +class GroupOrganization(TimeStampedModel):
Given that we are going to also be attaching permissions to this I think it would be more extensible if we called this `OrganizationExtension` or something that doesn't pin it to just being a join table.  I know this is a big change and I'm sorry for not bringing it up before. I am only now realizing this.  But better to catch it now than after we run the migrations.

If we could have we would have just added a group directly to `Organization` but we don't want to do that so we must extend that object with a publisher specific one. 

If we could have we would have just added the permissions directly to the Meta of the `Organization` but we don't want to do that so we must find a publisher specific place for those as well. 

Imagine tomorrow we realize that Publisher needs to associate a default seat type with an `Organization`.  If we call it `OrganizationExtension` or `PublisherOrganization` or something like that it makes sense why `default_seat_type` should live there.  If we continue to call it `GroupOrganization` it feels very strange attaching all of this stuff to it.  It's just for groups.

The functionality ends up being the same, but the intention is more clear.

2016-12-08 04:48 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    organization = models.OneToOneField(Organization, related_name='publisher_organizations')
`related_name='group_organization'`  Singular.  Or `organization_extension`/`publisher_organization` if we update the name

2016-12-08 04:48 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    group = models.OneToOneField(Group, related_name='publisher_groups')
Same as above

2016-12-08 07:47 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +    organization = forms.ModelChoiceField(queryset=GroupOrganization.objects.all(), required=True)
It will load only those organizations which are associated with any group. If I load from organizations table and user choose any of that organization which has no record in GroupOrganization it will create problem.

2016-12-08 07:49 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +    def assign_permission_by_group(self, group):
Actually we don't need to assign permission now. I thought we will remove this code in any other story. I just rename the variable. But i think it's better to remove.

2016-12-08 08:18 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +    def assign_permission_by_group(self, group):
I think its better to remove the permissions code in my other PR.
Because there I am fixing how to pick the courses based on roles.  
[PR 479](https://github.com/edx/course-discovery/blob/71a2dd4f1c4f8816d1718e6cb4184a8f16d1d178/course_discovery/apps/publisher/views.py#L43)

2016-12-08 09:32 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +    def group_organization(self):
We need to show the associated organization with course on dashboard. We have a m2m field as organization in the table. but in publisher app only one org can be join with one course.

2016-12-08 09:33 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +    def group_organization(self):
If return all orgs from m2m. Then do we need to show all orgs on dashboard for a course ?

2016-12-08 09:45 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +    organization = forms.ModelChoiceField(queryset=GroupOrganization.objects.all(), required=True)
queryset=Organization.objects.filter(id__in=OrganizationExtension.objects.all())

2016-12-08 09:56 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +class GroupOrganization(TimeStampedModel):
I have renamed the table as per your suggestion.

2016-12-08 11:31 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> -    def assign_permission_by_group(self, institution):
This will be remove in another PR where we are implementing the courses by rules.

2016-12-08 12:47 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +    def assign_permission_by_group(self, group):
But we have to assign the permission from OrganizationExtension table. So I think it make sense to create a ticket for that purpose.

2016-12-08 16:32 UTC, awais786 commented
@bderusha I have fixed all of your requested changes. For permissions we have to remove the assignment of permissions from course. My suggestion is to add a separate ticket to remove this or we can implement this when implement the OrganiztionExtension permission assignment from the admin.

2016-12-12 17:08 UTC, bderusha requested changes
Please clean up all of the references to group_organizations since that is no longer a thing.

2016-12-12 17:08 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    organization = models.OneToOneField(Organization, related_name='publisher_organization')
the `related_name` is `organization_extension`

2016-12-12 17:08 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    group = models.OneToOneField(Group, related_name='publisher_group')
the `related_name` is `organization_extension`

2016-12-12 17:08 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    def group_organization(self):
group organization isn't a thing anymore.  This method should be renamed

2016-12-12 17:08 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +                    group_organization = get_object_or_404(OrganizationExtension, pk=course_form.data['organization'])
update variable name

2016-12-12 17:08 UTC, bderusha commented on course_discovery/templates/publisher/dashboard/_in_progress.html
> +                    <td>{% if course_run.course.group_organization %}
we should be accessing the course's organizations directly.  There is no need to go through this middle-man

2016-12-12 17:08 UTC, bderusha commented on course_discovery/templates/publisher/dashboard/_in_progress.html
> +                    <td>{% if course_run.course.group_organization %}
Here and all other templates

2016-12-12 17:08 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +                    group_organization = get_object_or_404(OrganizationExtension, pk=course_form.data['organization'])
here and throughout

2016-12-12 17:08 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    def group_organization(self):
I think that in the templates we should just get the first org for now.  However that is entirely a scope issue.  We know that we want to support multiple orgs in the future.  So the few places we have that make assumptions about there being only one org, the better

2016-12-12 18:26 UTC, awais786 commented
@bderusha I have made all changes.

2016-12-13 18:38 UTC, bderusha requested changes

2016-12-13 18:38 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    def group_extension(self):
I still don't understand why this is necessary and why we have chosen this name.  This method has nothing to do with groups

2016-12-13 18:38 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +        It should come from the group-organization table not from M2M field.
Why not?

2016-12-13 18:38 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +                    group_extension = get_object_or_404(OrganizationExtension, pk=course_form.data['organization'])
What is a `group_extension`?  Am I missing something?

2016-12-13 18:38 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    def group_extension(self):
Also this method is not used at all in the application outside of tests.  Let's just delete it.

2016-12-13 19:06 UTC, awais786 commented on course_discovery/apps/publisher/views.py
> +                    group_extension = get_object_or_404(OrganizationExtension, pk=course_form.data['organization'])
This should be organization_extension. I mixed up the old and new variable name thats why it is causing confusion.

2016-12-13 19:39 UTC, awais786 commented
Update the variable name and also remove the method.

2016-12-13 20:41 UTC, bderusha approved these changes
👍 once tests pass

2016-12-14 10:41 UTC, waheedahmed requested changes
You need to recreate your migration, two migrations with same number.

2016-12-14 11:01 UTC, waheedahmed approved these changes

2016-12-15 06:26 UTC, merged