(WIP) Added Branding Logo Image to the Programs
openedx/course-discovery pull request #476
Opened 2016-12-06 13:18 UTC by afzaledx

2016-12-06 13:53 UTC, clintonb requested changes
WL-775 calls for having a logo *per program type*. You have added the logo to the `Program` model which is incorrect. You should be modifying the `ProgramType` model. Additionally, we should chat about your use cases to understand how this will be exposed via API.

2016-12-06 13:53 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0039_merge.py
> +# -*- coding: utf-8 -*-
This is unnecessary. If there is already a migration numbered `0038`, you need to regenerate your migration.

2016-12-07 11:30 UTC, afzaledx commented
@clintonb, I have made the changes. Can you please review?

2016-12-07 11:34 UTC, afzaledx commented on course_discovery/apps/course_metadata/models.py
> +            'large': (256, 256),
These dimensions might be changed in the future since we're not sure at this stage what the exact sizes are going to be.

2016-12-07 11:38 UTC, afzaledx commented
@ibrahimahmed443 @hasnain-naveed @douglashall 

The branch with the logo image has been added to the Programs dictionary
The logo image can be added to a `ProgramType` from the Django admin. The logo will not be visible when modifying a program, but the image will be returned whenever all programs, or a specific program (with a uuid) is requested.

2016-12-07 15:08 UTC, douglashall commented on course_discovery/apps/course_metadata/models.py
> +        upload_to=UploadToFieldNamePath(populate_from='name', path='media/program_types/logo_images'),
Can `UploadToFieldNamePath` handle the case when the `name` field has spaces/non-alphanumeric characters?

2016-12-07 15:09 UTC, afzaledx commented
Probably not. I will fix it

On Dec 7, 2016 8:08 PM, "Douglas Hall" <notifications@github.com> wrote:

> *@douglashall* commented on this pull request.
> ------------------------------
>
> In course_discovery/apps/course_metadata/models.py
> <https://github.com/edx/course-discovery/pull/476#pullrequestreview-11819192>
> :
>
> > @@ -580,6 +580,17 @@ class ProgramType(TimeStampedModel):
>                                'associated courses, but enrolled in other seat types, will NOT have their completion '
>                                'of the course counted toward the completion of the program.'),
>      )
> +    logo_image = StdImageField(
> +        upload_to=UploadToFieldNamePath(populate_from='name', path='media/program_types/logo_images'),
>
> Can UploadToFieldNamePath handle the case when the name field has
> spaces/non-alphanumeric characters?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/edx/course-discovery/pull/476#pullrequestreview-11819192>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AJNO9lafu17XYQ_fUZBCNyvcedOr30JNks5rFsvpgaJpZM4LFZal>
> .
>

2016-12-07 15:40 UTC, clintonb requested changes
Create a new API endpoint, and test it.

2016-12-07 15:40 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    logo_image = StdImageSerializerField(source='type.logo_image')
We have done a lot of work to tune these API endpoints. If you need to expose information about program types, that should be done via a new API endpoint (/program_types). Also, you need tests.

2016-12-07 15:40 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        upload_to=UploadToFieldNamePath(populate_from='name', path='media/program_types/logo_images'),
Nope. Use ID.

2016-12-07 15:41 UTC, douglashall commented on course_discovery/apps/api/serializers.py
> +    logo_image = StdImageSerializerField(source='type.logo_image')
Will this be an absolute URL to the program type logo image file?

2016-12-08 09:55 UTC, afzaledx commented on course_discovery/apps/api/serializers.py
> +    logo_image = StdImageSerializerField(source='type.logo_image')
works like the "banner_image" dictionary from here: https://stage-edx-discovery.edx.org/api/v1/programs/0df34738-be78-4a08-8382-566cf4682691/

Running locally, I am getting something like this: http://127.0.0.1:18381/media/media/program_types/logo_images/professional_wIQA9lv.medium.png

2016-12-08 10:03 UTC, douglashall commented on course_discovery/apps/api/serializers.py
> +    logo_image = StdImageSerializerField(source='type.logo_image')
Excellent, thanks for the confirmation.

2016-12-08 12:52 UTC, clintonb requested changes

2016-12-08 12:52 UTC, clintonb commented on course_discovery/apps/api/v1/views/program_types.py
> +    filter_backends = (DjangoFilterBackend,)
You're not filtering, so this isn't needed.

2016-12-08 12:52 UTC, clintonb commented on course_discovery/apps/api/v1/views/program_types.py
> +# pylint: disable=no-member
This is not needed.

2016-12-08 12:52 UTC, clintonb commented on course_discovery/apps/api/v1/views/program_types.py
> +from course_discovery.apps.course_metadata.models import ProgramType
Group this with the other import.

2016-12-08 12:52 UTC, clintonb commented on course_discovery/apps/api/v1/views/program_types.py
> +    """ Program resource. """
This is wrong.

2016-12-08 12:52 UTC, clintonb commented on course_discovery/apps/api/v1/views/program_types.py
> +class ProgramTypeViewSet(viewsets.ReadOnlyModelViewSet):
This can live in the programs module.

2016-12-08 12:52 UTC, clintonb commented on course_discovery/apps/api/v1/views/program_types.py
> +    lookup_field = 'name'
This is not a good lookup field, because there may be spaces. Add a slug field, use it.

2016-12-08 12:52 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    name = models.CharField(max_length=32, unique=True, null=False, blank=False, db_index=True)
Unique fields are indexed by definition.

2016-12-08 12:54 UTC, clintonb commented on course_discovery/apps/api/v1/views/program_types.py
> +    lookup_field = 'name'
You'll want the AutoSlugfield to be unique and non-nullable.

2016-12-08 13:35 UTC, afzaledx commented on course_discovery/apps/api/v1/views/program_types.py
> +    lookup_field = 'name'
This is still outstanding.

2016-12-08 13:42 UTC, afzaledx commented on course_discovery/apps/api/v1/views/program_types.py
> +    lookup_field = 'name'
@clintonb, when I ask for the Programs list, I get the list of program dictionaries having the ProgramType name only. I am going to loop each of those and hit the ProgramType endpoint that I just created to get the image_logo filed for each program.

2016-12-08 13:46 UTC, clintonb commented on course_discovery/apps/api/v1/views/program_types.py
> +    lookup_field = 'name'
That is an inefficient solution. If you get 20 programs, you will poll the endpoint 20 times. Given the limited number of program types, you should get the full list of program types and cache it on the client. When you need details of a program type, refer to your local cache.

Additionally, `name` is a bad identityf field because it is editable and may contain whitespace. `/api/v1/program_types/Professional Certification` is not a path we want in the API. Thus you want to use either a slug or UUID.

2016-12-08 14:30 UTC, afzaledx commented on course_discovery/apps/api/v1/views/program_types.py
> +    lookup_field = 'name'
In that case, I will not need the lookup field at all since I only want the list of all the programs for my local cache.

2016-12-08 14:33 UTC, afzaledx commented on course_discovery/apps/api/v1/views/program_types.py
> +    lookup_field = 'name'
If you remember, my first attempt was to add the type.logo_image in the programs endpoint. We already have the type (ProgramType) in the Programs model, but you suggested that it might cause a performance hit. That's why I created this new endpoint.

2016-12-08 14:57 UTC, afzaledx commented on course_discovery/apps/api/v1/views/program_types.py
> +    lookup_field = 'name'
The lookup_field defaults to id, and that is working just fine for individual program types.

2016-12-08 15:13 UTC, afzaledx commented on course_discovery/apps/api/v1/views/programs.py
> -    lookup_field = 'name'
@clintonb, I have removed the lookup_field from here, mostly because of the "spaces" in the URL messing up the lookup. The efficiency of multiple lookups was easily handled because the catalog integration is cached by default, so they would not have been an overhead.

Since I was only getting the ProgramType's "name" field in the Programs endpoint that I need for looking up the logo_image, the only remaining solution is to fetch all the program types and do a local lookup. This is what I have done on the edx-platform side.

2016-12-08 15:16 UTC, clintonb requested changes

2016-12-08 15:16 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +            'id', 'name', 'logo_image',
Do not expose database IDs. We don't want to repeat mistakes of the past and reference objects in this manner externally.

2016-12-08 15:16 UTC, clintonb commented on course_discovery/apps/api/v1/views/programs.py
> +class ProgramTypeViewSet(viewsets.ReadOnlyModelViewSet):
Either add a slug field or make this a list-only view. Providing external references as database IDs is a non-starter. It opens us up to numerous problems that we can easily avoid.

2016-12-08 15:16 UTC, clintonb commented on course_discovery/conf/locale/en/LC_MESSAGES/djangojs.po
> -# SOME DESCRIPTIVE TITLE.
Why are these files changed?

2016-12-08 15:16 UTC, afzaledx commented
@clintonb, I need help with the strange translations error that I am not familiar with.

2016-12-08 20:05 UTC, clintonb requested changes
`ProgramTypeListViewSet` needs tests.

2016-12-09 13:14 UTC, douglashall commented
@clintonb Can you please describe for Afzal what needs to be changed in order to resolve the translation related errors in the failed checks? Thanks.

2016-12-09 13:23 UTC, clintonb approved these changes
See comments. Remember to squash your commits before merging. Delete your branch after merging.

2016-12-09 13:23 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        expected = [ProgramTypeFactory() for __ in range(3)]
`ProgramTypeFactory.create_batch(3)`

2016-12-09 13:23 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        help_text=_('Please provide an image file with transparent background'),
This is the source of your build failures. Run `make fake_translations`.

2016-12-09 15:49 UTC, afzaledx commented
This test is passing locally but failing on travis. Will look into it later.

2016-12-12 15:05 UTC, douglashall commented on course_discovery/apps/course_metadata/models.py
> +        upload_to=UploadToFieldNamePath(populate_from='id', path='media/program_types/logo_images'),
@afzaledx When I save a new program type with a logo_image in Django admin, the logo_image [filename](https://discovery-edx.sandbox.edx.org/api/v1/program_types/) is 'none.medium.png'. Since the `id` field isn't populated until you save the model to the database, it looks like it is not the right candidate for use as the filename. The best path forward is probably to add a UUIDField and use it as the filename.

2016-12-13 11:21 UTC, afzaledx commented on course_discovery/apps/course_metadata/models.py
> +        upload_to=UploadToFieldNamePath(populate_from='id', path='media/program_types/logo_images'),
@douglashall, Instead of the uuid, I have changed it to:

`upload_to=UploadToAutoSlug(populate_from='name', path='media/program_types/logo_images')`

With the ProgramType name as : `ProgramType with Caps And Spaces`, the file name becomes: `programtype-with-caps-and-spaces.png`

2016-12-13 11:23 UTC, afzaledx commented on course_discovery/apps/course_metadata/models.py
> +        upload_to=UploadToFieldNamePath(populate_from='id', path='media/program_types/logo_images'),
Moreover, if the file is changed, it auto-adds a uuid in the end to make it unique, e.g. `programtype-with-caps-and-spaces_FOPO7av.png`

2016-12-13 20:15 UTC, douglashall commented
👍  Latest is deployed to https://discovery-edx.sandbox.edx.org. Ready for merge.

2016-12-13 20:19 UTC, douglashall commented
@afzaledx Looks like you will need to rebase one more time before merging.

2016-12-13 21:44 UTC, clintonb reviewed
Please add a migration to the [`edx_catalog_extensions` app](https://github.com/edx/course-discovery/tree/master/course_discovery/apps/edx_catalog_extensions) that adds the images now, or when they are available. Ideally, we should avoid manually adding these items so that it is easy to provision devstack and sandboxes.

2016-12-13 21:49 UTC, douglashall commented
@clintonb Good to know. We may or may not be able to add them as migrations depending on the contents of the name/logo and the confidentiality status of the partner.

2016-12-14 11:23 UTC, merged