ignore for now
openedx/course-discovery pull request #477
Opened 2016-12-06 14:48 UTC by MatthewPiatetsky

ECOM-4738 Use ngrams for autocomplete and set up index settings/mappings

2016-12-06 20:40 UTC, rlucioni requested changes

2016-12-06 20:40 UTC, rlucioni commented on course_discovery/apps/api/v1/views/search.py
> +        query = query.lower()
This can be removed (the lowercase analyzer handles this).

2016-12-06 20:40 UTC, rlucioni commented on course_discovery/apps/core/tests/mixins.py
> +        backend.setup_complete = False
I'd include a comment about why this is necessary/what it achieves.

2016-12-06 20:40 UTC, rlucioni commented on course_discovery/apps/core/utils.py
> +            if is_test:
Instead, just override HAYSTACK_CONNECTIONS in settings/test.py.

2016-12-06 20:40 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +        mapping['title_autocomplete'] = title_autocomplete_mapping
Consider breaking this out into a separate method to make what's going on here more clear (e.g., `configure_title_autocomplete_analyzers`).

2016-12-06 20:40 UTC, rlucioni commented on course_discovery/settings/base.py
> +  "settings": {
Nitpick (I'm surprised pylint didn't complain): 4 spaces and single qutoes, to be consistent with everything else, please.

2016-12-06 21:05 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/search.py
> +        query = query.lower()
fixed

2016-12-06 21:05 UTC, MatthewPiatetsky commented on course_discovery/apps/core/tests/mixins.py
> +        backend.setup_complete = False
added

2016-12-06 21:05 UTC, MatthewPiatetsky commented on course_discovery/apps/core/utils.py
> +            if is_test:
fixed

2016-12-06 21:05 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +        mapping['title_autocomplete'] = title_autocomplete_mapping
changed

2016-12-06 21:05 UTC, MatthewPiatetsky commented on course_discovery/settings/base.py
> +  "settings": {
fixed

2016-12-06 21:05 UTC, clintonb commented
How does this differ from the Auto-complete functionality built into `drf-haystack`: https://drf-haystack.readthedocs.io/en/latest/02_autocomplete.html?

2016-12-06 21:06 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/search.py
> +
@rlucioni I also added this comment below, which I think may be helpful in explaining the general idea (and is readable in swagger)

2016-12-06 21:32 UTC, MatthewPiatetsky commented
@clintonb This is using the same functionality, but has some additional changes..using different index vs search analyzers as well as actually initializing the index settings/mapping for both index creation and tests

2016-12-06 21:36 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/search.py
> +    GET:
@clintonb I'm trying to figure this out now, but do you know if there is a way to get this docstring to work properly for both the drf swagger UI and the self describing API UI?

2016-12-06 21:43 UTC, clintonb commented on course_discovery/apps/api/v1/views/search.py
> +    GET:
http://django-rest-swagger.readthedocs.io/en/stable-0.3.x/yaml.html

2016-12-06 22:05 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/search.py
> +    GET:
What I have currently seems to work fine with swagger, but get a error message rendered in the drf view (the results do come back), if I omit the GET then it works in drf view but doesn't even load in swagger

2016-12-06 22:10 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/search.py
> +    GET:
thanks! I just needed to add the docstring to the method rather than the class

2016-12-06 23:11 UTC, rlucioni commented on course_discovery/apps/core/tests/mixins.py
> +        connection = haystack_connections[backends[0]]
Can you look up the connection by name? Is the backend at index 0 always going to be correct? Typically, Django would have you use a name to look up a connection in a situation like this (e.g., default).

2016-12-06 23:11 UTC, rlucioni commented on course_discovery/apps/core/tests/mixins.py
> +        backend.setup_complete = False
Should this be set in a teardown method?

2016-12-06 23:11 UTC, rlucioni commented on course_discovery/settings/base.py
> +    'settings':{
pep8 should be upset with you about this, too. You need a space between the colon and the brace, here and throughout.

2016-12-06 23:14 UTC, rlucioni commented on course_discovery/settings/test.py
> +        'URL': 'http://127.0.0.1:9200/',
The [Travis build log](https://travis-ci.org/edx/course-discovery/builds/181793725#L7239) suggests this may not work out after all. Looks like the tests can't connect to Elasticsearch.

2016-12-07 00:51 UTC, MatthewPiatetsky commented on course_discovery/settings/test.py
> +        'URL': 'http://127.0.0.1:9200/',
there were some builds that passed fully earlier I'll figure out what broke tomorrow

2016-12-07 15:12 UTC, MatthewPiatetsky commented on course_discovery/apps/core/tests/mixins.py
> +        connection = haystack_connections[backends[0]]
fixed

2016-12-07 15:13 UTC, MatthewPiatetsky commented on course_discovery/apps/core/tests/mixins.py
> +        backend.setup_complete = False
idk, this flag is set in the set up process (on the previous line I think), if we don't want it set think it makes sense to set to False right after

2016-12-07 15:13 UTC, MatthewPiatetsky commented on course_discovery/settings/base.py
> +    'settings':{
fixed

2016-12-07 19:57 UTC, clintonb commented on course_discovery/apps/api/v1/views/search.py
> +        Typeahead uses the ngram_analyzer as the index_analyzer to generate ngrams of the title during indexing.
Clean this up to be a proper paragraph. As is, it reads like a disjointed list, and is unclear.

2016-12-07 19:57 UTC, clintonb commented on course_discovery/apps/core/tests/mixins.py
> +        # This results in the tests after the first run missing the field mapping
You're missing something in this sentence.

2016-12-07 19:57 UTC, clintonb commented on course_discovery/apps/core/tests/mixins.py
> +        connection = haystack_connections['default']
Why are these changes necessary?

2016-12-07 19:57 UTC, clintonb commented on course_discovery/settings/base.py
> +ELASTICSEARCH_INDEX_SETTINGS = {
Add a comment explaining what you're doing, and why this is necessary.

2016-12-07 19:57 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +class ConfigurableElasticBackend(ElasticsearchSearchBackend):
This should be a mixin added to `EdxElasticsearchSearchBackend`.

2016-12-07 19:57 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +        # We need to use a lowercase analyzer for search instead of the ngram_analyzer.
```python
# Use the ngram analyzer for the autocomplete field to support partial searches/typeahead.
```

2016-12-07 19:57 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +        # The generic analyzer is used for both if index_analyzer and search_analyzer are not specified
```python
""" Specify separate index and search analyzers for the given field.
  Args:
    ...
"""
```

2016-12-07 19:59 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/search.py
> +        Typeahead uses the ngram_analyzer as the index_analyzer to generate ngrams of the title during indexing.
I did it this way to add line breaks in swagger. I can change it to be a paragraph, but then I think the swagger will be one big block with no line breaks?

2016-12-07 20:03 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +class ConfigurableElasticBackend(ElasticsearchSearchBackend):
It already is, right?

2016-12-07 20:05 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +        # We need to use a lowercase analyzer for search instead of the ngram_analyzer.
That's not quite what this means, since I am using the lowercase analyzer as the search_analyzer
Is this clearer?
# Use the ngram analyzer as the index_analyzer and the lowercase analyzer as the search_analyzer
# This is necessary to support partial searches/typeahead

2016-12-07 20:08 UTC, rlucioni commented on course_discovery/settings/base.py
> +                    'min_gram':2,
You're still missing a space between the colon and the characters that come afterwards, here and throughout this dict. I also just realized that pep8 isn't failing your build because we tell it to ignore settings files. You can try running it locally against this file to pick out all the places were you need to add a space.

2016-12-07 20:12 UTC, MatthewPiatetsky commented on course_discovery/apps/core/tests/mixins.py
> +        connection = haystack_connections['default']
added comment, let me know if it is unclear

2016-12-07 20:12 UTC, MatthewPiatetsky commented on course_discovery/apps/core/tests/mixins.py
> +        # This results in the tests after the first run missing the field mapping
not sure what you meant, but is it clearer now?

2016-12-07 20:12 UTC, MatthewPiatetsky commented on course_discovery/settings/base.py
> +ELASTICSEARCH_INDEX_SETTINGS = {
added a comment

2016-12-07 20:13 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +        # The generic analyzer is used for both if index_analyzer and search_analyzer are not specified
added a comment

2016-12-07 20:15 UTC, MatthewPiatetsky commented on course_discovery/settings/base.py
> +                    'min_gram':2,
fixed

2016-12-07 20:32 UTC, rlucioni commented on course_discovery/apps/core/tests/mixins.py
> +        backend = connection.get_backend()
What happens if you move most of this to setUpClass? It seems like the only line required here should be `backend.setup_complete = False`, since that's what you appear to need run before each test.

2016-12-07 20:32 UTC, rlucioni approved these changes
@MatthewPiatetsky looks good, just one last question about moving some test setup code.

2016-12-07 20:34 UTC, rlucioni commented
@MatthewPiatetsky looks like you might have introduced a flaky test? Can you take a look at the [build log](https://travis-ci.org/edx/course-discovery/builds/182077215#L6172) and see about clearing that up?

2016-12-07 20:37 UTC, clintonb commented on course_discovery/apps/api/v1/views/search.py
> +        Typeahead uses the ngram_analyzer as the index_analyzer to generate ngrams of the title during indexing.
The Swagger readability is less important than code readability. Also, at some point when we upgrade DRF, the method by which we extract Swagger text will change.

2016-12-07 20:37 UTC, MatthewPiatetsky commented
@rlucioni thanks, looking into it

2016-12-07 20:38 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +class ConfigurableElasticBackend(ElasticsearchSearchBackend):
No. You're subclassing `ConfigurableElasticBackend`, which is not necessary.

2016-12-07 20:39 UTC, clintonb commented on course_discovery/settings/base.py
> +# so we need to use these settings rather than the index defaults
Explain _why_ this is necessary. Would @MatthewPiatetsky from last week know why we need an ngram analyzer?

2016-12-07 20:41 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +            mapping: /_mapping attribute on index (maps analyzers to fields)
Add types after the argument names.

2016-12-07 20:54 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +class ConfigurableElasticBackend(ElasticsearchSearchBackend):
I need the parent to be ElasticsearchSearchBackend to get the mapping in build_schema.
Are you suggesting I put just the specify analyzers function in a mixin?

2016-12-07 20:55 UTC, MatthewPiatetsky commented on course_discovery/settings/base.py
> +# so we need to use these settings rather than the index defaults
not sure exactly what you mean by why, does the line below clarify?

2016-12-07 20:57 UTC, clintonb commented on course_discovery/settings/base.py
> +# so we need to use these settings rather than the index defaults
Yes, that works. You just need some periods in these sentences.

2016-12-07 20:58 UTC, clintonb approved these changes

2016-12-07 20:58 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/search.py
> +        Typeahead uses the ngram_analyzer as the index_analyzer to generate ngrams of the title during indexing.
updated

2016-12-07 21:05 UTC, MatthewPiatetsky commented on course_discovery/apps/core/tests/mixins.py
> +        backend = connection.get_backend()
good idea, changed

2016-12-07 21:18 UTC, merged

2016-12-07 21:54 UTC, rlucioni commented on course_discovery/apps/core/tests/mixins.py
> +        # do not set the Elasticsearch _mapping
@MatthewPiatetsky you might want to open a new PR to move this comment above the line it refers to.