Awais786/ecom 6293 list as pc
openedx/course-discovery pull request #479
Opened 2016-12-07 08:31 UTC by awais786

WIP

2016-12-07 09:18 UTC, awais786 commented
@tasawernawaz @waheedahmed Please review this PR.

2016-12-07 12:28 UTC, waheedahmed requested changes
Right now the implementation doesn't look right to me, I think first you should re-think your implementation.

2016-12-07 12:28 UTC, waheedahmed commented on course_discovery/apps/publisher/constants.py
> +PUBLISHER_GROUP_NAME = 'publisher Admins'
These are not admins, change the names to:
```PARTNER_GROUP_NAME = 'Partner Coordinators'```
```REVIEWER_GROUP_NAME = 'Marketing Reviewers'```
```PUBLISHER_GROUP_NAME  = 'Publishers'```

2016-12-07 12:28 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.course_run_2.change_state(target=State.NEEDS_FINAL_APPROVAL)
I think definition of in-progress is: A course-run is in all states (Draft, In-Review, Need-Approval, etc) except ```Published``` state.

2016-12-07 12:28 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        elif is_partner_coordinator_user(user):
What about other tabs? With this code a PC can only see the course-runs which are currently assigned to him as PC in all other tabs, what if he is a assigned as marketing reviewer or publisher for some course-runs then he will not see them in in-progress or published tabs.

2016-12-12 18:58 UTC, bderusha approved these changes
A few small changes.  👍 once implemented

2016-12-12 18:58 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +    def assert_dashboard_response(self, studio_cnt=0, published_cnt=0, progress_cnt=0, preview_cnt=0):
please use full word `count`

2016-12-12 18:58 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +        response = self.assert_dashboard_response(studio_cnt=2, preview_cnt=0, progress_cnt=1, published_cnt=1)
please use full word `count`

2016-12-12 18:58 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assert_dashboard_response(studio_cnt=2, published_cnt=0, progress_cnt=1, preview_cnt=1)
please use full word `count`

2016-12-12 18:58 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assert_dashboard_response(0, 0, 0, 0)
Prefer naming the kwargs.  `self.assert_dashboard_response(studio_cnt=2, published_cnt=0, progress_cnt=1, preview_cnt=1)`  Much more readable that way and clear what you are testing for.

2016-12-12 19:00 UTC, bderusha commented on course_discovery/apps/publisher/constants.py
> +PARTNER_GROUP_NAME = 'Partner Coordinators'
`PARTNER_COORDINATOR_GROUP_NAME`

2016-12-12 19:50 UTC, bderusha commented
@awais786 You should be able to set up a sandbox now.  FYI https://openedx.atlassian.net/wiki/display/EdxOps/Sandboxes#Sandboxes-ProvisioningwithCatalogService(CourseDiscovery)

2016-12-13 10:24 UTC, waheedahmed requested changes
The code looks good now, but I think you missed one check:
1. Validate that a PC can see all course-runs assigned to him/her that need a Studio Instance created.

The current code will show all course runs which require studio instance even if a user is not PC for them but he is a Reviewer or Publisher.

2016-12-13 12:06 UTC, awais786 commented
@bderusha can you please take a look again i have added the missing condition for studio requests for PC.

2016-12-13 18:11 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +        """ Verify that inter user can see courses assigned to the groups. """
`internal`

2016-12-13 18:15 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +        assign_perm(Course.VIEW_PERMISSION, factories.GroupFactory(), self.course_run_1.course)
We should be assigning permission to the org

2016-12-13 18:31 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +        assign_perm(Course.VIEW_PERMISSION, factories.GroupFactory(), self.course_run_1.course)
here and below

2016-12-13 18:50 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_views.py
> +        assign_perm(Course.VIEW_PERMISSION, factories.GroupFactory(), self.course_run_1.course)
@bderusha That is not part of this story. We have remove the Group Permissions and fix all tests cases which should be a separate ticket.

2016-12-13 19:00 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +        assign_perm(Course.VIEW_PERMISSION, factories.GroupFactory(), self.course_run_1.course)
gotcha 👍

2016-12-14 10:16 UTC, waheedahmed approved these changes
Some small nits otherwise 👍

2016-12-14 10:16 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +
Remove this line.

2016-12-14 10:16 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +
Remove this line.

2016-12-14 10:16 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +
Remove this line.

2016-12-14 10:55 UTC, merged