Added permissions on published course runs tab.
openedx/course-discovery pull request #481
Opened 2016-12-08 11:12 UTC by waheedahmed

[ECOM-6298](https://openedx.atlassian.net/browse/ECOM-6298)

As a user in a role, I want to be able to see recent published course runs that I am assigned to.

**ACs:**

1. Only Course-runs that a user is assigned to (eg. PC, Marketer, Publisher) are displayed.
2. All course-runs are shown for publisher admins.

2016-12-08 11:20 UTC, tasawernawaz requested changes

2016-12-08 11:20 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
> +        # Verify that user cannot see 1 course run in published tab
`Verify that user can see 1 course run in published tab`

2016-12-08 11:21 UTC, tasawernawaz approved these changes
Just a nit, otherwise 👍

2016-12-08 11:25 UTC, waheedahmed commented
@edx/ecommerce Please review.

2016-12-13 07:39 UTC, waheedahmed commented
@bderusha Kindly review my PR.

2016-12-13 18:08 UTC, bderusha approved these changes

2016-12-14 07:44 UTC, merged