Boost orgs autocomplete in typeahead
openedx/course-discovery pull request #490
Opened 2016-12-14 22:50 UTC by MatthewPiatetsky

@edx/ecommerce 

Jasper found another issue where a smithsonian course was coming up above a MIT course.
We tested this by reindexing locally and it fixed the issue.
There are no other typeahead issues that we are aware of

2016-12-14 22:56 UTC, clintonb approved these changes

2016-12-14 22:56 UTC, mikedikan commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +            title="Objects That Define America"
Shouldn't we be testing that the title contains the "mit" string?

2016-12-14 22:58 UTC, rlucioni requested changes

2016-12-14 22:58 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        MITx = OrganizationFactory(key="MITx")
Nitpick: keep your quote level consistent. We tend to prefer single quotes.

2016-12-14 22:58 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +            'programs': []
Since you're boosting the org field for programs, too, a complete test should also cover programs.

2016-12-14 22:58 UTC, rlucioni commented on course_discovery/apps/course_metadata/search_indexes.py
> +ORG_FIELD_BOOST = 25.0
In case `TITLE_FIELD_BOOST` is changed in the future, I would make this:
```py
ORG_FIELD_BOOST = TITLE_FIELD_BOOST
```
Along with your comment, that makes the expected relationship between the two very clear.

2016-12-15 00:52 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        MITx = OrganizationFactory(key="MITx")
fixed

2016-12-15 00:52 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +            'programs': []
fixed

2016-12-15 00:52 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/search_indexes.py
> +ORG_FIELD_BOOST = 25.0
fixed

2016-12-15 00:53 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +            title="Objects That Define America"
good point, I've changed the test to test that the org is taken into account, Jasper and I did some discovery and there are some complex things going on, so we aren't quite fixing everything yet, but we will be doing some follow up work after releasing typeahead. These changes should give us the results we want with our current data, which should be fine for unblocking release of typeahead

2016-12-15 03:31 UTC, rlucioni commented on course_discovery/apps/api/tests/test_serializers.py
> +            'orgs': list(course_run.authoring_organizations.all().values_list('key', flat=True)),
Can you make this more readable with a list comprehension?
```py
'orgs': [org['key'] for org in course_run.authoring_organizations.all()]
```

2016-12-15 03:40 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
> +    def get_orgs(self, result):
`TypeaheadCourseRunSearchSerializer` and `TypeaheadProgramSearchSerializer` are looking very similar. You may want to subclass a new `TypeaheadBaseSearchSerializer` where you can move shared fields like `orgs` and `title`, and shared methods, like `get_orgs()`.

2016-12-15 04:11 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> +            'orgs': list(course_run.authoring_organizations.all().values_list('key', flat=True)),
fixed

2016-12-15 04:11 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +    def get_orgs(self, result):
good idea, changed

2016-12-15 05:19 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
> +class TypeaheadBaseSearchSerializer(serializers.Serializer):
Nice. You could take this a step further and define a metaclass here which can be extended by the child classes, like we do for the [minimal serializers](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/api/serializers.py#L287-L290).

2016-12-15 05:23 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
>      marketing_url = serializers.CharField()
Asking just because I don't see it: how is the `marketing_url` field populated? I don't see it listed in `fields`.

2016-12-15 13:17 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +class TypeaheadBaseSearchSerializer(serializers.Serializer):
I think in this case they only share title for the fields so using the meta class would be overly verbose

2016-12-15 13:28 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +class TypeaheadBaseSearchSerializer(serializers.Serializer):
good idea, fixed

2016-12-15 13:29 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
>      marketing_url = serializers.CharField()
I think I was a bit confused about this, http://www.django-rest-framework.org/api-guide/serializers/#specifying-fields-explicitly, seems like if you specify the fields explicitly they don't need to be in the Meta class. Anyway I have all the fields defined both ways now

2016-12-15 14:23 UTC, mikedikan approved these changes
:shipit:

2016-12-15 14:41 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
>      marketing_url = serializers.CharField()
@MatthewPiatetsky judging from the DRF serializer [docs](http://www.django-rest-framework.org/api-guide/serializers/#serializers), fields specified in the metaclass &mdash; and the metaclass itself for that matter &mdash; only seem to be relevant for the `ModelSerializer`. You should be able to drop the metaclass altogether here.

2016-12-15 14:41 UTC, rlucioni approved these changes
@MatthewPiatetsky I left one last comment about cleaning up the metaclasses, 👍 otherwise. Sorry about the back and forth, just making sure we're keeping things clean!

2016-12-15 15:01 UTC, merged