Tasawer/ecom 6525 front end for comment edit
openedx/course-discovery pull request #492
Opened 2016-12-15 11:31 UTC by tasawernawaz

[ECOM-6525](https://openedx.atlassian.net/browse/ECOM-6525)

* JS and CSS added for edit comment
* HTML refactoring

Edit comment functionality added using `/publisher/comments/api/comments/1/` API.

2016-12-15 11:34 UTC, tasawernawaz commented
@awais786 @waheedahmed Please review this.

2016-12-15 12:03 UTC, awais786 commented
Instead of input box it should be the TextArea.

2016-12-15 12:09 UTC, tasawernawaz commented
@awais786 it is not a `textbox`, code simply convert `dd` (text) into editable mode. For longer text you can look at this screenshot.

<img width="377" alt="screen shot 2016-12-15 at 5 07 28 pm" src="https://cloud.githubusercontent.com/assets/4245618/21223479/2e25b288-c2e9-11e6-91c9-3b4a8b163f68.png">

2016-12-15 13:08 UTC, tasawernawaz commented
@bderusha Please review this.

2016-12-15 18:54 UTC, bderusha requested changes

2016-12-15 18:54 UTC, bderusha commented on course_discovery/static/js/publisher/comments.js
> +        editableControlsHtml = '<div class="edit-controls"><span><a href="#" class="comment-save">Save</a></span>' +
These should be buttons, rather than anchor tags

2016-12-15 18:54 UTC, bderusha commented on course_discovery/static/sass/publisher/course_form.scss
> +  padding-right: 10px;
add RTL compatibility

2016-12-15 18:54 UTC, bderusha commented on course_discovery/static/js/publisher/comments.js
> +        url: $(editableControls).prev().find('a').attr('href'),
this should be a data attribute of something rather than baked into a anchor tag we arent actually using

2016-12-15 18:54 UTC, bderusha commented on course_discovery/templates/comments/comments_list.html
> +            - <a href="{% url 'publisher_comments:api:comments' comment.id %}" class="comment-edit">Edit</a>
This should be a button rather than an anchor tag. We aren't using this `href` to actually link to that location.
The api path should be added as a data attribute.

2016-12-16 07:25 UTC, tasawernawaz commented
@bderusha Your feedback is addressed, Please review again.

2016-12-16 13:16 UTC, awais786 requested changes

2016-12-16 13:16 UTC, awais786 commented on course_discovery/static/js/publisher/comments.js
> +            alert("unable to edit");
Instead of alert show some kind of message.

2016-12-16 13:16 UTC, awais786 commented on course_discovery/templates/publisher/course_run_detail.html
> +    <script src="https://raw.githubusercontent.com/phstc/jquery-dateFormat/master/dist/jquery-dateFormat.min.js"></script>
Don't need this. Don't ned to update the time after editing when ever user loads the page datetime will come from db

2016-12-16 13:16 UTC, awais786 commented on course_discovery/static/js/publisher/comments.js
> +            //format datetime e.g. Dec. 15, 2016, 10:03 a.m.
I think this can be remove.

2016-12-16 13:46 UTC, awais786 commented
@tasawernawaz I made few changes please review them.

2016-12-16 14:15 UTC, tasawernawaz commented on course_discovery/templates/publisher/course_run_detail.html
> +    <script src="https://raw.githubusercontent.com/phstc/jquery-dateFormat/master/dist/jquery-dateFormat.min.js"></script>
We need to update both the comment and datetime without loading the whole page that is the purpose here to use AJAX call, otherwise user cant see updated comment until he reloads the page. @awais786

2016-12-16 14:15 UTC, tasawernawaz commented on course_discovery/static/js/publisher/comments.js
> +            //format datetime e.g. Dec. 15, 2016, 10:03 a.m.
we need this to show datetime in similar format.

2016-12-16 14:48 UTC, awais786 commented on course_discovery/templates/publisher/course_run_detail.html
> +    <script src="https://raw.githubusercontent.com/phstc/jquery-dateFormat/master/dist/jquery-dateFormat.min.js"></script>
got it

2016-12-16 20:56 UTC, awais786 commented
@bderusha Please review this PR.

2016-12-20 11:02 UTC, awais786 approved these changes

2016-12-20 11:03 UTC, tasawernawaz commented
@bderusha I am waiting for your feedback on this PR.

2016-12-20 20:19 UTC, bderusha approved these changes

2016-12-21 04:55 UTC, merged