Tasawer/ecom 6526 email on comment update
openedx/course-discovery pull request #495
Opened 2016-12-16 09:28 UTC by tasawernawaz

[ECOM-6526](https://openedx.atlassian.net/browse/ECOM-6526)

Email notifications will be sent out after successful update comment.

2016-12-16 12:05 UTC, tasawernawaz commented
Please review this @waheedahmed @bderusha

2016-12-16 20:56 UTC, awais786 commented
@bderusha Please review this PR.

2016-12-19 20:17 UTC, bderusha requested changes

2016-12-19 20:17 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +        users_list_perms = get_users_with_perms(self)
Are we addressing the fact that we shouldn't be sending emails to users based on permission in another story?

2016-12-19 20:17 UTC, bderusha commented on course_discovery/apps/publisher_comments/emails.py
> +            subject = _('{subject_desc} in course run: {title}-{pacing_type}-{start}').format(
Please include a translators note here describing what all of the variables are

2016-12-19 20:17 UTC, bderusha commented on course_discovery/apps/publisher_comments/emails.py
> +            subject = _('{subject_desc} in Course: {title}').format(
add translator's comment

2016-12-19 20:17 UTC, bderusha commented on course_discovery/apps/publisher_comments/models.py
> +        send_email_for_comment(instance, kwargs.get('created', True))
Just wondering if there is a particular reason why this defaults to `True`.  Either is fine, just wondering really

2016-12-20 10:25 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +        users_list_perms = get_users_with_perms(self)
Yes in this story we are not sending emails to the users depending upon the group. But in other story we will do the complete cleanup.

2016-12-20 10:27 UTC, tasawernawaz commented on course_discovery/apps/publisher/models.py
> +        users_list_perms = get_users_with_perms(self)
Yes this story is only responsible for sending email on updating comments. Link: https://openedx.atlassian.net/browse/ECOM-6628

2016-12-20 11:01 UTC, awais786 commented on course_discovery/apps/publisher_comments/models.py
> +        send_email_for_comment(instance, kwargs.get('created', True))
Signals send keyword arguments and in case of new object dict will be {'created': True} otherwise it will be false.

2016-12-20 11:01 UTC, awais786 approved these changes

2016-12-20 11:04 UTC, tasawernawaz commented
@bderusha We have answered/addressed you comments, Please review it again.

2016-12-20 20:14 UTC, bderusha requested changes

2016-12-20 20:14 UTC, bderusha commented on course_discovery/apps/publisher_comments/emails.py
> +            # New comment added in course run: xyx-instructor-2016-1-1
Sorry I wasn't more clear about this.

This comment must be in a specific format to be read properly by Transifex.  `# Translators: msg`
example: https://github.com/edx/course-discovery/blob/master/course_discovery/apps/core/forms.py#L23

This way it is included in the .po file like this https://github.com/edx/course-discovery/blob/548e83e1a1cba6f350f4e5c864e737738da50ffc/course_discovery/conf/locale/en/LC_MESSAGES/django.po#L111

2016-12-20 20:14 UTC, bderusha commented on course_discovery/apps/publisher_comments/emails.py
> +            # Comment updated in Course: course name
Update comment to reflect Transifex syntax as noted above

2016-12-20 20:14 UTC, bderusha commented on course_discovery/apps/publisher_comments/models.py
> +        send_email_for_comment(instance, kwargs.get('created', True))
@awais786 so then if `created` does not exist in `kwargs` shouldn't we default to `False` because we havent been explicitly told that it was created?

2016-12-21 08:29 UTC, tasawernawaz commented
@bderusha Feedback addressed, Please review.

2016-12-21 14:33 UTC, bderusha approved these changes

2016-12-21 14:52 UTC, merged