Added searchable courseruns filter
openedx/course-discovery pull request #496
Opened 2016-12-16 10:39 UTC by ahsan-ul-haq

Added searchable filter for course runs so we can use to send data to the sailthru. Related to https://github.com/edx/ecommerce-scripts/pull/34

2016-12-16 13:30 UTC, clintonb requested changes

2016-12-16 13:30 UTC, clintonb commented on course_discovery/apps/course_metadata/query.py
> +    def searchable(self):
Remove this.

2016-12-16 13:30 UTC, clintonb commented on course_discovery/apps/api/filters.py
> +    searchable = django_filters.MethodFilter()
This should be a filter on the hidden flag. See https://django-filter.readthedocs.io/en/latest/. We should prefer to use composition—`?active=1&marketable=1&hidden=0`—when possible rather than completely customized filters. The customization in the case of `active` and `marketable` is only there because those filters are complex and potentially the most-requested.

In this case, we only need to exclude hidden courses. There is no reason to add additional complexity.

2016-12-19 12:37 UTC, ahsan-ul-haq commented
@clintonb please review

2016-12-19 15:33 UTC, mikedikan requested changes

2016-12-19 15:33 UTC, mikedikan commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +    def test_filter_by_hidden(self):
Please add tests for if flag isn't present in request, to make sure hidden runs are still returned - this default behavior needs to be maintained.

2016-12-20 09:52 UTC, ahsan-ul-haq commented
@mikedikan I have updated the test

2016-12-20 13:18 UTC, ahsan-ul-haq commented
@rock345

2016-12-20 19:23 UTC, ahsan-ul-haq commented
@clintonb @mikedikan please review

2016-12-20 21:30 UTC, mikedikan approved these changes
Thanks!

2016-12-20 22:01 UTC, clintonb requested changes

2016-12-20 22:01 UTC, clintonb commented on course_discovery/apps/api/v1/views/course_runs.py
> +        hidden = self.request.query_params.get('hidden', None)
Update CourseRunFilter. We should not be writing custom filters when we have a library that will do this for us.

2016-12-21 11:20 UTC, ahsan-ul-haq commented
@clintonb made the suggested change

2016-12-21 15:53 UTC, clintonb approved these changes

2016-12-21 15:53 UTC, clintonb commented on course_discovery/apps/api/filters.py
> +    hidden = django_filters.BooleanFilter(name='hidden')
I don't think this line is necessary.

2016-12-21 15:53 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        """ Verify the endpoint filters course runs to those that are searchable. """
Correct this.

2016-12-21 15:53 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        url = reverse('api:v1:course_run-list') + '?hidden=False'
If you invert your test order (test the default case first) this will look less like a wall of text. A beeline between the setup (variable creation), and each condition will also help.

2016-12-21 15:53 UTC, clintonb commented on course_discovery/apps/api/v1/views/course_runs.py
> +              description: Filter by hidden
Filter based on wether the course run is hidden from search.

2016-12-21 17:29 UTC, merged