ignore for now
openedx/course-discovery pull request #499
Opened 2016-12-19 19:30 UTC by MatthewPiatetsky

[WIP] ECOM-5562 Update program alias when saving program

2016-12-19 22:50 UTC, clintonb commented
Something went wrong with the language update here. You should not be changing every single language.

2016-12-19 22:55 UTC, MatthewPiatetsky commented
yeah I put it in separate commit because it seemed odd, if I remove that what are the correct commands I should run?

2016-12-19 22:57 UTC, clintonb commented
See https://openedx.atlassian.net/wiki/display/ECOM/Automated+Translation+Management.

2016-12-19 23:04 UTC, rlucioni commented
@MatthewPiatetsky to add to what @clintonb said: it looks like you're trying to update the source translation file, but you downloaded translated files from Transifex instead. See the first section in the link @clintonb posted, "Keeping master's source translation files current."

2016-12-19 23:19 UTC, clintonb commented on course_discovery/apps/course_metadata/publishers.py
> +            raise ProgramPublisherException("Marketing site alias form retrieval failed!")
Single quotes.

2016-12-19 23:19 UTC, clintonb commented on course_discovery/apps/course_metadata/publishers.py
> +        if response.status_code != 200:
What happens if the alias already exists?

2016-12-19 23:19 UTC, clintonb commented on course_discovery/apps/course_metadata/publishers.py
> +        headers = self._get_headers(api_client.api_session)
This isn't necessary. The cookies are already in the session object. I suspect Drupal will interpret the content type correctly.

2016-12-19 23:19 UTC, clintonb commented on course_discovery/apps/course_metadata/publishers.py
> +        form = response.text.split('\n')
You seem to be doing a lot of what Beautiful Soup is supposed to do for us—parsing HTML.

```python
from bs4 import BeautifulSoup

form = BeautifulSoup(response.text, 'html.parser')

for field in ('form_build_id', 'form_token'):
  form_attributes[field] = soup.find('input', {'name': field}).get('value')
```

2016-12-19 23:19 UTC, clintonb commented on requirements/base.txt
> +bs4==0.0.1
`beautifulsoup4==4.5.1`

2016-12-19 23:19 UTC, clintonb commented on course_discovery/apps/course_metadata/publishers.py
> +        alias = '{program_type}/{slug}'.format(program_type=program.type.name.lower(), slug=program.marketing_slug)
You will need to add a slug field to the `ProgramType` model. Otherwise, you will have issues with "Professional Certificate".

2016-12-19 23:19 UTC, clintonb commented on course_discovery/apps/course_metadata/publishers.py
> +            self._add_alias(api_client, program, nid)
Please rename `nid` to `node_id` here and elsewhere to avoid future confusion.

2016-12-19 23:19 UTC, clintonb commented on course_discovery/apps/course_metadata/publishers.py
>  import requests
This is a third-party library, and should be grouped accordingly.

2016-12-20 17:43 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
> +            raise ProgramPublisherException("Marketing site alias form retrieval failed!")
fixed

2016-12-20 17:43 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
> +        form = response.text.split('\n')
thanks, changed

2016-12-20 17:44 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
> +        alias = '{program_type}/{slug}'.format(program_type=program.type.name.lower(), slug=program.marketing_slug)
added

2016-12-20 17:45 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
> +        headers = self._get_headers(api_client.api_session)
yeah not sure why I had the cookies, but I do need the content type for it to work, maybe because the headers property on the client specifies application/json

2016-12-20 17:45 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
> +            self._add_alias(api_client, program, nid)
changed

2016-12-20 17:45 UTC, MatthewPiatetsky commented on requirements/base.txt
> +bs4==0.0.1
changed

2016-12-20 18:48 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
> +        if response.status_code != 200:
I've added a check to only add the alias if the alias changed. 
The slug field in the model being unique should mean there aren't duplicate aliases. 
This wouldn't necessarily cover the case of changing an alias and changing it back. If you're trying to create an alias for the same object it will delete the old one
<img width="1009" alt="screen shot 2016-12-20 at 1 46 43 pm" src="https://cloud.githubusercontent.com/assets/5958221/21363531/f415b8a6-c6ba-11e6-8b6f-89ca58dd5090.png">

2016-12-20 18:48 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
>  import requests
changed

2016-12-20 18:56 UTC, MatthewPiatetsky commented
@clintonb @rlucioni I removed the translations changes and ran fake_translations and got this again. It seems like something with the date may be changing?

2016-12-21 21:50 UTC, mikedikan requested changes

2016-12-21 21:50 UTC, mikedikan commented on course_discovery/apps/course_metadata/publishers.py
>              # Currently, we should not publish any programs that are not MicroMasters types to Marketing Site
update comment

2016-12-21 21:50 UTC, mikedikan commented on course_discovery/apps/course_metadata/publishers.py
> +        # Drupal do not allow us to update the UUID field on node update
do->does

2016-12-21 21:50 UTC, mikedikan commented on course_discovery/apps/course_metadata/publishers.py
> +        node_url = '{root}/node.json/{node_id}'.format(root=api_client.api_url, node_id=node_id)
👍

2016-12-21 21:50 UTC, mikedikan commented on course_discovery/apps/course_metadata/publishers.py
> +            raise ProgramPublisherException('Marketing site alias creation failed!')
did you test what happens if you change alias and then change back to original?

2016-12-21 21:50 UTC, mikedikan commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +        self.mock_add_alias(500)
does drupal return a 500 if you try to add an existing alias?  does it update the alias?  does it leave it alone?

2016-12-21 21:50 UTC, mikedikan commented on course_discovery/apps/course_metadata/publishers.py
> +        add_aliases_url = '{root}/admin/config/search/path/add'.format(root=api_client.api_url)
if adding alias fails, should we message the user to go to the drupal site to enter alias manually?

2016-12-21 21:55 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
> +        add_aliases_url = '{root}/admin/config/search/path/add'.format(root=api_client.api_url)
I don't know, should we?
You could say the same thing for the rest of the publishing process (currently it just fails).
Is this a product question?

2016-12-21 21:56 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +        self.mock_add_alias(500)
I believe if you try to add an alias for the same node and it already has one it does this
https://github.com/edx/course-discovery/pull/499#discussion_r93299759

2016-12-21 21:56 UTC, mikedikan commented on course_discovery/apps/course_metadata/publishers.py
> +        add_aliases_url = '{root}/admin/config/search/path/add'.format(root=api_client.api_url)
i think it is ultimately a product question - do you want to ping jasper?

2016-12-21 21:58 UTC, mikedikan commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +        self.mock_add_alias(500)
got it, thanks.  so under what circumstances will we see a 500?  what if someone added an alias in drupal and not in django (pointing to a different node)

2016-12-21 22:21 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
> +        add_aliases_url = '{root}/admin/config/search/path/add'.format(root=api_client.api_url)
ok I asked him, I think I will update the error messages to say that you can update drupal + let ecom know

2016-12-21 22:47 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +        self.mock_add_alias(500)
In this particular case I just added a test to cover the exceptions, I wasn't thinking of a particular case. 
There are a whole bunch of possible cases we could come up with, do we really want to cover all of them?
My guess would be that we should only cover the cases of what people can do through django. In this case the marketing slug will be required and unique, so duplications should not occur.

2016-12-21 22:50 UTC, mikedikan commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +        self.mock_add_alias(500)
i guess the scenario i'm trying to illustrate is if the person attempts to enter an alias that collides with something else in drupal (maybe not even a program)  Is this not possible because all of the aliases are namespaced to start with /program_type?

2016-12-21 22:52 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
> +        add_aliases_url = '{root}/admin/config/search/path/add'.format(root=api_client.api_url)
actually nvm I don't think we want to do this, the whole publishing program process is atomic, we don't want to update drupal manually if django failed to update

2016-12-21 22:56 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +        self.mock_add_alias(500)
Yes that is correct regarding program type, so I don't think this would happen unless someone manually created an alias such as micromasters/columbiax-artificial-intelligence for something other than that (which seems unlikely)

2016-12-21 22:58 UTC, mikedikan commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +        self.mock_add_alias(500)
got it, thanks

2016-12-21 22:58 UTC, mikedikan approved these changes
lgtm

2016-12-28 17:53 UTC, rlucioni commented
The `.mo` files on this PR are the result of running Django's [`compilemessages`](https://docs.djangoproject.com/en/1.9/ref/django-admin/#compilemessages) on new `.po` files introduced by our translation management bot. The script we use updates `.po` files, but doesn't generate or commit freshly compiled `.mo` files. (Travis compiles messages when running status checks against the "update translations" PR, but those `.mo` files aren't included in the PR.)

To clean up this PR, I would create a separate commit/PR for just the `.mo` files. I will update the script we use so that `.mo` are generated, so this doesn't happen again.

2016-12-28 22:11 UTC, MatthewPiatetsky commented
@rlucioni good idea, merged pr with fake_translations off master and updated this pr

2016-12-28 22:29 UTC, rlucioni commented on course_discovery/apps/course_metadata/models.py
> +        help_text=_('Slug used to generate links to the marketing site'), unique=True, max_length=255, db_index=True)
Have you checked to see if this uniqueness constraint is going to clash with existing marketing slugs? In other words, are there any duplicates today?

2016-12-28 22:29 UTC, rlucioni commented on course_discovery/apps/course_metadata/models.py
> +    slug = AutoSlugField(populate_from='name', editable=True, blank=True,
Will this populate a slug at migration-time, or do we need to go in and fill them in manually?

2016-12-29 15:47 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    slug = AutoSlugField(populate_from='name', editable=True, blank=True,
I'm pretty sure there aren't currently any collisions, though I'm not sure how I could properly test the migration because I don't have stage or prod programs locally..maybe I can do some sort of sql dump from the read replicas and load it locally

2016-12-29 15:47 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +        help_text=_('Slug used to generate links to the marketing site'), unique=True, max_length=255, db_index=True)
I'm pretty sure there aren't currently any collisions, though I'm not sure how I could properly test the migration because I don't have stage or prod programs locally..maybe I can do some sort of sql dump from the read replicas and load it locally

2016-12-29 15:49 UTC, rlucioni commented on course_discovery/apps/course_metadata/models.py
> +        help_text=_('Slug used to generate links to the marketing site'), unique=True, max_length=255, db_index=True)
You could start by checking to see if there are any duplicates in the read replica.

2016-12-29 15:53 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +        help_text=_('Slug used to generate links to the marketing site'), unique=True, max_length=255, db_index=True)
there are not, (though i had to look manually for staging because the staging read replica script doesn't seem to be working)

2016-12-29 16:30 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    slug = AutoSlugField(populate_from='name', editable=True, blank=True,
We will need to fill them in manually, but there are only 3, so I can do this

2016-12-29 16:53 UTC, rlucioni approved these changes
Please update your commit message to include at least the ticket number. A small description of the changes contained within would be nice, too, as is our standard.

2016-12-29 21:40 UTC, MatthewPiatetsky commented
i think this branch is ready, I will do some more manual testing before merging, but won't merge until we're back from the holiday in case anything breaks

2017-01-03 16:14 UTC, merged