MicroMasters logo showing on a non-MM course discovery card
openedx/course-discovery pull request #501
Opened 2016-12-20 11:37 UTC by ahsan-ul-haq

ECOM-6372

2016-12-20 13:01 UTC, ahsan-ul-haq commented
@MatthewPiatetsky please review.

2016-12-20 13:15 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +        if not self.course.programs.filter(excluded_course_runs=self):
you can assign self.course.programs to a variable

2016-12-20 13:22 UTC, ahsan-ul-haq commented
@MatthewPiatetsky made suggested change

2016-12-20 19:23 UTC, ahsan-ul-haq commented
@MatthewPiatetsky please review

2016-12-20 20:11 UTC, MatthewPiatetsky commented
can you use django toolbar to see if this is actually increasing the number of SQL queries? let me know if you don't know how to do this

2016-12-21 11:21 UTC, ahsan-ul-haq commented
@MatthewPiatetsky, unfortunately, I don't know how to do this.

2016-12-21 16:40 UTC, MatthewPiatetsky commented
@ahsan-ul-haq 
you run ENABLE_DJANGO_TOOLBAR=1 ./manage.py runserver localhost:8008
and look at the number of SQL queries.
I looked at this branch briefly locally and it seemed like your change did not introduce additional queries that were not prefetched, despite the changes you needed in your test.
might be good for @rlucioni to check this when he gets back. in the meantime you can get another review.

👍

2016-12-29 15:47 UTC, rlucioni requested changes
Not only does this change incur many new queries on the course runs endpoint (from 22 to 61 queries, with two programs, each with two courses, each with one run), it doesn't even appear to be necessary. The filtering logic you're trying to introduce here works already, which you can verify by setting up programs as I've described above.

2016-12-29 15:47 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        self.assertEqual(response_data['results'][0].get('program_types'), [])
What's the purpose of this assertion?

2016-12-29 15:47 UTC, rlucioni commented on course_discovery/apps/course_metadata/models.py
> +        if not programs.filter(excluded_course_runs=self):
This looks wrong. What if the same course is part of two separate programs, and this course run is only excluded from one? This will filter those programs, yield the one program from which the run is excluded, and then return None, even though there is one program from which the run is not excluded (which we would expect to be returned).

2016-12-29 16:00 UTC, rlucioni commented
My earlier comment was a little premature. This excluded course run filtering is implemented by the [`CourseRunWithProgramsSerializer`](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/api/serializers.py#L387), which is why the logic at /api/v1/course_runs is already correct. I realize now that this is meant to be a fix for search. Regardless, the change proposed here introduces way to many additional queries by that endpoint. Try reproducing the query count changes locally using the debug toolbar.

2017-01-03 20:00 UTC, schenedx commented
@ahsan-ul-haq: @rlucioni is right And you are not writing the exclusion logic at the right place.
It should be excluded at the Program_types property at https://github.com/edx/course-discovery/blob/master/course_discovery/apps/course_metadata/models.py#L382

Also, you should evaluate the query count increase to figure out if we can above the query count increase by using the Django_Toolbar. See instructions provided by @MatthewPiatetsky

2017-01-03 20:01 UTC, schenedx requested changes
The update should be at https://github.com/edx/course-discovery/blob/master/course_discovery/apps/course_metadata/models.py#L382 instead

2017-01-17 17:51 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +        all_programs = []
A better name for this variable is `associated_programs`

2017-01-17 17:52 UTC, schenedx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        self.assertEqual(response_data['results'][0].get('program_types'), [])
This is to ensure the program excluded course run do not have any `program_types` associated

2017-01-17 17:55 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +            if self not in program.excluded_course_runs:
According to travis unit tests, you cannot do this line. The is was `TypeError: argument of type 'ManyRelatedManager' is not iterable`. Basically, you cannot apply keyword `in` with `excluded_course_runs` object because `excluded_course_runs` object is a `ManyrelatedManager`, not a iterable array.

2017-01-17 17:55 UTC, schenedx requested changes
Please fix the error.

2017-01-18 11:15 UTC, ahsan-ul-haq commented
@schenedx @rlucioni made the suggested changes please take a look.

2017-01-18 15:23 UTC, schenedx approved these changes
👍

2017-01-18 16:06 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        response_data = json.loads(response.content.decode('utf-8'))
Use `response.json()`.

2017-01-18 16:06 UTC, rlucioni commented on course_discovery/apps/course_metadata/models.py
> +            if self not in program.excluded_course_runs.all():
@ahsan-ul-haq have you used the debug toolbar to look at the impact this change will have on queries made by this endpoint? I don't see any prefetching being done here, so I'm concerned that this will introduce many new queries that will impact the performance of endpoints using this property.

2017-01-20 14:29 UTC, ahsan-ul-haq commented
@rlucioni please review

2017-01-20 21:13 UTC, rlucioni commented on course_discovery/apps/course_metadata/models.py
> +        for program in self.programs.exclude(status__in=program_statuses_to_exclude,):
Nitpick: remove the trailing comma.

2017-01-20 21:13 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        with self.assertNumQueries(9):
@ahsan-ul-haq including this assertion is good, but it's not sufficient on its own. What was the query count before your change? How does it scale as the number of programs and course runs increases? We have nearly a hundred programs and thousands of course runs in production. Something small like this can have a big impact in that case.

I'll repeat what I wrote below: have you used the debug toolbar to look at the impact this change will have on queries made by this endpoint? I don't see any prefetching being done here, so I'm concerned that this will introduce many new queries that will impact the performance of endpoints using this property.

2017-01-20 21:39 UTC, ahsan-ul-haq commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        with self.assertNumQueries(9):
@rlucioni I have checked that and it seems like there is only increase of one query per record.

2017-01-20 21:44 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        with self.assertNumQueries(9):
@ahsan-ul-haq what data were you testing with? Were you using the debug toolbar or relying on this assertion? The query count change may only appear to be one if you only have one program with one course and one run. How do things change if you use multiple programs, each with multiple courses, each with multiple runs?

2017-01-20 21:47 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        with self.assertNumQueries(9):
@ahsan-ul-haq can you be more specific than "one query per record"? One query per program? One per course run? That aside, "one per" suggests the same query is being run repeatedly. Prefetching could limit this to a single new query.

2017-01-23 10:35 UTC, ahsan-ul-haq commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        with self.assertNumQueries(9):
I have tested with 3 programs among which 2 having 2 courses and 1 with 3 courses. Each course having 1 course_run and I excluded 4 course runs still the increase in the number of queries was of 1 query. Could you please verify that on your end as well maybe I would be doing something wrong and it would be better with two people testing this.

2017-01-23 15:17 UTC, schenedx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        with self.assertNumQueries(9):
@rlucioni In the team standup, I confirmed with @ahsan-ul-haq that he is indeed using debug tool bar to test and watch for the query count changes

2017-01-23 15:31 UTC, schenedx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        ProgramFactory(courses=[course_run.course], status=ProgramStatus.Active, excluded_course_runs=[course_run])
Can you also test the scenario where a program has more than 1 (maybe 3) course runs, and only one of the course runs is excluded?
Then call the excluded course run and ensure the NumQueries stays 9?

2017-01-24 13:15 UTC, ahsan-ul-haq commented
@schenedx added test

2017-01-24 15:01 UTC, schenedx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        self.assertNotEqual(response_data['results'][2].get('program_types'), [])
Instead of "Not Equal", is there a better assert to make sure the 'programs_types' array is not empty?

2017-01-24 15:02 UTC, schenedx commented
@rlucioni Could you please help review again?

2017-01-24 15:16 UTC, ahsan-ul-haq commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        self.assertNotEqual(response_data['results'][2].get('program_types'), [])
I can do assertFalse as well if you suggest so.

2017-01-24 17:33 UTC, schenedx approved these changes
👍

2017-01-24 18:24 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        with self.assertNumQueries(9):
You should be using ddt for this. As it is, not only have you duplicated an entire test case, it's not clear that the query counts are expected to be the same across both test cases.

2017-01-24 18:42 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        self.assertTrue(response_data['results'][2].get('program_types'))
Be explicit about what is expected. This should contain the type of the program returned by the program factory.

2017-01-24 18:43 UTC, rlucioni approved these changes
@ahsan-ul-haq your tests need some cleanup, but looks fine otherwise.

2017-01-26 09:53 UTC, merged