Publisher app: Add/Remove Permissions.
openedx/course-discovery pull request #502
Opened 2016-12-21 11:45 UTC by awais786

Removed the course view permissions.
Add the permission for OrganizationExtension.
Add migration for the new permission.
Fix all old tests cases.

2016-12-21 13:59 UTC, waheedahmed requested changes

2016-12-21 13:59 UTC, waheedahmed commented on course_discovery/apps/publisher/models.py
> +    VIEW_PERMISSION = 'organization_extension_access'
```ACCESS_PERMISSION = 'organization_access'```

2016-12-21 13:59 UTC, waheedahmed commented on course_discovery/apps/publisher/models.py
> +            ('organization_extension_access', 'Can access the organization related course'),
```organization_access```

2016-12-21 13:59 UTC, waheedahmed commented on course_discovery/apps/publisher/mixins.py
> +    if check_roles_access(user):
Simply ```return check_roles_access(user) or check_organization_permission(user, course)```

2016-12-21 13:59 UTC, waheedahmed commented on course_discovery/apps/publisher/models.py
>      def get_group_users_emails(self):
Change the name of this function and doc string.

2016-12-21 13:59 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +            organization_extensions = get_objects_for_user(
```
organizations = get_objects_for_user(
        user,
        OrganizationExtension.VIEW_PERMISSION,
        OrganizationExtension,
        use_groups=False,
        with_superuser=False
    ).values_list('organization')
courses = Course.objects.filter(organizations__in=organizations)

2016-12-21 14:50 UTC, waheedahmed commented
@bderusha Please review.

2016-12-21 18:20 UTC, awais786 commented
@bderusha Please review.

2016-12-21 19:28 UTC, bderusha requested changes

2016-12-21 19:28 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +    team_admin = forms.ModelChoiceField(queryset=User.objects.filter(), required=True)
Why are we filtering on nothing?  Should this be the same as above `User.objects.all()` ?

2016-12-21 19:28 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +            user.has_perm(OrganizationExtension.ACCESS_PERMISSION, org.organization_extension)
`OrganizationExtension.ACCESS_PERMISSION` is too broad of a permission.  While the current asks are this broad, I think we should be implementing more granular permissions here to prevent future rework and be more clear about exactly what views/methods/etc require what permissions.

Rather than checking `ACCESS_PERMISSION` can we pass in the appropriate permission to the method.  These should look something like `OrganizationExtension.COURSE_EDIT_PERMISSION` and `OrganizationExtension.COURSE_RUN_DELETE_PERMISSION` and `OrganizationExtension.SEAT_VIEW_PERMISSION` as appropriate

2016-12-21 19:28 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +    """ Return True if user is admin/internal user. """
Return True if user is part of a role that gives implicit access

2016-12-21 19:28 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +
`return False` rather than `None`

2016-12-21 19:28 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +def check_organization_permission(user, course):
This method is checking permissions for a course object.  We should either rename this or pass the organizations as the objects to be checked.

2016-12-21 19:28 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +def check_user_access(user, course):
currently is only checking for course objects.  We should rename or refactor.

2016-12-21 19:28 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    ACCESS_PERMISSION = 'organization_access'
Per my comment above this is too broad. We want more specific permissions like the one above `edit_course_run`

2016-12-21 19:40 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +    team_admin = forms.ModelChoiceField(queryset=User.objects.filter(), required=True)
Yes. Refactoring mistake.

2016-12-21 19:55 UTC, davec-edx commented on course_discovery/apps/publisher/migrations/0022_auto_20161221_1521.py
> +        ),
reformat please

2016-12-21 20:03 UTC, bderusha commented on course_discovery/apps/publisher/migrations/0022_auto_20161221_1521.py
> +        ),
@davec-edx This is autogenerated, so I think it's fine to leave as is

2016-12-21 20:04 UTC, davec-edx commented on course_discovery/apps/publisher/migrations/0022_auto_20161221_1521.py
> +        ),
absolutely correct, I didn't notice it was a migration.  ignore :-)

2016-12-22 07:27 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
> +            user.has_perm(OrganizationExtension.ACCESS_PERMISSION, org.organization_extension)
I have rename the permission. e.g
EDIT_COURSE_RUN = 'edit_course_run'
VIEW_COURSE_RUN = 'view_course_run'

But passing a permission to a method will be a big change. So I would suggest to create separate ticket for that change. Because with that we will have to update many views where we are checking permission in the view `ChangeStateView`.

2016-12-22 10:08 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
> +            user.has_perm(OrganizationExtension.ACCESS_PERMISSION, org.organization_extension)
Also do we need to consider multiple permissions on single view ?

2016-12-22 10:25 UTC, awais786 commented
@bderusha passing a permission to the ViewPermissionMixin is time consuming task and it should be cover in separate ticket.

2016-12-22 14:40 UTC, awais786 commented
@bderusha I have created a separate ticket here.
https://openedx.atlassian.net/browse/ECOM-6687

2016-12-22 16:24 UTC, bderusha approved these changes
Some small comments.  :shipit: once resolved.  No need for re-review

2016-12-22 16:24 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +            user.has_perm(OrganizationExtension.VIEW_COURSE_RUN, org.organization_extension)
should use the `VIEW_COURSE`

2016-12-22 16:24 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    VIEW_COURSE_RUN = 'view_course_run'
Based on our conversation this morning can we update this to be namespaced. E.G. `publisher_view_course_run`

this should probably be `publisher_view_course` based on usage

2016-12-22 16:24 UTC, bderusha commented on course_discovery/apps/publisher/models.py
>      EDIT_COURSE_RUN = 'edit_course_run'
Can you namespace this one as well while you are in here?

2016-12-22 16:24 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_utils.py
> +from course_discovery.apps.publisher.mixins import check_roles_access, check_course_organization_permission, \
Prefer `import ( )` with parens for multiline imports

2016-12-22 16:24 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +                user, OrganizationExtension.VIEW_COURSE_RUN, OrganizationExtension,
This is the correct permission.  So It looks like we need to add both `VIEW_COURSE_RUN` and `VIEW_COURSE` as permissions on the `OrganizationExtension` model

2016-12-22 16:24 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +                OrganizationExtension.VIEW_COURSE_RUN,
`VIEW_COURSE`

2016-12-27 06:57 UTC, tasawernawaz requested changes

2016-12-27 06:57 UTC, tasawernawaz commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        self.organization_extension = factories.OrganizationExtensionFactory()
If we are not using `self.organization_extension` in any test than no need to add `self` with it.

2016-12-27 06:57 UTC, tasawernawaz commented on course_discovery/apps/publisher/api/tests/test_views.py
>          # create group and add test users in the group
update comment

2016-12-27 06:57 UTC, tasawernawaz commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        self.organization_extension = factories.OrganizationExtensionFactory()
Similarly here, remove `self`

2016-12-27 06:57 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +    team_admin = forms.ModelChoiceField(queryset=User.objects.all(), required=True)
why this change ?

2016-12-27 06:57 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +    team_admin = forms.ModelChoiceField(queryset=User.objects.all(), required=True)
why this change ?

2016-12-27 06:57 UTC, tasawernawaz commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +        # add user in course-user-role table
remove redundant comment.

2016-12-27 06:57 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_utils.py
> +        organization permission on given course or user is internal or admin user.
I think this docstring needs to be updated, we are not checking for admin or internal users access.

2016-12-27 14:15 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +    team_admin = forms.ModelChoiceField(queryset=User.objects.all(), required=True)
We are not going to use staff any where now.

2016-12-27 14:15 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +    team_admin = forms.ModelChoiceField(queryset=User.objects.all(), required=True)
We are not going to use staff any where now.

2016-12-27 17:06 UTC, awais786 commented on course_discovery/apps/publisher/models.py
>      EDIT_COURSE_RUN = 'edit_course_run'
We will do this in a separate ticket. For this change we have to remove the old permission from the database with data migration.

2016-12-28 03:01 UTC, tasawernawaz approved these changes

2016-12-28 03:02 UTC, tasawernawaz commented
Remember to squash your commits.

2016-12-28 10:26 UTC, merged