Add flag to hide unpublished course runs on the course endpoint
openedx/course-discovery pull request #503
Opened 2016-12-21 20:29 UTC by MatthewPiatetsky

@edx/ecommerce  @AlasdairSwan

2016-12-21 20:37 UTC, mikedikan requested changes

2016-12-21 20:37 UTC, mikedikan commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        Verify the endpoint returns associated deleted programs
change to published/unpublished (says deleted)

2016-12-21 20:37 UTC, mikedikan commented on course_discovery/apps/api/v1/views/courses.py
> +            'published_course_runs_only': get_query_param(self.request, 'published_course_runs_only'),
why 'published_course_runs_only' instead of 'exclude_unpublished_course_runs' or changing default to excluding unpublished and make the flag 'include_unpublished_course_runs

2016-12-21 21:16 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/courses.py
> +            'published_course_runs_only': get_query_param(self.request, 'published_course_runs_only'),
there is already an existing flag for programs called published_course_runs_only

2016-12-21 21:39 UTC, mikedikan approved these changes

2016-12-22 16:16 UTC, amangano-edx commented on course_discovery/apps/api/serializers.py
> +    def get_course_runs(self, course):
Where does this get called?

2016-12-22 16:20 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +    def get_course_runs(self, course):
this is serializer magic. See other fields that use serializers.SerializerMethodField() in this file

2016-12-22 16:30 UTC, amangano-edx commented on course_discovery/apps/api/tests/test_serializers.py
> +            context={'request': self.request, 'published_course_runs_only': 1}
Why are we using 1 for published_course_runs_only instead of a bool?

2016-12-22 16:31 UTC, amangano-edx commented on course_discovery/apps/api/tests/test_serializers.py
> +        self.assertEqual(serializer.data['course_runs'], [])
Minor, but it might be nice to verify that it returns published course runs when this flag is present and only excludes those that are unpublished. As it stands, this test will pass even when all course runs are excluded.

2016-12-22 16:34 UTC, amangano-edx commented
I have limited context on this, but LGTM

2016-12-22 16:39 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> +            context={'request': self.request, 'published_course_runs_only': 1}
in this case because we were sending that from the marketing site

2016-12-22 16:42 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> +        self.assertEqual(serializer.data['course_runs'], [])
now testing both published/unpublished with/without the flag

2016-12-22 16:57 UTC, merged