Added studio instance required fields.
openedx/course-discovery pull request #506
Opened 2016-12-22 09:47 UTC by waheedahmed

[ECOM-6093](https://openedx.atlassian.net/browse/ECOM-6093)

```Course Organization/Admin``` fields will be implemented in [ECOM-6090](https://openedx.atlassian.net/browse/ECOM-6090)

![screencapture-localhost-8004-publisher-courses-new-1482399846320](https://cloud.githubusercontent.com/assets/2851134/21421507/214ddc9a-c855-11e6-8145-ec67e09bcccf.png)

2016-12-22 10:43 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +        queryset=User.objects.filter(is_staff=True),
User.objects.all().
We are not going to use is_staff any where.

2016-12-22 10:51 UTC, awais786 commented
What about if datetime not given ?

2016-12-22 10:52 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +        initial=CourseRunPacing.Self,
**Radio button - Instructor paced/Self paced - required**

I think you don't need to select using initial value.

2016-12-22 10:53 UTC, awais786 commented
Few minor things otherwise looks good.

2016-12-22 12:39 UTC, waheedahmed commented on course_discovery/apps/publisher/forms.py
> +        initial=CourseRunPacing.Self,
@awais786 I think we have to set an initial value for this, maybe to ```CourseRunPacing.Instructor``` because it was the requirement for new course-run form. We will confirm that with Deen.

2016-12-22 12:39 UTC, waheedahmed commented
@awais786 Which datetime?

2016-12-22 14:29 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +        initial=CourseRunPacing.Instructor,
For some reason last comment is not appearing. My question was do we need initial value here ?

2016-12-22 14:30 UTC, awais786 commented
Datetime for ( start date or end-date ) if user did not give any date ?
do we need to save any thing in db ?

2016-12-22 14:34 UTC, waheedahmed commented on course_discovery/apps/publisher/forms.py
> +        initial=CourseRunPacing.Instructor,
@awais786 I'll remove that.

2016-12-22 14:35 UTC, waheedahmed commented
@awais786 User has to select a start/end date, we will show an error if nothing provided.

2016-12-22 19:45 UTC, bderusha approved these changes
Once the radio buttons are defaulted to nothing selected this looks good 👍

2016-12-22 19:47 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +        initial=0,
This also shouldn't have a default selected (per our conversation this morning)

2016-12-29 18:15 UTC, awais786 commented
Radio buttons are now not selected by default.

<img width="955" alt="screen shot 2016-12-29 at 11 13 49 pm" src="https://cloud.githubusercontent.com/assets/445320/21550540/85a23d22-ce1c-11e6-9bb1-1309344b3ef4.png">

2016-12-29 18:20 UTC, tasawernawaz requested changes

2016-12-29 18:20 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +                field_classes = 'field-input input-checkbox'
why we are not using `if-elif` instead of multiple ifs.?

2016-12-29 18:20 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +    team_admin = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=True), required=True)
remove this line,  its already there https://github.com/edx/course-discovery/pull/506/files#diff-af9668030177ee3112a8eb5f7d81a484L58

2016-12-29 18:20 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
> +        created.
Please update this docstring like `Verify that without selecting radio button fields course cannot be created.`

2016-12-29 18:27 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +                field_classes = 'field-input input-checkbox'
Existing code.

2016-12-29 18:29 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +                field_classes = 'field-input input-checkbox'
We will discuss this with the actual author @waheedahmed.

2016-12-29 19:14 UTC, awais786 commented
@tasawernawaz You can review the PR again.
contacted_partner_manager has initial value as default. It's a limitation in django that if boolean field is required True then selecting No will raise the error.

2016-12-30 03:37 UTC, tasawernawaz requested changes

2016-12-30 03:37 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +        required=False,
@awais786  `contacted_partner_manager ` is required field in https://openedx.atlassian.net/browse/ECOM-6093, why you make it `False`

2016-12-30 03:38 UTC, tasawernawaz requested changes

2016-12-30 03:38 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +                field_classes = 'field-input input-checkbox'
So are we waiting for @waheedahmed on this one ?

2016-12-30 07:13 UTC, awais786 commented
@tasawernawaz this is not some thing new. Its already in code base.

2016-12-30 07:14 UTC, tasawernawaz commented
@awais786 Ok we can leave it for now.

2016-12-30 07:15 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +        required=False,
It remains required. I just gave its initial value. Its a limitation in django forms. If boolean field is required True then selecting No will raise the missing value error.

2016-12-30 07:15 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +        required=False,
Just curious about this ? other than looks LGTM.

2016-12-30 07:15 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +                field_classes = 'field-input input-checkbox'
nop. We can discuss this in separate stories. its existing code.

2016-12-30 07:16 UTC, tasawernawaz commented
@awais786 Thats what I mean, we can leave code as it is, and will discuss it later.

2016-12-30 07:18 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +        required=False,
https://docs.djangoproject.com/en/1.10/ref/forms/fields/#booleanfield

2016-12-30 07:24 UTC, tasawernawaz approved these changes

2016-12-30 09:45 UTC, awais786 commented
<img width="954" alt="screen shot 2016-12-30 at 2 43 49 pm" src="https://cloud.githubusercontent.com/assets/445320/21562912/699b850c-ce9e-11e6-960b-b5cfbd93294d.png">

2016-12-30 10:22 UTC, merged