Removed "team admin" from course model
openedx/course-discovery pull request #507
Opened 2016-12-22 11:53 UTC by tasawernawaz

[ECOM-6665](https://openedx.atlassian.net/browse/ECOM-6665)

2016-12-22 12:05 UTC, awais786 commented
Is it backward compatible ?

2016-12-22 12:22 UTC, awais786 commented
team_admin is in use at several places. It will crash the build. Please remove it from every where.

2016-12-22 19:42 UTC, bderusha commented
I agree with @awais786 all dependencies on this field must also be removed

2016-12-23 06:11 UTC, tasawernawaz commented
@bderusha @awais786 Yes you were right, initially I thought that could be done in  ECOM-6667, but now I will work on both subtasks in same PR, because both are interrelated.

2016-12-29 08:38 UTC, tasawernawaz commented on course_discovery/apps/publisher/models.py
> +        return cls.objects.get_or_create(course=course, user=user, role=role)
this method is copied from https://github.com/edx/course-discovery/pull/510/files#diff-ea7d9c84b7af3aab7f0c05a73be35752R413, will be updated with latest code there in #510

2016-12-29 10:41 UTC, tasawernawaz commented
@ziafazal Please review this.

2016-12-29 11:19 UTC, ziafazal requested changes
@tasawernawaz a couple of suggestions.

2016-12-29 11:19 UTC, ziafazal commented on course_discovery/apps/publisher/views.py
> +                    CourseUserRole.add_course_roles(course=course, user=self.request.user,
Should not here we have `team_admin_id` instead of `self.request.user`?

2016-12-29 11:19 UTC, ziafazal commented on course_discovery/templates/publisher/add_course_form.html
> +                    {% if course_form.organization.field.queryset.all|length > 1 %}
i think we should use count instead of applying length filter i.e.`field.queryset.all.count`

2016-12-29 12:43 UTC, ziafazal approved these changes

2016-12-29 13:10 UTC, awais786 approved these changes

2016-12-29 13:20 UTC, merged