ECOM-6666 front end of istitution admin
openedx/course-discovery pull request #509
Opened 2016-12-26 11:33 UTC by tasawernawaz

2016-12-27 12:06 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
>      def __init__(self, *args, **kwargs):
You don't need to do this in baseform. If you are make change in courseForm then make changes there only.

2016-12-27 12:46 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
>      def __init__(self, *args, **kwargs):
Moved in `CustomCourseForm`

2016-12-28 05:52 UTC, tasawernawaz commented
@ziafazal Please review this.

2016-12-28 09:09 UTC, ziafazal requested changes
@tasawernawaz overall LGTM just couple of suggestions.

2016-12-28 09:09 UTC, ziafazal commented on course_discovery/apps/publisher/forms.py
> +        queryset = kwargs.pop('team_admin_queryset', None)
What is the reason for this override?. I'm not sure if it is required or not.

2016-12-28 09:09 UTC, ziafazal commented on course_discovery/apps/publisher/views.py
> +        team_admin_queryset = User.objects.filter(id=self.request.POST.get('team_admin'))
This also does not make sense to me.

2016-12-28 09:09 UTC, ziafazal commented on course_discovery/static/js/publisher/publisher.js
> +    var org_id = this.value;
Can we use more safe jqeury API `$(this).value()` here?

2016-12-28 09:09 UTC, ziafazal commented on course_discovery/static/js/publisher/publisher.js
> +    $("#id_team_admin").prop("selectedIndex", 0);
What if we empty team admin drop down here instead of setting its selectedIndex to zero.

2016-12-28 09:09 UTC, ziafazal commented on course_discovery/static/js/publisher/publisher.js
> +                teamAdminDropDown.append($('<option> </option>').val(this.id).html(this.full_name));
nit: can we make it more readable?
```
 $.each(data.results, function (user) {
     teamAdminDropDown.append($('<option> </option>').val(user.id).html(user.full_name));
});
```

2016-12-28 09:54 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +        queryset = kwargs.pop('team_admin_queryset', None)
Problem is selected choice must be in choice set of `ModelChoiceField`. Thats why we need to add selected choice in the choices set of `team_admin`. If not then it will give error `selected choice is not valid choice` .

2016-12-28 09:55 UTC, tasawernawaz commented on course_discovery/apps/publisher/views.py
> +        team_admin_queryset = User.objects.filter(id=self.request.POST.get('team_admin'))
`ModelChoiceField` has `queryset` parameter for choices is by default None. After selection of team admin that admin will be sent to `Form` class to add `queryset` in choices.

2016-12-28 09:57 UTC, tasawernawaz commented on course_discovery/static/js/publisher/publisher.js
> +    $("#id_team_admin").prop("selectedIndex", 0);
`0` index will contain django empty choice e.g `--------` that will be selected, no admin will be selected on change of organization

2016-12-28 10:06 UTC, tasawernawaz commented on course_discovery/static/js/publisher/publisher.js
> +                teamAdminDropDown.append($('<option> </option>').val(this.id).html(this.full_name));
`$.each(data.results, function (index, user)` because first parameter contains index and element goes into 2nd parameter.

2016-12-28 10:10 UTC, tasawernawaz commented
@ziafazal Requested changes addressed. Please review.

2016-12-28 10:48 UTC, ziafazal approved these changes

2016-12-28 11:02 UTC, awais786 approved these changes

2016-12-28 11:29 UTC, merged