Assign Roles on course creation.
openedx/course-discovery pull request #510
Opened 2016-12-27 16:37 UTC by awais786

Assign Roles on course creation.
Redirect to course run detail page.

Ecom-6091

2016-12-27 16:37 UTC, awais786 commented
@tasawernawaz Please review this PR.

2016-12-27 16:56 UTC, davec-edx commented on course_discovery/apps/publisher/models.py
> +            CourseUserRole.add_course_roles(self, user_role.user, user_role.role)
Is having no roles in the organization a possibility or an error condition?  In other words, if .all() returns an empty list, what should we do?

2016-12-27 17:10 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +            CourseUserRole.add_course_roles(self, user_role.user, user_role.role)
If default roles exists then CourseUserRole's will be added otherwise it will do nothing.

2016-12-28 06:39 UTC, tasawernawaz requested changes
I can't see implementation for last AC in ticket
"Validate that if the Save wasn't successful, an error message is displayed. "An error occurred while saving your changes." and some useful reason for the error is displayed (ex. Server timed out)"

Is it already implemented ? If not then please update the error message.

2016-12-28 06:39 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_model.py
> +        """ Verify that method assign course-user-roles for the organization against a course. """
update docstring

2016-12-28 06:39 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_model.py
> +        )
I think assignment of role is already tested in `test_assign_roles`

2016-12-28 06:39 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
> +        response = self.client.get(reverse('publisher:publisher_course_run_detail', kwargs={'pk': course.id}))
You can put this path into variable or under a function to get url.

2016-12-28 08:54 UTC, awais786 commented
@ziafazal Please review this PR.

2016-12-28 08:55 UTC, awais786 commented
@zubair-arbi review this PR.

2016-12-28 13:27 UTC, awais786 commented
If required field missing the data. 
<img width="988" alt="screen shot 2016-12-28 at 4 22 19 pm" src="https://cloud.githubusercontent.com/assets/445320/21520890/dfa66a86-cd19-11e6-9770-117952cfdd85.png">

If error occur from server side.
<img width="989" alt="screen shot 2016-12-28 at 4 21 23 pm" src="https://cloud.githubusercontent.com/assets/445320/21520891/dfa788e4-cd19-11e6-95a6-a7304b4ade8b.png">

2016-12-28 13:45 UTC, tasawernawaz commented
@awais786 I don't think this message will be useful for enduser.

2016-12-28 14:46 UTC, zubair-arbi commented on course_discovery/apps/publisher/models.py
> +        """ Create course-user-roles for the given organization against a course. """
Please stop using this format for docstring, use this format:
```
"""
Computes the foo of a and b.
"""
```
for more details read this: http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python_guidelines.html#docstrings

2016-12-28 14:48 UTC, zubair-arbi commented on course_discovery/apps/publisher/models.py
> +        """ Create course roles .
docstring format should be:
```
def func(arg1, arg2):
    """
    Summary line.

    Extended description of function.

    Arguments:
        arg1 (int): Description of arg1
        arg2 (str): Description of arg2

    Returns:
        bool: Description of return value

    """
```

2016-12-28 14:50 UTC, zubair-arbi commented on course_discovery/apps/publisher/models.py
> +    def assign_roles(self, organization):
Rename this method to something like `assign_organization_role`

2016-12-28 14:52 UTC, zubair-arbi commented on course_discovery/apps/publisher/models.py
> +            user (:obj:`User`): User
Consider arranging arguments in alphabetical order for easy reading and editing.

2016-12-28 14:52 UTC, zubair-arbi commented on course_discovery/apps/publisher/tests/test_model.py
> +        """ Verify that method assign course-user-roles for the organization against a course. """
update docstring format and also remember to break it at 80 chars length

2016-12-28 14:54 UTC, zubair-arbi commented on course_discovery/apps/publisher/tests/test_model.py
> +        """ Verify that method created the course user role."""
which method created the course user role? try to provide method name or change the docstring.

2016-12-28 14:57 UTC, zubair-arbi commented on course_discovery/apps/publisher/tests/test_model.py
> +            self.course, self.user, PublisherUserRole.MarketingReviewer
assign `PublisherUserRole.MarketingReviewer` to some variable like `marketing_reviewer_role` and use it other places this will ensure you that same role is being used for creating and assertion, it will also help you to update the role from one place.

2016-12-28 14:59 UTC, zubair-arbi commented on course_discovery/apps/publisher/tests/test_views.py
> +        factories.OrganizationUserRoleFactory(
What is the purpose of calling factories here and for specific roles [`PartnerCoordinator`, `MarketingReviewer`] ? Maybe try adding some comment

2016-12-28 15:01 UTC, zubair-arbi commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertTrue(course.course_user_roles.all())
remove this assert as it is automatically being tested by your next line.

2016-12-28 15:04 UTC, zubair-arbi commented on course_discovery/apps/publisher/views.py
> +                # pylint: disable=no-member
remove this pylint disabling, since you are using a variable to store the exception string first instead of directly calling `messages.error()` method (in that case use string concatenation instead of using `format` to avoid pylint warning).

2016-12-28 16:51 UTC, awais786 commented on course_discovery/apps/publisher/views.py
> +                # pylint: disable=no-member
We are using this at several other places in same file. So I think we can left this as it is.

2016-12-28 18:13 UTC, awais786 commented
@tasawernawaz @zubair-arbi Please review again.

2016-12-29 06:41 UTC, zubair-arbi commented on course_discovery/apps/publisher/models.py
> +        Args:
nit `Arguments:`

2016-12-29 08:39 UTC, tasawernawaz approved these changes

2016-12-29 08:50 UTC, zubair-arbi commented
LGTM 👍

2016-12-29 08:58 UTC, zubair-arbi approved these changes

2016-12-29 11:06 UTC, merged