Basic decorator for publisher app users
openedx/course-discovery pull request #515
Opened 2016-12-30 11:08 UTC by awais786

WIP:

Ecom-6094

2016-12-30 17:10 UTC, awais786 commented
@tasawernawaz Please review.

2017-01-02 07:07 UTC, waheedahmed requested changes
Generally this looks good.

2017-01-02 07:07 UTC, waheedahmed commented on course_discovery/apps/publisher/utils.py
> +def require_is_publisher_user(func):
```publisher_user_required```

2017-01-02 07:07 UTC, waheedahmed commented on course_discovery/apps/publisher/utils.py
> +    return login_required(wrapped)
Instead of returning ```login_required``` here you should decorate views with ```login_required``` first then decorate with ```publisher_user_required```.

2017-01-02 07:07 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +    @method_decorator(require_is_publisher_user)
```publisher_user_required```

2017-01-02 07:07 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +    @method_decorator(require_is_publisher_user)
```publisher_user_required```

2017-01-03 08:17 UTC, tasawernawaz requested changes
Both tests names are confusing `test_course_edit_page_without_admin_rights` and `test_update_course_without_admin_rights`. What is difference between update and edit course ?

2017-01-03 08:17 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_utils.py
> +        of any publisher group.
Update docstring, in this case there will be no error message.

2017-01-03 08:17 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.user.groups.add(self.internal_user_group)
Why are you adding `internal_user_group` in user groups, because in tests you need to remove in all related tests.

2017-01-03 08:17 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
>          """ Verify that non publisher admin user can't access course edit page without rights. """
Update this test name or docstring to because dosctring suggests that users are admin but don't have publisher app rights.

2017-01-03 08:17 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.user.groups.remove(self.internal_user_group)
Are admin rights and publisher app rights are different (`internal_user_group`) ?

2017-01-03 10:35 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.user.groups.add(self.internal_user_group)
Removing at one place only. But need at several places.

2017-01-03 13:07 UTC, tasawernawaz approved these changes

2017-01-03 13:26 UTC, awais786 commented
@bderusha Please review.

2017-01-03 15:33 UTC, awais786 commented
For organization groups names we can use some kind of prefix with those groups e.g Publisher_MIT etc

2017-01-03 20:48 UTC, bderusha requested changes

2017-01-03 20:48 UTC, bderusha commented on course_discovery/apps/publisher/utils.py
> +def is_publisher_user(user):
We just need to check if the user is a member of any group.  Having the list of all groups is actually counter-productive, since it won't include the course team groups

2017-01-04 09:38 UTC, awais786 commented on course_discovery/apps/publisher/utils.py
> +def is_publisher_user(user):
How can we make sure user belongs to the publishers app related group ?

2017-01-04 15:32 UTC, awais786 commented
@bderusha You can review this PR again.

2017-01-05 15:32 UTC, bderusha requested changes

2017-01-05 15:32 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_utils.py
> +        self.user.groups.add(self.internal_user_group)
this test should create a new group.  The internal_user_group has other permission things associated with it.

2017-01-05 15:32 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.user.groups.remove(self.internal_user_group)
rather than removing here prefer creating a new users with the expected permissions (or lack thereof)

2017-01-06 18:43 UTC, awais786 commented
@bderusha Please review again.

2017-01-06 18:55 UTC, bderusha approved these changes
👍 :shipit: once tests pass

2017-01-09 11:14 UTC, merged