Template added for studio instance needed
openedx/course-discovery pull request #518
Opened 2017-01-03 10:40 UTC by tasawernawaz

[ECOM-6097](https://openedx.atlassian.net/browse/ECOM-6097)

2017-01-03 14:17 UTC, tasawernawaz commented
@awais786 @waheedahmed Please review.

2017-01-04 07:09 UTC, waheedahmed requested changes
This looks good, just minor changes.

2017-01-04 07:09 UTC, waheedahmed commented on course_discovery/templates/publisher/email/studio_instance_needed.html
> +    <li>{{ course_name }}</li>
Where is the link to dashboard?
```<course name> (provide a link to the dashboard)```

2017-01-04 07:09 UTC, waheedahmed commented on course_discovery/templates/publisher/email/studio_instance_needed
> +    <li>{{ course_name }}</li>
Where is the link to dashboard?
```<course name> (provide a link to the dashboard)```

2017-01-04 07:09 UTC, waheedahmed commented on course_discovery/templates/publisher/email/studio_instance_needed
> +  <p>
Fix indentation.

2017-01-04 07:13 UTC, waheedahmed commented on course_discovery/templates/publisher/email/studio_instance_needed
> +    {% trans "Thanks," %} {{ course_team_admin_name }}
```course_team_admin_name``` on next line.

2017-01-04 07:13 UTC, waheedahmed commented on course_discovery/templates/publisher/email/studio_instance_needed.html
> +    {% trans "Thanks," %} {{ course_team_admin_name }}
Same here, ```course_team_admin_name``` on next line.

2017-01-04 07:18 UTC, tasawernawaz commented
@waheedahmed Made suggested changes.

2017-01-04 07:26 UTC, waheedahmed commented on course_discovery/templates/publisher/email/studio_instance_needed
> +{% trans "Dear," %} {{ edx_pc_name }}
Comma after PC name.

2017-01-04 07:26 UTC, waheedahmed commented on course_discovery/templates/publisher/email/studio_instance_needed.html
> +    {% trans "Dear," %} {{ edx_pc_name }}
Comma after PC name.

2017-01-04 07:27 UTC, waheedahmed approved these changes

2017-01-04 07:30 UTC, tasawernawaz commented
@bderusha Please review this.

2017-01-04 07:52 UTC, awais786 commented on course_discovery/templates/publisher/email/studio_instance_needed
> +{% load i18n %}
Whats the type of this file ?

2017-01-04 07:53 UTC, tasawernawaz commented on course_discovery/templates/publisher/email/studio_instance_needed
> +{% load i18n %}
.txt

2017-01-04 07:54 UTC, awais786 approved these changes

2017-01-05 06:50 UTC, merged