Certificate type and price fields updated
openedx/course-discovery pull request #521
Opened 2017-01-04 10:38 UTC by tasawernawaz

[ECOM-6087](https://openedx.atlassian.net/browse/ECOM-6087)

* Validate the drop down contains "Choose course type" (default value), "Audit Only", "Verified Certificate" and "Professional Education".
* Price will be required only for verified and professional education.

2017-01-04 12:54 UTC, waheedahmed requested changes

2017-01-04 12:54 UTC, waheedahmed commented on course_discovery/apps/publisher/forms.py
> +    def __init__(self, *args, **kwargs):
No need for this ```__init__()```, already being handled in ```BaseCourseForm```'s init at L17.

2017-01-04 12:54 UTC, waheedahmed commented on course_discovery/apps/publisher/forms.py
> +    type_choices = [
I think we should change the choices in model instead adding here.

2017-01-04 12:58 UTC, waheedahmed commented
And I think you also need to update the save method [here](https://github.com/edx/course-discovery/blob/c13f0849407917112c293e70179a193c3bbfecc9/course_discovery/apps/publisher/forms.py#L174-L187).

2017-01-04 13:03 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +    type_choices = [
We need a Choicefield because modelChoiceField requires queryset. Can we get choices of a field as queryset ?

2017-01-04 13:06 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +    def __init__(self, *args, **kwargs):
I used it here because we are not adding class `input-select` for `ChoiceField` so make it similar to other dropdown I used it here. The reason why I did not change in base class is other `ChoiceFields` in form have only two values and are shown as radio buttons. But in this case we have a dropdown of `ChoiceField` so I need to override `__init__` here.

2017-01-04 13:23 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +    def __init__(self, *args, **kwargs):
This method updated to add `empty_label` for Seat Type dropdown.

2017-01-04 13:28 UTC, waheedahmed requested changes

2017-01-04 13:28 UTC, waheedahmed commented on course_discovery/apps/publisher/models.py
>          (VERIFIED, _('Verified')),
```Verified Certificate```

2017-01-04 13:30 UTC, waheedahmed commented on course_discovery/apps/publisher/forms.py
> +    def __init__(self, *args, **kwargs):
Looks good now 👍.

2017-01-04 14:21 UTC, waheedahmed commented on course_discovery/apps/publisher/forms.py
> +    type_choices = [
```TYPE_CHOICES```

2017-01-04 14:22 UTC, waheedahmed approved these changes
One minor comment, otherwise looks good 👍

2017-01-04 14:29 UTC, tasawernawaz commented
@bderusha Please review this.

2017-01-05 15:07 UTC, bderusha approved these changes

2017-01-05 16:13 UTC, merged