WL-914 | Added staff members in Course data loader.
openedx/course-discovery pull request #522
Opened 2017-01-04 11:49 UTC by hasnain-naveed

@douglashall @afzaledx

2017-01-04 13:54 UTC, clintonb requested changes

2017-01-04 13:54 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            person, created = Person.objects.update_or_create(
This will always create a new object. The unique key is UUID. If you want to load people from LMS, you will need to add a UUID field there. You will also need to ensure any instructors defined for edx.org have the UUID back-populate with the value pulled from the marketing site.

2017-01-04 13:54 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        defaults['staff'] = self._update_or_create_course_staff(body["instructor_info"])
Single quotes. Also, you don't want to do this if a marketing site is in use.

2017-01-04 14:16 UTC, davec-edx commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            staff_list.append(person)
We're doing several things here without any exception handling at this level. Does it create a problem if we fail in the middle of the list of staff members and have created/updated some but not all?

2017-01-04 18:06 UTC, douglashall commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        validated_data['staff'] = self._update_or_create_course_staff(body["instructor_info"])
Can we move this [inside](https://github.com/edx/course-discovery/pull/522/files#diff-b225ce3f72b8695dadd76de7d8f77aacR206) `formate_course_run_data` under the marketing_site check?

2017-01-04 18:07 UTC, douglashall commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        defaults['staff'] = self._update_or_create_course_staff(body["instructor_info"])
Same as above, move inside `format_course_run_data`.

2017-01-04 18:10 UTC, douglashall commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            person, created = Person.objects.update_or_create(
I think we may need the flexibility of maintaining separate `Person` objects for the same physical person across partners. Matching on partner/name makes sense to me here.

2017-01-04 18:16 UTC, douglashall commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            staff_list.append(person)
I think the only thing that could go wrong here is some kind of database connection issue which would cause more then just this function to fail. Recovering from such a failure would just be a matter of running `refresh_course_metadata` again.

2017-01-04 18:56 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            person, created = Person.objects.update_or_create(
I'm not opposed to duplicate people across partners. The issue here is that your unique key is a value that is (a) not indexed, (b) not unique, and (c) not constant. Names change. UUIDs do not. UUID is the publicly-exposed unique identifier for almost every object in this system. That field must be used to avoid issues with subsequent runs of the data loaders.

Also, empty string is not a sane default. At some point we need to enforce a minimum amount of information for each `Person`—full name, bio, image (maybe). If that information is not available, the `Person` should not be imported. I'd rather have no information than incomplete information.

2017-01-04 19:03 UTC, douglashall commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            person, created = Person.objects.update_or_create(
Got it. This makes sense now. Thanks for the clarification.

2017-01-25 11:55 UTC, afzaledx commented
@clintonb, can you please review this PR again? we've tried to fix the issues you raised.

2017-01-25 14:36 UTC, clintonb requested changes

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    faq = FAQSerializer()
Why is this here? [WL-914](https://openedx.atlassian.net/browse/WL-914) doesn't call for changes to the `ProgramType` model.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        if not self.partner.has_marketing_site:
Move this conditional to `_process_response`.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        if not self.partner.has_marketing_site:
Move this conditional to `_process_response`.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                    type=mode.get('name', '').lower(),
Empty string is not a safe default. If there is no value, the data should not be ingested. You should log an exception, and make sure you've updated Splunk to alert on it. If the data is bad, we don't want it in our system.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                        code=mode.get('currency', '').upper()
No empty strings.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                        'price': mode.get('price', '')
No empty strings. Also, this needs to be a `decimal` type.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                        'upgrade_deadline': mode.get('expires', ''),
This must be a `datetime` type or `None`. `str` is not valid.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                            'given_name': member.get('name', ''),
There is no need for empty strings in any of these fields. The default of `None` is valid.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                if not member.get('uuid'):
Bring this into a separate variable to avoid duplication with the line below.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                if not member.get('uuid'):
Also, considering that [WL-912](https://openedx.atlassian.net/browse/WL-912) must be merged before this PR is merged, is this check even necessary?

FYI @douglashall @hasnain-naveed the UUID back-population needs to happen for all instructors, not just those for white label.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        if organization_name or title:
Avoid giant conditional blocks like this. Your code is much more legible if you exit early. Also, there is no need to put anything besides UUID in your error messages. That's the primary key, so it's all we care about when debugging.

```python
if not organization_name and not title:
  logger.warning('Unable to create position for Person [%s]. No organization or title provided.', person.uuid)
```

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +            if title:
This conditional is not necessary.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                    key=organization_name
What is `organization_name`? The key should, ideally, be the short name (e.g. MITx) instead of the full name (e.g. Massachusetts Institute of Technology). See https://github.com/edx/course-discovery/blob/master/course_discovery/apps/course_metadata/data_loaders/api.py#L21. Also, the `name` field needs to be set.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                    key=organization_name
@douglashall @hasnain-naveed it would be ideal if your changes to the Course API incorporated the exact same data from the Organization API so that we can re-use that data loader code.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +        if organization_name or title:
Also, if no data is provided, you should remove any existing positions for the person.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/tests/mock_data.py
> +                "expires": None
At least one of your test objects needs to have this field set to a real date.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/tests/mock_data.py
> +                "expires": None
Also, where is the bad data? We should verify the data loaders behave appropriately when given non-ideal data.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/tests/test_api.py
> +        if not partner_has_marketing_site:
These assertions should not have conditionals. If there is no marketing site, don't call the function.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/tests/test_api.py
> +        if not partner_has_marketing_site:
Same as above.

2017-01-25 14:36 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0044_programtype_faq.py
> +# -*- coding: utf-8 -*-
Again, why is this model being touched? If it must be modified, let's discuss that in a separate PR. However, we should really have the discussion before any changes are made to this model.

2017-01-25 15:03 UTC, afzaledx commented on course_discovery/apps/course_metadata/migrations/0044_programtype_faq.py
> +# -*- coding: utf-8 -*-
@clintonb , we'll pull the unrelated changes to a new PR. I will try to explain why this field is being added. If you visit https://www.edx.org/micromasters/ritx-project-management and scroll down  a bit  and look at the right column, you'll see the "What is a MicroMasters Program Program?" and the copy below the question. This question+answer is related to the ProgramType and the ProgramType model had no place to hold this info.

2017-01-31 20:12 UTC, douglashall commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +                    self._populate_course_run_staff(course_run, body.get('instructor_info'))
`self._create_or_update_course_run_staff(course_run, body.get('instructor_info'))`

2017-01-31 20:13 UTC, douglashall commented on course_discovery/apps/course_metadata/data_loaders/api.py
> +    def _populate_course_run_staff(self, course_run, staff_members):
`def _create_or_update_course_run_staff(self, course_run, instructors):`

2017-02-02 02:03 UTC, douglashall commented
No longer needed.

2017-02-02 02:03 UTC, closed without merging