Awais786/ecom 6687 permissions mixins
openedx/course-discovery pull request #523
Opened 2017-01-04 19:13 UTC by awais786

WIP:

2017-01-05 14:53 UTC, awais786 commented
@bderusha @waheedahmed Please review this PR.

2017-01-05 16:29 UTC, bderusha requested changes

2017-01-05 16:29 UTC, bderusha commented on course_discovery/apps/publisher/api/permissions.py
> +        return check_roles_access(request.user)
This seems wrong.  Why is the `CanViewAssociatedCourse` class only checking roles?

2017-01-05 16:29 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +    permission_required = None
Not sure how I feel about this.  I think it would be better to have a specific view permission.

2017-01-05 16:29 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +def check_course_organization_permission(user, course, permission_required):
`permission_required` sounds like a boolean.

This should just be called `permission`

2017-01-05 16:29 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +            check_course_organization_permission(user, course, self.permission_required)
This will always return false as written.  Is that the way it is supposed to work?

2017-01-05 16:29 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_utils.py
> +    check_course_organization_permission, check_roles_access
This no longer needs to be multi-line

2017-01-05 18:03 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
> +            check_course_organization_permission(user, course, self.permission_required)
No it will not return false always. Permission will be set in the view e.g
https://github.com/edx/course-discovery/blob/master/course_discovery/apps/publisher/views.py#L243

2017-01-05 18:06 UTC, awais786 commented on course_discovery/apps/publisher/api/permissions.py
> +        return check_roles_access(request.user)
This is existing method. I just updated the name. Would you please elaborate ?

2017-01-05 18:09 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
> +    permission_required = None
Do we need multiple permissions mixin e.g 
```
    EDIT_COURSE_RUN = 'edit_course_run'
    VIEW_COURSE = 'publisher_view_course'
    VIEW_COURSE_RUN = 'publisher_view_course_run'
```

2017-01-05 19:58 UTC, awais786 commented on course_discovery/apps/publisher/api/permissions.py
> +        return check_roles_access(request.user)
Ok I got it. You mean we should check user roles only. No need to check organizationExtension permissions.

2017-01-05 20:32 UTC, awais786 commented
@bderusha Please review this again.

2017-01-05 20:37 UTC, bderusha commented on course_discovery/apps/publisher/api/permissions.py
> +        return check_roles_access(request.user)
To maintain functionality it seems like it should be checking VIEW_COURSE permission in addition to checking the role.

2017-01-05 20:37 UTC, bderusha commented on course_discovery/apps/publisher/api/permissions.py
> +        return check_roles_access(request.user)
@waheedahmed can you weigh in on this?

2017-01-05 20:43 UTC, bderusha reviewed
A few small comments.  I think this will be good to go once resolved.

2017-01-05 20:43 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +    permission = OrganizationExtension.VIEW_COURSE
I see now what you are doing.  Sorry, I think I mispoke before.  You are right that `None` is a good default.

But maybe we should add a check to make sure that `permission` is set by the view.

2017-01-05 20:43 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +        return False
Per my comment above:  I think this should raise an exception rather than just return false.  You should not be allowed to check the permission if no permission is passed

2017-01-06 02:04 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
> +        return False
Right.

2017-01-06 04:02 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
> +        return False
Or we can set the default permission. e.g
`
 permission = OrganizationExtension.VIEW_COURSE
`

2017-01-06 10:27 UTC, waheedahmed commented on course_discovery/apps/publisher/api/permissions.py
> +        return check_roles_access(request.user)
@bderusha You are right, we should check ```VIEW_COURSE``` permission along with role checking here.

2017-01-06 10:45 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
> +    permission = OrganizationExtension.VIEW_COURSE
@bderusha in that case we might need to add a permission in each view.

2017-01-06 10:45 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
> +        return False
@bderusha in that case we might need to add a permission in each view.

2017-01-06 13:39 UTC, waheedahmed commented on course_discovery/apps/publisher/mixins.py
> +    permission = OrganizationExtension.VIEW_COURSE
If we can set different permissions in views then we should rename this mixin too, with this name it looks like this is only to check view related permission.

2017-01-06 13:41 UTC, waheedahmed commented on course_discovery/apps/publisher/mixins.py
> +    permission = OrganizationExtension.VIEW_COURSE
@bderusha What do you think ^^?

2017-01-06 14:42 UTC, bderusha commented on course_discovery/apps/publisher/mixins.py
> +    permission = OrganizationExtension.VIEW_COURSE
I like the idea of making this more generic.  Going back to setting `permission = None`.  Renaming the mixin.  And having it raise an exception if you do not set the `permission` in the view

2017-01-06 18:12 UTC, awais786 commented
@bderusha Please review this PR again.

2017-01-06 18:52 UTC, bderusha approved these changes

2017-01-06 18:53 UTC, bderusha commented
Squash commits before merging.  Nice work on this!

2017-01-07 18:23 UTC, awais786 commented
@tasawernawaz @waheedahmed Please review this PR.

2017-01-07 18:29 UTC, awais786 commented
I already got 1 approval. But need 2nd approval also.

2017-01-09 08:27 UTC, waheedahmed approved these changes
Just one comment otherwise looks good 👍

2017-01-09 08:27 UTC, waheedahmed commented on course_discovery/apps/publisher/mixins.py
>  class ViewPermissionMixin(object):
I think we decided to rename this mixin to more generic name because now it can check multiple type of permissions not only the ```VIEW_COURSE``` permission.

2017-01-09 08:56 UTC, awais786 commented on course_discovery/apps/publisher/mixins.py
>  class ViewPermissionMixin(object):
@waheedahmed I will create a sub-task and do that change in separate PR. This PR already become too big so its good to merge this one and only rename in 2nd PR.

2017-01-09 09:37 UTC, merged