WIP language typeahead
openedx/course-discovery pull request #528
Opened 2017-01-05 20:22 UTC by bderusha

2017-01-06 20:54 UTC, bderusha commented
@tasawernawaz @awais786 @waheedahmed Please review

2017-01-09 14:34 UTC, tasawernawaz requested changes

2017-01-09 14:34 UTC, tasawernawaz commented on course_discovery/apps/ietf_language_tags/tests/test_lookups.py
> +from course_discovery.apps.core.tests.factories import UserFactory, USER_PASSWORD
Alphabetize Imports

2017-01-09 14:34 UTC, tasawernawaz commented on course_discovery/apps/ietf_language_tags/tests/test_lookups.py
> +        response = self.client.get(
I think we can create a separate test (using `ddt.data`) for testing `query`, because upper part of test is not related to `query` which doesn't make sense to run twice.

2017-01-09 14:34 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +                'class': 'sortable-select',
Do we this class defined already ?

2017-01-09 15:48 UTC, bderusha commented
@tasawernawaz comments addressed.  Please have another look

2017-01-09 16:39 UTC, tasawernawaz approved these changes
Just a minor change required. 👍

2017-01-09 16:39 UTC, tasawernawaz commented on course_discovery/apps/ietf_language_tags/tests/test_lookups.py
> +        # Lookup returns top 10 results by default
Please update the comment.

2017-01-09 18:07 UTC, merged