WIP Update new course page fields
openedx/course-discovery pull request #529
Opened 2017-01-05 21:43 UTC by bderusha

2017-01-09 18:28 UTC, awais786 requested changes

2017-01-09 18:28 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +        queryset=Subject.objects.all(),
This query can be called once and store in a var and use at all three places.

2017-01-09 18:28 UTC, awais786 commented on course_discovery/templates/publisher/add_course_form.html
> +                        <p>140 character limit, including spaces.</p>
140 limit need to be enforce at form level.

2017-01-09 18:28 UTC, awais786 commented on course_discovery/templates/publisher/add_course_form.html
> +                        <p>2500 character limit, including spaces.</p>
2500 limit need to be enforce also at form level.

2017-01-09 18:28 UTC, awais786 commented on course_discovery/templates/publisher/add_course_form.html
> +                        <p>200 character limit, including spaces.</p>
200 limit need to be enforce also at form level.

2017-01-09 19:42 UTC, bderusha commented on course_discovery/templates/publisher/add_course_form.html
> +                        <p>140 character limit, including spaces.</p>
It is.

2017-01-09 19:42 UTC, bderusha commented on course_discovery/templates/publisher/add_course_form.html
> +                        <p>2500 character limit, including spaces.</p>
it is. :)

2017-01-09 19:42 UTC, bderusha commented on course_discovery/templates/publisher/add_course_form.html
> +                        <p>200 character limit, including spaces.</p>
it is! :D

2017-01-12 02:06 UTC, bderusha commented
@awais786 @waheedahmed @tasawernawaz Please review

2017-01-12 07:48 UTC, waheedahmed requested changes

2017-01-12 07:48 UTC, waheedahmed commented on course_discovery/apps/publisher/forms.py
> +    # program_type = forms.MultipleChoiceField(
Remove this commented code if not needed.

2017-01-12 07:48 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +                            <li>{% trans 'Is this course a part of any programs?' %}</li>
Be consistent with single or double quotes.

2017-01-12 07:48 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +                        <p>140 character limit, including spaces.</p>
i18n support.

2017-01-12 07:48 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +                        <p>2500 character limit, including spaces.</p>
i18n support.

2017-01-12 07:48 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +                        <p>200 character limit, including spaces.</p>
i18n support.

2017-01-12 18:59 UTC, bderusha commented
@awais786 @waheedahmed comments addressed

2017-01-13 14:32 UTC, waheedahmed approved these changes

2017-01-13 20:29 UTC, merged

2017-01-14 20:33 UTC, rlucioni commented
Don't forget to delete merged branches!