Course run list widget.
openedx/course-discovery pull request #536
Opened 2017-01-09 12:47 UTC by waheedahmed

[ECOM-6043](https://openedx.atlassian.net/browse/ECOM-6043)

As a Publisher user, I would like to see the Course-run list widget so that I can see all the course-runs associated with the Parent course.

**Wireframe:** http://s2q9k4.axshare.com/#g=1&p=ecom-6339

**Screenshot:**
<img width="431" alt="screen shot 2017-01-09 at 5 11 41 pm" src="https://cloud.githubusercontent.com/assets/2851134/21767055/aaa8e984-d693-11e6-9c4d-4c8fccaa8ba6.png">

2017-01-09 13:02 UTC, waheedahmed commented
@tasawernawaz, @awais786 Please review.

2017-01-09 15:25 UTC, waheedahmed commented
@bderusha Please review.

2017-01-09 20:12 UTC, bderusha requested changes

2017-01-09 20:12 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +        return self.history.order_by('history_id').first().history_user     # pylint: disable=no-member
More reliable to use `history_date` instead of `history_id`

2017-01-09 20:12 UTC, bderusha commented on course_discovery/templates/publisher/course_detail/_widgets.html
> +<div class="approval-widget">
We need a better name for this.  This is not really part of the approval widget

2017-01-10 09:20 UTC, waheedahmed commented
@bderusha Feedback addressed, please take another look.

2017-01-10 09:34 UTC, tasawernawaz approved these changes

2017-01-10 19:28 UTC, bderusha approved these changes

2017-01-11 14:58 UTC, merged