ECOM-6793 Publish alias when creating new node
openedx/course-discovery pull request #540
Opened 2017-01-10 02:33 UTC by MatthewPiatetsky

@edx/ecommerce

2017-01-10 02:34 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
> +                api_client = self._get_api_client(program)
I'm not entirely sure why, but I don't get a node id back unless I recreate the api client. I think it may have something to do with session caching or something like that?

2017-01-10 03:25 UTC, clintonb requested changes
We should do some more investigation before adding more API calls.

2017-01-10 03:25 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +                self.assert_responses_call_count(13)
Increasing the number of API calls by over 50% seems like a bad idea.

2017-01-10 03:25 UTC, clintonb commented on course_discovery/apps/course_metadata/publishers.py
> +                api_client = self._get_api_client(program)
Session caching should not change the API response. What response is returned without these changes?

2017-01-10 05:47 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +                self.assert_responses_call_count(13)
I was getting no node_id back if I didn't recreate the session. Regardless I realized we were creating the node through the node api rather than drupal form hacking so I already had access to what I need. fixed.

2017-01-10 14:50 UTC, schenedx commented on course_discovery/apps/course_metadata/publishers.py
> +                response = self._create_node(api_client, node_data)
Instead of returning the response with `self._create_node()` function, why not make the change so the function returns `node_id` and other interesting node related information being used in this code block?

2017-01-10 16:01 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/publishers.py
> +                response = self._create_node(api_client, node_data)
@schenedx 
I'm not sure I understand your comment, the response has the node id, uuid and node url.
Are you saying to name it something else or to return those things as variables?  
I don't want to return unused variables, but I'm open to only returning the node id

2017-01-10 16:06 UTC, schenedx commented on course_discovery/apps/course_metadata/publishers.py
> +                response = self._create_node(api_client, node_data)
Just return the node_id for now is fine with me. I don't see a need to return the whole response.

2017-01-10 17:25 UTC, clintonb approved these changes

2017-01-10 17:49 UTC, schenedx approved these changes
👍  Yes. LGTM

2017-01-10 18:21 UTC, merged

2017-01-11 14:35 UTC, rlucioni commented
@MatthewPiatetsky please delete your merged branches.