In Refresh Course metadata handle wrong course id errors
openedx/course-discovery pull request #544
Opened 2017-01-10 13:51 UTC by umar-nawaz

[ECOM-6457](https://openedx.atlassian.net/browse/ECOM-6457)
Refresh Course Metadata Issues.
@schenedx @MatthewPiatetsky  Please review PR.

2017-01-10 14:54 UTC, schenedx requested changes
Please also write a unit test for this scenario

2017-01-10 14:54 UTC, schenedx commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +                logger.warning('Invalid course key [%s].', data['field_course_id'])
Once you logged the warning, should the execution continue in this function? Should we stop the code to create the course_run? Have you tested this code to ensure the data are correct?

2017-01-10 15:34 UTC, umar-nawaz commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +                logger.warning('Invalid course key [%s].', data['field_course_id'])
@schenedx you are right. Does the latest update looks better.

2017-01-10 15:37 UTC, schenedx commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +                if created:
You can wrap the try and except block just before this block, and use `created` flag to determine the validity of the database data creation.

2017-01-10 15:51 UTC, umar-nawaz commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +                if created:
@schenedx do you mean like this? 
```
try:
    course, created = self.get_or_create_course(data)
    course_run = self.create_course_run(course, data)
except InvalidKeyError:
    logger.warning('Invalid course key [%s].', data['field_course_id'])

if 'created' in locals() and created: 
    course.canonical_course_run = course_run
    course.save()
```

2017-01-10 15:53 UTC, schenedx commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +                if created:
Yes. But instead of checking whether the variable `created` exists in the `locales`, you can just initiate the variable as `False` before the try block

2017-01-10 16:44 UTC, clintonb reviewed
Why do we have invalid data on stage/production? What is being done to fix it? This treats the symptoms rather than the disease.

2017-01-11 13:20 UTC, umar-nawaz commented
@clintonb the invalid data came from marketing site. This PR would try to make itself more robust. We can create a ticket to remove such contents ([like this](https://www.edx.org/admin/content?title=derp&author=&status=0&field_course_availability_tid_op=or)) from Drupal and communicate with marketing team. Does it cover your concerns?

2017-01-11 13:36 UTC, clintonb commented
@umar-nawaz @schenedx https://openedx.atlassian.net/browse/ECOM-6809

Removing the fake data should be part of the original story. If it's a separate story/task, I fear it will never get done.

2017-01-11 15:33 UTC, schenedx requested changes
Please add unit tests

2017-01-11 15:34 UTC, schenedx commented
@clintonb I asked @umar-nawaz to also work on the subtask you created ECOM-6809 together with this PR. Please help review this PR once unit test is in place.

2017-01-11 20:27 UTC, schenedx commented on course_discovery/apps/course_metadata/data_loaders/tests/test_marketing_site.py
> +from opaque_keys import InvalidKeyError
You don't need this import

2017-01-11 20:27 UTC, schenedx commented on course_discovery/apps/course_metadata/data_loaders/tests/test_marketing_site.py
> +        {'field_course_id': 'EPtestx'}
Add more test case to use ddt.

2017-01-12 14:43 UTC, schenedx approved these changes
👍

2017-01-17 14:55 UTC, schenedx commented
@umar-nawaz Looks good to me with the new test case.

2017-01-17 15:42 UTC, umar-nawaz commented
@edx/ecommerce Anyone please help review.

2017-01-17 17:08 UTC, clintonb requested changes

2017-01-17 17:08 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +            logger.warning('Invalid course key [%s].', data['field_course_id'])
`logger.error`

2017-01-17 17:08 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +        except InvalidKeyError:
Do this exception handling in `process_node` and you can drop the if statement there.

2017-01-17 17:44 UTC, schenedx commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +        except InvalidKeyError:
That was our first implementation. But then we found that there are other exception cases during `get_or_create_course` function that we should not mask. We figure it is more specific to maintainers if we catch the error here.

2017-01-17 17:45 UTC, schenedx commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +            logger.warning('Invalid course key [%s].', data['field_course_id'])
@umar-nawaz Since we have removed all the courses that cause this issue, I am agreeing with @clintonb we should log error here now instead of just warning.

2017-01-17 18:18 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/marketing_site.py
> +        except InvalidKeyError:
If you catch InvalidKeyErrror you won't be masking anything. Returning special values to indicate an error is an anti-pattern. We have exceptions. Let's use them.

2017-01-18 13:00 UTC, umar-nawaz commented
@clintonb I have covered your requested changes, please take a look.

2017-01-18 14:20 UTC, clintonb approved these changes
Remember to squash your commits.

2017-01-18 14:20 UTC, clintonb commented on course_discovery/apps/course_metadata/data_loaders/tests/test_marketing_site.py
> +from testfixtures import LogCapture
Alphabetize

2017-01-18 16:05 UTC, merged