Fixed course listing page for pilot demo
openedx/course-discovery pull request #548
Opened 2017-01-11 07:56 UTC by tasawernawaz

[ECOM-6799](https://openedx.atlassian.net/browse/ECOM-6796)

Screenshot:

<img width="1121" alt="screen shot 2017-01-11 at 12 53 46 pm" src="https://cloud.githubusercontent.com/assets/4245618/21840098/6787f5d0-d7fd-11e6-9758-6499e414a4b7.png">

2017-01-11 09:46 UTC, tasawernawaz commented
@awais786 @bderusha Please review this.

2017-01-11 12:46 UTC, awais786 approved these changes

2017-01-11 12:46 UTC, tasawernawaz commented
@bderusha Please review this.

2017-01-12 02:40 UTC, bderusha requested changes

2017-01-12 02:40 UTC, bderusha commented on course_discovery/templates/publisher/courses.html
> +                          {#TODO this is commented only for pilot demo#}
I know we said that we should just comment this out.  But since we already have that waffle flag for hiding pilot things I think that it may make more sense to just use that

2017-01-12 09:49 UTC, tasawernawaz commented
@waheedahmed Please review this.

2017-01-12 10:18 UTC, awais786 requested changes

2017-01-12 10:18 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_views.py
> +    def test_page_with_waffle_switch(self, active):
Create two separate tests cases instead of adding If condition.

2017-01-12 16:24 UTC, bderusha approved these changes

2017-01-13 10:58 UTC, merged