Course Team groups only see the 'In Progress" Tab on the Dashboard.
openedx/course-discovery pull request #549
Opened 2017-01-11 09:35 UTC by awais786

https://openedx.atlassian.net/browse/ECOM-6795

2017-01-11 09:51 UTC, awais786 commented
@tasawernawaz Please review.

2017-01-11 12:07 UTC, tasawernawaz requested changes

2017-01-11 12:07 UTC, tasawernawaz commented on course_discovery/apps/publisher/views.py
> +        context['can_view_in_progress_tab'] = can_view_in_progress_tab
You can simply this logic like
`if mixins.check_roles_access(self.request.user):`
    `context['can_view_in_progress_tab'] = True`

by default it will be `Flase`

2017-01-11 12:07 UTC, tasawernawaz commented on course_discovery/templates/publisher/dashboard.html
> +            {% if can_view_in_progress_tab %}
`can_view_in_progress_tab` should means that user can see only in progress tab.

2017-01-11 12:26 UTC, awais786 commented
@bderusha Please review.

2017-01-11 12:44 UTC, tasawernawaz approved these changes

2017-01-12 02:38 UTC, bderusha approved these changes

2017-01-12 02:38 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +            context['can_view_all_tabs'] = True
Please chat with @tasawernawaz and agree on a consistent name for this context key

2017-01-12 11:47 UTC, merged