Address Pilot Gaps: Course Listing Page
openedx/course-discovery pull request #550
Opened 2017-01-11 11:56 UTC by tasawernawaz

[ECOM-6796](https://openedx.atlassian.net/browse/ECOM-6798)

2017-01-11 13:58 UTC, tasawernawaz commented
@bderusha Please review it.

2017-01-12 02:35 UTC, bderusha approved these changes

2017-01-12 07:30 UTC, waheedahmed requested changes

2017-01-12 07:30 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        if mixins.check_roles_access(self.request.user):
Instead doing this you can simply assign like this:
```
context['can_view_tab'] = mixins.check_roles_access(self.request.user)
```

2017-01-12 07:30 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +            context['can_view_tab'] = True
```is _internal_user```

2017-01-12 07:30 UTC, waheedahmed commented on course_discovery/templates/publisher/course_run_detail.html
> +                    {% include 'publisher/course_run_detail/_all.html' %}
Move this outside else above if, no need to add else part.

2017-01-12 08:20 UTC, tasawernawaz commented on course_discovery/apps/publisher/views.py
> +            context['can_view_tab'] = True
renamed it to 'can_view_all_tabs' like @awais786  is doing in #549

2017-01-12 08:23 UTC, tasawernawaz commented
@waheedahmed Feedback addressed you can review again.

2017-01-12 08:59 UTC, waheedahmed approved these changes

2017-01-12 09:48 UTC, merged