Making Seat optional on course-creation page.
openedx/course-discovery pull request #551
Opened 2017-01-11 12:48 UTC by awais786

Seat type and prices are marked as required=False in forms.
Hide the div in page using waffle switch. 
Add data migration to create the switch.

ECOM-6797

2017-01-11 12:49 UTC, awais786 commented
@tasawernawaz Please review.

2017-01-12 02:33 UTC, bderusha approved these changes
A couple small things then 👍

2017-01-12 02:33 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +    price = forms.DecimalField(max_digits=5, decimal_places=2, required=False, initial=0.00)
lets make the max 6 digits

2017-01-12 02:33 UTC, bderusha commented on course_discovery/apps/publisher/migrations/0026_create_switch_hide_features_for_pilot.py
> +    """Create the enable_publisher_email_notifications switch if it does not already exist."""
update doc string

2017-01-12 02:33 UTC, bderusha commented on course_discovery/apps/publisher/migrations/0026_create_switch_hide_features_for_pilot.py
> +    """Delete the enable_publisher_email_notifications switch."""
update docstring

2017-01-12 06:42 UTC, awais786 commented
@tasawernawaz @waheedahmed Please review.

2017-01-12 07:41 UTC, waheedahmed requested changes

2017-01-12 07:41 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +<div class="layout-full publisher-layout layout" style="{% if publisher_hide_features_for_pilot %}display:none;{% endif %}">
Instead adding style here you can simply add ```hidden``` class.

2017-01-12 07:41 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +        course_run = course.publisher_course_runs.all()[0]
Instead indexing use ```course.publisher_course_runs.first()```.

2017-01-12 07:42 UTC, awais786 commented on course_discovery/templates/publisher/add_course_form.html
> +<div class="layout-full publisher-layout layout" style="{% if publisher_hide_features_for_pilot %}display:none;{% endif %}">
Do you mean add a hidden class in sass ?

2017-01-12 07:43 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +<div class="layout-full publisher-layout layout" style="{% if publisher_hide_features_for_pilot %}display:none;{% endif %}">
Its already available just add it here in class attribute.

2017-01-12 07:55 UTC, waheedahmed approved these changes

2017-01-12 10:55 UTC, merged