Send email on course-creation.
openedx/course-discovery pull request #552
Opened 2017-01-11 13:58 UTC by awais786

Send email on new course creation.

ECOM-6801

2017-01-11 14:03 UTC, awais786 commented
@tasawernawaz Please review.

2017-01-12 02:46 UTC, bderusha requested changes

2017-01-12 02:46 UTC, bderusha commented on course_discovery/templates/publisher/email/course_created.html
> +         <!--Translators: It's closing of mail.-->
This message isn't showing up in the translators.  Please see the documentation for how to do this

https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#translator-comments-in-templates

2017-01-12 02:46 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_emails.py
> +        """ DRY method to assert sent email data"""
Calling a method DRY in a docstring is not really helpful documentation.  Can we update this docstring to just describe what the method does?

2017-01-13 10:54 UTC, tasawernawaz requested changes

2017-01-13 10:54 UTC, tasawernawaz commented on course_discovery/apps/publisher/emails.py
> +            course_run (CourseRun): CourseRun object
define `course` in arguments.

2017-01-13 10:54 UTC, tasawernawaz commented on course_discovery/apps/publisher/emails.py
> +        from_address = settings.PUBLISHER_FROM_EMAIL
what if `PUBLISHER_FROM_EMAIL` is not defined in settings.

2017-01-13 10:54 UTC, tasawernawaz commented on course_discovery/apps/publisher/emails.py
> +        from nose.tools import set_trace; set_trace()
remove this.

2017-01-13 10:54 UTC, tasawernawaz commented on course_discovery/apps/publisher/emails.py
> +    try:
I think we can move this `try` down where we are actually expecting exceptions.

2017-01-13 10:54 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_emails.py
> +        # assert email sent
Comment not needed

2017-01-13 10:54 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_emails.py
> +        self.group = factories.GroupFactory()
why we are creating group here ?

2017-01-13 11:29 UTC, awais786 commented on course_discovery/apps/publisher/emails.py
> +    try:
We are dealing it as a broad-exception. If any thing breaks will not send any email.

2017-01-13 11:29 UTC, awais786 commented on course_discovery/apps/publisher/emails.py
> +        from_address = settings.PUBLISHER_FROM_EMAIL
PUBLISHER_FROM_EMAIL this will come from secure vars. And it is already added by devops.

2017-01-13 15:10 UTC, awais786 commented
@tasawernawaz @bderusha Please review this PR again.

2017-01-13 16:24 UTC, awais786 commented
````
Dear John,

Tasawer created the Computer Science course in Publisher on January 13, 2017 at 15:08:45.

Please create a Studio instance for this course.

Thanks,

The edX team
````

2017-01-13 16:27 UTC, awais786 commented
Sample email
````
Dear John,

Tasawer created the Computer Science course in Publisher on January 13, 2017 at 15:08:45.

Please create a Studio instance for this course.

Thanks,

The edX team
````

2017-01-13 16:27 UTC, awais786 commented
@bderusha @tasawernawaz Please review.

2017-01-13 22:50 UTC, bderusha approved these changes

2017-01-16 07:24 UTC, tasawernawaz commented on course_discovery/apps/publisher/emails.py
> +        from_address = settings.PUBLISHER_FROM_EMAIL
:+1:

2017-01-16 07:31 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_emails.py
>          """ Verify that emails sent successfully for studio instance created."""
Email will be sent on course creation of studio instance creation ?

2017-01-16 07:35 UTC, tasawernawaz approved these changes
Do we have another sub-task to implement the final template this email? if not, please update the description of PR.

Make it sure that comments and docstrings suggests that this email is for course creation not for studio instance creation.

2017-01-16 07:35 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_emails.py
> +        """ Verify that emails for studio instance created."""
I think this email is for studio instance request which will be sent out on course creation ?

2017-01-16 08:35 UTC, awais786 commented
@tasawernawaz every thing is implemented I just updated the description.

2017-01-16 08:46 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_emails.py
>          """ Verify that emails sent successfully for studio instance created."""
@awais786 Please update this comment as well. Its a small change, but will help in future.

2017-01-17 07:31 UTC, merged