Awais786/ecom 6713 set org permissions in admin
openedx/course-discovery pull request #555
Opened 2017-01-12 13:43 UTC by awais786

WIP:

Implement Permissions assignment in admin

https://openedx.atlassian.net/browse/ECOM-6713

2017-01-12 13:44 UTC, awais786 commented
<img width="1275" alt="one" src="https://cloud.githubusercontent.com/assets/445320/21891999/2244ab1c-d8f7-11e6-9732-29ee73edb7e3.png">
<img width="1270" alt="two" src="https://cloud.githubusercontent.com/assets/445320/21892000/22460c78-d8f7-11e6-8c72-674c5ba232d7.png">

2017-01-12 15:56 UTC, awais786 commented
@bderusha @waheedahmed @tasawernawaz Please check this PR. I have implemented the guadian permissions using the default django admin customization.

2017-01-12 16:23 UTC, bderusha requested changes

2017-01-12 16:23 UTC, bderusha commented on course_discovery/apps/publisher/admin.py
> +            # remove all existing perms
Rather than blanket removing all permissions and adding some back is it much more work to calculate the diff? and create a set of permissions to remove and a set to add

2017-01-12 16:23 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_admin.py
> +        self.assertEqual(response.status_code, 200)
`assertContains` implicitly tests for 200 so this line is unnecessary

2017-01-12 17:53 UTC, awais786 commented on course_discovery/apps/publisher/admin.py
> +            # remove all existing perms
Yes its possible. I will do that.

2017-01-13 10:42 UTC, awais786 commented
<img width="1272" alt="screen shot 2017-01-13 at 3 39 15 pm" src="https://cloud.githubusercontent.com/assets/445320/21927172/c208a6d0-d9a6-11e6-8b86-bf17d6d9c23d.png">

<img width="1258" alt="screen shot 2017-01-13 at 3 39 35 pm" src="https://cloud.githubusercontent.com/assets/445320/21927178/cda5a286-d9a6-11e6-9d4f-82017e39fc29.png">

<img width="1105" alt="screen shot 2017-01-13 at 3 39 47 pm" src="https://cloud.githubusercontent.com/assets/445320/21927180/cf996e60-d9a6-11e6-85df-d33981bca850.png">

2017-01-13 10:44 UTC, awais786 commented
@bderusha admin is implemented using guaridan. Thanks to @tasawernawaz for helping out. I have removed the old existing permissions for the OrganizationExtension table.

2017-01-13 10:57 UTC, tasawernawaz approved these changes

2017-01-13 22:30 UTC, bderusha approved these changes

2017-01-17 07:53 UTC, merged