Changed the marketing_url property to use the slug from the program_t…
openedx/course-discovery pull request #556
Opened 2017-01-12 19:54 UTC by davec-edx

Changed the marketing_url property to use the slug from the program_type object instead of the name of the program_type.  Added a unittest to verify that the URL generated by the marketing_url property not only has the elements we're expecting but that it is a valid URL in general.

ECOM-6813

@edx/ecommerce

2017-01-12 19:59 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_models.py
> +class ProgramTypeTests(MarketingSitePublisherTestMixin):
I don't think we need to be testing publishing here.  
We have unit tests for that in test_publishers

2017-01-12 20:01 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    def test_marketing_url(self):
I'm not sure why we want to test this way.  
This seems like a lot of extra complexity.  
Why not just test the property directly and make sure it does the correct thing?
These are unit tests after all

2017-01-12 20:09 UTC, davec-edx commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    def test_marketing_url(self):
This will test specifically that it can generate a valid url for each data type we have.  Testing each one by hand could be done, but when we add new ones we'll have to add them here too so this is just grabbing all of them.  It is comparing the various slugs because if, for example, a slug is missing from the program_type, a URL will be generated and miss that completely and the URL could appear to be correct, doing this I think handles missing and present, correct and incorrect.

2017-01-12 20:10 UTC, davec-edx commented on course_discovery/apps/course_metadata/tests/test_models.py
> +class ProgramTypeTests(MarketingSitePublisherTestMixin):
I thought I needed to have it in order to generate the URL at the program level.

2017-01-12 20:13 UTC, mikedikan commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        self.program.partner.marketing_site_url_root = self.api_root
why set up user/pass and all that jazz?  it doesn't look like it's being used below...

2017-01-12 20:15 UTC, davec-edx commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        self.program.partner.marketing_site_url_root = self.api_root
Couple reasons: A) I wanted to make sure we're testing all types against programs and generating a URL from it.  B) Thought I needed to in order to do A based on how other unit tests were working.

2017-01-12 20:15 UTC, davec-edx commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        self.program.partner.marketing_site_url_root = self.api_root
Very likely it's there because I'm not familiar enough with that area and it is overkill.

2017-01-12 20:20 UTC, mikedikan commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        self.program.partner.marketing_site_url_root = self.api_root
let's try killing it and seeing if the tests still pass

2017-01-12 20:24 UTC, clintonb requested changes

2017-01-12 20:24 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_models.py
> +class ProgramTypeTests(MarketingSitePublisherTestMixin):
Revert. Testing should be on the `Program` model, which already has a test for the `marketing_url` property. Also, we don't necessarily need to have test cases for every one of edX's program types, so you only need to one line of the existing test: https://github.com/edx/course-discovery/blob/master/course_discovery/apps/course_metadata/tests/test_models.py#L326.

2017-01-17 15:12 UTC, davec-edx commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    def test_marketing_url(self):
Changed it so it tested just the property generation itself, not using the generated data, please take another look.

2017-01-17 15:16 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    def test_marketing_url(self):
I'm not sure what you changed, but this still seems not necessary. 
I think you just need to change the already existing test_marketing_url test inside the ProgramTests (not ProgramTypeTests)

2017-01-17 15:29 UTC, davec-edx commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    def test_marketing_url(self):
Oh!  I had added it in the tests for program types, didn't catch that you were saying it should be in the programs instead.  I see.  Ok, I adjusted that test to ensure that the slug was different than the name.

2017-01-17 15:34 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        self.program.type.slug = 'slug.goes.here'
You can make sure the program type factory creates the program type slug rather than doing it here.

2017-01-17 15:36 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_models.py
> +import urllib.parse
unused import

2017-01-17 17:13 UTC, clintonb requested changes

2017-01-17 17:13 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/factories.py
> +    slug = ''
There is no need to modify the factory. This field uses `AutoSlug`, which generates a value from the name field. https://github.com/edx/course-discovery/blob/master/course_discovery/apps/course_metadata/models.py#L596-L597

2017-01-17 19:19 UTC, clintonb approved these changes

2017-01-17 19:19 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        # Set slug to something we'll recognized so we can check that it is used and not the name
`# We set the ProgramType slug to a value that is obviously different from its name so that we can ensure the slug is being used in the URL rather than the name.

2017-01-17 19:41 UTC, merged