Make statement field in corporate endorsement not required
openedx/course-discovery pull request #562
Opened 2017-01-16 10:33 UTC by ahsan-ul-haq

ECOM-6544

2017-01-16 10:51 UTC, umar-nawaz commented
@ahsan-ul-haq These Travis tests are also failing on my PR: https://travis-ci.org/edx/course-discovery/builds/192293317

2017-01-16 11:12 UTC, ahsan-ul-haq commented
@umar-nawaz It seems like some sort of translation issue

2017-01-17 03:57 UTC, rlucioni commented
@umar-nawaz @ahsan-ul-haq keep an eye on https://github.com/edx/course-discovery/pull/568 for status on a fix for the build issue.

2017-01-17 17:56 UTC, schenedx requested changes
Can you please add a new test case to ensure we can insert null into the `statement` field?

2017-01-18 11:16 UTC, ahsan-ul-haq commented
@schenedx added test and migration please take a look

2017-01-18 15:08 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_models.py
> +    def test_null_statement(self):
This is essentially testing Django. This may be one of the few times where I say you don't need tests.

2017-01-18 15:08 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        endorsement = CorporateEndorsement.objects.create(
In the future, use a factory.

```python
endorsement = CorporateEndorsementFactory(statement=None)
self.assertIsNone(endorsement.statement)
```

2017-01-18 15:35 UTC, schenedx approved these changes
@ahsan-ul-haq The test case came out not as I expected. I was wrong to call for a test case. I agree with @clintonb. Go ahead and remove the test case and you should be 👍

2017-01-20 06:03 UTC, merged