WIP: ECOM-6051 instructor module
openedx/course-discovery pull request #575
Opened 2017-01-19 13:45 UTC by tasawernawaz

[ECOM-6051](https://openedx.atlassian.net/browse/ECOM-6051)

* Add typeahead search for instructors
* Add Instructor module on new course creation page

2017-01-20 13:09 UTC, tasawernawaz commented
@waheedahmed Please review.

2017-01-20 13:16 UTC, waheedahmed commented on course_discovery/static/sass/publisher/publisher.scss
> +    padding-left: 5px;
Add RTL support.

2017-01-20 13:17 UTC, waheedahmed commented on course_discovery/static/sass/publisher/publisher.scss
> +    padding-right: 5px;
Add RTL support.

2017-01-20 13:17 UTC, waheedahmed commented on course_discovery/static/sass/publisher/publisher.scss
> +  float: left;
Add RTL support.

2017-01-20 13:31 UTC, waheedahmed commented on course_discovery/templates/publisher/add_course_form.html
> +                  <div class="selected-instructor">
With this selected instructor's will not appear at right place, move this div inside ```<div class="col col-6 instructor-select">```.
<img width="938" alt="screen shot 2017-01-20 at 6 30 26 pm" src="https://cloud.githubusercontent.com/assets/2851134/22151132/8b621baa-df3e-11e6-8351-ed8b4d61f3ae.png">

2017-01-20 14:08 UTC, tasawernawaz commented on course_discovery/templates/publisher/add_course_form.html
> +                  <div class="selected-instructor">
this was issue due to rebase, fixed now.

2017-01-20 14:12 UTC, tasawernawaz commented
@waheedahmed Your suggestions are implemented. Please review again.

2017-01-20 14:19 UTC, waheedahmed approved these changes
Looks great, nice work!

2017-01-20 14:54 UTC, tasawernawaz commented
@bderusha Please review.

2017-01-23 17:15 UTC, bderusha requested changes

2017-01-23 17:15 UTC, bderusha commented on course_discovery/apps/course_metadata/lookups.py
> +        html_start = '''
No HTML in the views.  Please put all of this into a template and return the rendered template

2017-01-23 17:15 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +        return '<img src="{profile_image}"/><span>{full_name}</span>'.format(profile_image=obj.profile_image_url,
Same here.  Please no HTML in the view.  Extract this out into it's own small template.

2017-01-23 17:15 UTC, bderusha commented on course_discovery/apps/course_metadata/urls.py
> +    url(r'^instructor-autocomplete/$', InstructorAutoComplete.as_view(), name='instructor-autocomplete',),
`person-autocomplete`

2017-01-23 17:15 UTC, bderusha commented on course_discovery/apps/course_metadata/lookups.py
> +class InstructorAutoComplete(autocomplete.Select2QuerySetView):
Let's use the generic `PersonAutocomplete` (note the consistent lowercase 'c' in Autocomplete as well)

2017-01-23 17:15 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +class InstructorModelMultipleChoiceField(forms.ModelMultipleChoiceField):
`PersonModelMultipleChoice`

2017-01-23 17:15 UTC, bderusha commented on course_discovery/static/js/publisher/publisher.js
> +    $('.selected-instructor').append('<div class="instructor"><div><img src="' + image + '"></div><div><a id="' +
NIT:  pull HTML elements into a well named variable append that variable for better readability

2017-01-23 17:15 UTC, bderusha commented on course_discovery/static/sass/publisher/publisher.scss
> +    display: none!important;
I am wary of using `!important` to override CSS.  Why is this necessary?  Is there another way to achieve the same effect?

2017-01-24 07:47 UTC, tasawernawaz commented
@bderusha Feedback addressed, Please review again.

2017-01-25 13:39 UTC, bderusha approved these changes

2017-01-25 13:39 UTC, bderusha commented on course_discovery/apps/course_metadata/lookups.py
> +        ctx = {
NIT: full var name please `context`

2017-01-25 13:39 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +        ctx = {
NIT: full var name `context`

2017-01-25 14:01 UTC, merged