Add migration to populate ElasticsearchBoostConfig
openedx/course-discovery pull request #579
Opened 2017-01-20 18:09 UTC by amangano-edx

This PR adds a migration to populate the ElasticsearchBoostConfig with it's initial config, which was taken from production on January 20, 2017. We want to move towards updating this config via migrations instead of django admin, as doing so helps us to ensure the correct config is used in all environments.

2017-01-20 18:21 UTC, davec-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record.function_score = {
Comment says this is creating or updating...  This is replacing function_score.  Is the comment correct?

2017-01-20 18:25 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record.function_score = {
It might be a little misleading. What's happening is that it's creating or updating the ElasticsearchBoostConfig record in the DB, and replacing what's in the function_score column with the new value.

2017-01-20 18:35 UTC, davec-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record.function_score = {
I see, can you update the comment then :-)

2017-01-20 19:20 UTC, rlucioni requested changes

2017-01-20 19:20 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +def forward_func(apps, schema_editor):
Give this a name indicating what it does. For example, `create_or_update_boost_config`.

2017-01-20 19:20 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    model = apps.get_model("edx_haystack_extensions", "ElasticsearchBoostConfig")
By convention, this variable is given the same name as the model. This would become:
```py
ElasticsearchBoostConfig = apps.get_model('edx_haystack_extensions', 'ElasticsearchBoostConfig')
```
Nitpick: stick with single quotes to stay consistent with the rest of the project, here and throughout this migration.

2017-01-20 19:20 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record = model(pk=ElasticsearchBoostConfig.SINGLETON_INSTANCE_PRIMARY_KEY)
Instead of relying on a hardcoded primary key, take advantage of the fact that this is a singleton model and use `first()`:
```py
boost_config = ElasticsearchBoostConfig.objects.first()
```

2017-01-20 19:20 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +        migrations.RunPython(forward_func, migrations.RunPython.noop)
When possible, I suggest being explicit about keyword arguments to aid readability. This would make more sense to someone with less context using the full
```py
migrations.RunPython(create_or_update_boost_config, reverse_code=migrations.RunPython.noop)
```

2017-01-20 19:21 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +from __future__ import unicode_literals
We're working in Python 3 here, so this can be removed.

2017-01-20 19:24 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record = model(pk=ElasticsearchBoostConfig.SINGLETON_INSTANCE_PRIMARY_KEY)
There is nothing in the DB enforcing that there is just one row. I'm using the SINGLETON_INSTANCE_PRIMARY_KEY, which is used explicitly by `solo` to load the singleton model from the DB, to protect against the possibility that duplicate rows could have be inserted.

2017-01-20 19:25 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +from __future__ import unicode_literals
This was auto-generated, but I will remove if we're sure that it's not needed.

2017-01-20 19:27 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +from __future__ import unicode_literals
Actually, I might not have been using the course-discovery venv when I auto-generated this. I will re-generate it in the venv.

2017-01-20 19:31 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record = model(pk=ElasticsearchBoostConfig.SINGLETON_INSTANCE_PRIMARY_KEY)
I see that. This works, I just think using `first()` is cleaner. Ultimately your call, but just because the library is using a hardcoded primary key doesn't mean we have to. If I'd written the package I would have used `get()` instead of hardcoding anything.

2017-01-20 19:43 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record = model(pk=ElasticsearchBoostConfig.SINGLETON_INSTANCE_PRIMARY_KEY)
I'm not advocating using the key just because that's what the library does, I'm advocating it because I feel it is better to be explicit about which record we want to modify. 

In future versions of that library you can configure the primary key to be whatever you want, and I would encourage us to explicitly set the key if we ever upgrade.

2017-01-20 19:54 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record = model(pk=ElasticsearchBoostConfig.SINGLETON_INSTANCE_PRIMARY_KEY)
@amangano-edx we run the latest version of the library. According to the [docs](https://github.com/lazybird/django-solo#use-cases) (scroll down a bit), setting of the `singleton_instance_id` is only suggested when converting an existing model to a singleton. Otherwise, it doesn't make a difference.

2017-01-20 19:59 UTC, davec-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record = model(pk=ElasticsearchBoostConfig.SINGLETON_INSTANCE_PRIMARY_KEY)
With the current code creating a new instance of the ElasticsearchBoostConfig class.  When the save is performed, will all fields/columns be overwritten with default values?   ie, we're starting with a brand new row with all defaults, changing the function_score field, then performing a save.  Won't that lose any other field values in the db?  I would suggest using the .first as well, which will slice and only return the first object, or do a get(pk=1) if that's the preferred way.

2017-01-20 20:01 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +from __future__ import unicode_literals
Hmm, this auto-generated the same way even when within the venv. I will remove this include in any case.

2017-01-20 20:02 UTC, clintonb requested changes

2017-01-20 20:02 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +from course_discovery.apps.edx_haystack_extensions.models import ElasticsearchBoostConfig
You should not import models in migrations.

2017-01-20 20:02 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/models.py
> +    SINGLETON_INSTANCE_PRIMARY_KEY = 1
This is not necessary. Regardless of what instance you retrieve from the database, the `save()` method will always set the primary key to 1: https://github.com/lazybird/django-solo/blob/1.1.2/solo/models.py#L18.

2017-01-20 20:02 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record = model(pk=ElasticsearchBoostConfig.SINGLETON_INSTANCE_PRIMARY_KEY)
`boost_config = ElasticsearchBoostConfig.get_solo()`

2017-01-20 20:04 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record = model(pk=ElasticsearchBoostConfig.SINGLETON_INSTANCE_PRIMARY_KEY)
@clintonb that doesn't work when looking up the model from the versioned registry. None of the model methods are available, just the properties.

2017-01-20 20:08 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/models.py
> +    SINGLETON_INSTANCE_PRIMARY_KEY = 1
I prefer using the explicit primary key used by the library when looking up or creating the initial record, especially when the model methods like `get_solo` are not available, as they are not when `apps.get_model("edx_haystack_extensions", "ElasticsearchBoostConfig")` is used to lookup the model in migrations.

2017-01-20 20:08 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +from course_discovery.apps.edx_haystack_extensions.models import ElasticsearchBoostConfig
Necessary to retrieve the primary key for lookup/creation of the model.

2017-01-20 20:11 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +from __future__ import unicode_literals
Ignore this line please. It's irrelevant.

2017-01-20 20:12 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +from course_discovery.apps.edx_haystack_extensions.models import ElasticsearchBoostConfig
The versioned app registry returns a model of type `<class '__fake__.ElasticsearchBoostConfig'>`

2017-01-20 20:17 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record = model(pk=ElasticsearchBoostConfig.SINGLETON_INSTANCE_PRIMARY_KEY)
`boost_config, __ = ElasticsearchBoostConfig.objects.get_or_create(pk=1)`

I see no need for the constant.

2017-01-20 20:27 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    record = model(pk=ElasticsearchBoostConfig.SINGLETON_INSTANCE_PRIMARY_KEY)
IMO the constant better communicates what is going on here, as in the future someone might look at these migrations and question why we hardcode the value 1. It doesn't hurt anything. With that being said, if everyone really doesn't like it's use or the use of the explicit primary key in this migration file, I will change it.

2017-01-20 20:36 UTC, amangano-edx commented
@clintonb @rlucioni @davec-edx I've remove the primary key constant and made many of the other changes that were requested. Please take another look when you have a minute.

2017-01-20 20:43 UTC, davec-edx commented
Is the filename correct?  I already see a migration step 0002 -- I realize that the rest of the step is different but shouldn't this be 0003?

2017-01-20 20:44 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +    ElasticsearchBoostConfig = apps.get_model("edx_haystack_extensions", "ElasticsearchBoostConfig")
Single quotes here, and elsewhere.

2017-01-20 20:44 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +        # These values were taken from production on January 20, 2017.
Is this your new config, or the existing? This migration should include whichever configuration we want to be present after closing ECOM-6715. There's no need for a second migration.

2017-01-20 20:44 UTC, rlucioni commented
@davec-edx it's correct. The original migrations (1 and 2) were squashed. You can tell by looking the `replaces` field on `0001_squashed_0002_auto_20160826_1750.py`.

2017-01-20 20:45 UTC, clintonb commented
@davec-edx the previous two migrations were squashed. `0002_` is the correct prefix.

2017-01-20 20:45 UTC, rlucioni approved these changes

2017-01-20 20:48 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +        # These values were taken from production on January 20, 2017.
This is the existing config. A second (and third migration after Matt's changes) doesn't hurt anything. It is valuable to be able to see how the config has evolved over time in case there are any problems that need to be addressed. It is also valuable, IMO to set a common initial state before we start introducing new modifications to the config.

2017-01-20 20:50 UTC, davec-edx commented
@rlucioni @clintonb After we squash and let that go through, we don't remove the squashed commits and the 'replaces' directive?

2017-01-20 20:51 UTC, clintonb approved these changes

2017-01-20 20:52 UTC, clintonb commented
@davec-edx we will eventually. The thought was that we will give any open source users, who haven't run migrations since squashing, time to run that before we do away with them. There is no rush to get rid of them.

2017-01-23 15:15 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +                    {'filter': {'term': {'type_exact': 'micromasters'}}, 'weight': 1.0},
@amangano-edx are we sure lowercase `micromasters` is going to give us the boost we're looking for here? The [tests](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/api/v1/tests/test_views/test_search.py#L331) use camel cased `MicroMasters`.

2017-01-23 15:30 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +                    {'filter': {'term': {'type_exact': 'micromasters'}}, 'weight': 1.0},
I'm not 100% sure, but this value was pulled directly from the production config in Django admin.

2017-01-23 16:41 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +                    {'filter': {'term': {'type_exact': 'micromasters'}}, 'weight': 1.0},
I suspect this should actually be MicroMasters. Could be the config in production was wrong, if that is the case probably another good reason to have it in the migration.

2017-01-23 20:52 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +                    {'filter': {'term': {'type_exact': 'micromasters'}}, 'weight': 1.0},
This does seem to be case sensitive. Therefore, if we know that we will be storing `"MicroMasters"` in the `type_exact` field, this will need to change.

2017-01-23 21:22 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/migrations/0002_auto_20170118_1826.py
> +                    {'filter': {'term': {'type_exact': 'micromasters'}}, 'weight': 1.0},
you should change it, I have Professional Certificate on my branch

2017-01-24 14:34 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> -                             [self.serialize_course_run(course_run), self.serialize_program(program)])
Order changed here because the start date boosting config also boosts documents with a null start date.

2017-01-24 14:36 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_affiliate_window.py
> -        with self.assertNumQueries(11):
All of these query counts reduced by 3 because by default, the `solo` library saves a new record when the `ElasticsearchBoostConfig.get_solo` method is called for the first time, resulting in 3 SQL statements for `SAVEPOINT`, `INSERT`, and `RELEASE SAVEPOINT`.

2017-01-24 14:38 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
>          )
Changed the order here because this test was passing even though the boost wasn't being properly applied.

2017-01-24 16:34 UTC, MatthewPiatetsky commented
👍 once tests pass/conflicts resolved

2017-01-24 18:29 UTC, merged