Adding basic code.
openedx/course-discovery pull request #582
Opened 2017-01-23 09:25 UTC by awais786

WIP:
ECOM-6067

2017-01-23 11:50 UTC, awais786 commented
@tasawernawaz @waheedahmed Please review this PR.

2017-01-23 12:04 UTC, tasawernawaz requested changes

2017-01-23 12:04 UTC, tasawernawaz commented on course_discovery/apps/publisher/views.py
> +    UpdateCourseRunForm)
move on previous line

2017-01-23 12:04 UTC, tasawernawaz commented on course_discovery/apps/publisher/views.py
> +        user_role = CourseUserRole.objects.filter(
Why we are using `filter` here instead of `get`

2017-01-23 12:04 UTC, tasawernawaz commented on course_discovery/apps/publisher/views.py
> +                    messages.success(request, _('Course run saved successfully.'))
`Course run updated successfully.`

2017-01-23 12:04 UTC, tasawernawaz commented on course_discovery/apps/publisher/views.py
> +                logger.exception('Unable to create course run and seat for course [%s].', course_run.id)
This message should be updated because we are updating here not creating.

2017-01-23 12:04 UTC, tasawernawaz commented on course_discovery/apps/publisher/views.py
> +            'publisher_hide_features_for_pilot': waffle.switch_is_active('publisher_hide_features_for_pilot'),
where are we using this ?

2017-01-23 12:29 UTC, awais786 commented on course_discovery/apps/publisher/views.py
> +        user_role = CourseUserRole.objects.filter(
At the moment CourseTeam users can be multiple.

2017-01-23 12:29 UTC, awais786 commented on course_discovery/apps/publisher/views.py
> +            'publisher_hide_features_for_pilot': waffle.switch_is_active('publisher_hide_features_for_pilot'),
To hide the 2nd block on the add course page.

2017-01-23 13:34 UTC, tasawernawaz approved these changes

2017-01-23 13:36 UTC, awais786 commented
<img width="1175" alt="screen shot 2017-01-23 at 6 35 03 pm" src="https://cloud.githubusercontent.com/assets/445320/22205907/bd8469a4-e19a-11e6-9480-a7dd48dd1065.png">

2017-01-23 16:46 UTC, awais786 commented
![Uploading Screen Shot 2017-01-23 at 9.44.05 pm.png…]()

2017-01-23 16:48 UTC, awais786 commented
<img width="1000" alt="screen shot 2017-01-23 at 9 44 05 pm" src="https://cloud.githubusercontent.com/assets/445320/22213281/647b2bfc-e1b5-11e6-9651-f4910a768943.png">

2017-01-23 16:48 UTC, awais786 commented
@bderusha Please review this PR.

2017-01-23 17:08 UTC, awais786 commented
<img width="1271" alt="screen shot 2017-01-23 at 10 07 23 pm" src="https://cloud.githubusercontent.com/assets/445320/22214117/5c1bd544-e1b8-11e6-84ad-23767de892ce.png">

2017-01-23 17:19 UTC, awais786 commented on course_discovery/apps/publisher_comments/tests/test_views.py
> -    def test_course_run_edit_page_with_multiple_comments(self):
I have removed these tests. Now edit page has no comment functionality.

2017-01-23 19:50 UTC, awais786 commented
@bderusha Please review this PR.

2017-01-24 12:43 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +        user_role = CourseUserRole.objects.filter(
Then we should fix that instead of this using filter here. It doesn't make sense that a course can have multiple course admins.

2017-01-24 12:46 UTC, waheedahmed commented on course_discovery/static/js/publisher/publisher.js
> +    if ($(microMaster).is(':checked')) {
No need to initial it with jquery here again, you already did it at L32 ```var microMaster = $('#id_is_micromasters')```.

2017-01-24 12:46 UTC, waheedahmed commented on course_discovery/static/js/publisher/publisher.js
> +    if ($(xseries).is(':checked')) {
Same here.

2017-01-24 12:46 UTC, waheedahmed commented on course_discovery/static/js/publisher/publisher.js
> +    $(microMaster).click( function(){
Also here.

2017-01-24 12:46 UTC, waheedahmed commented on course_discovery/static/js/publisher/publisher.js
> +    $(xseries).click( function(e){
Also here.

2017-01-24 13:38 UTC, tasawernawaz approved these changes

2017-01-25 09:47 UTC, tasawernawaz commented on course_discovery/apps/publisher/views.py
> +        user_role = CourseUserRole.objects.filter(
@awais786 I think you can use this property now. https://github.com/edx/course-discovery/pull/597/files#diff-ea7d9c84b7af3aab7f0c05a73be35752R190 #597 is also merged now.

2017-01-25 13:52 UTC, bderusha requested changes

2017-01-25 13:52 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +    template_name = 'publisher/add_course_form.html'
I feel like the course run edit page should have its own template.  Why are we using the `add_course_form` here? Is this temporary?

2017-01-25 13:52 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +        ctx = self.get_context_data()
NIT: prefer `context` to abbreviated form

2017-01-25 13:52 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +        ctx['breadcrumbs'] = [
I think we can pull this breadcrumb maker into a helper function and reuse it

2017-01-25 13:52 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +        ctx = self.get_context_data()
`context`

2017-01-25 13:52 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +                    if request.POST.get('type'):
We should think about making this more readable.  It is not obvious why `type` in the POST request should lead to use saving the seat_form.  Better variable name for what is now `type`?  Maybe just a comment?

2017-01-25 13:52 UTC, bderusha commented on course_discovery/templates/publisher/add_course_form.html
We should rename this template if we are going to use it for both pages.

2017-01-25 14:16 UTC, awais786 commented on course_discovery/apps/publisher/views.py
> +    template_name = 'publisher/add_course_form.html'
This is not temporary. Same template can be use for both add and edit. Almost all things are same.

2017-01-25 14:22 UTC, awais786 commented on course_discovery/templates/publisher/add_course_form.html
Right

2017-01-25 14:48 UTC, awais786 commented
@bderusha You can review this PR again.

2017-01-25 17:41 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +class CreateCourseViewTests(TestCase):
You renamed wrong class, you need to rename this `CreateUpdateCourseRunViewTests`.

2017-01-25 18:33 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_views.py
> +class CreateCourseViewTests(TestCase):
It's intentional. I just rename this class because it will test only creation.

2017-01-25 18:34 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_views.py
> +class CreateCourseViewTests(TestCase):
`CreateUpdateCourseRunViewTests` this is not related to my PR.

2017-01-25 18:35 UTC, awais786 commented
@bderusha Please review this PR again.

2017-01-25 19:22 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +class CreateCourseViewTests(TestCase):
You moved the test's from `CreateUpdateCourseRunViewTests` not from `CreateUpdateCourseViewTests `.

2017-01-25 19:25 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +class CreateCourseViewTests(TestCase):
You implement course run edit page, according to that this class `CreateUpdateCourseRunViewTests ` name should be updated.

2017-01-25 19:38 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +class CreateCourseViewTests(TestCase):
The class you updated is related to parent course and is updated in this PR https://github.com/edx/course-discovery/pull/598.

2017-01-25 19:45 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_views.py
> +class CreateCourseViewTests(TestCase):
OK I will fix this tomorrow.

2017-01-27 03:15 UTC, bderusha approved these changes
👍 once comments addressed

2017-01-27 03:15 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +            {'url': reverse('publisher:publisher_courses'), 'slug': 'Courses'},
NIT: this would be easier to read if all of the dicts in this list looked the same

```
[
  {
    'url':...
    'slug':...
  },
  {
    'url': ...
    'slug':...  # etc
  }
]
```

2017-01-27 03:15 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +            {'url': reverse('publisher:publisher_courses'), 'slug': 'Courses'},
Additionally it would be great to pull that out into a helper method.  I think I made this comment on another PR so coordinate with @waheedahmed and @tasawernawaz if you decide to do this.

2017-01-27 03:15 UTC, bderusha commented on course_discovery/static/js/publisher/publisher.js
> +}
In general this file is starting to get pretty unwieldy.  Can you please add some comments to the methods about what each of them does

2017-01-27 07:17 UTC, awais786 commented
@waheedahmed @tasawernawaz I have make bread-crumbs helper function. Please check.

2017-01-27 07:30 UTC, waheedahmed commented
LGTM 👍

2017-01-27 11:26 UTC, merged