Ignore for now
openedx/course-discovery pull request #599
Opened 2017-01-25 19:06 UTC by MatthewPiatetsky

ECOM-4959 Enable configuration of synonyms for search and typeahead

2017-01-26 16:22 UTC, rlucioni requested changes

2017-01-26 16:22 UTC, rlucioni commented on course_discovery/settings/synonyms.txt
> +# Comments must start with this character #
I would encourage you to use YAML for this. You can then use PyYAML to load it in without having to do any custom parsing.

2017-01-26 16:22 UTC, rlucioni commented on course_discovery/settings/synonyms.py
> +with open(os.path.join(directory_path, 'synonyms.txt')) as f:
Have you tried just `open('synonyms.yml')` without this path manipulation?

2017-01-26 16:22 UTC, rlucioni commented on course_discovery/settings/base.py
> +                "snowball_with_synonyms": {
Single quotes here and everywhere, please!

2017-01-26 16:22 UTC, rlucioni commented on course_discovery/settings/base.py
> +                  'synonyms' : SYNONYMS_LIST
The linter isn't catching these because we have it configured to ignore settings files. Maybe we should change that. Run pylint against this file to catch cases like these (you have an extra space between the key and the colon).

2017-01-26 16:22 UTC, rlucioni commented on course_discovery/settings/base.py
> +from .synonyms import SYNONYMS_LIST
We use absolute paths: `from course_discovery.settings.synonyms import SYNONYMS`.

2017-01-26 16:22 UTC, rlucioni commented on course_discovery/settings/synonyms.py
> +    SYNONYMS_LIST = [line.rstrip() for line in f if line[0] != '#']
You can just use `SYNONYMS` as the variable name.

2017-01-26 16:22 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        self.assertTrue(len(response1))
Can you assert something more specific than "the response is not empty"?

2017-01-26 16:22 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +class SynonymsTestsMixin:
`SynonymTestMixin`

2017-01-26 16:22 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        authoring_organizations = [OrganizationFactory(name='Massachusetts Institute of Technology', key='MIT')]
If the synonyms file is changed, these tests may break. Is that desired?

2017-01-26 17:05 UTC, rock345 commented on course_discovery/settings/synonyms.txt
> +excel, microsoft excel
maybe add msft excel

2017-01-26 19:13 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def get_response(self, query=None, faceted=False):
Why the change?

2017-01-26 19:13 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def get_response(self, query=None, partner=None):
Why the name change?

2017-01-26 19:13 UTC, clintonb commented on course_discovery/settings/synonyms.txt
> +# Other Terms
This would be cleaner with a newline between sections, or YAML as suggested in another comment.

2017-01-26 19:13 UTC, clintonb commented on course_discovery/settings/synonyms.txt
> +react, typescript, javascript, jquery, java script
Should this be merged with the other line for "js, javascript"?

2017-01-26 19:13 UTC, clintonb commented on course_discovery/settings/synonyms.txt
> +autocad, auto cad
Also, "cad"?

2017-01-26 19:56 UTC, amangano-edx commented on course_discovery/settings/synonyms.txt
> +NYIF, New York Institute of Finance, NYIFx
It might make it easier for some people reading this file if these were sorted.

2017-01-26 20:11 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.txt
> +# Comments must start with this character #
now using yaml/pyaml

2017-01-26 20:12 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +    SYNONYMS_LIST = [line.rstrip() for line in f if line[0] != '#']
using synonyms now

2017-01-26 20:12 UTC, MatthewPiatetsky commented on course_discovery/settings/base.py
> +from .synonyms import SYNONYMS_LIST
fixed

2017-01-26 20:12 UTC, MatthewPiatetsky commented on course_discovery/settings/base.py
> +                "snowball_with_synonyms": {
fixed

2017-01-26 20:12 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +class SynonymsTestsMixin:
fixed

2017-01-26 20:13 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        authoring_organizations = [OrganizationFactory(name='Massachusetts Institute of Technology', key='MIT')]
With the current implementation I am postprocessing the file to generate synonyms. Do you think it would be worth it to define a test synonyms file that would override the synonyms of base.py? It would only break if synonyms were removed (which seems like it would be uncommon)

2017-01-26 20:14 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.txt
> +excel, microsoft excel
added

2017-01-26 20:14 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def get_response(self, query=None, faceted=False):
I am using the SynonymMixin to test both search and typeahead. I wanted to be able to get the response and assert they are equal without knowing whether I am inside search or typeahead tests

2017-01-26 20:14 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.txt
> +# Other Terms
added newlines

2017-01-26 20:14 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.txt
> +autocad, auto cad
added

2017-01-26 20:14 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.txt
> +react, typescript, javascript, jquery, java script
merged

2017-01-26 20:28 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        ProgramFactory(title='spanish and french', partner=self.partner)
Why does this only test `Program`s?

2017-01-26 20:28 UTC, MatthewPiatetsky commented
Understand the test failure, discussing with renzo (due to using wrong settings data)

2017-01-26 20:29 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +            response1, response2 = response1['objects'], response2['objects']
Is it possible for these to be empty (maybe if neither search matched)? Maybe we should also verify that they contain something?

2017-01-26 20:30 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        ProgramFactory(title=title, partner=self.partner)
Why only testing `Program`?

2017-01-26 20:32 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def get_response(self, querystring=None):
This says it takes a `String` but all the Synonym tests pass in an dictionary. Could we maybe rename this param to communicate more clearly what is expected here?

2017-01-26 20:35 UTC, amangano-edx commented on course_discovery/settings/synonyms.py
> +    return processed_synonyms
We should be able to store the synonyms in a format that does not require us to manually parse each line. Maybe CSV, YAML, or JSON would be better?

2017-01-26 20:37 UTC, clintonb requested changes

2017-01-26 20:37 UTC, clintonb commented on course_discovery/settings/synonyms.py
> +    return synonyms
Add a newline.

2017-01-26 20:37 UTC, clintonb commented on course_discovery/settings/synonyms.py
> +    file_path = join(directory_path, 'synonyms.txt')
`synonyms.yaml`

2017-01-26 20:37 UTC, clintonb commented on course_discovery/settings/synonyms.py
> +            url = '{}{}{}'.format(host, analyze_string, synonym)
Use [`urllib.parse`](https://docs.python.org/3/library/urllib.parse.html) to build URLs.

2017-01-26 20:37 UTC, clintonb commented on course_discovery/settings/synonyms.py
> +    """ This method takes list of lines (strings) in the form 'running, jogging'
Follow the docstring format at http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html.

2017-01-26 20:37 UTC, clintonb commented on course_discovery/settings/synonyms.py
> +            response = requests.get(url).json()
This has the potential to overload Elasticsearch if there are a lot of synonyms. Is there a way to batch this operation or avoid it altogether?

2017-01-26 20:37 UTC, clintonb commented on course_discovery/settings/synonyms.py
> +    file_path = join(directory_path, 'synonyms.txt')
We should use a setting (or some other editable mechanism) to define the location of this file. This should probably live in `edx_catalog_extensions`. The synonyms for edx.org may not be useful for Open edX users.

2017-01-26 20:37 UTC, clintonb commented on course_discovery/settings/synonyms.py
> +import requests
Group these appropriately.

2017-01-26 20:37 UTC, clintonb commented on course_discovery/settings/base.py
> +                  'synonyms': get_synonyms(HAYSTACK_HOST)
This will not work as expected in production, or any other environment where `HAYSTACK_HOST` is overridden. This will need to be moved to a function that is called here in `base.py` and again in `production.py`, and `local.py` _after_ `HAYSTACK_HOST` is defined.

2017-01-26 20:37 UTC, amangano-edx commented on course_discovery/settings/synonyms.py
> +        return yaml.load(f)
Why bother using YAML if each line still has to be individually parsed? I think something like CSV would be better.

2017-01-26 20:47 UTC, MatthewPiatetsky commented on course_discovery/settings/base.py
> +                  'synonyms': get_synonyms(HAYSTACK_HOST)
don't think that would work because production imports base, etc...
however, I realized I could just do this inside the update_index command

2017-01-26 20:52 UTC, rlucioni commented on course_discovery/settings/synonyms.py
> +        return yaml.load(f)
It is possible to use YAML for this without parsing each line:
```yaml
- - a
  - b
  - c
- - 1
  - 2
  - français
```
Yields:
```py
[['a', 'b', 'c'], [1, 2, 'français']]
```

2017-01-26 21:15 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +    """ This method takes list of lines (strings) in the form 'running, jogging'
I think this is a valid docstring by that format, is this comment suggesting that I describe the arguments in an attributes section or something else?

2017-01-26 21:34 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +import requests
fixed

2017-01-26 21:35 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +    return synonyms
fixed

2017-01-26 21:35 UTC, MatthewPiatetsky commented on course_discovery/settings/base.py
> +                  'synonyms': get_synonyms(HAYSTACK_HOST)
I am now doing this in update_index and core/tests/mixins

2017-01-26 21:37 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +        return yaml.load(f)
imo this version is more readable, since the line separation makes it easy to see which synonyms are grouped together. (the only postprocessing after reading the file though is splitting on comma. The bulk is parsing the response back from elasticsearch)

2017-01-26 21:43 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +            response = requests.get(url).json()
I don't think there is a bulk operation in v 1.5.2
I think we want to process these with ES to ensure we see the same behavior as when we search (as opposed to some python library).
With this implementation this will only get called when rebuilding the index, do you still think that would be a problematic amount of load?

2017-01-26 21:58 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +            url = '{}{}{}'.format(host, analyze_string, synonym)
is the change I made what you were suggesting

2017-01-26 22:00 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +    file_path = join(directory_path, 'synonyms.txt')
Could you clarify how this would work? Currently I'm calling out to the function from apps/core/utils.py and edx_haystack_extensions/management/commands/update_index.py.

2017-01-26 22:01 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.txt
> +NYIF, New York Institute of Finance, NYIFx
i sorted the lines alphabetically and change the order of some of the synonyms, sometimes i think the lines are more readable if they aren't alphabetical, but i changed this one

2017-01-26 22:02 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        ProgramFactory(title='spanish and french', partner=self.partner)
Do you think there would be value in testing both courses and programs?  
I think if I know that some synonyms work for both, it doesn't add value to run identical tests for both if we don't think there is a reason that one wouldn't work. I'm just looking at the same title field on both, not doing anything different

2017-01-26 22:08 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        response2 = self.get_response({'q': 'HTML'}).json()
The `get_response` methods all take different args and some have different names. I think we should go a little further in this refactor and change them all to have a consistent interface. Rather than `partner` as an argument for some of them and `faceted` as an argument to others, why not change them all so that they all just expect a query dictionary?

2017-01-26 23:36 UTC, clintonb requested changes

2017-01-26 23:36 UTC, clintonb commented on course_discovery/apps/core/utils.py
> +    def create_alias_and_index(cls, es, alias, host=None):
There is no need to pass `host` here. `es` is an Elasticsearch client. Use it. https://elasticsearch-py.readthedocs.io/en/master/

2017-01-26 23:36 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +    def prepare_backend_index(self, backend, host):
Again, no need for `host`. Use `backend`

2017-01-26 23:36 UTC, clintonb commented on course_discovery/settings/base.py
> +# Haystack configuration (http://django-haystack.readthedocs.io/en/v2.5.0/settings.html)
Nit: this doesn't need to be moved.

2017-01-26 23:36 UTC, clintonb commented on course_discovery/settings/synonyms.py
> +    """This method takes list of lines (strings) in the form 'running, jogging'
List the `Args` according to the link provided earlier.

2017-01-26 23:36 UTC, clintonb commented on course_discovery/settings/synonyms.py
> +def process_synonyms(host, analyze_string, synonyms):
Pass the `Elasticsearch` client and use it, rather than `requests`.

2017-01-26 23:36 UTC, clintonb commented on course_discovery/settings/synonyms.yaml
> +- usa, united states of america
Add a newline.

2017-01-27 14:05 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.yaml
> +- usa, united states of america
added

2017-01-27 14:06 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +    return processed_synonyms
This is parsing the response from es, not the file. Only line.split(', ') is parsing the file (that could be avoided, but I think the current format is much more readable)

2017-01-27 14:09 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +    """This method takes list of lines (strings) in the form 'running, jogging'
added attribuets section

2017-01-27 14:10 UTC, MatthewPiatetsky commented on course_discovery/apps/core/utils.py
> +    def create_alias_and_index(cls, es, alias, host=None):
thanks, i couldn't find the analyze api on it earlier (it was under indices for some reason which doesn't make sense since you can call it without an index)

2017-01-27 14:10 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +    def prepare_backend_index(self, backend, host):
fixed

2017-01-27 14:10 UTC, MatthewPiatetsky commented on course_discovery/settings/base.py
> +# Haystack configuration (http://django-haystack.readthedocs.io/en/v2.5.0/settings.html)
fixed

2017-01-27 14:15 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        response2 = self.get_response({'q': 'HTML'}).json()
I'll update some of the same things to be consistent (like query vs querystring). Though they may have the same name, they are methods with different functionality because they are in different classes. It makes it more dry to avoid the small bit of logic regarding faceted and partner to have that in the method rather than every test call

2017-01-27 14:18 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def get_response(self, querystring=None):
renamed to be consistent with the other search method

2017-01-27 14:19 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        ProgramFactory(title=title, partner=self.partner)
same reason mentioned above

2017-01-27 14:20 UTC, amangano-edx commented on course_discovery/settings/synonyms.py
> +    return processed_synonyms
I was referring to the `line.split` piece. I think that functionality would be better handled by a CSV library, since that is how you're storing the data. I don't really understand the advantage to using YAML over CSV for this stuff.

2017-01-27 14:22 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +    return processed_synonyms
I think clinton and renzo suggested that so I could include comments and new lines for better readability. So regardless there will be one bit of text parsing for either format.

2017-01-27 14:24 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +            response1, response2 = response1['objects'], response2['objects']
good point, i didn't want to explicitly look at the objects because this method uses both search and typeahead which return in different format. however, I realized i am only testing special characters here so if these did not work, this test could still pass. for that reason i've added a base case without special characters that we expect to work to compare against

2017-01-27 14:47 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +            response1, response2 = response1['objects'], response2['objects']
maybe the logic to normalize the responses could be DRY'd up by moving it into a helper method.

2017-01-27 17:03 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +            response1, response2 = response1['objects'], response2['objects']
refactored the objects check into a helper and put an assertion that the response was not empty there

2017-01-27 17:03 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +            response1, response2 = response1['objects'], response2['objects']
done

2017-01-27 17:04 UTC, MatthewPiatetsky commented
@amangano-edx @clintonb 
think I've addressed your existing comments (except @clintonb not sure about how to move the synonyms code into edx_catalog_extensions, could use some clarification on that)

2017-01-27 17:33 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def test_org_synonyms(self, get_synonym_lines):  # pylint: disable=unused-argument
What's going on here with `get_synonym_lines`? It might be cleaner to move the mocking to a helper method.

2017-01-27 17:33 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def test_org_synonyms(self, get_synonym_lines):  # pylint: disable=unused-argument
Add a docstring to these test methods explaining what they are testing.

2017-01-27 17:33 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        if 'objects' in response1:
`if` statements in test methods are a sign that the test method should really be two methods. I'm guessing this line is here because you are attempting to use the same method for two different endpoints. If that is the case, the mixin should contain the code that can be fully shared, and call an assertion helper that must be overridden by the individual test cases.

This should be done here and in the other test methods you have `if` statements.

2017-01-27 17:45 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def test_org_synonyms(self, get_synonym_lines):  # pylint: disable=unused-argument
maybe I can rename it get_synonym_lines_from_file. That method loads the file and this overrides it so the tests don't have to depend on the file

2017-01-27 17:54 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def test_org_synonyms(self, get_synonym_lines):  # pylint: disable=unused-argument
renamed and added docstrings

2017-01-27 17:54 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        if 'objects' in response1:
added the process response to each individual class

2017-01-27 19:40 UTC, clintonb commented on course_discovery/settings/synonyms.yaml
> +- usa, united states of america
Additional synonyms: murika, murrrrrika, god bless, trumplonia

FYI @jcdyer @stroilova

2017-01-30 16:43 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +                             SynonymTestMixin):
Does the order of the mixins matter here?

2017-01-30 16:44 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +                             SynonymTestMixin):
Yes. Mixins should come before the base class.

2017-01-30 16:47 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        return response['objects']
Does this contain a dictionary or a list? The Synonym tests all seem expect to get dictionaries (the use `self.assertDictEqual`).

2017-01-30 16:53 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +        for field in synonym_snowball_fields:
You could do this in one loop (and avoid allocating another list object) by writing:
```python
for field, value in mapping.items():
    if value.get('analyzer') != 'snowball']
        continue
```

2017-01-30 17:00 UTC, amangano-edx commented on course_discovery/settings/synonyms.py
> +        line = line.split(', ')
Does this handle escaped commas correctly, like the one on https://github.com/edx/course-discovery/pull/599/files#diff-8fa1fa692c631251ec1a558a998d282aR13?

2017-01-30 17:02 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +                             SynonymTestMixin):
changed to have api test case last

2017-01-30 17:02 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        return response['objects']
dictionary

2017-01-30 17:02 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +        for field in synonym_snowball_fields:
changed

2017-01-30 19:07 UTC, amangano-edx commented on course_discovery/settings/synonyms.py
> +        line = line.split(', ')
I think it would be good to have a test case for this.

2017-01-30 19:18 UTC, davec-edx commented on course_discovery/apps/core/utils.py
> +
Extra blank line  (I think)

2017-01-30 19:18 UTC, davec-edx commented on course_discovery/apps/core/utils.py
> +            index_settings['settings']['analysis']['filter']['synonym']['synonyms'] = get_synonyms(es)
Is this guaranteed to exist or there be a try/except around this?

2017-01-30 19:31 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms.py
> +        line = line.split(', ')
good point, i've updated the command to not split on those commas

2017-01-30 19:31 UTC, MatthewPiatetsky commented on course_discovery/apps/core/utils.py
> +
removed

2017-01-30 19:31 UTC, MatthewPiatetsky commented on course_discovery/apps/core/utils.py
> +            index_settings['settings']['analysis']['filter']['synonym']['synonyms'] = get_synonyms(es)
I create this in the base.py settings file, so I don't think I need to check for this

2017-01-30 19:39 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +                               index_analyzer='ngram_analyzer', search_analyzer='snowball_with_synonyms')
Nitpick: 'snowball_with_synonyms' is repeated a lot. You could save it to a variable first and DRY this up a bit.

2017-01-30 19:41 UTC, amangano-edx commented on course_discovery/settings/synonyms.py
> +        line = split(r'(?<!\\), ', line) # Split string on commas , except escaped commas \,
I think there should be a test for this somewhere, to verify it works as expected.

2017-01-30 19:42 UTC, davec-edx commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +                               index_analyzer='ngram_analyzer', search_analyzer='snowball_with_synonyms')
ehhh, leave it DAMP

2017-01-30 20:01 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +                               index_analyzer='ngram_analyzer', search_analyzer='snowball_with_synonyms')
added variable

2017-01-30 20:02 UTC, clintonb approved these changes
You're missing "murika"!

2017-01-30 20:19 UTC, rlucioni approved these changes

2017-01-30 21:53 UTC, MatthewPiatetsky commented
I had a conversation regarding the synonym format with Anthony, he had some concerns about escaping characters like commas and just the general structure, I've changed the files to be lists of lists in python, that way we have to worry about less file parsing/escaping/comments etc.... Thoughts?

2017-01-30 22:32 UTC, rlucioni commented on course_discovery/settings/synonyms_list.py
> +SYNONYMS = [
I'd prefer not to use Python modules to store configuration and data, but it seems to work in this case. Generally, using Python for config/data opens things up to unnecessary complexity. I still think my original YAML suggestion, one word per line, would be the cleanest option.

If you're going to go this route, please follow the same syntax standards we have elsewhere: single quotes, 4 space indentation. You may want to look into pointing the linter at these settings files so I don't have to keep making these comments 😄 .

2017-01-30 22:32 UTC, rlucioni commented on course_discovery/settings/synonyms_list.py
> +# Note: Do not use synonyms with punctuation, search and typeahead do not yet fully support punctuation
Keep it concise and just name the module `synonyms.py`. Same with `test_synonyms.py`.

2017-01-30 22:32 UTC, rlucioni commented on course_discovery/settings/synonyms_list.py
> +["usa", "united states of america", "murika"]
Add a trailing comma so the next person to add an entry gets a clean diff.

2017-01-30 22:40 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms_list.py
> +# Note: Do not use synonyms with punctuation, search and typeahead do not yet fully support punctuation
renamed (renamed the existing one process_synonyms.py)

2017-01-30 22:41 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms_list.py
> +["usa", "united states of america", "murika"]
fixed

2017-01-30 22:42 UTC, MatthewPiatetsky commented on course_discovery/settings/synonyms_list.py
> +SYNONYMS = [
It seems like everyone wanted slightly different, so it is hard to make everyone happy, but hopefully everyone is okish with this route.  
I updated the syntax, I think it is a good idea to update the linting to look at the settings, but I don't want to do that in this PR to confuse the diff. I can do that as soon as I merge this

2017-01-31 15:13 UTC, rlucioni approved these changes

2017-01-31 17:19 UTC, amangano-edx commented on course_discovery/settings/process_synonyms.py
> +def get_synonym_lines_from_file():
This probably doesn't need to be it's own method anymore.

2017-01-31 17:20 UTC, amangano-edx commented on course_discovery/settings/process_synonyms.py
> +            response = es.indices.analyze(text=synonym, analyzer='snowball')
What should we do if this call fails? Do we care?

2017-01-31 17:26 UTC, amangano-edx commented
LGTM

2017-01-31 18:03 UTC, merged