Added workflow data models.
openedx/course-discovery pull request #610
Opened 2017-01-31 09:20 UTC by waheedahmed

[ECOM-7004](https://openedx.atlassian.net/browse/ECOM-7004)

Added workflow data models.

2017-01-31 10:00 UTC, waheedahmed commented
@awais786, @tasawernawaz Please review.

2017-01-31 10:12 UTC, awais786 requested changes

2017-01-31 10:12 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +        CourseUserRole, null=True, blank=True, related_name='course_approved_by_state'
Update the related name.

2017-01-31 10:12 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +    course = models.OneToOneField(Course, related_name='publisher_course_state')
don't need to add publisher as prefix in related name.

2017-01-31 12:51 UTC, waheedahmed commented
@awais786 Feedback addressed, please take another look.

2017-01-31 13:21 UTC, awais786 approved these changes

2017-01-31 13:21 UTC, waheedahmed commented
@bderusha Please review.

2017-01-31 15:27 UTC, bderusha requested changes

2017-01-31 15:27 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    approved_by_role = models.ForeignKey(CourseUserRole, null=True, blank=True)
Rather than using the user role I think it may make more sense to use `PublisherUserRole.choices` here.  We will never make decisions about workflow state based on the users, only the roles they play.

2017-01-31 15:27 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    owner_role = models.ForeignKey(CourseUserRole, related_name='course_state')
Same here as above

2017-01-31 15:27 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    owner_role = models.ForeignKey(CourseUserRole, related_name='course_run_state')
Same note about using `PublisherUserRole.choices` for all role related fields

2017-02-01 09:01 UTC, waheedahmed commented
@bderusha Feedback addressed, kindly take another look.

2017-02-02 15:30 UTC, bderusha approved these changes

2017-02-03 10:32 UTC, merged