History page front end with no diff
openedx/course-discovery pull request #615
Opened 2017-02-01 08:20 UTC by tasawernawaz

[ECOM-7010 ](https://openedx.atlassian.net/browse/ECOM-7010)

Front end template and design of history page implemented (no diff).

**Screenshot**
<img width="633" alt="screen shot 2017-02-01 at 1 15 44 pm" src="https://cloud.githubusercontent.com/assets/4245618/22499500/00ae9f32-e881-11e6-83ed-0f83c4abdb8e.png">

2017-02-01 09:30 UTC, tasawernawaz commented
@waheedahmed @awais786 Please review.

2017-02-01 09:50 UTC, awais786 requested changes

2017-02-01 09:50 UTC, awais786 commented on course_discovery/templates/publisher/course_revision_history.html
> +{% extends 'base.html' %}{% load i18n %}{% block title %}
should be in separate lines.

2017-02-01 09:50 UTC, awais786 commented on course_discovery/templates/publisher/course_revision_history.html
> +        {% blocktrans with history_object.history_date|date:"d-m-Y" as date and history_object.history_user.full_name as name %}
used trimmed also.

2017-02-01 12:47 UTC, waheedahmed commented on course_discovery/static/sass/publisher/publisher.scss
> +    float: left;
Add RTL support.

2017-02-01 12:48 UTC, waheedahmed commented on course_discovery/templates/publisher/course_revision_history.html
> +{% block title %}
Add new line above title block to keep both separate.

2017-02-01 12:49 UTC, waheedahmed commented on course_discovery/templates/publisher/course_revision_history.html
> +        <button class="btn-show-changes">Show changes</button>
Add i18n support.

2017-02-01 12:52 UTC, waheedahmed commented on course_discovery/static/js/publisher/comparing-objects.js
> +    if ($(this).text() === 'Show changes') {
Instead of matching the text value you can add remove a class, what if user's is viewing this page in some other language.

2017-02-01 12:53 UTC, waheedahmed commented on course_discovery/static/js/publisher/comparing-objects.js
> +        $(this).text('Show changes');
Add i18n support `gettext('Show changes')`.

2017-02-01 12:53 UTC, waheedahmed commented on course_discovery/static/js/publisher/comparing-objects.js
> +        $(this).text('Hide changes');
Add i18n support `gettext('Hide changes')`.

2017-02-01 13:01 UTC, tasawernawaz commented
@waheedahmed Feedback addressed. Please review.

2017-02-01 14:50 UTC, tasawernawaz commented
@bderusha Please review.

2017-02-01 14:52 UTC, awais786 approved these changes

2017-02-02 07:29 UTC, waheedahmed approved these changes

2017-02-02 07:30 UTC, merged