ignore for now
openedx/course-discovery pull request #622
Opened 2017-02-01 22:24 UTC by MatthewPiatetsky

2017-02-03 18:41 UTC, rlucioni reviewed
I also mentioned this to @amangano-edx on https://github.com/edx/course-discovery/pull/621: we shouldn't be introducing new tests which only pass if some required initial data is present in the database. Tests should be creating (or verifying the existence of, via `get_or_create()`) their own data if they need it to pass.

2017-02-03 18:41 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_catalogs.py
> +        assert response.data['results'] == self.serialize_catalog_course(courses, many=True)
Hurray for pytest! You can change the line above to `assert response.status_code == 200`.

2017-02-03 18:41 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.assertEqual(
You can use regular `assert` statements here, too, and throughout.

2017-02-03 18:41 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> -        with self.assertNumQueries(37):
Why get rid of this?

2017-02-03 18:41 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        with self.assertNumQueries(12):
Are these incremented by one because it only takes one query to retrieve the new field, or because there's only one `ReportingType` record present? Given that the new field is a `ForeignKey`, I would have expected to see a `select_related` on the serializer, but I don't.

2017-02-03 18:41 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        self.assertEqual(response.data, self.serialize_program(program))
Consider switching the lines you're touching to use `assert`.

2017-02-03 18:41 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        with self.assertNumQueries(19):
For those who are wondering: these query counts are dropping because previously we were also counting the un-prefetched queries made by test methods like `serialize_program()`. We only care about the queries made by the view.

2017-02-03 18:41 UTC, rlucioni commented on course_discovery/apps/course_metadata/models.py
> +    reporting_type = models.ForeignKey(ReportingType, null=False, blank=False, default=1)
Is the default here necessary? Hardcoding a primary key seems wrong. What happens if that record isn't present? During testing, this will fail MySQL's referential integrity checks if the record is cleared. I'd recommend leaving the default unspecified.

2017-02-03 18:41 UTC, rlucioni commented on course_discovery/apps/course_metadata/tests/factories.py
> +    name = FuzzyText()
Use `Faker`, now included with factory_boy. These fuzzy utilities are deprecated.

2017-02-03 19:16 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> -        with self.assertNumQueries(37):
This test performs an es query and locally there were only a few setup related queries and no other SQL queries. I think there are SQL queries coming back because I think the SerializationMixin may be mocking out the actual call to ES?

2017-02-03 19:17 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +        self.assertEqual(response.data, self.serialize_program(program))
switched

2017-02-03 19:17 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_catalogs.py
> +        assert response.data['results'] == self.serialize_catalog_course(courses, many=True)
changed

2017-02-03 19:17 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.assertEqual(
changed

2017-02-03 19:18 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/factories.py
> +    name = FuzzyText()
changed, should we use factory.Faker('text') ?

2017-02-03 19:25 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        with self.assertNumQueries(12):
I see, that makes sense. Changed serializers to select_related

2017-02-03 19:26 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    reporting_type = models.ForeignKey(ReportingType, null=False, blank=False, default=1)
Well as I mentioned above, I did look into specifying this in the edx_catalog_extensions app, but if we didn't have a default specified, the field would no have default, right? Is there a way we can not have the default and still satisfy the ask by analytics to default new courses to mooc?

2017-02-03 19:40 UTC, rlucioni commented on course_discovery/apps/course_metadata/tests/factories.py
> +    name = FuzzyText()
@MatthewPiatetsky `factory.Faker('word')` is closer to what you want.

2017-02-03 19:41 UTC, rlucioni commented on course_discovery/apps/course_metadata/models.py
> +    reporting_type = models.ForeignKey(ReportingType, null=False, blank=False, default=1)
@MatthewPiatetsky sure, one possibility is modifying the `CourseRun` `save()` method so that the field is set to the right `ReportingType`.

2017-02-03 19:44 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> -        with self.assertNumQueries(37):
@MatthewPiatetsky it doesn't look like the serialization mixin was being used in this block to begin with. Don't we want to keep tabs on how many queries are being made by this view?

2017-02-03 19:45 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    reporting_type = models.ForeignKey(ReportingType, null=False, blank=False, default=1)
Well we do want to allow setting the field to something else. I guess we could check on save if the field is not set, and set it to mooc if that is the case. Wouldn't we risk running into the same issue though if that record is removed like you said?

2017-02-03 19:46 UTC, rlucioni commented on course_discovery/apps/api/serializers.py
> +        return queryset.select_related('language', 'video', 'reporting_type').prefetch_related(
@MatthewPiatetsky this is the right direction. Can you verify that there is a test case serializing multiple `CourseRuns` with linked `ReportingTypes`? We should make sure the `select_related` is actually working.

2017-02-03 19:48 UTC, rlucioni commented on course_discovery/apps/course_metadata/models.py
> +    reporting_type = models.ForeignKey(ReportingType, null=False, blank=False, default=1)
@MatthewPiatetsky the code could be smart enough to not do anything if a filter for `ReportingTypes` with name `mooc` doesn't return any results.

2017-02-03 19:50 UTC, clintonb requested changes

2017-02-03 19:50 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +class ReportingType(AbstractNamedModel):
Why is this a separate model instead of a field? I'm in favor of using a field, and including a large comment explaining that this field is experimental and likely to be removed in the future. No need to try to put lipstick on the pig.

2017-02-03 19:50 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    reporting_type = models.ForeignKey(ReportingType, null=False, blank=False, default=1)
Remove the default and make the field nullable.

2017-02-03 19:50 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +class ReportingTypeSerializer(serializers.ModelSerializer):
This is not used, and should be deleted.

2017-02-03 19:50 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> -    Course, CourseRun, Image, Organization, Person, Prerequisite, Seat, Subject, Video, Program, ProgramType, FAQ,
Nit: no need to touch FAQ

2017-02-03 20:16 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +class ReportingType(AbstractNamedModel):
Ok I can change it to use a choice field, I did not get the impression that this field would be removed in the future from my conversation with analytics, but if we're ok hardcoding those terms that is fine. I thought that since we usually don't want to hardcoded edx specific things we'd want them in a catalog extensions migration like I have done here

2017-02-03 20:19 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +class ReportingType(AbstractNamedModel):
The plan I have been discussing is to take the simplest approach for now—choices. We will revisit this after we better understand all of the use cases. That could mean multiple fields. It could mean something else altogether.

2017-02-03 20:20 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +class ReportingType(AbstractNamedModel):
Eh...let's avoid the re-work on this PR. No solution will be ideal at this time. Keep the foreign key if that's what you want to go with.

2017-02-03 20:57 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +        with self.assertNumQueries(6):
looking into why this changed

2017-02-03 21:10 UTC, MatthewPiatetsky commented
@rlucioni @clintonb i've done some refactoring based on @clintonb suggestion that should make most of your comments N/A

2017-02-06 17:06 UTC, MatthewPiatetsky commented
@rlucioni @clintonb retagging

2017-02-06 18:38 UTC, clintonb requested changes

2017-02-06 18:38 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    REPORTING_TYPE_CHOICES = (
Use [django-choices](https://github.com/bigjason/django-choices).

2017-02-06 18:38 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        ('mooc', _('mooc')),
Unmark for migration. We don't want anyone else sharing our shame.

2017-02-06 18:38 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    reporting_type = serializers.ChoiceField(
You shouldn't need to specify this field explicitly. DRF knows how to validate choices.

2017-02-06 20:17 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +        ('mooc', _('mooc')),
can you clarify how to unmark for migration? Also, will the default value still work if the migration is not present?

2017-02-06 20:50 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    REPORTING_TYPE_CHOICES = (
changed to django-choices and moved to choices.py

2017-02-06 20:50 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +    reporting_type = serializers.ChoiceField(
removed

2017-02-06 21:23 UTC, clintonb requested changes

2017-02-06 21:23 UTC, clintonb commented on course_discovery/apps/course_metadata/choices.py
> +    mooc = ChoiceItem('mooc', _('mooc'))
These don't need to be translated.

2017-02-06 21:23 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    reporting_type = models.CharField(max_length=255, choices=ReportingType.choices, default='mooc')
`ReportingType.mooc`

2017-02-06 21:26 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/choices.py
> +    mooc = ChoiceItem('mooc', _('mooc'))
do i just need to do mooc = ChoiceItem('mooc', 'mooc')?
changed

2017-02-06 21:26 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/models.py
> +    reporting_type = models.CharField(max_length=255, choices=ReportingType.choices, default='mooc')
changed

2017-02-06 22:21 UTC, clintonb approved these changes

2017-02-06 22:28 UTC, rlucioni approved these changes

2017-02-06 22:28 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.assertEqual(response.data.get('programs'), [])
`assert` statement, please.

2017-02-06 22:41 UTC, clintonb commented
Remember to squash your commits.

2017-02-06 23:50 UTC, merged