Added simple endpoint for PATCH for course_runs api to allow the modi…
openedx/course-discovery pull request #634
Opened 2017-02-06 16:57 UTC by davec-edx

Addition of a PATCH verb to the API

ECOM-7024

2017-02-06 17:08 UTC, clintonb requested changes
Permissions need to be fixed. We don't want any authenticated user to be able to modify course runs.

2017-02-06 17:14 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        """ Verify the endpoint supports partially updating a course_run's fields. """
this works, but what if we used the CourseRun factory and updated all the fields, then checked that all of them got updated. If all the fields including m2m actually work, using the factory could be a simple way to ensure that new fields also get updated without having to update the test

2017-02-06 17:23 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        assert updated_course_run.max_effort == max_effort
if you go with the factory you could probably have a loop of assert statements using the original_course_run.__dict__.items() and updated_course_run.__dict__.items() or something like that

2017-02-07 18:12 UTC, clintonb requested changes

2017-02-07 18:12 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.user = UserFactory(is_staff=False, is_superuser=True)
This does not need to be changed.

2017-02-07 18:12 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.request.user.is_staff = True
This has no effect on the test.

2017-02-07 18:12 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        updated_course_run = CourseRun.objects.get(key=self.course_run.key)
Use [`refresh_from_db`](https://docs.djangoproject.com/en/1.10/ref/models/instances/#django.db.models.Model.refresh_from_db).

2017-02-07 18:12 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        original_course_run = CourseRun.objects.get(key=self.course_run.key)
There is no need to reload this object from the database. Your test values don't need to depend on the original values.

2017-02-07 18:12 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.assertEqual(response.status_code, 200)
`assert response.status_code == 200`

2017-02-07 18:12 UTC, clintonb commented on course_discovery/apps/api/v1/views/course_runs.py
> +        if self.request.user.is_authenticated() and self.request.user.is_staff:
This is not how we handle permissions. See http://www.django-rest-framework.org/api-guide/permissions/.

2017-02-07 18:12 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        # Get a course_run, and calculate new min_ and max_effort
This test should be much simpler. There is no need to worry about the data being sent to the API because we should not get to that level.

```python
response = self.client.patch(url,{}, format='json')
assert response.status_code == 403
```

2017-02-08 14:23 UTC, davec-edx commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.user = UserFactory(is_staff=False, is_superuser=True)
Everything was being tested with is_staff set, where most don't need anything more than being authenticated.

2017-02-08 14:24 UTC, davec-edx commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.request.user.is_staff = True
In conjunction with not setting it for other tests, it needs to be set for this test (and unset for the corresponding negative test)

2017-02-08 14:25 UTC, davec-edx commented
@clintonb Please re-review -- thanks

2017-02-08 14:25 UTC, davec-edx commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        assert updated_course_run.max_effort == max_effort
Yes, I thought about that, but thought it would be overkill, I just chose a couple fields at random.

2017-02-08 14:39 UTC, clintonb requested changes

2017-02-08 14:39 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.user = UserFactory(is_staff=False, is_superuser=True)
Superuser trumps staff. Given that all superusers are staff, this change is not necessary.

2017-02-08 14:39 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        self.request.user.is_staff = True
If you revert the change to `self.user` this line can go away.

2017-02-08 14:39 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        original_course_run = CourseRun.objects.get(key=self.course_run.key)
Please clean this up. There is no need to load the object from the DB. Doing so is unnecessarily confusing.

```python
expected_max_effort = 1000
expected_min_effort = 100
data = {
  'max_effort': expected_max_effort,
  'min_effort': expected_min_effort,
}

response = self.client.patch(url, data, format='json')
assert response.status_code == 200

self.course_run.refresh_from_db()
assert self.course_run.max_effort == expected_max_effort
assert self.course_run.min_effort == expected_min_effort
```

2017-02-08 14:39 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        # Update this course_run with the new info, NOTE this should fail with a 404
This is not valid.

2017-02-08 14:39 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        assert response.status_code != 200
`assert response.status_code == 403`

2017-02-08 14:39 UTC, clintonb commented on course_discovery/apps/api/v1/views/course_runs.py
> +    permission_classes = (IsAuthenticated, )
Revert

2017-02-08 14:39 UTC, clintonb commented on course_discovery/apps/api/v1/views/course_runs.py
> +    @method_decorator(staff_member_required)
This is not what we discussed yesterday. You should be using [`DjangoModelPermissions`](http://www.django-rest-framework.org/api-guide/permissions/#djangomodelpermissions).

2017-02-08 19:29 UTC, clintonb requested changes

2017-02-08 19:29 UTC, clintonb commented on course_discovery/apps/api/v1/views/course_runs.py
> +    permission_classes = (DRYPermissions,)
`permission_classes = (IsAuthenticated, DjangoModelPermissions)`

We don't need instance-specific permissions, and we always want users to be authenticated. Use `DjangoModelPermissions`.

2017-02-08 19:29 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +class CourseRun(ModelPermissionsMixin, TimeStampedModel):
This is not necessary.

2017-02-08 20:11 UTC, clintonb approved these changes

2017-02-08 20:12 UTC, merged