Added send for review functionality for parent course.
openedx/course-discovery pull request #637
Opened 2017-02-07 11:46 UTC by waheedahmed

[ECOM-6047](https://openedx.atlassian.net/browse/ECOM-6047)

As a Course team reviewer or Marketing reviewer, I need to be able to send my Parent Course edits for review so that the About page can move to the next step in the workflow.

<img width="508" alt="screen shot 2017-02-07 at 4 39 52 pm" src="https://cloud.githubusercontent.com/assets/2851134/22689826/8301827e-ed54-11e6-9bba-7d3fed3471d4.png">
<img width="513" alt="screen shot 2017-02-07 at 4 37 06 pm" src="https://cloud.githubusercontent.com/assets/2851134/22689829/834f38d4-ed54-11e6-8ea7-e6736edfc056.png">
<img width="507" alt="screen shot 2017-02-07 at 4 38 24 pm" src="https://cloud.githubusercontent.com/assets/2851134/22689827/832e13d4-ed54-11e6-8635-89ac1235a799.png">
<img width="508" alt="screen shot 2017-02-07 at 4 45 54 pm" src="https://cloud.githubusercontent.com/assets/2851134/22689922/f038f250-ed54-11e6-99d6-df224e5b10ed.png">

2017-02-09 08:43 UTC, tasawernawaz requested changes

2017-02-09 08:43 UTC, tasawernawaz commented on course_discovery/templates/publisher/course_detail/_approval_widget.html
> +                                {{ role_widget.state_button.text }}
do we need to support 118 here?

2017-02-09 08:43 UTC, tasawernawaz commented on course_discovery/templates/publisher/course_detail/_approval_widget.html
> +                            <strong>{{ role_widget.heading }}</strong>
same question here

2017-02-09 08:43 UTC, tasawernawaz commented on course_discovery/templates/publisher/course_detail.html
> +            <p id="stateChangeError" class="alert-copy">{{ message }}</p>
what will be the `{{ message }}` mark it for 118

2017-02-09 08:43 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
> +    def test_edit_course_with_state(self):
I think test name should be changed according to docstring

2017-02-09 08:43 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
> +            'btn btn-neutral btn-change-state',
why you are not adding classes directly ?

2017-02-09 08:51 UTC, waheedahmed commented on course_discovery/templates/publisher/course_detail/_approval_widget.html
> +                                {{ role_widget.state_button.text }}
@tasawernawaz Already doing here https://github.com/edx/course-discovery/pull/637/files#diff-2680d228b92a6ff1a837bbd2abcd1cfbR52

2017-02-09 08:51 UTC, waheedahmed commented on course_discovery/templates/publisher/course_detail/_approval_widget.html
> +                            <strong>{{ role_widget.heading }}</strong>
same answer

2017-02-09 08:52 UTC, waheedahmed commented on course_discovery/templates/publisher/course_detail.html
> +            <p id="stateChangeError" class="alert-copy">{{ message }}</p>
Nothing, removing.

2017-02-09 08:53 UTC, waheedahmed commented on course_discovery/templates/publisher/course_detail.html
> +            <p id="stateChangeError" class="alert-copy">{{ message }}</p>
Error message will be added through JS.

2017-02-09 08:54 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +            'btn btn-neutral btn-change-state',
Its a test case I'm just making an expected button here and verifying that the right button is in the template.

2017-02-09 09:19 UTC, waheedahmed commented
@tasawernawaz Feedback addressed.

2017-02-09 09:22 UTC, tasawernawaz approved these changes

2017-02-09 09:26 UTC, waheedahmed commented
@bderusha Please review.

2017-02-09 16:33 UTC, bderusha requested changes

2017-02-09 16:33 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    def is_any_required_field_none(self):
Can this logic live in the state machine?  Are we able to add checks before moving between states? I think we are.  Ideally this sort of check would live there.

2017-02-09 16:33 UTC, bderusha commented on course_discovery/static/js/publisher/publisher.js
> +                $('.alert-messages').show();
there will be two alert messages classes on the page.  This will show both?  I don't think we want that

2017-02-09 16:33 UTC, bderusha commented on course_discovery/templates/publisher/course_detail.html
>  {% include 'alert_messages.html' %}
will also create a `.alert-message` box

2017-02-09 16:38 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +    def initialize_workflow(self):
I don't think this needs to be a method on `Course`

2017-02-09 16:38 UTC, bderusha commented on course_discovery/apps/publisher/models.py
> +        course_state = CourseState(owner_role=PublisherUserRole.CourseTeam, course=self)
`CourseState.objects.create`

2017-02-09 16:38 UTC, bderusha commented on course_discovery/apps/publisher/views.py
> +                    course.initialize_workflow()
Fine to just call `CourseState.objects.create` here

2017-02-10 11:05 UTC, waheedahmed commented
@bderusha Feedback addressed, kindly take another look.

2017-02-11 20:41 UTC, bderusha approved these changes

2017-02-13 11:00 UTC, merged