Comment Widget on Course-run detail page.
openedx/course-discovery pull request #640
Opened 2017-02-08 13:38 UTC by awais786

Update the design and add a comment widget on the course-run page.

https://openedx.atlassian.net/browse/ECOM-6075

2017-02-08 13:39 UTC, awais786 commented
<img width="440" alt="screen shot 2017-02-08 at 6 37 31 pm" src="https://cloud.githubusercontent.com/assets/445320/22739537/dc5aaba0-ee2d-11e6-9c8f-87d3a81f8949.png">

2017-02-08 13:42 UTC, awais786 commented
@waheedahmed @tasawernawaz Please review.

2017-02-08 14:46 UTC, tasawernawaz requested changes

2017-02-08 14:46 UTC, tasawernawaz commented on course_discovery/static/sass/publisher/course_form.scss
> +      float: left;
add i18 support

2017-02-08 14:46 UTC, tasawernawaz commented on course_discovery/static/sass/publisher/course_form.scss
> +    text-align: right;
add i18 support

2017-02-08 14:46 UTC, tasawernawaz commented on course_discovery/static/js/publisher/comments.js
> +        updatedComment = $(editableDd).text()    ;
remove extra spaces before `;`

2017-02-08 14:46 UTC, tasawernawaz commented on course_discovery/static/js/publisher/comments.js
> +    $(editableDd).next('dt').show();
correct indentation

2017-02-08 14:46 UTC, tasawernawaz commented on course_discovery/static/js/publisher/comments.js
> +            formattedDatetime = $.format.date(response['modified'], 'MMMM dd, yyyy, hh:mm p');
make sure this formate is as same as you are adding through html template at https://github.com/edx/course-discovery/pull/640/files#diff-1bad55bfb299a92c649318257dcbf806R8

2017-02-08 14:46 UTC, tasawernawaz commented on course_discovery/static/js/publisher/comments.js
>              //format datetime e.g. Dec. 15, 2016, 10:03 a.m.
since you have updated date format so update this comment.

2017-02-08 14:46 UTC, tasawernawaz commented on course_discovery/templates/comments/comments_list.html
> +                {% trans 'Submitted by' %}&nbsp;{{ comment.name }}
make this _italic_

2017-02-08 15:05 UTC, awais786 commented on course_discovery/static/js/publisher/comments.js
> +            formattedDatetime = $.format.date(response['modified'], 'MMMM dd, yyyy, hh:mm p');
Verified

2017-02-08 15:06 UTC, awais786 commented
<img width="421" alt="screen shot 2017-02-08 at 8 05 59 pm" src="https://cloud.githubusercontent.com/assets/445320/22742842/0963a3f2-ee3a-11e6-9978-759ebecbae3d.png">

2017-02-08 15:11 UTC, awais786 commented
@bderusha Please review this PR.

2017-02-08 15:15 UTC, awais786 commented
New course page ( cancel link and button alignment )

<img width="1001" alt="screen shot 2017-02-08 at 8 14 24 pm" src="https://cloud.githubusercontent.com/assets/445320/22743166/3513fbae-ee3b-11e6-95d9-887c761959aa.png">

2017-02-09 11:19 UTC, tasawernawaz approved these changes

2017-02-09 11:19 UTC, tasawernawaz commented on course_discovery/static/sass/publisher/course_form.scss
> +      float: left;
i18

2017-02-09 11:21 UTC, tasawernawaz commented on course_discovery/templates/comments/add_auth_comments.html
> +        <p><div class="heading">{% trans 'Comment:' %}</div></p>
Fix related test.

2017-02-09 13:18 UTC, awais786 commented
@bderusha Please review.

2017-02-09 16:08 UTC, bderusha approved these changes
👍 once comments addressed

2017-02-09 16:08 UTC, bderusha commented on course_discovery/apps/publisher/migrations/0032_create_switch_for_comments.py
> +    Switch.objects.get_or_create(name='publisher_hide_comments_widget', defaults={'active': False})
Can we please rename this to a 'positive' name like `publisher_comment_widget_feature` and only show when the feature is enabled.

2017-02-09 16:08 UTC, bderusha commented on course_discovery/templates/comments/comments_list.html
> +                {% trans 'Submitted by' %}&nbsp;{{ comment.name }}
use `<em>` and not `<i>` for doing this, FYI

2017-02-09 16:50 UTC, awais786 commented
@bderusha I am not sure about the above comment of  `<em>`

2017-02-09 17:15 UTC, awais786 commented
@bderusha I got it `<em>` :)

2017-02-09 18:22 UTC, merged