ignore for now
openedx/course-discovery pull request #641
Opened 2017-02-08 17:41 UTC by MatthewPiatetsky

ECOM-7079 Move ElasticSearchBoostConfig into settings

2017-02-09 16:31 UTC, clintonb requested changes
Put the ticket number on the last line of your commit message.

How do we get edX.org information out of the base settings? As an OpenEdX user, I don't care about Professional Certificate.

2017-02-09 16:39 UTC, MatthewPiatetsky commented
@clintonb is there a way we can have settings in an edx only app override the base settings or something like that?  
(Though I'm also not sure if open edx users would care about other boosting either. Not all of it has our brand names, but all of it is specific to the behavior we want on our marketing site, no idea if others might want similar behavior).

2017-02-09 18:01 UTC, clintonb commented
@MatthewPiatetsky you could load the module dynamically like we do with fulfillment modules in edx/ecommerce:

* https://github.com/edx/ecommerce/blob/8fde125db17565c28cdf182fd35416c5c05b9dee/ecommerce/settings/_oscar.py#L80-L84
* https://github.com/edx/ecommerce/blob/8fde125db17565c28cdf182fd35416c5c05b9dee/ecommerce/extensions/fulfillment/api.py#L99-L100

Regardless of which implementation you use, remember to document this in the `docs/` directory.

2017-02-09 19:20 UTC, mikedikan commented on course_discovery/apps/edx_haystack_extensions/tests/test_boosting.py
> +import datetime
can you explain why all of this test code was moved?

2017-02-09 19:23 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/tests/test_boosting.py
> +import datetime
I'm in the middle of refactoring some things for this PR, but specifically Clinton suggested in an earlier comment to move the boosting config and functionality into an edx app since our config is specific to our needs

2017-02-13 19:13 UTC, MatthewPiatetsky commented
@clintonb @mikedikan did I address your comments

2017-02-13 19:22 UTC, clintonb approved these changes

2017-02-13 19:22 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/mixins.py
> +        function_score = ELASTICSEARCH_BOOST_CONFIG
Name this variable appropriately to avoid confusion. Alternatively, ditch the variable and use the constant directly on the line below.

2017-02-13 19:38 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        with self.assertNumQueries(36):
Why do some of the query counts change by one and others by two?

2017-02-13 19:42 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +from course_discovery.apps.edx_haystack_extensions.elasticsearch_boost_config import ELASTICSEARCH_BOOST_CONFIG
Just curious, but the boost config was moved to an app because it is edx-specific and not everyone in the community will need it. Is the edx_haystack_extensions app also meant to be edx-specific?

2017-02-13 19:44 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/tests/mixins.py
> +        return ELASTICSEARCH_BOOST_CONFIG
This is modifying the constant, which I believe may have consequences for tests that run later on in the suite (they may be flaky since the `ELASTICSEARCH_BOOST_CONFIG` was modified in a prior test and is no longer in a consistent state).

2017-02-13 19:46 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/tests/mixins.py
> +        TEST_ELASTICSEARCH_BOOST_CONFIG = {
Why change this to a constant if it's only used for this one test?

2017-02-13 19:53 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        with self.assertNumQueries(36):
i looked at this test on master and it was getting the boost config twice, probably due to what we were doing in the backends.py file

2017-02-13 19:54 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +from course_discovery.apps.edx_haystack_extensions.elasticsearch_boost_config import ELASTICSEARCH_BOOST_CONFIG
i believe so  
it would be unfortunate if the name for a non edx specific app started with edx

2017-02-13 19:57 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +from course_discovery.apps.edx_haystack_extensions.elasticsearch_boost_config import ELASTICSEARCH_BOOST_CONFIG
Aren't the edx_haystack_extensions required for the rest of the IDA to function properly? If you removed the edx_haystack_extensions app, would everything else continue to work properly, just without boosting? Isn't the synonym and typeahead behavior dependent on modifications made in that app?

The point I'm trying to make is maybe we might want to add the boost config here in a way that degrades gracefully if it's not available (in case someone uses course-discovery without our specific boosting).

2017-02-13 20:05 UTC, davec-edx commented on course_discovery/apps/api/v1/tests/test_views/test_course_runs.py
> +        with self.assertNumQueries(36):
course-runs was also changed for permissions so that could cause an extra query for perms

2017-02-13 20:36 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +from course_discovery.apps.edx_haystack_extensions.elasticsearch_boost_config import ELASTICSEARCH_BOOST_CONFIG
`edx_haystack_extensions` is not required, and is only for edx.org.

2017-02-13 20:38 UTC, amangano-edx requested changes

2017-02-13 20:38 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/tests/mixins.py
> +        boost_config['function_score']['query'] = {'query_string': self.simple_query}
doesn't this still modify the constant (since `boost_config` is just a reference to the same document as `ELASTICSEARCH_BOOST_CONFIG`?

2017-02-13 20:40 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/tests/mixins.py
> +        boost_config['function_score']['query'] = {'query_string': self.simple_query}
I think you need to create a deep copy of ELASTICSEARCH_BOOST_CONFIG to avoid modifying the original object.

2017-02-13 20:43 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/tests/mixins.py
> +        boost_config['function_score']['query'] = {'query_string': self.simple_query}
`X = 1
def changeX():
	X = 2
print (X)

1`

2017-02-13 20:45 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/tests/mixins.py
> +        boost_config['function_score']['query'] = {'query_string': self.simple_query}
```
X = {'1': '2'}
def changeX():
	X['1'] = ['3']
print (X)

{'1': '2'}
```
I don't think this is an issue

2017-02-13 20:45 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/tests/mixins.py
> +        boost_config['function_score']['query'] = {'query_string': self.simple_query}
good point

2017-02-13 21:09 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +from course_discovery.apps.edx_haystack_extensions.elasticsearch_boost_config import ELASTICSEARCH_BOOST_CONFIG
@amangano-edx isn't the boost config only used in the edx_haystack_extensions app?  
Not sure about typeahead etc... but that probably wouldn't be part of this PR

2017-02-13 21:09 UTC, MatthewPiatetsky commented
@amangano-edx did I address your comments?

2017-02-14 14:35 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +from course_discovery.apps.edx_haystack_extensions.elasticsearch_boost_config import ELASTICSEARCH_BOOST_CONFIG
Yes, AFAIK the boost config is only used here. My comment about typeahead and synonyms was relevant to the question about whether this app (edx_haystack_extensions) is truly edx-specific or if it is always necessary for the IDA to run properly.

2017-02-14 14:36 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/backends.py
> +        function_score_config = ELASTICSEARCH_BOOST_CONFIG['function_score']
I think we need to create a deep copy of the config here. Otherwise, I believe we risk modifying it whenever a query is run (line 42) and leaving it in an inconsistent state.

2017-02-14 14:39 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/tests/mixins.py
> +        boost_config = dict(ELASTICSEARCH_BOOST_CONFIG)
I just want to point out that this makes a shallow copy of the config. All of the nested dictionaries and lists within the config would not be copied and would still refer to the original objects. This might not be a problem here, since we only modify the outermost dictionary in line 41. However, I think it'd be safer and less error prone to do a deep copy instead. https://docs.python.org/3.5/library/copy.html

2017-02-14 15:33 UTC, MatthewPiatetsky commented
@amangano-edx  
I just moved the variable into a function. That should address all the variable modification comments

2017-02-14 17:52 UTC, amangano-edx approved these changes

2017-02-14 17:52 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/elasticsearch_boost_config.py
> +def get_elasticsearch_boost_config():
This seems fine, though I wonder if it might make sense to just have this method become a query builder of sorts and move lines 41-43 from `course_discovery/apps/edx_haystack_extensions/backends.py` into here? It could take the query as an argument.

2017-02-14 17:56 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/elasticsearch_boost_config.py
> +def get_elasticsearch_boost_config():
We use the config differently in the test files and could be differently in the future, I'd rather keep the specific modifications where they are needed and keep this generic

2017-02-14 17:57 UTC, merged