ECOM-6820 Add enrollable filter to course runs
openedx/course-discovery pull request #642
Opened 2017-02-08 19:40 UTC by MatthewPiatetsky

2017-02-08 20:13 UTC, amangano-edx commented on course_discovery/apps/course_metadata/query.py
> +            - OR have no specified enrollment close date (e.g. self-paced courses)
This conflicts with definitions of enrollable elsewhere (like the enrollable course boosting), which take into account enrollment_start date. Perhaps we should come up with a consensus for this term so that it may be used consistently within the code base.

2017-02-08 20:28 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/query.py
> +            - OR have no specified enrollment close date (e.g. self-paced courses)
Could you spell out the definition in the boosting here?

2017-02-08 20:39 UTC, schenedx commented on course_discovery/apps/api/serializers.py
> +            course_runs = course_runs.marketable().enrollable()
I am worried that we decide to change the definition of this flag from `.active()` to `.enrollable()`. The Sailthru 'marketable` variable is using this flag. Can you communicate with Patrick and Jeanie in Marketing to make sure they are OK with courses that ended to be `marketable` for email marketing?

2017-02-08 20:42 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +            course_runs = course_runs.marketable().enrollable()
thanks, I didn't realize that sailthru was using this

2017-02-08 20:50 UTC, amangano-edx commented on course_discovery/apps/course_metadata/query.py
> +            - OR have no specified enrollment close date (e.g. self-paced courses)
A course_run is considered enrollable if:
- enrollment_start and enrollment_end are null
- enrollment_start is null and enrollment_end is in the future
- enrollment_start is in the past and enrollment_end is null
- enrollment_start is in the past and enrollment_end is in the future

2017-02-08 21:00 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/query.py
> +            - OR have no specified enrollment close date (e.g. self-paced courses)
cool, jasper said we don't need courses with enrollment_start in future to show up, so i'll update enrollment to mean this

2017-02-08 21:14 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/query.py
> +            - OR have no specified enrollment close date (e.g. self-paced courses)
updated with this definition

2017-02-08 21:14 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +            course_runs = course_runs.marketable().enrollable()
I am no longer modifying this query parameter, I will modify the marketing site to pass marketable=1&enrollable=1

2017-02-08 21:37 UTC, schenedx commented
@MatthewPiatetsky Could you please write a test case in the api view test to ensure the flag `is_enrollable` is returning with correct course_runs?

2017-02-08 21:37 UTC, amangano-edx commented on course_discovery/apps/course_metadata/query.py
> +                Q(enrollment_start__gt=now) |
Maybe `gte` might be better for this?

2017-02-08 21:37 UTC, amangano-edx commented on course_discovery/apps/course_metadata/query.py
> +            - OR have no specified enrollment close date (e.g. self-paced courses)
The code looks good, but could you please also update the comment?

2017-02-08 21:38 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/query.py
> +                Q(enrollment_start__gt=now) |
true

2017-02-08 21:38 UTC, amangano-edx commented on course_discovery/apps/course_metadata/query.py
> +                Q(enrollment_start__gt=now) |
sorry, this should actually be `lte`

2017-02-08 21:38 UTC, amangano-edx commented on course_discovery/apps/course_metadata/query.py
> +                Q(enrollment_start__gt=now) |
enrollment_start should be in the past

2017-02-08 21:45 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/query.py
> +                Q(enrollment_start__gt=now) |
thanks for helping clarify the lte/gte get confusing

2017-02-08 23:04 UTC, MatthewPiatetsky commented
FYI I need to refactor a bunch of things here because the filter is applying to courses rather than course runs

2017-02-09 15:13 UTC, amangano-edx commented on course_discovery/apps/course_metadata/query.py
> +            - OR have no specified enrollment close date (e.g. self-paced courses)
I think that this should also mention that enrollment_start must be unspecified or in the past.

2017-02-09 16:30 UTC, schenedx approved these changes
👍 
Can you please add this flag to the swagger list at https://github.com/edx/course-discovery/blob/master/course_discovery/apps/api/v1/views/courses.py#L53?

2017-02-09 16:37 UTC, davec-edx commented on course_discovery/apps/api/tests/test_serializers.py
> +            2 if marketable_enrollable_course_runs_with_archived else 4
`assert len(serializer.data['course_runs']) == 2 if ... else 4`

2017-02-09 16:38 UTC, davec-edx commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.assertEqual(
more self.asserts that should be changed

2017-02-09 16:41 UTC, davec-edx commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        self.assertEqual(
more self.asserts

2017-02-09 16:43 UTC, davec-edx commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        CourseRunFactory(enrollment_end=past)
Is there a need to explicitly add a start=None?  I see end=None but not start...

2017-02-09 16:55 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> +            2 if marketable_enrollable_course_runs_with_archived else 4
changed

2017-02-09 16:55 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.assertEqual(
changed

2017-02-09 16:55 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        self.assertEqual(
changed

2017-02-09 16:56 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        CourseRunFactory(enrollment_end=past)
added, there are 9 combinations for just these two fields, it wasn't really necessary to test all, but added this one

2017-02-09 17:18 UTC, clintonb requested changes

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +            # Same as the querystring above, but does not filter out archived courses with an end date in the past
Same as the "marketable_course_runs_only", but includes courses that have ended.

Don't assume this block of code will always follow the one above.

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> -        closed_course_run = CourseRunFactory(
Revert. "Archived" is more of a marketing term. As I've dug into the course lifecycle, it's clear that while an archived course run is a closed run (end date passed), a closed run is not necessarily archived (open for enrollment/review after end date).

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        Verify that the test_marketable_enrollable_course_runs_with_archived option is respected, restricting returned
s/test_marketable_enrollable_course_runs_with_archived/marketable_enrollable_course_runs_with_archived

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        Also includes archived courses with an end date in the past that the test_marketable_course_runs_only
I don't know what this means.

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        # Published course run with a seat, no enrollment start or end, and an end date in the future.
This isn't telling me anything that I can't see below. This line can go away.

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        # Unpublished course run with a seat.
Remove.

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        # Published course run with no seats.
Remove

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        no_seats_course_run = CourseRunFactory(status=CourseRunStatus.Published)
Nit: `course_run_without_seats`

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        # Published course run with a seat and an end date in the past.
Remove.

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        archived_course_run = CourseRunFactory(
`closed_course_run`

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +            2 if marketable_enrollable_course_runs_with_archived else 4
No if statements in tests. That's a sign that you need multiple tests. You don't need to test the case where the flag is not active. We already have tests for that. You do, however, need to ensure the correct data is returned, not just the number of course runs.

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        enrollable, including archived courses (with an end date in the past). """
s/courses/course_runs

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.course.course_runs.add(
Pass the course to the factories: `CourseRunFactory(course=self.course)`. Avoid creating other courses unnecessarily. Please correct the other tests in this file that are also creating course runs incorrectly.

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/v1/views/courses.py
>              'exclude_utm': get_query_param(self.request, 'exclude_utm'),
It's time to clean this up. There is a lost of duplication that can be avoided with a simple for-loop.

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/api/v1/views/courses.py
> +                and can be enrolled in, now or in the future.
If the course run can be enrolled in, by definition that is now or in the future. This change doesn't add much value and can be reverted.

2017-02-09 17:18 UTC, clintonb commented on course_discovery/apps/course_metadata/query.py
> +        """ Returns instructor paced course runs that are open for enrollment or self-paced course runs
This has nothing to do with pacing.

2017-02-09 17:23 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> -        closed_course_run = CourseRunFactory(
but based on the definitions in this ticket this course run is archived and not closed. https://openedx.atlassian.net/browse/ECOM-6819
I don't care what this course run is, but we should agree on a team on what these terms actually mean

2017-02-09 17:27 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> -        closed_course_run = CourseRunFactory(
> ...but we should agree on a team on what these terms actually mean

This is why I don't want to touch any of this until we've defined the course lifecycle!

2017-02-09 17:34 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/courses.py
> +                and can be enrolled in, now or in the future.
The enrollable filter only looks for enrollable course runs that are enrollable today, so the way we have defined enrollable there does not include courses which you can enroll in in the future. The existing active filter looks also includes course runs with an enrollment_start date in the future. They are not enrollable. If this is unclear I could change it to something like "and are enrollable or will be enrollable in the future"

2017-02-09 17:35 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/query.py
> +        """ Returns instructor paced course runs that are open for enrollment or self-paced course runs
ok will remove the docstring

2017-02-09 17:39 UTC, clintonb commented on course_discovery/apps/api/v1/views/courses.py
> +                and can be enrolled in, now or in the future.
I like your change. 👍

2017-02-09 18:07 UTC, amangano-edx commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        """ Verify the method returns only course runs currently open for enrollment or opening in the future. """
The `enrollable` method in query.py filters out CourseRuns for which enrollment is opening in the future.

2017-02-09 18:15 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        """ Verify the method returns only course runs currently open for enrollment or opening in the future. """
thanks, fixed

2017-02-09 19:09 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.course.course_runs.add(
Could you clarify why this approach is incorrect, I don't see the difference, or is it just that we use the other approach more often?

2017-02-09 19:12 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> -        closed_course_run = CourseRunFactory(
i don't mind changing this back, but philosophically I thought that us writing the definitions on the ticket and the grooming and planning it as a team meant that we agreed on the definitions as a team. Rather than pushing off defining some of these things into the future, why not make us of things we've already defined now?

2017-02-09 19:20 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.course.course_runs.add(
Calling `CourseRunFactory()` will create a `Course` if none is supplied. That's a bunch of wasted DB calls to create data that is not needed. Just pass the course and the factory will make the correct association at the time the `CourseRun` is created.

2017-02-09 19:23 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> -        closed_course_run = CourseRunFactory(
We have not reached any agreement on these definitions or their implementation.

2017-02-09 19:23 UTC, mikedikan commented on course_discovery/apps/api/tests/test_serializers.py
> -        closed_course_run = CourseRunFactory(
I would agree @MatthewPiatetsky - I thought this horse was already dead.

2017-02-09 19:41 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.course.course_runs.add(
got it, thanks!

2017-02-09 22:06 UTC, clintonb requested changes

2017-02-09 22:06 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        assert len(course_serializer.data['course_runs']) == 2
Less counting, more validating the actual data returned.

2017-02-09 22:06 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        self.course.course_runs.add(
This still needs to be addressed.

2017-02-09 22:06 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        url += '?marketable_enrollable_course_runs_with_archived={}'.format(
Use `.format()` for everything here instead of also mixing in concatenation.

2017-02-09 22:06 UTC, clintonb commented on course_discovery/apps/api/v1/views/courses.py
> +                and can be enrolled in, now or in the future.
This still needs to be addressed.

2017-02-09 22:06 UTC, clintonb commented on course_discovery/apps/course_metadata/query.py
> +        """ Returns course runs that can be enrolled in now.
Returns course runs that are currently open for enrollment.

A course run is considered open for enrollment if its enrollment start date has passed or is `None`, AND its enrollment end date is in the future or is `None`.

2017-02-09 22:06 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        assert set(CourseRun.objects.enrollable()) == {
I am leery of casting to a set on the off-chance that duplicates are returned. I believe the ORM returns items in order of their ID values, if no `order_by` value is set on the model. Given that we don't set an `order_by`, you should be safe doing the following:

```python
assert list(CourseRun.objects.enrollable()) == [enrollable, enrollable_no_enrollment_end, enrollable_no_enrollment_start, enrollable_enrollment_start_in_past]
```

2017-02-09 22:15 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> +        assert len(course_serializer.data['course_runs']) == 2
I am validating in the statement below that the correct course runs below by the course run key. Do I want to verify all the fields even though we're already testing the serializer? The only issue I see with that is since we're using a different serializer to construct the get_expected_data I would need to add this querystring to the other serializer purely for test purposes. It seems bad to do that just for the tests, unless there's a better way to do it

2017-02-09 22:16 UTC, MatthewPiatetsky commented on course_discovery/apps/api/v1/views/courses.py
> +                and can be enrolled in, now or in the future.
ok will change, i thought you meant you liked the original lol

2017-02-09 22:19 UTC, amangano-edx commented on course_discovery/apps/api/tests/test_serializers.py
> +        self.assertCountEqual(course_run_keys, [enrollable_course_run.key, archived_course_run.key])
This seems to be testing that we got two course runs back, not that they are the correct two course runs.

2017-02-09 22:20 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> +        self.assertCountEqual(course_run_keys, [enrollable_course_run.key, archived_course_run.key])
that's not what assertCountEqual does https://docs.python.org/3.6/library/unittest.html#unittest.TestCase.assertCountEqual

however, since we are moving away from unittest i suppose I could change this to sorted()

2017-02-09 22:21 UTC, amangano-edx commented on course_discovery/apps/api/tests/test_serializers.py
> +        self.assertCountEqual(course_run_keys, [enrollable_course_run.key, archived_course_run.key])
Also, I think we should be consistent with our approach to assertions. On line 278, we use a pytest style assertion but here we're using a unittest style assertion.

2017-02-09 22:24 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        enrollable = CourseRunFactory(enrollment_end=future)
If we expect this to always be enrollable, we should set an explicit value for enrollment_start (even if it's just `None`). When it's left unspecified like this, the test may become flaky as the factory may sometimes set a value for enrollment_start that results in the CourseRun being un-enrollable.

2017-02-09 22:32 UTC, amangano-edx commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        enrollable = CourseRunFactory(enrollment_end=future)
I brought this up in one of the other tests, but I think you should explicitly set enrollment_start in addition to enrollment_end if you expect this course run to always be enrollable. Depending on the factory implementation, it may be possible for it to set enrollment_start in a way that would make the course_run unenrollable, which would result in flaky behavior from this test.

2017-02-09 22:34 UTC, amangano-edx commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        assert set(CourseRun.objects.enrollable()) == {
Would it hurt to just add an order_by to the end of that query to ensure that the results are always returned consistently? Doing so would prevent flaky behavior from this test.

2017-02-09 22:49 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        assert set(CourseRun.objects.enrollable()) == {
I was using sorted, order by is just for queries

2017-02-09 22:52 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        assert set(CourseRun.objects.enrollable()) == {
Actually, we do have `ordering` (not `order_by` as I previously stated) set. We inherit `TimeStampedModel`, which returns items in reverse order of their modified and creation dates.

2017-02-09 22:54 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        assert sorted(CourseRun.objects.enrollable()) == sorted([
These items are already sorted: `ordering = ('-modified', '-created',)`. There is no need to call `sorted()`.

2017-02-09 22:56 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        assert sorted(course_run_keys) == sorted([enrollable_course_run.key, archived_course_run.key])
No need for `sorted()`.

2017-02-09 22:59 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        assert len(course_serializer.data['course_runs']) == 2
I don't quite follow you. If the existing methods aren't usable, don't use them. That being said, I mostly concerned that the correct course runs are concerned than the actual data returned for them.

2017-02-09 23:00 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        assert sorted(CourseRun.objects.enrollable()) == sorted([
I'm using sorted to make it clear in the test that we don't care about the order. previously we'd were using assertCountEqual to signal the intention of the test.
it seems to me like if we're using an assert statement in a test, we should the assert should only depend on what we're actually testing, even if other factors will coincidentally pass (the order). Otherwise everytime we see a list we'll have to figure out if the test cares about order or not

2017-02-09 23:00 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        assert len(course_serializer.data['course_runs']) == 2
If we are validating the course run keys, there is no need to validate the count. This line should go away.

2017-02-09 23:02 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        assert sorted(CourseRun.objects.enrollable()) == sorted([
I'd prefer that to be in the form of a comment than assuming another developer will interpret the use of `sorted()` as not caring about order.

2017-02-09 23:11 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        assert sorted(CourseRun.objects.enrollable()) == sorted([
i think that's why i liked assertCountEqual, but ok

2017-02-10 13:49 UTC, MatthewPiatetsky commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        assert sorted(CourseRun.objects.enrollable()) == sorted([
actually added sorted back in both places, though the query may have a set order, the expected results do not. I don't want the tests to only pass if we create the variables in a specific order. There were some boosting tests that were incorrectly passing for that reason previously. So rather than comment to people that they have to expect the variables back in the same order they were created, i'd rather use sorted and add a comment (which I did)

2017-02-10 14:02 UTC, clintonb approved these changes

2017-02-10 14:02 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        Also includes courses with an end date in the past that the test_marketable_course_runs_only
`test_marketable_course_runs_only` is not relevant here.

2017-02-10 14:02 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +        assert len(course_serializer.data['course_runs']) == 2
This line is unnecessary given the assertion below.

2017-02-10 14:02 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        url += '?marketable_enrollable_course_runs_with_archived={}'.format(
Use `.format()` here.

2017-02-10 14:02 UTC, clintonb commented on course_discovery/apps/api/v1/views/courses.py
> +            context.update({
This can be more efficient: `context[query_param] = get_query_param(self.request, query_param)`

2017-02-10 14:02 UTC, clintonb commented on course_discovery/apps/course_metadata/query.py
> +        A course run is considered open for enrollment if its enrollment start date
Add a new line above this one.

2017-02-10 14:02 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        assert sorted(CourseRun.objects.enrollable()) == sorted([
Use `.order_by` on `QuerySets`.

2017-02-10 14:54 UTC, amangano-edx commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        enrollable_enrollment_start_in_past = CourseRunFactory(enrollment_start=past, enrollment_end=future)
this test case is the same as the one on line 76.

2017-02-10 15:00 UTC, amangano-edx commented on course_discovery/apps/api/v1/tests/test_views/test_courses.py
> +        CourseRunFactory(enrollment_end=None, course=self.course)
Should we have set enrollment_start here?

2017-02-10 15:21 UTC, merged

2017-02-10 15:35 UTC, amangano-edx commented
LGTM