Comment widget Course detail page
openedx/course-discovery pull request #645
Opened 2017-02-09 18:52 UTC by awais786

Implement comments widget on course-detail page.

https://openedx.atlassian.net/browse/ECOM-6042

2017-02-09 18:53 UTC, awais786 commented
<img width="949" alt="screen shot 2017-02-09 at 11 52 42 pm" src="https://cloud.githubusercontent.com/assets/445320/22798196/e48c6412-ef22-11e6-8b29-354ae1183ec8.png">

2017-02-09 18:57 UTC, awais786 commented
@bderusha Please review this PR. Its for comments widget on course detail page.

2017-02-10 10:59 UTC, awais786 commented
<img width="1006" alt="screen shot 2017-02-10 at 3 58 37 pm" src="https://cloud.githubusercontent.com/assets/445320/22824451/d5f4ae8c-efa9-11e6-98b6-155d4bb2d0f6.png">

2017-02-10 11:09 UTC, tasawernawaz requested changes

2017-02-10 11:09 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertContains(response, '<div id="approval-widget" class="hidden">')
you are checking for `approval-widget`  but docstring suggest that this test is for studio fields. ?

2017-02-10 11:09 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertContains(response, '<div id="approval-widget" class="">')
same as above

2017-02-10 11:09 UTC, tasawernawaz commented on course_discovery/apps/publisher_comments/forms.py
> +        self.fields['comment'].widget.attrs['rows'] = 4
why you are not adding this using CSS directly?

2017-02-10 11:09 UTC, tasawernawaz commented on course_discovery/static/sass/publisher/course_form.scss
> +  padding-left: 3px;
i18n

2017-02-10 11:11 UTC, awais786 commented on course_discovery/apps/publisher_comments/forms.py
> +        self.fields['comment'].widget.attrs['rows'] = 4
Django providing a way to fix text area size.

2017-02-10 11:18 UTC, awais786 commented
<img width="1004" alt="screen shot 2017-02-10 at 4 17 36 pm" src="https://cloud.githubusercontent.com/assets/445320/22824992/7990823a-efac-11e6-825b-bda343a148b8.png">

2017-02-10 11:30 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertContains(response, '<div id="approval-widget" class="hidden">')
Done

2017-02-10 11:30 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertContains(response, '<div id="approval-widget" class="">')
Done

2017-02-10 11:47 UTC, tasawernawaz approved these changes

2017-02-10 11:48 UTC, awais786 commented
@bderusha Please review.

2017-02-10 14:56 UTC, awais786 commented
@bderusha Please review.

2017-02-10 15:01 UTC, awais786 commented
<img width="1277" alt="screen shot 2017-02-10 at 8 01 21 pm" src="https://cloud.githubusercontent.com/assets/445320/22831318/b9032caa-efcb-11e6-815a-ac5f9d111ac3.png">

2017-02-11 20:43 UTC, bderusha approved these changes

2017-02-11 20:43 UTC, bderusha commented on course_discovery/apps/publisher/tests/test_views.py
> +        'publisher_comment_widget_feature' is disable.
`is disabled`

2017-02-13 09:08 UTC, merged