Create remove_unused_indexes management command
openedx/course-discovery pull request #646
Opened 2017-02-10 02:46 UTC by mikedikan

ECOM-7129

Creating management command to remove older indexes automatically, to clean up dangling elasticsearch indexes.

@edx/ecommerce for review

2017-02-10 03:27 UTC, clintonb requested changes

2017-02-10 03:27 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +from collections import OrderedDict
This is part of Python and should be grouped above.

2017-02-10 03:27 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        # Use the creation timestamp to identify oldest index
This comment doesn't make sense here. Remove it.

2017-02-10 03:27 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        :param indices:
Remove.

2017-02-10 03:27 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +            indices = backend.conn.indices
Use `indicies_client` as the variable name to avoid confusion.

2017-02-10 03:27 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +    def remove_unused_indexes(self, indices):
`indicies_client`

2017-02-10 03:27 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        all_index_settings = indices.get_settings()
All you need to do here is return a sorted list of index names. If you simply sort them alphabetically, you should be all set. No need to look at the settings or return a `dict`.

2017-02-10 03:27 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +                indices.delete(index=index_name)
Create a comma-separated list and delete the indexes in bulk. See http://elasticsearch-py.readthedocs.io/en/1.9.0/api.html#elasticsearch.client.IndicesClient.delete. You shouldn't need a for-loop. It should be possible to use list slicing to pick which indexes need to be removed. Remember to *not* delete anything if there are `settings.HAYSTACK_INDEX_RETENTION_LIMIT`, or fewer, indexes.

2017-02-10 03:27 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +    def reset_sessions(self):
What are the errors?

2017-02-10 03:27 UTC, clintonb commented on course_discovery/settings/base.py
> +HAYSTACK_INDEX_RETENTION_LIMIT = 3
Add documentation to https://github.com/edx/course-discovery/blob/master/docs/edx_extensions.rst.

2017-02-10 03:27 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +            None
No need to document this.

2017-02-11 00:49 UTC, mikedikan commented on course_discovery/settings/base.py
> +HAYSTACK_INDEX_RETENTION_LIMIT = 3
I don't see an obvious place to add documentation on this, did you have an idea of what to say so we avoid back and forth through PR comments?

2017-02-11 01:12 UTC, clintonb commented on course_discovery/settings/base.py
> +HAYSTACK_INDEX_RETENTION_LIMIT = 3
Add documentation at https://github.com/edx/course-discovery/blob/master/docs/edx_extensions.rst.

2017-02-11 01:30 UTC, mikedikan commented on course_discovery/settings/base.py
> +HAYSTACK_INDEX_RETENTION_LIMIT = 3
Sorry, what I mean is, i see the file - what exactly do you want me to say?  "Add documentation" is open ended and difficult to interpret.  The documentation you link has no natural spot for me to mention this variable, and the settings file has several other haystack variables. Are you asking me to describe this one only?  All of them? Some of them? Are you asking me to add a section in this file detailing the management commands and mention that one of them has a settings parameter?    What level of detail are you looking for?  Is there an example I can follow that shows me what your expectations are?

 I'm looking for guidance up front to avoid going through multiple rounds of revision.

2017-02-13 15:24 UTC, clintonb commented on course_discovery/settings/base.py
> +HAYSTACK_INDEX_RETENTION_LIMIT = 3
Add a new section, call it "Settings". Document the new setting. Since it only applies to this custom app, it seems logical to group it there.

2017-02-13 20:30 UTC, clintonb requested changes

2017-02-13 20:30 UTC, clintonb commented on docs/edx_extensions.rst
> +HAYSTACK_INDEX_RETENTION_LIMIT: This field sets an upper bound for the number of indexes that will be retained after
Provide a bit better formatting:
* https://raw.githubusercontent.com/edx/edx-drf-extensions/master/docs/settings.rst
* http://edx-drf-extensions.readthedocs.io/en/latest/settings.html

2017-02-13 20:30 UTC, clintonb commented on docs/edx_extensions.rst
> +a purge triggered by the 'remove_unused_indexes' command.  This command will never delete the currently used index.
The comment about the command not deleting current indexes belongs in the help text/docs for that command. It seems out of place here.

2017-02-13 20:30 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +
Add `help`. See https://docs.djangoproject.com/en/1.10/howto/custom-management-commands/#django.core.management.BaseCommand.help.

2017-02-13 20:30 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        return sorted_indexes_by_timestamp
Merge with the line above.

2017-02-13 20:30 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        # We only have one index for the alias (so we can cheat and refer to the 0th index directly)
Why? Just remove all them. There will almost always be one; but, we shouldn't make an assumption here.

2017-02-13 20:30 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        logger.debug('Found {index_count} indexes'.format(index_count=index_count))
Debug-level log entries don't go to Splunk, making them useless outside of local development. Use `.info()`.

2017-02-13 20:30 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        index_index = 0  # ;)
Save the time/resources and just delete in bulk.

```python
num_indices_to_remove = len(sorted_indexes_by_timestamp) - settings.HAYSTACK_INDEX_RETENTION_LIMIT

if num_indices_to_remove > 0:
  indices_to_remove = sorted_indexes_by_timestamp[:num_indices_to_remove]
  logger.info('Deleting indices %s...', indices_to_remove)
  indices_client.delete(index=','.join(indices_to_remove))
  logger.info('Successfully deleted indices %s.', indices_to_remove)
else:
  logger.info('No indicies to remove.')
```

2017-02-13 20:30 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +        update_index_command = Command()
There should not be a reliance on another command to test this command. Move shared code to [`ElasticsearchUtils`](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/core/utils.py#L11) (and add the appropriate tests).

2017-02-13 20:30 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +        response = connection.indices.get_settings()
This is never used.

2017-02-13 20:30 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +        self.assertEqual(len(response), expected_count)
The purpose of these tests should be to ensure that the *correct* indexes are removed, not just a certain number. You want to ensure the currently aliased index is not removed. If the number of indexes on the host is less than the number of indexes to remove, you want to ensure no indexes are removed.

Also, you should be using `assert` now that we are using `pytest`.

2017-02-13 20:30 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +        connection = Elasticsearch(host)
You already have a backend. Use `backend.conn`.

2017-02-13 20:49 UTC, mikedikan commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        logger.debug('Found {index_count} indexes'.format(index_count=index_count))
This seemed like it wasn't appropriate for splunk.

2017-02-13 20:50 UTC, mikedikan commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        # We only have one index for the alias (so we can cheat and refer to the 0th index directly)
What?

2017-02-13 21:00 UTC, mikedikan commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +        self.assertEqual(len(response), expected_count)
I can add tests for those two scenarios you describe, but the count still seems like the appropriate way to do it.

2017-02-13 21:05 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        logger.debug('Found {index_count} indexes'.format(index_count=index_count))
If it's not going to Splunk, the statement is not that useful.

2017-02-13 21:05 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        # We only have one index for the alias (so we can cheat and refer to the 0th index directly)
We can easily account for the case where an alias might reference two distinct indices. Just do that instead of assuming the alias will only point to one index.

`sorted_indexes_by_timestamp = set(sorted_indexes_by_timestamp) - set(current_alias.keys())`

2017-02-13 21:05 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +        self.assertEqual(len(response), expected_count)
The count doesn't assert that the indexes we expect to be removed are removed or that the live index remains untouched.

2017-02-13 21:05 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +            update_index_command.create_timestamped_index(backend=backend, prefix=backend.index_name)
Make sure you delete any additional indices created by these tests. `ElasticsearchTestMixin.delete_index()` has an example method. Ideally, the cleanup should happen in either the `tearDown()` or `tearDownClass()` method. You should be able to use a wildcard call to delete all indices matching `catalog_test_*`.

2017-02-13 21:07 UTC, mikedikan commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        logger.debug('Found {index_count} indexes'.format(index_count=index_count))
I disagree, i found it helpful during development, and think other developers might as well.

2017-02-13 21:12 UTC, rock345 commented
@clintonb can you call out nits?

2017-02-13 21:17 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        logger.debug('Found {index_count} indexes'.format(index_count=index_count))
@mikedikan I can tell you from experience that this and other debug messages here will be useful to have in Splunk when something inevitably goes wrong. For example, take a look at how I did the logging for the LMS' program certificate [backpopulation command](https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/programs/management/commands/backpopulate_program_credentials.py#L40).

Keep in mind that the people running these commands are often not intimately familiar with the code, and these messages can help to quickly diagnose problems.

2017-02-13 21:26 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        logger.debug('Found {index_count} indexes'.format(index_count=index_count))
Another way to say it: if you found it helpful during development, we're going to find it helpful in a production setting when we need to figure out what the command did. Detailed logging has proven to be useful. Please use `.info()`.

2017-02-13 21:31 UTC, clintonb commented
@rock345 the only item that might be considered a nit-pick is the use of `logging.debug()`. Other than that every other comment needs to be addressed before I approve this pull request.

2017-02-15 06:19 UTC, mikedikan commented
@clintonb This is ready for another pass.  Note there were several changes here due to the refactoring to use the shared index create util.  I suspect I can further reduce the code duplication, but I am concerned that this call might be doing something important:

https://github.com/edx/course-discovery/blob/master/course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py#L30

If that is not important, the entire update_index command is redundant code that can be eliminated, see https://github.com/edx/course-discovery/blob/master/course_discovery/apps/core/management/commands/install_es_indexes.py

2017-02-15 07:52 UTC, clintonb approved these changes
The call to `super(Command, self).handle(*items, **options)` in `update_index.py` is quite important—it does the actual indexing. The rest of the file is simply ensuring we are operating on an index with a timestamped name.

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/core/utils.py
> +            es_connection (Elasticsearch): Elasticsearch connection - (ElasticsearchSearchBackend.conn)
Nit: the parenthetical is confusing and should be removed.

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/core/utils.py
> +    def create_index(cls, es_connection, alias):
s/alias/prefix

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/core/utils.py
> +        timestamp = datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S")
Nit: single quotes

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/remove_unused_indexes.py
> +        # We only have one index for the alias (so we can cheat and refer to the 0th index directly)
This comment makes no sense with the current code.

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +            assert (index_to_keep in all_indexes) is True
No need for the parentheses or `is True`

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +        self.backend.conn.indices.delete(index='catalog_test_*')
This prefix should come from the Haystack settings: https://github.com/edx/course-discovery/blob/master/course_discovery/settings/shared/test.py#L7

`self.backend.index_name + '_*'`

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +        backends = list(haystack_connections.connections_info.keys())
The odds of using a connection other than `'default'` *for tests* are quite low. You can simplify this by simply calling `self.backend = haystack_connections['default'].get_backend()` in `setUp()`, and removing this method.

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_update_index.py
> +        self.backend.conn.indices.delete(index='catalog_test_*')
Move this setup/teardown behavior to a mixin to avoid duplication.

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_update_index.py
> +        index = '{alias}_20160621000000'.format(alias=alias)
The index naming scheme should not be changing.

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/core/utils.py
> +        timestamp = datetime.datetime.utcnow().strftime("%Y%m%d%H%M%S")
Keep the underscore between the date and time so the index names are easier for humans to parse: `'%Y%m%d_%H%M%S'`.

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +            assert (index_to_keep in all_indexes) is True
Also, this can be simplified: `assert set(all_indexes).issuperset(set(indexes_to_keep))`

2017-02-15 07:52 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +        # check that we keep the current indexes, which we don't want removed
Same as above: `assert set(all_indexes).issuperset(set(indexes_to_keep))`.

2017-02-15 19:38 UTC, mikedikan commented on course_discovery/apps/edx_haystack_extensions/tests/test_remove_unused_indexes.py
> +            assert (index_to_keep in all_indexes) is True
How is that a simplification?

2017-02-15 22:15 UTC, clintonb approved these changes

2017-02-15 22:15 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +        # index_name = self.create_timestamped_index(backend, alias)
This should be removed.

2017-02-15 22:15 UTC, clintonb commented on course_discovery/apps/core/utils.py
> +        timestamp = datetime.datetime.utcnow().strftime("%Y%m%d_%H%M%S")
Single quotes.

2017-02-15 23:01 UTC, merged