Inconsistent datetime formats in Course Catalog API
openedx/course-discovery pull request #661
Opened 2017-02-14 09:36 UTC by ahsan-ul-haq

ECOM-4354

2017-02-14 14:21 UTC, clintonb requested changes
We do NOT want fractional seconds in the API responses. Also, this should be handle via settings: http://www.django-rest-framework.org/api-guide/settings/#date-and-time-formatting

2017-02-14 17:54 UTC, clintonb commented
See https://github.com/tomchristie/django-rest-framework/blob/a68b37d8bc432fae37ef5880aec500002b59f565/rest_framework/utils/humanize_datetime.py#L10.

We want to use that format without the optional milliseconds. After discussing with @schenedx, always show milliseconds: `'YYYY-MM-DDThh:mm:ss.uuuuuu[+HH:MM|-HH:MM|Z]'`

2017-02-15 12:00 UTC, ahsan-ul-haq commented
@clintonb I think with %f it will always show milliseconds. Do I need to do something else?

2017-02-15 13:50 UTC, clintonb commented
Use the setting intead of modifying each serializer field.

2017-02-15 13:59 UTC, ahsan-ul-haq commented
@clintonb please review

2017-02-15 14:10 UTC, clintonb requested changes

2017-02-15 14:10 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    upgrade_deadline = serializers.DateTimeField(format=settings.API_DATETIME_FORMAT)
You should not need to change any of these serializers.

2017-02-15 14:10 UTC, clintonb commented on course_discovery/apps/api/v1/views/course_runs.py
> +              description: Filter based on weather the course run is hidden from search.
whether

2017-02-15 14:10 UTC, clintonb commented on course_discovery/settings/base.py
> +API_DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S.%fZ'
http://www.django-rest-framework.org/api-guide/settings/#date-and-time-formatting

```python
REST_FRAMEWORK = {
  # NOTE: This is the same format as DRF's iso-8601, however the milliseconds are always rendered.
  'DATETIME_FORMAT': 'YYYY-MM-DDThh:mm:ss.uuuuuu[+HH:MM|-HH:MM|Z]',
}
```

2017-02-15 14:24 UTC, ahsan-ul-haq commented
@clintonb made the change

2017-02-15 14:31 UTC, clintonb commented on course_discovery/settings/base.py
> +    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S.%fZ',
Please use this exact string: `'YYYY-MM-DDThh:mm:ss.uuuuuu[+HH:MM|-HH:MM|Z]'` to avoid issues with time zones.

2017-02-15 14:53 UTC, ahsan-ul-haq commented on course_discovery/settings/base.py
> +    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S.%fZ',
@clintonb Doing that causes the dates time to appear like following
<img width="416" alt="screen shot 2017-02-15 at 7 49 14 pm" src="https://cloud.githubusercontent.com/assets/7567613/22979502/6be9b75e-f3b8-11e6-8d2e-d151064eee93.png">

2017-02-15 14:55 UTC, ahsan-ul-haq commented
I have made change for time zone as well

2017-02-15 15:16 UTC, schenedx commented on course_discovery/settings/base.py
> +    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S.%fZ',
@clintonb I read the DRF documentation again. They require python strftime format string. See http://www.django-rest-framework.org/api-guide/settings/#datetime_format

So `YYYY-MM-DDThh:mm:ss.uuuuuu[+HH:MM|-HH:MM|Z]` is not a python strftime format. It's just a format they use on datetime string to replace `iso-8601`.

2017-02-15 15:16 UTC, schenedx approved these changes
👍

2017-02-15 15:18 UTC, schenedx commented
@ahsan-ul-haq You got 8 unit test failures, could you please investigate?

2017-02-16 09:26 UTC, closed without merging