Added mark as reviewed functionality for parent course.
openedx/course-discovery pull request #662
Opened 2017-02-14 09:38 UTC by waheedahmed

[ECOM-6347](https://openedx.atlassian.net/browse/ECOM-6347)

As a Course team reviewer or Marketing reviewer, I need to be able to mark a Parent Course as reviewed, so that the About page process can move to the next stage in the workflow.

<img width="504" alt="screen shot 2017-02-14 at 1 07 32 pm" src="https://cloud.githubusercontent.com/assets/2851134/22923430/44ac1a06-f2c3-11e6-9ffd-59b0b0d3af31.png">
<img width="511" alt="screen shot 2017-02-14 at 1 07 03 pm" src="https://cloud.githubusercontent.com/assets/2851134/22923432/44dc9c30-f2c3-11e6-9046-2415b744d5d3.png">
<img width="578" alt="screen shot 2017-02-14 at 2 17 04 pm" src="https://cloud.githubusercontent.com/assets/2851134/22923433/45007592-f2c3-11e6-88dd-37adb9c5a38a.png">

2017-02-14 11:52 UTC, waheedahmed commented
@tasawernawaz @awais786 Please review.

2017-02-14 13:27 UTC, waheedahmed commented
@bderusha Please review.

2017-02-15 07:44 UTC, tasawernawaz commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        self.assertNotEqual(self.course_state.name, CourseStateChoices.Approved)
I think we don't need this because we already making course state as 'review'

2017-02-15 07:55 UTC, tasawernawaz requested changes

2017-02-15 07:55 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_emails.py
> +    def test_email_with_error(self):
Can we move successful email sent tests here from https://github.com/edx/course-discovery/pull/662/files#diff-87bb42cd9546e429d9e0d0cbc7374706R169

2017-02-15 07:55 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_emails.py
> +    def test_email_with_error(self):
same here,

2017-02-15 09:45 UTC, tasawernawaz approved these changes

2017-02-15 09:47 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_emails.py
> +    def test_email_with_error(self):
I wrote these test to fix the coverage for exception clauses of email sending functions.

2017-02-15 09:47 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_emails.py
> +    def test_email_with_error(self):
same answer.

2017-02-15 09:50 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_emails.py
> +    def test_email_with_error(self):
Successful email sent functionality should be tested in changing state tests.

2017-02-16 11:07 UTC, awais786 commented on course_discovery/apps/publisher/views.py
> +            if is_internal_user(user):
Can you please divide the following code into separate methods with some doc-strings.

2017-02-16 11:27 UTC, awais786 approved these changes

2017-02-16 11:36 UTC, merged