Course-run approval widget.
openedx/course-discovery pull request #669
Opened 2017-02-16 06:47 UTC by awais786

ECOM-6076

2017-02-17 11:23 UTC, waheedahmed requested changes
First pass completed.

2017-02-17 11:23 UTC, waheedahmed commented on course_discovery/apps/publisher/api/tests/test_views.py
> +        self.course_run.staff = [staff]
`self.course_run.staff.add(PersonFactory())`

2017-02-17 11:23 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course_run.save()
No need for above three lines, just do this `self.course_run.staff.add(PersonFactory())`

2017-02-17 11:23 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course_run.save()
No need to call save just do this `self.course_run.staff.add(staff)`

2017-02-17 11:23 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course_run.is_micromasters = True
I think you don't need to set value for `is_micromasters` and `micromasters_name` here, if `is_micromasters` is `False`, `is_valid_micromasters` will always return True.

2017-02-17 11:23 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course.course_state.name = CourseStateChoices.Draft
You should assert true at top to check that `can_send_for_review()` is returning `True`. Then make test assert False after changing values.

2017-02-17 11:23 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course_run.is_micromasters = False
Same here, you should assert true at top to check that `can_send_for_review()` is returning `True`. Then make test assert False after changing values.

2017-02-17 11:23 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.seat.price = 0
Same here, you should assert true at top to check that `can_send_for_review()` is returning `True`. Then make test assert False after changing values.

2017-02-17 11:23 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course_run.seats.all().first().delete()
Same here, you should assert true at top to check that `can_send_for_review()` is returning `True`. Then make test assert False after changing values.

2017-02-17 11:23 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course_run.language = None
Same here, you should assert true at top to check that `can_send_for_review()` is returning `True`. Then make test assert False after changing values.

2017-02-17 11:23 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course_run.transcript_languages = []
Same here, you should assert true at top to check that `can_send_for_review()` is returning `True`. Then make test assert False after changing values.

2017-02-17 11:23 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +    def test_course_approval_widget_disabled_button(self):
No need for this test case, you are already doing this in `test_course_run_approval_widget_for_course_team` at line 1075.

2017-02-17 13:44 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.seat.price = 0
Done

2017-02-17 13:44 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course_run.seats.all().first().delete()
Done

2017-02-17 13:44 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course_run.language = None
Done

2017-02-17 13:44 UTC, awais786 commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course_run.transcript_languages = []
Done

2017-02-20 07:55 UTC, waheedahmed requested changes

2017-02-20 07:55 UTC, waheedahmed commented on course_discovery/apps/publisher/models.py
> +        if not self.staff.all().exists():
Create a variable `staff_members = self.staff.all()` and use that variable on both places, it will reduce query count. Also you don't need to call `exists()`, you can simply do the following:
```
if not staff_members:
    return False
```

2017-02-20 07:55 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_model.py
> +        self.course_run.is_micromasters = True
You don't need to set this True for every test just move this line into its test case and remove next line.

2017-02-20 08:59 UTC, tasawernawaz approved these changes

2017-02-20 09:03 UTC, waheedahmed approved these changes

2017-02-20 09:04 UTC, waheedahmed approved these changes
👍 when build passes.

2017-02-20 11:14 UTC, merged