check added for parent course not approved state
openedx/course-discovery pull request #672
Opened 2017-02-17 09:46 UTC by tasawernawaz

[ECOM-6290](https://openedx.atlassian.net/browse/ECOM-6290)

- [ ]  [ECOM-7158](https://openedx.atlassian.net/browse/ECOM-7158) front end design.
- [ ]  [ECOM-7157](https://openedx.atlassian.net/browse/ECOM-7157) add "approved parent course" check to all states.

**Screenshot:**

<img width="569" alt="screen shot 2017-02-17 at 2 46 23 pm" src="https://cloud.githubusercontent.com/assets/4245618/23060524/e7c91a6e-f51f-11e6-889e-1742a717cab7.png">

2017-02-20 12:45 UTC, tasawernawaz commented
@awais786 @waheedahmed Please review.

2017-02-20 13:06 UTC, waheedahmed requested changes

2017-02-20 13:06 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertNotIn(response.content.decode('utf-8'), '<div class="parent-course-approval">')
`self.assertNotContains(response, '<div class="parent-course-approval">')`

2017-02-20 13:06 UTC, waheedahmed commented on course_discovery/templates/publisher/_approval_widget.html
> +      {% if not object.course.course_state.is_approved %}
You can achieve above both in single statement.
`{% if is_course_run and not object.course.course_state.is_approved %}`

2017-02-20 13:32 UTC, tasawernawaz commented
@waheedahmed Made suggested changes, Please take another look.

2017-02-20 13:33 UTC, waheedahmed approved these changes

2017-02-21 07:44 UTC, awais786 approved these changes

2017-02-21 07:44 UTC, merged