Preview widget approval.
openedx/course-discovery pull request #675
Opened 2017-02-21 13:16 UTC by waheedahmed

[ECOM-7168](https://openedx.atlassian.net/browse/ECOM-7168)

As a Course team reviewer, I need to be able to view the preview page so that I can approve the preview.

<img width="503" alt="screen shot 2017-02-21 at 6 14 40 pm" src="https://cloud.githubusercontent.com/assets/2851134/23166237/aa4ba84c-f861-11e6-973e-bb6db5d13632.png">
---------------------------------------------------------------------------------------------------
<img width="753" alt="screen shot 2017-02-21 at 6 15 42 pm" src="https://cloud.githubusercontent.com/assets/2851134/23166270/ce4185c8-f861-11e6-82cd-d330f44df76b.png">
---------------------------------------------------------------------------------------------------
<img width="502" alt="screen shot 2017-02-21 at 6 14 11 pm" src="https://cloud.githubusercontent.com/assets/2851134/23166238/aa4bb3dc-f861-11e6-81a3-7effbfaa9d49.png">

2017-02-21 13:38 UTC, waheedahmed commented
@tasawernawaz @awais786 Please review.

2017-02-22 07:02 UTC, tasawernawaz requested changes

2017-02-22 07:02 UTC, tasawernawaz commented on course_discovery/apps/publisher/api/serializers.py
> +        elif preview_accepted:
Do we need to change class name because now we are also updating course run other than changing state.

2017-02-22 07:02 UTC, tasawernawaz commented on course_discovery/apps/publisher/api/tests/test_serializers.py
> +        self.assertFalse(self.run_state.preview_accepted)
update docstring of this test.

2017-02-22 07:02 UTC, tasawernawaz commented on course_discovery/apps/publisher/emails.py
> +                'contact_us_email': partner_coordinator.email if partner_coordinator else '',
is this a possibility that we will not have `partner_coordinator` ?

2017-02-22 07:02 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_emails.py
> +    """ Tests email functionality of course review. """
nit: "course preview"

2017-02-22 07:02 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_emails.py
> +        # add user in course-user-role table
nit "users"

2017-02-22 07:11 UTC, waheedahmed commented on course_discovery/apps/publisher/api/serializers.py
> +        elif preview_accepted:
@tasawernawaz No, its `CourseRunState` model's serializer and we are only updating this model fields.

2017-02-22 07:13 UTC, waheedahmed commented on course_discovery/apps/publisher/emails.py
> +                'contact_us_email': partner_coordinator.email if partner_coordinator else '',
@tasawernawaz Yes by mistake publisher admin forgot to add one for some org otherwise not.

2017-02-22 07:18 UTC, waheedahmed commented on course_discovery/apps/publisher/api/tests/test_serializers.py
> +        self.assertFalse(self.run_state.preview_accepted)
Done.

2017-02-22 07:18 UTC, waheedahmed commented
@tasawernawaz Feedback addressed, please take another look.

2017-02-22 07:50 UTC, tasawernawaz approved these changes
Once build pass. 👍

2017-02-22 07:53 UTC, awais786 approved these changes

2017-02-22 08:10 UTC, merged