WIP: ECOM-6077 preview widget publisher role
openedx/course-discovery pull request #676
Opened 2017-02-21 13:58 UTC by tasawernawaz

[ECOM-6077](https://openedx.atlassian.net/browse/ECOM-6077)

2017-02-22 10:17 UTC, tasawernawaz commented
@awais786  @waheedahmed Please review.

2017-02-22 10:55 UTC, waheedahmed requested changes

2017-02-22 10:55 UTC, waheedahmed commented on course_discovery/templates/publisher/course_run_detail/_widgets.html
> +                            <span class="preview-status">{% trans "Submitted for review" %}</span>
In prototype its `Out for review`.

2017-02-22 10:55 UTC, waheedahmed commented on course_discovery/static/js/publisher/publisher.js
> +function showError() {
Use more precise name, this doesn't explain which error you are showing here.

2017-02-22 10:55 UTC, waheedahmed commented on course_discovery/static/js/publisher/publisher.js
> +            'preview_url': preview_url
Move this above and make it single line.

2017-02-22 10:55 UTC, waheedahmed commented on course_discovery/apps/publisher/tests/test_views.py
> +        """Verify that user with  "Publisher Role" can see preview widget. """
Verify that publisher user can see preview widget.

2017-02-22 10:55 UTC, waheedahmed commented on course_discovery/apps/publisher/emails.py
> +    """ Send email for when preview is available to course team.
Send email for course preview available to course team.

2017-02-22 10:55 UTC, waheedahmed commented on course_discovery/apps/publisher/api/serializers.py
> +    def update(self, instance, validated_data):
What if an error occurred during sending email, do we need to rollback the transaction? because course team will not get a notification that a preview url is added but publisher will think he added it.

I think you should use `@transaction.atomic` here.

2017-02-22 10:58 UTC, waheedahmed requested changes
You should change `owner_role=CourseTeam` and also update the `owner_role_modified`.

2017-02-22 11:00 UTC, tasawernawaz commented on course_discovery/templates/publisher/course_run_detail/_widgets.html
> +                            <span class="preview-status">{% trans "Submitted for review" %}</span>
In ticket its mentioned use "Submitted for review"

2017-02-22 11:24 UTC, waheedahmed requested changes

2017-02-22 11:24 UTC, waheedahmed commented on course_discovery/apps/publisher/api/serializers.py
> +        instance.owner_role = PublisherUserRole.CourseTeam
I think `instance` is a CourseRun object here not a `CourseRunState`.
```
instance.course_run_state.owner_role = PublisherUserRole.CourseTeam
instance.course_run_state.owner_role_modified = timezone.now()
instance.course_run_state.save()
```

2017-02-22 11:25 UTC, waheedahmed commented on course_discovery/apps/publisher/api/serializers.py
> +        instance.owner_role = PublisherUserRole.CourseTeam
Also verify this in its tests.

2017-02-22 11:27 UTC, waheedahmed commented on course_discovery/apps/publisher/api/views.py
> +    permission_classes = (IsAuthenticated,)
I think we `PublisherUser` can only update this, so we should add that permission class also.

2017-02-22 12:33 UTC, awais786 commented on course_discovery/apps/publisher/api/serializers.py
> +        instance.course_run_state.owner_role = PublisherUserRole.CourseTeam
Make method in course-run-state model and pass the role.
Save the modified time there also.

2017-02-23 09:30 UTC, waheedahmed approved these changes
One minor comment.

2017-02-23 09:30 UTC, waheedahmed commented on course_discovery/apps/publisher/api/serializers.py
> +class UpdateCourseRunSerializer(serializers.ModelSerializer):
`CourseRunSerializer`

2017-02-23 11:25 UTC, waheedahmed approved these changes

2017-02-23 13:48 UTC, awais786 approved these changes

2017-02-23 13:48 UTC, merged