Awais786/ecom 6330 decline
openedx/course-discovery pull request #681
Opened 2017-02-23 07:15 UTC by awais786

WIP

2017-02-23 11:46 UTC, awais786 commented
<img width="522" alt="screen shot 2017-02-23 at 4 07 44 pm" src="https://cloud.githubusercontent.com/assets/445320/23257864/6d8eada0-f9e7-11e6-9ba9-d80896af965c.png">
-----------------------------

<img width="517" alt="screen shot 2017-02-23 at 4 08 06 pm" src="https://cloud.githubusercontent.com/assets/445320/23257881/80aa02cc-f9e7-11e6-85bd-3fa5a1ad537e.png">
------------------------------
<img width="516" alt="screen shot 2017-02-23 at 4 11 48 pm" src="https://cloud.githubusercontent.com/assets/445320/23257890/8cc86490-f9e7-11e6-8914-bb63616857d9.png">

2017-02-23 12:59 UTC, tasawernawaz requested changes

2017-02-23 12:59 UTC, tasawernawaz commented on course_discovery/apps/publisher/emails.py
> +        message = 'Failed to send email notifications for preview approved of course-run [{}].'.format(course_run.id)
nit: add variable name in `{}`.

2017-02-23 12:59 UTC, tasawernawaz commented on course_discovery/apps/publisher/models.py
> +        Change owner role.
Please make docstring more descriptive.

2017-02-23 12:59 UTC, tasawernawaz commented on course_discovery/apps/publisher/tests/test_model.py
> +        Verify that property change_owner_role updates the role.
It is not a property.

2017-02-23 12:59 UTC, tasawernawaz commented on course_discovery/apps/publisher_comments/emails.py
> +        # 'title' will be the value of course title.
update comments

2017-02-23 12:59 UTC, tasawernawaz commented on course_discovery/apps/publisher_comments/emails.py
> +    """ Send the emails for a comment.
update

2017-02-23 12:59 UTC, tasawernawaz commented on course_discovery/apps/publisher_comments/emails.py
> +        message = 'Decline preview fail to send email notifications for course run [{}].'.format(course_run.id)
'Failed to send email notifications for preview decline for course-run'

2017-02-23 12:59 UTC, tasawernawaz commented on course_discovery/apps/publisher_comments/models.py
> +                preview_url = course_run.preview_url
I think this functionality should be part of the `save` method not `send_email`.

2017-02-23 12:59 UTC, tasawernawaz commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +    def test_decline_preview_comment(self):
nit: `test_decline_preview_email`

2017-02-23 12:59 UTC, tasawernawaz commented on course_discovery/apps/publisher_comments/tests/test_emails.py
> +        self.course_run.preview_url = 'http://'
add example url for better readability.

2017-02-23 12:59 UTC, tasawernawaz commented on course_discovery/static/js/publisher/comments.js
> +        frm_comment = $(this).closest("#frm_comment");
on both lines you are using same selector '$(this).closest("#frm_comment")', you can declare it first then reuse it.

2017-02-24 10:21 UTC, waheedahmed requested changes

2017-02-24 10:21 UTC, waheedahmed commented on course_discovery/apps/publisher/models.py
> -    def change_role(self, role):
Just rename this one instead of creating new.

2017-02-24 10:21 UTC, waheedahmed commented on course_discovery/static/js/publisher/comments.js
> +    var frm_comment = $(this).closest("#frm_comment");
Use single `var` and also move them at top.
```
var frm_comment = $(this).closest("#frm_comment"),
    comment_box = frm_comment.find("#id_comment");
```

2017-02-24 10:21 UTC, waheedahmed commented on course_discovery/templates/comments/add_auth_comments.html
> +                        <input type="button" value="Submit" class="btn btn-neutral btn-add-comment" />
i18n support for value please.

2017-02-24 10:21 UTC, waheedahmed commented on course_discovery/templates/comments/add_auth_comments.html
> +                        <input type="button" value="Add comment" class="btn btn-brand btn-small btn-course-add btn-add-comment" />
same here.

2017-02-24 10:21 UTC, waheedahmed commented on course_discovery/templates/publisher/course_run_detail/_widgets.html
> +            {% include 'comments/add_auth_comments.html' with comment_type='decline_preview' box_label='Reason for declining preview' btn_label='Submit' %}
i18n support for `box_label='Reason for declining preview'`.

2017-02-24 11:48 UTC, waheedahmed commented on course_discovery/templates/comments/add_auth_comments.html
> +                        <input type="button" value="Submit" class="btn btn-neutral btn-add-comment" />
Also use button element instead input type button.

2017-02-24 11:48 UTC, waheedahmed commented on course_discovery/templates/comments/add_auth_comments.html
> +                        <input type="button" value="Add comment" class="btn btn-brand btn-small btn-course-add btn-add-comment" />
Also use button element instead input type button.

2017-02-24 14:06 UTC, awais786 commented
@tasawernawaz @waheedahmed Please review.

2017-02-24 14:30 UTC, waheedahmed approved these changes

2017-02-27 09:27 UTC, tasawernawaz approved these changes

2017-02-27 09:27 UTC, merged