lms_course_id set as blank=False
openedx/course-discovery pull request #706
Opened 2017-03-02 07:48 UTC by awais786

Remove blank=True from lms_course_id

[ECOM-6931](https://openedx.atlassian.net/browse/ECOM-6931)

2017-03-02 07:48 UTC, awais786 commented
<img width="1004" alt="screen shot 2017-03-01 at 10 10 50 pm" src="https://cloud.githubusercontent.com/assets/445320/23497770/90098f58-ff46-11e6-9a97-0a86529d0a31.png">

2017-03-02 07:52 UTC, awais786 commented
@waheedahmed @tasawernawaz Please review this PR.

2017-03-02 07:53 UTC, awais786 commented
We don't need to override the clean method in admin. Because now without data form will not submit.

2017-03-02 08:21 UTC, tasawernawaz commented on course_discovery/apps/publisher/models.py
> +    lms_course_id = models.CharField(max_length=255, unique=True, null=True)
I think this will effect course/course_run edit pages as well, we will not able to submit form with providing value of `lms_course_id`. Can you confirm ?

2017-03-02 08:22 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +    lms_course_id = models.CharField(max_length=255, unique=True, null=True)
https://github.com/edx/course-discovery/blob/master/course_discovery/apps/publisher/forms.py#L237

2017-03-02 11:42 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +    lms_course_id = forms.CharField(required=True)
@awais786 No need to make `lms_course_id` required, I think only we need to change it to `None` if `lms_course_id` is not provided because we don't want to save it as empty string.

@bderusha You thoughts ?

2017-03-02 11:43 UTC, awais786 commented on course_discovery/apps/publisher/forms.py
> +    lms_course_id = forms.CharField(required=True)
@tasawernawaz in that we need to override the clean method only.

2017-03-02 11:47 UTC, tasawernawaz commented on course_discovery/apps/publisher/forms.py
> +    lms_course_id = forms.CharField(required=True)
@awais786 Yes that's enough I think.

2017-03-03 01:43 UTC, bderusha requested changes

2017-03-03 01:43 UTC, bderusha commented on course_discovery/apps/publisher/forms.py
> +    lms_course_id = forms.CharField(required=True)
Per our conversation offline, please make `required=False`

2017-03-03 13:09 UTC, awais786 commented
@waheedahmed Please review.

2017-03-03 13:50 UTC, waheedahmed approved these changes

2017-03-03 13:58 UTC, awais786 commented
@bderusha please review.

2017-03-03 18:28 UTC, awais786 commented
@bderusha please review.

2017-03-06 14:18 UTC, awais786 commented
@bderusha please review.

2017-03-06 16:31 UTC, bderusha approved these changes

2017-03-07 06:54 UTC, merged