Preview available email.
openedx/course-discovery pull request #708
Opened 2017-03-02 10:43 UTC by waheedahmed

[ECOM-6084](https://openedx.atlassian.net/browse/ECOM-6084)

As a Publisher tool owner, I'd like an email template created which will be used to send emails to Course Team when a Preview link has been added by the Publisher.

<img width="669" alt="screen shot 2017-03-02 at 3 01 02 pm" src="https://cloud.githubusercontent.com/assets/2851134/23503818/fd06bee2-ff5e-11e6-9f2a-1582f6342c0d.png">

2017-03-02 12:32 UTC, waheedahmed commented
@tasawernawaz @awais786 Please review.

2017-03-03 01:41 UTC, bderusha requested changes

2017-03-03 01:41 UTC, bderusha commented on course_discovery/apps/publisher/api/serializers.py
> +    @transaction.atomic
Can you comment (here, not in the code) as to why this was added.  Just curious

2017-03-03 01:41 UTC, bderusha commented on course_discovery/templates/publisher/email/course_run/preview_available.html
> +    edX {{ sender_role }}
Same note here as the other PR. Please use dynamic site name here

2017-03-03 11:14 UTC, waheedahmed commented on course_discovery/apps/publisher/api/serializers.py
> +    @transaction.atomic
@bderusha This was added if some error occurred during sending email, then user will not get an email notification and the user who is updating course_key or preview_url will think he has done his part but the course team user did not get any email, so he does not know a preview is available or studio instance is created for the course.

So I'm rolling back the whole transaction if some error occurred to let user know that there was an error during updating course_key or preview_url.

2017-03-03 11:14 UTC, waheedahmed commented on course_discovery/templates/publisher/email/course_run/preview_available.html
> +    edX {{ sender_role }}
@bderusha Yeah it should be, but not mentioned in any ticket.

2017-03-03 13:53 UTC, awais786 approved these changes

2017-03-03 13:55 UTC, waheedahmed commented on course_discovery/templates/publisher/email/course_run/preview_available.html
> +    edX {{ sender_role }}
I think we should create a ticket to fix it every where in publisher.

2017-03-06 09:50 UTC, waheedahmed commented on course_discovery/templates/publisher/email/course_run/preview_available.html
> +    edX {{ sender_role }}
Done.

2017-03-06 14:27 UTC, waheedahmed commented
@bderusha Feedback addressed, please take another look.

2017-03-06 16:27 UTC, bderusha approved these changes

2017-03-08 09:22 UTC, merged