add support for course run key in catalog contains endpoint
openedx/course-discovery pull request #721
Opened 2017-03-08 11:46 UTC by zubair-arbi

ENT-201

@saleem-latif @asadiqbal08 @mattdrayer @clintonb @cpennington 
Update the endpoint `contains` of `CatalogViewSet` to accept a new optional parameter `course_run_id`. This new parameter will be used for validating if the course run keys of the format `org/course/run` or `course-v1:org+course+run` exists in a catalog.

For example in `Ecom` we can use this endpoint like this:
```python
>>> course_ids = 'edX+TEST_01'
>>> course_run_ids = 'org/course/run,course-v1:edX+DemoX+Demo_Course'
>>> catalog_id = 1
>>> response = site.siteconfiguration.course_catalog_api_client.catalogs(catalog_id).contains.get(
    course_id=course_ids,
    course_run_id=course_run_ids,
)
>>> response
{u'courses': {u'edX+TEST_01': True, u'org/course/run': False, u'course-v1:edX+DemoX+Demo_Course': True}}
```

**Related PR:** [ENT-211 add aggregate course key](https://github.com/edx/opaque-keys/pull/87)

2017-03-08 11:50 UTC, zubair-arbi commented
@clintonb Please review this PR and let me know your thoughts on whether we still need the PR [ENT-211 add aggregate course key](https://github.com/edx/opaque-keys/pull/87)?
One possibility I can think of for the aggregate course key is for validating the input key provided to the catalog contains endpoint.

Our base requirement was to validate if a course run in the basket is available for a catalog.

2017-03-09 04:22 UTC, clintonb requested changes
This will work, but it would be nice to properly define the course key in the opaque-keys library.

2017-03-09 04:22 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_catalogs.py
> -        """ Verify the endpoint returns a filtered list of courses contained in the catalog. """
This change is not necessary.

2017-03-09 04:22 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_catalogs.py
> -        """ Verify the endpoint returns a filtered list of courses contained in the catalog. """
Also, split this into two separate test cases, or use `ddt` to achieve a similar result.

2017-03-09 04:22 UTC, clintonb commented on course_discovery/apps/api/v1/views/catalogs.py
> +            course_runs = CourseRun.search(catalog.query).filter(key__in=course_run_ids).values_list('key', flat=True)
Move this to a method on the `Catalog` model, similar to `Catalog.contains()`.

2017-03-09 18:32 UTC, zubair-arbi commented
@clintonb Please have another look

2017-03-09 19:37 UTC, clintonb approved these changes

2017-03-09 19:37 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_catalogs.py
> +    def _assert_catalog_contains(self, catalog_contains_query_string, course_key):
1. Call `catalog_contains_query_string` `query_string_kwargs`, which should be a `dict`.
2. Add `query_string = urllib.parse.urlencode(query_string_kwargs)` to de-dupe.

2017-03-09 19:37 UTC, clintonb commented on course_discovery/apps/catalogs/tests/test_models.py
> +        uncontained_course = CourseFactory(key='d/e/f', title='ABDEF')
This line is not necessary.

2017-03-09 19:37 UTC, clintonb commented on course_discovery/apps/catalogs/tests/test_models.py
> +        course_run = CourseRunFactory(course__partner=partner, course=self.course)
`course__partner` is never used since you pass `course`.

2017-03-09 19:37 UTC, clintonb commented on course_discovery/apps/catalogs/tests/test_models.py
> +        uncontained_course_run = CourseRunFactory(course__partner=partner, course=uncontained_course)
`uncontained_course_run = CourseRunFactory(title_override='ABD')`

2017-03-10 07:46 UTC, zubair-arbi commented
@clintonb thanks for the valuable feedback. I have addressed your suggestions.
@mattdrayer please give review.
These changes should give live before its related changes in [Ecom - use catalog contains endpoint for varifying the course seats against a course catalog range](https://github.com/edx/ecommerce/pull/1195).

2017-03-13 12:18 UTC, mattdrayer commented
Thanks for taking care of this @zubair-arbi  -- LGTM 👍

2017-03-13 12:59 UTC, merged