Fix backend state in SearchIndexTestMixin tearDown method
openedx/course-discovery pull request #731
Opened 2017-03-08 23:17 UTC by amangano-edx

The `UpdateIndexTests` modify the backend.index_name variable without cleaning up after itself, which causes future tests to interact with the wrong index and fail. This PR addresses this issue by resetting the index_name in the `tearDown` method of `SearchIndexTestMixin`, which is including in `UpdateIndexTests`.

2017-03-08 23:46 UTC, clintonb approved these changes

2017-03-09 03:05 UTC, clintonb requested changes

2017-03-09 03:05 UTC, clintonb commented on course_discovery/apps/edx_haystack_extensions/tests/mixins.py
> +        self.backend.index_name = self.index_prefix
What test changes the value of `self.backend.index_name`? I don't see anything in the code base.

2017-03-09 14:20 UTC, amangano-edx commented on course_discovery/apps/edx_haystack_extensions/tests/mixins.py
> +        self.backend.index_name = self.index_prefix
This test, https://github.com/edx/course-discovery/blob/master/course_discovery/apps/edx_haystack_extensions/tests/test_update_index.py#L14, calls the update_index command, which modifies backend.index_name in https://github.com/edx/course-discovery/blob/master/course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py#L72

2017-03-09 14:47 UTC, clintonb approved these changes

2017-03-09 15:13 UTC, merged

2017-03-09 15:41 UTC, rlucioni commented
@amangano-edx please delete your merged branches.