Refactoring JS.
openedx/course-discovery pull request #732
Opened 2017-03-09 07:48 UTC by awais786

ECOM-6466

2017-03-09 08:39 UTC, awais786 commented
@waheedahmed @tasawernawaz Please review.

2017-03-09 11:13 UTC, tasawernawaz reviewed
Can we move `{% compress js %}` into `base.html` ?

2017-03-09 11:16 UTC, tasawernawaz commented on course_discovery/templates/publisher/add_courserun_form.html
>      <script src="{% static 'js/publisher/publisher.js' %}"></script>
Can we move `publisher.js` into `course_discovery/templates/publisher/base.html` ?

2017-03-09 11:23 UTC, awais786 commented on course_discovery/templates/publisher/add_courserun_form.html
>      <script src="{% static 'js/publisher/publisher.js' %}"></script>
This will be in later PR.

2017-03-09 12:47 UTC, tasawernawaz requested changes

2017-03-09 12:47 UTC, tasawernawaz commented on course_discovery/templates/publisher/base.html
> +    {% block js_no_compress %}{% endblock %}
rename this block

2017-03-09 12:47 UTC, tasawernawaz commented on course_discovery/templates/publisher/course_detail.html
> +        <script src="{% static 'js/publisher/comments.js' %}"></script>
remove extra indentation

2017-03-09 12:47 UTC, tasawernawaz commented on course_discovery/templates/publisher/course_run_detail.html
> +        </script>
same as above

2017-03-09 12:47 UTC, tasawernawaz commented on course_discovery/templates/publisher/dashboard.html
> +        <script src="{% static 'js/publisher/views/dashboard.js' %}"></script>
same here

2017-03-09 12:50 UTC, awais786 commented
@bderusha Please review.

2017-03-09 15:29 UTC, bderusha requested changes
This is a good start.  The publisher.js file is loaded on edit and details pages depsite the fact that most of what we are still doing in that file is for edit pages only.  It would be good to pull that out as well.  I think we should probably get rid of the `publisher.js` file entirely unless there is JS code we need to run on all pages.

2017-03-09 17:25 UTC, awais786 commented
@bderusha I have same plan for publisher.js. I will remove this in 2nd PR. I will do this in small chunks otherwise changes become too big for testing.

2017-03-09 17:42 UTC, bderusha commented
:shipit:

2017-03-09 17:42 UTC, bderusha approved these changes

2017-03-10 07:31 UTC, tasawernawaz approved these changes

2017-03-10 10:21 UTC, merged