ignore for now
openedx/course-discovery pull request #738
Opened 2017-03-09 19:39 UTC by MatthewPiatetsky

ECOM-7262 Expose course run seats on program endpoint

2017-03-09 20:27 UTC, davec-edx commented
Looks ok to me, my only question was why change from 'seats' to 'staff' in the test, but that got answered.

2017-03-09 21:57 UTC, clintonb requested changes

2017-03-09 21:57 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    seats = SeatSerializer(many=True)
Why are we adding items to the minimal serializer? That goes against the minimal idea.

2017-03-09 21:57 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> -        # Assert that the seats are not available when fetched without any flag
It seems your find-replace operation did too much.

2017-03-09 21:58 UTC, clintonb reviewed
How will this data be used?

2017-03-09 22:08 UTC, MatthewPiatetsky commented
We need the upgrade deadlines on seats for both the course about and program about pages to implement all the upgrade deadline logic for the multi course runs  
this data is already available in the courses endpoint, just not the program endpoint

2017-03-09 22:10 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> -        # Assert that the seats are not available when fetched without any flag
are you asking why i changed seats to staff?
this test is testing the "use_full_course_serializer" argument by checking if seats are present or not, so if i add them to the minimal serializer i need a different field for this check

2017-03-09 22:12 UTC, MatthewPiatetsky commented on course_discovery/apps/api/serializers.py
> +    seats = SeatSerializer(many=True)
if we need this data for the program detail page we could use a different serializer, but then nothing would use this serializer. Minimal should just be the smallest set of an actual existing use case right?

2017-03-10 17:16 UTC, clintonb requested changes

2017-03-10 17:16 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> -        # Assert that the seats are not available when fetched without any flag
Yeah...this test is not implemented well. If you want to verify the `CourseSerializer` is used, just use that class directly. Check to see what data *isn't* in the serialized value is odd and, as we see now, brittle. `test_course_ordering` offers a good example of cleanly validating the courses.

```python
actual = self.serializer_class(program, context={'request': request, 'use_full_course_serializer': 1}).data['courses']
expected = ProgramCourseSerializer(
    program.courses,
    many=True,
    context={'request': request, 'program': program, 'course_runs': list(program.course_runs)}
).data
self.assertDictEqual(actual, expected)
```

2017-03-10 17:54 UTC, MatthewPiatetsky commented on course_discovery/apps/api/tests/test_serializers.py
> -        # Assert that the seats are not available when fetched without any flag
ok I changed the test to use the CourseRunSerializer

2017-03-10 18:08 UTC, clintonb approved these changes

2017-03-10 20:17 UTC, merged