Fix Courses Without End Date Not Visible via API. ECOM-7444
openedx/course-discovery pull request #740
Opened 2017-03-10 06:00 UTC by awaisdar001

2017-03-10 13:38 UTC, clintonb requested changes

2017-03-10 13:38 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_query.py
> +        self.active_course_end = now + datetime.timedelta(days=60)
Move these to the methods that need them rather than creating them for every test.

2017-03-10 13:38 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_query.py
> -        """ Verify the method returns only course runs currently open for enrollment or opening in the future. """
This change is not necessary.

2017-03-10 13:38 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_query.py
> -        """ Verify the method returns only course runs currently open for enrollment or opening in the future. """
Actually...none of your changes to this method are necessary. All you need to do here is add `active_no_end_date = CourseRunFactory(end=None, enrollment_end=self.open_enrollment_end)` to the end of this method and update the assertion.

2017-03-10 15:24 UTC, schenedx commented
@rlucioni I always had a question why course_run `active` must have course_end date defined. Was there a consideration when that was done? Do you think the change here is valid and won't break course multi-run select dialog? 
This change does have an impact to the Sailthru marketing. But I can manage that impact

2017-03-10 16:40 UTC, rlucioni commented
@schenedx I was actually just talking about the discrepancy between the Course and CourseRun `active` filters with @clintonb. I think this is the right change to make, and end date isn't necessary for a run to be considered "active."

2017-03-10 17:33 UTC, schenedx requested changes
Unit test can be cleaned up according to @clintonb's comment

2017-03-10 17:47 UTC, awaisdar001 commented
@clintonb @schenedx PR is updated with requested changes. Please have a look.

2017-03-10 17:49 UTC, clintonb approved these changes

2017-03-10 17:50 UTC, schenedx approved these changes
👍

2017-03-13 19:26 UTC, schenedx commented
@awaisdar001 Are you going to merge this PR?

2017-03-13 20:14 UTC, merged

2017-03-14 05:42 UTC, awaisdar001 commented
@Ayub-Khan Thank you for doing this, while I was away.

2017-03-15 13:39 UTC, Ayub-Khan commented
👍