Proposal: Eliminate excess search queries in search facets views
openedx/course-discovery pull request #762
Opened 2017-03-17 18:41 UTC by amangano-edx

2017-03-17 18:44 UTC, amangano-edx commented on course_discovery/apps/api/v1/views/search.py
> +        self.populate_queryset_cache(queryset, request)
All of the code in this method, except for this one line, was borrowed from the superclass version. See https://github.com/inonit/drf-haystack/blob/master/drf_haystack/mixins.py#L47

2017-03-20 15:07 UTC, rlucioni approved these changes
@amangano-edx nice. Is this something that can be contributed back to drf-haystack? If so, I would encourage you to go that route and push the maintainer to release an updated version of the package. Are there situations in which you wouldn't want to do this?

2017-03-20 15:07 UTC, rlucioni commented on course_discovery/apps/api/v1/views/search.py
> +        the serializer and avoid making extra search queries. Original implimentation:
s/implimentation/implementation

2017-03-22 13:52 UTC, clintonb requested changes
I will approve after Waffle switch added, and comments addressed.

2017-03-22 13:52 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +from unittest import mock
`import mock`

2017-03-22 13:52 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        (5, {'q': 'cs'}, 5),
De-dupe. `record_count` is always 5. `query_params` always has `{'q': 'cs'}`.

2017-03-22 13:52 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +            CourseRunFactory(course=course, status=CourseRunStatus.Published, title='cs')
`CourseRunFactory.create_batch(record_count, course__partner=self.partner, status=CourseRunStatus.Published, title='cs')`

2017-03-22 13:52 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        {'q': 'cs', 'page': -1},
De-dupe. The only data needed here is the value of `page`.

2017-03-22 13:52 UTC, clintonb commented on course_discovery/apps/api/v1/views/search.py
> +        the serializer and avoid making extra search queries. Original implimentation:
Suggested redux: This method is copied exactly from `FacetMixin.facets()`. The only difference is the inclusion of the call to `self.populate_queryset_cache()`.

2017-03-22 13:52 UTC, clintonb commented on course_discovery/apps/api/v1/views/search.py
> +        self.populate_queryset_cache(queryset, request)
Put this behind a Waffle switch in case we need to disable it.

2017-03-22 16:03 UTC, closed without merging

2017-03-22 16:03 UTC, amangano-edx commented
Decided to go with the original approach after all, as this one assumes that the endpoints use PageNumberPagination.