Added instructor marketing profile URL .
openedx/course-discovery pull request #775
Opened 2017-03-23 10:40 UTC by awais786

Name is link now that links to the instructor page (on Drupal)
https://openedx.atlassian.net/browse/ECOM-7558

2017-03-23 10:40 UTC, awais786 commented
@waheedahmed  @tasawernawaz Please review.

2017-03-23 10:49 UTC, waheedahmed approved these changes

2017-03-23 12:19 UTC, awais786 commented
@bderusha please review.

2017-03-23 13:33 UTC, awais786 commented
@bderusha please review.

2017-03-24 14:16 UTC, bderusha requested changes

2017-03-24 14:16 UTC, bderusha commented on course_discovery/apps/course_metadata/models.py
> +    def profile_url(self):
This is not always true.

```
url: "https://stage.edx.org/bio/piotr-mitros-0",
```

We need to actually get the URL from the node and store it

2017-03-24 14:20 UTC, bderusha commented on course_discovery/apps/course_metadata/models.py
> +    def profile_url(self):
The marketing team has the ability to change these URLs at will

2017-03-24 15:20 UTC, awais786 commented on course_discovery/apps/course_metadata/models.py
> +    def profile_url(self):
@bderusha then what do u suggest?
This might need to be done in data-loaders.

2017-04-04 12:01 UTC, closed without merging