Add sanity check before moving index alias
openedx/course-discovery pull request #777
Opened 2017-03-23 17:47 UTC by MatthewPiatetsky

2017-03-23 18:44 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            record_count = backend.conn.count(backend.index_name).get('count')
I'm not sure how to tell if our prod elasticsearch exposes this count endpoint.  
If it does not, we could just do a search and look at hits.get('total')

2017-03-23 18:54 UTC, mikedikan commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            record_count = backend.conn.count(backend.index_name).get('count')
http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es_version_1_5.html

2017-03-23 18:55 UTC, rlucioni requested changes

2017-03-23 18:55 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +SANITY_CHECK_PERCENTAGE_CHANGE = 10
This percentage check on its own should be sufficient. I don't think there's value in overcomplicating this and also checking the record count.

Please make this a float (so you don't need to multiply by 100 - it's standard to see percentage settings specified as floats) and make it a proper setting by moving it to base.py.

2017-03-23 18:55 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +        condition1 = percentage_change < SANITY_CHECK_PERCENTAGE_CHANGE
Give this a useful name. For example, `is_record_count_sane`, or something along those lines.

2017-03-23 18:55 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +                               '{} Current Count: {}'.format(previous_record_count, current_record_count))
Could you also print the percentage change here?

2017-03-23 18:55 UTC, mikedikan commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            record_count = backend.conn.count(backend.index_name).get('count')
Sorry, that used to have a table showing the available endpoints, it doesn't seem to any longer, let me see if I can find you that.

2017-03-23 18:56 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/tests/test_update_index.py
> +                        'update_index.Command.sanity_check_new_index', return_value=True):
@MatthewPiatetsky you do plan to write tests for the sanity check, right? We can't trust it to work like this without tests.

2017-03-23 19:05 UTC, mikedikan commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            record_count = backend.conn.count(backend.index_name).get('count')
http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-supported-es-operations.html

2017-03-23 19:06 UTC, mikedikan commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            record_count = backend.conn.count(backend.index_name).get('count')
It does appear that _count is a supported operation

2017-03-23 20:14 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            alias = connection.options['INDEX_NAME']
it seems if i do backend.index_name which this was previously doing, and run the update_index command twice, the second time it will return the current index_name, not the alias catalog_test (which causes set_alias to fail because an index with that name already exists).

If we didn't want to do this i could mock out set_alias to pass on the second run of this command in the test

2017-03-23 20:14 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/tests/test_update_index.py
> +                        'update_index.Command.sanity_check_new_index', return_value=True):
see the tests i added, i added a comment about one

2017-03-23 20:35 UTC, rlucioni requested changes

2017-03-23 20:35 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            raise CommandError('The current index is empty')
This seems to defensive. Is it really a problem if the current index is empty and you're trying to replace it with a populated index? I would pass in this case.

2017-03-23 20:35 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +    def sanity_check_new_index(self, conn, index, previous_record_count):
This is a side-effecting function. A more Pythonic approach is to name this something like `is_new_index_sane()` and return a Boolean (i.e., return `percentage_change < settings.SANITY_CHECK_PERCENTAGE_CHANGE`), then use that in the `handle()` method to decide whether to raise a `CommandError` or set the alias.

2017-03-23 20:35 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            alias = connection.options['INDEX_NAME']
@MatthewPiatetsky if I'm understanding correctly, you're making this change on account of a test? If so, I would prefer to see the tests mock as necessary rather than change the code under test.

2017-03-23 20:35 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/tests/test_update_index.py
> +        """ Verify the command raises a CommandError if the previous index is empty. """
I don't see a test verifying that the command refuses to set the alias if the sanity check doesn't pass when the previous index is non-empty. That's the more likely case.

2017-03-23 20:44 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +                    previous_record_count, current_record_count, percentage_change * 100
You should round the percentage to the nearest two decimal places when printing it. For example:
```py
>>>  '{0:.2f}%'.format(0.123456*100)
'12.35%'
```

2017-03-23 20:52 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            raise CommandError('The current index is empty')
that seems strange. pass if the previous index is empty but fail if it has one record?

2017-03-23 20:56 UTC, rlucioni commented on course_discovery/settings/base.py
> +SANITY_CHECK_PERCENTAGE_CHANGE = .1
The name for this setting can make its purpose a little more clear. Suggestion: `INDEX_SIZE_CHANGE_THRESHOLD`.

2017-03-23 21:00 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            raise CommandError('The current index is empty')
Why would the check fail if the previous index had one record? I just don't see how failing because the previous index is empty is useful here. If I'm trying to use this command to populate a new index, and I happen to have an empty index in place, why refuse to update the index?

2017-03-23 21:14 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            raise CommandError('The current index is empty')
this check is just if the previous index is empty. With the current code if there was any number of records that did not meet the threshold, including fewer records, it would fail.  
i don't think we should always assume more records is right

2017-03-24 13:14 UTC, MatthewPiatetsky commented
@rlucioni did I address your comments?

2017-03-24 15:19 UTC, rlucioni approved these changes
@MatthewPiatetsky looks good, though I would make a few changes to the tests.

2017-03-24 15:19 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/tests/test_update_index.py
> +        CourseRunFactory.create_batch(100)
Is it really necessary to create 100 runs? Could you do this with an order of magnitude less?

2017-03-24 15:19 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/tests/test_update_index.py
> +        """ Verify the command raises a CommandError if the previous index is empty. """
Can you update this docstring to reflect the behavior the test is covering now?

2017-03-24 15:19 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/tests/test_update_index.py
> +                            'update_index.Command.set_alias', return_value=True):
Why is it necessary to mock `set_alias` here? Aren't you expecting the sanity check to fail, meaning this method will never be called?

2017-03-24 15:19 UTC, rlucioni commented on course_discovery/apps/edx_haystack_extensions/management/commands/update_index.py
> +            # pick large percentage for division by 0
I'd elaborate a bit on your choice here to make it clear that this is done to force the sanity check to fail.

2017-03-24 15:46 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/tests/test_update_index.py
> +        CourseRunFactory.create_batch(100)
well if i did 10 then 10 * .1 - 1 will be 0 additional courses. 
I can do 30.

2017-03-24 16:03 UTC, MatthewPiatetsky commented on course_discovery/apps/edx_haystack_extensions/tests/test_update_index.py
> +                            'update_index.Command.set_alias', return_value=True):
due to this issue i mentioned earlier where i had to change update_index if i didn't do this, because it was trying to make the alias for the new index the name of the existing index which would break. the important part here though is that the sanity check passes/fails.  
What happens after doesn't matter as much

2017-03-24 16:49 UTC, merged