(WIP) [LEARNER-275] Enable eligible program functionality
openedx/course-discovery pull request #787
Opened 2017-03-28 13:16 UTC by iivic

Ticket: https://openedx.atlassian.net/browse/LEARNER-275

![admin-program-filter](https://cloud.githubusercontent.com/assets/16685686/24406763/4016fafc-13c9-11e7-85b5-818c264f3bf9.png)
![admin-one-click-purchase-field](https://cloud.githubusercontent.com/assets/16685686/24406765/42084c08-13c9-11e7-93eb-797de4f834a1.png)

2017-03-28 13:52 UTC, clintonb requested changes

2017-03-28 13:52 UTC, clintonb commented on course_discovery/apps/course_metadata/utils.py
> +def is_program_eligible(program):
This should be a property on the model. Also, eligible for what? The name is too ambiguous.

2017-03-28 13:52 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    one_click_purchase = models.BooleanField(default=False)
Vague name is vague. one_click_purchase_enabled

2017-03-28 13:52 UTC, clintonb commented on course_discovery/apps/course_metadata/utils.py
> +    for course in program.courses.all():
Use prefetch to get all data in a single DB call. Also, you need to account for excluded course runs. @rlucioni can help with this if you need it.

2017-03-28 13:52 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +    title = _('is eligible for one click purchase')
Eligible for one-click purchase

2017-03-28 13:52 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +    parameter_name = 'is_eligible'
eligible_for_one_click_purchase

2017-03-28 13:52 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +def _get_program_queryset(queryset, display_eligible_programs):
This seems like it should be a method in the class below. It should be the overridden `queryset()` method.

2017-03-28 13:52 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +    for program in queryset:
Again, look at prefetch options. As-is this is O(n^3) DB queries.

2017-03-28 13:52 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +        if self.value() == '1':
```python
value = bool(int(self.value()))
return _get_program_queryset(queryset, value)
```

2017-03-28 13:52 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +from django.utils.translation import ugettext_lazy as _
No need for `_lazy`.

2017-03-28 17:41 UTC, clintonb commented on course_discovery/apps/course_metadata/admin.py
>      fields += (
Please merge this with the tuple above. Not sure why this is here.

2017-03-28 17:42 UTC, clintonb commented on course_discovery/apps/course_metadata/utils.py
> +    for course in program.courses.all():
* https://docs.djangoproject.com/en/1.10/ref/models/querysets/#select-related
* https://docs.djangoproject.com/en/1.10/ref/models/querysets/#prefetch-related

2017-03-28 18:17 UTC, rlucioni commented on course_discovery/apps/course_metadata/utils.py
> +    all his courses must contain only one course run.
s/his/its

2017-03-28 18:18 UTC, rlucioni commented on course_discovery/apps/course_metadata/utils.py
> +    for course in program.courses.all():
Good catch @clintonb. @iivic please use the Django debug toolbar to understand how the query counts for the program list and detail views are impacted by this change. Most of the serializers, including the `MinimalProgramSerializer`, include a [`prefetch_queryset()`](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/api/serializers.py#L671) method. Any prefetching should occur in this method. Any manipulation of data should happen after that method is called so that you're working with cached data. Be careful not to perform any queryset filtering after prefetching; doing that will cause the cached data to be discarded.

2017-03-28 18:20 UTC, rlucioni commented on course_discovery/apps/course_metadata/utils.py
> +    for course in program.courses.all():
Follow-up: in this case, it looks like the serializer may already be prefetching course runs for you. Regardless, you should use the debug toolbar to make sure you understand how query counts are changing. Unit tests should fail if you cause the query count to change.

2017-03-29 12:22 UTC, clintonb requested changes
If you don't make changes to Tex in JS files, there is no need to commit updated djangojs translation files.

2017-03-29 12:22 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +            'courses', 'authoring_organizations', 'card_image_url', 'is_eligible_for_one_click_purchase'
Add a trailing comma.

2017-03-29 12:22 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +    is_eligible_for_one_click_purchase = serializers.SerializerMethodField()
There should be no need to declare this here. If you must declare it, declare it as a Boolean field that is read-only.

2017-03-29 12:22 UTC, clintonb commented on course_discovery/apps/course_metadata/admin.py
> +    list_filter = ('partner', 'type', 'status', ProgramEligibilityFilter)
Add a trailing comma.

2017-03-29 12:22 UTC, clintonb commented on course_discovery/apps/course_metadata/admin.py
> +        'min_hours_effort_per_week', 'max_hours_effort_per_week', 'one_click_purchase_enabled',
Avoid messing up users' current workflows. Move the new field to the bottom of the page/end of the list.

2017-03-29 12:22 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        for course in self.courses.all():
Move this to the method below.

2017-03-29 12:22 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            if course.course_runs.count() != 1:
Remember to account for excluded course runs.

2017-03-29 12:53 UTC, iivic commented on course_discovery/apps/course_metadata/models.py
> +            if course.course_runs.count() != 1:
Can you elaborate? Currently it counts all course runs that are linked to the course regardless of the program excluded course runs list.

2017-03-29 12:54 UTC, vkaracic commented on course_discovery/apps/course_metadata/admin_filters.py
> +            if value == '1':
I don't see ``value`` changing with each (any?) iteration so maybe avoid doing the same operation in each iteration.

2017-03-29 13:04 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            if course.course_runs.count() != 1:
Let's say you encounter a course with two course runs. If one of those course runs is excluded, the course run count should for that course should be one, not two.

2017-03-29 13:10 UTC, iivic commented on course_discovery/apps/course_metadata/models.py
> +            if course.course_runs.count() != 1:
I asked how to count the course runs on our standup yesterday. Maybe I wasn't clear but this is exactly what I was referring to. I'll inform the team on todays standup.

2017-03-29 13:13 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            if course.course_runs.count() != 1:
I am technically out of the office all week, so I haven't been at standup. It's easier for me to have a conversation either here on the PR or on the original ticket in JIRA.

2017-03-29 13:35 UTC, vkaracic commented on course_discovery/apps/course_metadata/admin_filters.py
> +            if value == '1':
I don't see value changing with each (any?) iteration so maybe avoid doing the same operation in each iteration.

2017-03-29 13:35 UTC, vkaracic commented on course_discovery/apps/course_metadata/models.py
> +        if self.one_click_purchase_enabled and self._program_course_and_course_run_mapping():
You don't need the rest of the code in this property, just do `` return elf.one_click_purchase_enabled and self._program_course_and_course_run_mapping()``.

2017-03-31 22:59 UTC, clintonb requested changes

2017-03-31 22:59 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +        for program in queryset.prefetch_related('courses__course_runs'):
Move this to a separate line: `queryset = queryset.prefetch_related('courses__course_runs')`

2017-03-31 22:59 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +class ProgramEligibilityFilter(admin.SimpleListFilter):
This seems more at home in `admin.py`.

2017-03-31 22:59 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    one_click_purchase_enabled = models.BooleanField(default=False)
Add help text: Allow allow courses in this program to be purchased in a single transaction.

2017-03-31 22:59 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            if course.course_runs.exclude(id__in=self.excluded_course_runs.values_list('id', flat=True)).count() != 1:
This will most likely result in a database call. You should do the filtering in Python:

```python
excluded_course_run_ids = set(self.excluded_course_runs.values_list('id', flat=True))

for course in self.courses.all():
  course_run_ids = set(course.course_runs.values_list('id', flat=True)) - excluded_course_run_ids
  if len(course_run_ids) != 1
    return False
```

2017-03-31 22:59 UTC, clintonb commented on course_discovery/conf/locale/eo/LC_MESSAGES/djangojs.po
> -"POT-Creation-Date: 2017-03-31 15:15+0500\n"
You aren't changing any JS text, so there is no need to commit changes to `djanogojs.*`.

2017-03-31 22:59 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +    title = _('eligible for one-click purchase')
Capitalize: Eligible

2017-03-31 22:59 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +class ProgramEligibilityFilter(admin.SimpleListFilter):
This also needs tests.

2017-03-31 23:01 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +class ProgramEligibilityFilter(admin.SimpleListFilter):
Please ensure the tests also ensure a linear (relative to the number of programs) query count.

2017-04-03 07:25 UTC, iivic commented on course_discovery/apps/course_metadata/admin_filters.py
> +    title = _('eligible for one-click purchase')
"By" will get prepended so capitalising would look silly. You can see how it looks in the description screenshot.

2017-04-03 07:32 UTC, iivic commented on course_discovery/apps/course_metadata/admin_filters.py
> +        for program in queryset.prefetch_related('courses__course_runs'):
What is the benefit of doing so?

2017-04-03 12:12 UTC, clintonb commented on course_discovery/apps/course_metadata/admin_filters.py
> +        for program in queryset.prefetch_related('courses__course_runs'):
The code is clearer to read.

2017-04-03 14:36 UTC, iivic commented
You can review one more time.

2017-04-03 15:15 UTC, clintonb requested changes

2017-04-03 15:15 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0050_program_one_click_purchase_enabled.py
> +            field=models.BooleanField(default=False),
This needs to be updated with the help text.

2017-04-03 15:15 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.programs_queryset = Program.objects.filter(id__in=[pr.id for pr in self.programs])
Just use `Program.objects.all()` where this variable is used.

2017-04-03 15:15 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.one_click_purchase_ineligible_program = factories.ProgramFactory(courses=self.courses)
This doesn't need to be an instance variable. The same goes for pretty much all of these variables. Move the data to the tests where they actually belong. This will make the tests much easier to read, and avoid introducing dependencies that make adding/modifying tests difficult in the future.

2017-04-03 15:15 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        self.program.one_click_purchase_enabled = True
You need more conditions/tests and comments. Conditions I can think of (that are not tested):

1. Course has multiple course runs.
2. Course has multiple course runs, and all but one is excluded from the program.
3. One course has multiple runs, other courses have one.
4. Course runs are not enrollable/purchaseable.

2017-04-04 09:52 UTC, iivic commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        self.program.one_click_purchase_enabled = True
4. Is this a condition that should be meet by an eligible program? If not how is it connected to these tests? What is required for a course run to be enrollable, enrollment_start/end dates?

2017-04-04 12:26 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        self.program.one_click_purchase_enabled = True
We don't want to have a one-click purchase scenario where the learner ends up with a fraction of the program. The simplest method of determining availability will be to look at the upgrade deadlines on the eligibility seats.

2017-04-04 12:50 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_models.py
> +
You still need to test for the case when a course run is excluded from the program.

2017-04-04 12:50 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +                [one_click_purchase_ineligible_program, one_click_purchase_eligible_program]
`Program.objects.all()`

2017-04-04 12:50 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +                program_filter.queryset({}, Program.objects.all()).first(),
Drop `first()`. There shouldn't be any more objects returned. Cast to a `list` as you did above.

2017-04-04 12:50 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        """ Verify that one click purchase ineligible programs pass the filter. """
Verify programs ineligible for one-click purchase do not pass the filter.

2017-04-04 12:50 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        course_run = factories.CourseRunFactory()
These two lines can be simplified: `program = factories.ProgramFactory(one_click_purchase_enabled=False)`.

2017-04-04 12:50 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +                program_filter.queryset({}, Program.objects.all()).first(),
Same comment as above regarding `first()`.

2017-04-04 13:13 UTC, iivic commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +                [one_click_purchase_ineligible_program, one_click_purchase_eligible_program]
An additional database call will be made after this change. I prefer leaving it as is.

2017-04-05 12:36 UTC, clintonb reviewed
This is a great purchaseable property. It needs some tweaks before it's good to go.

2017-04-05 12:36 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        verified_seats = self.seats.filter(type=Seat.VERIFIED)
Calling `filter()` here will result in an extra call to the DB that should be avoided by using Python filtering.

2017-04-05 12:36 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            1. The course run is open for enrollment
You also need to account for whether the course run itself is open. See `start` and `end`.

2017-04-05 12:36 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        verified_seats = self.seats.filter(type=Seat.VERIFIED)
We don't want to hard-code `Seat.VERIFIED` here. You might want to modify the method signature:

```python
def enrollable_seats(self, types):
  Returns seats, of the given type(s), that can be enrolled in/purchased.

  Arguments:
    types (SeatType[]): Type of seats to limit the returned value to.

  Returns:
    SeatType[]
```

2017-04-05 12:36 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            if len(course_run_ids) != 1 or not CourseRun.objects.get(id=course_run_ids.pop()).is_purchasable:
This is going to result in multiple calls to the database that should be avoided.

```python
excluded_course_runs = set(self.excluded_course_runs)

for course in self.courses.all():
  course_runs = set(course.course_runs) - excluded_course_runs

  if len(course_runs) != 1:
    return False

  if not course_runs.pop().is_purchaseable:
    return False
```

2017-04-05 14:00 UTC, iivic commented on course_discovery/apps/course_metadata/models.py
> +        verified_seats = self.seats.filter(type=Seat.VERIFIED)
Regarding the filter() I need to get the seats from the database in both cases. I don't see how to avoid that.

2017-04-05 14:03 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        verified_seats = self.seats.filter(type=Seat.VERIFIED)
When using `prefetch`/`select_related`, you have all of the data cached after the first call. If you need to filter, do so in Python (rather than the DB/Django ORM) to avoid a call to the database.

```python
verified_seats = [seat if seat.type == Seat.VERIFIED for seat in self.seats.all()]
```

2017-04-05 14:42 UTC, iivic commented
@clintonb Please review the latest changes.

2017-04-06 13:06 UTC, iivic commented
@clintonb @marjev

2017-04-06 13:52 UTC, marjev approved these changes

2017-04-06 15:43 UTC, clintonb requested changes
`CourseRun.is_purchaseable()` is not needed.

2017-04-06 15:43 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +                if not seat.upgrade_deadline or now < seat.upgrade_deadline:
Combine with the statement above.

2017-04-06 15:43 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        Indicates weather or not the course run contains a purchasable seat
whether

2017-04-06 15:43 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    PURCHASABLE_SEAT_TYPES = [PROFESSIONAL, VERIFIED]
This is not needed.

2017-04-06 15:43 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +    def is_purchasable(self):
This is not needed.

2017-04-07 11:27 UTC, iivic commented
@clintonb Comments addressed.

2017-04-07 12:04 UTC, clintonb requested changes

2017-04-07 12:04 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            if not course_runs.pop().enrollable_seats([Seat.VERIFIED, Seat.PROFESSIONAL]):
Stop hard-coding seat types. Use self.type.applicable_seat_types.

2017-04-07 12:22 UTC, iivic commented on course_discovery/apps/course_metadata/models.py
> +            if not course_runs.pop().enrollable_seats([Seat.VERIFIED, Seat.PROFESSIONAL]):
I understood that the the seat type must be buyable (learner must pay for it). That's the reason I hardcoded verified and professional because those are buyable. `applicable_seat_types` can be any seat type so this is different from what I was doing.

2017-04-07 12:24 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            if not course_runs.pop().enrollable_seats([Seat.VERIFIED, Seat.PROFESSIONAL]):
Applicable seat types is what matters. If, in the future, we decide to allow audit seats or some new seat type, we should not need to modify this code.

2017-04-07 12:33 UTC, marjev commented on course_discovery/apps/course_metadata/models.py
> +            if not course_runs.pop().enrollable_seats([Seat.VERIFIED, Seat.PROFESSIONAL]):
So `self.type.applicable_seat_types` currently doesn't contain non-purchasable seat types like Audit?

2017-04-07 12:38 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            if not course_runs.pop().enrollable_seats([Seat.VERIFIED, Seat.PROFESSIONAL]):
Nope. Even if it did, that would be okay, because that's what the creators deemed applicable for completing a program.

2017-04-07 13:45 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            print(types)
Remove these print statements.

2017-04-07 13:45 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            if not course_runs.pop().enrollable_seats(applicable_seat_types):
`list(self.type.applicable_seat_types.all())`

2017-04-07 13:53 UTC, iivic commented on course_discovery/apps/course_metadata/models.py
> +            if not course_runs.pop().enrollable_seats(applicable_seat_types):
This will return a list of SeatType objects and thus not work.

2017-04-07 13:56 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +            types (list of SeatTypes): Type of seats to limit the returned value to.
list of seat type names

2017-04-07 13:56 UTC, clintonb approved these changes
See my last comment on the docstring. Remember to squash your commits.

2017-04-07 14:25 UTC, iivic commented
@clintonb FYI I noticed that the applicable_seat_types are uppercase and added https://github.com/edx/course-discovery/pull/787/files#diff-a79b6f6b0e3ecfd5c59847f0e39d59d2R787

2017-04-07 15:39 UTC, merged