Update preview tab on publisher dashboard
openedx/course-discovery pull request #795
Opened 2017-03-31 08:16 UTC by tasawernawaz

[ECOM-7528](https://openedx.atlassian.net/browse/ECOM-7528)

WIP

2017-03-31 10:48 UTC, tasawernawaz commented
@waheedahmed @awais786 Please review.

2017-03-31 12:46 UTC, waheedahmed requested changes
In screenshot available on ticket it was wrong, Roderick also mentioned that in planning session last Monday.
It should be like this.
```
{% if not course_run.preview_url %}
	{% trans "Preview Requested" %}
{% elif course_run.course_run_state.preview_accepted %}
	{% trans "Approved" %}
{% else %}
	{% trans "In Review" %}
{% endif %}
```

2017-03-31 12:46 UTC, waheedahmed commented on course_discovery/templates/publisher/dashboard/_in_preview.html
> +                        {% if not course_run.preview_url %}
This is not right, In review means when `preview_url` is available but not accepted.

2017-04-03 10:34 UTC, tasawernawaz commented on course_discovery/templates/publisher/dashboard/_in_preview.html
> +                        {% if not course_run.preview_url %}
Done. Please review it again.

2017-04-03 10:41 UTC, waheedahmed approved these changes

2017-04-03 10:56 UTC, merged