Instructor profile modal screen
openedx/course-discovery pull request #830
Opened 2017-04-16 19:38 UTC by awais786

https://openedx.atlassian.net/browse/ECOM-7679

2017-04-16 19:42 UTC, awais786 commented
@waheedahmed @tasawernawaz Please review.

2017-04-17 08:38 UTC, waheedahmed requested changes
One comment and download button doesn't look same as in wireframe.

2017-04-17 08:38 UTC, waheedahmed commented on course_discovery/apps/publisher/views.py
> +            staff['full_name']: staff
Instead `full_name` you should use `username` or `id` as key.

2017-04-19 06:19 UTC, tasawernawaz approved these changes

2017-04-19 06:50 UTC, waheedahmed approved these changes

2017-04-19 09:05 UTC, merged