Catalog API pagination URL domains should be consistant
openedx/course-discovery pull request #838
Opened 2017-04-18 14:58 UTC by adeelkhan

ECOM-5122

Generates pagination url based on gateway passed HOST header params instead of underlying hostname/server e.g. stage-edx-discovery.

2017-04-18 15:00 UTC, clintonb requested changes

2017-04-18 15:00 UTC, clintonb commented on course_discovery/settings/local.py
> +ALLOWED_HOSTS = ['api.stage.edx.org']
This should never be in our code base.

2017-04-18 15:00 UTC, clintonb commented on course_discovery/settings/local.py
> +USE_X_FORWARDED_HOST = True
This belongs in base.py. Local settings will *never* be read in production.

2017-04-18 21:30 UTC, schenedx requested changes
Please see my comments

2017-04-18 21:30 UTC, schenedx commented on course_discovery/settings/local.py
> +ALLOWED_HOSTS = ['api.stage.edx.org']
What are you trying to achieve by making this change?

2017-04-18 21:30 UTC, schenedx commented on course_discovery/settings/local.py
> +USE_X_FORWARDED_HOST = True
Please move this line to  https://github.com/edx/course-discovery/blob/master/course_discovery/settings/base.py#L20

2017-04-19 10:24 UTC, adeelkhan commented
@simon I just wanted to share changes with you for testing purpose. Therefore I hardcoded the ALLOWED_HOST value. This wasn’t meant for external review. After agreeing on changes I would ask for further reviews. Sorry for not mentioning this before.

2017-04-20 19:43 UTC, schenedx approved these changes
👍

2017-04-21 09:54 UTC, ahsan-ul-haq approved these changes

2017-04-24 15:16 UTC, schenedx commented
@clintonb Since you are back, can you review this PR quickly? One line change only

2017-04-24 15:21 UTC, clintonb requested changes
I would like to see a test to confirm this will work as expected before we deploy it.

2017-04-24 15:22 UTC, clintonb commented
By test, I mean unit/acceptance test. I want to ensure that we don't accidentally break this functionality in the future.

2017-05-03 09:29 UTC, ahsan-ul-haq requested changes

2017-05-03 09:29 UTC, ahsan-ul-haq commented on acceptance_tests/config.py
> +API_COURSES_ROOT = os.environ.get('API_COURSES_ROOT', 'http://localhost:18381')
Put a default value for stage not your local.

2017-05-03 09:29 UTC, ahsan-ul-haq commented on acceptance_tests/config.py
> +    raise RuntimeError('API_COURSE_ROOT (e.g. https://api.stage.edx.org/api/v1/courses) must be supplied!')
As you are putting a default value this block of code will not run.

2017-05-03 09:29 UTC, ahsan-ul-haq commented on acceptance_tests/config.py
>      raise RuntimeError('API_GATEWAY_CATALOG_ROOT (e.g. https://api.stage.edx.org/catalog/v1) must be supplied!')
Same here

2017-05-03 09:29 UTC, ahsan-ul-haq commented on acceptance_tests/test_xforwarding_host.py
> +@ddt.ddt
what is the use of ddt here?

2017-05-03 09:29 UTC, ahsan-ul-haq commented on acceptance_tests/test_xforwarding_host.py
> +    path = 'api/v1/courses/'
why `api/v1/courses/` instead of `api/v1`

2017-05-03 09:29 UTC, ahsan-ul-haq commented on acceptance_tests/test_xforwarding_host.py
> +        if courses_list['next'] is not None:
you can simplify it to 
```
if not courses_list['next']:
```

2017-05-03 09:29 UTC, ahsan-ul-haq commented on acceptance_tests/test_xforwarding_host.py
> +                                                                          path=self.path))
why not using `get_discovery_api_url` here?

2017-05-03 09:29 UTC, ahsan-ul-haq commented on acceptance_tests/test_xforwarding_host.py
> +        if courses_list['previous'] is not None:
Same here.

2017-05-03 18:20 UTC, awais786 commented on acceptance_tests/test_xforwarding_host.py
> +    path = 'api/v1/courses/'
reverse('api:v1:course-list')

2017-05-03 19:03 UTC, schenedx commented on acceptance_tests/test_xforwarding_host.py
> +    path = 'api/v1/courses/'
Please take in this feedback

2017-05-03 19:06 UTC, schenedx commented on acceptance_tests/test_xforwarding_host.py
> +        """ Returns a complete URL for the given path. """
@adeelkhan I feel like you can generalize this function by doing `Returns a complete URL for given path and root`. This way, you can use the caller code to specify the domain, and then the path.
This way, can you reuse this function in the `assertEqual` statements below

2017-05-03 19:06 UTC, schenedx commented
@clintonb You think the new acceptance test works?

2017-05-03 19:20 UTC, adeelkhan commented
@ahsan-ul-haq @clintonb Please review acceptance test.

2017-05-03 21:02 UTC, clintonb requested changes
This will not work as expected.

Take `https://prod-edx-discovery.edx.org/api/v1/catalogs/`. The gateway path is `https://api.stage.edx.org/catalog/v1/catalogs`. Simply changing the host will result a URL pointing to path that does not exist, breaking pagination for all clients.

2017-05-03 21:02 UTC, clintonb commented on acceptance_tests/config.py
> +API_COURSES_ROOT = os.environ.get('API_COURSES_ROOT')
This is not necessary given `API_GATEWAY_CATALOG_ROOT` below.

2017-05-03 21:02 UTC, clintonb commented on acceptance_tests/test_xforwarding_host.py
> +    def get_discovery_api_url(self, path):
`get_api_gateway_url`

2017-05-03 21:02 UTC, clintonb commented on acceptance_tests/test_xforwarding_host.py
> +    forwarded_host_name = 'api.stage.edx.org'
This should not be hard-coded.

2017-05-03 21:02 UTC, clintonb commented on acceptance_tests/test_xforwarding_host.py
> +        return "http://{forwarded_host_name}/{path}/".format(forwarded_host_name=self.forwarded_host_name,
This should basically be `self.get_discovery_api_url(self.path)`.

2017-05-03 21:02 UTC, clintonb commented on acceptance_tests/test_xforwarding_host.py
> +    def test_xforwarded_generated_pagination(self):
This belongs in `test_api_gateway.py`.

2017-05-03 21:02 UTC, clintonb commented on acceptance_tests/test_xforwarding_host.py
> +    def test_xforwarded_generated_pagination(self):
This can be simplified:

```python
from edx_rest_api_client.client import EdxRestApiClient

def test_pagination_urls(self):
    client = EdxRestApiClient(API_GATEWAY_CATALOG_ROOT, jwt=API_ACCESS_TOKEN)
    response = client.catalogs(CATALOG_ID).courses.get()

    pagination_urls = (response.get('next'), response.get('previous'))
    pagination_urls = [url for url in pagination_urls if url]

    if not pagination_urls:
        self.fail('The API response does not include pagination URLs.')

    for url in pagination_urls:
        self.assertTrue(url.startswith(API_GATEWAY_CATALOG_ROOT))

```

2017-05-03 21:02 UTC, clintonb commented on acceptance_tests/test_xforwarding_host.py
> +    path = 'api/v1/courses'
This path is not exposed by the API gateway. Only a subset of catalog paths are exposed, as described in https://github.com/edx/course-discovery/blob/master/api.yaml:

* /catalogs/
* /catalogs/{id}/
* /catalogs/{id}/courses/

2017-09-04 23:21 UTC, closed without merging