Update the api gateway to provide x-forwarded-host header value
openedx/course-discovery pull request #848
Opened 2017-04-20 11:29 UTC by adeelkhan

ECOM-7686 - Sub task of ECOM-5122
 api gateway now forwards x-forwarded-host header.
WIP, Not for external reviewers.

2017-04-20 18:59 UTC, schenedx reviewed
@adeelkhan I don't really have domain knowledge on how the changes here would affect the behavior of api gateway. I did notice that on api-manager file, the reference https://github.com/edx/api-manager/blob/master/swagger/api.yaml#L33 refer to a specific version. Do we need to update the api-manager swagger api.yaml as well?

2017-04-20 21:35 UTC, efagin commented
@schenedx yes, once this merges we'll need to update the api-manager reference accordingly. @mattdrayer's team has a development instance of the gateway that you could potentially use if you want, before trying to update and merge everything.

2017-04-20 21:41 UTC, mattdrayer commented
@saleem-latif @asadiqbal08 @zubair-arbi FYI

2017-04-20 21:43 UTC, efagin requested changes

2017-04-20 21:43 UTC, efagin commented on api-compact.yaml
> +  name: "HOST"
I would prefer that this is defined as {{Host}}, instead of {{HOST}}. Header names are typically not defined as all-caps. Please try to remain consistent with how the {{Authorization}} header is defined.

2017-04-20 21:43 UTC, efagin commented on api-compact.yaml
> +    integration.request.header.X-Forwarded-Host: "method.request.header.HOST"
Please see above regarding {{Host}} instead of {{HOST}}.

2017-04-20 21:43 UTC, efagin commented on api-compact.yaml
> +    integration.request.header.X-Forwarded-Host: "method.request.header.HOST"
Please see above regarding {{Host}} instead of {{HOST}}.

2017-04-20 21:43 UTC, efagin commented on api-compact.yaml
> +    integration.request.header.X-Forwarded-Host: "method.request.header.HOST"
Also, please group the {{integration.request.header}} items together instead of just appending this to the end of the list, as it's easier to review and understand that way.

2017-04-20 21:45 UTC, efagin commented
@mattdrayer also FYI that you're likely going to want to use this Host header proxying for the ENT catalog endpoints as well (or any other endpoint that has paginated responses). We first need to ensure that this method works, but once it's established I recommend doing something similar.

2017-04-21 13:01 UTC, efagin approved these changes

2017-04-21 13:54 UTC, schenedx approved these changes
👍 Let's see if this does the job on stage.

2017-04-24 14:43 UTC, clintonb commented
> Let's see if this does the job on stage.

Has this not been tested locally?

2017-04-24 14:44 UTC, clintonb commented
By "this" I mean the usage of the X-Forwarded-For header to change pagination URL. That seems like it should be pretty quick to test locally with cURL.

2017-04-24 15:16 UTC, schenedx commented
@clintonb "The usage of the X-Forwarded-For header to change pagination URL" was actually already tested on PR https://github.com/edx/course-discovery/pull/838. The PR there is to realize that update.
This PR is really to configure the API manager behavior to provide the Hostname value in x-forwarded-for header

2017-04-24 21:44 UTC, efagin commented on api-compact.yaml
> +      Authorization: "method.request.header.Authorization"
I don't think the Swagger spec allows nesting of request parameters.

2017-04-24 21:47 UTC, efagin commented on api-compact.yaml
> +      Authorization: "method.request.header.Authorization"
On second thought, that's part of the AWS specific detail, so I'm not sure that's a Swagger issue, but I suspect it'll fail at the AWS upload level.

2017-09-04 23:22 UTC, closed without merging