Program marketing slug to be URL of published Drupal page
openedx/course-discovery pull request #854
Opened 2017-04-24 12:45 UTC by ahsan-ul-haq

ECOM-7310

2017-04-24 19:44 UTC, schenedx requested changes
Mostly suggestions to keep the code dry and re-usable

2017-04-24 19:44 UTC, schenedx commented on course_discovery/apps/course_metadata/publishers.py
> +        alias_list_url = self.alias_list_url(obj.marketing_slug)
I believe this line (301) and the next line (302) can be wrapped into a single function. It was repeated twice.

2017-04-24 19:44 UTC, schenedx commented on course_discovery/apps/course_metadata/publishers.py
> +                alias_list_url = self.alias_list_url(slugify(obj.title, allow_unicode=True))
This whole block (line 259 - line 262) can be wrapped into another new function. This is repeated twice. Once here, once on line 307 to line 311.

2017-04-24 19:44 UTC, schenedx commented on course_discovery/apps/course_metadata/publishers.py
> +    def alias_list_url(self, slug):
#nit `def get_alias_list_url(self, slug)`

2017-04-27 12:15 UTC, ahsan-ul-haq commented
@rlucioni @MatthewPiatetsky could either of you please review this.

2017-04-27 14:39 UTC, schenedx approved these changes
👍  Looks good

2017-04-27 14:49 UTC, rlucioni requested changes

2017-04-27 14:49 UTC, rlucioni commented on course_discovery/apps/course_metadata/publishers.py
> -    @cached_property
Why did you get rid of this?

2017-04-27 14:49 UTC, rlucioni commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +        # slug Alias creation should occur, but slug alias deletion should not.
This tests the case where no previous object is provided. What is there to delete?

2017-04-27 14:49 UTC, rlucioni commented on course_discovery/apps/course_metadata/publishers.py
> +        data.update(self.alias_form_inputs(alias_delete_url))
Why did you change the `**` syntax that was being used before?

2017-04-27 14:49 UTC, rlucioni commented on course_discovery/apps/course_metadata/publishers.py
> +            data.update(self.alias_form_inputs(self.alias_add_url))
Why did you change the `**` syntax that was being used?

2017-04-27 14:49 UTC, rlucioni commented on course_discovery/apps/course_metadata/publishers.py
> +            # Delete old alias before saving the new one.
Is it going to be a problem if the old alias is deleted before the new one is created?

2017-04-27 14:49 UTC, rlucioni commented on course_discovery/apps/course_metadata/publishers.py
> +                self.get_and_delete_alias(slugify(obj.title, allow_unicode=True))
Is the `allow_unicode` kwarg necessary here?

2017-04-28 11:08 UTC, ahsan-ul-haq commented on course_discovery/apps/course_metadata/publishers.py
> -    @cached_property
I don't think we can cache this form inputs are being scraped based on the url provided i.e. alias_delete_url or alias_add_url

2017-04-28 11:12 UTC, ahsan-ul-haq commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +        # slug Alias creation should occur, but slug alias deletion should not.
For a newly created node in drupal, when it is published an alias based on the title of the node is being created we need to delete that alias and then create a marketing slug based alias. Here title based alias is being deleted.

2017-04-28 13:13 UTC, ahsan-ul-haq commented on course_discovery/apps/course_metadata/publishers.py
> +            # Delete old alias before saving the new one.
I observe an issue if we create a new alias and then delete the old one it does not create the new alias just create an URL redirect which is being resolved by first deleting the old one and then create a new one.

2017-05-01 18:30 UTC, ahsan-ul-haq commented
@rlucioni could you please review this.

2017-05-01 20:22 UTC, rlucioni approved these changes

2017-05-01 20:22 UTC, rlucioni commented on course_discovery/apps/course_metadata/tests/test_publishers.py
> +        # slug Alias creation should occur, but slug alias deletion should not.
@ahsan-ul-haq please make that more clear in this comment for others who may not know this.

2017-05-01 20:23 UTC, rlucioni commented
@ahsan-ul-haq please remember to squash your commits!

2017-05-02 09:08 UTC, merged