Cache program viewset responses
openedx/course-discovery pull request #857
Opened 2017-04-25 21:33 UTC by rlucioni

@clintonb @mjfrey @mikedikan this is a proof-of-concept showing how we can cache DRF responses using only utilities provided by Django. [cache_page()](https://docs.djangoproject.com/en/1.11/topics/cache/#django.views.decorators.cache.cache_page) uses the request received by the view to construct a cache key, taking headers and querystring parameters into account.

2017-04-25 21:35 UTC, rlucioni commented on course_discovery/settings/base.py
> +RESPONSE_CACHE_TTL = 60
If we had a good way to clear and rebuild specific cache entries when certain models are saved, this could be set to `None` to cache entries indefinitely.

2017-04-25 21:48 UTC, rlucioni commented on course_discovery/settings/base.py
> +RESPONSE_CACHE_TTL = 60
Doing this would require a way of finding the cache entries associated with each model. For example, when a program is saved, we'd need to know which cache keys to clear and/or set. In theory, we could do this by crafting request objects and passing them to the function Django uses to construct the view cache keys. Not pretty.

2017-04-26 15:21 UTC, rlucioni commented
@mikedikan @clintonb @MatthewPiatetsky what are your thoughts on starting small and introducing simple, TTL-based caching for the programs endpoint as shown here? Even a short TTL (e.g. 1 minute, 5 minutes) could help protect the discovery service (and by extension, other service like the LMS and ecommerce) when discovery experiences significant throughput spikes.

2017-04-26 15:34 UTC, mikedikan commented
I'd be fine with a 1 minute TTL - we just should make it clear to our django admin users (tatiana especially)

2017-04-26 15:37 UTC, rlucioni commented
@mikedikan sure. We could even add a simple cache-clearing view like the one @clintonb implemented for the credentials service, so that we have a way to clear the cache in case of emergencies. Though that doesn't seem as critical if we're only using 1 to 5 minute TTLs.

2017-04-26 15:51 UTC, MatthewPiatetsky commented
for 1 minute I don't think we need to be able to clear it

2017-04-26 16:01 UTC, clintonb requested changes

2017-04-26 16:01 UTC, clintonb commented on course_discovery/apps/api/v1/views/programs.py
> +    @method_decorator(cache_page(settings.RESPONSE_CACHE_TTL))
How does this work for authenticated, non-authenticated, and error responses? 

https://www.technomancy.org/python/django-cache_page-useless/

We should use drf-extensions to avoid these issues: https://chibisov.github.io/drf-extensions/docs/#caching

2017-04-26 18:13 UTC, rlucioni commented on course_discovery/apps/api/v1/views/programs.py
> +    @method_decorator(cache_page(settings.RESPONSE_CACHE_TTL))
@clintonb what I've got here handles authentication fine, but it doesn't give us the option to skip caching of error responses, nor does it provide us with many of the tools drf-extensions provides (e.g., key functions). I will convert this to using drf-extensions.

2017-04-26 18:47 UTC, rlucioni commented
@clintonb updated to use drf-extensions, which provides a variety of tools we can use to implement response caching. This change now adds caching with a short 1 minute TTL for the ProgramViewSet's list and retrieve actions. Error responses are not cached. This will provide some protection against significant increases in throughput. We can build on this later to add a longer TTL and invalidation on model changes.

2017-04-26 19:09 UTC, rlucioni commented
Also, one point of clarification: we don't yet have a Memcached cluster configured for discovery. The plan is to move ahead with this change and use in-memory, per-worker caching while work with @feanil to write the Terraform necessary to provision ourselves an ElastiCache Memcached cluster. Once that's done, we should be able to apply the same patterns to other services which need a Memcached cluster.

2017-04-26 19:24 UTC, rlucioni commented
Terraform PR to provision ElastiCache clusters is taking shape at https://github.com/edx-ops/terraform/pull/415.

2017-04-26 19:53 UTC, clintonb approved these changes

2017-04-26 20:27 UTC, rlucioni commented
@clintonb thanks for the review. I've added some changes to make sure that we're using memcached when running tests, and modified tests to verify that we're actually using the cache as expected.

2017-04-26 20:34 UTC, clintonb approved these changes

2017-04-26 20:34 UTC, rlucioni commented
I'm not sure what to make of these [defaults](https://github.com/edx/configuration/blob/master/playbooks/roles/discovery/defaults/main.yml#L46-L52) in the configuration repo. Unless they're overridden in config-secure so that we're using an in-memory cache, I don't think I can deploy these changes without breaking things.

2017-04-27 17:23 UTC, rlucioni commented
Rather than make a config change to use per-worker, in-memory caches, then another to switch to memcached, I'm going to hold off on merging this until Terraform from https://github.com/edx-ops/terraform/pull/415 is applied and config updates in https://github.com/edx/edx-internal/pull/57 are merged and deployed.

2017-04-28 17:00 UTC, merged