[DO NOT MERGE][WIP][LEARNER-687] Import course instructors' data from the LMS
openedx/course-discovery pull request #867
Opened 2017-05-02 11:56 UTC by marjev

### Reviewers:
@edx/helio 

### JIRA ticket:
https://openedx.atlassian.net/browse/LEARNER-687

### Related PRs:
https://github.com/edx/edx-platform/pull/14986

# To-do:
- [ ] Write tests
- [ ] Figure out a way to provide instructor's UUID

2017-05-02 12:06 UTC, clintonb requested changes

2017-05-02 12:06 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> -    instructors = serializers.SerializerMethodField(help_text='This field is deprecated. Use staff.')
This field was deprecated for a reason. Why are you restoring it?

2017-05-02 12:23 UTC, marjev commented on course_discovery/apps/api/serializers.py
> -    instructors = serializers.SerializerMethodField(help_text='This field is deprecated. Use staff.')
To differentiate between staff members and instructors.

Each time a `refresh_course_metadata` command is ran, staff field is cleared and updated. To refresh instructors' data in the same manner, I planned to restore this field.

Is there a better way to handle this?

2017-05-02 12:36 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> -    instructors = serializers.SerializerMethodField(help_text='This field is deprecated. Use staff.')
Do we need that separation? I would prefer to mimic the edx.org behavior as much as possible. We do not make such a separation there.

2017-05-02 12:58 UTC, marjev commented on course_discovery/apps/api/serializers.py
> -    instructors = serializers.SerializerMethodField(help_text='This field is deprecated. Use staff.')
edx.org only displays the staff members on the Program marketing page, but the WL site uses both the staff member and the instructors.

If we decide to keep the data in a single Many2Many field (staff), we would have to handle the refreshing of the course metadata, since the field is currently cleared before being filled again. This is OK now, because there's a single source of data (Marketing API). But, how would we handle the case when both Marketing API and LMS Courses API provide the data during the execution of `refresh_course_metadata` for the same course?

2017-05-03 09:43 UTC, marjev commented
@clintonb I've addressed the comment you left. Could you please take another look to verify that this is the way to go?

2017-06-20 10:25 UTC, closed without merging