Import courses from metadata to publisher app.
openedx/course-discovery pull request #889
Opened 2017-05-12 11:19 UTC by awais786

WIP:

https://openedx.atlassian.net/browse/ECOM-7809

2017-05-15 12:42 UTC, waheedahmed requested changes

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/dataloader/__init__.py
> +__author__ = 'apple'
Remove this.

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/management/__init__.py
> +__author__ = 'apple'
Remove this.

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/management/commands/__init__.py
> +__author__ = 'apple'
Remove this.

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/dataloader/create_courses.py
> +        return False
Return `None` instead `False`

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/dataloader/create_courses.py
> +        return False
Same here, return `None` instead `False`

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/dataloader/create_courses.py
> +        return False
Same here, return `None` instead `False`

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/dataloader/create_courses.py
> +        # create or update all metadata course runs.
Here you are creating only one course-run against the course but from your comment it looks like a course can have multiple course runs, is that right?

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/dataloader/create_courses.py
> +    # create or update all metadata course runs.
*seats

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/management/commands/import_metadata_courses.py
> +            help='To this id courses will be downloaded.'
*Imported

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/management/commands/import_metadata_courses.py
> +            help='The Primary key value starting id to download the courses.'
*import

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/management/commands/tests/__init__.py
> +__author__ = 'apple'
Remove this.

2017-05-15 12:42 UTC, waheedahmed commented on course_discovery/apps/publisher/models.py
> +    card_image_url = models.URLField(null=True, blank=True, verbose_name='canonical course run image')
Instead of downloading and saving the files, can't we use this field and Image field both?

2017-05-15 13:46 UTC, awais786 commented on course_discovery/apps/publisher/dataloader/create_courses.py
> +        # create or update all metadata course runs.
We just need to create most recent course-run. Canonical one

2017-05-15 13:50 UTC, awais786 commented on course_discovery/apps/publisher/models.py
> +    card_image_url = models.URLField(null=True, blank=True, verbose_name='canonical course run image')
That can be discussed. But first we need to import this field.

2017-05-18 07:08 UTC, awais786 commented on course_discovery/apps/publisher/dataloader/create_courses.py
> +        # create or update all metadata course runs.
Comment Updated.

2017-05-18 10:46 UTC, waheedahmed approved these changes

2017-05-23 17:27 UTC, awais786 commented
@tasawernawaz @waheedahmed Please review.

2017-05-25 14:28 UTC, awais786 commented
@tasawernawaz please review.

2017-05-26 06:52 UTC, tasawernawaz approved these changes

2017-05-26 06:52 UTC, tasawernawaz commented on course_discovery/apps/publisher/dataloader/create_courses.py
> +    # add default organization roles into course-user-roles
remove duplicate comments

2017-05-26 11:16 UTC, merged