Average length calculate based on canonical course run
openedx/course-discovery pull request #899
Opened 2017-05-16 12:55 UTC by ahsan-ul-haq

LEARNER-578

2017-05-18 13:56 UTC, tasawernawaz approved these changes

2017-05-18 14:19 UTC, schenedx requested changes
Please consider my suggestion. If my suggestion is not clear, message me.

2017-05-18 14:19 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +        for course in self.courses.all():
I am glad you are thinking about the excluded_course_run case.
What if canonical_course_run is excluded, instead of not using it, shouldn't we choose another course_run from the course? It makes it slightly complicated. But I feel we should protected the system with that logic.

2017-05-18 20:51 UTC, ahsan-ul-haq commented on course_discovery/apps/course_metadata/models.py
> +        for course in self.courses.all():
Canonical course run is the current run of the course, I don't think it will make sense to do the calculation based on previous or future course runs. So if canonical course run is excluded the average length still will be calculated based on the other course runs in the program.

2017-05-19 14:07 UTC, schenedx commented on course_discovery/apps/course_metadata/models.py
> +        for course in self.courses.all():
Got it. Thanks for the response

2017-05-19 14:07 UTC, schenedx approved these changes
👍

2017-05-20 09:33 UTC, merged