Upgrade discovery service to django 1.11.1
openedx/course-discovery pull request #911
Opened 2017-05-23 11:59 UTC by ahsan-ul-haq

LEARNER-947

2017-05-24 13:01 UTC, clintonb commented on course_discovery/apps/api/tests/test_views.py
> +from django.core.urlresolvers import reverse_lazy
Why are you changing this everywhere? There is no mention of this change in [the release notes](https://docs.djangoproject.com/en/1.11/releases/1.11/).

2017-06-12 13:21 UTC, clintonb commented on requirements/base.txt
> -git+https://github.com/edx/django-sortedm2m.git@1.3.4#egg=django-sortedm2m==1.3.4
Remember to delete this fork.

2017-06-12 13:21 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +    @ddt.data('31bb7f66-4c43-11e7-b114-b2f933d5fe66', uuid.uuid4())
Why was this changed? If `123` is not acceptable, get rid of `ddt`.

2017-06-12 13:21 UTC, clintonb commented on requirements/base.txt
> +django==1.11.2
Please follow the checklist at https://openedx.atlassian.net/wiki/display/OpenDev/Django+Upgrade+Checklist. Move this to a separate PR that we will deploy on its own.

2017-06-13 15:09 UTC, ahsan-ul-haq commented
@schenedx @clintonb @rlucioni could you please review.

2017-06-13 15:14 UTC, clintonb requested changes
Correct your commit message and PR title. This is not the Django upgrade. This is the resolution of deprecation warnings, and other preparations, for the upgrade.

2017-06-13 15:29 UTC, ahsan-ul-haq commented
@clintonb corrected the title and commit message

2017-06-13 15:30 UTC, clintonb approved these changes

2017-06-13 17:00 UTC, schenedx approved these changes
👍

2017-06-13 17:05 UTC, rlucioni commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +    def test_retrieve_not_found(self):
@ahsan-ul-haq what prompted this change? If there's a good reason to make the change, ddt is no longer used in this module, so please remove it.

2017-06-13 20:31 UTC, ahsan-ul-haq commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +    def test_retrieve_not_found(self):
The reason behind this is change is that in the newer version of Django `123` is no longer considered as valid `UUID` and the test fails in Django 1.11 with the error message that 123 is not valid UUID. I didn't notice that this is the only place where `ddt` was used so I will remove that.

2017-06-13 23:25 UTC, merged

2017-06-14 11:08 UTC, ahsan-ul-haq commented
Verified on stage