Learner-780 -Display price of only active courses on prog cert page
openedx/course-discovery pull request #929
Opened 2017-05-29 12:44 UTC by Ayub-Khan

Learner-780

**Description:**
prof cert program pages are displaying costs in the right sidebar under "price" for inactive, published runs (from years past), giving current or prospective learners confusing information.

**Expected Behavior:**
pricing in the right sidebar should display cost information associated only with current / published runs

**Acceptance Criteria:**
The desired behavior on the Prof Cert landing page is to display a price range for all course runs in the program, excluding course runs that are either unpublished or published, but whose start and end dates are in the past.

2017-05-30 14:25 UTC, schenedx approved these changes
👍

2017-05-30 18:15 UTC, ahsan-ul-haq requested changes

2017-05-30 18:15 UTC, ahsan-ul-haq commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        course_runs_same_course = factories.CourseRunFactory.create_batch(3, course=course)
Can't we use course runs created in the setup?

2017-05-31 08:47 UTC, Ayub-Khan commented on course_discovery/apps/course_metadata/tests/test_models.py
> +        course_runs_same_course = factories.CourseRunFactory.create_batch(3, course=course)
yeah we could have. But this is more suitable to test the right behavior. Because course runs created in setup are all from different courses. But We get double values for single course (one from expired and one from canonical ) if there are two. So i created the test like that it tests that it tests the canonical course seats for single course course runs.

2017-05-31 08:49 UTC, ahsan-ul-haq approved these changes
👍

2017-05-31 12:04 UTC, merged

2017-05-31 15:48 UTC, schenedx commented
@Ayub-Khan Please test your changes here on course discovery stage now. And report your findings on this PR. Thank you