Vkaracic/learner 1121
openedx/course-discovery pull request #934
Opened 2017-05-30 10:08 UTC by ibrahimahmed443

2017-05-30 11:55 UTC, vkaracic commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +
Could you please add a test to verify that the filter field is actually non-nullable. For example if you would filter with `?hidden=None` it shouldn't return any results.

2017-05-30 12:53 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +
Frankly, I don't care about any values besides 0, 1, true, and false. As long as the API endpoint returns properly for those, we are fine.

2017-05-30 12:56 UTC, clintonb requested changes
Update to your commit message: `Added hidden filter to Programs API list endpoint`.

2017-05-30 12:56 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +
Please add tests with the field query string set to 0 and 1.

2017-05-30 16:27 UTC, clintonb commented on course_discovery/apps/api/filters.py
> +    hidden = django_filters.TypedChoiceFilter(
Yeah...this is too much of a hack. The first thing you should do is upgrade django-filter to the latest version to determine if the new package corrects issues with `BooleanFilter`. Also, see https://github.com/encode/django-rest-framework/issues/2122 for ideas.

2017-05-31 05:05 UTC, clintonb commented on course_discovery/apps/api/filters.py
> +    hidden = django_filters.TypedChoiceFilter(
See f624a914050aee8748b74220fc27fb51e83f4e8c.

2017-05-31 11:47 UTC, ibrahimahmed443 commented
@clintonb I fixed some issues with FilterSetMixin. Are we looking good now?

2017-05-31 12:03 UTC, clintonb commented
Squash the last four commits.

2017-06-01 12:23 UTC, clintonb approved these changes

2017-06-01 12:23 UTC, clintonb commented on course_discovery/apps/course_metadata/models.py
> +        help_text=_('Hide program on marketing site landing and search pages. This program MAY have a detail page.'))
Ideally, this should be part of the first commit.

2017-06-01 12:23 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_programs.py
> +    def test_filter_by_hidden(self):
This should be part of the last commit, which deals with API filtering.

2017-06-01 12:23 UTC, clintonb commented on course_discovery/apps/api/filters.py
> +    hidden = django_filters.BooleanFilter(name='hidden')
This belongs in the last commit.

2017-06-01 15:52 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0056_auto_20170531_0500.py
> +        migrations.AlterField(
Merge this with the migration above.

2017-06-01 15:52 UTC, clintonb commented on course_discovery/apps/course_metadata/migrations/0056_auto_20170531_0500.py
> +        migrations.AlterField(
All you need to do is move the `help_text` kwarg into the first commit.

2017-06-02 09:19 UTC, merged

2017-06-02 13:57 UTC, clintonb commented
@ibrahimahmed443 please remember to delete merged branches.