Associate Site model with Partner
openedx/course-discovery pull request #936
Opened 2017-05-31 11:22 UTC by mjfrey

Associate Site model with Partner model to allow for multi-tenant support.

LEARNER-1117

2017-05-31 11:39 UTC, vkaracic commented on course_discovery/apps/core/models.py
> +    site = models.OneToOneField(Site, null=True, blank=True)
A partner can be without a site attached to it?

2017-05-31 11:39 UTC, vkaracic commented on course_discovery/apps/publisher_comments/tests/factories.py
> -class SiteFactory(factory.DjangoModelFactory):  # pylint: disable=missing-docstring
Why the move to the upper file?

2017-05-31 11:39 UTC, mjfrey commented on course_discovery/apps/core/models.py
> +    site = models.OneToOneField(Site, null=True, blank=True)
Yes, for now, until we fix up the data.

2017-05-31 11:40 UTC, mjfrey commented on course_discovery/apps/publisher_comments/tests/factories.py
> -class SiteFactory(factory.DjangoModelFactory):  # pylint: disable=missing-docstring
Should be in core and is not specific to publisher.

2017-05-31 11:42 UTC, vkaracic commented on course_discovery/apps/core/models.py
> +    site = models.OneToOneField(Site, null=True, blank=True)
Is there a ticket for that fix? I'd like to see what data needs to be fixed, cause I might be able to do it in the same migration file.

2017-05-31 11:45 UTC, mjfrey commented on course_discovery/apps/core/models.py
> +    site = models.OneToOneField(Site, null=True, blank=True)
We can just do this manually as there will only be a handful.  Can be done via the django admin.

2017-06-04 14:39 UTC, clintonb requested changes

2017-06-04 14:39 UTC, clintonb commented on course_discovery/apps/core/admin.py
> +    search_fields = ('name', 'short_code', 'site')
This field should be in the list display. Given the handful of sites, there is no need for search.

2017-06-04 14:39 UTC, clintonb commented on course_discovery/apps/core/migrations/0004_partner_site.py
> +            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
Cascade is not good. We don't want to delete all of the data. We should disable this.

2017-06-04 14:39 UTC, clintonb commented on course_discovery/apps/core/tests/factories.py
> +    domain = factory.fuzzy.FuzzyText(suffix='.fake')
Fuzzy is deprecated. Use Faker.

2017-06-04 14:39 UTC, clintonb commented on course_discovery/apps/core/tests/factories.py
> +    class Meta(object):
No need for the parenthetical in Python 3.5.

2017-06-04 14:41 UTC, clintonb commented on course_discovery/apps/core/migrations/0004_partner_site.py
> +            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.ForeignKey.on_delete

PROTECT is what we want here.

2017-06-05 09:17 UTC, vkaracic commented
@clintonb comments addressed.

2017-06-05 13:41 UTC, clintonb approved these changes
Use Faker.

2017-06-05 13:41 UTC, clintonb commented on course_discovery/apps/core/tests/factories.py
> +    domain = factory.fuzzy.FuzzyText(suffix='.fake')
Same comment as before: Fuzzy is deprecated. Use Faker. See https://github.com/edx/credentials/blob/master/credentials/apps/core/tests/factories.py#L25-L30.

2017-06-05 13:41 UTC, clintonb commented on course_discovery/apps/core/tests/factories.py
> +    marketing_site_api_username = factory.fuzzy.FuzzyText().fuzz()
Use Faker. See https://github.com/edx/credentials/blob/master/credentials/apps/core/tests/factories.py#L33 for examples.

2017-06-05 14:45 UTC, merged