Excluded hidden programs from the typeahead endpoint
openedx/course-discovery pull request #954
Opened 2017-06-05 14:53 UTC by afzaledx

…rse_runs.

2017-06-05 15:14 UTC, clintonb commented on course_discovery/apps/api/v1/views/search.py
> +        programs = programs.filter(status=ProgramStatus.Active).exclude(hidden=True).filter(partner=partner.short_code)
`filter(partner=partner.short_code, hidden=False)`

2017-06-05 15:20 UTC, afzaledx commented on course_discovery/apps/api/v1/views/search.py
> +        programs = programs.filter(status=ProgramStatus.Active).exclude(hidden=True).filter(partner=partner.short_code)
Can I change the similar query on line 136 above for course runs as well?

2017-06-05 15:34 UTC, clintonb commented on course_discovery/apps/api/v1/views/search.py
> +        programs = programs.filter(status=ProgramStatus.Active).exclude(hidden=True).filter(partner=partner.short_code)
Probably, but it's not worth it right now. Let's focus solely on programs.

2017-06-06 10:28 UTC, afzaledx commented on course_discovery/apps/api/v1/views/search.py
> +        programs = programs.filter(status=ProgramStatus.Active).exclude(hidden=True).filter(partner=partner.short_code)
@clintonb, I tried with the filter(partner=partner.short_code, hidden=False), but the tests start failing. I reverted to the exclude() and they start passing.

2017-06-06 13:49 UTC, clintonb requested changes
Squash your commits.

2017-06-06 13:49 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        CourseRunFactory(title=title + "hidden", hidden=True, course__partner=self.partner)
This PR has nothing to do with course runs. Get rid of this.

2017-06-06 13:49 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        program_visible = ProgramFactory(title=title, hidden=False, status=ProgramStatus.Active, partner=self.partner)
There is no need to override title.

```python
program = ProgramFactory(hidden=False, status=ProgramStatus.Active, partner=self.partner)
ProgramFactory(title=program.title, hidden=True, status=ProgramStatus.Active, partner=self.partner)
```

2017-06-06 13:49 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        response = self.get_response({'q': query})
`response = self.get_response({'q': program.title})`

2017-06-06 15:56 UTC, clintonb approved these changes
Update your commit message: Excluded hidden programs from typeahead endpoint. Also, include the ticket number. Commit message guidelines are at https://openedx.atlassian.net/wiki/display/ECOM/Developer+Onboarding.

2017-06-06 15:56 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +        ProgramFactory(title=program.title, hidden=True, status=ProgramStatus.Active, partner=self.partner)
The title field is unique. Use `program.title + 'hidden'`. (Please run tests locally to avoid the long turnaround time.)

2017-06-06 21:11 UTC, merged