changes to preview tab on Dashboard
openedx/course-discovery pull request #975
Opened 2017-06-12 11:24 UTC by asadazam93

ECOM-7863

- Added a new status for "preview decline"
- Added "preview requested date" to status column
- Added "course start date" column
- Moved preview URL below the Course title
<img width="1093" alt="screen shot 2017-06-12 at 4 13 50 pm" src="https://user-images.githubusercontent.com/10988308/27031893-a0632748-4f8b-11e7-9aab-9aa45a4259c6.png">

2017-06-12 13:17 UTC, waheedahmed requested changes

2017-06-12 13:17 UTC, waheedahmed commented on course_discovery/templates/publisher/dashboard/_in_preview.html
> +                            {% elif course_run.course_run_state.preview_declined %}
I don't think this `preview_declined` property or field exist in `course_run_state` model.

2017-06-13 12:06 UTC, awais786 commented on course_discovery/apps/publisher/wrappers.py
> +        comments = Comments.objects.filter(
Use `return Comments.objects.filter(...).exists()`

2017-06-13 12:55 UTC, waheedahmed approved these changes

2017-06-13 12:56 UTC, waheedahmed commented
👍 after Awais's comment addressed.

2017-06-16 09:33 UTC, merged