Filter API data by partner
openedx/course-discovery pull request #977
Opened 2017-06-13 11:46 UTC by vkaracic

LEARNER-1119

2017-06-13 11:47 UTC, vkaracic commented
@edx/helio please review.

2017-06-13 13:51 UTC, clintonb requested changes

2017-06-13 13:51 UTC, clintonb commented on .travis/run_tests.sh
> -xvfb-run make validate
Revert.

2017-06-13 13:51 UTC, clintonb commented on course_discovery/apps/api/serializers.py
> +            'expected_learning_items', 'video', 'sponsors', 'modified', 'marketing_url', 'partner'
Why is the partner field being added to the API response?

2017-06-13 13:51 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +    def setUp(self):
Remove. This should not be necessary.

2017-06-13 13:51 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/mixins.py
> +        site = Site.objects.get_current()
Why are you doing this? Just make the `Site` object. Actually, use `PartnerFactory` to make everything.

2017-06-13 13:51 UTC, clintonb commented on course_discovery/apps/api/v1/views/courses.py
> +        partner = get_current_site(self.request).partner
`partner = self.request.site.partner`

2017-06-13 13:51 UTC, clintonb commented on course_discovery/apps/api/v1/views/courses.py
> +                    course__partner=partner
One line.

2017-06-13 13:51 UTC, clintonb commented on course_discovery/apps/api/v1/views/courses.py
> +                    course__partner=partner
One line.

2017-06-13 13:51 UTC, clintonb commented on course_discovery/apps/api/v1/views/organizations.py
> +from django.contrib.sites.shortcuts import get_current_site
You should not need this function anywhere. Use [`CurrentSiteMiddleware`](https://docs.djangoproject.com/en/1.11/ref/middleware/#django.contrib.sites.middleware.CurrentSiteMiddleware).

2017-06-13 13:51 UTC, clintonb commented on course_discovery/conf/locale/eo/LC_MESSAGES/djangojs.po
> -"POT-Creation-Date: 2017-06-09 21:46+0500\n"
If you didn't actually change any translations, there is no need to commit translation files.

2017-06-13 13:51 UTC, clintonb commented on course_discovery/apps/api/tests/test_serializers.py
> +from course_discovery.apps.api.v1.tests.test_views.mixins import PartnerMixin
The `api` module should not use code from `api.v1`. Move the shared code to `api`.

2017-06-13 13:51 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/mixins.py
> +                id=settings.DEFAULT_PARTNER_ID,
We no longer need `DEFAULT_PARTNER_ID` since everything should be filtered.

2017-06-14 10:27 UTC, vkaracic commented on course_discovery/apps/api/v1/views/courses.py
> +        partner = get_current_site(self.request).partner
I've tried that already and keep getting `'Request' object has no attribute 'site'` errors.

2017-06-14 11:24 UTC, afzaledx commented
@vkaracic the api/v1/programs/?uuids_only=1 is not filtering by partner.

2017-06-14 11:34 UTC, vkaracic commented on course_discovery/apps/api/v1/views/courses.py
> +        partner = get_current_site(self.request).partner
Never mind, works after adding the middleware.

2017-06-16 11:34 UTC, afzaledx commented
@vkaracic, have you been able to run this in a multi-site scenario? I have it setup on a sandbox with multiple cnames and sites and partners. When I hit the URLs, it only detects a single site.

I have set the SITE_ID = None in settings (base.py), and now it detects the site correctly, but some exceptions are appearing in the log. Can you take a look at it?

2017-06-20 19:14 UTC, vkaracic commented
@clintonb comments addressed!

2017-06-20 20:21 UTC, clintonb requested changes

2017-06-20 20:21 UTC, clintonb commented on .travis/run_tests.sh
> +xvfb-run make validate
Add a new line and/or revert all changes to this file.

2017-06-20 20:21 UTC, clintonb commented on course_discovery/apps/api/tests/mixins.py
> +        site = Site.objects.get_current()
Stop using `Site.objects.get_current()` for tests! Anything that relies on a global request or other global variable in tests should be avoided like the plague. Use `SiteFactory`, and update it to create a related partner (if it doesn't already).

2017-06-20 20:21 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_search.py
> +    def setUp(self):
This is not necessary.

2017-06-20 20:21 UTC, clintonb commented on course_discovery/apps/core/views.py
> +def get_database_status():
Why are you touching in this file? None of it is related to the API. If this is necessary, it should be moved to a separate pull request.

2017-06-20 20:21 UTC, clintonb commented on course_discovery/conf/locale/en/LC_MESSAGES/djangojs.po
> -"POT-Creation-Date: 2017-06-14 17:09+0500\n"
If you didn't actually touch strings, there is no need to commit translations.

2017-06-20 20:21 UTC, clintonb commented on course_discovery/settings/base.py
> -    'simple_history.middleware.HistoryRequestMiddleware',
Revert and restore the trailing comma.

2017-06-21 08:21 UTC, vkaracic commented on course_discovery/apps/core/views.py
> +def get_database_status():
It's related to the new middleware addition. The first database interaction with the new middleware is fetching the site (IIRC), not the one in this function, so [this test](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/core/tests/test_views.py#L24-L27) fails now.

2017-06-21 10:21 UTC, vkaracic commented
@clintonb comments addressed!

2017-06-21 11:11 UTC, afzaledx commented
@vkaracic @clintonb , don't we require SITE_ID = None in settings for multi tenancy to work?

2017-06-21 12:25 UTC, clintonb requested changes
Make sure that SITE_ID is not set anywhere in settings. If it is, we will have problems in production.

2017-06-21 12:25 UTC, clintonb commented on course_discovery/apps/api/tests/mixins.py
> +        Site.objects.all().delete()
Why? If this is absolutely needed, add a comment explaining why.

2017-06-21 12:25 UTC, clintonb commented on course_discovery/apps/api/tests/mixins.py
> +        self.site = SiteFactory(id=settings.SITE_ID)
We shouldn't be specifying the site in settings. Also, look at the SiteMixin in edx/ecommerce. Call SiteConfigurationFactory, and pull Site and Partner from it.

2017-06-21 12:25 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_catalogs.py
> -                with self.assertNumQueries(3):
Why was this removed?

2017-06-21 12:25 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +            actual = sorted(actual, key=lambda k: k['uuid'])
What changed to cause us to need to sort the data? This is a code smell because the data should be returned with a stable sort.

2017-06-21 12:25 UTC, clintonb commented on course_discovery/apps/core/views.py
> +def get_database_status():
Replicate what we've done for ecommerce and other services: patch the middleware. See https://github.com/edx/ecommerce/blob/master/ecommerce/core/tests/test_views.py.

2017-06-21 12:25 UTC, clintonb commented on course_discovery/apps/core/views.py
> +def get_database_status():
The boilerplate should ideally be consistent across services. Ultimately, we will move it all to a common Django app.

2017-06-21 12:47 UTC, vkaracic commented on course_discovery/apps/api/v1/tests/test_views/test_catalogs.py
> -                with self.assertNumQueries(3):
It started to behave flaky. When I add `with self.assertNumQueries(4)` I get `AssertionError: 3 != 4 : 3 queries executed, 4 expected`. When I add `with self.assertNumQueries(3)` I would get `AssertionError: 4 != 3 : 4 queries executed, 3 expected`. The query that differs is related to the `django_site` table.

2017-06-21 13:29 UTC, vkaracic commented on course_discovery/apps/api/tests/mixins.py
> +        self.site = SiteFactory(id=settings.SITE_ID)
There is no `SiteConfiguration` in Course Discovery.

2017-06-21 13:42 UTC, vkaracic commented on course_discovery/apps/api/tests/mixins.py
> +        Site.objects.all().delete()
There already was a site object in (not all) tests. I just wanted to make sure that the site that is created here is the only one. Something similar that is being done [here](https://github.com/edx/ecommerce/blob/master/ecommerce/tests/mixins.py#L244). If another site is required it could be added in the actual test case.

2017-06-21 13:52 UTC, vkaracic commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +            actual = sorted(actual, key=lambda k: k['uuid'])
The only change that could have affected this is the added filter [here](https://github.com/edx/course-discovery/pull/977/files#diff-651fda19c2550b81fbdc3c7de19a0dbbR373). I'll add an explicit `order_by` clause there and see if this ordering is still needed.

2017-06-21 14:32 UTC, vkaracic commented
@clintonb I stumbled on a problem here. When I remove `SITE_ID` I would get errors like:
```
____________________________________________________________________________ AdminTests.test_comment_detail_form _____________________________________________________________________________

self = <course_discovery.apps.publisher_comments.tests.test_admin.AdminTests testMethod=test_comment_detail_form>

    def test_comment_detail_form(self):
        """ Verify in admin panel comment detail form contain the custom modified field. """
        # pylint: disable=no-member
>       resp = self.client.get(reverse('admin:publisher_comments_comments_change', args=(self.comment.id,)))

course_discovery/apps/publisher_comments/tests/test_admin.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../venvs/discovery/lib/python3.5/site-packages/django/test/client.py:529: in get
    **extra)
../venvs/discovery/lib/python3.5/site-packages/django/test/client.py:333: in get
    return self.generic('GET', path, secure=secure, **r)
../venvs/discovery/lib/python3.5/site-packages/django/test/client.py:409: in generic
    return self.request(**r)
../venvs/discovery/lib/python3.5/site-packages/django/test/client.py:494: in request
    six.reraise(*exc_info)
../venvs/discovery/lib/python3.5/site-packages/django/utils/six.py:686: in reraise
    raise value
../venvs/discovery/lib/python3.5/site-packages/django/core/handlers/exception.py:42: in inner
    response = get_response(request)
../venvs/discovery/lib/python3.5/site-packages/django/core/handlers/base.py:244: in _legacy_get_response
    response = middleware_method(request)
../venvs/discovery/lib/python3.5/site-packages/django/contrib/sites/middleware.py:12: in process_request
    request.site = get_current_site(request)
../venvs/discovery/lib/python3.5/site-packages/django/contrib/sites/shortcuts.py:15: in get_current_site
    return Site.objects.get_current(request)
../venvs/discovery/lib/python3.5/site-packages/django/contrib/sites/models.py:67: in get_current
    return self._get_site_by_request(request)
../venvs/discovery/lib/python3.5/site-packages/django/contrib/sites/models.py:44: in _get_site_by_request
    SITE_CACHE[host] = self.get(domain__iexact=host)
../venvs/discovery/lib/python3.5/site-packages/django/db/models/manager.py:85: in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <QuerySet [<Site: example.com>]>, args = (), kwargs = {'domain__iexact': 'testserver'}, clone = <QuerySet []>, num = 0

    def get(self, *args, **kwargs):
        """
            Performs the query and returns a single object matching the given
            keyword arguments.
            """
        clone = self.filter(*args, **kwargs)
        if self.query.can_filter() and not self.query.distinct_fields:
            clone = clone.order_by()
        num = len(clone)
        if num == 1:
            return clone._result_cache[0]
        if not num:
            raise self.model.DoesNotExist(
                "%s matching query does not exist." %
>               self.model._meta.object_name
            )
E           django.contrib.sites.models.DoesNotExist: Site matching query does not exist.

../venvs/discovery/lib/python3.5/site-packages/django/db/models/query.py:385: DoesNotExist
```
If you take a look at the stacktrace you'll see that it eventually hits `Site.objects.get_current(request)`, which in turn [gets the site from either `settings.SITE_ID` or the request](https://github.com/django/django/blob/master/django/contrib/sites/models.py#L50).
On Ecommerce this seems to be done by [setting the global request variable](https://github.com/edx/ecommerce/blob/master/ecommerce/tests/mixins.py#L264) which we want to avoid here.
Any ideas how to set the site in this case?

2017-06-21 14:51 UTC, clintonb commented
See the `SiteMixin` in edx/ecommerce: https://github.com/edx/ecommerce/blob/0a614c778146cf99ac03a7b4868078ee92ae0d7a/ecommerce/tests/mixins.py#L240-L242

2017-06-29 15:32 UTC, vkaracic commented
@clintonb please review the last changes.

2017-06-29 21:11 UTC, clintonb reviewed
1. Work with @edx/devops to ensure the `SITE_ID` setting is not set in secure configuration. I have confirmed it is not set in edx/edx-internal.
2. Resolve the sorting question.
3. Squash your commits.

2017-06-29 21:11 UTC, clintonb commented on course_discovery/apps/api/tests/mixins.py
> +        self.site = SiteFactory(domain=domain, name='Test server')
Don't override fields unless you actually need to. Ditch the `name` kwarg.

2017-06-29 21:11 UTC, clintonb commented on course_discovery/apps/api/tests/mixins.py
> +        domain = 'testserver'
Nit: testserver.fake

Use a domain name that is obviously fake and cannot be confused with Django's defaults.

2017-06-29 21:11 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +            actual = sorted(actual, key=lambda k: k['uuid'])
Any update on this? We should have a defined, stable, sort. Tests should not need to sort the results.

2017-06-29 21:11 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +@override_settings(SITE_ID=1)
Why is this necessary? You probably want the following in `SiteMixin.setUp()`:

```python
domain = 'testserver.fake'
self.client = self.client_class(SERVER_NAME=domain)
```

See the following in edx/ecommerce:
* https://github.com/edx/ecommerce/blob/3873cad9fdbd846f3ede7077dd6bc4d5ae6fa724/ecommerce/tests/mixins.py#L241-L242
* https://github.com/edx/ecommerce/blob/57bcc22b5337a86e4cff3baa75cf6aeb18bcd331/ecommerce/tests/testcases.py

2017-06-29 21:11 UTC, clintonb commented on course_discovery/apps/publisher/api/serializers.py
> +            request = self.context.get('request')
What happens if this returns `None`? It may be best to use `self.context['request']` and make the failure more obvious.

2017-06-29 21:11 UTC, clintonb commented on course_discovery/apps/publisher/api/serializers.py
> +        request = self.context.get('request')
Same comment as above. Use `self.context['request']`.

2017-06-29 21:11 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_serializers.py
>          self.request = RequestFactory()
`RequestFactory()` returns a `RequestFactory`. `RequestFactory().get('')` will return a `Request`. It will be best if you simply create `self.request` in `SiteMixin` so that all tests benefit. See https://github.com/edx/ecommerce/blob/3873cad9fdbd846f3ede7077dd6bc4d5ae6fa724/ecommerce/tests/mixins.py#L261-L263.

2017-06-29 21:11 UTC, clintonb commented on course_discovery/apps/publisher/api/tests/test_serializers.py
>          self.request = RequestFactory()
Same as above.

2017-06-30 13:21 UTC, vkaracic commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +@override_settings(SITE_ID=1)
I don't think that will work in this case since this is a selenium test where ``self.client`` isn't used at all.

2017-06-30 14:17 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +@override_settings(SITE_ID=1)
Add the following to your `setUp()`:

```python
self.site.domain = self.live_server_url.strip('http://')
self.site.save()
```

This will create a `Site` corresponding to the hostname used by the live server.

2017-07-03 11:19 UTC, feanil commented
@vkaracic @clintonb `SITE_ID` is not set in any configuration.  It looks like it was never something that ansible knew about.  https://github.com/edx/configuration/search?utf8=%E2%9C%93&q=SITE_ID&type=

It's not a configuration we could override it looks like.

2017-07-03 13:26 UTC, vkaracic commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +            actual = sorted(actual, key=lambda k: k['uuid'])
I've spent the better half of today trying to understand why this happens and I still can't figure out. I've tried adding a `order_by` clause to the query on the serializer, that didn't work. I've tried adding it to both serializer query and the query in the test which also didn't work. 
Tried casting them to lists in the assertion, didn't work. Tried removing all the organizations in the `setUp`, didn't work. Tried adding a `.filter(partner=self.partner)` in the [couple](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/api/v1/tests/test_views/test_organizations.py#L68) of [places](https://github.com/edx/course-discovery/blob/master/course_discovery/apps/api/v1/tests/test_views/test_organizations.py#L98) where Organizations are retrieve in the test, that didn't work either.

What's strange is that when I tried casting them to lists, I would run only the `test_organizations.py` test file and all the tests would pass, and my first thought was that it must be somehow related to Django's lazy evaluation, but when running the whole test suite they would fail (because of different order of objects), so I was back to the drawing board.

I'll need some help with this. Can you take a quick look, please?

2017-07-05 12:39 UTC, vkaracic commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +            actual = sorted(actual, key=lambda k: k['uuid'])
@clintonb ping ^

2017-07-05 15:16 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +            actual = sorted(actual, key=lambda k: k['uuid'])
Try adding the following to `assert_list_uuid_filter`: `organizations = sorted(organizations, key=lambda o: o.created)`

2017-07-06 08:16 UTC, vkaracic commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +            actual = sorted(actual, key=lambda k: k['uuid'])
That doesn't work either.

2017-07-06 17:31 UTC, clintonb approved these changes
Digging into that sorting issue will take more time than I have. I recommend sorting in the specific test, and adding a comment explaining the issue.

2017-07-07 10:08 UTC, vkaracic commented
@marjev found a more appropriate assertion for our issue. @clintonb please take a final(ish) look :)

2017-07-07 12:57 UTC, clintonb commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +        self.assertCountEqual(actual, serializer_data)
I disagree with this change. I would be more comfortable with you sorting the data and leaving a comment explaining why. Simply looking at the number of items doesn't validate the correct data is actually returned. If I modified the endpoint to simply return an array of empty dicts this test would pass.

2017-07-07 13:19 UTC, vkaracic commented on course_discovery/apps/api/v1/tests/test_views/test_organizations.py
> +        self.assertCountEqual(actual, serializer_data)
Actually the name of the assertion is misleading. [ `Test that sequence first contains the same elements as second, regardless of their order.` ](https://docs.python.org/3.2/library/unittest.html#unittest.TestCase.assertCountEqual)

2017-07-07 14:04 UTC, merged