upgrade discovery service to django 1.11
openedx/course-discovery pull request #986
Opened 2017-06-15 11:30 UTC by ahsan-ul-haq

LEARNER-947

2017-06-15 12:30 UTC, clintonb requested changes

2017-06-15 12:30 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        mutable = self.request.POST._mutable
This is a big code smell. If times need to be parsed, update the forms to do so. Django is wisely not allowing you to touch the original data. Don't work around that.

2017-06-15 12:30 UTC, clintonb commented on course_discovery/apps/publisher/views.py
> +        mutable = self.request.POST._mutable
Same comment as above.

2017-06-16 13:02 UTC, schenedx requested changes
If we are no longer able to check the existence of HTML element, can you figure out and explain here why?

2017-06-16 13:02 UTC, schenedx commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.assertContains(response, 'value="{id}'.format(id=self.excluded_course_run.id))
Why we need to simplify the assert here? I believe the original intention for the assert is to make sure the check box is included in the HTML. With the change here, we are no longer making sure a checkbox is rendered.

2017-06-16 13:02 UTC, schenedx commented on course_discovery/apps/publisher/views.py
> -        self.request.POST['start'] = parse_datetime_field(self.request.POST.get('start'))
If we remove these, won't the data fail the condition needed to format `start` time at  course_discovery/apps/publisher/forms.py line 343?

2017-06-17 20:15 UTC, ahsan-ul-haq commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.assertContains(response, 'value="{id}'.format(id=self.excluded_course_run.id))
In the new release of Django 1.11 the HTML content does not always render the same way. For example, this HTML could be rendered as following
```
<input checked="checked" id="id_excluded_course_runs_0" name="excluded_course_runs" type="checkbox" value="{id}" />
```
and 
```
<input type="checkbox" checked="checked" name="excluded_course_runs"  id="id_excluded_course_runs_0" value="{id}" />
```
Therefore I decided to check only the ids.

2017-06-17 20:17 UTC, ahsan-ul-haq commented on course_discovery/apps/publisher/views.py
> -        self.request.POST['start'] = parse_datetime_field(self.request.POST.get('start'))
No, it won't.

2017-06-17 20:17 UTC, ahsan-ul-haq commented
@clintonb @schenedx please review.

2017-06-19 22:58 UTC, ahsan-ul-haq commented
@clintonb @schenedx please review

2017-06-20 13:05 UTC, clintonb requested changes

2017-06-20 13:05 UTC, clintonb commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.assertContains(response, 'value="{id}'.format(id=self.excluded_course_run.id))
At the very least use a regex, BeautifulSoup, or some other mechanism to ensure you have the correct element (e.g. based on ID). As is, this test seems like a potential source of flakiness should the UI ever changed. In fact, if we had done proper HTML parsing when this test was first written, we wouldn't be having this conversation now.

2017-06-20 13:05 UTC, clintonb commented on course_discovery/apps/publisher/forms.py
> +    def clean_start(self):
This is not necessary. `DateTimeField` does parsing already. See https://docs.djangoproject.com/en/1.11/ref/forms/fields/#datetimefield.

2017-06-20 13:05 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> -            '<select class="field-input input-select" id="id_organization" name="organization" required>'
Same comment as above. Use an HTML parser.

2017-06-20 13:05 UTC, clintonb commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertNotContains(response, 'class="studio-link"')
Use an HTML parse for the entire file.

Unrelated: holy cow! 3300 lines of test code seems a bit much.

2017-06-20 13:05 UTC, clintonb commented on requirements/base.txt
> +django==1.11.2
None of the changes you've made are specific to Django 1.11. They are backward-compatible with Django 1.10. It will be much safer if we do the actual Django upgrade in its own commit that we can safely deploy by itself. See https://openedx.atlassian.net/wiki/display/OpenDev/Django+Upgrade+Checklist.

2017-06-20 17:09 UTC, schenedx commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.assertContains(response, 'value="{id}'.format(id=self.excluded_course_run.id))
@ahsan-ul-haq I agree what @clintonb is saying. Let's use BeautifulSoup to parse the html elements and asserts base on those.
The changes here would make the testing less rigorous, hence allow the code to be broken undetected.

2017-06-20 17:10 UTC, schenedx commented on requirements/base.txt
> +django==1.11.2
I don't know about that tho. If Ahsan upgraded to django 1.11 directly and merged without his changes in here, won't we suffer from flaky tests at least?

2017-06-20 17:36 UTC, clintonb commented on requirements/base.txt
> +django==1.11.2
I'm advocating for merging all of the changes except this one line. Release those changes. Run another release with only this Django upgrade.

2017-06-20 18:06 UTC, schenedx commented on requirements/base.txt
> +django==1.11.2
@clintonb Ah.. Thank you for the explanation. I agree with your proposed plan.

2017-06-21 16:30 UTC, ahsan-ul-haq commented
@clintonb made the suggested change

2017-06-21 16:34 UTC, schenedx requested changes
Please improve the strength of the test validations by doing more asserts and checks on the HTML elements.
rest LGTM

2017-06-21 16:34 UTC, schenedx commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.assertIsNotNone(response_content.find("input", {"value": self.excluded_course_run.id}))
I believe this assert is not good enough. Can you please make sure the input is of type `checkbox` with proper html id?

2017-06-21 16:34 UTC, schenedx commented on course_discovery/apps/publisher/tests/test_views.py
> +        self.assertIsNotNone(response_content.find("select", {"id": "id_organization"}))
Again, please validate more elements on the HTML element. Like make sure the name is `organization`

2017-06-21 19:09 UTC, clintonb approved these changes
Squash your commits, and correct the commit message and PR title.

2017-06-21 19:13 UTC, schenedx approved these changes
👍

2017-06-21 19:46 UTC, rlucioni commented
@doctoryes and I glanced at this in the context of a separate conversation and noticed that the version of DRF being installed remains at 3.3.3. 3.3.3 was only [tested up to Django 1.9](https://github.com/encode/django-rest-framework/blob/0c42c742290400e3ee742e77268681b6911604ed/tox.ini#L18). 3.6.3 was the first version to be tested against a stable version of Django 1.11.

Given that this project's tests pass, it seems like the parts of DRF used here are compatible with 1.11, but we should be aware that we're running DRF alongside a version of Django with which it wasn't tested (and doesn't promise to support).

2017-06-21 19:50 UTC, rlucioni commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +
Is isort requiring you to add this newline (and the ones below)? We don't typically separate direct module imports into a separate group like this.

2017-06-21 19:50 UTC, rlucioni commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +        self.assertIsNotNone(response_content.find(
We use pytest in this project. Use regular assertions when you add new tests, here and below.
```py
assert response_content.find(...) != None
```

2017-06-21 19:55 UTC, jibsheet commented
has anyone run showmigrations and sqlmigrate and examined what will change in this upgrade?

2017-06-21 20:40 UTC, ahsan-ul-haq commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +
yes seemingly isort require me to do so.

2017-06-21 21:27 UTC, rlucioni commented on course_discovery/apps/course_metadata/tests/test_admin.py
> +
This isn't a big deal, but could you try pushing up a commit without these newlines? Our version of isort is pinned and it shouldn't suddenly start requiring different (and unwanted) behavior.

2017-06-22 13:34 UTC, merged

2017-06-22 13:35 UTC, clintonb commented
You didn't fix your commit message.

2017-06-22 13:36 UTC, ahsan-ul-haq commented
@clintonb oh missed that