Use set comprehension instead of list comprehension when collecting C…
openedx/course-discovery pull request #999
Opened 2017-06-19 20:14 UTC by douglashall

…ourse model primary keys.

This is an attempt to fix an issue we are seeing with unreliable search results.

ENT-444

2017-06-19 20:17 UTC, clintonb requested changes
Have you tested this locally? I fail to see how this fixes anything. Databases don't usually care how many times a clause is met; they will only return one row.

2017-06-19 20:20 UTC, douglashall commented
@clintonb Agreed that it shouldn't matter, but technically this should be a set comprehension and not a list comprehension. Do you see any downsides to making this change? If not, I'd like to roll this out to see if it has any affect on the issue.

Unfortunately I am unable to currently reproduce the search flakiness issue locally (waiting on DevOps for a snapshot of PROD discovery elasticsearch).

2017-06-19 20:24 UTC, clintonb commented
There are no downsides to deploying, but there are no upsides either. It's a change we know won't fix anything. Why would we exert the resources to deploy it?

2017-06-19 20:26 UTC, douglashall commented
@clintonb Sometimes life surprises you when you least expect it. Do you see deploying the discovery service as something that takes a lot of resources?

2017-06-20 12:18 UTC, mattdrayer commented on course_discovery/apps/course_metadata/models.py
> +        logger.info('Course search query {query} returned the following ids: {course_ids}'.format(
Rather than remove, maybe we can make it a configuration thing so we can turn on/off when further troubleshooting is needed?

2017-06-20 13:57 UTC, douglashall commented
@mattdrayer Thanks for the suggestion. I have added the waffle switch.

2017-06-20 14:06 UTC, mattdrayer commented
Thanks!  👍 -- good to go after we've got all the checks passing

2017-06-20 17:01 UTC, merged

2017-06-20 17:27 UTC, clintonb commented
Please remember to remove this once your investigation is complete.

2017-06-20 17:33 UTC, douglashall commented
@clintonb Will do. As expected, the set comprehension had no effect, but the logging proves that our problem lies with the elasticsearch query. I'm getting back completely different result sets with each query to elasticsearch.

2017-06-20 17:41 UTC, mattdrayer commented
Possible explanation: https://github.com/elastic/elasticsearch/issues/11037